### ISSUE TITLE
2.0.12: Fatal error: Uncaught InvalidArgumentException: Could not get file storage

### ISSUE THREAD

**Issue by fisharebest** [vimeo/psalm#1005]
```
$ psalm --version
Psalm dev-master@679f4894a92cb8d36709ed82b5e13af52bf64dbc
$ psalm --threads=1 --debug-by-line --no-cache

[...snip...]

    checking ./routes/web.php
Fatal error: Uncaught InvalidArgumentException: Could not get file storage for /users/gr4376/projects/webtrees/./routes/web.php in /Users/gr4376/.composer/vendor/vimeo/psalm/src/Psalm/Provider/FileStorageProvider.php:36
Stack trace:
#0 /Users/gr4376/.composer/vendor/vimeo/psalm/src/Psalm/Checker/FileChecker.php(102): Psalm\Provider\FileStorageProvider->get('/users/gr4376/p...')
#1 /Users/gr4376/.composer/vendor/vimeo/psalm/src/Psalm/Checker/Statements/Expression/IncludeChecker.php(126): Psalm\Checker\FileChecker->analyze(Object(Psalm\Context), false, NULL)
#2 /Users/gr4376/.composer/vendor/vimeo/psalm/src/Psalm/Checker/Statements/ExpressionChecker.php(496): Psalm\Checker\Statements\Expression\IncludeChecker::analyze(Object(Psalm\Checker\StatementsChecker), Object(PhpParser\Node\Expr\Include_), Object(Psalm\Context), NULL)
#3 /Users/gr4376/.composer/vendor/vimeo/psalm/src/Psalm/Checker/Statements/Expression/AssignmentChecker.php(131): Psalm\Checker\Statements\ExpressionChecker::analyze(Object(Psalm\Checker\StatementsChecke in /Users/gr4376/.composer/vendor/vimeo/psalm/src/Psalm/Provider/FileStorageProvider.php on line 36
```

If you want to see the code that triggers this exception, you can get it from:
`git clone https://github.com/fisharebest/webtrees`.

**Comment by muglug** [comment]
Thanks, should be good now.

**Comment by fisharebest** [comment]
That fixes it.

Thanks!
