### ISSUE TITLE
[PHP 8.3] `Psalm\Storage\MethodStorage::$unused_docblock_params` is dynamic (?)

### ISSUE THREAD

**Issue by weirdan** [vimeo/psalm#10137]
```
Uncaught RuntimeException: PHP Error: Creation of dynamic property Psalm\Storage\MethodStorage::$unused_docblock_params is deprecated in /home/weirdan/src/psalm/psalm/src/Psalm/Internal/Fork/Pool.php:377 for command with CLI args "./psalm" in /home/weirdan/src/psalm/psalm/src/Psalm/Internal/ErrorHandler.php:75
Stack trace:
#0 [internal function]: Psalm\Internal\ErrorHandler::Psalm\Internal\{closure}()
#1 /home/weirdan/src/psalm/psalm/src/Psalm/Internal/Fork/Pool.php(377): unserialize()
#2 /home/weirdan/src/psalm/psalm/src/Psalm/Internal/Fork/Pool.php(432): Psalm\Internal\Fork\Pool->readResultsFromChildren()
#3 /home/weirdan/src/psalm/psalm/src/Psalm/Internal/Codebase/Scanner.php(384): Psalm\Internal\Fork\Pool->wait()
#4 /home/weirdan/src/psalm/psalm/src/Psalm/Internal/Codebase/Scanner.php(280): Psalm\Internal\Codebase\Scanner->scanFilePaths()
#5 /home/weirdan/src/psalm/psalm/src/Psalm/Codebase.php(505): Psalm\Internal\Codebase\Scanner->scanFiles()
#6 /home/weirdan/src/psalm/psalm/src/Psalm/Internal/Analyzer/ProjectAnalyzer.php(545): Psalm\Codebase->scanFiles()
#7 /home/weirdan/src/psalm/psalm/src/Psalm/Internal/Cli/Psalm.php(378): Psalm\Internal\Analyzer\ProjectAnalyzer->check()
#8 /home/weirdan/src/psalm/psalm/psalm(9): Psalm\Internal\Cli\Psalm::run()
#9 {main}
(Psalm 5.x-dev@9bc98ecd47a4b83a663783c5a4744d48605d3eba crashed due to an uncaught Throwable)
```

Not sure what's going on here, as `MethodStorage` extends `FunctionLikeStorage`, and that class does have `$unused_docblock_params` property defined. So far this crash happened only once, and disappeared after cache clear.

**Comment by weirdan** [comment]
This appears to happen when switching between `5.x` and `master` branches. `master` has `$unused_docblock_params` removed, so we must somehow be getting a `5.x` object from one of the child processes.

**Comment by orklah** [comment]
Most probably a cache thing. You generated the cache from master then ran on 5.x. Psalm deserialize the MethodStorage object and is left with an invalid state
