### ISSUE TITLE
Uncaught Psalm\Exception\TypeParseTreeException: Misplaced brackets

### ISSUE THREAD

**Issue by danherd** [vimeo/psalm#1026]
Just installed this (following the quickstart [here](https://getpsalm.org/quickstart)) and my first output upon running it on our codebase is the following:

```
vagrant@vagrant:/vagrant$ ./vendor/bin/psalm
Scanning files...
PHP Fatal error:  Uncaught Psalm\Exception\TypeParseTreeException: Misplaced brackets in /vagrant/vendor/vimeo/psalm/src/Psalm/Type.php:412
Stack trace:
#0 /vagrant/vendor/vimeo/psalm/src/Psalm/Type.php(119): Psalm\Type::getTypeFromTree(Object(Psalm\Type\ParseTree\MethodTree), false, Array)
#1 /vagrant/vendor/vimeo/psalm/src/Psalm/Visitor/DependencyFinderVisitor.php(678): Psalm\Type::parseTokens(Array)
#2 /vagrant/vendor/vimeo/psalm/src/Psalm/Visitor/DependencyFinderVisitor.php(200): Psalm\Visitor\DependencyFinderVisitor->registerClassLike(Object(PhpParser\Node\Stmt\Class_))
#3 /vagrant/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(200): Psalm\Visitor\DependencyFinderVisitor->enterNode(Object(PhpParser\Node\Stmt\Class_))
#4 /vagrant/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(91): PhpParser\NodeTraverser->traverseArray(Array)
#5 /vagrant/vendor/vimeo/psalm/src/Psalm/Scanner/FileScanner.php(86): PhpParser\NodeTraverser->traverse(Array)
#6 /vagrant/vendor/vimeo/psalm/src/Psalm/Codebase/Scanner.php(568): Psa in /vagrant/vendor/vimeo/psalm/src/Psalm/Type.php on line 412

Fatal error: Uncaught Psalm\Exception\TypeParseTreeException: Misplaced brackets in /vagrant/vendor/vimeo/psalm/src/Psalm/Type.php:412
Stack trace:
#0 /vagrant/vendor/vimeo/psalm/src/Psalm/Type.php(119): Psalm\Type::getTypeFromTree(Object(Psalm\Type\ParseTree\MethodTree), false, Array)
#1 /vagrant/vendor/vimeo/psalm/src/Psalm/Visitor/DependencyFinderVisitor.php(678): Psalm\Type::parseTokens(Array)
#2 /vagrant/vendor/vimeo/psalm/src/Psalm/Visitor/DependencyFinderVisitor.php(200): Psalm\Visitor\DependencyFinderVisitor->registerClassLike(Object(PhpParser\Node\Stmt\Class_))
#3 /vagrant/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(200): Psalm\Visitor\DependencyFinderVisitor->enterNode(Object(PhpParser\Node\Stmt\Class_))
#4 /vagrant/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(91): PhpParser\NodeTraverser->traverseArray(Array)
#5 /vagrant/vendor/vimeo/psalm/src/Psalm/Scanner/FileScanner.php(86): PhpParser\NodeTraverser->traverse(Array)
#6 /vagrant/vendor/vimeo/psalm/src/Psalm/Codebase/Scanner.php(568): Psa in /vagrant/vendor/vimeo/psalm/src/Psalm/Type.php on line 412
```

PHP version:

`PHP 7.0.32-2+ubuntu16.04.1+deb.sury.org+1 (cli) (built: Oct 15 2018 11:36:52) ( NTS )`

Any more info required - just ask!

**Comment by muglug** [comment]
Would you mind running with `--debug-by-line` to figure out where the error's coming from?

**Comment by muglug** [comment]
Realised it must be from a badly-formatted `@property` block in a file
