### ISSUE TITLE
Invalid storage exception when UndefinedClass is suppressed

### ISSUE THREAD

**Issue by joksnet** [vimeo/psalm#104]
I getting the following exception:

```
Fatal error: Uncaught exception 'UnexpectedValueException' with message 'Invalid storage for <ns>\actioninterface' in /home/vagrant/.config/composer/vendor/vimeo/psalm/src/Psalm/Checker/InterfaceChecker.php:90
Stack trace:
#0 /home/vagrant/.config/composer/vendor/vimeo/psalm/src/Psalm/Checker/ClassLikeChecker.php(271): Psalm\Checker\InterfaceChecker::getParentInterfaces('<NS>...')
#1 /home/vagrant/.config/composer/vendor/vimeo/psalm/src/Psalm/Checker/FileChecker.php(304): Psalm\Checker\ClassLikeChecker->visit()
#2 /home/vagrant/.config/composer/vendor/vimeo/psalm/src/Psalm/Checker/ProjectChecker.php(569): Psalm\Checker\FileChecker->visit()
#3 /home/vagrant/.config/composer/vendor/vimeo/psalm/src/Psalm/Checker/ProjectChecker.php(290): Psalm\Checker\ProjectChecker->visitFile('/home/vagrant/k...', Array)
#4 /home/vagrant/.config/composer/vendor/vimeo/psalm/src/Psalm/Checker/ProjectChecker.php(242): Psalm\Checker\ProjectChecker->visitFiles()
#5 /home/vagrant/.config/composer/vendor/vimeo/psalm/b in /home/vagrant/.config/composer/vendor/vimeo/psalm/src/Psalm/Checker/InterfaceChecker.php on line 90
```

Config used:
```xml
<?xml version="1.0"?>
<psalm name="Test">
    <projectFiles>
        <directory name="src" />
    </projectFiles>

    <issueHandlers>
        <UndefinedClass errorLevel="suppress" />
    </issueHandlers>
</psalm>
```

File `ActionInterface` has no parent interfaces, is quite simple:

```php
use Symfony\Component\HttpFoundation\Request;

interface ActionInterface
{
    /**
     * Handle action.
     *
     * @param \Symfony\Component\HttpFoundation\Request $request
     *
     * @return \Symfony\Component\HttpFoundation\Response
     */
    public function handle(Request $request);
}
```

----

I wanted to test **psalm** in a Symfony 2 project and I was getting too many `ERROR: UndefinedClass - src/<NS>/<CLASS>.php:13 - Class or interface Symfony\Component\Form\AbstractType does not exist`.

**Comment by muglug** [comment]
@joksnet do you see this on latest master too? I [fixed an issue](https://github.com/vimeo/psalm/commit/45577f123c290d6a59616a475244653b7035edf3) last night related to loading Symfony classes.
