### ISSUE TITLE
Const inside Enum throw error

### ISSUE THREAD

**Issue by pdragun** [vimeo/psalm#10447]
Hi.
I am getting error, when const is used inside backed enum:
Example: https://psalm.dev/r/ab79d19de0

Error:
`Internal Psalm error on line 1468 - /vendor/vimeo/psalm/src/Psalm/Internal/PhpVisitor/Reflector/ClassLikeNodeScanner.php: Failed to infer case value for A`

Thanks a lot.

**Comment by pdragun** [comment]
@orklah yeah, you are correct. By bad. Example is wrong. Unfortunately even with correct syntax I still get error in my app. But for now I do not know how to reproduce it.

Anyway. Thanks for help.
```
Uncaught RuntimeException: Failed to infer case value for FOO_BAR in /srv/www/vendor/vimeo/psalm/src/Psalm/Internal/PhpVisitor/Reflector/ClassLikeNodeScanner.php:1466
Stack trace:
#0 /srv/www/vendor/vimeo/psalm/src/Psalm/Internal/PhpVisitor/Reflector/ClassLikeNodeScanner.php(738): Psalm\Internal\PhpVisitor\Reflector\ClassLikeNodeScanner->visitEnumDeclaration(Object(PhpParser\Node\Stmt\EnumCase), Object(Psalm\Storage\ClassLikeStorage), 'App\\Enum\\Foo...')
#1 /srv/www/vendor/vimeo/psalm/src/Psalm/Internal/PhpVisitor/ReflectorVisitor.php(155): Psalm\Internal\PhpVisitor\Reflector\ClassLikeNodeScanner->start(Object(PhpParser\Node\Stmt\Enum_))
#2 /srv/www/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(200): Psalm\Internal\PhpVisitor\ReflectorVisitor->enterNode(Object(PhpParser\Node\Stmt\Enum_))
#3 /srv/www/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(114): PhpParser\NodeTraverser->traverseArray(Array)
#4 /srv/www/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(223): PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Stmt\Namespace_))
#5 /srv/www/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(91): PhpParser\NodeTraverser->traverseArray(Array)
#6 /srv/www/vendor/vimeo/psalm/src/Psalm/Internal/Scanner/FileScanner.php(79): PhpParser\NodeTraverser->traverse(Array)
#7 /srv/www/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Scanner.php(554): Psalm\Internal\Scanner\FileScanner->scan(Object(Psalm\Codebase), Object(Psalm\Storage\FileStorage), false, Object(Psalm\Progress\DefaultProgress))
#8 /srv/www/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Scanner.php(782): Psalm\Internal\Codebase\Scanner->scanFile('/srv/www/src/En...', Array, true)
#9 /srv/www/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Scanner.php(428): Psalm\Internal\Codebase\Scanner->scanAPath(107, '/srv/www/src/En...')
#10 /srv/www/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Scanner.php(280): Psalm\Internal\Codebase\Scanner->scanFilePaths(1)
#11 /srv/www/vendor/vimeo/psalm/src/Psalm/Codebase.php(505): Psalm\Internal\Codebase\Scanner->scanFiles(Object(Psalm\Internal\Codebase\ClassLikes), 10)
#12 /srv/www/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/ProjectAnalyzer.php(510): Psalm\Codebase->scanFiles(10)
#13 /srv/www/vendor/vimeo/psalm/src/Psalm/Internal/Cli/Psalm.php(373): Psalm\Internal\Analyzer\ProjectAnalyzer->check('/srv/www/', true)
#14 /srv/www/vendor/vimeo/psalm/psalm(9): Psalm\Internal\Cli\Psalm::run(Array)
#15 /srv/www/vendor/bin/psalm(119): include('/srv/www/vendor...')
#16 {main}
(Psalm 5.17.0@c620f6e80d0abfca532b00bda366062aaedf6e5d crashed due to an uncaught Throwable)
```
