### ISSUE TITLE
Uncaught Exception: UnexpectedValueException Shouldn’t get a generic param here

### ISSUE THREAD

**Issue by Nyholm** [vimeo/psalm#10507]
Symfony's CI for branch 5.4 is installing `psalm/phar (dev-master d7978dc)`. That causes an issue when generate baseline (see stack trace below)
When installing `psalm/phar (5.18.0)`, it works as expected. 

```
Uncaught Exception: UnexpectedValueException Shouldn’t get a generic param here
Emitted in phar:///Users/tobias/Workspace/PHPStorm/symfony/vendor/psalm/phar/psalm.phar/src/Psalm/Internal/Analyzer/Statements/Expression/CallAnalyzer.php:350
Stack trace in the forked worker:
#0 phar:///Users/tobias/Workspace/PHPStorm/symfony/vendor/psalm/phar/psalm.phar/src/Psalm/Internal/Analyzer/Statements/Expression/Call/ArgumentAnalyzer.php(542): Psalm\Internal\Analyzer\Statements\Expression\CallAnalyzer::getFunctionIdsFromCallableArg(Object(Psalm\Internal\Analyzer\StatementsAnalyzer), Object(_HumbugBox01762676be3d\PhpParser\Node\Expr\Array_))
#1 phar:///Users/tobias/Workspace/PHPStorm/symfony/vendor/psalm/phar/psalm.phar/src/Psalm/Internal/Analyzer/Statements/Expression/Call/ArgumentAnalyzer.php(478): Psalm\Internal\Analyzer\Statements\Expression\Call\ArgumentAnalyzer::verifyExplicitParam(Object(Psalm\Internal\Analyzer\StatementsAnalyzer), Object(Psalm\Type\Union), Object(Psalm\CodeLocation), Object(_HumbugBox01762676be3d\PhpParser\Node\Expr\Array_), Object(Psalm\Context))
#2 phar:///Users/tobias/Workspace/PHPStorm/symfony/vendor/psalm/phar/psalm.phar/src/Psalm/Internal/Analyzer/Statements/Expression/Call/ArgumentAnalyzer.php(311): Psalm\Internal\Analyzer\Statements\Expression\Call\ArgumentAnalyzer::verifyType(Object(Psalm\Internal\Analyzer\StatementsAnalyzer), Object(Psalm\Type\Union), Object(Psalm\Type\Union), Object(Psalm\Type\Union), 'Symfony\\Compone...', Object(Psalm\Internal\MethodIdentifier), 0, Object(Psalm\CodeLocation), Object(_HumbugBox01762676be3d\PhpParser\Node\Expr\Array_), Object(Psalm\Context), Object(Psalm\Storage\FunctionLikeParameter), false, NULL, false, false, Object(Psalm\CodeLocation))
#3 phar:///Users/tobias/Workspace/PHPStorm/symfony/vendor/psalm/phar/psalm.phar/src/Psalm/Internal/Analyzer/Statements/Expression/Call/ArgumentAnalyzer.php(128): Psalm\Internal\Analyzer\Statements\Expression\Call\ArgumentAnalyzer::checkFunctionLikeTypeMatches(Object(Psalm\Internal\Analyzer\StatementsAnalyzer), Object(Psalm\Codebase), 'Symfony\\Compone...', Object(Psalm\Internal\MethodIdentifier), 'Symfony\\Compone...', 'Symfony\\Compone...', Object(Psalm\CodeLocation), Object(Psalm\Storage\FunctionLikeParameter), true, Object(Psalm\Type\Union), 0, 0, Object(_HumbugBox01762676be3d\PhpParser\Node\Arg), Object(Psalm\Context), Array, NULL, false, false)
#4 phar:///Users/tobias/Workspace/PHPStorm/symfony/vendor/psalm/phar/psalm.phar/src/Psalm/Internal/Analyzer/Statements/Expression/Call/ArgumentsAnalyzer.php(412): Psalm\Internal\Analyzer\Statements\Expression\Call\ArgumentAnalyzer::checkArgumentMatches(Object(Psalm\Internal\Analyzer\StatementsAnalyzer), 'Symfony\\Compone...', Object(Psalm\Internal\MethodIdentifier), 'Symfony\\Compone...', 'Symfony\\Compone...', Object(Psalm\CodeLocation), Object(Psalm\Storage\FunctionLikeParameter), 0, 0, true, Object(_HumbugBox01762676be3d\PhpParser\Node\Arg), Object(Psalm\Type\Union), Object(Psalm\Context), Array, NULL, false, false)
#5 phar:///Users/tobias/Workspace/PHPStorm/symfony/vendor/psalm/phar/psalm.phar/src/Psalm/Internal/Analyzer/Statements/Expression/CallAnalyzer.php(225): Psalm\Internal\Analyzer\Statements\Expression\Call\ArgumentsAnalyzer::checkArgumentsMatch(Object(Psalm\Internal\Analyzer\StatementsAnalyzer), Array, Object(Psalm\Internal\MethodIdentifier), Array, Object(Psalm\Storage\MethodStorage), Object(Psalm\Storage\ClassLikeStorage), NULL, Object(Psalm\CodeLocation), Object(Psalm\Context))
#6 phar:///Users/tobias/Workspace/PHPStorm/symfony/vendor/psalm/phar/psalm.phar/src/Psalm/Internal/Analyzer/Statements/Expression/Call/Method/ExistingAtomicMethodCallAnalyzer.php(137): Psalm\Internal\Analyzer\Statements\Expression\CallAnalyzer::checkMethodArgs(Object(Psalm\Internal\MethodIdentifier), Array, Object(Psalm\Internal\Type\TemplateResult), Object(Psalm\Context), Object(Psalm\CodeLocation), Object(Psalm\Internal\Analyzer\StatementsAnalyzer))
#7 phar:///Users/tobias/Workspace/PHPStorm/symfony/vendor/psalm/phar/psalm.phar/src/Psalm/Internal/Analyzer/Statements/Expression/Call/Method/AtomicMethodCallAnalyzer.php(214): Psalm\Internal\Analyzer\Statements\Expression\Call\Method\ExistingAtomicMethodCallAnalyzer::analyze(Object(Psalm\Internal\Analyzer\StatementsAnalyzer), Object(_HumbugBox01762676be3d\PhpParser\Node\Expr\MethodCall), Object(_HumbugBox01762676be3d\PhpParser\Node\Identifier), Array, Object(Psalm\Codebase), Object(Psalm\Context), Object(Psalm\Type\Atomic\TNamedObject), Object(Psalm\Type\Atomic\TNamedObject), '$badge', Object(Psalm\Internal\MethodIdentifier), Object(Psalm\Internal\Analyzer\Statements\Expression\Call\Method\AtomicMethodCallAnalysisResult), NULL)
#8 phar:///Users/tobias/Workspace/PHPStorm/symfony/vendor/psalm/phar/psalm.phar/src/Psalm/Internal/Analyzer/Statements/Expression/Call/MethodCallAnalyzer.php(102): Psalm\Internal\Analyzer\Statements\Expression\Call\Method\AtomicMethodCallAnalyzer::analyze(Object(Psalm\Internal\Analyzer\StatementsAnalyzer), Object(_HumbugBox01762676be3d\PhpParser\Node\Expr\MethodCall), Object(Psalm\Codebase), Object(Psalm\Context), Object(Psalm\Type\Union), Object(Psalm\Type\Atomic\TNamedObject), Object(Psalm\Type\Atomic\TNamedObject), false, '$badge', Object(Psalm\Internal\Analyzer\Statements\Expression\Call\Method\AtomicMethodCallAnalysisResult), NULL)
#9 phar:///Users/tobias/Workspace/PHPStorm/symfony/vendor/psalm/phar/psalm.phar/src/Psalm/Internal/Analyzer/Statements/ExpressionAnalyzer.php(111): Psalm\Internal\Analyzer\Statements\Expression\Call\MethodCallAnalyzer::analyze(Object(Psalm\Internal\Analyzer\StatementsAnalyzer), Object(_HumbugBox01762676be3d\PhpParser\Node\Expr\MethodCall), Object(Psalm\Context), true, NULL)
#10 phar:///Users/tobias/Workspace/PHPStorm/symfony/vendor/psalm/phar/psalm.phar/src/Psalm/Internal/Analyzer/Statements/ExpressionAnalyzer.php(76): Psalm\Internal\Analyzer\Statements\ExpressionAnalyzer::handleExpression(Object(Psalm\Internal\Analyzer\StatementsAnalyzer), Object(_HumbugBox01762676be3d\PhpParser\Node\Expr\MethodCall), Object(Psalm\Context), false, NULL, true, NULL, false)
#11 phar:///Users/tobias/Workspace/PHPStorm/symfony/vendor/psalm/phar/psalm.phar/src/Psalm/Internal/Analyzer/StatementsAnalyzer.php(380): Psalm\Internal\Analyzer\Statements\ExpressionAnalyzer::analyze(Object(Psalm\Internal\Analyzer\StatementsAnalyzer), Object(_HumbugBox01762676be3d\PhpParser\Node\Expr\MethodCall), Object(Psalm\Context), false, NULL, true)
#12 phar:///Users/tobias/Workspace/PHPStorm/symfony/vendor/psalm/phar/psalm.phar/src/Psalm/Internal/Analyzer/StatementsAnalyzer.php(169): Psalm\Internal\Analyzer\StatementsAnalyzer::analyzeStatement(Object(Psalm\Internal\Analyzer\StatementsAnalyzer), Object(_HumbugBox01762676be3d\PhpParser\Node\Stmt\Expression), Object(Psalm\Context), NULL)
#13 phar:///Users/tobias/Workspace/PHPStorm/symfony/vendor/psalm/phar/psalm.phar/src/Psalm/Internal/Analyzer/Statements/Block/IfElse/IfAnalyzer.php(100): Psalm\Internal\Analyzer\StatementsAnalyzer->analyze(Array, Object(Psalm\Context))
#14 phar:///Users/tobias/Workspace/PHPStorm/symfony/vendor/psalm/phar/psalm.phar/src/Psalm/Internal/Analyzer/Statements/Block/IfElseAnalyzer.php(151): Psalm\Internal\Analyzer\Statements\Block\IfElse\IfAnalyzer::analyze(Object(Psalm\Internal\Analyzer\StatementsAnalyzer), Object(_HumbugBox01762676be3d\PhpParser\Node\Stmt\If_), Object(Psalm\Internal\Scope\IfScope), Object(Psalm\Internal\Scope\IfConditionalScope), Object(Psalm\Context), Object(Psalm\Context), Array)
#15 phar:///Users/tobias/Workspace/PHPStorm/symfony/vendor/psalm/phar/psalm.phar/src/Psalm/Internal/Analyzer/StatementsAnalyzer.php(334): Psalm\Internal\Analyzer\Statements\Block\IfElseAnalyzer::analyze(Object(Psalm\Internal\Analyzer\StatementsAnalyzer), Object(_HumbugBox01762676be3d\PhpParser\Node\Stmt\If_), Object(Psalm\Context))
#16 phar:///Users/tobias/Workspace/PHPStorm/symfony/vendor/psalm/phar/psalm.phar/src/Psalm/Internal/Analyzer/StatementsAnalyzer.php(169): Psalm\Internal\Analyzer\StatementsAnalyzer::analyzeStatement(Object(Psalm\Internal\Analyzer\StatementsAnalyzer), Object(_HumbugBox01762676be3d\PhpParser\Node\Stmt\If_), Object(Psalm\Context), Object(Psalm\Context))
#17 phar:///Users/tobias/Workspace/PHPStorm/symfony/vendor/psalm/phar/psalm.phar/src/Psalm/Internal/Analyzer/FunctionLikeAnalyzer.php(283): Psalm\Internal\Analyzer\StatementsAnalyzer->analyze(Array, Object(Psalm\Context), Object(Psalm\Context), true)
#18 phar:///Users/tobias/Workspace/PHPStorm/symfony/vendor/psalm/phar/psalm.phar/src/Psalm/Internal/Analyzer/ClassAnalyzer.php(817): Psalm\Internal\Analyzer\FunctionLikeAnalyzer->analyze(Object(Psalm\Context), Object(Psalm\Internal\Provider\NodeDataProvider), Object(Psalm\Context))
#19 phar:///Users/tobias/Workspace/PHPStorm/symfony/vendor/psalm/phar/psalm.phar/src/Psalm/Internal/Analyzer/ClassAnalyzer.php(252): Psalm\Internal\Analyzer\ClassAnalyzer->analyzeClassMethod(Object(_HumbugBox01762676be3d\PhpParser\Node\Stmt\ClassMethod), Object(Psalm\Storage\ClassLikeStorage), Object(Psalm\Internal\Analyzer\ClassAnalyzer), Object(Psalm\Context), Object(Psalm\Context))
#20 phar:///Users/tobias/Workspace/PHPStorm/symfony/vendor/psalm/phar/psalm.phar/src/Psalm/Internal/Analyzer/FileAnalyzer.php(158): Psalm\Internal\Analyzer\ClassAnalyzer->analyze(Object(Psalm\Context), Object(Psalm\Context))
#21 phar:///Users/tobias/Workspace/PHPStorm/symfony/vendor/psalm/phar/psalm.phar/src/Psalm/Internal/Codebase/Analyzer.php(1103): Psalm\Internal\Analyzer\FileAnalyzer->analyze()
#22 phar:///Users/tobias/Workspace/PHPStorm/symfony/vendor/psalm/phar/psalm.phar/src/Psalm/Internal/Fork/Pool.php(156): Psalm\Internal\Codebase\Analyzer->analysisWorker(569, '/Users/tobias/W...')
#23 phar:///Users/tobias/Workspace/PHPStorm/symfony/vendor/psalm/phar/psalm.phar/src/Psalm/Internal/Codebase/Analyzer.php(294): Psalm\Internal\Fork\Pool->__construct(Object(Psalm\Config), Array, Object(Closure), Object(Closure), Object(Closure), Object(Closure))
#24 phar:///Users/tobias/Workspace/PHPStorm/symfony/vendor/psalm/phar/psalm.phar/src/Psalm/Internal/Codebase/Analyzer.php(224): Psalm\Internal\Codebase\Analyzer->doAnalysis(Object(Psalm\Internal\Analyzer\ProjectAnalyzer), 7)
#25 phar:///Users/tobias/Workspace/PHPStorm/symfony/vendor/psalm/phar/psalm.phar/src/Psalm/Internal/Analyzer/ProjectAnalyzer.php(370): Psalm\Internal\Codebase\Analyzer->analyzeFiles(Object(Psalm\Internal\Analyzer\ProjectAnalyzer), 7, false, true)
#26 phar:///Users/tobias/Workspace/PHPStorm/symfony/vendor/psalm/phar/psalm.phar/src/Psalm/Internal/Cli/Psalm.php(272): Psalm\Internal\Analyzer\ProjectAnalyzer->check('/Users/tobias/W...', false)
#27 phar:///Users/tobias/Workspace/PHPStorm/symfony/vendor/psalm/phar/psalm.phar/psalm(7): Psalm\Internal\Cli\Psalm::run(Array)
#28 /Users/tobias/Workspace/PHPStorm/symfony/vendor/psalm/phar/psalm.phar(14): require('phar:///Users/t...')
#29 /Users/tobias/Workspace/PHPStorm/symfony/vendor/bin/psalm.phar(117): include('/Users/tobias/W...')
#30 {main} in phar:///Users/tobias/Workspace/PHPStorm/symfony/vendor/psalm/phar/psalm.phar/src/Psalm/Internal/Fork/Pool.php:310
Stack trace:
#0 phar:///Users/tobias/Workspace/PHPStorm/symfony/vendor/psalm/phar/psalm.phar/src/Psalm/Internal/Fork/Pool.php(340): Psalm\Internal\Fork\Pool->readResultsFromChildren()
#1 phar:///Users/tobias/Workspace/PHPStorm/symfony/vendor/psalm/phar/psalm.phar/src/Psalm/Internal/Codebase/Analyzer.php(316): Psalm\Internal\Fork\Pool->wait()
#2 phar:///Users/tobias/Workspace/PHPStorm/symfony/vendor/psalm/phar/psalm.phar/src/Psalm/Internal/Codebase/Analyzer.php(224): Psalm\Internal\Codebase\Analyzer->doAnalysis(Object(Psalm\Internal\Analyzer\ProjectAnalyzer), 7)
#3 phar:///Users/tobias/Workspace/PHPStorm/symfony/vendor/psalm/phar/psalm.phar/src/Psalm/Internal/Analyzer/ProjectAnalyzer.php(370): Psalm\Internal\Codebase\Analyzer->analyzeFiles(Object(Psalm\Internal\Analyzer\ProjectAnalyzer), 7, false, true)
#4 phar:///Users/tobias/Workspace/PHPStorm/symfony/vendor/psalm/phar/psalm.phar/src/Psalm/Internal/Cli/Psalm.php(272): Psalm\Internal\Analyzer\ProjectAnalyzer->check('/Users/tobias/W...', false)
#5 phar:///Users/tobias/Workspace/PHPStorm/symfony/vendor/psalm/phar/psalm.phar/psalm(7): Psalm\Internal\Cli\Psalm::run(Array)
#6 /Users/tobias/Workspace/PHPStorm/symfony/vendor/psalm/phar/psalm.phar(14): require('phar:///Users/t...')
#7 /Users/tobias/Workspace/PHPStorm/symfony/vendor/bin/psalm.phar(117): include('/Users/tobias/W...')
#8 {main}
(Psalm dev-master@a75d26a3d425d183da8bef37cfc14976c8d817d6 crashed due to an uncaught Throwable)     

```

**Comment by Nyholm** [comment]
No, Im sorry for this bad issue. 

Is the psalm/phar package updated as it supposed to? I see that 
- dev-master is updated at 2023-12-10
- 5.18.0 is updated at 2023-12-16

**Comment by Nyholm** [comment]
I see now. 

This is an old bug. But since Symfony is using dev-master of psalm/phar AND because we [only update the phar package on releases](https://github.com/vimeo/psalm/blob/dcec7ac82cee0498bb9523119eb89981c9144960/.github/workflows/build-phar.yml#L3-L9) we still have this issue. 

It will be solved with PR #10504
