### ISSUE TITLE
"Could not get class storage for X"

### ISSUE THREAD

**Issue by akaDJon** [vimeo/psalm#10895]
I got error "Could not get class storage for X" with my codebase. I see many issues on github with this problem. 
My codebase has many aliases and I found solve!

I fix it in file `AssertionsFromInheritanceResolver.php`. I put getUnAliasedName function:

before: 
```php
        foreach ($inherited_classes_and_interfaces as $potential_assertion_providing_class) {
            $potential_assertion_providing_classlike_storage = $this->codebase->classlike_storage_provider->get(
                $potential_assertion_providing_class,
            );
```

after:
```php
        foreach ($inherited_classes_and_interfaces as $potential_assertion_providing_class) {
            $potential_assertion_providing_class = $this->codebase->classlikes->getUnAliasedName($potential_assertion_providing_class);

            $potential_assertion_providing_classlike_storage = $this->codebase->classlike_storage_provider->get(
                $potential_assertion_providing_class,
            );
```

**Comment by veewee** [comment]
Hello,

I am facing a similar issue in sulu, which I described and reported here:
https://github.com/sulu/sulu/issues/7523

The fix provided above solves the issue for this specific case as well.
I tried creating a simple reproducer, but cannot figure out in what specific case psalm isn't able to track it anymore.

Would you be interested in a PR (without additional tests)? 
If not : Maybe someone with broader understanding of psalm internals could take a look at what could possibly go wrong here?

**Comment by blm768** [comment]
Could this be related to #4462?

**Comment by orklah** [comment]
Can you check if it still happens with Psalm 6?

**Comment by HenkPoley** [comment]
I have some code that causes "Could not get class storage for divisionbyzeroerror in" to be emitted.

(Based on: https://github.com/HenkPoley/PhpDocBlockDoctor/blob/8cf40531118439454a6e7ab23dc680466bb68fcc/tests/fixtures/throw-class-string/ThrowClassStrings.php )

```php
<?php

class ClassName
{
    public function doubleDoubleColonActualString(): void
    {
        $foo = '\DivisionByZeroError';
        throw new $foo('failed');
    }
}
```

Online psalm merely complains about "ERROR: [InvalidStringClass](https://psalm.dev/160) - 8:15 - String cannot be used as a class"

https://psalm.dev/r/54f32014db

I'm seeing, with Psalm 6.4.0@04f312ac6ea48ba1c3e5db4d815bf6d74641c0ee on PHP 8.4.8

```
Parsing /Users/henk/PhpDocBlockDoctor/tests/fixtures/throw-class-string/PsalmBugCouldNotGetClassStorage.php
Uncaught InvalidArgumentException: Could not get class storage for divisionbyzeroerror in /Users/henk/PhpDocBlockDoctor/vendor/vimeo/psalm/src/Psalm/Internal/Provider/ClassLikeStorageProvider.php:45
Stack trace:
#0 /Users/henk/PhpDocBlockDoctor/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/ClassLikeAnalyzer.php(327): Psalm\Internal\Provider\ClassLikeStorageProvider->get('DivisionByZeroE...')
#1 /Users/henk/PhpDocBlockDoctor/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/Statements/Expression/Call/NewAnalyzer.php(210): Psalm\Internal\Analyzer\ClassLikeAnalyzer::checkFullyQualifiedClassLikeName(Object(Psalm\Internal\Analyzer\StatementsAnalyzer), 'DivisionByZeroE...', Object(Psalm\CodeLocation), 'AnotherClassNam...', 'anotherclassnam...', Array)
#2 /Users/henk/PhpDocBlockDoctor/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/Statements/ExpressionAnalyzer.php(306): Psalm\Internal\Analyzer\Statements\Expression\Call\NewAnalyzer::analyze(Object(Psalm\Internal\Analyzer\StatementsAnalyzer), Object(PhpParser\Node\Expr\New_), Object(Psalm\Context), NULL)
#3 /Users/henk/PhpDocBlockDoctor/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/Statements/ExpressionAnalyzer.php(92): Psalm\Internal\Analyzer\Statements\ExpressionAnalyzer::handleExpression(Object(Psalm\Internal\Analyzer\StatementsAnalyzer), Object(PhpParser\Node\Expr\New_), Object(Psalm\Context), false, NULL, NULL, NULL, false)
#4 /Users/henk/PhpDocBlockDoctor/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/Statements/Expression/ThrowAnalyzer.php(30): Psalm\Internal\Analyzer\Statements\ExpressionAnalyzer::analyze(Object(Psalm\Internal\Analyzer\StatementsAnalyzer), Object(PhpParser\Node\Expr\New_), Object(Psalm\Context))
#5 /Users/henk/PhpDocBlockDoctor/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/Statements/ExpressionAnalyzer.php(458): Psalm\Internal\Analyzer\Statements\Expression\ThrowAnalyzer::analyze(Object(Psalm\Internal\Analyzer\StatementsAnalyzer), Object(PhpParser\Node\Expr\Throw_), Object(Psalm\Context))
#6 /Users/henk/PhpDocBlockDoctor/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/Statements/ExpressionAnalyzer.php(92): Psalm\Internal\Analyzer\Statements\ExpressionAnalyzer::handleExpression(Object(Psalm\Internal\Analyzer\StatementsAnalyzer), Object(PhpParser\Node\Expr\Throw_), Object(Psalm\Context), false, Object(Psalm\Context), Object(PhpParser\Node\Stmt\Expression), NULL, false)
#7 /Users/henk/PhpDocBlockDoctor/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/StatementsAnalyzer.php(555): Psalm\Internal\Analyzer\Statements\ExpressionAnalyzer::analyze(Object(Psalm\Internal\Analyzer\StatementsAnalyzer), Object(PhpParser\Node\Expr\Throw_), Object(Psalm\Context), false, Object(Psalm\Context), Object(PhpParser\Node\Stmt\Expression))
#8 /Users/henk/PhpDocBlockDoctor/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/StatementsAnalyzer.php(191): Psalm\Internal\Analyzer\StatementsAnalyzer::analyzeStatement(Object(Psalm\Internal\Analyzer\StatementsAnalyzer), Object(PhpParser\Node\Stmt\Expression), Object(Psalm\Context), Object(Psalm\Context))
#9 /Users/henk/PhpDocBlockDoctor/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/FunctionLikeAnalyzer.php(508): Psalm\Internal\Analyzer\StatementsAnalyzer->analyze(Array, Object(Psalm\Context), Object(Psalm\Context), true)
#10 /Users/henk/PhpDocBlockDoctor/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/ClassAnalyzer.php(1823): Psalm\Internal\Analyzer\FunctionLikeAnalyzer->analyze(Object(Psalm\Context), Object(Psalm\Internal\Provider\NodeDataProvider), Object(Psalm\Context))
#11 /Users/henk/PhpDocBlockDoctor/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/ClassAnalyzer.php(447): Psalm\Internal\Analyzer\ClassAnalyzer->analyzeClassMethod(Object(PhpParser\Node\Stmt\ClassMethod), Object(Psalm\Storage\ClassLikeStorage), Object(Psalm\Internal\Analyzer\ClassAnalyzer), Object(Psalm\Context), Object(Psalm\Context))
#12 /Users/henk/PhpDocBlockDoctor/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/FileAnalyzer.php(197): Psalm\Internal\Analyzer\ClassAnalyzer->analyze(Object(Psalm\Context), Object(Psalm\Context))
#13 /Users/henk/PhpDocBlockDoctor/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Analyzer.php(1488): Psalm\Internal\Analyzer\FileAnalyzer->analyze()
#14 /Users/henk/PhpDocBlockDoctor/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Analyzer.php(436): Psalm\Internal\Codebase\Analyzer::analysisWorker(Object(Psalm\Config), Object(Psalm\Progress\DebugProgress), '/Users/henk/Php...')
#15 /Users/henk/PhpDocBlockDoctor/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Analyzer.php(245): Psalm\Internal\Codebase\Analyzer->doAnalysis(Object(Psalm\Internal\Analyzer\ProjectAnalyzer), 1)
#16 /Users/henk/PhpDocBlockDoctor/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/ProjectAnalyzer.php(520): Psalm\Internal\Codebase\Analyzer->analyzeFiles(Object(Psalm\Internal\Analyzer\ProjectAnalyzer), 1, false, true)
#17 /Users/henk/PhpDocBlockDoctor/vendor/vimeo/psalm/src/Psalm/Internal/Cli/Psalm.php(393): Psalm\Internal\Analyzer\ProjectAnalyzer->check('/Users/henk/Php...', true)
#18 /Users/henk/PhpDocBlockDoctor/vendor/vimeo/psalm/psalm(9): Psalm\Internal\Cli\Psalm::run(Array)
#19 /Users/henk/PhpDocBlockDoctor/vendor/bin/psalm(119): include('/Users/henk/Php...')
#20 {main}
(Psalm 6.4.0@04f312ac6ea48ba1c3e5db4d815bf6d74641c0ee crashed due to an uncaught Throwable)
```

If I add a DivisionByZeroError class to the file, my local psalm no longer gives the exception

```
class DivisionByZeroError {
}
```

The online version still doesn't like the string calling stuff: https://psalm.dev/r/c576712ed9

I must have seen code that instantiates a class based on a string like this in phpsimplesaml. 

PHP's built-in lint does not complain:

```
% php -l tests/fixtures/throw-class-string/PsalmBugCouldNotGetClassStorage.php
No syntax errors detected in tests/fixtures/throw-class-string/PsalmBugCouldNotGetClassStorage.php
```

**Comment by HenkPoley** [comment]
If you add `extends \Exception` to the DivisionByZeroError lass, online Psalm will stop complaining about it not being an exception.

Otherwise the same (wrong) behaviour: "String cannot be used as a class".

https://psalm.dev/r/fd9b489577

Be sure to note that the namespace of the class has influence.

**Comment by orklah** [comment]
InvalidStringClass is a valid issue here. Psalm doesn't allow any string to be used a class in any context.
`$a = "Test"; new $a();` isn't valid, `$a = Test::class; new $a();` is.

The doc: https://psalm.dev/docs/running_psalm/issues/InvalidStringClass/ states that there is a flag in your config if you don't want to check for this.

The "could not get class storage" issue is not normal though. 

However, this error can happen for a lot of reasons so your case may be very different from the original post. Given there is no reproducer in the original post and no recent answer for last Psalm version, I'll close this issue. Feel free to reopen one with a reproducer (either on psalm.dev or in a GH repo) for your specific case
