### ISSUE TITLE
Errors VS Code ext: and Psalm 5.x-dev

### ISSUE THREAD

**Issue by microwin7** [vimeo/psalm#10931]
```log
[Error - 12:32:17 AM] Method Psalm\Internal\LanguageServer\LanguageServer::cancelRequest() does not exist
[Error - 12:32:37 AM] Method Psalm\Internal\LanguageServer\LanguageServer::cancelRequest() does not exist
[Error - 12:32:47 AM] Method Psalm\Internal\LanguageServer\LanguageServer::cancelRequest() does not exist
[Error - 12:32:48 AM] Method Psalm\Internal\LanguageServer\LanguageServer::cancelRequest() does not exist
[Error - 12:32:48 AM] Method Psalm\Internal\LanguageServer\LanguageServer::cancelRequest() does not exist
[Error - 12:32:51 AM] Method Psalm\Internal\LanguageServer\LanguageServer::cancelRequest() does not exist
[Error - 12:32:54 AM] Method Psalm\Internal\LanguageServer\LanguageServer::cancelRequest() does not exist
[Error - 12:32:59 AM] Method Psalm\Internal\LanguageServer\LanguageServer::cancelRequest() does not exist
[Error - 12:33:55 AM] Method Psalm\Internal\LanguageServer\LanguageServer::cancelRequest() does not exist
[Error - 12:34:30 AM] Method Psalm\Internal\LanguageServer\LanguageServer::cancelRequest() does not exist
[Error - 12:34:44 AM] Method Psalm\Internal\LanguageServer\LanguageServer::cancelRequest() does not exist
[Error - 12:34:44 AM] Method Psalm\Internal\LanguageServer\LanguageServer::cancelRequest() does not exist
[Error - 12:34:57 AM] Method Psalm\Internal\LanguageServer\LanguageServer::cancelRequest() does not exist
[Error - 12:34:59 AM] Method Psalm\Internal\LanguageServer\LanguageServer::cancelRequest() does not exist
[Error - 12:35:00 AM] completion not found at 40:23
[Error - 12:35:01 AM] completion not found at 40:24
[Error - 12:35:01 AM] Method Psalm\Internal\LanguageServer\LanguageServer::cancelRequest() does not exist
[Error - 12:36:27 AM] Method Psalm\Internal\LanguageServer\LanguageServer::cancelRequest() does not exist
[Error - 12:36:33 AM] Method Psalm\Internal\LanguageServer\LanguageServer::cancelRequest() does not exist
[Error - 12:36:33 AM] Method Psalm\Internal\LanguageServer\LanguageServer::cancelRequest() does not exist
[Error - 12:36:33 AM] completion not found at 132:8
[Error - 12:36:33 AM] UnexpectedValueException: Expecting non-empty $root_file_path and $checked_file_path in /var/www/html/PHP-Utils/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Functions.php:120
Stack trace:
#0 /var/www/html/PHP-Utils/vendor/vimeo/psalm/src/Psalm/Codebase.php(1120): Psalm\Internal\Codebase\Functions->getStorage()
#1 /var/www/html/PHP-Utils/vendor/vimeo/psalm/src/Psalm/Internal/LanguageServer/Server/TextDocument.php(254): Psalm\Codebase->getMarkupContentForSymbolByReference()
#2 /var/www/html/PHP-Utils/vendor/felixfbecker/advanced-json-rpc/lib/Dispatcher.php(168): Psalm\Internal\LanguageServer\Server\TextDocument->hover()
#3 /var/www/html/PHP-Utils/vendor/vimeo/psalm/src/Psalm/Internal/LanguageServer/LanguageServer.php(199): AdvancedJsonRpc\Dispatcher->dispatch()
#4 [internal function]: Psalm\Internal\LanguageServer\LanguageServer->Psalm\Internal\LanguageServer\{closure}()
#5 /var/www/html/PHP-Utils/vendor/amphp/amp/lib/Coroutine.php(67): Generator->current()
#6 /var/www/html/PHP-Utils/vendor/amphp/amp/lib/functions.php(96): Amp\Coroutine->__construct()
#7 /var/www/html/PHP-Utils/vendor/amphp/amp/lib/functions.php(61): Amp\call()
#8 /var/www/html/PHP-Utils/vendor/vimeo/psalm/src/Psalm/Internal/LanguageServer/EmitterTrait.php(85): Amp\{closure}()
#9 /var/www/html/PHP-Utils/vendor/vimeo/psalm/src/Psalm/Internal/LanguageServer/ProtocolStreamReader.php(116): Psalm\Internal\LanguageServer\ProtocolStreamReader->emit()
#10 /var/www/html/PHP-Utils/vendor/vimeo/psalm/src/Psalm/Internal/LanguageServer/ProtocolStreamReader.php(63): Psalm\Internal\LanguageServer\ProtocolStreamReader->readMessages()
#11 [internal function]: Psalm\Internal\LanguageServer\ProtocolStreamReader->Psalm\Internal\LanguageServer\{closure}()
#12 /var/www/html/PHP-Utils/vendor/amphp/amp/lib/Coroutine.php(118): Generator->send()
#13 /var/www/html/PHP-Utils/vendor/amphp/amp/lib/Internal/Placeholder.php(149): Amp\Coroutine->Amp\{closure}()
#14 /var/www/html/PHP-Utils/vendor/amphp/amp/lib/Deferred.php(53): Amp\Promise@anonymous->resolve()
#15 /var/www/html/PHP-Utils/vendor/amphp/byte-stream/lib/ResourceInputStream.php(101): Amp\Deferred->resolve()
#16 /var/www/html/PHP-Utils/vendor/amphp/amp/lib/Loop/NativeDriver.php(327): Amp\ByteStream\ResourceInputStream::Amp\ByteStream\{closure}()
#17 /var/www/html/PHP-Utils/vendor/amphp/amp/lib/Loop/NativeDriver.php(124): Amp\Loop\NativeDriver->selectStreams()
#18 /var/www/html/PHP-Utils/vendor/amphp/amp/lib/Loop/Driver.php(138): Amp\Loop\NativeDriver->dispatch()
#19 /var/www/html/PHP-Utils/vendor/amphp/amp/lib/Loop/Driver.php(72): Amp\Loop\Driver->tick()
#20 /var/www/html/PHP-Utils/vendor/amphp/amp/lib/Loop.php(95): Amp\Loop\Driver->run()
#21 /var/www/html/PHP-Utils/vendor/vimeo/psalm/src/Psalm/Internal/LanguageServer/LanguageServer.php(372): Amp\Loop::run()
#22 /var/www/html/PHP-Utils/vendor/vimeo/psalm/src/Psalm/Internal/Cli/LanguageServer.php(417): Psalm\Internal\LanguageServer\LanguageServer::run()
#23 /var/www/html/PHP-Utils/vendor/vimeo/psalm/psalm-language-server(9): Psalm\Internal\Cli\LanguageServer::run()
#24 {main}
[Error - 12:36:33 AM] UnexpectedValueException: Expecting non-empty $root_file_path and $checked_file_path in /var/www/html/PHP-Utils/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Functions.php:120
Stack trace:
#0 /var/www/html/PHP-Utils/vendor/vimeo/psalm/src/Psalm/Codebase.php(1120): Psalm\Internal\Codebase\Functions->getStorage()
#1 /var/www/html/PHP-Utils/vendor/vimeo/psalm/src/Psalm/Internal/LanguageServer/Server/TextDocument.php(254): Psalm\Codebase->getMarkupContentForSymbolByReference()
#2 /var/www/html/PHP-Utils/vendor/felixfbecker/advanced-json-rpc/lib/Dispatcher.php(168): Psalm\Internal\LanguageServer\Server\TextDocument->hover()
#3 /var/www/html/PHP-Utils/vendor/vimeo/psalm/src/Psalm/Internal/LanguageServer/LanguageServer.php(199): AdvancedJsonRpc\Dispatcher->dispatch()
#4 [internal function]: Psalm\Internal\LanguageServer\LanguageServer->Psalm\Internal\LanguageServer\{closure}()
#5 /var/www/html/PHP-Utils/vendor/amphp/amp/lib/Coroutine.php(67): Generator->current()
#6 /var/www/html/PHP-Utils/vendor/amphp/amp/lib/functions.php(96): Amp\Coroutine->__construct()
#7 /var/www/html/PHP-Utils/vendor/amphp/amp/lib/functions.php(61): Amp\call()
#8 /var/www/html/PHP-Utils/vendor/vimeo/psalm/src/Psalm/Internal/LanguageServer/EmitterTrait.php(85): Amp\{closure}()
#9 /var/www/html/PHP-Utils/vendor/vimeo/psalm/src/Psalm/Internal/LanguageServer/ProtocolStreamReader.php(116): Psalm\Internal\LanguageServer\ProtocolStreamReader->emit()
#10 /var/www/html/PHP-Utils/vendor/vimeo/psalm/src/Psalm/Internal/LanguageServer/ProtocolStreamReader.php(63): Psalm\Internal\LanguageServer\ProtocolStreamReader->readMessages()
#11 [internal function]: Psalm\Internal\LanguageServer\ProtocolStreamReader->Psalm\Internal\LanguageServer\{closure}()
#12 /var/www/html/PHP-Utils/vendor/amphp/amp/lib/Coroutine.php(118): Generator->send()
#13 /var/www/html/PHP-Utils/vendor/amphp/amp/lib/Internal/Placeholder.php(149): Amp\Coroutine->Amp\{closure}()
#14 /var/www/html/PHP-Utils/vendor/amphp/amp/lib/Deferred.php(53): Amp\Promise@anonymous->resolve()
#15 /var/www/html/PHP-Utils/vendor/amphp/byte-stream/lib/ResourceInputStream.php(101): Amp\Deferred->resolve()
#16 /var/www/html/PHP-Utils/vendor/amphp/amp/lib/Loop/NativeDriver.php(327): Amp\ByteStream\ResourceInputStream::Amp\ByteStream\{closure}()
#17 /var/www/html/PHP-Utils/vendor/amphp/amp/lib/Loop/NativeDriver.php(124): Amp\Loop\NativeDriver->selectStreams()
#18 /var/www/html/PHP-Utils/vendor/amphp/amp/lib/Loop/Driver.php(138): Amp\Loop\NativeDriver->dispatch()
#19 /var/www/html/PHP-Utils/vendor/amphp/amp/lib/Loop/Driver.php(72): Amp\Loop\Driver->tick()
#20 /var/www/html/PHP-Utils/vendor/amphp/amp/lib/Loop.php(95): Amp\Loop\Driver->run()
#21 /var/www/html/PHP-Utils/vendor/vimeo/psalm/src/Psalm/Internal/LanguageServer/LanguageServer.php(372): Amp\Loop::run()
#22 /var/www/html/PHP-Utils/vendor/vimeo/psalm/src/Psalm/Internal/Cli/LanguageServer.php(417): Psalm\Internal\LanguageServer\LanguageServer::run()
#23 /var/www/html/PHP-Utils/vendor/vimeo/psalm/psalm-language-server(9): Psalm\Internal\Cli\LanguageServer::run()
#24 {main}
[Error - 12:36:33 AM] UnexpectedValueException: Expecting non-empty $root_file_path and $checked_file_path in /var/www/html/PHP-Utils/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Functions.php:120
Stack trace:
#0 /var/www/html/PHP-Utils/vendor/vimeo/psalm/src/Psalm/Codebase.php(1120): Psalm\Internal\Codebase\Functions->getStorage()
#1 /var/www/html/PHP-Utils/vendor/vimeo/psalm/src/Psalm/Internal/LanguageServer/Server/TextDocument.php(254): Psalm\Codebase->getMarkupContentForSymbolByReference()
#2 /var/www/html/PHP-Utils/vendor/felixfbecker/advanced-json-rpc/lib/Dispatcher.php(168): Psalm\Internal\LanguageServer\Server\TextDocument->hover()
#3 /var/www/html/PHP-Utils/vendor/vimeo/psalm/src/Psalm/Internal/LanguageServer/LanguageServer.php(199): AdvancedJsonRpc\Dispatcher->dispatch()
#4 [internal function]: Psalm\Internal\LanguageServer\LanguageServer->Psalm\Internal\LanguageServer\{closure}()
#5 /var/www/html/PHP-Utils/vendor/amphp/amp/lib/Coroutine.php(67): Generator->current()
#6 /var/www/html/PHP-Utils/vendor/amphp/amp/lib/functions.php(96): Amp\Coroutine->__construct()
#7 /var/www/html/PHP-Utils/vendor/amphp/amp/lib/functions.php(61): Amp\call()
#8 /var/www/html/PHP-Utils/vendor/vimeo/psalm/src/Psalm/Internal/LanguageServer/EmitterTrait.php(85): Amp\{closure}()
#9 /var/www/html/PHP-Utils/vendor/vimeo/psalm/src/Psalm/Internal/LanguageServer/ProtocolStreamReader.php(116): Psalm\Internal\LanguageServer\ProtocolStreamReader->emit()
#10 /var/www/html/PHP-Utils/vendor/vimeo/psalm/src/Psalm/Internal/LanguageServer/ProtocolStreamReader.php(63): Psalm\Internal\LanguageServer\ProtocolStreamReader->readMessages()
#11 [internal function]: Psalm\Internal\LanguageServer\ProtocolStreamReader->Psalm\Internal\LanguageServer\{closure}()
#12 /var/www/html/PHP-Utils/vendor/amphp/amp/lib/Coroutine.php(118): Generator->send()
#13 /var/www/html/PHP-Utils/vendor/amphp/amp/lib/Internal/Placeholder.php(149): Amp\Coroutine->Amp\{closure}()
#14 /var/www/html/PHP-Utils/vendor/amphp/amp/lib/Deferred.php(53): Amp\Promise@anonymous->resolve()
#15 /var/www/html/PHP-Utils/vendor/amphp/byte-stream/lib/ResourceInputStream.php(101): Amp\Deferred->resolve()
#16 /var/www/html/PHP-Utils/vendor/amphp/amp/lib/Loop/NativeDriver.php(327): Amp\ByteStream\ResourceInputStream::Amp\ByteStream\{closure}()
#17 /var/www/html/PHP-Utils/vendor/amphp/amp/lib/Loop/NativeDriver.php(124): Amp\Loop\NativeDriver->selectStreams()
#18 /var/www/html/PHP-Utils/vendor/amphp/amp/lib/Loop/Driver.php(138): Amp\Loop\NativeDriver->dispatch()
#19 /var/www/html/PHP-Utils/vendor/amphp/amp/lib/Loop/Driver.php(72): Amp\Loop\Driver->tick()
#20 /var/www/html/PHP-Utils/vendor/amphp/amp/lib/Loop.php(95): Amp\Loop\Driver->run()
#21 /var/www/html/PHP-Utils/vendor/vimeo/psalm/src/Psalm/Internal/LanguageServer/LanguageServer.php(372): Amp\Loop::run()
#22 /var/www/html/PHP-Utils/vendor/vimeo/psalm/src/Psalm/Internal/Cli/LanguageServer.php(417): Psalm\Internal\LanguageServer\LanguageServer::run()
#23 /var/www/html/PHP-Utils/vendor/vimeo/psalm/psalm-language-server(9): Psalm\Internal\Cli\LanguageServer::run()
#24 {main}
[Error - 12:36:34 AM] UnexpectedValueException: Expecting non-empty $root_file_path and $checked_file_path in /var/www/html/PHP-Utils/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Functions.php:120
Stack trace:
#0 /var/www/html/PHP-Utils/vendor/vimeo/psalm/src/Psalm/Codebase.php(1120): Psalm\Internal\Codebase\Functions->getStorage()
#1 /var/www/html/PHP-Utils/vendor/vimeo/psalm/src/Psalm/Internal/LanguageServer/Server/TextDocument.php(254): Psalm\Codebase->getMarkupContentForSymbolByReference()
#2 /var/www/html/PHP-Utils/vendor/felixfbecker/advanced-json-rpc/lib/Dispatcher.php(168): Psalm\Internal\LanguageServer\Server\TextDocument->hover()
#3 /var/www/html/PHP-Utils/vendor/vimeo/psalm/src/Psalm/Internal/LanguageServer/LanguageServer.php(199): AdvancedJsonRpc\Dispatcher->dispatch()
#4 [internal function]: Psalm\Internal\LanguageServer\LanguageServer->Psalm\Internal\LanguageServer\{closure}()
#5 /var/www/html/PHP-Utils/vendor/amphp/amp/lib/Coroutine.php(67): Generator->current()
#6 /var/www/html/PHP-Utils/vendor/amphp/amp/lib/functions.php(96): Amp\Coroutine->__construct()
#7 /var/www/html/PHP-Utils/vendor/amphp/amp/lib/functions.php(61): Amp\call()
#8 /var/www/html/PHP-Utils/vendor/vimeo/psalm/src/Psalm/Internal/LanguageServer/EmitterTrait.php(85): Amp\{closure}()
#9 /var/www/html/PHP-Utils/vendor/vimeo/psalm/src/Psalm/Internal/LanguageServer/ProtocolStreamReader.php(116): Psalm\Internal\LanguageServer\ProtocolStreamReader->emit()
#10 /var/www/html/PHP-Utils/vendor/vimeo/psalm/src/Psalm/Internal/LanguageServer/ProtocolStreamReader.php(63): Psalm\Internal\LanguageServer\ProtocolStreamReader->readMessages()
#11 [internal function]: Psalm\Internal\LanguageServer\ProtocolStreamReader->Psalm\Internal\LanguageServer\{closure}()
#12 /var/www/html/PHP-Utils/vendor/amphp/amp/lib/Coroutine.php(118): Generator->send()
#13 /var/www/html/PHP-Utils/vendor/amphp/amp/lib/Internal/Placeholder.php(149): Amp\Coroutine->Amp\{closure}()
#14 /var/www/html/PHP-Utils/vendor/amphp/amp/lib/Deferred.php(53): Amp\Promise@anonymous->resolve()
#15 /var/www/html/PHP-Utils/vendor/amphp/byte-stream/lib/ResourceInputStream.php(101): Amp\Deferred->resolve()
#16 /var/www/html/PHP-Utils/vendor/amphp/amp/lib/Loop/NativeDriver.php(327): Amp\ByteStream\ResourceInputStream::Amp\ByteStream\{closure}()
#17 /var/www/html/PHP-Utils/vendor/amphp/amp/lib/Loop/NativeDriver.php(124): Amp\Loop\NativeDriver->selectStreams()
#18 /var/www/html/PHP-Utils/vendor/amphp/amp/lib/Loop/Driver.php(138): Amp\Loop\NativeDriver->dispatch()
#19 /var/www/html/PHP-Utils/vendor/amphp/amp/lib/Loop/Driver.php(72): Amp\Loop\Driver->tick()
#20 /var/www/html/PHP-Utils/vendor/amphp/amp/lib/Loop.php(95): Amp\Loop\Driver->run()
#21 /var/www/html/PHP-Utils/vendor/vimeo/psalm/src/Psalm/Internal/LanguageServer/LanguageServer.php(372): Amp\Loop::run()
#22 /var/www/html/PHP-Utils/vendor/vimeo/psalm/src/Psalm/Internal/Cli/LanguageServer.php(417): Psalm\Internal\LanguageServer\LanguageServer::run()
#23 /var/www/html/PHP-Utils/vendor/vimeo/psalm/psalm-language-server(9): Psalm\Internal\Cli\LanguageServer::run()
#24 {main}
[Error - 12:36:34 AM] UnexpectedValueException: Expecting non-empty $root_file_path and $checked_file_path in /var/www/html/PHP-Utils/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Functions.php:120
Stack trace:
#0 /var/www/html/PHP-Utils/vendor/vimeo/psalm/src/Psalm/Codebase.php(1120): Psalm\Internal\Codebase\Functions->getStorage()
#1 /var/www/html/PHP-Utils/vendor/vimeo/psalm/src/Psalm/Internal/LanguageServer/Server/TextDocument.php(254): Psalm\Codebase->getMarkupContentForSymbolByReference()
#2 /var/www/html/PHP-Utils/vendor/felixfbecker/advanced-json-rpc/lib/Dispatcher.php(168): Psalm\Internal\LanguageServer\Server\TextDocument->hover()
#3 /var/www/html/PHP-Utils/vendor/vimeo/psalm/src/Psalm/Internal/LanguageServer/LanguageServer.php(199): AdvancedJsonRpc\Dispatcher->dispatch()
#4 [internal function]: Psalm\Internal\LanguageServer\LanguageServer->Psalm\Internal\LanguageServer\{closure}()
#5 /var/www/html/PHP-Utils/vendor/amphp/amp/lib/Coroutine.php(67): Generator->current()
#6 /var/www/html/PHP-Utils/vendor/amphp/amp/lib/functions.php(96): Amp\Coroutine->__construct()
#7 /var/www/html/PHP-Utils/vendor/amphp/amp/lib/functions.php(61): Amp\call()
#8 /var/www/html/PHP-Utils/vendor/vimeo/psalm/src/Psalm/Internal/LanguageServer/EmitterTrait.php(85): Amp\{closure}()
#9 /var/www/html/PHP-Utils/vendor/vimeo/psalm/src/Psalm/Internal/LanguageServer/ProtocolStreamReader.php(116): Psalm\Internal\LanguageServer\ProtocolStreamReader->emit()
#10 /var/www/html/PHP-Utils/vendor/vimeo/psalm/src/Psalm/Internal/LanguageServer/ProtocolStreamReader.php(63): Psalm\Internal\LanguageServer\ProtocolStreamReader->readMessages()
#11 [internal function]: Psalm\Internal\LanguageServer\ProtocolStreamReader->Psalm\Internal\LanguageServer\{closure}()
#12 /var/www/html/PHP-Utils/vendor/amphp/amp/lib/Coroutine.php(118): Generator->send()
#13 /var/www/html/PHP-Utils/vendor/amphp/amp/lib/Internal/Placeholder.php(149): Amp\Coroutine->Amp\{closure}()
#14 /var/www/html/PHP-Utils/vendor/amphp/amp/lib/Deferred.php(53): Amp\Promise@anonymous->resolve()
#15 /var/www/html/PHP-Utils/vendor/amphp/byte-stream/lib/ResourceInputStream.php(101): Amp\Deferred->resolve()
#16 /var/www/html/PHP-Utils/vendor/amphp/amp/lib/Loop/NativeDriver.php(327): Amp\ByteStream\ResourceInputStream::Amp\ByteStream\{closure}()
#17 /var/www/html/PHP-Utils/vendor/amphp/amp/lib/Loop/NativeDriver.php(124): Amp\Loop\NativeDriver->selectStreams()
#18 /var/www/html/PHP-Utils/vendor/amphp/amp/lib/Loop/Driver.php(138): Amp\Loop\NativeDriver->dispatch()
#19 /var/www/html/PHP-Utils/vendor/amphp/amp/lib/Loop/Driver.php(72): Amp\Loop\Driver->tick()
#20 /var/www/html/PHP-Utils/vendor/amphp/amp/lib/Loop.php(95): Amp\Loop\Driver->run()
#21 /var/www/html/PHP-Utils/vendor/vimeo/psalm/src/Psalm/Internal/LanguageServer/LanguageServer.php(372): Amp\Loop::run()
#22 /var/www/html/PHP-Utils/vendor/vimeo/psalm/src/Psalm/Internal/Cli/LanguageServer.php(417): Psalm\Internal\LanguageServer\LanguageServer::run()
#23 /var/www/html/PHP-Utils/vendor/vimeo/psalm/psalm-language-server(9): Psalm\Internal\Cli\LanguageServer::run()
#24 {main}
[Error - 12:36:34 AM] UnexpectedValueException: Expecting non-empty $root_file_path and $checked_file_path in /var/www/html/PHP-Utils/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Functions.php:120
Stack trace:
#0 /var/www/html/PHP-Utils/vendor/vimeo/psalm/src/Psalm/Codebase.php(1120): Psalm\Internal\Codebase\Functions->getStorage()
#1 /var/www/html/PHP-Utils/vendor/vimeo/psalm/src/Psalm/Internal/LanguageServer/Server/TextDocument.php(254): Psalm\Codebase->getMarkupContentForSymbolByReference()
#2 /var/www/html/PHP-Utils/vendor/felixfbecker/advanced-json-rpc/lib/Dispatcher.php(168): Psalm\Internal\LanguageServer\Server\TextDocument->hover()
#3 /var/www/html/PHP-Utils/vendor/vimeo/psalm/src/Psalm/Internal/LanguageServer/LanguageServer.php(199): AdvancedJsonRpc\Dispatcher->dispatch()
#4 [internal function]: Psalm\Internal\LanguageServer\LanguageServer->Psalm\Internal\LanguageServer\{closure}()
#5 /var/www/html/PHP-Utils/vendor/amphp/amp/lib/Coroutine.php(67): Generator->current()
#6 /var/www/html/PHP-Utils/vendor/amphp/amp/lib/functions.php(96): Amp\Coroutine->__construct()
#7 /var/www/html/PHP-Utils/vendor/amphp/amp/lib/functions.php(61): Amp\call()
#8 /var/www/html/PHP-Utils/vendor/vimeo/psalm/src/Psalm/Internal/LanguageServer/EmitterTrait.php(85): Amp\{closure}()
#9 /var/www/html/PHP-Utils/vendor/vimeo/psalm/src/Psalm/Internal/LanguageServer/ProtocolStreamReader.php(116): Psalm\Internal\LanguageServer\ProtocolStreamReader->emit()
#10 /var/www/html/PHP-Utils/vendor/vimeo/psalm/src/Psalm/Internal/LanguageServer/ProtocolStreamReader.php(63): Psalm\Internal\LanguageServer\ProtocolStreamReader->readMessages()
#11 [internal function]: Psalm\Internal\LanguageServer\ProtocolStreamReader->Psalm\Internal\LanguageServer\{closure}()
#12 /var/www/html/PHP-Utils/vendor/amphp/amp/lib/Coroutine.php(118): Generator->send()
#13 /var/www/html/PHP-Utils/vendor/amphp/amp/lib/Internal/Placeholder.php(149): Amp\Coroutine->Amp\{closure}()
#14 /var/www/html/PHP-Utils/vendor/amphp/amp/lib/Deferred.php(53): Amp\Promise@anonymous->resolve()
#15 /var/www/html/PHP-Utils/vendor/amphp/byte-stream/lib/ResourceInputStream.php(101): Amp\Deferred->resolve()
#16 /var/www/html/PHP-Utils/vendor/amphp/amp/lib/Loop/NativeDriver.php(327): Amp\ByteStream\ResourceInputStream::Amp\ByteStream\{closure}()
#17 /var/www/html/PHP-Utils/vendor/amphp/amp/lib/Loop/NativeDriver.php(124): Amp\Loop\NativeDriver->selectStreams()
#18 /var/www/html/PHP-Utils/vendor/amphp/amp/lib/Loop/Driver.php(138): Amp\Loop\NativeDriver->dispatch()
#19 /var/www/html/PHP-Utils/vendor/amphp/amp/lib/Loop/Driver.php(72): Amp\Loop\Driver->tick()
#20 /var/www/html/PHP-Utils/vendor/amphp/amp/lib/Loop.php(95): Amp\Loop\Driver->run()
#21 /var/www/html/PHP-Utils/vendor/vimeo/psalm/src/Psalm/Internal/LanguageServer/LanguageServer.php(372): Amp\Loop::run()
#22 /var/www/html/PHP-Utils/vendor/vimeo/psalm/src/Psalm/Internal/Cli/LanguageServer.php(417): Psalm\Internal\LanguageServer\LanguageServer::run()
#23 /var/www/html/PHP-Utils/vendor/vimeo/psalm/psalm-language-server(9): Psalm\Internal\Cli\LanguageServer::run()
#24 {main}
[Error - 12:36:43 AM] Method Psalm\Internal\LanguageServer\LanguageServer::cancelRequest() does not exist
[Error - 12:38:31 AM] Method Psalm\Internal\LanguageServer\LanguageServer::cancelRequest() does not exist
[Error - 12:38:40 AM] completion not found at 156:81
[Error - 12:38:40 AM] completion not found at 156:82
[Error - 12:38:40 AM] Method Psalm\Internal\LanguageServer\LanguageServer::cancelRequest() does not exist
[Error - 12:38:40 AM] completion not found at 156:83
[Error - 12:38:40 AM] Method Psalm\Internal\LanguageServer\LanguageServer::cancelRequest() does not exist
[Error - 12:40:14 AM] Method Psalm\Internal\LanguageServer\LanguageServer::cancelRequest() does not exist
[Error - 12:40:15 AM] completion not found at 156:66
[Error - 12:40:15 AM] Method Psalm\Internal\LanguageServer\LanguageServer::cancelRequest() does not exist
[Error - 12:40:15 AM] Method Psalm\Internal\LanguageServer\LanguageServer::cancelRequest() does not exist
[Error - 12:40:15 AM] Method Psalm\Internal\LanguageServer\LanguageServer::cancelRequest() does not exist
[Error - 12:40:35 AM] Method Psalm\Internal\LanguageServer\LanguageServer::cancelRequest() does not exist
[Error - 12:40:37 AM] Method Psalm\Internal\LanguageServer\LanguageServer::cancelRequest() does not exist
[Error - 12:40:37 AM] Method Psalm\Internal\LanguageServer\LanguageServer::cancelRequest() does not exist
[Error - 12:40:45 AM] Method Psalm\Internal\LanguageServer\LanguageServer::cancelRequest() does not exist
[Error - 12:40:47 AM] Method Psalm\Internal\LanguageServer\LanguageServer::cancelRequest() does not exist
[Error - 12:41:08 AM] Method Psalm\Internal\LanguageServer\LanguageServer::cancelRequest() does not exist
[Error - 12:41:10 AM] Method Psalm\Internal\LanguageServer\LanguageServer::cancelRequest() does not exist
[Error - 12:41:10 AM] Method Psalm\Internal\LanguageServer\LanguageServer::cancelRequest() does not exist
[Error - 12:41:10 AM] Method Psalm\Internal\LanguageServer\LanguageServer::cancelRequest() does not exist
[Error - 12:41:10 AM] Method Psalm\Internal\LanguageServer\LanguageServer::cancelRequest() does not exist
[Error - 12:41:12 AM] Method Psalm\Internal\LanguageServer\LanguageServer::cancelRequest() does not exist
[Error - 12:41:12 AM] Method Psalm\Internal\LanguageServer\LanguageServer::cancelRequest() does not exist
[Error - 12:41:14 AM] Method Psalm\Internal\LanguageServer\LanguageServer::cancelRequest() does not exist
[Error - 12:41:24 AM] Method Psalm\Internal\LanguageServer\LanguageServer::cancelRequest() does not exist
[Error - 12:41:28 AM] Method Psalm\Internal\LanguageServer\LanguageServer::cancelRequest() does not exist
[Error - 12:41:28 AM] completion not found at 95:79
[Error - 12:41:29 AM] Method Psalm\Internal\LanguageServer\LanguageServer::cancelRequest() does not exist
[Error - 12:41:30 AM] completion not found at 95:80
[Error - 12:41:30 AM] Method Psalm\Internal\LanguageServer\LanguageServer::cancelRequest() does not exist
[Error - 12:41:30 AM] completion not found at 95:81
[Error - 12:41:30 AM] Method Psalm\Internal\LanguageServer\LanguageServer::cancelRequest() does not exist
[Error - 12:41:30 AM] Method Psalm\Internal\LanguageServer\LanguageServer::cancelRequest() does not exist
[Error - 12:41:30 AM] Method Psalm\Internal\LanguageServer\LanguageServer::cancelRequest() does not exist
[Error - 12:41:36 AM] Method Psalm\Internal\LanguageServer\LanguageServer::cancelRequest() does not exist
[Error - 12:41:36 AM] Method Psalm\Internal\LanguageServer\LanguageServer::cancelRequest() does not exist
[Error - 12:41:36 AM] Method Psalm\Internal\LanguageServer\LanguageServer::cancelRequest() does not exist
[WARN  - 12:43:40 AM] Psalm Version could not be parsed as a Semantic Version. Got "Psalm 5.x-dev@c6311028647126fa760ff54b580bcde7ca9a0f92
". Assuming unknown
[Error - 12:43:52 AM] Method Psalm\Internal\LanguageServer\LanguageServer::cancelRequest() does not exist
[WARN  - 12:44:03 AM] Psalm Version could not be parsed as a Semantic Version. Got "Psalm 5.x-dev@c6311028647126fa760ff54b580bcde7ca9a0f92
". Assuming unknown
[Error - 12:44:57 AM] Method Psalm\Internal\LanguageServer\LanguageServer::cancelRequest() does not exist
[Error - 12:44:57 AM] Method Psalm\Internal\LanguageServer\LanguageServer::cancelRequest() does not exist
[Error - 12:44:57 AM] Method Psalm\Internal\LanguageServer\LanguageServer::cancelRequest() does not exist
[Error - 12:44:57 AM] Method Psalm\Internal\LanguageServer\LanguageServer::cancelRequest() does not exist
[Error - 12:44:57 AM] Method Psalm\Internal\LanguageServer\LanguageServer::cancelRequest() does not exist
[Error - 12:44:57 AM] Method Psalm\Internal\LanguageServer\LanguageServer::cancelRequest() does not exist
[Error - 12:45:16 AM] Method Psalm\Internal\LanguageServer\LanguageServer::cancelRequest() does not exist
[Error - 12:45:31 AM] Method Psalm\Internal\LanguageServer\LanguageServer::cancelRequest() does not exist
```

I try restart server and try Analyze Workspace in `Ctrl + Shift + P`

**Comment by danielbeardsley** [comment]
Running into this same bug in vscode with psalm language server 6.4.1:

```
[INFO  - 10:10:13 AM] Starting language server
[INFO  - 10:10:13 AM] Psalm Version was detected as 6.4.1
[Info  - 10:10:16 AM] Psalm Language Server 6.4.1@09a200c15910905ddc49e5edd37b73f9c78f7580 has started.
[Info  - 10:10:16 AM] Initializing...
[Info  - 10:10:16 AM] Initializing: Visiting Autoload Files...
[Info  - 10:10:33 AM] Initializing: Loading Reference Cache...
[Info  - 10:10:33 AM] Initializing: Initialize Plugins...
[Info  - 10:10:33 AM] Initializing: Getting code base...
[Info  - 10:10:33 AM] Initializing: Scanning files (1 Threads)...
[Info  - 10:11:47 AM] Initializing: Registering stub files...
[Info  - 10:11:49 AM] Initializing: Complete.
[INFO  - 10:11:49 AM] The Language Server is ready
[Error - 10:11:52 AM] Method Psalm\Internal\LanguageServer\LanguageServer::cancelRequest() does not exist
[Error - 10:11:52 AM] Method Psalm\Internal\LanguageServer\LanguageServer::cancelRequest() does not exist
[Error - 10:11:52 AM] Method Psalm\Internal\LanguageServer\LanguageServer::cancelRequest() does not exist
... on and on for thousands of lines.
```
