### ISSUE TITLE
Fatal error when dealing with class_alias-ed class

### ISSUE THREAD

**Issue by flack** [vimeo/psalm#1102]
When I try to run psalm on one of my projects (just following the basic steps in the readme), I get the following error:

```
$> vendor/bin/psalm
Scanning files...
Analyzing files...
PHP Notice:  Undefined index: $object->metadata in ./vendor/vimeo/psalm/src/Psalm/Type/Reconciler.php on line 2087

Notice: Undefined index: $object->metadata in ./vendor/vimeo/psalm/src/Psalm/Type/Reconciler.php on line 2087
PHP Notice:  Undefined index: $object->metadata in ./vendor/vimeo/psalm/src/Psalm/Type/Reconciler.php on line 2087

Notice: Undefined index: $object->metadata in ./vendor/vimeo/psalm/src/Psalm/Type/Reconciler.php on line 2087
PHP Notice:  Undefined index: $object->metadata in ./vendor/vimeo/psalm/src/Psalm/Type/Reconciler.php on line 2034

Notice: Undefined index: $object->metadata in ./vendor/vimeo/psalm/src/Psalm/Type/Reconciler.php on line 2034
PHP Fatal error:  Uncaught Error: Call to a member function getTypes() on null in ./vendor/vimeo/psalm/src/Psalm/Type/Reconciler.php:2034
Stack trace:
#0 ./vendor/vimeo/psalm/src/Psalm/Type/Reconciler.php(138): Psalm\Type\Reconciler::getValueForKey(Object(Psalm\Codebase), '$object->metada...', Array)
#1 ./vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/Statements/Block/IfAnalyzer.php(1355): Psalm\Type\Reconciler::reconcileKeyedTypes(Array, Array, Array, Array, Object(Psalm\Internal\Analyzer\StatementsAnalyzer), NULL)
#2 ./vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/Statements/Block/IfAnalyzer.php(406): Psalm\Internal\Analyzer\Statements\Block\IfAnalyzer::analyzeElseBlock(Object(Psalm\Internal\Analyzer\StatementsAnalyzer), NULL, Object(Psalm\Internal\Scope\IfScope), Object(Psalm\Context), Object(Psalm\Context))
#3 ./vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/StatementsAnalyzer.php(223): Psalm\Internal\Analyze in ./vendor/vimeo/psalm/src/Psalm/Type/Reconciler.php on line 2034

Fatal error: Uncaught Error: Call to a member function getTypes() on null in ./vendor/vimeo/psalm/src/Psalm/Type/Reconciler.php:2034
Stack trace:
#0 ./vendor/vimeo/psalm/src/Psalm/Type/Reconciler.php(138): Psalm\Type\Reconciler::getValueForKey(Object(Psalm\Codebase), '$object->metada...', Array)
#1 ./vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/Statements/Block/IfAnalyzer.php(1355): Psalm\Type\Reconciler::reconcileKeyedTypes(Array, Array, Array, Array, Object(Psalm\Internal\Analyzer\StatementsAnalyzer), NULL)
#2 ./vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/Statements/Block/IfAnalyzer.php(406): Psalm\Internal\Analyzer\Statements\Block\IfAnalyzer::analyzeElseBlock(Object(Psalm\Internal\Analyzer\StatementsAnalyzer), NULL, Object(Psalm\Internal\Scope\IfScope), Object(Psalm\Context), Object(Psalm\Context))
#3 ./vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/StatementsAnalyzer.php(223): Psalm\Internal\Analyze in ./vendor/vimeo/psalm/src/Psalm/Type/Reconciler.php on line 2034
```

**Comment by muglug** [comment]
Sorry about that - could you run `--debug-by-line` to try to narrow down where there error is coming from?

**Comment by flack** [comment]
These are the lines before the errors:

before first notice:

https://github.com/flack/openpsa/blob/5839cce01a69d5ac9a4b6b387e052a455d426cb8/lib/midcom/services/indexer/document.php#L610

before second notice:

https://github.com/flack/openpsa/blob/5839cce01a69d5ac9a4b6b387e052a455d426cb8/lib/midcom/services/indexer/document.php#L612

before third notice and fatal errors:

https://github.com/flack/openpsa/blob/5839cce01a69d5ac9a4b6b387e052a455d426cb8/lib/midcom/services/indexer/document.php#L614

**Comment by muglug** [comment]
Yeah, if you replace `midgard_object` with `\midgard\portable\api\mgdobject` everything works.

**Comment by muglug** [comment]
You should be good now - I've added support for `class_alias`, though coverage might be spotty. LMK if you run into problems.

**Comment by flack** [comment]
@muglug looks good! I just installed `dev-master`, and now psalm runs through without errors

**Comment by flack** [comment]
Oops, tunrs out I spoke too soon: I was on another machine that didn't have the directories configured correctly yet. When I fixed the config, I got a couple of warnings like this one:

```
Notice: Undefined index: $this->__privilege_object->guid in ./openpsa/vendor/vimeo/psalm/src/Psalm/Type/Reconciler.php on line 2087
```

This is shown for this line:

https://github.com/flack/openpsa/blob/9cec7ec17a498b3db0e6e1fd84f0365ef855739e/lib/midcom/core/privilege.php#L640

There are a couple more that look similar:

```
Notice: Undefined index: $this->_storage->id in /home/flack/git/openpsa/vendor/vimeo/psalm/src/Psalm/Type/Reconciler.php on line 2087
```

from https://github.com/flack/openpsa/blob/e7be6b161393373ead7e7c54abf26e8d068b3488/lib/midcom/core/group.php#L127

and so on. But it's finishing its run now, so there's definitely progress :-)

**Comment by muglug** [comment]
> I was on another machine that didn't have the directories configured correctly yet.

If you're able to reproduce, please file another ticket!
