### ISSUE TITLE
Fatal error:  Uncaught Error: Call to a member function getTypes() on null

### ISSUE THREAD

**Issue by adammarton** [vimeo/psalm#1114]
Hi there,

Experienced this issue on PHP7.2 Win:

This might be because of the code I'm testing or can be a bug in Psalm.

```
Scanning files...
Analyzing files...
PHP Notice:  Undefined index: $field->type in C:\Users\<username>\AppData\Roaming\Composer\vendor\vimeo\psalm\src\Psalm\Type\Reconciler.php on line 2087

Notice: Undefined index: $field->type in C:\Users\<username>\AppData\Roaming\Composer\vendor\vimeo\psalm\src\Psalm\Type\Reconciler.php on line 2087
PHP Notice:  Undefined index: $field->type in C:\Users\<username>\AppData\Roaming\Composer\vendor\vimeo\psalm\src\Psalm\Type\Reconciler.php on line 2087

Notice: Undefined index: $field->type in C:\Users\<username>\AppData\Roaming\Composer\vendor\vimeo\psalm\src\Psalm\Type\Reconciler.php on line 2087
PHP Notice:  Undefined index: $field->type in C:\Users\<username>\AppData\Roaming\Composer\vendor\vimeo\psalm\src\Psalm\Type\Reconciler.php on line 2087

Notice: Undefined index: $field->type in C:\Users\<username>\AppData\Roaming\Composer\vendor\vimeo\psalm\src\Psalm\Type\Reconciler.php on line 2087
PHP Notice:  Undefined index: $field->type in C:\Users\<username>\AppData\Roaming\Composer\vendor\vimeo\psalm\src\Psalm\Type\Reconciler.php on line 2087

Notice: Undefined index: $field->type in C:\Users\<username>\AppData\Roaming\Composer\vendor\vimeo\psalm\src\Psalm\Type\Reconciler.php on line 2087
PHP Notice:  Undefined index: $this->constrains->static in C:\Users\<username>\AppData\Roaming\Composer\vendor\vimeo\psalm\src\Psalm\Type\Reconciler.php on line 2034

Notice: Undefined index: $this->constrains->static in C:\Users\<username>\AppData\Roaming\Composer\vendor\vimeo\psalm\src\Psalm\Type\Reconciler.php on line 2034
PHP Fatal error:  Uncaught Error: Call to a member function getTypes() on null in C:\Users\<username>\AppData\Roaming\Composer\vendor\vimeo\psalm\src\Psalm\Type\Reconciler.php:2034
Stack trace:
#0 C:\Users\<username>\AppData\Roaming\Composer\vendor\vimeo\psalm\src\Psalm\Type\Reconciler.php(138): Psalm\Type\Reconciler::getValueForKey(Object(Psalm\Codebase), '$this->constrai...', Array)
#1 C:\Users\<username>\AppData\Roaming\Composer\vendor\vimeo\psalm\src\Psalm\Internal\Analyzer\Statements\Expression\BinaryOpAnalyzer.php(224): Psalm\Type\Reconciler::reconcileKeyedTypes(Array, Array, Array, Array, Object(Psalm\Internal\Analyzer\StatementsAnalyzer), Object(Psalm\CodeLocation))
#2 C:\Users\<username>\AppData\Roaming\Composer\vendor\vimeo\psalm\src\Psalm\Internal\Analyzer\Statements\ExpressionAnalyzer.php(204): Psalm\Internal\Analyzer\Statements\Expression\BinaryOpAnalyzer::analyze(Object(Psalm\Internal\Analyzer\StatementsAnalyzer), Object(PhpParser\Node\Expr\BinaryOp\BooleanOr), Object(Psalm\Context))
#3 C:\Users\<username>\A in C:\Users\<username>\AppData\Roaming\Composer\vendor\vimeo\psalm\src\Psalm\Type\Reconciler.php on line 2034

Fatal error: Uncaught Error: Call to a member function getTypes() on null in C:\Users\<username>\AppData\Roaming\Composer\vendor\vimeo\psalm\src\Psalm\Type\Reconciler.php:2034
Stack trace:
#0 C:\Users\<username>\AppData\Roaming\Composer\vendor\vimeo\psalm\src\Psalm\Type\Reconciler.php(138): Psalm\Type\Reconciler::getValueForKey(Object(Psalm\Codebase), '$this->constrai...', Array)
#1 C:\Users\<username>\AppData\Roaming\Composer\vendor\vimeo\psalm\src\Psalm\Internal\Analyzer\Statements\Expression\BinaryOpAnalyzer.php(224): Psalm\Type\Reconciler::reconcileKeyedTypes(Array, Array, Array, Array, Object(Psalm\Internal\Analyzer\StatementsAnalyzer), Object(Psalm\CodeLocation))
#2 C:\Users\<username>\AppData\Roaming\Composer\vendor\vimeo\psalm\src\Psalm\Internal\Analyzer\Statements\ExpressionAnalyzer.php(204): Psalm\Internal\Analyzer\Statements\Expression\BinaryOpAnalyzer::analyze(Object(Psalm\Internal\Analyzer\StatementsAnalyzer), Object(PhpParser\Node\Expr\BinaryOp\BooleanOr), Object(Psalm\Context))
#3 C:\Users\<username>\A in C:\Users\<username>\AppData\Roaming\Composer\vendor\vimeo\psalm\src\Psalm\Type\Reconciler.php on line 2034
```

**Comment by muglug** [comment]
Also is this with Psalm latest master? I fixed a [similar issue](https://github.com/vimeo/psalm/issues/1102)

**Comment by muglug** [comment]
Yes, what I mean is `--debug-by-line` allows you to figure out what lines are causing the error message (which you could paste here). Also are you checking with latest master?

**Comment by adammarton** [comment]
Hi @muglug,

As I've mentioned, I'm on `3.0.2`. Sorry, but I wouldn't like to paste the output of `--debug-by-line` because there's nothing in it, but the name of my files.

**Comment by muglug** [comment]
It should give you the line number (after the name of the file).

To get latest master you have to explicitly install it with Composer - like `composer require --dev vimeo/psalm:dev-master`

**Comment by muglug** [comment]
Also if you use latest master (and if the error still crops up) you should see an error message that tells you where in your code Psalm failed.

**Comment by muglug** [comment]
Closing - if you have info, feel free to reopen!
