### ISSUE TITLE
Psalm don't work after installing package "sendgrid/sendgrid:5.6.2" via composer

### ISSUE THREAD

**Issue by yevgen-2m** [vimeo/psalm#11147]
Steps to reproduce error:
1. Run `composer init`  in empty folder
2. `composer require sendgrid/sendgrid:5.6.2`
3. `psalm.phar --version`

php shows error:
```
PHP Fatal error:  During inheritance of JsonSerializable: Uncaught RuntimeException: PHP Error: Return type of SendGrid\ReplyTo::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/empty/vendor/sendgrid/sendgrid/lib/helpers/mail/Mail.php:49 for command with CLI args "./psalm.phar" in phar:///var/www/empty/psalm.phar/src/Psalm/Internal/ErrorHandler.php:61
Stack trace:
#0 /var/www/empty/vendor/sendgrid/sendgrid/lib/helpers/mail/Mail.php(15): Psalm\Internal\ErrorHandler::Psalm\Internal\{closure}(8192, 'Return type of ...', '/var/www/empty/...', 49)
#1 /var/www/empty/vendor/composer/autoload_real.php(71): require('/var/www/empty/...')
#2 /var/www/empty/vendor/composer/autoload_real.php(61): composerRequire1548a346eba4adb410bac0310916e649('9dda55337a76a24...', '/var/www/empty/...')
#3 /var/www/empty/vendor/autoload.php(7): ComposerAutoloaderInit1548a346eba4adb410bac0310916e649::getLoader()
#4 phar:///var/www/empty/psalm.phar/src/Psalm/Internal/CliUtils.php(108): require_once('/var/www/empty/...')
#5 phar:///var/www/empty/psalm.phar/src/Psalm/Internal/Cli/Psalm.php(201): Psalm\Internal\CliUtils::requireAutoloaders('/var/www/empty', false, 'vendor')
#6 phar:///var/www/empty/psalm.phar/src/Psalm/Internal/IncludeCollector.php(32): Psalm\Internal\Cli\Psalm::Psalm\Internal\Cli\{closure}()
#7 phar:///var/www/empty/psalm.phar/src/Psalm/Internal/Cli/Psalm.php(202): Psalm\Internal\IncludeCollector->runAndCollect(Object(Closure))
#8 phar:///var/www/empty/psalm.phar/psalm(7): Psalm\Internal\Cli\Psalm::run(Array)
#9 /var/www/empty/psalm.phar(14): require('phar:///var/www...')
#10 {main} in /var/www/empty/vendor/sendgrid/sendgrid/lib/helpers/mail/Mail.php on line 15
Fatal error: During inheritance of JsonSerializable: Uncaught RuntimeException: PHP Error: Return type of SendGrid\ReplyTo::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/empty/vendor/sendgrid/sendgrid/lib/helpers/mail/Mail.php:49 for command with CLI args "./psalm.phar" in phar:///var/www/empty/psalm.phar/src/Psalm/Internal/ErrorHandler.php:61
Stack trace:
#0 /var/www/empty/vendor/sendgrid/sendgrid/lib/helpers/mail/Mail.php(15): Psalm\Internal\ErrorHandler::Psalm\Internal\{closure}(8192, 'Return type of ...', '/var/www/empty/...', 49)
#1 /var/www/empty/vendor/composer/autoload_real.php(71): require('/var/www/empty/...')
#2 /var/www/empty/vendor/composer/autoload_real.php(61): composerRequire1548a346eba4adb410bac0310916e649('9dda55337a76a24...', '/var/www/empty/...')
#3 /var/www/empty/vendor/autoload.php(7): ComposerAutoloaderInit1548a346eba4adb410bac0310916e649::getLoader()
#4 phar:///var/www/empty/psalm.phar/src/Psalm/Internal/CliUtils.php(108): require_once('/var/www/empty/...')
#5 phar:///var/www/empty/psalm.phar/src/Psalm/Internal/Cli/Psalm.php(201): Psalm\Internal\CliUtils::requireAutoloaders('/var/www/empty', false, 'vendor')
#6 phar:///var/www/empty/psalm.phar/src/Psalm/Internal/IncludeCollector.php(32): Psalm\Internal\Cli\Psalm::Psalm\Internal\Cli\{closure}()
#7 phar:///var/www/empty/psalm.phar/src/Psalm/Internal/Cli/Psalm.php(202): Psalm\Internal\IncludeCollector->runAndCollect(Object(Closure))
#8 phar:///var/www/empty/psalm.phar/psalm(7): Psalm\Internal\Cli\Psalm::run(Array)
#9 /var/www/empty/psalm.phar(14): require('phar:///var/www...')
#10 {main} in /var/www/empty/vendor/sendgrid/sendgrid/lib/helpers/mail/Mail.php on line 15
```

Without `sendgrid` psalm works well

**Comment by yevgen-2m** [comment]
I solved this issue by replacing line
```
public function jsonSerialize()
```
with
```
public function jsonSerialize(): mixed
```

It seems better to update the package than to try to fix this error on the psaml side
