### ISSUE TITLE
Scanning thinks README.md is a folder in 3.0.9

### ISSUE THREAD

**Issue by AJenbo** [vimeo/psalm#1187]
After upgrading from 3.0.7 to 3.0.9 i get the following error during scanning of the vendor folder:
```
vendor/bin/psalm
Scanning files...
PHP Fatal error:  Uncaught UnexpectedValueException: RecursiveDirectoryIterator::__construct(../../README.md/): failed to open dir: No such file or directory in /__redacated__/vendor/vimeo/psalm/src/Psalm/Internal/Provider/FileProvider.php:128
Stack trace:
#0 /__redacated__/vendor/vimeo/psalm/src/Psalm/Internal/Provider/FileProvider.php(128): RecursiveDirectoryIterator->__construct('../../README.md...')
#1 /__redacated__/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/ProjectAnalyzer.php(523): Psalm\Internal\Provider\FileProvider->getFilesInDir('../../README.md...', Array)
#2 /__redacated__/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/ProjectAnalyzer.php(380): Psalm\Internal\Analyzer\ProjectAnalyzer->checkDirWithConfig('../../README.md...', Object(Psalm\Config))
#3 /__redacated__/vendor/vimeo/psalm/src/psalm.php(501): Psalm\Internal\Analyzer\ProjectAnalyzer->check('/home/ajenbo/co...', fa in /__redacated__/vendor/vimeo/psalm/src/Psalm/Internal/Provider/FileProvider.php on line 128

Fatal error: Uncaught UnexpectedValueException: RecursiveDirectoryIterator::__construct(../../README.md/): failed to open dir: No such file or directory in /__redacated__/vendor/vimeo/psalm/src/Psalm/Internal/Provider/FileProvider.php:128
Stack trace:
#0 /__redacated__/vendor/vimeo/psalm/src/Psalm/Internal/Provider/FileProvider.php(128): RecursiveDirectoryIterator->__construct('../../README.md...')
#1 /__redacated__/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/ProjectAnalyzer.php(523): Psalm\Internal\Provider\FileProvider->getFilesInDir('../../README.md...', Array)
#2 /__redacated__/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/ProjectAnalyzer.php(380): Psalm\Internal\Analyzer\ProjectAnalyzer->checkDirWithConfig('../../README.md...', Object(Psalm\Config))
#3 /__redacated__/vendor/vimeo/psalm/src/psalm.php(501): Psalm\Internal\Analyzer\ProjectAnalyzer->check('/home/ajenbo/co...', fa in /__redacated__/vendor/vimeo/psalm/src/Psalm/Internal/Provider/FileProvider.php on line 128

```

Update this issue doesn't appear in 3.0.8

**Comment by AJenbo** [comment]
My guess is that the new feature for haneling symlinks is assuming that links are folders.

**Comment by muglug** [comment]
This should be fixed in master - I'll create a release imminently

**Comment by AJenbo** [comment]
Can confirm that it's fixed in master.

**Comment by muglug** [comment]
https://github.com/vimeo/psalm/releases/tag/3.0.10
