### ISSUE TITLE
"Could not get class storage for closure"

### ISSUE THREAD

**Issue by xPaw** [vimeo/psalm#1229]
```
PHP Fatal error:  Uncaught InvalidArgumentException: Could not get class storage for closure in vendor\vimeo\psalm\src\Psalm\Internal\Provider\ClassLikeStorageProvider.php:43
Stack trace:
#0 vendor\vimeo\psalm\src\Psalm\Internal\Codebase\ClassLikes.php(425): Psalm\Internal\Provider\ClassLikeStorageProvider->get('closure')
#1 vendor\vimeo\psalm\src\Psalm\Codebase.php(586): Psalm\Internal\Codebase\ClassLikes->classExtends('closure', 'callback')
#2 vendor\vimeo\psalm\src\Psalm\Internal\Analyzer\TypeAnalyzer.php(406): Psalm\Codebase->classExtendsOrImplements('closure', 'callback')
#3 vendor\vimeo\psalm\src\Psalm\Internal\Analyzer\TypeAnalyzer.php(511): Psalm\Internal\Analyzer\TypeAnalyzer::isObjectContainedByObject(Object(Psalm\Codebase), Object(Psalm\Type\Atomic\Fn), Object(Psalm\Type\Atomic\TNamedObject), false)
#4 vendor\vimeo\psalm\src\Psalm\Internal\Analyzer\TypeAnalyzer.php(120): Psalm\Int in vendor\vimeo\psalm\src\Psalm\Internal\Provider\ClassLikeStorageProvider.php on line 43
```

I managed to boil it down to this code:
```php
<?php

while( true )
{
	$Crimp = new Crimp( function() use ( $Test )
	{
	});
}
```

**Comment by xPaw** [comment]
Hm, looks like it needed the class itself to happen: https://getpsalm.org/r/4b53d29b2e

It seems to only happen in this specific combination, when the anonymous function is 'created' inside of a while loop.

**Comment by muglug** [comment]
Thanks! Reproduced with

```
class Foo {
  	public function __construct(UndefinedClass $o) {}
}
new Foo(function() {});
```

**Comment by xPaw** [comment]
Interesting. Does psalm consider type defined in `@param` higher priority than the one in the actual function definition?

**Comment by muglug** [comment]
> Does psalm consider type defined in @param higher priority than the one in the actual function definition?

Yup, because docblocks can carry more information (e.g. `@param array<int, string>`, @param B|C`. Psalm also checks that the docblocks more specific (and not just different) from the one in the actual function definition.
