### ISSUE TITLE
Fatal Error: UnexpectedValueException: Storage should exist for Foo

### ISSUE THREAD

**Issue by SignpostMarv** [vimeo/psalm#130]
I've got a class that implements __invoke() and I'm getting a fatal error:

Examplish code:
```php
protected $stackForFoo[];

public function getFoo() : Foo
{
    return new Foo($stackForFoo);
}

public function bar($argOne, $argTwo)
{
    $this->getFoo()($argOne, $argTwo); // seems to trigger error
}

public function baz($argOne, $argTwo)
{
    $foo = $this->getFoo();  // seems to trigger error
    $foo($argOne, $argTwo);  // seems to trigger error
}
```

```
Fatal error: Uncaught UnexpectedValueException: Storage should exist for Foo in path-to-package\vendor\vimeo\psalm\src\Psalm\Checker\MethodChecker.php:320
Stack trace:
#0 path-to-package\vendor\vimeo\psalm\src\Psalm\Checker\Statements\Expression\CallChecker.php(165): Psalm\Checker\MethodChecker::methodExists('truncatedNamespaceOfTh...', Object(Psalm\Checker\FileChecker))
#1 path-to-package\vendor\vimeo\psalm\src\Psalm\Checker\Statements\ExpressionChecker.php(207): Psalm\Checker\Statements\Expression\CallChecker::analyzeFunctionCall(Object(Psalm\Checker\StatementsChecker), Object(PhpParse         r\Node\Expr\FuncCall), Object(Psalm\Context))
#2 path-to-package\vendor\vimeo\psalm\src\Psalm\Checker\StatementsChecker.php(222): Psalm\Checker\Statements\ExpressionChecker::analyze(Object(Psalm\Checker\StatementsChecker), Object(PhpPars in path-to-package\vendor\vimeo\psalm\src\Psalm\Checker\MethodChecker.php on line 320
```

**Comment by muglug** [comment]
Thanks! Let me know if the above fix nixes the issue.

**Comment by SignpostMarv** [comment]
running on 32efdfd0f7, issue is fixed :)
