### ISSUE TITLE
Fatal error: Uncaught UnexpectedValueException: Could not find declaring method for ...

### ISSUE THREAD

**Issue by jdufresne** [vimeo/psalm#1337]
I'm using the default configuration generated by `psalm --init`.

My best guess is this is due to use of `__call` method to dynamically handle undefined methods. They are never declared explicitly.

https://secure.php.net/manual/en/language.oop5.overloading.php#object.call

It looks like psalms can't handle this and fails with an `UnexpectedValueException`. Full output below.

```
$ ./vendor/bin/psalm
Scanning files...
Analyzing files...
PHP Fatal error:  Uncaught UnexpectedValueException: Could not find declaring method for myclass::mymethod in /home/jdufresne/myproject/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/Statements/Expression/CallAnalyzer.php:142
Stack trace:
#0 /home/jdufresne/myproject/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/Statements/Expression/Call/MethodCallAnalyzer.php(829): Psalm\Internal\Analyzer\Statements\Expression\CallAnalyzer::collectSpecialInformation(Object(Psalm\Internal\Analyzer\MethodAnalyzer), 'mymethod', Object(Psalm\Context))
#1 /home/jdufresne/myproject/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/Statements/Expression/Call/MethodCallAnalyzer.php(199): Psalm\Internal\Analyzer\Statements\Expression\Call\MethodCallAnalyzer::analyzeAtomicCall(Object(Psalm\Internal\Analyzer\StatementsAnalyzer), Object(PhpParser\Node\Expr\MethodCall), Object(Psalm\Codebase), Object(Psalm\Context), Object(Psalm\Type\Atomic\TNamedObject), '$this', NULL, false, false, true, false, Array, Array, Array, Arr in /home/jdufresne/myproject/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/Statements/Expression/CallAnalyzer.php on line 142

Fatal error: Uncaught UnexpectedValueException: Could not find declaring method for myclass::mymethod in /home/jdufresne/myproject/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/Statements/Expression/CallAnalyzer.php:142
Stack trace:
#0 /home/jdufresne/myproject/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/Statements/Expression/Call/MethodCallAnalyzer.php(829): Psalm\Internal\Analyzer\Statements\Expression\CallAnalyzer::collectSpecialInformation(Object(Psalm\Internal\Analyzer\MethodAnalyzer), 'mymethod', Object(Psalm\Context))
#1 /home/jdufresne/myproject/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/Statements/Expression/Call/MethodCallAnalyzer.php(199): Psalm\Internal\Analyzer\Statements\Expression\Call\MethodCallAnalyzer::analyzeAtomicCall(Object(Psalm\Internal\Analyzer\StatementsAnalyzer), Object(PhpParser\Node\Expr\MethodCall), Object(Psalm\Codebase), Object(Psalm\Context), Object(Psalm\Type\Atomic\TNamedObject), '$this', NULL, false, false, true, false, Array, Array, Array, Arr in /home/jdufresne/myproject/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/Statements/Expression/CallAnalyzer.php on line 142
```

**Comment by muglug** [comment]
Thanks - would you mind running with `--debug-by-line` to figure out where exactly the exception is coming from?

**Comment by jdufresne** [comment]
This prints out lots of filenames before eventually getting to the same error. Is there something in particular I can share from the output? Unfortunately, I can't copy & paste the exact output as the project is private.

**Comment by muglug** [comment]
The last line before the error should be the source of the error (so whatever Psalm was trying to do there caused it).

Could you post an obfuscated version of whatever code is referenced?

**Comment by muglug** [comment]
I'm presuming it's in a constructor, judging by the error location

**Comment by jdufresne** [comment]
Yup, that is right. In a constructor.

**Comment by muglug** [comment]
What sort of thing is being called, and how?

**Comment by muglug** [comment]
Reproduced with

```php
class A {
  /** @var string */
  private $a;
  
  public function __construct() {
    $this->setA();
  }
  
  public function __call() {}
}
```
