### ISSUE TITLE
Fatal on analyze generator with enabled PhpStorm generics feature

### ISSUE THREAD

**Issue by andrew-demb** [vimeo/psalm#1370]
https://getpsalm.org/r/57936d08a0

```php
<?php
class A
{
    /**
     * @return stdClass[]|Generator
     */
    function getCollection(): Generator
    {
        yield new stdClass;
    }
}
```

```
PHP Notice:  Undefined offset: 2 in /.../.composer/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/Statements/ExpressionAnalyzer.php on line 1259

Notice: Undefined offset: 2 in /.../.composer/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/Statements/ExpressionAnalyzer.php on line 1259
PHP Fatal error:  Uncaught Error: Call to a member function isMixed() on null in /.../.composer/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/Statements/ExpressionAnalyzer.php:1259
Stack trace:
#0 /.../.composer/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/Statements/ExpressionAnalyzer.php(546): Psalm\Internal\Analyzer\Statements\ExpressionAnalyzer::analyzeYield(Object(Psalm\Internal\Analyzer\StatementsAnalyzer), Object(PhpParser\Node\Expr\Yield_), Object(Psalm\Context))
#1 /.../.composer/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/StatementsAnalyzer.php(522): Psalm\Internal\Analyzer\Statements\ExpressionAnalyzer::analyze(Object(Psalm\Internal\Analyzer\StatementsAnalyzer), Object(PhpParser\Node\Expr\Yield_), Object(Psalm\Context), false, Object(Psalm\Context))
#2 /.../.composer/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/FunctionLikeAnalyzer.php(561): Psalm\Internal\Analyzer\StatementsAnalyzer->analyze(Array, Object(Psalm\Context), Object(Psalm\Context), true)
#3 /.../.composer/ in /.../.composer/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/Statements/ExpressionAnalyzer.php on line 1259
```

**Comment by muglug** [comment]
Thanks for ticketing!
