### ISSUE TITLE
Fatal Phar error with latest release

### ISSUE THREAD

**Issue by ADmad** [vimeo/psalm#1452]
```
Analyzing /srv/sites/cake-apps/cakephp/src/Database/Schema/SqliteSchema.php
PHP Fatal error:  Uncaught Exception: Specified context ("_HumbugBox8872e19a0990\PhpMyAdmin\SqlParser\Contexts\Context_HumbugBox8872e19a0990\PhpMyAdmin\SqlParser\Contexts\ContextMySql50700") does not exist. in phar:///home/admad/.phive/phars/psalm.phar/vendor/phpmyadmin/sql-parser/src/Context.php:386
Stack trace:
#0 phar:///home/admad/.phive/phars/psalm.phar/vendor/phpmyadmin/sql-parser/src/Context.php(472): _HumbugBox8872e19a0990\PhpMyAdmin\SqlParser\Context::load()
#1 phar:///home/admad/.phive/phars/psalm.phar/.box/vendor/composer/ClassLoader.php(444): include('phar:///home/ad...')
#2 phar:///home/admad/.phive/phars/psalm.phar/.box/vendor/composer/ClassLoader.php(322): Composer\Autoload\includeFile('phar:///home/ad...')
#3 [internal function]: Composer\Autoload\ClassLoader->loadClass('_HumbugBox8872e...')
#4 phar:///home/admad/.phive/phars/psalm.phar/vendor/phpmyadmin/sql-parser/src/Lexer.php(453): spl_autoload_call('_HumbugBox8872e...')
#5 phar:///home/admad/.phive/phars/psalm.phar/vendor/phpmyadmin/sql-parser/src/Lexer.php in phar:///home/admad/.phive/phars/psalm.phar/vendor/phpmyadmin/sql-parser/src/Context.php on line 386

Fatal error: Uncaught Exception: Specified context ("_HumbugBox8872e19a0990\PhpMyAdmin\SqlParser\Contexts\Context_HumbugBox8872e19a0990\PhpMyAdmin\SqlParser\Contexts\ContextMySql50700") does not exist. in phar:///home/admad/.phive/phars/psalm.phar/vendor/phpmyadmin/sql-parser/src/Context.php:386
Stack trace:
#0 phar:///home/admad/.phive/phars/psalm.phar/vendor/phpmyadmin/sql-parser/src/Context.php(472): _HumbugBox8872e19a0990\PhpMyAdmin\SqlParser\Context::load()
#1 phar:///home/admad/.phive/phars/psalm.phar/.box/vendor/composer/ClassLoader.php(444): include('phar:///home/ad...')
#2 phar:///home/admad/.phive/phars/psalm.phar/.box/vendor/composer/ClassLoader.php(322): Composer\Autoload\includeFile('phar:///home/ad...')
#3 [internal function]: Composer\Autoload\ClassLoader->loadClass('_HumbugBox8872e...')
#4 phar:///home/admad/.phive/phars/psalm.phar/vendor/phpmyadmin/sql-parser/src/Lexer.php(453): spl_autoload_call('_HumbugBox8872e...')
#5 phar:///home/admad/.phive/phars/psalm.phar/vendor/phpmyadmin/sql-parser/src/Lexer.php in phar:///home/admad/.phive/phars/psalm.phar/vendor/phpmyadmin/sql-parser/src/Context.php on line 386
```

**Comment by ADmad** [comment]
New error using 3.1.3

```
Analyzing /srv/sites/cake-apps/cakephp/src/Database/Schema/PostgresSchema.php
PHP Fatal error:  Uncaught Cake\Cache\InvalidArgumentException: The "_cake_core_" cache configuration does not exist. in /srv/sites/cake-apps/cakephp/src/Cache/Cache.php:146
Stack trace:
#0 /srv/sites/cake-apps/cakephp/src/Cache/Cache.php(226): Cake\Cache\Cache::_buildEngine('_cake_core_')
#1 /srv/sites/cake-apps/cakephp/src/I18n/I18n.php(81): Cake\Cache\Cache::pool('_cake_core_')
#2 /srv/sites/cake-apps/cakephp/src/I18n/I18n.php(148): Cake\I18n\I18n::translators()
#3 /srv/sites/cake-apps/cakephp/src/I18n/functions.php(37): Cake\I18n\I18n::getTranslator()
#4 phar:///home/admad/.phive/phars/psalm.phar/vendor/phpmyadmin/sql-parser/src/Lexer.php(236): __('Unexpected char...')
#5 phar:///home/admad/.phive/phars/psalm.phar/vendor/phpmyadmin/sql-parser/src/Lexer.php(189): _HumbugBoxf4683abd9f8b\PhpMyAdmin\SqlParser\Lexer->lex()
#6 phar:///home/admad/.phive/phars/psalm.phar/vendor/phpmyadmin/sql-parser/src/Parser.php(190): _HumbugBoxf4683abd9f8b\PhpMyAdmin\SqlParser\Lexer->__construct('SELECT table_na...', false)
#7 phar:///home/adma in /srv/sites/cake-apps/cakephp/src/Cache/Cache.php on line 146
```
