### ISSUE TITLE
undefined offset in type analyzer leads to TypeError in isContainedBy

### ISSUE THREAD

**Issue by SignpostMarv** [vimeo/psalm#1474]
I've tried various workarounds, but https://github.com/SignpostMarv/Daft-Schema.org/blob/6dc9af7a21c0a6972e42758d46b7b4089415ebe6/Tests/DaftObjectSchemaOrg/DaftObjectFuzzingTest.php#L255 causes an undefined offset in psalm:
https://github.com/vimeo/psalm/blob/3704e75049703e861cda4585b66d49e3eb6810bd/src/Psalm/Internal/Analyzer/TypeAnalyzer.php#L1480 which then leads to a `TypeError` in https://github.com/vimeo/psalm/blob/3704e75049703e861cda4585b66d49e3eb6810bd/src/Psalm/Internal/Analyzer/TypeAnalyzer.php#L63

> Notice: Undefined offset: 2 in .\vendor\vimeo\psalm\src\Psalm\Internal\Analyzer\TypeAnalyzer.php on line 1480
> PHP Fatal error:  Uncaught TypeError: Argument 3 passed to Psalm\Internal\Analyzer\TypeAnalyzer::isContainedBy() must be an instance of Psalm\Type\Union, null given, called in .\vendor\vimeo\psalm\src\Psalm\Internal\Analyzer\TypeAnalyzer.php on line 1502 and defined in .\vendor\vimeo\psalm\src\Psalm\Internal\Analyzer\TypeAnalyzer.php:63
> Stack trace:
> #0 .\vendor\vimeo\psalm\src\Psalm\Internal\Analyzer\TypeAnalyzer.php(1502): Psalm\Internal\Analyzer\TypeAnalyzer::isContainedBy(Object(Psalm\Codebase), Object(Psalm\Type\Union), NULL, false, false, true, NULL, NULL, false, NULL, false)
> #1 .\vendor\vimeo\psalm\src\Psalm\Internal\Analyzer\TypeAnalyzer.php(557): Psalm\Internal\Analyzer\TypeAnalyzer::isMatchingTypeContainedBy(Object(Psalm\Codebase), Object(Psalm\Type\Atomic\TArray), Object(Psalm\Type\Atomic\TArray), true, NULL, NULL, false, false)
> #2 .\v in .\vendor\vimeo\psalm\src\Psalm\Internal\Analyzer\TypeAnalyzer.php on line 63

> Fatal error: Uncaught TypeError: Argument 3 passed to Psalm\Internal\Analyzer\TypeAnalyzer::isContainedBy() must be an instance of Psalm\Type\Union, null given, called in .\vendor\vimeo\psalm\src\Psalm\Internal\Analyzer\TypeAnalyzer.php on line 1502 and defined in .\vendor\vimeo\psalm\src\Psalm\Internal\Analyzer\TypeAnalyzer.php:63
> Stack trace:
> #0 .\vendor\vimeo\psalm\src\Psalm\Internal\Analyzer\TypeAnalyzer.php(1502): Psalm\Internal\Analyzer\TypeAnalyzer::isContainedBy(Object(Psalm\Codebase), Object(Psalm\Type\Union), NULL, false, false, true, NULL, NULL, false, NULL, false)
> #1 .\vendor\vimeo\psalm\src\Psalm\Internal\Analyzer\TypeAnalyzer.php(557): Psalm\Internal\Analyzer\TypeAnalyzer::isMatchingTypeContainedBy(Object(Psalm\Codebase), Object(Psalm\Type\Atomic\TArray), Object(Psalm\Type\Atomic\TArray), true, NULL, NULL, false, false)
> #2 .\v in .\vendor\vimeo\psalm\src\Psalm\Internal\Analyzer\TypeAnalyzer.php on line 63

**Comment by SignpostMarv** [comment]
looks like i type-hinted something wrongly and broke psalm:P https://github.com/SignpostMarv/Daft-Schema.org/commit/7172062104faa5bd7d346e43c9fde55873afc91a#diff-aba7e1ae04c4d190393723926f96c1ba
