### ISSUE TITLE
PHP Fatal error:  Uncaught InvalidArgumentException: Could not get file storage for (file)

### ISSUE THREAD

**Issue by Firehed** [vimeo/psalm#1526]
I'm trying to get Psalm set up for the first time on my codebase (PHPStan and PHPCS already happily run), and I'm getting a crash. This is using the default config with `psalm --init`.

Psalm 3.2.5@d8411dc510f948dea463953d87a71d65e12fade8

`--debug-by-line` output:
```
...
Analyzing /Users/firehed/dev/github/parli/normalizer/src/Endpoints/Meta/All.php
/Users/firehed/dev/github/parli/normalizer/src/Endpoints/Meta/All.php:2
/Users/firehed/dev/github/parli/normalizer/vendor/firehed/api/src/Traits/Input/NoOptional.php:11
...
/Users/firehed/dev/github/parli/normalizer/src/Endpoints/Meta/All.php:55
/Users/firehed/dev/github/parli/normalizer/src/Endpoints/Meta/All.php:57
  checking __endpoint_list__.php
PHP Fatal error:  Uncaught InvalidArgumentException: Could not get file storage for /users/firehed/dev/github/parli/normalizer/__endpoint_list__.php in /Users/firehed/dev/github/parli/normalizer/vendor/vimeo/psalm/src/Psalm/Internal/Provider/FileStorageProvider.php:47
Stack trace:
#0 /Users/firehed/dev/github/parli/normalizer/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/FileAnalyzer.php(123): Psalm\Internal\Provider\FileStorageProvider->get('/users/firehed/...')
#1 /Users/firehed/dev/github/parli/normalizer/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/Statements/Expression/IncludeAnalyzer.php(121): Psalm\Internal\Analyzer\FileAnalyzer->analyze(Object(Psalm\Context), false, NULL)
#2 /Users/firehed/dev/github/parli/normalizer/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/Statements/ExpressionAnalyzer.php(526): Psalm\Internal\Analyzer\Statements\Expression\IncludeAnalyzer::analyze(Object(Psalm\Internal\Analyzer\StatementsAnalyzer), Object(PhpParser\Node\Expr\Include_), Object(Psalm\Context), NULL)
#3 /Users/firehed/dev/githu in /Users/firehed/dev/github/parli/normalizer/vendor/vimeo/psalm/src/Psalm/Internal/Provider/FileStorageProvider.php on line 47
```

The source of the file causing a crash:
```php
    protected function getEndpoints()
    {
        $listFile = '__endpoint_list__.php';
        if (!file_exists($listFile)) {
            throw new RuntimeException('Endpoint list not found');
        }
        $data = include $listFile; // <-- this line
```

The file being included is auto-generated, and simply returns an array (like many config definition files). The file does exist and works fine, but is not something Composer's autoloader is aware of.

**Comment by muglug** [comment]
Thanks, I'll have a look

**Comment by muglug** [comment]
Is it possible that the file existed during one of Psalm's runs?

**Comment by muglug** [comment]
And does it work if you run with `--no-cache`?

**Comment by muglug** [comment]
Thanks, I figured it out.

Psalm has two steps - scanning and analysis. The scanning step ideally crawls all files that are candidates for analysis (and including a file makes it a candidate). It captures `include "foo.php"` but misses `include $foo`.

The analysis step understands files defined in variables, but was choking because that file had not previously been scanned. The fix just tells Psalm to skip analysing `include` files if they haven't been scanned.

**Comment by Firehed** [comment]
Thanks for looking into this so quickly! To answer your previous questions: the file being included did exist the whole time (and was unchanged). The error occurred on my very first run of Psalm, which I assume would have the same behavior as `—no-cache`.

**Comment by muglug** [comment]
Yup - the master branch should be good for you - let me know if it doesn’t work

**Comment by Firehed** [comment]
I just pulled master `Psalm dev-master@9447cd2d98ba943ea9b47e5d1777865608794f70` - the same error occurs by default (`vendor/bin/psalm`). If I run with `--no-cache`, it makes it through just fine.

Even after `--clear-cache`, it still fails with the bare command. It will only succeed with `--no-cache`.

**Comment by muglug** [comment]
@Firehed would you be able to reproduce in a separate repo?

**Comment by Firehed** [comment]
Yeah, just managed to. https://gist.github.com/Firehed/c4492b4c1cbdb904c6bcd424a1628e30

```
$ vendor/bin/psalm --version
Psalm dev-master@41c722448a737c2227124ca3693d9e85811f2eb6

14:22:08 firehed@Erics-MacBook-Pro ~/dev/github/parli/psalm-repro [0] $ vendor/bin/psalm --no-cache
Scanning files...
Analyzing files...

INFO: MissingReturnType - src/Bar.php:7:21 - Method Foo\Bar::baz does not have a return type
    public function baz()


------------------------------
No errors found!
------------------------------
1 other issues found.
You can hide them with --show-info=false
------------------------------

Checks took 0.18 seconds and used 24.174MB of memory
Psalm was able to infer types for 66.6667% of the codebase

14:22:11 firehed@Erics-MacBook-Pro ~/dev/github/parli/psalm-repro [0] $ vendor/bin/psalm --clear-cache
Cache directory deleted

14:22:39 firehed@Erics-MacBook-Pro ~/dev/github/parli/psalm-repro [0] $ vendor/bin/psalm
Scanning files...
Analyzing files...
PHP Fatal error:  Uncaught InvalidArgumentException: Could not get file storage for /users/firehed/dev/github/parli/psalm-repro/list.php in /Users/firehed/dev/github/parli/psalm-repro/vendor/vimeo/psalm/src/Psalm/Internal/Provider/FileStorageProvider.php:47
Stack trace:
#0 /Users/firehed/dev/github/parli/psalm-repro/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/FileAnalyzer.php(123): Psalm\Internal\Provider\FileStorageProvider->get('/users/firehed/...')
#1 /Users/firehed/dev/github/parli/psalm-repro/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/Statements/Expression/IncludeAnalyzer.php(122): Psalm\Internal\Analyzer\FileAnalyzer->analyze(Object(Psalm\Context), false, NULL)
#2 /Users/firehed/dev/github/parli/psalm-repro/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/Statements/ExpressionAnalyzer.php(526): Psalm\Internal\Analyzer\Statements\Expression\IncludeAnalyzer::analyze(Object(Psalm\Internal\Analyzer\StatementsAnalyzer), Object(PhpParser\Node\Expr\Include_), Object(Psalm\Context), NULL)
#3 /Users/firehed/dev/github/parli/ in /Users/firehed/dev/github/parli/psalm-repro/vendor/vimeo/psalm/src/Psalm/Internal/Provider/FileStorageProvider.php on line 47

Fatal error: Uncaught InvalidArgumentException: Could not get file storage for /users/firehed/dev/github/parli/psalm-repro/list.php in /Users/firehed/dev/github/parli/psalm-repro/vendor/vimeo/psalm/src/Psalm/Internal/Provider/FileStorageProvider.php:47
Stack trace:
#0 /Users/firehed/dev/github/parli/psalm-repro/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/FileAnalyzer.php(123): Psalm\Internal\Provider\FileStorageProvider->get('/users/firehed/...')
#1 /Users/firehed/dev/github/parli/psalm-repro/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/Statements/Expression/IncludeAnalyzer.php(122): Psalm\Internal\Analyzer\FileAnalyzer->analyze(Object(Psalm\Context), false, NULL)
#2 /Users/firehed/dev/github/parli/psalm-repro/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/Statements/ExpressionAnalyzer.php(526): Psalm\Internal\Analyzer\Statements\Expression\IncludeAnalyzer::analyze(Object(Psalm\Internal\Analyzer\StatementsAnalyzer), Object(PhpParser\Node\Expr\Include_), Object(Psalm\Context), NULL)
#3 /Users/firehed/dev/github/parli/ in /Users/firehed/dev/github/parli/psalm-repro/vendor/vimeo/psalm/src/Psalm/Internal/Provider/FileStorageProvider.php on line 47
```

**Comment by muglug** [comment]
Awesome, thanks!

**Comment by Firehed** [comment]
I can confirm it's now fixed :) Thank you!
