### ISSUE TITLE
Fatal error when calling internal method during property set checks

### ISSUE THREAD

**Issue by sebastianbergmann** [vimeo/psalm#1556]
```
$ git clone git@github.com:sebastianbergmann/phpunit.git
$ cd phpunit
$ composer install
$ cd ..
```
```
$ git clone git@github.com:vimeo/psalm.git
$ cd psalm
$ composer install
$ cd ..
```
```
$ cd phpunit
$ ../psalm/psalm --init
$ ../psalm/psalm --stats
Scanning files...
Analyzing files...
PHP Fatal error:  Uncaught UnexpectedValueException: Could not find file for exception in /usr/local/src/psalm/src/Psalm/Internal/Codebase/Scanner.php:256
Stack trace:
#0 /usr/local/src/psalm/src/Psalm/Internal/Analyzer/ProjectAnalyzer.php(786): Psalm\Internal\Codebase\Scanner->getClassLikeFilePath('exception')
#1 /usr/local/src/psalm/src/Psalm/Internal/Analyzer/ProjectAnalyzer.php(811): Psalm\Internal\Analyzer\ProjectAnalyzer->getFileAnalyzerForClassLike('Exception')
#2 /usr/local/src/psalm/src/Psalm/Internal/Analyzer/Statements/Expression/CallAnalyzer.php(198): Psalm\Internal\Analyzer\ProjectAnalyzer->getMethodMutations('Exception::gett...', Object(Psalm\Context), '/usr/local/src/...', 'src/Framework/U...')
#3 /usr/local/src/psalm/src/Psalm/Internal/Analyzer/Statements/Expression/Call/MethodCallAnalyzer.php(864): Psalm\Internal\Analyzer\Statements\Expression\CallAnalyzer::collectSpecialInformation(Object(Psalm\Internal\Analyzer\MethodAnalyzer), 'getTrace', Object(Psalm\Context))
#4 /usr/local/src/psalm/src/Psalm/Internal/Ana in /usr/local/src/psalm/src/Psalm/Internal/Codebase/Scanner.php on line 256

Fatal error: Uncaught UnexpectedValueException: Could not find file for exception in /usr/local/src/psalm/src/Psalm/Internal/Codebase/Scanner.php:256
Stack trace:
#0 /usr/local/src/psalm/src/Psalm/Internal/Analyzer/ProjectAnalyzer.php(786): Psalm\Internal\Codebase\Scanner->getClassLikeFilePath('exception')
#1 /usr/local/src/psalm/src/Psalm/Internal/Analyzer/ProjectAnalyzer.php(811): Psalm\Internal\Analyzer\ProjectAnalyzer->getFileAnalyzerForClassLike('Exception')
#2 /usr/local/src/psalm/src/Psalm/Internal/Analyzer/Statements/Expression/CallAnalyzer.php(198): Psalm\Internal\Analyzer\ProjectAnalyzer->getMethodMutations('Exception::gett...', Object(Psalm\Context), '/usr/local/src/...', 'src/Framework/U...')
#3 /usr/local/src/psalm/src/Psalm/Internal/Analyzer/Statements/Expression/Call/MethodCallAnalyzer.php(864): Psalm\Internal\Analyzer\Statements\Expression\CallAnalyzer::collectSpecialInformation(Object(Psalm\Internal\Analyzer\MethodAnalyzer), 'getTrace', Object(Psalm\Context))
#4 /usr/local/src/psalm/src/Psalm/Internal/Ana in /usr/local/src/psalm/src/Psalm/Internal/Codebase/Scanner.php on line 256
```

**Comment by muglug** [comment]
Broken by https://github.com/vimeo/psalm/commit/5c76ab35c8952e6f8f6363c66e0a0f721b7b99cd, reproduced with https://psalm.dev/r/9746909414

**Comment by muglug** [comment]
Thanks for ticketing. I'll add phpunit to the list of packages I test against prior to release.

This was broken when I allowed property initialisation checks to follow `protected` and `public`-ly declared methods so Psalm can analyse code like this:
```php
<?php
  
class C {
  public string $s;
  
  public function __construct() {
    $this->setS();
  }
  
  public function setS() : void {
    $this->s = "hello";
  }
}

class D extends C { // error appears here
  public function setS() : void {}
}
```

https://psalm.dev/r/aaa46f0340
