### ISSUE TITLE
Uncaught UnexpectedValueException: Could not find file for exception

### ISSUE THREAD

**Issue by sebastianbergmann** [vimeo/psalm#1579]
Psalm 3.2.7 crashes when trying to analyse PHPUnit (master):
```
$ ./tools/psalm --version
Psalm 3.2.7.0@6e010d9db95275725e5ad6409c387eb173091f72
```
```
$ ./tools/psalm --init      
Config file created successfully. Please re-run psalm.
```
```
$ ./tools/psalm
Scanning files...
Analyzing files...
PHP Fatal error:  Uncaught UnexpectedValueException: Could not find file for exception in phar:///usr/local/src/phpunit/tools/psalm/src/Psalm/Internal/Codebase/Scanner.php:224
Stack trace:
#0 phar:///usr/local/src/phpunit/tools/psalm/src/Psalm/Internal/Analyzer/ProjectAnalyzer.php(598): _HumbugBox1b24ec6c5e06\Psalm\Internal\Codebase\Scanner->getClassLikeFilePath('exception')
#1 phar:///usr/local/src/phpunit/tools/psalm/src/Psalm/Internal/Analyzer/ProjectAnalyzer.php(611): _HumbugBox1b24ec6c5e06\Psalm\Internal\Analyzer\ProjectAnalyzer->getFileAnalyzerForClassLike('Exception')
#2 phar:///usr/local/src/phpunit/tools/psalm/src/Psalm/Internal/Analyzer/Statements/Expression/CallAnalyzer.php(141): _HumbugBox1b24ec6c5e06\Psalm\Internal\Analyzer\ProjectAnalyzer->getMethodMutations('Exception::gett...', Object(_HumbugBox1b24ec6c5e06\Psalm\Context), '/usr/local/src/...', 'src/Framework/E...')
#3 phar:///usr/local/src/phpunit/tools/psalm/src/Psalm/Internal/Analyzer/Statements/Expression/Call/MethodCallAnalyzer.php(466): _HumbugBox1b24ec6c in phar:///usr/local/src/phpunit/tools/psalm/src/Psalm/Internal/Codebase/Scanner.php on line 224

Fatal error: Uncaught UnexpectedValueException: Could not find file for exception in phar:///usr/local/src/phpunit/tools/psalm/src/Psalm/Internal/Codebase/Scanner.php:224
Stack trace:
#0 phar:///usr/local/src/phpunit/tools/psalm/src/Psalm/Internal/Analyzer/ProjectAnalyzer.php(598): _HumbugBox1b24ec6c5e06\Psalm\Internal\Codebase\Scanner->getClassLikeFilePath('exception')
#1 phar:///usr/local/src/phpunit/tools/psalm/src/Psalm/Internal/Analyzer/ProjectAnalyzer.php(611): _HumbugBox1b24ec6c5e06\Psalm\Internal\Analyzer\ProjectAnalyzer->getFileAnalyzerForClassLike('Exception')
#2 phar:///usr/local/src/phpunit/tools/psalm/src/Psalm/Internal/Analyzer/Statements/Expression/CallAnalyzer.php(141): _HumbugBox1b24ec6c5e06\Psalm\Internal\Analyzer\ProjectAnalyzer->getMethodMutations('Exception::gett...', Object(_HumbugBox1b24ec6c5e06\Psalm\Context), '/usr/local/src/...', 'src/Framework/E...')
#3 phar:///usr/local/src/phpunit/tools/psalm/src/Psalm/Internal/Analyzer/Statements/Expression/Call/MethodCallAnalyzer.php(466): _HumbugBox1b24ec6c in phar:///usr/local/src/phpunit/tools/psalm/src/Psalm/Internal/Codebase/Scanner.php on line 224
```

**Comment by sebastianbergmann** [comment]
Sorry for the noise, with 3.2.9 it works. Somehow thought for a minute that 3.2.7 was latest version.

**Comment by muglug** [comment]
No worries! I'm also going to borrow @nikic's script crawl Packagist to ensure Psalm doesn't error on any of the most popular frameworks
