### ISSUE TITLE
Fatal error under 0.3.43

### ISSUE THREAD

**Issue by erunion** [vimeo/psalm#161]
Upgrading from 0.2 to 0.3 and I get this when running analysis on my library:

```
PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Psalm\EffectsAnalyser::getReturnTypes() must be of the type array, null given, called in /code/mill/vendor/vimeo/psalm/src/Psalm/Checker/FunctionLikeChecker.php on line 989 and defined in /code/mill/vendor/vimeo/psalm/src/Psalm/EffectsAnalyser.php:22

Stack trace:
#0 /code/mill/vendor/vimeo/psalm/src/Psalm/Checker/FunctionLikeChecker.php(989): Psalm\EffectsAnalyser::getReturnTypes(NULL, Array, NULL, true)
#1 /code/mill/vendor/vimeo/psalm/src/Psalm/Checker/ClassLikeChecker.php(798): Psalm\Checker\FunctionLikeChecker->verifyReturnType(false, Object(Psalm\Type\Union), 'Mill\\Parser\\Ann...', Object(Psalm\CodeLocation), NULL)
#2 /code/mill/vendor/vimeo/psalm/src/Psalm/Checker/ClassLikeChecker.php(600): Psalm\Checker\ClassLikeChecker->analyzeClassMethod(Object(PhpParser\Node\Stmt\ClassMethod), Object(Psalm\Checker\ClassChecker), Object(Psalm\Context), Object(Psalm\Context), false)
#3 /code/ in /code/mill/vendor/vimeo/psalm/src/Psalm/EffectsAnalyser.php on line 22
```

**Comment by muglug** [comment]
Huh, I cloned the repo and updated Psalm to 0.3.43 (and PHP Parser to 3.x) and didn't see that error.

**Comment by muglug** [comment]
Do you still see it if you clear out Psalm's cache?

**Comment by erunion** [comment]
Yep, clearing the cache fixed it, and also magically made an E_WARNING error go away that started happening on 0.3.

Should definitely add in a cache clearing command at some point.

Good find.
