### ISSUE TITLE
Fatal error when running attempting to fix  LessSpecificReturnType in psalm codebase

### ISSUE THREAD

**Issue by bdsl** [vimeo/psalm#1693]
Using the latest master commit, 442c307b30, run:

`
/psalter --issues=LessSpecificReturnType --debug
`

Final lines of output are:

```
Analyzing /home/barney/development/psalm/src/Psalm/Internal/LanguageServer/ClientHandler.php
Parsing /home/barney/development/psalm/src/Psalm/Internal/LanguageServer/ClientHandler.php
PHP Fatal error:  Uncaught Error: Call to undefined method PhpParser\Node\Expr\Closure::isFinal() in /home/barney/development/psalm/src/Psalm/Internal/Analyzer/FunctionLike/ReturnTypeAnalyzer.php:750
Stack trace:
#0 /home/barney/development/psalm/src/Psalm/Internal/Analyzer/FunctionLike/ReturnTypeAnalyzer.php(491): Psalm\Internal\Analyzer\FunctionLike\ReturnTypeAnalyzer::addOrUpdateReturnType(Object(PhpParser\Node\Expr\Closure), Object(Psalm\Internal\Analyzer\ProjectAnalyzer), Object(Psalm\Type\Union), Object(Psalm\Internal\Analyzer\StatementsAnalyzer), Object(Psalm\Internal\Analyzer\ClosureAnalyzer), false, Object(Psalm\Storage\FunctionLikeStorage))
#1 /home/barney/development/psalm/src/Psalm/Internal/Analyzer/FunctionLikeAnalyzer.php(945): Psalm\Internal\Analyzer\FunctionLike\ReturnTypeAnalyzer::verifyReturnType(Object(PhpParser\Node\Expr\Closure), Object(Psalm\Internal\Analyzer\StatementsAnalyzer), Object(Psalm\Internal\Analyzer\ClosureAnalyzer), Object(Psalm\Type\Union), 'Psalm\\Internal\\...', Object(Psalm\CodeLocation),  in /home/barney/development/psalm/src/Psalm/Internal/Analyzer/FunctionLike/ReturnTypeAnalyzer.php on line 750

Fatal error: Uncaught Error: Call to undefined method PhpParser\Node\Expr\Closure::isFinal() in /home/barney/development/psalm/src/Psalm/Internal/Analyzer/FunctionLike/ReturnTypeAnalyzer.php:750
Stack trace:
#0 /home/barney/development/psalm/src/Psalm/Internal/Analyzer/FunctionLike/ReturnTypeAnalyzer.php(491): Psalm\Internal\Analyzer\FunctionLike\ReturnTypeAnalyzer::addOrUpdateReturnType(Object(PhpParser\Node\Expr\Closure), Object(Psalm\Internal\Analyzer\ProjectAnalyzer), Object(Psalm\Type\Union), Object(Psalm\Internal\Analyzer\StatementsAnalyzer), Object(Psalm\Internal\Analyzer\ClosureAnalyzer), false, Object(Psalm\Storage\FunctionLikeStorage))
#1 /home/barney/development/psalm/src/Psalm/Internal/Analyzer/FunctionLikeAnalyzer.php(945): Psalm\Internal\Analyzer\FunctionLike\ReturnTypeAnalyzer::verifyReturnType(Object(PhpParser\Node\Expr\Closure), Object(Psalm\Internal\Analyzer\StatementsAnalyzer), Object(Psalm\Internal\Analyzer\ClosureAnalyzer), Object(Psalm\Type\Union), 'Psalm\\Internal\\...', Object(Psalm\CodeLocation),  in /home/barney/development/psalm/src/Psalm/Internal/Analyzer/FunctionLike/ReturnTypeAnalyzer.php on line 750
```

Once #1687 is merged the same crash will also happen with `./psalter --issues=all`

**Comment by muglug** [comment]
What version of PHP are you using?

**Comment by muglug** [comment]
Oh nvm
