### ISSUE TITLE
Errors when running Psalm on Repository

### ISSUE THREAD

**Issue by prondubuisi** [vimeo/psalm#1713]
Hello , I am running Psalm on this repository https://github.com/civicrm/civicrm-core
I have the following errors https://pastebin.com/x8jhQ6H9

```
coolife@coolife:~/git-repos/civicrm-buildkit-docker/build/dmaster/sites/all/modules/civicrm$ ./vendor/bin/psalm --init
Config file created successfully. Please re-run psalm.
coolife@coolife:~/git-repos/civicrm-buildkit-docker/build/dmaster/sites/all/modules/civicrm$ ./vendor/bin/psalm
Scanning files...
Analyzing files...
PHP Fatal error:  Uncaught UnexpectedValueException: $this->isVisible should be in scope in /home/coolife/git-repos/civicrm-buildkit-docker/build/dmaster/sites/all/modules/civicrm/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/ClassAnalyzer.php:1007
Stack trace:
#0 /home/coolife/git-repos/civicrm-buildkit-docker/build/dmaster/sites/all/modules/civicrm/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/ClassAnalyzer.php(700): Psalm\Internal\Analyzer\ClassAnalyzer->checkPropertyInitialization(Object(Psalm\Codebase), Object(Psalm\Config), Object(Psalm\Storage\ClassLikeStorage), Object(Psalm\Context), Object(Psalm\Context), Object(Psalm\Internal\Analyzer\MethodAnalyzer))
#1 /home/coolife/git-repos/civicrm-buildkit-docker/build/dmaster/sites/all/modules/civicrm/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/FileAnalyzer.php(174): Psalm\Internal\Analyzer\ClassAnalyzer->analyze(Object(Psalm\Context), Object(Psalm\Context))
#2 /home/coolife/git-repos/civicrm-buildkit-docker/build/dmaster/sites/all/modules/civicrm/vendor/vimeo/psalm/src/Ps in /home/coolife/git-repos/civicrm-buildkit-docker/build/dmaster/sites/all/modules/civicrm/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/ClassAnalyzer.php on line 1007
 
Fatal error: Uncaught UnexpectedValueException: $this->isVisible should be in scope in /home/coolife/git-repos/civicrm-buildkit-docker/build/dmaster/sites/all/modules/civicrm/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/ClassAnalyzer.php:1007
Stack trace:
#0 /home/coolife/git-repos/civicrm-buildkit-docker/build/dmaster/sites/all/modules/civicrm/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/ClassAnalyzer.php(700): Psalm\Internal\Analyzer\ClassAnalyzer->checkPropertyInitialization(Object(Psalm\Codebase), Object(Psalm\Config), Object(Psalm\Storage\ClassLikeStorage), Object(Psalm\Context), Object(Psalm\Context), Object(Psalm\Internal\Analyzer\MethodAnalyzer))
#1 /home/coolife/git-repos/civicrm-buildkit-docker/build/dmaster/sites/all/modules/civicrm/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/FileAnalyzer.php(174): Psalm\Internal\Analyzer\ClassAnalyzer->analyze(Object(Psalm\Context), Object(Psalm\Context))
#2 /home/coolife/git-repos/civicrm-buildkit-docker/build/dmaster/sites/all/modules/civicrm/vendor/vimeo/psalm/src/Ps in /home/coolife/git-repos/civicrm-buildkit-docker/build/dmaster/sites/all/modules/civicrm/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/ClassAnalyzer.php on line 1007
coolife@coolife:~/git-repos/civicrm-buildkit-docker/build/dmaster/sites/all/modules/civicrm$
```
passing `--debug` also return the same errors as seen[ here ](https://gist.githubusercontent.com/prondubuisi/19abf949b3965b47a51184cd1fdf7d74/raw/24fe28981a4bd174b89713065f04ef8e29227502/--debug%2520log) any help? this is what my psalm.xml looks like 

https://pastebin.com/M1qW2R7U

**Comment by muglug** [comment]
Sorry about that - reproduced with
```php
class A {
  /** @var bool */
  private $foo;
  
  public function __construct() {
    unset($this->foo);
  }
}
```

Can be fixed by giving the property a default (`private $foo = false;`)

**Comment by prondubuisi** [comment]
Hello @muglug, Thanks for the fix I have been trying to get this fix to my local Psalm installation to no avail
I was thinking `composer update vimeo/psalm` would have done the trick 
How do I get the latest Psalm fix to the package?

**Comment by muglug** [comment]
you can run `composer remove --dev vimeo/psalm` then `composer install vimeo/psalm:dev-master`

**Comment by andrew-demb** [comment]
@prondubuisi, you may temporary specify in composer.json `vimeo/psalm:dev-master` until it will be released

**Comment by prondubuisi** [comment]
Thanks, am on it
