### ISSUE TITLE
Uncaught UnexpectedValueException

### ISSUE THREAD

**Issue by ssnepenthe** [vimeo/psalm#184]
I am loving psalm - thanks for all the hard work!

Currently I am getting an uncaught `UnexpectedValueException` which seems to be related to my use of the `DOMImplementation` class.

As a simplified test case try the following against the default config from `psalm --init`:

```PHP
<?php

class SomeClass
{
    /**
     * @return void
     */
    public function someMethod()
    {
        $implementation = new DOMImplementation;
    }
}
```

When running `./vendor/bin/psalm src/SomeClass.php` I am seeing the following:

```
PHP Notice:  Undefined offset: 1 in /path/to/project/vendor/vimeo/psalm/src/Psalm/Checker/MethodChecker.php on line 387
Fatal error: Uncaught UnexpectedValueException: $class_storage should not be null for  in /path/to/project/vendor/vimeo/psalm/src/Psalm/Checker/MethodChecker.php:392
Stack trace:
#0 /path/to/project/vendor/vimeo/psalm/src/Psalm/Checker/MethodChecker.php(462): Psalm\Checker\MethodChecker::getStorage('')
#1 /path/to/project/vendor/vimeo/psalm/src/Psalm/Checker/Statements/Expression/CallChecker.php(556): Psalm\Checker\MethodChecker::checkMethodVisibility('DOMImplementati...', 'SomeClass', Object(Psalm\Checker\MethodChecker), Object(Psalm\CodeLocation), Array)
#2 /path/to/project/vendor/vimeo/psalm/src/Psalm/Checker/Statements/ExpressionChecker.php(186): Psalm\Checker\Statements\Expression\CallChecker::analyzeNew(Object(Psalm\Checker\StatementsChecker), Object(PhpParser\Node\Expr\New_), Object(Psalm\Context))
#3 /path/to/project/vendor/vimeo/psalm/src/Psalm/Checker/Statements/Expression/AssignmentChecker.php(95): Psalm\Checker\Statements in /path/to/project/vendor/vimeo/psalm/src/Psalm/Checker/MethodChecker.php on line 392
```

I am on PHP 7.0.20 and Psalm 0.3.46

**Comment by muglug** [comment]
Even just
```php
<?php
new DOMImplementation();
```
is enough to reproduce

**Comment by muglug** [comment]
Problem is that DomImplementation doesn't have a reflected `__construct` function, even though it's documented [here](http://php.net/manual/en/domimplementation.construct.php).
