### ISSUE TITLE
UnexpectedValueException: Function ... should be defined (when function exists in Reflection)

### ISSUE THREAD

**Issue by TysonAndre** [vimeo/psalm#1859]
```php
<?php

if (!function_exists('igbinary_serialize')){
    function igbinary_serialize($data){
        return 'placeholder';
    }
}
```

If you don't have igbinary installed, other functions also cause this crash

```php
<?php

if (!function_exists('in_array')) {
    function in_array($a, $b) {
        return true;
    }
}
```

This results in the following uncaught error with af1decf30c3d4212e054fc514314b8c790f3c02a
It seems to be related to the function being available from reflection - If it's not from an installed extension, I don't see this error

```

Scanning files...
Analyzing files...


Fatal error: Uncaught UnexpectedValueException: Function igbinary_serialize should be defined in /path/to/psalm_example_project/src/example.php in /path/to/psalm/src/Psalm/Internal/Analyzer/FunctionAnalyzer.php:30
Stack trace:
#0 /path/to/psalm/src/Psalm/Internal/Analyzer/StatementsAnalyzer.php(153): Psalm\Internal\Analyzer\FunctionAnalyzer->__construct(Object(PhpParser\Node\Stmt\Function_), Object(Psalm\Internal\Analyzer\FileAnalyzer))
#1 /path/to/psalm/src/Psalm/Internal/Analyzer/Statements/Block/IfAnalyzer.php(578): Psalm\Internal\Analyzer\StatementsAnalyzer->analyze(Array, Object(Psalm\Context))
#2 /path/to/psalm/src/Psalm/Internal/Analyzer/Statements/Block/IfAnalyzer.php(384): Psalm\Internal\Analyzer\Statements\Block\IfAnalyzer::analyzeIfBlock(Object(Psalm\Internal\Analyzer\StatementsAnalyzer), Object(PhpParser\Node\Stmt\If_), Object(Psalm\Internal\Scope\IfScope), Object(Psalm\Context), Object(Psalm\Context), Object(Psalm\Context), Array)
#3 / in /path/to/psalm/src/Psalm/Internal/Analyzer/FunctionAnalyzer.php on line 30
```

**Comment by muglug** [comment]
Sorry, I didn't quite think that feature through

**Comment by TysonAndre** [comment]
Thanks!

**Comment by muglug** [comment]
This is now in a release (3.4.7)

**Comment by TysonAndre** [comment]
A minor comment on the release notes: There's two different function names, but they should be the same name on both lines to demonstrate this?

```
if (!function_exists("some_function")) {
  function in_array() {...}
}
```

**Comment by muglug** [comment]
oops, fixed
