### ISSUE TITLE
LogicException scanning wordpress-importer on bedrock

### ISSUE THREAD

**Issue by omivore** [vimeo/psalm#1925]
When running Psalm on the WordPress-Importer plugin, Psalm crashes with a LogicException. Based on the error, it looks like it's actually a PhpParser error, but I don't know enough to be sure and at least wanted to file a bug here before going there.
To reproduce:
1. New directory
2. Copy in the `wordpress-importer` folder that you get from the Download link at the [plugin site](https://wordpress.org/plugins/wordpress-importer/#developers)
2. `composer init -n; composer require --dev vimeo/psalm; composer install`
3. `./vendor/bin/psalm --init`
4. Edit `psalm.xml` to have `projectFiles` like so
```
    <projectFiles>
        <directory name="wordpress-importer" />
        <ignoreFiles>
            <directory name="vendor" />
        </ignoreFiles>
    </projectFiles>
```
5. Run `./vendor/bin/psalm` and witness a crash that spits this out with a `--debug-by-line`:
```
Registering autoloaded files
Using composer to locate file for Symfony\Polyfill\Ctype\Ctype
Using composer to locate file for Amp\Promise
Using reflection to get metadata for Generator
Using reflection to get metadata for Throwable
Using composer to locate file for Amp\Failure
Using composer to locate file for Amp\Coroutine
Using reflection to locate file for React\Promise\PromiseInterface
Using composer to locate file for Amp\Success
Using composer to locate file for Amp\Loop
Using reflection to get metadata for Error
Using composer to locate file for Amp\Deferred
Using composer to locate file for Amp\TimeoutException
Using reflection to get metadata for Countable
Using reflection to get metadata for SimpleXMLElement
Using reflection to locate file for ResourceBundle
Using composer to locate file for Amp\MultiReasonException
Using composer to locate file for Amp\Iterator
Using reflection to get metadata for Traversable
Using composer to locate file for Amp\Producer
Using composer to locate file for Amp\Delayed
Using composer to locate file for Amp\Emitter
Using reflection to get metadata for TypeError
Using composer to locate file for Symfony\Polyfill\Mbstring\Mbstring
Using composer to locate file for Symfony\Polyfill\Php73\Php73
Using composer to locate file for Amp\ByteStream\InputStream
Using composer to locate file for Amp\ByteStream\OutputStream
Using composer to locate file for Amp\ByteStream\ResourceInputStream
Using composer to locate file for Amp\ByteStream\ResourceOutputStream
Using composer to locate file for Webmozart\PathUtil\Path
Using reflection to get metadata for Exception
Using composer to locate file for Amp\Internal\Placeholder
Using composer to locate file for Amp\Loop\Driver
Using composer to locate file for Amp\Loop\DriverFactory
Using composer to locate file for Amp\CallableMaker
Using composer to locate file for Amp\Internal\Producer
Using reflection to get metadata for SplQueue
Scanning /Users/jason/Fresh/psalm-integration/importer-debug/vendor/amphp/amp/lib/Internal/Placeholder.php
Scanning /Users/jason/Fresh/psalm-integration/importer-debug/vendor/amphp/amp/lib/CallableMaker.php
Scanning /Users/jason/Fresh/psalm-integration/importer-debug/vendor/amphp/amp/lib/Internal/Producer.php
Using composer to locate file for Amp\Internal\ResolutionQueue
Using composer to locate file for Amp\Loop\Watcher
Using reflection to get metadata for ReflectionClass
Using reflection to get metadata for ReflectionMethod
Using reflection to get metadata for ReflectionProperty
Using reflection to get metadata for ReflectionClassConstant
Using reflection to get metadata for ReflectionExtension
Using reflection to get metadata for ReflectionParameter
Using reflection to get metadata for ReflectionType
Using reflection to get metadata for Closure
Using composer to locate file for Amp\Struct
Scanning /Users/jason/Fresh/psalm-integration/importer-debug/vendor/amphp/amp/lib/Struct.php
Using reflection to get metadata for ReflectionFunction
Using reflection to get metadata for ReflectionFunctionAbstract
Finished registering autoloaded files
Visiting autoload files took 0.065s
Scanning files...
Parsing /Users/jason/Fresh/psalm-integration/importer-debug/wordpress-importer/wordpress-importer.php
Deep scanning /Users/jason/Fresh/psalm-integration/importer-debug/wordpress-importer/wordpress-importer.php
PHP Fatal error:  Uncaught LogicException: $this->fq_classlike_names should not be null in /Users/jason/Fresh/psalm-integration/importer-debug/vendor/vimeo/psalm/src/Psalm/Internal/Visitor/ReflectorVisitor.php:1548
Stack trace:
#0 /Users/jason/Fresh/psalm-integration/importer-debug/vendor/vimeo/psalm/src/Psalm/Internal/Visitor/ReflectorVisitor.php(321): Psalm\Internal\Visitor\ReflectorVisitor->registerFunctionLike(Object(PhpParser\Node\Stmt\ClassMethod))
#1 /Users/jason/Fresh/psalm-integration/importer-debug/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(200): Psalm\Internal\Visitor\ReflectorVisitor->enterNode(Object(PhpParser\Node\Stmt\ClassMethod))
#2 /Users/jason/Fresh/psalm-integration/importer-debug/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(114): PhpParser\NodeTraverser->traverseArray(Array)
#3 /Users/jason/Fresh/psalm-integration/importer-debug/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(223): PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Stmt\Class_))
#4 /Users/jason/Fres in /Users/jason/Fresh/psalm-integration/importer-debug/vendor/vimeo/psalm/src/Psalm/Internal/Visitor/ReflectorVisitor.php on line 1548
```

**Comment by muglug** [comment]
This specific issue is fixed, but Psalm still complains when trying to analyse the file. It's not able to analyse it properly without also having the WordPress source code handy.
