### ISSUE TITLE
Unknown psalm annotation should report an issue

### ISSUE THREAD

**Issue by souravchandra** [vimeo/psalm#1934]
If we use not supported / unknown psalm annotation, for example instead of `@psalm-suppress` by mistake we use `@psalm-ignore` which is not a valid existing annotation, psalm should report that as an issue rather than throwing exception. Because of exception it is checking whole codebase instead of the files changed in the branch and throws other random errors
```
[RUNNING] [PHP-DEPENDENCIES] .cache/php/Psalm.x 
Checking files
PHP Fatal error:  Uncaught Psalm\Exception\DocblockParseException: Unrecognised annotation @psalm-ignore in /Users/sourav/Documents/work/Vimeo/vimeo/vendor/vimeo/psalm/src/Psalm/DocComment.php:156
Stack trace:
#0 /Users/sourav/Documents/work/Vimeo/vimeo/vendor/psalm/plugin-phpunit/hooks/TestCaseHandler.php(528): Psalm\DocComment::parse('This method sea...', 57)
#1 /Users/sourav/Documents/work/Vimeo/vimeo/vendor/psalm/plugin-phpunit/hooks/TestCaseHandler.php(518): Psalm\PhpUnitPlugin\Hooks\TestCaseHandler::getSpecials(Object(PhpParser\Node\Stmt\ClassMethod))
#2 /Users/sourav/Documents/work/Vimeo/vimeo/vendor/psalm/plugin-phpunit/hooks/TestCaseHandler.php(509): Psalm\PhpUnitPlugin\Hooks\TestCaseHandler::isBeforeInitializer(Object(PhpParser\Node\Stmt\ClassMethod))
#3 /Users/sourav/Documents/work/Vimeo/vimeo/vendor/psalm/plugin-phpunit/hooks/TestCaseHandler.php(90): Psalm\PhpUnitPlugin\Hooks\TestCaseHandler::hasInitializers(Object(Psalm\Storage\ClassLikeStorage), Object(PhpParser\Node\Stmt\Class_))
#4 /Users/sourav/Documents/work/ in /Users/sourav/Documents/work/Vimeo/vimeo/vendor/vimeo/psalm/src/Psalm/DocComment.php on line 156

Fatal error: Uncaught Psalm\Exception\DocblockParseException: Unrecognised annotation @psalm-ignore in /Users/sourav/Documents/work/Vimeo/vimeo/vendor/vimeo/psalm/src/Psalm/DocComment.php:156
Stack trace:
#0 /Users/sourav/Documents/work/Vimeo/vimeo/vendor/psalm/plugin-phpunit/hooks/TestCaseHandler.php(528): Psalm\DocComment::parse('This method sea...', 57)
#1 /Users/sourav/Documents/work/Vimeo/vimeo/vendor/psalm/plugin-phpunit/hooks/TestCaseHandler.php(518): Psalm\PhpUnitPlugin\Hooks\TestCaseHandler::getSpecials(Object(PhpParser\Node\Stmt\ClassMethod))
#2 /Users/sourav/Documents/work/Vimeo/vimeo/vendor/psalm/plugin-phpunit/hooks/TestCaseHandler.php(509): Psalm\PhpUnitPlugin\Hooks\TestCaseHandler::isBeforeInitializer(Object(PhpParser\Node\Stmt\ClassMethod))
#3 /Users/sourav/Documents/work/Vimeo/vimeo/vendor/psalm/plugin-phpunit/hooks/TestCaseHandler.php(90): Psalm\PhpUnitPlugin\Hooks\TestCaseHandler::hasInitializers(Object(Psalm\Storage\ClassLikeStorage), Object(PhpParser\Node\Stmt\Class_))
#4 /Users/sourav/Documents/work/ in /Users/sourav/Documents/work/Vimeo/vimeo/vendor/vimeo/psalm/src/Psalm/DocComment.php on line 156
PHP Fatal error:  Uncaught InvalidArgumentException: Could not get file storage for /users/sourav/documents/work/vimeo/vimeo/routes/main.php in /Users/sourav/Documents/work/Vimeo/vimeo/vendor/vimeo/psalm/src/Psalm/Internal/Provider/FileStorageProvider.php:49
Stack trace:
#0 /Users/sourav/Documents/work/Vimeo/vimeo/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/FileAnalyzer.php(141): Psalm\Internal\Provider\FileStorageProvider->get('/users/sourav/d...')
#1 /Users/sourav/Documents/work/Vimeo/vimeo/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Analyzer.php(262): Psalm\Internal\Analyzer\FileAnalyzer->analyze(NULL)
#2 /Users/sourav/Documents/work/Vimeo/vimeo/vendor/vimeo/psalm/src/Psalm/Internal/Fork/Pool.php(182): Psalm\Internal\Codebase\Analyzer->Psalm\Internal\Codebase\{closure}(10, '/Users/sourav/D...')
#3 /Users/sourav/Documents/work/Vimeo/vimeo/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Analyzer.php(354): Psalm\Internal\Fork\Pool->__construct(Array, Object(Closure), Object(Closure), Object(Closure), Object(Closure))
#4 / in /Users/sourav/Documents/work/Vimeo/vimeo/vendor/vimeo/psalm/src/Psalm/Internal/Provider/FileStorageProvider.php on line 49

Fatal error: Uncaught InvalidArgumentException: Could not get file storage for /users/sourav/documents/work/vimeo/vimeo/routes/main.php in /Users/sourav/Documents/work/Vimeo/vimeo/vendor/vimeo/psalm/src/Psalm/Internal/Provider/FileStorageProvider.php:49
Stack trace:
#0 /Users/sourav/Documents/work/Vimeo/vimeo/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/FileAnalyzer.php(141): Psalm\Internal\Provider\FileStorageProvider->get('/users/sourav/d...')
#1 /Users/sourav/Documents/work/Vimeo/vimeo/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Analyzer.php(262): Psalm\Internal\Analyzer\FileAnalyzer->analyze(NULL)
#2 /Users/sourav/Documents/work/Vimeo/vimeo/vendor/vimeo/psalm/src/Psalm/Internal/Fork/Pool.php(182): Psalm\Internal\Codebase\Analyzer->Psalm\Internal\Codebase\{closure}(10, '/Users/sourav/D...')
#3 /Users/sourav/Documents/work/Vimeo/vimeo/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Analyzer.php(354): Psalm\Internal\Fork\Pool->__construct(Array, Object(Closure), Object(Closure), Object(Closure), Object(Closure))
#4 / in /Users/sourav/Documents/work/Vimeo/vimeo/vendor/vimeo/psalm/src/Psalm/Internal/Provider/FileStorageProvider.php on line 49
```

**Comment by souravchandra** [comment]
Closing it in favour of https://github.com/psalm/phpunit-psalm-plugin/issues/36
