### ISSUE TITLE
PHP Fatal error:  Uncaught Error: Class '<NonAutoloadedClass>' not found in..

### ISSUE THREAD

**Issue by AdamMarton** [vimeo/psalm#1938]
Using Psalm on [12eeb8b](https://github.com/vimeo/psalm/commit/12eeb8b32075f37304144d7ce217b989f56976ab) (also [on 3.4.7](https://github.com/psalm/psalm-vscode-plugin/issues/6#issuecomment-510492335)), I'm getting the following error:

```
PHP Fatal error:  Uncaught Error: Class 'acf_field' not found in ...
rejected promise not handled within 1 second: Error: Error: Class 'acf_field' not found in <redacted>
Stack trace:
#0 <site>\vendor\composer\ClassLoader.php(444): include()
#1 <site>vendor\composer\ClassLoader.php(322): Composer\Autoload\includeFile('C:\\Users\\Adam_M...')
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass(<redacted>)
#3 [internal function]: spl_autoload_call(<redacted>)
#4 C:\Users\Adam_Marton\AppData\Roaming\Composer\vendor\vimeo\psalm\src\Psalm\Internal\Visitor\ReflectorVisitor.php(697): class_exists(<redacted>)
#5 C:\Users\Adam_Marton\AppData\Roaming\Composer\vendor\vimeo\psalm\src\Psalm\Internal\Visitor\ReflectorVisitor.php(504): Psalm\Internal\Visitor\ReflectorVisitor->enterConditional(Object(PhpPa in <redacted>

Fatal error: Uncaught Error: Class 'acf_field' not found in <redacted>
Stack trace:
#0 <site>\vendor\composer\ClassLoader.php(444): include()
#1 <site>\vendor\composer\ClassLoader.php(322): Composer\Autoload\includeFile('C:\\Users\\Adam_M...')
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass(<redacted>)
#3 [internal function]: spl_autoload_call(<redacted>)
#4 C:\Users\Adam_Marton\AppData\Roaming\Composer\vendor\vimeo\psalm\src\Psalm\Internal\Visitor\ReflectorVisitor.php(697): class_exists(<redacted>)
#5 C:\Users\Adam_Marton\AppData\Roaming\Composer\vendor\vimeo\psalm\src\Psalm\Internal\Visitor\ReflectorVisitor.php(504): Psalm\Internal\Visitor\ReflectorVisitor->enterConditional(Object(PhpPa in <redacted>
```

Please let me know if you need further details.

**Comment by muglug** [comment]
Hey - Psalm should definitely catch composer issues, but code that causes Composer to error probably has bigger issues.

**Comment by AdamMarton** [comment]
While you're perfectly right and I agree with you, this is pretty much how WordPress works on Bedrock.

**Comment by muglug** [comment]
Can you put together a repository where the issue can be replicated?
