### ISSUE TITLE
Psalm throwing errors after successful runs

### ISSUE THREAD

**Issue by prondubuisi** [vimeo/psalm#1954]
I am using Psalm  and everything works fine, after some runs though I start having errors

```
prondubuisi@test-gsoc19:~/civi$ sudo ./vendor/bin/psalm 
[sudo] password for prondubuisi: 
Scanning files...
Analyzing files...

PHP Fatal error:  Uncaught UnexpectedValueException: $storage should not be null for CRM_GCD::_getrandomstring in /home/prondubuisi/civi/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Methods.php:913
Stack trace:
#0 /home/prondubuisi/civi/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/MethodAnalyzer.php(52): Psalm\Internal\Codebase\Methods->getStorage('CRM_GCD::_getra...')
#1 /home/prondubuisi/civi/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/ClassAnalyzer.php(1483): Psalm\Internal\Analyzer\MethodAnalyzer->__construct(Object(PhpParser\Node\Stmt\ClassMethod), Object(Psalm\Internal\Analyzer\ClassAnalyzer))
#2 /home/prondubuisi/civi/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/ClassAnalyzer.php(768): Psalm\Internal\Analyzer\ClassAnalyzer->analyzeClassMethod(Object(PhpParser\Node\Stmt\ClassMethod), Object(Psalm\Storage\ClassLikeStorage), Object(Psalm\Internal\Analyzer\ClassAnalyzer), Object(Psalm\Context), Object(Psalm\Context))
#3 /home/prondubuisi/civi/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/FileAnalyzer.php(195): Psa in /home/prondubuisi/civi/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Methods.php on line 913

Fatal error: Uncaught UnexpectedValueException: $storage should not be null for CRM_GCD::_getrandomstring in /home/prondubuisi/civi/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Methods.php:913
Stack trace:
#0 /home/prondubuisi/civi/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/MethodAnalyzer.php(52): Psalm\Internal\Codebase\Methods->getStorage('CRM_GCD::_getra...')
#1 /home/prondubuisi/civi/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/ClassAnalyzer.php(1483): Psalm\Internal\Analyzer\MethodAnalyzer->__construct(Object(PhpParser\Node\Stmt\ClassMethod), Object(Psalm\Internal\Analyzer\ClassAnalyzer))
#2 /home/prondubuisi/civi/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/ClassAnalyzer.php(768): Psalm\Internal\Analyzer\ClassAnalyzer->analyzeClassMethod(Object(PhpParser\Node\Stmt\ClassMethod), Object(Psalm\Storage\ClassLikeStorage), Object(Psalm\Internal\Analyzer\ClassAnalyzer), Object(Psalm\Context), Object(Psalm\Context))
#3 /home/prondubuisi/civi/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/FileAnalyzer.php(195): Psa in /home/prondubuisi/civi/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Methods.php on line 913

```

**Comment by muglug** [comment]
`sudo` should not be needed for Psalm to work.

Is there a way I can reproduce this locally?

**Comment by SignpostMarv** [comment]
I generally get storage-related issues if I save/touch a file while psalm is running, if that helps.

**Comment by prondubuisi** [comment]
Hello @muglug Using the debug by line flag, I have been able to discover the source of this error as https://github.com/civicrm/civicrm-core/blob/master/api/v3/utils.php#L1032 

```
 /home/coolife/git-repos/gsoc/core/api/v3/utils.php:1032
PHP Fatal error:  Uncaught InvalidArgumentException: Could not get class storage for crm_core_bao_customquery in /home/coolife/git-repos/gsoc/core/vendor/vimeo/psalm/src/Psalm/Internal/Provider/ClassLikeStorageProvider.php:47
Stack trace:
#0 /home/coolife/git-repos/gsoc/core/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/ClassLikes.php(1405): Psalm\Internal\Provider\ClassLikeStorageProvider->get('crm_core_bao_cu...')
#1 /home/coolife/git-repos/gsoc/core/vendor/vimeo/psalm/src/Psalm/Type/Reconciler.php(2909): Psalm\Internal\Codebase\ClassLikes->getConstantsForClass('crm_core_bao_cu...', 1024)
#2 /home/coolife/git-repos/gsoc/core/vendor/vimeo/psalm/src/Psalm/Type/Reconciler.php(173): Psalm\Type\Reconciler::getValueForKey(Object(Psalm\Codebase), 'CRM_Core_BAO_Cu...', Array, Array, Object(Psalm\CodeLocation))
#3 /home/coolife/git-repos/gsoc/core/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/Statements/Block/IfAnalyzer.php(298): Psalm\Type\Reconciler::reconcileKeyedTypes(Array, Array, Array, Array, Object(Psalm\Internal\Analyzer\S in /home/coolife/git-repos/gsoc/core/vendor/vimeo/psalm/src/Psalm/Internal/Provider/ClassLikeStorageProvider.php on line 47

Fatal error: Uncaught InvalidArgumentException: Could not get class storage for crm_core_bao_customquery in /home/coolife/git-repos/gsoc/core/vendor/vimeo/psalm/src/Psalm/Internal/Provider/ClassLikeStorageProvider.php:47
Stack trace:
#0 /home/coolife/git-repos/gsoc/core/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/ClassLikes.php(1405): Psalm\Internal\Provider\ClassLikeStorageProvider->get('crm_core_bao_cu...')
#1 /home/coolife/git-repos/gsoc/core/vendor/vimeo/psalm/src/Psalm/Type/Reconciler.php(2909): Psalm\Internal\Codebase\ClassLikes->getConstantsForClass('crm_core_bao_cu...', 1024)
#2 /home/coolife/git-repos/gsoc/core/vendor/vimeo/psalm/src/Psalm/Type/Reconciler.php(173): Psalm\Type\Reconciler::getValueForKey(Object(Psalm\Codebase), 'CRM_Core_BAO_Cu...', Array, Array, Object(Psalm\CodeLocation))
#3 /home/coolife/git-repos/gsoc/core/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/Statements/Block/IfAnalyzer.php(298): Psalm\Type\Reconciler::reconcileKeyedTypes(Array, Array, Array, Array, Object(Psalm\Internal\Analyzer\S in /home/coolife/git-repos/gsoc/core/vendor/vimeo/psalm/src/Psalm/Internal/Provider/ClassLikeStorageProvider.php on line 47
```
