### ISSUE TITLE
Anonymous class in a method crashes psalm

### ISSUE THREAD

**Issue by weirdan** [vimeo/psalm#197]
```php
class BBB
{
    public function a()
    {
        return new class() {};
    }
}
```
causes psalm to fail with the following exception:
```
Fatal error: Uncaught LogicException: $this->fq_classlike_name should bot be null in /home/weirdan/.composer/vendor/vimeo/psalm/src/Psalm/Visitor/DependencyFinderVisitor.php:401
Stack trace:
#0 /home/weirdan/.composer/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(178): Psalm\Visitor\DependencyFinderVisitor->leaveNode(Object(PhpParser\Node\Stmt\Class_))
#1 /home/weirdan/.composer/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(85): PhpParser\NodeTraverser->traverseArray(Array)
#2 /home/weirdan/.composer/vendor/vimeo/psalm/src/Psalm/Checker/FileChecker.php(131): PhpParser\NodeTraverser->traverse(Array)
#3 /home/weirdan/.composer/vendor/vimeo/psalm/src/Psalm/Checker/ProjectChecker.php(1315): Psalm\Checker\FileChecker->scan()
#4 /home/weirdan/.composer/vendor/vimeo/psalm/src/Psalm/Checker/ProjectChecker.php(422): Psalm\Checker\ProjectChecker->scanFile('/home/weirdan/s...', Array, true)
#5 /home/weirdan/.composer/vendor/vimeo/psalm/src/Psalm/Checker/ProjectChecker.php(1247): Psalm\Checker\ProjectChecker->scan in /home/weirdan/.composer/vendor/vimeo/psalm/src/Psalm/Visitor/DependencyFinderVisitor.php on line 401
```

Psalm version: 0.3.52

**Comment by muglug** [comment]
Yeah, it's because there's a class within a class, and Psalm can’t currently handle that – introduced with https://github.com/vimeo/psalm/pull/191
