### ISSUE TITLE
Psalm running into  complicated Expression Exception

### ISSUE THREAD

**Issue by prondubuisi** [vimeo/psalm#1984]
I run into into the following error while running Psalm on a code Repo
```
PHP Fatal error:  Uncaught Psalm\Exception\ComplicatedExpressionException in /srv/www/d7-master/web/sites/all/modules/civicrm/vendor/vimeo/psalm/src/Psalm/Type/Algebra.php:487
Stack trace:
#0 /srv/www/d7-master/web/sites/all/modules/civicrm/vendor/vimeo/psalm/src/Psalm/Type/Algebra.php(484): Psalm\Type\Algebra::groupImpossibilities(Array, 88589)
#1 /srv/www/d7-master/web/sites/all/modules/civicrm/vendor/vimeo/psalm/src/Psalm/Type/Algebra.php(484): Psalm\Type\Algebra::groupImpossibilities(Array, 88589)
#2 /srv/www/d7-master/web/sites/all/modules/civicrm/vendor/vimeo/psalm/src/Psalm/Type/Algebra.php(484): Psalm\Type\Algebra::groupImpossibilities(Array, 88589)
#3 /srv/www/d7-master/web/sites/all/modules/civicrm/vendor/vimeo/psalm/src/Psalm/Type/Algebra.php(484): Psalm\Type\Algebra::groupImpossibilities(Array, 88589)
#4 /srv/www/d7-master/web/sites/all/modules/civicrm/vendor/vimeo/psalm/src/Psalm/Type/Algebra.php(484): Psalm\Type\Algebra::groupImpossibilities(Array, 88589)
#5 /srv/www/d7-master/web/sites/all/modules/civicrm/vendor in /srv/www/d7-master/web/sites/all/modules/civicrm/vendor/vimeo/psalm/src/Psalm/Type/Algebra.php on line 487

Fatal error: Uncaught Psalm\Exception\ComplicatedExpressionException in /srv/www/d7-master/web/sites/all/modules/civicrm/vendor/vimeo/psalm/src/Psalm/Type/Algebra.php:487
Stack trace:
#0 /srv/www/d7-master/web/sites/all/modules/civicrm/vendor/vimeo/psalm/src/Psalm/Type/Algebra.php(484): Psalm\Type\Algebra::groupImpossibilities(Array, 88589)
#1 /srv/www/d7-master/web/sites/all/modules/civicrm/vendor/vimeo/psalm/src/Psalm/Type/Algebra.php(484): Psalm\Type\Algebra::groupImpossibilities(Array, 88589)
#2 /srv/www/d7-master/web/sites/all/modules/civicrm/vendor/vimeo/psalm/src/Psalm/Type/Algebra.php(484): Psalm\Type\Algebra::groupImpossibilities(Array, 88589)
#3 /srv/www/d7-master/web/sites/all/modules/civicrm/vendor/vimeo/psalm/src/Psalm/Type/Algebra.php(484): Psalm\Type\Algebra::groupImpossibilities(Array, 88589)
#4 /srv/www/d7-master/web/sites/all/modules/civicrm/vendor/vimeo/psalm/src/Psalm/Type/Algebra.php(484): Psalm\Type\Algebra::groupImpossibilities(Array, 88589)
#5 /srv/www/d7-master/web/sites/all/modules/civicrm/vendor in /srv/www/d7-master/web/sites/all/modules/civicrm/vendor/vimeo/psalm/src/Psalm/Type/Algebra.php on line 487

```
Any Idea how I can fix this?

**Comment by prondubuisi** [comment]
@muglug any help please?

**Comment by muglug** [comment]
Mind running with `--debug-by-line` to see what code produces that error?

**Comment by muglug** [comment]
This should now be fixed on maser
