### ISSUE TITLE
Invalid Arguement Exception

### ISSUE THREAD

**Issue by prondubuisi** [vimeo/psalm#1985]
Hello, running Psalm I get an `Invalid Aguement Exception`

```
vagrant@civi:/srv/www/d7-master/web/sites/all/modules/civicrm$ php ./vendor/bin/psalm 
Scanning files...
Analyzing files...

EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE  60 / 467 (13%)
EEEEEEPHP Fatal error:  Uncaught InvalidArgumentException: Could not get class storage for crm_core_bao_customquery in /srv/www/d7-master/web/sites/all/modules/civicrm/vendor/vimeo/psalm/src/Psalm/Internal/Provider/ClassLikeStorageProvider.php:47
Stack trace:
#0 /srv/www/d7-master/web/sites/all/modules/civicrm/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/ClassLikes.php(1387): Psalm\Internal\Provider\ClassLikeStorageProvider->get('crm_core_bao_cu...')
#1 /srv/www/d7-master/web/sites/all/modules/civicrm/vendor/vimeo/psalm/src/Psalm/Type/Reconciler.php(2868): Psalm\Internal\Codebase\ClassLikes->getConstantsForClass('crm_core_bao_cu...', 1024)
#2 /srv/www/d7-master/web/sites/all/modules/civicrm/vendor/vimeo/psalm/src/Psalm/Type/Reconciler.php(173): Psalm\Type\Reconciler::getValueForKey(Object(Psalm\Codebase), 'CRM_Core_BAO_Cu...', Array, Array, Object(Psalm\CodeLocation))
#3 /srv/www/d7-master/web/sites/all/modules/civicrm/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/Statements/Block/IfAnalyzer.php(299): Psalm\Type\Reconciler::recon in /srv/www/d7-master/web/sites/all/modules/civicrm/vendor/vimeo/psalm/src/Psalm/Internal/Provider/ClassLikeStorageProvider.php on line 47

Fatal error: Uncaught InvalidArgumentException: Could not get class storage for crm_core_bao_customquery in /srv/www/d7-master/web/sites/all/modules/civicrm/vendor/vimeo/psalm/src/Psalm/Internal/Provider/ClassLikeStorageProvider.php:47
Stack trace:
#0 /srv/www/d7-master/web/sites/all/modules/civicrm/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/ClassLikes.php(1387): Psalm\Internal\Provider\ClassLikeStorageProvider->get('crm_core_bao_cu...')
#1 /srv/www/d7-master/web/sites/all/modules/civicrm/vendor/vimeo/psalm/src/Psalm/Type/Reconciler.php(2868): Psalm\Internal\Codebase\ClassLikes->getConstantsForClass('crm_core_bao_cu...', 1024)
#2 /srv/www/d7-master/web/sites/all/modules/civicrm/vendor/vimeo/psalm/src/Psalm/Type/Reconciler.php(173): Psalm\Type\Reconciler::getValueForKey(Object(Psalm\Codebase), 'CRM_Core_BAO_Cu...', Array, Array, Object(Psalm\CodeLocation))
#3 /srv/www/d7-master/web/sites/all/modules/civicrm/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/Statements/Block/IfAnalyzer.php(299): Psalm\Type\Reconciler::recon in /srv/www/d7-master/web/sites/all/modules/civicrm/vendor/vimeo/psalm/src/Psalm/Internal/Provider/ClassLikeStorageProvider.php on line 47
```
Any help on fixing this?

**Comment by prondubuisi** [comment]
Hello @muglug passing the flag this is what I get 
```
/srv/www/d7-master/web/sites/all/modules/civicrm/packages/IDS/vendors/htmlpurifer/HTMLPurifier/Encoder.php:234
/srv/www/d7-master/web/sites/all/modules/civicrm/packages/IDS/vendors/htmlpurifer/HTMLPurifier/Encoder.php:236
/srv/www/d7-master/web/sites/all/modules/civicrm/packages/IDS/vendors/htmlpurifer/HTMLPurifier/Encoder.php:243
PHP Fatal error:  Uncaught Psalm\Exception\ComplicatedExpressionException in /srv/www/d7-master/web/sites/all/modules/civicrm/vendor/vimeo/psalm/src/Psalm/Type/Algebra.php:487
Stack trace:
```
Here is a link to the file causing the error https://github.com/civicrm/civicrm-packages/blob/master/IDS/vendors/htmlpurifer/HTMLPurifier/Encoder.php#L243

I will be happy to give more information if needed

**Comment by prondubuisi** [comment]
Thanks @muglug
