### ISSUE TITLE
PHP Fatal error: Uncaught UnexpectedValueException: Expecting closure to have storage

### ISSUE THREAD

**Issue by bkdotcom** [vimeo/psalm#2250]
```
PHP Fatal error:  Uncaught exception 'UnexpectedValueException' with message 'Expecting .../Config.php:38:782:-:closure to have storage in .../Config.php' in .../vendor/vimeo/psalm/src/Psalm/Codebase.php:403
Stack trace:
#0 .../vendor/vimeo/psalm/src/Psalm/Checker/FunctionLikeChecker.php(234): Psalm\Codebase->getClosureStorage('/Users/bkent/Dr...', '/Users/bkent/Dr...')
#1 .../vendor/vimeo/psalm/src/Psalm/Checker/Statements/ExpressionChecker.php(344): Psalm\Checker\FunctionLikeChecker->analyze(Object(Psalm\Context), Object(Psalm\Context))
#2 .../vendor/vimeo/psalm/src/Psalm/Checker/Statements/Expression/AssignmentChecker.php(122): Psalm\Checker\Statements\Expression in .../vendor/vimeo/psalm/src/Psalm/Codebase.php on line 403
```

Offending code

```PHP
    /**
     * Constructor
     *
     * @param Debug $debug debug instance
     * @param array $cfg   configuration
     */
    public function __construct(Debug $debug, &$cfg = array())
    {
        $this->values = &$cfg;
        $this->debug = $debug;
        $this->valuesPending['errorEmailer']['emailBacktraceDumper'] = function ($backtrace) use ($debug) {
            return $debug->dumpText->dump($backtrace);
        };
    }
```

My guess:  it can't resolve dumpText which is resolved via `Debug::_get()`
¯\\\_(ツ)_/¯

**Comment by muglug** [comment]
Are you running Psalm on the `v3-dev` branch of https://github.com/bkdotcom/PHPDebugConsole?

What version of Psalm are you using?

**Comment by bkdotcom** [comment]
Correct

Psalm 1.1.9@d15cf3b7f50249caf933144c8926c8e69aff3d34

**Comment by muglug** [comment]
That version of Psalm is a couple of years old. Please use the latest version!

**Comment by muglug** [comment]
I imagine you’re using PHP 5.6, which has been EOL for almost a year.

**Comment by bkdotcom** [comment]
Yes / d'oh...  I regularly switch between 5.6 (to support older projects / day-job) & 7.x..   
Should have been the first thing I checked

Thank you!
