### ISSUE TITLE
3.6.5 crashes

### ISSUE THREAD

**Issue by ADmad** [vimeo/psalm#2342]
Psalm crashes when running on this file https://github.com/FriendsOfCake/crud-view/blob/cake-4.x/src/View/CrudView.php.

```
PHP Notice:  Undefined offset: 1 in phar:///home/admad/.phive/phars/psalm-3.6.5.phar/src/Psalm/Internal/Codebase/Methods.php on line 586

Notice: Undefined offset: 1 in phar:///home/admad/.phive/phars/psalm-3.6.5.phar/src/Psalm/Internal/Codebase/Methods.php on line 586
PHP Fatal error:  Uncaught InvalidArgumentException: Could not get class storage for not-callable in phar:///home/admad/.phive/phars/psalm-3.6.5.phar/src/Psalm/Internal/Provider/ClassLikeStorageProvider.php:42
Stack trace:
#0 phar:///home/admad/.phive/phars/psalm-3.6.5.phar/src/Psalm/Internal/Codebase/Methods.php(587): _HumbugBoxb6ab9d012af3\Psalm\Internal\Provider\ClassLikeStorageProvider->get('not-callable')
#1 phar:///home/admad/.phive/phars/psalm-3.6.5.phar/src/Psalm/Internal/Analyzer/TypeAnalyzer.php(947): _HumbugBoxb6ab9d012af3\Psalm\Internal\Codebase\Methods->getStorage('not-callable')
#2 phar:///home/admad/.phive/phars/psalm-3.6.5.phar/src/Psalm/Internal/Type/UnionTemplateHandler.php(146): _HumbugBoxb6ab9d012af3\Psalm\Internal\Analyzer\TypeAnalyzer::getCallableFromAtomic(Object(_HumbugBoxb6ab9d012af3\Psalm\Codebase), Object(_HumbugBoxb6ab9d012af3\Psalm\Type\Atomic\ObjectLike))
#3 phar:///home/admad/.phive/phars/psalm-3.6.5.phar/src/Psalm/Internal/Type/UnionTemplateHandler.php(116): _HumbugBoxb6ab9d012af3\Psalm\Internal in phar:///home/admad/.phive/phars/psalm-3.6.5.phar/src/Psalm/Internal/Provider/ClassLikeStorageProvider.php on line 42

Fatal error: Uncaught InvalidArgumentException: Could not get class storage for not-callable in phar:///home/admad/.phive/phars/psalm-3.6.5.phar/src/Psalm/Internal/Provider/ClassLikeStorageProvider.php:42
Stack trace:
#0 phar:///home/admad/.phive/phars/psalm-3.6.5.phar/src/Psalm/Internal/Codebase/Methods.php(587): _HumbugBoxb6ab9d012af3\Psalm\Internal\Provider\ClassLikeStorageProvider->get('not-callable')
#1 phar:///home/admad/.phive/phars/psalm-3.6.5.phar/src/Psalm/Internal/Analyzer/TypeAnalyzer.php(947): _HumbugBoxb6ab9d012af3\Psalm\Internal\Codebase\Methods->getStorage('not-callable')
#2 phar:///home/admad/.phive/phars/psalm-3.6.5.phar/src/Psalm/Internal/Type/UnionTemplateHandler.php(146): _HumbugBoxb6ab9d012af3\Psalm\Internal\Analyzer\TypeAnalyzer::getCallableFromAtomic(Object(_HumbugBoxb6ab9d012af3\Psalm\Codebase), Object(_HumbugBoxb6ab9d012af3\Psalm\Type\Atomic\ObjectLike))
#3 phar:///home/admad/.phive/phars/psalm-3.6.5.phar/src/Psalm/Internal/Type/UnionTemplateHandler.php(116): _HumbugBoxb6ab9d012af3\Psalm\Internal in phar:///home/admad/.phive/phars/psalm-3.6.5.phar/src/Psalm/Internal/Provider/ClassLikeStorageProvider.php on line 42
```

Config file is the default you get by running `psalm --init`

**Comment by muglug** [comment]
Fixed in 5fabf41

**Comment by ADmad** [comment]
Could you make a new release please with this fix. Thanks.

**Comment by muglug** [comment]
https://github.com/vimeo/psalm/releases/tag/3.6.6 - give it a few minutes for a Phar to be built

**Comment by ADmad** [comment]
Thank you

**Comment by ADmad** [comment]
FYI some travis jobs are failing https://travis-ci.org/vimeo/psalm/builds/612533596
