### ISSUE TITLE
"Permission denied" (//lost+found) when using psalm with github actions

### ISSUE THREAD

**Issue by SpazzMarticus** [vimeo/psalm#2465]
When using psalm with Github Actions it failed with:

```bash
PHP Fatal error:  Uncaught UnexpectedValueException: RecursiveDirectoryIterator::__construct(//lost+found): failed to open dir: Permission denied in /home/runner/work/tus/tus/vendor/vimeo/psalm/src/Psalm/Config/FileFilter.php:208
```

```bash
Stack trace:
#0 [internal function]: RecursiveDirectoryIterator->__construct()
#1 [internal function]: RecursiveDirectoryIterator->getChildren()
#2 /home/runner/work/<package>/vendor/vimeo/psalm/src/Psalm/Config/FileFilter.php(208): RecursiveIteratorIterator->next()
#3 /home/runner/work/<package>/vendor/vimeo/psalm/src/Psalm/Config/ProjectFileFilter.php(27): Psalm\Config\FileFilter::loadFromXMLElement()
#4 /home/runner/work/<package>/vendor/vimeo/psalm/src/Psalm/Config.php(789): Psalm\Config\ProjectFileFilter::loadFromXMLElement()
#5 /home/runner/work/<package>/vendor/vimeo/psalm/src/Psalm/Config.php(610): Psalm\Config::fromXmlAndPaths()
#6 /home/runner/work/<package>/vendor/vimeo/psalm/src/Psalm/Config.php(580): Psalm\Config::loadFromXML()
#7 /home/runner/work/<package>/vendor/vimeo/psalm/src/Psalm/Config.php(52 in /home/runner/work/tus/tus/vendor/vimeo/psalm/src/Psalm/Config/FileFilter.php on line 208
```

(The `//lost+found` directory does not exist in my repository.)

Psalm was installed as a composer dev-dependency and was run with `vendor/bin/psalm`.

Project files where defined like:

```xml
<projectFiles>
        <directory name="/" />
        <ignoreFiles>
            <directory name="vendor" />
        </ignoreFiles>
</projectFiles>
```

Ignoring the directory did not work:

```xml
<projectFiles>
        <directory name="/" />
        <ignoreFiles>
            <directory name="vendor" />
            <directory name="lost+found" />
            <directory name="/lost+found" />
            <directory name="//lost+found" />
            <directory name="lost\+found" />
            <directory name="/lost\+found" />
            <directory name="//lost\+found" />
        </ignoreFiles>
</projectFiles>
```

**Workaround:** When changing the project files to specific folders the exception is not thrown:

```xml
<projectFiles>
        <directory name="src" />
        <directory name="example" />
        <directory name="tests" />
        <ignoreFiles>
            <directory name="vendor" />
        </ignoreFiles>
</projectFiles>
```

If checking for permissions is out of scope for psalm, you can close the issue.

Cheers!

**Comment by weirdan** [comment]
With `<directory name="/" />` you asked Psalm to check the entire filesystem starting from the root folder, and [`lost+found` dir](https://unix.stackexchange.com/questions/18154/what-is-the-purpose-of-the-lostfound-folder-in-linux-and-unix) is expected to be in the root folder.

**Comment by SpazzMarticus** [comment]
Changed the directory to `.` (`<directory name=".">`), now it works. 🤦‍♂
