### ISSUE TITLE
PHP 7 `new class implements OtherClass` throwing errors

### ISSUE THREAD

**Issue by erunion** [vimeo/psalm#249]
I have a strange bug where Psalm doesn't seem to like usage of `new class implements OtherClass`.

```php
<?php
namespace Tests;

use Illuminate\Contracts\Auth\Authenticatable;

class PsalmNewClassBugTest extends \PHPUnit\Framework\TestCase
{
    /** @var Authenticatable */
    protected $authenticatable;

    public function setUp(): void
    {
        parent::setUp();

        $this->authenticatable = new class implements Authenticatable {
            public function getAuthIdentifierName() { return true; }
            public function getAuthIdentifier() { return true; }
            public function getAuthPassword() { return true; }
            public function getRememberToken() { return true; }
            public function setRememberToken($value) { return true; }
            public function getRememberTokenName() { return true; }
        };
    }

    public function testRetrieveByToken()
    {
        $this->fail();
    }
}
```

Running Psalm, I get the following error:

```
$ ./vendor/bin/psalm tests/PsalmNewClassBugTest.php 
PHP Fatal error:  Uncaught UnexpectedValueException: $storage should not be null for _Users_erunion_code_project_tests_PsalmNewClassBugTest_php_17::testretrievebytoken in /Users/erunion/code/project/vendor/vimeo/psalm/src/Psalm/Checker/MethodChecker.php:411
Stack trace:
#0 /Users/erunion/code/project/vendor/vimeo/psalm/src/Psalm/Checker/ClassLikeChecker.php(347): Psalm\Checker\MethodChecker::getStorage(Object(Psalm\Checker\ProjectChecker), '_Users_erunion...')
#1 /Users/erunion/code/project/vendor/vimeo/psalm/src/Psalm/Checker/FileChecker.php(194): Psalm\Checker\ClassLikeChecker->analyze(Object(Psalm\Context), Object(Psalm\Context))
#2 /Users/erunion/code/project/vendor/vimeo/psalm/src/Psalm/Checker/ProjectChecker.php(920): Psalm\Checker\FileChecker->analyze(NULL, false)
#3 /Users/erunion/code/project/vendor/vimeo/psalm/src/Psalm/Checker/ProjectChecker.php(970): Psalm\Checker\ProjectChecker->Psalm\Checker\{closure}
Fatal error: Uncaught UnexpectedValueException: $storage should not be null for _Users_erunion_code_project_tests_PsalmNewClassBugTest_php_17::testretrievebytoken in /Users/erunion/code/project/vendor/vimeo/psalm/src/Psalm/Checker/MethodChecker.php:411
Stack trace:
#0 /Users/erunion/code/project/vendor/vimeo/psalm/src/Psalm/Checker/ClassLikeChecker.php(347): Psalm\Checker\MethodChecker::getStorage(Object(Psalm\Checker\ProjectChecker), '_Users_erunion...')
#1 /Users/erunion/code/project/vendor/vimeo/psalm/src/Psalm/Checker/FileChecker.php(194): Psalm\Checker\ClassLikeChecker->analyze(Object(Psalm\Context), Object(Psalm\Context))
#2 /Users/erunion/code/project/vendor/vimeo/psalm/src/Psalm/Checker/ProjectChecker.php(920): Psalm\Checker\FileChecker->analyze(NULL, false)
#3 /Users/erunion/code/project/vendor/vimeo/psalm/src/Psalm/Checker/ProjectChecker.php(970): Psalm\Checker\ProjectChecker->Psalm\Checker\{closure}(0, '/Users/erunion... in /Users/erunion/code/project/vendor/vimeo/psalm/src/Psalm/Checker/MethodChecker.php on line 411
```

**Comment by erunion** [comment]
Thought it was maybe something weird with the Laravel `Authenticatable` interface, but this also fails:

```php
<?php
namespace Tests;

//use Illuminate\Contracts\Auth\Authenticatable;

interface Authenticatable {
    /** @return bool **/
    public function getAuthIdentifierName();
    /** @return bool **/
    public function getAuthIdentifier();
    /** @return bool **/
    public function getAuthPassword();
    /** @return bool **/
    public function getRememberToken();
    /** @return bool **/
    public function setRememberToken($value);
    /** @return bool **/
    public function getRememberTokenName();
}

class PsalmNewClassBugTest extends \PHPUnit\Framework\TestCase
{
    /** @var Authenticatable */
    protected $authenticatable;

    public function setUp(): void
    {
        parent::setUp();

        $this->authenticatable = new class implements Authenticatable {
            public function getAuthIdentifierName() { return true; }
            public function getAuthIdentifier() { return true; }
            public function getAuthPassword() { return true; }
            public function getRememberToken() { return true; }
            public function setRememberToken($value) { return true; }
            public function getRememberTokenName() { return true; }
        };
    }

    public function testRetrieveByToken()
    {
        $this->fail();
    }
}
```

**Comment by muglug** [comment]
Smaller testcase
```
interface I {}

class PsalmNewClassBugTest
{
    /** @var ?I */
    protected $i;

    public function foo(): void
    {
        $this->i = new class implements I {};
    }

    public function foo2() : void {} // commenting this line out fixes
}
```
