### ISSUE TITLE
Crash with FunctionExistenceProvider plugin

### ISSUE THREAD

**Issue by weirdan** [vimeo/psalm#2493]
Psalm crashes when analyzing a call to the function postulated to exist by a plugin implementing `FunctionExistenceProviderInterface`

**Demo repo**
https://github.com/weirdan/function-existence-crash

**Steps to reproduce**
```console
$ git clone git@github.com:weirdan/function-existence-crash.git
$ cd function-existence-crash
$ composer install
$ vendor/bin/psalm
```
**Expected**: MixedMethodCall
**Actual**: 
```console
$ vendor/bin/psalm 
Scanning files...
Analyzing files...

Uncaught UnexpectedValueException: Expecting logger to have storage in /home/weirdan/src/psalm-issues/function-existence-crash/src/file.php in /home/weirdan/src/psalm-issues/function-existence-crash/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Functions.php:117
Stack trace:
#0 /home/weirdan/src/psalm-issues/function-existence-crash/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/Statements/Expression/Call/FunctionCallAnalyzer.php(373): Psalm\Internal\Codebase\Functions->getStorage(Object(Psalm\Internal\Analyzer\StatementsAnalyzer), 'logger')
#1 /home/weirdan/src/psalm-issues/function-existence-crash/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/Statements/ExpressionAnalyzer.php(432): Psalm\Internal\Analyzer\Statements\Expression\Call\FunctionCallAnalyzer::analyze(Object(Psalm\Internal\Analyzer\StatementsAnalyzer), Object(PhpParser\Node\Expr\FuncCall), Object(Psalm\Context))
#2 /home/weirdan/src/psalm-issues/function-existence-crash/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/Statements/Expression/AssignmentAnalyzer.php(232): Psalm\Internal\Analyzer\Statements\ExpressionAnalyzer::analyze(Object(Psalm\Internal\Analyzer\StatementsAnalyzer), Object(PhpParser\Node\Expr\FuncCall), Object(Psalm\Context))
#3 /home/weirdan/src/psalm-issues/function-existence-crash/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/Statements/ExpressionAnalyzer.php(118): Psalm\Internal\Analyzer\Statements\Expression\AssignmentAnalyzer::analyze(Object(Psalm\Internal\Analyzer\StatementsAnalyzer), Object(PhpParser\Node\Expr\Variable), Object(PhpParser\Node\Expr\FuncCall), NULL, Object(Psalm\Context), NULL)
#4 /home/weirdan/src/psalm-issues/function-existence-crash/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/StatementsAnalyzer.php(679): Psalm\Internal\Analyzer\Statements\ExpressionAnalyzer::analyze(Object(Psalm\Internal\Analyzer\StatementsAnalyzer), Object(PhpParser\Node\Expr\Assign), Object(Psalm\Context), false, NULL, true)
#5 /home/weirdan/src/psalm-issues/function-existence-crash/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/FileAnalyzer.php(190): Psalm\Internal\Analyzer\StatementsAnalyzer->analyze(Array, Object(Psalm\Context), NULL, true)
#6 /home/weirdan/src/psalm-issues/function-existence-crash/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Analyzer.php(334): Psalm\Internal\Analyzer\FileAnalyzer->analyze(NULL)
#7 /home/weirdan/src/psalm-issues/function-existence-crash/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Analyzer.php(566): Psalm\Internal\Codebase\Analyzer->Psalm\Internal\Codebase\{closure}(0, '/home/weirdan/s...')
#8 /home/weirdan/src/psalm-issues/function-existence-crash/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Analyzer.php(257): Psalm\Internal\Codebase\Analyzer->doAnalysis(Object(Psalm\Internal\Analyzer\ProjectAnalyzer), 1)
#9 /home/weirdan/src/psalm-issues/function-existence-crash/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/ProjectAnalyzer.php(520): Psalm\Internal\Codebase\Analyzer->analyzeFiles(Object(Psalm\Internal\Analyzer\ProjectAnalyzer), 1, false)
#10 /home/weirdan/src/psalm-issues/function-existence-crash/vendor/vimeo/psalm/src/psalm.php(547): Psalm\Internal\Analyzer\ProjectAnalyzer->check('/home/weirdan/s...', false)
#11 /home/weirdan/src/psalm-issues/function-existence-crash/vendor/vimeo/psalm/psalm(2): require_once('/home/weirdan/s...')
#12 {main}
(Psalm dev-master@59aeb6b6c3f1ee5c0474da8b63af8818318138d7 crashed due to an uncaught Throwable)
```
Note that there's the following plugin in `.psalm/Plugin.php`:
```php
<?php

namespace ZZ;

use Psalm\Plugin\Hook\FunctionExistenceProviderInterface;

class Plugin implements FunctionExistenceProviderInterface
{
    public static function getFunctionIds(): array
    {
        return ['logger'];
    }

    public static function doesFunctionExist(\Psalm\StatementsSource $statements_source, string $function_id)
    {
        return true;
    }
}
```

**Comment by muglug** [comment]
Hmm you're not providing function params though. What ought Psalm to do?

**Comment by weirdan** [comment]
I'd think it should interpret it as variadic mixed function returning mixed. Similar (from users point of view) to what it does in `if (function_exists(...))` block: https://psalm.dev/r/cc0a46a8fd

**Comment by muglug** [comment]
OK, I did that
