### ISSUE TITLE
Psalm breaks trying to check WordPress

### ISSUE THREAD

**Issue by paragonie-scott** [vimeo/psalm#251]
Steps to reproduce:

```bash
mkdir WordPress
cd WordPress
git clone https://github.com/WordPress/WordPress src
composer require --dev "vimeo/psalm:^0|^1"
vendor/bin/psalm --init
vendor/bin/psalm
```

Results:

```
PHP Fatal error:  Uncaught UnexpectedValueException: Expecting esc_html to have storage in /home/scott/WordPress/src/wp-admin/includes/class-bulk-upgrader-skin.php in /home/scott/WordPress/vendor/vimeo/psalm/src/Psalm/Checker/FunctionChecker.php:121
Stack trace:
#0 /home/scott/WordPress/vendor/vimeo/psalm/src/Psalm/Checker/FunctionChecker.php(691): Psalm\Checker\FunctionChecker::getStorage(Object(Psalm\Checker\StatementsChecker), 'esc_html')
#1 /home/scott/WordPress/vendor/vimeo/psalm/src/Psalm/Checker/FunctionChecker.php(476): Psalm\Checker\FunctionChecker::getArrayMapReturnType(Object(Psalm\Checker\StatementsChecker), 'array_map', Array, Object(Psalm\CodeLocation), Array)
#2 /home/scott/WordPress/vendor/vimeo/psalm/src/Psalm/Checker/FunctionChecker.php(410): Psalm\Checker\FunctionChecker::getArrayReturnType(Object(Psalm\Checker\StatementsChecker), 'array_map', Array, Object(Psalm\CodeLocation), Array)
#3 /home/scott/WordPress/vendor/vimeo/psalm/src/Psalm/Checker/Statements/Expression/CallChecker.php(370): Psalm\Checker\FunctionChe in /home/scott/WordPress/vendor/vimeo/psalm/src/Psalm/Checker/FunctionChecker.php on line 121
0
```

I'm not sure if this is just "WordPress is really *that* bad" or if it's a bug worth fixing in Psalm, but I thought I'd let you know either way. (WordPress is a wonderful test bed for a tool like this.)

**Comment by muglug** [comment]
Now it's failing at 
```php
if ( ! class_exists( 'SimplePie', false ) ) :
```

because it doesn't deal with conditional class declarations terribly well.

**Comment by paragonie-scott** [comment]
Their weird syntax doesn't help things much.

**Comment by muglug** [comment]
```bash
$ vendor/bin/psalm | grep ERROR | wc -l
> 9323
```

That's pretty conservative IMO.
