### ISSUE TITLE
 Call to undefined function spl_object_id() in php 7.1

### ISSUE THREAD

**Issue by keywan-ghadami-oxid** [vimeo/psalm#2530]
I do not know why, but for some reason the polifill is not used in my environment using Psalm 3.8.1 phar file:
```
Scanning files...
Uncaught Error: Call to undefined function spl_object_id() in phar:///var/www/oxid/vendor/psalm/phar/psalm.phar/src/Psalm/Internal/Visitor/ReflectorVisitor.php:1121
Stack trace:
#0 phar:///var/www/oxid/vendor/psalm/phar/psalm.phar/src/Psalm/Internal/Visitor/ReflectorVisitor.php(239): _HumbugBox47b9e0d79dfb\Psalm\Internal\Visitor\ReflectorVisitor->registerFunctionLike(Object(_HumbugBox47b9e0d79dfb\PhpParser\Node\Stmt\ClassMethod))
#1 phar:///var/www/oxid/vendor/psalm/phar/psalm.phar/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(176): _HumbugBox47b9e0d79dfb\Psalm\Internal\Visitor\ReflectorVisitor->enterNode(Object(_HumbugBox47b9e0d79dfb\PhpParser\Node\Stmt\ClassMethod))
#2 phar:///var/www/oxid/vendor/psalm/phar/psalm.phar/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(105): _HumbugBox47b9e0d79dfb\PhpParser\NodeTraverser->traverseArray(Array)
#3 phar:///var/www/oxid/vendor/psalm/phar/psalm.phar/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(196): _HumbugBox47b9e0d79dfb\PhpParser\NodeTraverser->traverseNode(Object(_HumbugBox47b9e0d79dfb\PhpParser\Node\Stmt\Class_))
#4 phar:///var/www/oxid/vendor/psalm/phar/psalm.phar/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(85): _HumbugBox47b9e0d79dfb\PhpParser\NodeTraverser->traverseArray(Array)
#5 phar:///var/www/oxid/vendor/psalm/phar/psalm.phar/src/Psalm/Internal/Scanner/FileScanner.php(68): _HumbugBox47b9e0d79dfb\PhpParser\NodeTraverser->traverse(Array)
#6 phar:///var/www/oxid/vendor/psalm/phar/psalm.phar/src/Psalm/Internal/Codebase/Scanner.php(453): _HumbugBox47b9e0d79dfb\Psalm\Internal\Scanner\FileScanner->scan(Object(_HumbugBox47b9e0d79dfb\Psalm\Codebase), Object(_HumbugBox47b9e0d79dfb\Psalm\Storage\FileStorage), false, Object(_HumbugBox47b9e0d79dfb\Psalm\Progress\LongProgress))
#7 phar:///var/www/oxid/vendor/psalm/phar/psalm.phar/src/Psalm/Internal/Codebase/Scanner.php(310): _HumbugBox47b9e0d79dfb\Psalm\Internal\Codebase\Scanner->scanFile('/var/www/oxid/v...', Array, true)
#8 phar:///var/www/oxid/vendor/psalm/phar/psalm.phar/src/Psalm/Internal/Codebase/Scanner.php(376): _HumbugBox47b9e0d79dfb\Psalm\Internal\Codebase\Scanner->_HumbugBox47b9e0d79dfb\Psalm\Internal\Codebase\{closure}(4, '/var/www/oxid/v...')
#9 phar:///var/www/oxid/vendor/psalm/phar/psalm.phar/src/Psalm/Internal/Codebase/Scanner.php(289): _HumbugBox47b9e0d79dfb\Psalm\Internal\Codebase\Scanner->scanFilePaths(1)
#10 phar:///var/www/oxid/vendor/psalm/phar/psalm.phar/src/Psalm/Codebase.php(362): _HumbugBox47b9e0d79dfb\Psalm\Internal\Codebase\Scanner->scanFiles(Object(_HumbugBox47b9e0d79dfb\Psalm\Internal\Codebase\ClassLikes), 1)
#11 phar:///var/www/oxid/vendor/psalm/phar/psalm.phar/src/Psalm/Internal/Analyzer/ProjectAnalyzer.php(733): _HumbugBox47b9e0d79dfb\Psalm\Codebase->scanFiles(1)
#12 phar:///var/www/oxid/vendor/psalm/phar/psalm.phar/src/psalm.php(370): _HumbugBox47b9e0d79dfb\Psalm\Internal\Analyzer\ProjectAnalyzer->checkPaths(Array)
#13 phar:///var/www/oxid/vendor/psalm/phar/psalm.phar/psalm(5): require_once('phar:///var/www...')
#14 /var/www/oxid/vendor/psalm/phar/psalm.phar(14): require('phar:///var/www...')
#15 {main}
(Psalm 3.8.1@8e54e3aa060fc490d86d0e2abbf62750516d40fd crashed due to an uncaught Throwable)
```

**Comment by keywan-ghadami-oxid** [comment]
no sorry I am not able to reproduce this on psalm.dev, I do not know how to do that.

**Comment by weirdan** [comment]
@keywan-ghadami-oxid please try with this build: https://circleci.com/api/v1.1/project/github/weirdan/psalm/232/artifacts/0/home/docker/project/build/psalm.phar

**Comment by keywan-ghadami-oxid** [comment]
it works, thanks for the quick support
