### ISSUE TITLE
Uncaught Psalm\Exception\TypeParseTreeException in psalm >= 0.3.58

### ISSUE THREAD

**Issue by zdenekdrahos** [vimeo/psalm#254]
**Exception**

```
Fatal error: Uncaught Psalm\Exception\TypeParseTreeException: Invalid characters in type in /vimeo/psalm/src/Psalm/Type.php:44
Stack trace:
#0 /vimeo/psalm/src/Psalm/Visitor/DependencyFinderVisitor.php(958): Psalm\Type::parseString('array(string)')
#1 /vimeo/psalm/src/Psalm/Visitor/DependencyFinderVisitor.php(821): Psalm\Visitor\DependencyFinderVisitor->improveParamsFromDocblock(Object(Psalm\Storage\MethodStorage), Array, NULL, Object(PhpParser\Node\Stmt\ClassMethod), Object(Psalm\CodeLocation))
#2 /vimeo/psalm/src/Psalm/Visitor/DependencyFinderVisitor.php(285): Psalm\Visitor\DependencyFinderVisitor->registerFunctionLike(Object(PhpParser\Node\Stmt\ClassMethod))
#3 /nikic/php-parser/lib/PhpParser/NodeTraverser.php(159): Psalm\Visitor\DependencyFinderVisitor->enterNode(Object(PhpParser\Node\Stmt\ClassMethod))
#4 /nikic/php-parser/lib/PhpParser/NodeTraverser.php(101): Php in /vimeo/psalm/src/Psalm/Type.php on line 44
```

**Steps to reproduce**

```bash
git clone https://github.com/EdgedesignCZ/phpqa.git
cd phpqa
composer install --no-dev
composer require vimeo/psalm:0.3.58 --update-no-dev
composer require vimeo/psalm:0.3.59 --update-no-dev
./phpqa --output cli --tools psalm
```

**Environment**

```bash
$ php -v
PHP 7.1.9-1+ubuntu14.04.1+deb.sury.org+1 (cli) (built: Sep  2 2017 06:17:11) ( NTS )
```

But [travis](https://travis-ci.org/EdgedesignCZ/phpqa/jobs/290824395#L789) succeeded, so it might be a local issue.

**Comment by weirdan** [comment]
Simpler way to reproduce is to check this file: https://github.com/squizlabs/PHP_CodeSniffer/blob/68fb8e5c76da4a220275ecce7179f25c9ecc2b13/CodeSniffer/File.php

**Comment by weirdan** [comment]
And, stipped down to the culprit:
```php
<?php
class PHP_CodeSniffer_File
{
    /**
     * @param array(string)   $listeners The initial listeners listening to processing of this file.
     */
    public function __construct(
        array $listeners
    ) {
    }
}
```
