### ISSUE TITLE
Error: Uncaught UnexpectedValueException

### ISSUE THREAD

**Issue by andres-valdes** [vimeo/psalm#2563]
I get this error trying to run any of the psalm commands:

```
> ./vendor/bin/psalm --show-info=false --diff
Uncaught UnexpectedValueException: symfony\polyfill\php73\php73 should be in cache in /Users/andres/Projects/dna-as/dna/src/vendor/vimeo/psalm/src/Psalm/Internal/Provider/ClassLikeStorageCacheProvider.php:101
Stack trace:
#0 /Users/andres/Projects/dna-as/dna/src/vendor/vimeo/psalm/src/Psalm/Internal/Provider/ClassLikeStorageProvider.php(84): Psalm\Internal\Provider\ClassLikeStorageCacheProvider->getLatestFromCache('symfony\\polyfil...', '/Users/andres/P...', '<?php\n\n/*\n * Th...')
#1 /Users/andres/Projects/dna-as/dna/src/vendor/vimeo/psalm/src/Psalm/Codebase.php(542): Psalm\Internal\Provider\ClassLikeStorageProvider->exhume('Symfony\\Polyfil...', '/Users/andres/P...', '<?php\n\n/*\n * Th...')
#2 /Users/andres/Projects/dna-as/dna/src/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Scanner.php(625): Psalm\Codebase->exhumeClassLikeStorage('Symfony\\Polyfil...', '/Users/andres/P...')
#3 /Users/andres/Projects/dna-as/dna/src/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Scanner.php(389): Psalm\Internal\Codebase\Scanner->scanFile('/Users/andres/P...', Array, true)
#4 /Users/andres/Projects/dna-as/dna/src/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Scanner.php(497): Psalm\Internal\Codebase\Scanner->Psalm\Internal\Codebase\{closure}(0, '/Users/andres/P...')
#5 /Users/andres/Projects/dna-as/dna/src/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Scanner.php(347): Psalm\Internal\Codebase\Scanner->scanFilePaths(1)
#6 /Users/andres/Projects/dna-as/dna/src/vendor/vimeo/psalm/src/Psalm/Config.php(1707): Psalm\Internal\Codebase\Scanner->scanFiles(Object(Psalm\Internal\Codebase\ClassLikes))
#7 /Users/andres/Projects/dna-as/dna/src/vendor/vimeo/psalm/src/psalm.php(506): Psalm\Config->visitComposerAutoloadFiles(Object(Psalm\Internal\Analyzer\ProjectAnalyzer), Object(Psalm\Progress\DefaultProgress))
#8 /Users/andres/Projects/dna-as/dna/src/vendor/vimeo/psalm/psalm(2): require_once('/Users/andres/P...')
#9 {main}
(Psalm 3.8.1@8e54e3aa060fc490d86d0e2abbf62750516d40fd crashed due to an uncaught Throwable)
Script ./vendor/bin/psalm --show-info=false --diff handling the psalm event returned with error code 1
```

**Comment by muglug** [comment]
Does this persist after running `--clear-cache`? Also, what version of PHP are you using?

**Comment by orklah** [comment]
I had this error at least 5 times too on PHP 7.4 in windows. Will check next time if --clear-cache solves it (I solved it by deleting psalm.xml and launching psalm --init again)

**Comment by andres-valdes** [comment]
--clear-cache worked
