### ISSUE TITLE
Exception is thrown if .phpstorm.meta.php is a directory

### ISSUE THREAD

**Issue by oqq** [vimeo/psalm#2640]
Psalm crashes and outputs this error message since v3.8.3

```
▶ tools/psalm --show-info=false --threads=16
Scanning files...
Uncaught UnexpectedValueException: File /***/***/***/***/***//.phpstorm.meta.php is a directory in phar:///***/***/.phive/phars/psalm-3.8.3.phar/src/Psalm/Internal/Provider/FileProvider.php:39
Stack trace:
#0 phar:///***/***/.phive/phars/psalm-3.8.3.phar/src/Psalm/Internal/Codebase/Scanner.php(446): _HumbugBox0cbdd78e9d3e\Psalm\Internal\Provider\FileProvider->getContents('/***/***/Pro...')
#1 phar:///***/***/.phive/phars/psalm-3.8.3.phar/src/Psalm/Internal/Codebase/Scanner.php(310): _HumbugBox0cbdd78e9d3e\Psalm\Internal\Codebase\Scanner->scanFile('/***/***/Pro...', Array, false)
#2 phar:///***/***/.phive/phars/psalm-3.8.3.phar/src/Psalm/Internal/Codebase/Scanner.php(376): _HumbugBox0cbdd78e9d3e\Psalm\Internal\Codebase\Scanner->_HumbugBox0cbdd78e9d3e\Psalm\Internal\Codebase\{closure}(2, '/***/***/Pro...')
#3 phar:///***/***/.phive/phars/psalm-3.8.3.phar/src/Psalm/Internal/Codebase/Scanner.php(289): _HumbugBox0cbdd78e9d3e\Psalm\Internal\Codebase\Scanner->scanFilePaths(1)
#4 phar:///***/***/.phive/phars/psalm-3.8.3.phar/src/Psalm/Codebase.php(358): _HumbugBox0cbdd78e9d3e\Psalm\Internal\Codebase\Scanner->scanFiles(Object(_HumbugBox0cbdd78e9d3e\Psalm\Internal\Codebase\ClassLikes), 1)
#5 phar:///***/***/.phive/phars/psalm-3.8.3.phar/src/Psalm/Config.php(1220): _HumbugBox0cbdd78e9d3e\Psalm\Codebase->scanFiles()
#6 phar:///***/***/.phive/phars/psalm-3.8.3.phar/src/Psalm/Internal/Analyzer/ProjectAnalyzer.php(381): _HumbugBox0cbdd78e9d3e\Psalm\Config->visitStubFiles(Object(_HumbugBox0cbdd78e9d3e\Psalm\Codebase), Object(_HumbugBox0cbdd78e9d3e\Psalm\Progress\DefaultProgress))
#7 phar:///***/***/.phive/phars/psalm-3.8.3.phar/src/psalm.php(373): _HumbugBox0cbdd78e9d3e\Psalm\Internal\Analyzer\ProjectAnalyzer->check('/***/***/Pro...', false)
#8 phar:///***/***/.phive/phars/psalm-3.8.3.phar/psalm(5): require_once('phar:///Users/e...')
#9 /***/***/.phive/phars/psalm-3.8.3.phar(14): require('phar:///Users/e...')
#10 {main}
(Psalm 3.8.3@389af1bfc739bfdff3f9e3dc7bd6499aee51a831 crashed due to an uncaught Throwable)
```

`.phpstorm.meta.php` is of course a directory in the root dir of the library, which is valid according to this document: https://www.jetbrains.com/help/phpstorm/ide-advanced-metadata.html

```
Create a directory and name it .phpstorm.meta.php. Inside this directory, you can store any number of metadata files and name them arbitrarily.
```

**Comment by muglug** [comment]
Should be fixed now
