### ISSUE TITLE
PHP 7.4 psalm can't find stdclass storage

### ISSUE THREAD

**Issue by auroraeosrose** [vimeo/psalm#2826]
Similar to #1016 I'm seeing this with a PHP 7.4 install and psalm 3.8.5

Uncaught InvalidArgumentException: Could not get class storage for stdclass

Notice it's now "stdclass" not "stdClass" which is what the previous bug hit

Here's the full backtrace
```
Uncaught InvalidArgumentException: Could not get class storage for stdclass in C:\Users\emsmith\AppData\Roaming\Composer\vendor\vimeo\psalm\src\Psalm\Internal\Provider\ClassLikeStorageProvider.php:47
Stack trace:
#0 C:\Users\emsmith\AppData\Roaming\Composer\vendor\vimeo\psalm\src\Psalm\Internal\Codebase\ClassLikes.php(496): Psalm\Internal\Provider\ClassLikeStorageProvider->get('stdclass')
#1 C:\Users\emsmith\AppData\Roaming\Composer\vendor\vimeo\psalm\src\Psalm\Codebase.php(736): Psalm\Internal\Codebase\ClassLikes->classExtends('stdClass', 'Slim\\Http\\Respo...', true)
#2 C:\Users\emsmith\AppData\Roaming\Composer\vendor\vimeo\psalm\src\Psalm\Internal\Type\TypeCombination.php(1009): Psalm\Codebase->classExtends('stdClass', 'Slim\\Http\\Respo...')
#3 C:\Users\emsmith\AppData\Roaming\Composer\vendor\vimeo\psalm\src\Psalm\Internal\Type\TypeCombination.php(187): Psalm\Internal\Type\TypeCombination::scrapeTypeProperties(Object(Psalm\Type\Atomic\TNamedObject), Object(Psalm\Internal\Type\TypeCombination), Object(Psalm\Codebase), false, true, 500)
#4 C:\Users\emsmith\AppData\Roaming\Composer\vendor\vimeo\psalm\src\Psalm\Type.php(1583): Psalm\Internal\Type\TypeCombination::combineTypes(Array, Object(Psalm\Codebase), false, true, 500)
#5 C:\Users\emsmith\AppData\Roaming\Composer\vendor\vimeo\psalm\src\Psalm\Internal\Analyzer\Statements\Expression\CallAnalyzer.php(2516): Psalm\Type::combineUnionTypes(Object(Psalm\Type\Union), Object(Psalm\Type\Union), Object(Psalm\Codebase))
#6 C:\Users\emsmith\AppData\Roaming\Composer\vendor\vimeo\psalm\src\Psalm\Internal\Analyzer\Statements\Expression\CallAnalyzer.php(1936): Psalm\Internal\Analyzer\Statements\Expression\CallAnalyzer::checkFunctionArgumentType(Object(Psalm\Internal\Analyzer\StatementsAnalyzer), Object(Psalm\Type\Union), Object(Psalm\Type\Union), NULL, 'PHPUnit\\Framewo...', 0, Object(Psalm\CodeLocation), Object(PhpParser\Node\Expr\Variable), Object(Psalm\Context), Object(Psalm\Storage\FunctionLikeParameter), false, false, false, Object(Psalm\CodeLocation))
#7 C:\Users\emsmith\AppData\Roaming\Composer\vendor\vimeo\psalm\src\Psalm\Internal\Analyzer\Statements\Expression\CallAnalyzer.php(1569): Psalm\Internal\Analyzer\Statements\Expression\CallAnalyzer::checkFunctionLikeTypeMatches(Object(Psalm\Internal\Analyzer\StatementsAnalyzer), Object(Psalm\Codebase), 'PHPUnit\\Framewo...', 'PHPUnit\\Framewo...', 'PHPUnit\\Framewo...', Object(Psalm\CodeLocation), Object(Psalm\Storage\FunctionLikeParameter), Object(Psalm\Type\Union), 0, Object(PhpParser\Node\Arg), Object(Psalm\Context), Array, NULL, false, false)
#8 C:\Users\emsmith\AppData\Roaming\Composer\vendor\vimeo\psalm\src\Psalm\Internal\Analyzer\Statements\Expression\CallAnalyzer.php(1362): Psalm\Internal\Analyzer\Statements\Expression\CallAnalyzer::checkFunctionLikeArgumentMatches(Object(Psalm\Internal\Analyzer\StatementsAnalyzer), 'PHPUnit\\Framewo...', 'PHPUnit\\Framewo...', 'PHPUnit\\Framewo...', Object(Psalm\CodeLocation), Object(Psalm\Storage\FunctionLikeParameter), 0, Object(PhpParser\Node\Arg), Object(Psalm\Context), Array, NULL, false, false)
#9 C:\Users\emsmith\AppData\Roaming\Composer\vendor\vimeo\psalm\src\Psalm\Internal\Analyzer\Statements\Expression\CallAnalyzer.php(326): Psalm\Internal\Analyzer\Statements\Expression\CallAnalyzer::checkFunctionLikeArgumentsMatch(Object(Psalm\Internal\Analyzer\StatementsAnalyzer), Array, 'PHPUnit\\Framewo...', Array, Object(Psalm\Storage\MethodStorage), Object(Psalm\Storage\ClassLikeStorage), Object(Psalm\Internal\Type\TemplateResult), Object(Psalm\CodeLocation), Object(Psalm\Context))
#10 C:\Users\emsmith\AppData\Roaming\Composer\vendor\vimeo\psalm\src\Psalm\Internal\Analyzer\Statements\Expression\Call\MethodCallAnalyzer.php(1063): Psalm\Internal\Analyzer\Statements\Expression\CallAnalyzer::checkMethodArgs('PHPUnit\\Framewo...', Array, Object(Psalm\Internal\Type\TemplateResult), Object(Psalm\Context), Object(Psalm\CodeLocation), Object(Psalm\Internal\Analyzer\StatementsAnalyzer))
#11 C:\Users\emsmith\AppData\Roaming\Composer\vendor\vimeo\psalm\src\Psalm\Internal\Analyzer\Statements\Expression\Call\MethodCallAnalyzer.php(215): Psalm\Internal\Analyzer\Statements\Expression\Call\MethodCallAnalyzer::analyzeAtomicCall(Object(Psalm\Internal\Analyzer\StatementsAnalyzer), Object(PhpParser\Node\Expr\MethodCall), Object(Psalm\Codebase), Object(Psalm\Context), Object(Psalm\Type\Atomic\TNamedObject), Object(Psalm\Type\Atomic\TNamedObject), NULL, NULL, false, false, true, false, Array, Array, Array, Array, Array)
#12 C:\Users\emsmith\AppData\Roaming\Composer\vendor\vimeo\psalm\src\Psalm\Internal\Analyzer\Statements\ExpressionAnalyzer.php(135): Psalm\Internal\Analyzer\Statements\Expression\Call\MethodCallAnalyzer::analyze(Object(Psalm\Internal\Analyzer\StatementsAnalyzer), Object(PhpParser\Node\Expr\MethodCall), Object(Psalm\Context))
#13 C:\Users\emsmith\AppData\Roaming\Composer\vendor\vimeo\psalm\src\Psalm\Internal\Analyzer\StatementsAnalyzer.php(704): Psalm\Internal\Analyzer\Statements\ExpressionAnalyzer::analyze(Object(Psalm\Internal\Analyzer\StatementsAnalyzer), Object(PhpParser\Node\Expr\MethodCall), Object(Psalm\Context), false, Object(Psalm\Context), true)
#14 C:\Users\emsmith\AppData\Roaming\Composer\vendor\vimeo\psalm\src\Psalm\Internal\Analyzer\FunctionLikeAnalyzer.php(533): Psalm\Internal\Analyzer\StatementsAnalyzer->analyze(Array, Object(Psalm\Context), Object(Psalm\Context), true)
#15 C:\Users\emsmith\AppData\Roaming\Composer\vendor\vimeo\psalm\src\Psalm\Internal\Analyzer\ClassAnalyzer.php(1660): Psalm\Internal\Analyzer\FunctionLikeAnalyzer->analyze(Object(Psalm\Context), Object(Psalm\Internal\Provider\NodeDataProvider), Object(Psalm\Context))
#16 C:\Users\emsmith\AppData\Roaming\Composer\vendor\vimeo\psalm\src\Psalm\Internal\Analyzer\ClassAnalyzer.php(812): Psalm\Internal\Analyzer\ClassAnalyzer->analyzeClassMethod(Object(PhpParser\Node\Stmt\ClassMethod), Object(Psalm\Storage\ClassLikeStorage), Object(Psalm\Internal\Analyzer\ClassAnalyzer), Object(Psalm\Context), Object(Psalm\Context))
#17 C:\Users\emsmith\AppData\Roaming\Composer\vendor\vimeo\psalm\src\Psalm\Internal\Analyzer\FileAnalyzer.php(201): Psalm\Internal\Analyzer\ClassAnalyzer->analyze(Object(Psalm\Context), Object(Psalm\Context))
#18 C:\Users\emsmith\AppData\Roaming\Composer\vendor\vimeo\psalm\src\Psalm\Internal\Codebase\Analyzer.php(335): Psalm\Internal\Analyzer\FileAnalyzer->analyze(NULL)
#19 C:\Users\emsmith\AppData\Roaming\Composer\vendor\vimeo\psalm\src\Psalm\Internal\Codebase\Analyzer.php(569): Psalm\Internal\Codebase\Analyzer->Psalm\Internal\Codebase\{closure}(81, 'C:\\Users\\emsmit...')
#20 C:\Users\emsmith\AppData\Roaming\Composer\vendor\vimeo\psalm\src\Psalm\Internal\Codebase\Analyzer.php(258): Psalm\Internal\Codebase\Analyzer->doAnalysis(Object(Psalm\Internal\Analyzer\ProjectAnalyzer), 1)
#21 C:\Users\emsmith\AppData\Roaming\Composer\vendor\vimeo\psalm\src\Psalm\Internal\Analyzer\ProjectAnalyzer.php(528): Psalm\Internal\Codebase\Analyzer->analyzeFiles(Object(Psalm\Internal\Analyzer\ProjectAnalyzer), 1, false)
#22 C:\Users\emsmith\AppData\Roaming\Composer\vendor\vimeo\psalm\src\psalm.php(557): Psalm\Internal\Analyzer\ProjectAnalyzer->check('C:\\Users\\emsmit...', false)
#23 C:\Users\emsmith\AppData\Roaming\Composer\vendor\vimeo\psalm\psalm(2): require_once('C:\\Users\\emsmit...')
#24 {main}
(Psalm 3.8.5@e6ec5fa22a7b9e61670a24d07b3119aff80dcd89 crashed due to an uncaught Throwable) 
```

**Comment by muglug** [comment]
@auroraeosrose mind running with `--debug-by-line` to figure out where the error comes from?

**Comment by auroraeosrose** [comment]
Do you just want the backtrace for this?

Code in the file that is killing it looks like this

```
        $entity = (object) [];

        $read->expects($this->once())
           ->method('fetchOneObject')
           ->with($this->equalTo(
               "SELECT TOP 1\r\n    foo,\r\n    bar\r\nFROM\r\n    [my_table]\r\nLEFT JOIN [join_table] ON "
                    . "[join_table].[id] = [my_table].[id]\r\nWHERE\r\n    [my_table].[id] = :_1_"
           ))
           ->willReturn($entity);
```

```
Uncaught InvalidArgumentException: Could not get class storage for stdclass in C:\Users\emsmith\AppData\Roaming\Composer\vendor\vimeo\psalm\src\Psalm\Internal\Provider\ClassLikeStorageProvider.php:47
Stack trace:
#0 C:\Users\emsmith\AppData\Roaming\Composer\vendor\vimeo\psalm\src\Psalm\Internal\Codebase\ClassLikes.php(496): Psalm\Internal\Provider\ClassLikeStorageProvider->get('stdclass')
#1 C:\Users\emsmith\AppData\Roaming\Composer\vendor\vimeo\psalm\src\Psalm\Codebase.php(736): Psalm\Internal\Codebase\ClassLikes->classExtends('stdClass', 'Slim\\Http\\Respo...', true)
#2 C:\Users\emsmith\AppData\Roaming\Composer\vendor\vimeo\psalm\src\Psalm\Internal\Type\TypeCombination.php(1009): Psalm\Codebase->classExtends('stdClass', 'Slim\\Http\\Respo...')
#3 C:\Users\emsmith\AppData\Roaming\Composer\vendor\vimeo\psalm\src\Psalm\Internal\Type\TypeCombination.php(187): Psalm\Internal\Type\TypeCombination::scrapeTypeProperties(Object(Psalm\Type\Atomic\TNamedObject), Object(Psalm\Internal\Type\TypeCombination), Object(Psalm\Codebase), false, true, 500)
#4 C:\Users\emsmith\AppData\Roaming\Composer\vendor\vimeo\psalm\src\Psalm\Type.php(1583): Psalm\Internal\Type\TypeCombination::combineTypes(Array, Object(Psalm\Codebase), false, true, 500)
#5 C:\Users\emsmith\AppData\Roaming\Composer\vendor\vimeo\psalm\src\Psalm\Internal\Analyzer\Statements\Expression\CallAnalyzer.php(2516): Psalm\Type::combineUnionTypes(Object(Psalm\Type\Union), Object(Psalm\Type\Union), Object(Psalm\Codebase))
#6 C:\Users\emsmith\AppData\Roaming\Composer\vendor\vimeo\psalm\src\Psalm\Internal\Analyzer\Statements\Expression\CallAnalyzer.php(1936): Psalm\Internal\Analyzer\Statements\Expression\CallAnalyzer::checkFunctionArgumentType(Object(Psalm\Internal\Analyzer\StatementsAnalyzer), Object(Psalm\Type\Union), Object(Psalm\Type\Union), NULL, 'PHPUnit\\Framewo...', 0, Object(Psalm\CodeLocation), Object(PhpParser\Node\Expr\Variable), Object(Psalm\Context), Object(Psalm\Storage\FunctionLikeParameter), false, false, false, Object(Psalm\CodeLocation))
#7 C:\Users\emsmith\AppData\Roaming\Composer\vendor\vimeo\psalm\src\Psalm\Internal\Analyzer\Statements\Expression\CallAnalyzer.php(1569): Psalm\Internal\Analyzer\Statements\Expression\CallAnalyzer::checkFunctionLikeTypeMatches(Object(Psalm\Internal\Analyzer\StatementsAnalyzer), Object(Psalm\Codebase), 'PHPUnit\\Framewo...', 'PHPUnit\\Framewo...', 'PHPUnit\\Framewo...', Object(Psalm\CodeLocation), Object(Psalm\Storage\FunctionLikeParameter), Object(Psalm\Type\Union), 0, Object(PhpParser\Node\Arg), Object(Psalm\Context), Array, NULL, false, false)
#8 C:\Users\emsmith\AppData\Roaming\Composer\vendor\vimeo\psalm\src\Psalm\Internal\Analyzer\Statements\Expression\CallAnalyzer.php(1362): Psalm\Internal\Analyzer\Statements\Expression\CallAnalyzer::checkFunctionLikeArgumentMatches(Object(Psalm\Internal\Analyzer\StatementsAnalyzer), 'PHPUnit\\Framewo...', 'PHPUnit\\Framewo...', 'PHPUnit\\Framewo...', Object(Psalm\CodeLocation), Object(Psalm\Storage\FunctionLikeParameter), 0, Object(PhpParser\Node\Arg), Object(Psalm\Context), Array, NULL, false, false)
#9 C:\Users\emsmith\AppData\Roaming\Composer\vendor\vimeo\psalm\src\Psalm\Internal\Analyzer\Statements\Expression\CallAnalyzer.php(326): Psalm\Internal\Analyzer\Statements\Expression\CallAnalyzer::checkFunctionLikeArgumentsMatch(Object(Psalm\Internal\Analyzer\StatementsAnalyzer), Array, 'PHPUnit\\Framewo...', Array, Object(Psalm\Storage\MethodStorage), Object(Psalm\Storage\ClassLikeStorage), Object(Psalm\Internal\Type\TemplateResult), Object(Psalm\CodeLocation), Object(Psalm\Context))
#10 C:\Users\emsmith\AppData\Roaming\Composer\vendor\vimeo\psalm\src\Psalm\Internal\Analyzer\Statements\Expression\Call\MethodCallAnalyzer.php(1063): Psalm\Internal\Analyzer\Statements\Expression\CallAnalyzer::checkMethodArgs('PHPUnit\\Framewo...', Array, Object(Psalm\Internal\Type\TemplateResult), Object(Psalm\Context), Object(Psalm\CodeLocation), Object(Psalm\Internal\Analyzer\StatementsAnalyzer))
#11 C:\Users\emsmith\AppData\Roaming\Composer\vendor\vimeo\psalm\src\Psalm\Internal\Analyzer\Statements\Expression\Call\MethodCallAnalyzer.php(215): Psalm\Internal\Analyzer\Statements\Expression\Call\MethodCallAnalyzer::analyzeAtomicCall(Object(Psalm\Internal\Analyzer\StatementsAnalyzer), Object(PhpParser\Node\Expr\MethodCall), Object(Psalm\Codebase), Object(Psalm\Context), Object(Psalm\Type\Atomic\TNamedObject), Object(Psalm\Type\Atomic\TNamedObject), NULL, NULL, false, false, true, false, Array, Array, Array, Array, Array)
#12 C:\Users\emsmith\AppData\Roaming\Composer\vendor\vimeo\psalm\src\Psalm\Internal\Analyzer\Statements\ExpressionAnalyzer.php(135): Psalm\Internal\Analyzer\Statements\Expression\Call\MethodCallAnalyzer::analyze(Object(Psalm\Internal\Analyzer\StatementsAnalyzer), Object(PhpParser\Node\Expr\MethodCall), Object(Psalm\Context))
#13 C:\Users\emsmith\AppData\Roaming\Composer\vendor\vimeo\psalm\src\Psalm\Internal\Analyzer\StatementsAnalyzer.php(704): Psalm\Internal\Analyzer\Statements\ExpressionAnalyzer::analyze(Object(Psalm\Internal\Analyzer\StatementsAnalyzer), Object(PhpParser\Node\Expr\MethodCall), Object(Psalm\Context), false, Object(Psalm\Context), true)
#14 C:\Users\emsmith\AppData\Roaming\Composer\vendor\vimeo\psalm\src\Psalm\Internal\Analyzer\FunctionLikeAnalyzer.php(533): Psalm\Internal\Analyzer\StatementsAnalyzer->analyze(Array, Object(Psalm\Context), Object(Psalm\Context), true)
#15 C:\Users\emsmith\AppData\Roaming\Composer\vendor\vimeo\psalm\src\Psalm\Internal\Analyzer\ClassAnalyzer.php(1660): Psalm\Internal\Analyzer\FunctionLikeAnalyzer->analyze(Object(Psalm\Context), Object(Psalm\Internal\Provider\NodeDataProvider), Object(Psalm\Context))
#16 C:\Users\emsmith\AppData\Roaming\Composer\vendor\vimeo\psalm\src\Psalm\Internal\Analyzer\ClassAnalyzer.php(812): Psalm\Internal\Analyzer\ClassAnalyzer->analyzeClassMethod(Object(PhpParser\Node\Stmt\ClassMethod), Object(Psalm\Storage\ClassLikeStorage), Object(Psalm\Internal\Analyzer\ClassAnalyzer), Object(Psalm\Context), Object(Psalm\Context))
#17 C:\Users\emsmith\AppData\Roaming\Composer\vendor\vimeo\psalm\src\Psalm\Internal\Analyzer\FileAnalyzer.php(201): Psalm\Internal\Analyzer\ClassAnalyzer->analyze(Object(Psalm\Context), Object(Psalm\Context))
#18 C:\Users\emsmith\AppData\Roaming\Composer\vendor\vimeo\psalm\src\Psalm\Internal\Codebase\Analyzer.php(335): Psalm\Internal\Analyzer\FileAnalyzer->analyze(NULL)
#19 C:\Users\emsmith\AppData\Roaming\Composer\vendor\vimeo\psalm\src\Psalm\Internal\Codebase\Analyzer.php(569): Psalm\Internal\Codebase\Analyzer->Psalm\Internal\Codebase\{closure}(81, 'C:\\Users\\emsmit...')
#20 C:\Users\emsmith\AppData\Roaming\Composer\vendor\vimeo\psalm\src\Psalm\Internal\Codebase\Analyzer.php(258): Psalm\Internal\Codebase\Analyzer->doAnalysis(Object(Psalm\Internal\Analyzer\ProjectAnalyzer), 1)
#21 C:\Users\emsmith\AppData\Roaming\Composer\vendor\vimeo\psalm\src\Psalm\Internal\Analyzer\ProjectAnalyzer.php(528): Psalm\Internal\Codebase\Analyzer->analyzeFiles(Object(Psalm\Internal\Analyzer\ProjectAnalyzer), 1, false)
#22 C:\Users\emsmith\AppData\Roaming\Composer\vendor\vimeo\psalm\src\psalm.php(557): Psalm\Internal\Analyzer\ProjectAnalyzer->check('C:\\Users\\emsmit...', false)
#23 C:\Users\emsmith\AppData\Roaming\Composer\vendor\vimeo\psalm\psalm(2): require_once('C:\\Users\\emsmit...')
#24 {main}
(Psalm 3.8.5@e6ec5fa22a7b9e61670a24d07b3119aff80dcd89 crashed due to an uncaught Throwable)
```

**Comment by muglug** [comment]
Ok, this is very strange – Psalm should be explicitly whitelisting `stdClass` when `(object)` casts are used in the codebase.

Mind doing some sort of `var_dump` to see if https://github.com/vimeo/psalm/blob/master/src/Psalm/Internal/Visitor/ReflectorVisitor.php#L582 is hit when running  with `--no-cache`?

**Comment by muglug** [comment]
oh and actually I suspect this might disappear when running with `--no-cache`

**Comment by auroraeosrose** [comment]
Yup no-cache fixed it - I can close this but a readme that "for weird results run without a cache" would be great :)

**Comment by muglug** [comment]
> I can close this

No, this was a legitimate bug, hopefully now fixed – mind getting latest master, running `--clear-cache`, and re-running _twice_?

**Comment by muglug** [comment]
(maybe wait a moment for composer to catch up)

**Comment by auroraeosrose** [comment]
Woo - ok, dev-master fixed that bug (I'm getting a different bug about domdocument create text node) but this appears to be fixed - thanks!
