### ISSUE TITLE
Crash after 3.9.0 update with old Psalm PHPUnit plugin

### ISSUE THREAD

**Issue by vadim2991** [vimeo/psalm#2833]
$ vendor/bin/psalm
Scanning files...
Analyzing files...

░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░Uncaught Exception: explode() expects parameter 2 to be string, object given in /app/app/vendor/vimeo/psalm/src/Psalm/Internal/Fork/Pool.php:335
Stack trace:
#0 /app/app/vendor/vimeo/psalm/src/Psalm/Internal/Fork/Pool.php(367): Psalm\Internal\Fork\Pool->readResultsFromChildren()
#1 /app/app/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Analyzer.php(444): Psalm\Internal\Fork\Pool->wait()
#2 /app/app/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Analyzer.php(241): Psalm\Internal\Codebase\Analyzer->doAnalysis(Object(Psalm\Internal\Analyzer\ProjectAnalyzer), 6)
#3 /app/app/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/ProjectAnalyzer.php(528): Psalm\Internal\Codebase\Analyzer->analyzeFiles(Object(Psalm\Internal\Analyzer\ProjectAnalyzer), 6, false)
#4 /app/app/vendor/vimeo/psalm/src/psalm.php(594): Psalm\Internal\Analyzer\ProjectAnalyzer->check('/app/app/', false)
#5 /app/app/vendor/vimeo/psalm/psalm(2): require_once('/app/app/vendor...')
#6 {main}
(Psalm 3.9.0@9866b292a40bc0258b1483428ea2f19baa7aed51 crashed due to an uncaught Throwable)

$ php -v
PHP 7.3.11-1~deb10u1 (cli) (built: Oct 26 2019 14:14:18) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.11, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.11-1~deb10u1, Copyright (c) 1999-2018, by Zend Technologies
    with Xdebug v2.7.0RC2, Copyright (c) 2002-2019, by Derick Rethans

**Comment by pilif** [comment]
I'm getting a different crash, but unfortunately, it's also not reliable. This one only seems to happen on our CI, not my local machine

```
Uncaught Exception: Expecting non-empty $root_file_path and $checked_file_path in /var/webapps/popscan/vendor/vimeo/psalm/src/Psalm/Internal/Fork/Pool.php:335
Stack trace:
#0 /var/webapps/popscan/vendor/vimeo/psalm/src/Psalm/Internal/Fork/Pool.php(367): Psalm\Internal\Fork\Pool->readResultsFromChildren()
#1 /var/webapps/popscan/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Analyzer.php(444): Psalm\Internal\Fork\Pool->wait()
#2 /var/webapps/popscan/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Analyzer.php(241): Psalm\Internal\Codebase\Analyzer->doAnalysis(Object(Psalm\Internal\Analyzer\ProjectAnalyzer), 4)
#3 /var/webapps/popscan/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/ProjectAnalyzer.php(528): Psalm\Internal\Codebase\Analyzer->analyzeFiles(Object(Psalm\Internal\Analyzer\ProjectAnalyzer), 4, false)
#4 /var/webapps/popscan/vendor/vimeo/psalm/src/psalm.php(594): Psalm\Internal\Analyzer\ProjectAnalyzer->check('/var/webapps/po...', false)
#5 /var/webapps/popscan/vendor/vimeo/psalm/psalm(2): require_once('/var/webapps/po...')
#6 {main}
(Psalm 3.9.0@9866b292a40bc0258b1483428ea2f19baa7aed51 crashed due to an uncaught Throwable)
```

**Comment by asgrim** [comment]
I'm also getting similar errors in local:

```
$ php7.4 vendor/bin/psalm
Scanning files...
Analyzing files...

░Uncaught Exception: explode() expects parameter 2 to be string, object given in /home/james/workspace/scout-apm-symfony-bundle/vendor/vimeo/psalm/src/Psalm/Internal/Fork/Pool.php:335
Stack trace:
#0 /home/james/workspace/scout-apm-symfony-bundle/vendor/vimeo/psalm/src/Psalm/Internal/Fork/Pool.php(367): Psalm\Internal\Fork\Pool->readResultsFromChildren()
#1 /home/james/workspace/scout-apm-symfony-bundle/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Analyzer.php(444): Psalm\Internal\Fork\Pool->wait()
#2 /home/james/workspace/scout-apm-symfony-bundle/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Analyzer.php(241): Psalm\Internal\Codebase\Analyzer->doAnalysis()
#3 /home/james/workspace/scout-apm-symfony-bundle/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/ProjectAnalyzer.php(528): Psalm\Internal\Codebase\Analyzer->analyzeFiles()
#4 /home/james/workspace/scout-apm-symfony-bundle/vendor/vimeo/psalm/src/psalm.php(594): Psalm\Internal\Analyzer\ProjectAnalyzer->check()
#5 /home/james/workspace/scout-apm-symfony-bundle/vendor/vimeo/psalm/psalm(2): require_once('/home/james/wor...')
#6 {main}
(Psalm 3.9.0@9866b292a40bc0258b1483428ea2f19baa7aed51 crashed due to an uncaught Throwable)
$ php7.4 -v
PHP 7.4.2 (cli) (built: Feb  5 2020 16:50:21) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.2, Copyright (c), by Zend Technologies
    with Xdebug v2.9.1, Copyright (c) 2002-2020, by Derick Rethans
```

and also [in CI](https://travis-ci.com/scoutapp/scout-apm-symfony-bundle/jobs/288432268) with a different issue, not sure if related:

```
Uncaught TypeError: explode() expects parameter 2 to be string, object given in /home/travis/build/scoutapp/scout-apm-symfony-bundle/vendor/psalm/plugin-phpunit/hooks/TestCaseHandler.php:109
Stack trace:
#0 /home/travis/build/scoutapp/scout-apm-symfony-bundle/vendor/psalm/plugin-phpunit/hooks/TestCaseHandler.php(109): explode('::', Object(Psalm\Internal\MethodIdentifier))
#1 /home/travis/build/scoutapp/scout-apm-symfony-bundle/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/ClassAnalyzer.php(1037): Psalm\PhpUnitPlugin\Hooks\TestCaseHandler::afterStatementAnalysis(Object(PhpParser\Node\Stmt\Class_), Object(Psalm\Storage\ClassLikeStorage), Object(Psalm\Internal\Analyzer\ClassAnalyzer), Object(Psalm\Codebase), Array)
#2 /home/travis/build/scoutapp/scout-apm-symfony-bundle/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/FileAnalyzer.php(201): Psalm\Internal\Analyzer\ClassAnalyzer->analyze(Object(Psalm\Context), Object(Psalm\Context))
#3 /home/travis/build/scoutapp/scout-apm-symfony-bundle/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Analyzer.php(318): Psalm\Internal\Analyzer\FileAnalyzer->analyze(NULL)
#4 /home/travis/build/scoutapp/scout-apm-symfony-bundle/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Analyzer.php(552): Psalm\Internal\Codebase\Analyzer->Psalm\Internal\Codebase\{closure}(7, '/home/travis/bu...')
#5 /home/travis/build/scoutapp/scout-apm-symfony-bundle/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Analyzer.php(241): Psalm\Internal\Codebase\Analyzer->doAnalysis(Object(Psalm\Internal\Analyzer\ProjectAnalyzer), 1)
#6 /home/travis/build/scoutapp/scout-apm-symfony-bundle/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/ProjectAnalyzer.php(528): Psalm\Internal\Codebase\Analyzer->analyzeFiles(Object(Psalm\Internal\Analyzer\ProjectAnalyzer), 1, false)
#7 /home/travis/build/scoutapp/scout-apm-symfony-bundle/vendor/vimeo/psalm/src/psalm.php(594): Psalm\Internal\Analyzer\ProjectAnalyzer->check('/home/travis/bu...', false)
#8 /home/travis/build/scoutapp/scout-apm-symfony-bundle/vendor/vimeo/psalm/psalm(2): require_once('/home/travis/bu...')
#9 {main}
(Psalm 3.9.0@9866b292a40bc0258b1483428ea2f19baa7aed51 crashed due to an uncaught Throwable)
The command "vendor/bin/psalm" exited with 1.
```

**Comment by muglug** [comment]
@vadim2991 and @asgrim: upgrade the Psalm PHPUnit plugin to prevent crashes

**Comment by muglug** [comment]
Version 0.9, released two days ago, has the fix for that

**Comment by asgrim** [comment]
@muglug ahh yes thank you, that fixes. I did a `composer up` but since `psalm/plugin-phpunit:^0.8.0` was my requirement, I don't think it updated to ^0.9.0 (different rules pre-1.0.0 I guess). Thanks!

**Comment by muglug** [comment]
And sorry @weirdan, I realise this does slighlty break semver (the plugin expected something to  be a string that became an object with `__toString`)
