### ISSUE TITLE
TypeError producing xml report

### ISSUE THREAD

**Issue by ndench** [vimeo/psalm#2865]
When running psalm with `--report=somefile.xml` I get the following error:

```
PHP Warning:  DOMDocument::createTextNode() expects parameter 1 to be string, object given in /srv/www/app/current/vendor/openlss/lib-array2xml/LSS/Array2XML.php on line 174
Uncaught TypeError: Argument 1 passed to DOMNode::appendChild() must be an instance of DOMNode, null given in /srv/www/app/current/vendor/openlss/lib-array2xml/LSS/Array2XML.php:174
Stack trace:
#0 /srv/www/app/current/vendor/openlss/lib-array2xml/LSS/Array2XML.php(174): DOMNode->appendChild(NULL)
#1 /srv/www/app/current/vendor/openlss/lib-array2xml/LSS/Array2XML.php(161): LSS\Array2XML::convert('item', Object(Psalm\Internal\Analyzer\IssueData))
#2 /srv/www/app/current/vendor/openlss/lib-array2xml/LSS/Array2XML.php(87): LSS\Array2XML::convert('report', Array)
#3 /srv/www/app/current/vendor/vimeo/psalm/src/Psalm/Report/XmlReport.php(14): LSS\Array2XML::createXML('report', Array)
#4 /srv/www/app/current/vendor/vimeo/psalm/src/Psalm/IssueBuffer.php(690): Psalm\Report\XmlReport->create()
#5 /srv/www/app/current/vendor/vimeo/psalm/src/Psalm/IssueBuffer.php(541): Psalm\IssueBuffer::getOutput(Object(Psalm\Report\ReportOptions), Array)
#6 /srv/www/app/current/vendor/vimeo/psalm/src/psalm.php(760): Psalm\IssueBuffer::finish(Object(Psalm\Internal\Analyzer\ProjectAnalyzer), true, 1582508663.7913, false, Array)
#7 /srv/www/app/current/vendor/vimeo/psalm/psalm(2): require_once('/srv/www/app/cu...')
#8 {main}
(Psalm 3.9.3@2e4154d76e24d1b4e59e6cc2bebef7790cb9e550 crashed due to an uncaught Throwable)
```

The command we're using is: 
```
vendor/bin/psalm --config="phpqa.xml" --show-info=true --use-ini-defaults --report="build/report.xml" --find-dead-code
```

Other reporting types (json, txt, emacs) and not specifying `--report` all work correctly.

Unfortunately I can't give a reproducer on psalm.dev since it's an issue with generating the report :disappointed:

**Comment by muglug** [comment]
This was fixed in https://github.com/vimeo/psalm/pull/2856

**Comment by ndench** [comment]
Ah oops, I only checked issues and not PRs before reporting. Thanks @muglug, I'll wait for the next release.

**Comment by ndench** [comment]
@muglug any idea when a new release will be tagged with this fix?

**Comment by muglug** [comment]
Some time today, hopefully
