### ISSUE TITLE
Letter case in filenames is ignored

### ISSUE THREAD

**Issue by rybakit** [vimeo/psalm#2888]
I have a folder that has an `email.php` script and an `Email.php` class. Running psalm on this folder leads to strange errors, for example:

```
Uncaught InvalidArgumentException: Could not get class storage for app\email in /client/vendor/vimeo/psalm/src/Psalm/Internal/Provider/ClassLikeStorageProvider.php:45

Stack trace:

#0 /client/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/ClassLikeAnalyzer.php(111): Psalm\Internal\Provider\ClassLikeStorageProvider->get('App\\Email')
#1 /client/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/ClassAnalyzer.php(70): Psalm\Internal\Analyzer\ClassLikeAnalyzer->__construct(Object(PhpParser\Node\Stmt\Class_), Object(Psalm\Internal\Analyzer\NamespaceAnalyzer), 'App\\Email')
#2 /client/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/NamespaceAnalyzer.php(121): Psalm\Internal\Analyzer\ClassAnalyzer->__construct(Object(PhpParser\Node\Stmt\Class_), Object(Psalm\Internal\Analyzer\NamespaceAnalyzer), 'App\\Email')
#3 /client/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/NamespaceAnalyzer.php(73): Psalm\Internal\Analyzer\NamespaceAnalyzer->collectAnalyzableClassLike(Object(PhpParser\Node\Stmt\Class_))
#4 /client/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/FileAnalyzer.php(243): Psalm\Internal\Analyzer\NamespaceAnalyzer->collectAnalyzableInformation()
#5 /client/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/FileAnalyzer.php(182): Psalm\Internal\Analyzer\FileAnalyzer->populateCheckers(Array)
#6 /client/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Analyzer.php(318): Psalm\Internal\Analyzer\FileAnalyzer->analyze(NULL)
#7 /client/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Analyzer.php(552): Psalm\Internal\Codebase\Analyzer->Psalm\Internal\Codebase\{closure}(60, '/client/example...')
#8 /client/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Analyzer.php(241): Psalm\Internal\Codebase\Analyzer->doAnalysis(Object(Psalm\Internal\Analyzer\ProjectAnalyzer), 1)
#9 /client/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/ProjectAnalyzer.php(528): Psalm\Internal\Codebase\Analyzer->analyzeFiles(Object(Psalm\Internal\Analyzer\ProjectAnalyzer), 1, false)
#10 /client/vendor/vimeo/psalm/src/psalm.php(594): Psalm\Internal\Analyzer\ProjectAnalyzer->check('/client/', false)
#11 /client/vendor/vimeo/psalm/psalm(2): require_once('/client/vendor/...')
#12 {main}

(Psalm 3.9.3@2e4154d76e24d1b4e59e6cc2bebef7790cb9e550 crashed due to an uncaught Throwable)
```
or

```
ERROR: UndefinedFunction - examples/user_defined_type/email.php:23:11 - Function create_client does not exist
$client = create_client($packer);
```
Renaming the file `email.php` eliminates these errors.

Link to the folder:  https://github.com/tarantool-php/client/tree/ba0938a52678c9378d1fe2a58719d13ac802bdd1/examples/user_defined_type
Link to the failed build: https://travis-ci.org/tarantool-php/client/jobs/655913882

**Comment by muglug** [comment]
You may need to debug this one yourself – my file system is case-insensitive (as are all macs by default) so it's not possible to have this on a mac.
