### ISSUE TITLE
Integrating psalm with PhpStorm having PHP on Docker container

### ISSUE THREAD

**Issue by ktrzos** [vimeo/psalm#3038]
Hi all,

I'm trying to integrate psalm with my project and PhpStorm. Doing everything like it is described [here](https://psalm.dev/docs/running_psalm/language_server/), but with one difference. My PHP is available in Docker container. Instead of giving path to PHP itself, I'm setting path to my bash script:

**/srv/www/project/bin/php**

```bash
#!/bin/bash

docker exec -u=appuser -t project_app_1 php $*

exit $?
```

So, in IDE configuration I'm setting "Raw command", extension "php" and this command:

```
/srv/www/project/bin/php vendor/bin/psalm-language-server
```

But, this does not work. I'm getting this error:

> LanguageServer for definition
 exe : path /srv/www/klaskrank/bin/php args : vendor/bin/psalm-language-server
not initialized after 10s
> Check settings

Here is also my psalm.xml:

```xml
<?xml version="1.0"?>
<psalm
    totallyTyped="false"
    errorLevel="4"
    resolveFromConfigFile="true"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns="https://getpsalm.org/schema/config"
    xsi:schemaLocation="https://getpsalm.org/schema/config vendor/vimeo/psalm/config.xsd"
>
    <projectFiles>
        <directory name="src" />
        <ignoreFiles>
            <directory name="vendor" />
        </ignoreFiles>
    </projectFiles>
</psalm>
```

Thanks in advance for any help.

**Comment by muglug** [comment]
Maybe someone else who's done this successfully could chime in (or maybe you could borrow some ideas from [setting up XDebug in Docker with PHPStorm](https://www.pascallandau.com/blog/setup-phpstorm-with-xdebug-on-docker/) but the best idea, in my experience, is to use PHP running on the host system instead.

**Comment by weirdan** [comment]
You certainly need to use `-i` (`--interactive`) flag in addition to `-t`, as by default Psalm LSP server communicates with the client over the stdio streams.

**Comment by ktrzos** [comment]
While setting `-it`, server still doesn't want to run. It showing me this message in Psalm errors log:

> the input device is not a TTY

But setting only `-i` works, and I've got a green dot on the bottom of PhpStorm. So thanks for that :).

Now, another question. I assume that it should work. But unfortunately I still don't have any warnings/errors in my IDE from Psalm. Do I need any additional configuration set?

**Comment by weirdan** [comment]
You may need to enable LSP inspections: https://www.jetbrains.com/help/phpstorm/code-inspection.html

**Comment by ktrzos** [comment]
I've got it turned on.
I've checked the "Connected files" list and got one PHP file:
- file:///srv/www/project/src/Controller/SomeController.php

But inside of Docker container this path is 
- file:///srv/www/src/Controller/SomeController.php
(without `project` dir)

Does it matter? How could I check this?

**Comment by ktrzos** [comment]
Huh! I've just noticed an error thrown by LSP plugin:


```
java.lang.NullPointerException
	at com.github.gtache.lsp.utils.FileUtils$.pathToUri(FileUtils.scala:186)
	at com.github.gtache.lsp.utils.FileUtils$.editorToProjectFolderUri(FileUtils.scala:165)
	at com.github.gtache.lsp.PluginMain$.$anonfun$editorOpened$1(PluginMain.scala:135)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:238)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by ktrzos** [comment]
Huh! I've just noticed an error thrown by LSP plugin:

```
java.lang.NullPointerException
	at com.github.gtache.lsp.utils.FileUtils$.pathToUri(FileUtils.scala:186)
	at com.github.gtache.lsp.utils.FileUtils$.editorToProjectFolderUri(FileUtils.scala:165)
	at com.github.gtache.lsp.PluginMain$.$anonfun$editorOpened$1(PluginMain.scala:135)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:238)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

Could it somehow be related with Psalm, or is it problem of [gtache/intellij-lsp](https://github.com/gtache/intellij-lsp)?

**Comment by weirdan** [comment]
> Does it matter?

Likely.

Looking at LSP specs there's no standard way to map paths, so either client or server has to provide that option. I don't think either does in this case.

**Comment by ktrzos** [comment]
@weirdan 

And what about this Java error which I've shown above?

**Comment by weirdan** [comment]
Well, it looks like the plugin has a problem with some file path, possibly sent from the LSP server.

**Comment by ktrzos** [comment]
Ok. So I've created an issue in there https://github.com/gtache/intellij-lsp/issues/143 :). Maybe someone from that project could help. Nevertheless, I'm closing this issue, because server is working :). Thanks for help @weirdan!
