### ISSUE TITLE
Invalidate all caches when composer lockfile changes

### ISSUE THREAD

**Issue by marvin255** [vimeo/psalm#3117]
I have updated my composer dependencies. `nikic/php-parser` have been updated to version 4.4. With this version psalm crashes during any run.

### Versions
* `psalm`: ^3.10,
* `nikic/php-parser`: ^4.4

### Example
Any run of psalm console command.

### Expected Behavior
No errors.

### Actual behavior
```
Uncaught Exception: Return value of PhpParser\Comment::getFilePos() must be of the type int, null returned
Stack trace in the forked worker:
#0 /var/app/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/ClassAnalyzer.php(1699): PhpParser\Comment->getFilePos()
#1 /var/app/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/ClassAnalyzer.php(721): Psalm\Internal\Analyzer\ClassAnalyzer->analyzeClassMethod(Object(PhpParser\Node\Stmt\ClassMethod), Object(Psalm\Storage\ClassLikeStorage), Object(Psalm\Internal\Analyzer\ClassAnalyzer), Object(Psalm\Context), Object(Psalm\Context))
#2 /var/app/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/FileAnalyzer.php(198): Psalm\Internal\Analyzer\ClassAnalyzer->analyze(Object(Psalm\Context), Object(Psalm\Context))
#3 /var/app/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Analyzer.php(318): Psalm\Internal\Analyzer\FileAnalyzer->analyze(NULL)
#4 /var/app/vendor/vimeo/psalm/src/Psalm/Internal/Fork/Pool.php(182): Psalm\Internal\Codebase\Analyzer->Psalm\Internal\Codebase\{closure}(0, '/var/app/src/In...')
#5 /var/app/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Analyzer.php(384): Psalm\Internal\Fork\Pool->__construct(Array, Object(Closure), Object(Closure), Object(Closure), Object(Closure))
#6 /var/app/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Analyzer.php(241): Psalm\Internal\Codebase\Analyzer->doAnalysis(Object(Psalm\Internal\Analyzer\ProjectAnalyzer), 3)
#7 /var/app/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/ProjectAnalyzer.php(527): Psalm\Internal\Codebase\Analyzer->analyzeFiles(Object(Psalm\Internal\Analyzer\ProjectAnalyzer), 3, false)
#8 /var/app/vendor/vimeo/psalm/src/psalm.php(594): Psalm\Internal\Analyzer\ProjectAnalyzer->check('/var/app/', false)
#9 /var/app/vendor/vimeo/psalm/psalm(2): require_once('/var/app/vendor...')
#10 {main} in /var/app/vendor/vimeo/psalm/src/Psalm/Internal/Fork/Pool.php:339
Stack trace:
#0 /var/app/vendor/vimeo/psalm/src/Psalm/Internal/Fork/Pool.php(371): Psalm\Internal\Fork\Pool->readResultsFromChildren()
#1 /var/app/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Analyzer.php(444): Psalm\Internal\Fork\Pool->wait()
#2 /var/app/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Analyzer.php(241): Psalm\Internal\Codebase\Analyzer->doAnalysis(Object(Psalm\Internal\Analyzer\ProjectAnalyzer), 3)
#3 /var/app/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/ProjectAnalyzer.php(527): Psalm\Internal\Codebase\Analyzer->analyzeFiles(Object(Psalm\Internal\Analyzer\ProjectAnalyzer), 3, false)
#4 /var/app/vendor/vimeo/psalm/src/psalm.php(594): Psalm\Internal\Analyzer\ProjectAnalyzer->check('/var/app/', false)
#5 /var/app/vendor/vimeo/psalm/psalm(2): require_once('/var/app/vendor...')
#6 {main}
(Psalm 3.10.1@eeed5ecccc10131397f0eb7ee6da810c0be3a7fc crashed due to an uncaught Throwable)
```

**Comment by marvin255** [comment]
This is not reproducable on psalm.dev because I can't set composer dependencies for psalm on psalm.dev.

**Comment by muglug** [comment]
What if you clear your Psalm cache with `--clear-cache`? Do you still see the errors?

**Comment by marvin255** [comment]
Yes. Run is ok, without any errors.
