### ISSUE TITLE
Crash with invalid(?) extended array typehint check

### ISSUE THREAD

**Issue by weirdan** [vimeo/psalm#312]
Looking at the wiki section on 'makeshift structs' typing I thought that maybe psalm could also support tuples in a similar way, so I tried the following:
```php
<?php

/**
 * @psalm-param array{int,string,bool} $b
 */
function a($b)
{

}
```
But with this input psalm crashes with the following output:
```
PHP Notice:  Undefined offset: 1 in /home/weirdan/.composer/vendor/vimeo/psalm/src/Psalm/Type.php on line 190

Notice: Undefined offset: 1 in /home/weirdan/.composer/vendor/vimeo/psalm/src/Psalm/Type.php on line 190
PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Psalm\Type::getTypeFromTree() must be an instance of Psalm\Type\ParseTree, null given, called in /home/weirdan/.composer/vendor/vimeo/psalm/src/Psalm/Type.php on line 190 and defined in /home/weirdan/.composer/vendor/vimeo/psalm/src/Psalm/Type.php:118
Stack trace:
#0 /home/weirdan/.composer/vendor/vimeo/psalm/src/Psalm/Type.php(190): Psalm\Type::getTypeFromTree(NULL)
#1 /home/weirdan/.composer/vendor/vimeo/psalm/src/Psalm/Type.php(59): Psalm\Type::getTypeFromTree(Object(Psalm\Type\ParseTree))
#2 /home/weirdan/.composer/vendor/vimeo/psalm/src/Psalm/Visitor/DependencyFinderVisitor.php(1002): Psalm\Type::parseString('array{int,strin...')
#3 /home/weirdan/.composer/vendor/vimeo/psalm/src/Psalm/Visitor/DependencyFinderVisitor.php(872): Psalm\Visitor\DependencyFinderVisitor->improveParamsFromDocblock(Object(Psalm\Storage\FunctionLikeStorage), Array, NULL, Object(PhpParser\Node\Stmt\Function_), Object(Psalm\CodeLocation))
#4 /home/weirdan/.composer/vendor/vimeo/psalm/src/Psal in /home/weirdan/.composer/vendor/vimeo/psalm/src/Psalm/Type.php on line 118

Fatal error: Uncaught TypeError: Argument 1 passed to Psalm\Type::getTypeFromTree() must be an instance of Psalm\Type\ParseTree, null given, called in /home/weirdan/.composer/vendor/vimeo/psalm/src/Psalm/Type.php on line 190 and defined in /home/weirdan/.composer/vendor/vimeo/psalm/src/Psalm/Type.php:118
Stack trace:
#0 /home/weirdan/.composer/vendor/vimeo/psalm/src/Psalm/Type.php(190): Psalm\Type::getTypeFromTree(NULL)
#1 /home/weirdan/.composer/vendor/vimeo/psalm/src/Psalm/Type.php(59): Psalm\Type::getTypeFromTree(Object(Psalm\Type\ParseTree))
#2 /home/weirdan/.composer/vendor/vimeo/psalm/src/Psalm/Visitor/DependencyFinderVisitor.php(1002): Psalm\Type::parseString('array{int,strin...')
#3 /home/weirdan/.composer/vendor/vimeo/psalm/src/Psalm/Visitor/DependencyFinderVisitor.php(872): Psalm\Visitor\DependencyFinderVisitor->improveParamsFromDocblock(Object(Psalm\Storage\FunctionLikeStorage), Array, NULL, Object(PhpParser\Node\Stmt\Function_), Object(Psalm\CodeLocation))
#4 /home/weirdan/.composer/vendor/vimeo/psalm/src/Psal in /home/weirdan/.composer/vendor/vimeo/psalm/src/Psalm/Type.php on line 118
```
```
$ psalm --version
Psalm dev-master@7d33db0d19d85e1c318ee2261f548513f0905800
```

**Comment by weirdan** [comment]
Apparently tuples can be annotated, with somewhat contrived syntax: `array{0:int,1:string,2:bool}`

**Comment by muglug** [comment]
Yup, but obviously this shouldn't be a crash. Will fix.
