### ISSUE TITLE
Crash when closure has `self` as a return type

### ISSUE THREAD

**Issue by weirdan** [vimeo/psalm#313]
Psalm crashes when checking the closure that is typed to return `self` (referring to the containing class). Apparently PHP has no problems with such type hint, neither psalm has any problems when `self` is used to annotate the closure param. 

Checked file:
```php
<?php

class A
{
    /**
     * @var self[]
     */
    private $subitems;
    public function __construct(array $in = [])
    {
        $this->subitems = array_map(function(self $i): self { return $i; }, $in);
    }
}

new A([new A, new A]);
```
Psalm output:
```
PHP Notice:  Undefined offset: 1 in /home/weirdan/.composer/vendor/vimeo/psalm/src/Psalm/Checker/Statements/ExpressionChecker.php on line 1784

Notice: Undefined offset: 1 in /home/weirdan/.composer/vendor/vimeo/psalm/src/Psalm/Checker/Statements/ExpressionChecker.php on line 1784
PHP Fatal error:  Uncaught InvalidArgumentException: $class cannot be empty in /home/weirdan/.composer/vendor/vimeo/psalm/src/Psalm/Checker/ClassLikeChecker.php:956
Stack trace:
#0 /home/weirdan/.composer/vendor/vimeo/psalm/src/Psalm/Type/Atomic.php(216): Psalm\Checker\ClassLikeChecker::checkFullyQualifiedClassLikeName(Object(Psalm\Checker\ProjectChecker), '', Object(Psalm\CodeLocation), Array, false)
#1 /home/weirdan/.composer/vendor/vimeo/psalm/src/Psalm/Type/Union.php(394): Psalm\Type\Atomic->check(Object(Psalm\Checker\ClosureChecker), Object(Psalm\CodeLocation), Array, Array, false)
#2 /home/weirdan/.composer/vendor/vimeo/psalm/src/Psalm/Checker/FunctionLikeChecker.php(970): Psalm\Type\Union->check(Object(Psalm\Checker\ClosureChecker), Object(Psalm\CodeLocation), Array, Array, false)
#3 /home/weirdan/.composer/vendor/vimeo/psalm/src/Psalm/Checker/FunctionLikeChecker.php(556): Psalm\Checker\FunctionLikeChecker->verifyReturnType(Object(Psalm\Checker\ProjectChecker), Object(Psalm\Type\Union), 'A', Object(Psalm\CodeLocation))
 in /home/weirdan/.composer/vendor/vimeo/psalm/src/Psalm/Checker/ClassLikeChecker.php on line 956

Fatal error: Uncaught InvalidArgumentException: $class cannot be empty in /home/weirdan/.composer/vendor/vimeo/psalm/src/Psalm/Checker/ClassLikeChecker.php:956
Stack trace:
#0 /home/weirdan/.composer/vendor/vimeo/psalm/src/Psalm/Type/Atomic.php(216): Psalm\Checker\ClassLikeChecker::checkFullyQualifiedClassLikeName(Object(Psalm\Checker\ProjectChecker), '', Object(Psalm\CodeLocation), Array, false)
#1 /home/weirdan/.composer/vendor/vimeo/psalm/src/Psalm/Type/Union.php(394): Psalm\Type\Atomic->check(Object(Psalm\Checker\ClosureChecker), Object(Psalm\CodeLocation), Array, Array, false)
#2 /home/weirdan/.composer/vendor/vimeo/psalm/src/Psalm/Checker/FunctionLikeChecker.php(970): Psalm\Type\Union->check(Object(Psalm\Checker\ClosureChecker), Object(Psalm\CodeLocation), Array, Array, false)
#3 /home/weirdan/.composer/vendor/vimeo/psalm/src/Psalm/Checker/FunctionLikeChecker.php(556): Psalm\Checker\FunctionLikeChecker->verifyReturnType(Object(Psalm\Checker\ProjectChecker), Object(Psalm\Type\Union), 'A', Object(Psalm\CodeLocation))
 in /home/weirdan/.composer/vendor/vimeo/psalm/src/Psalm/Checker/ClassLikeChecker.php on line 956
```
```
$ psalm --version
Psalm dev-master@7d33db0d19d85e1c318ee2261f548513f0905800
```

**Comment by muglug** [comment]
Thanks for finding!
