### ISSUE TITLE
Crash with nikic/php-parser 4.3.0

### ISSUE THREAD

**Issue by greg0ire** [vimeo/psalm#3155]
```
Uncaught TypeError: Return value of PhpParser\Comment::getFilePos() must be of the type int, null returned in /home/greg/dev/doctrine-dbal/vendor/nikic/php-parser/lib/PhpParser/Comment.php:53
Stack trace:
#0 /home/greg/dev/doctrine-dbal/vendor/vimeo/psalm/src/Psalm/CodeLocation.php(131): PhpParser\Comment->getFilePos()
#1 /home/greg/dev/doctrine-dbal/vendor/vimeo/psalm/src/Psalm/Internal/PhpVisitor/ReflectorVisitor.php(947): Psalm\CodeLocation->__construct(Object(Psalm\Internal\Scanner\FileScanner), Object(PhpParser\Node\Stmt\Interface_))
#2 /home/greg/dev/doctrine-dbal/vendor/vimeo/psalm/src/Psalm/Internal/PhpVisitor/ReflectorVisitor.php(272): Psalm\Internal\PhpVisitor\ReflectorVisitor->registerClassLike(Object(PhpParser\Node\Stmt\Interface_))
#3 /home/greg/dev/doctrine-dbal/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(200): Psalm\Internal\PhpVisitor\ReflectorVisitor->enterNode(Object(PhpParser\Node\Stmt\Interface_))
#4 /home/greg/dev/doctrine-dbal/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(114): PhpParser\NodeTraverser->traverseArray(Array)
#5 /home/greg/dev/doctrine-dbal/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(223): PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Stmt\Namespace_))
#6 /home/greg/dev/doctrine-dbal/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(91): PhpParser\NodeTraverser->traverseArray(Array)
#7 /home/greg/dev/doctrine-dbal/vendor/vimeo/psalm/src/Psalm/Internal/Scanner/FileScanner.php(94): PhpParser\NodeTraverser->traverse(Array)
#8 /home/greg/dev/doctrine-dbal/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Scanner.php(586): Psalm\Internal\Scanner\FileScanner->scan(Object(Psalm\Codebase), Object(Psalm\Storage\FileStorage), false, Object(Psalm\Progress\DefaultProgress))
#9 /home/greg/dev/doctrine-dbal/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Scanner.php(367): Psalm\Internal\Codebase\Scanner->scanFile('/home/greg/dev/...', Array, true)
#10 /home/greg/dev/doctrine-dbal/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Scanner.php(475): Psalm\Internal\Codebase\Scanner->Psalm\Internal\Codebase\{closure}(0, '/home/greg/dev/...')
#11 /home/greg/dev/doctrine-dbal/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Scanner.php(325): Psalm\Internal\Codebase\Scanner->scanFilePaths(1)
#12 /home/greg/dev/doctrine-dbal/vendor/vimeo/psalm/src/Psalm/Codebase.php(477): Psalm\Internal\Codebase\Scanner->scanFiles(Object(Psalm\Internal\Codebase\ClassLikes), 3)
#13 /home/greg/dev/doctrine-dbal/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/ProjectAnalyzer.php(519): Psalm\Codebase->scanFiles(3)
#14 /home/greg/dev/doctrine-dbal/vendor/vimeo/psalm/src/psalm.php(588): Psalm\Internal\Analyzer\ProjectAnalyzer->check('/home/greg/dev/...', false)
#15 /home/greg/dev/doctrine-dbal/vendor/vimeo/psalm/psalm(2): require_once('/home/greg/dev/...')
#16 {main}
(Psalm 3.11.2@d470903722cfcbc1cd04744c5491d3e6d13ec3d9 crashed due to an uncaught Throwable)
```

Note that upgrading to v4.4.0 fixes the issue

**Comment by greg0ire** [comment]
Nope, sorry little bot

**Comment by muglug** [comment]
I think this was fixed in the current release - do you still see it?

**Comment by weirdan** [comment]
@muglug `Psalm 3.11.2@d470903722cfcbc1cd04744c5491d3e6d13ec3d9` (in the error message) is the current release as far as can tell.

**Comment by vasily-kartashov** [comment]
Try with `--no-cache`. Solved it for me.

**Comment by greg0ire** [comment]
It must have to do with cache because it works after a reboot.

**Comment by YetiCGN** [comment]
@greg0ire Then, I believe, you can close the ticket. 😉

**Comment by greg0ire** [comment]
I will let Matthew Brown decide on this, maybe there is something that needs to be fixed, like auto-cleaning the cache under some circumstances. Or maybe this will never happen again for some other reason and it can be closed, but since it happen to me and other people, I guess it could happen again to anyone.

**Comment by muglug** [comment]
@zerkms this fits the bill of an easy problem to fix – the cache should clear whenever there's a lockfile change, but it appears not to be

**Comment by weirdan** [comment]
However multiple lockfiles may need to be considered when Psalm is installed globally (with `composer global require vimeo/psalm`).
