### ISSUE TITLE
Unexpected LHS of property - What does it mean?

### ISSUE THREAD

**Issue by vjandrea** [vimeo/psalm#3191]
I'm having trouble to undestand what's wrong with this piece of code, psalm crashes with an "`Unexpected LHS of property`" exception. Does LHS stand for "Left Hand Side" ? If so, what's wrong in using get_class?

```php
private function hasAttachmentOfGivenType(string $attachment_type): bool
{
        $attachments = $this->getAttachments();

        if (empty($attachments)) {
            return false;
        }

        foreach ($attachments as $attachment) {
            if (is_object($attachment) && get_class($attachment) === $attachment_type) {
                return true;
            }
        }
        
        return false;
}
```

Stack trace:
```
Uncaught Psalm\Exception\TypeParseTreeException: Unexpected LHS of property in C:\Users\user\AppData\Roaming\Composer\vendor\vimeo\psalm\src\Psalm\Internal\Type\ParseTree.php:338
Stack trace:
#0 C:\Users\user\AppData\Roaming\Composer\vendor\vimeo\psalm\src\Psalm\Type.php(181): Psalm\Internal\Type\ParseTree::createFromTokens(Array)
#1 C:\Users\user\AppData\Roaming\Composer\vendor\vimeo\psalm\src\Psalm\Type.php(142): Psalm\Type::parseTokens(Array, NULL, Array)
#2 C:\Users\user\AppData\Roaming\Composer\vendor\vimeo\psalm\src\Psalm\Internal\Type\AssertionReconciler.php(592): Psalm\Type::parseString('class-string<Ap...', NULL, Array)
#3 C:\Users\user\AppData\Roaming\Composer\vendor\vimeo\psalm\src\Psalm\Type\Reconciler.php(261): Psalm\Internal\Type\AssertionReconciler::reconcile('class-string<Ap...', Object(Psalm\Type\Union), '$attachment_typ...', Object(Psalm\Internal\Analyzer\StatementsAnalyzer), true, Array, Object(Psalm\CodeLocation), Array, 0)
#4 C:\Users\user\AppData\Roaming\Composer\vendor\vimeo\psalm\src\Psalm\Internal\Analyzer\Statements\Block\IfAnalyzer.php(259): Psalm\Type\Reconciler::reconcileKeyedTypes(Array, Array, Array, Array, Array, Object(Psalm\Internal\Analyzer\StatementsAnalyzer), Array, true, Object(Psalm\CodeLocation))
#5 C:\Users\user\AppData\Roaming\Composer\vendor\vimeo\psalm\src\Psalm\Internal\Analyzer\StatementsAnalyzer.php(374): Psalm\Internal\Analyzer\Statements\Block\IfAnalyzer::analyze(Object(Psalm\Internal\Analyzer\StatementsAnalyzer), Object(PhpParser\Node\Stmt\If_), Object(Psalm\Context))
#6 C:\Users\user\AppData\Roaming\Composer\vendor\vimeo\psalm\src\Psalm\Internal\Analyzer\Statements\Block\LoopAnalyzer.php(193): Psalm\Internal\Analyzer\StatementsAnalyzer->analyze(Array, Object(Psalm\Context))
#7 C:\Users\user\AppData\Roaming\Composer\vendor\vimeo\psalm\src\Psalm\Internal\Analyzer\Statements\Block\ForeachAnalyzer.php(304): Psalm\Internal\Analyzer\Statements\Block\LoopAnalyzer::analyze(Object(Psalm\Internal\Analyzer\StatementsAnalyzer), Array, Array, Array, Object(Psalm\Internal\Scope\LoopScope), Object(Psalm\Context))
#8 C:\Users\user\AppData\Roaming\Composer\vendor\vimeo\psalm\src\Psalm\Internal\Analyzer\StatementsAnalyzer.php(386): Psalm\Internal\Analyzer\Statements\Block\ForeachAnalyzer::analyze(Object(Psalm\Internal\Analyzer\StatementsAnalyzer), Object(PhpParser\Node\Stmt\Foreach_), Object(Psalm\Context))
#9 C:\Users\user\AppData\Roaming\Composer\vendor\vimeo\psalm\src\Psalm\Internal\Analyzer\FunctionLikeAnalyzer.php(541): Psalm\Internal\Analyzer\StatementsAnalyzer->analyze(Array, Object(Psalm\Context), Object(Psalm\Context), true)
#10 C:\Users\user\AppData\Roaming\Composer\vendor\vimeo\psalm\src\Psalm\Internal\Analyzer\ClassAnalyzer.php(1750): Psalm\Internal\Analyzer\FunctionLikeAnalyzer->analyze(Object(Psalm\Context), Object(Psalm\Internal\Provider\NodeDataProvider), Object(Psalm\Context))
#11 C:\Users\user\AppData\Roaming\Composer\vendor\vimeo\psalm\src\Psalm\Internal\Analyzer\ClassAnalyzer.php(726): Psalm\Internal\Analyzer\ClassAnalyzer->analyzeClassMethod(Object(PhpParser\Node\Stmt\ClassMethod), Object(Psalm\Storage\ClassLikeStorage), Object(Psalm\Internal\Analyzer\ClassAnalyzer), Object(Psalm\Context), Object(Psalm\Context))
#12 C:\Users\user\AppData\Roaming\Composer\vendor\vimeo\psalm\src\Psalm\Internal\Analyzer\FileAnalyzer.php(201): Psalm\Internal\Analyzer\ClassAnalyzer->analyze(Object(Psalm\Context), Object(Psalm\Context))
#13 C:\Users\user\AppData\Roaming\Composer\vendor\vimeo\psalm\src\Psalm\Internal\Codebase\Analyzer.php(357): Psalm\Internal\Analyzer\FileAnalyzer->analyze(NULL)
#14 C:\Users\user\AppData\Roaming\Composer\vendor\vimeo\psalm\src\Psalm\Internal\Codebase\Analyzer.php(589): Psalm\Internal\Codebase\Analyzer->Psalm\Internal\Codebase\{closure}(0, 'C:\\Users\\Andrea...')
#15 C:\Users\user\AppData\Roaming\Composer\vendor\vimeo\psalm\src\Psalm\Internal\Codebase\Analyzer.php(267): Psalm\Internal\Codebase\Analyzer->doAnalysis(Object(Psalm\Internal\Analyzer\ProjectAnalyzer), 1)
#16 C:\Users\user\AppData\Roaming\Composer\vendor\vimeo\psalm\src\Psalm\Internal\Analyzer\ProjectAnalyzer.php(1146): Psalm\Internal\Codebase\Analyzer->analyzeFiles(Object(Psalm\Internal\Analyzer\ProjectAnalyzer), 1, false, false)
#17 C:\Users\user\AppData\Roaming\Composer\vendor\vimeo\psalm\src\psalm.php(590): Psalm\Internal\Analyzer\ProjectAnalyzer->checkPaths(Array)
#18 C:\Users\user\AppData\Roaming\Composer\vendor\vimeo\psalm\psalm(2): require_once('C:\\Users\\Andrea...')
#19 {main}
(Psalm 3.11.2@d470903722cfcbc1cd04744c5491d3e6d13ec3d9 crashed due to an uncaught Throwable)
```

**Comment by weirdan** [comment]
What's the return type of `getAttachments()` (including the type from docblocks)?

**Comment by vjandrea** [comment]
`getAttachments()` returns an array of objects that implement a common interface.
I added `is_object `to the condition to see if that was the issue, since `get_class `might return false, but that didn't change the behavior.
I tried to adapt the code [on psalm.dev](https://psalm.dev/r/5ebc9cd334)

**Comment by weirdan** [comment]
Obviously there's something else at play, as it doesn't fail on psalm.dev. Do you run the latest Psalm version and did you try `dev-master` (`composer require --dev vimeo/psalm:dev-master`)?

**Comment by muglug** [comment]
It would be great if you could get a concise valid reproducer on your end so I can add to the test suite, but this should be fixed in latest Psalm.

**Comment by vjandrea** [comment]
@muglug  What's the cause of "Unexpected LHS of property"? So I can try to pin down the reproducer.

**Comment by cedw032** [comment]
Ok, I am totally speculating here, but...

I think it is to do with declaring a type in the form:
```
@psalm-type myType = array {
  field1: string,
  field2: int
}
```

My guess it that if you forget the comma here it is interpreting the first line as part of the LHS (left hand side) of the second field declaration.

```
@psalm-type myType = array {
  field1: string // <- Missing comma here might be the issue?
  field2: int
}
```
