### ISSUE TITLE
Psalm crashes when using Symfony validator in test case

### ISSUE THREAD

**Issue by tjveldhuizen** [vimeo/psalm#3196]
I've made a [reproducer](https://github.com/tjveldhuizen/psalm-crash-reproducer) which makes Psalm crash while analyzing the code.

```
$ git clone git@github.com:tjveldhuizen/psalm-crash-reproducer.git
$ cd psalm-crash-reproducer/
$ composer install
$ bin/phpunit
$ vendor/bin/psalm
```

Output with --debug: [psalm-crash-reproducer.txt](https://github.com/vimeo/psalm/files/4500457/psalm-crash-reproducer.txt)

```
tjv@PC:~/php-projects/temp/psalm-crash-reproducer$ php -v
PHP 7.2.29-1+ubuntu18.04.1+deb.sury.org+1 (cli) (built: Mar 20 2020 13:54:39) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.29-1+ubuntu18.04.1+deb.sury.org+1, Copyright (c) 1999-2018, by Zend Technologies
    with Xdebug v2.9.3, Copyright (c) 2002-2020, by Derick Rethans
tjv@PC:~/php-projects/temp/psalm-crash-reproducer$
tjv@PC:~/php-projects/temp/psalm-crash-reproducer$ vendor/bin/psalm
Scanning files...
Analyzing files...

Uncaught InvalidArgumentException: Could not get class storage for symfony\component\validator\validator\traceablevalidator in /home/tjv/php-projects/temp/psalm-crash-reproducer/vendor/vimeo/psalm/src/Psalm/Internal/Provider/ClassLikeStorageProvider.php:45
Stack trace:
#0 /home/tjv/php-projects/temp/psalm-crash-reproducer/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/ClassLikes.php(548): Psalm\Internal\Provider\ClassLikeStorageProvider->get('symfony\\compone...')
#1 /home/tjv/php-projects/temp/psalm-crash-reproducer/vendor/vimeo/psalm/src/Psalm/Codebase.php(723): Psalm\Internal\Codebase\ClassLikes->classExtends('symfony\\compone...', 'symfony\\compone...')
#2 /home/tjv/php-projects/temp/psalm-crash-reproducer/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/TypeAnalyzer.php(704): Psalm\Codebase->classExtendsOrImplements('symfony\\compone...', 'symfony\\compone...')
#3 /home/tjv/php-projects/temp/psalm-crash-reproducer/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/TypeAnalyzer.php(903): Psalm\Internal\Analyzer\TypeAnalyzer::isObjectContainedByObject(Object(Psalm\Codebase), Object(Psalm\Type\Atomic\TNamedObject), Object(Psalm\Type\Atomic\TNamedObject), false, Object(Psalm\Internal\Analyzer\TypeComparisonResult))
#4 /home/tjv/php-projects/temp/psalm-crash-reproducer/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/TypeAnalyzer.php(147): Psalm\Internal\Analyzer\TypeAnalyzer::isAtomicContainedBy(Object(Psalm\Codebase), Object(Psalm\Type\Atomic\TNamedObject), Object(Psalm\Type\Atomic\TNamedObject), false, true, Object(Psalm\Internal\Analyzer\TypeComparisonResult))
#5 /home/tjv/php-projects/temp/psalm-crash-reproducer/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/Statements/Expression/Assignment/PropertyAssignmentAnalyzer.php(855): Psalm\Internal\Analyzer\TypeAnalyzer::isContainedBy(Object(Psalm\Codebase), Object(Psalm\Type\Union), Object(Psalm\Type\Union), true, true, Object(Psalm\Internal\Analyzer\TypeComparisonResult))
#6 /home/tjv/php-projects/temp/psalm-crash-reproducer/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/Statements/Expression/AssignmentAnalyzer.php(730): Psalm\Internal\Analyzer\Statements\Expression\Assignment\PropertyAssignmentAnalyzer::analyzeInstance(Object(Psalm\Internal\Analyzer\StatementsAnalyzer), Object(PhpParser\Node\Expr\PropertyFetch), 'validator', Object(PhpParser\Node\Expr\MethodCall), Object(Psalm\Type\Union), Object(Psalm\Context))
#7 /home/tjv/php-projects/temp/psalm-crash-reproducer/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/Statements/ExpressionAnalyzer.php(120): Psalm\Internal\Analyzer\Statements\Expression\AssignmentAnalyzer::analyze(Object(Psalm\Internal\Analyzer\StatementsAnalyzer), Object(PhpParser\Node\Expr\PropertyFetch), Object(PhpParser\Node\Expr\MethodCall), Object(Psalm\Type\Union), Object(Psalm\Context), NULL)
#8 /home/tjv/php-projects/temp/psalm-crash-reproducer/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/StatementsAnalyzer.php(736): Psalm\Internal\Analyzer\Statements\ExpressionAnalyzer::analyze(Object(Psalm\Internal\Analyzer\StatementsAnalyzer), Object(PhpParser\Node\Expr\Assign), Object(Psalm\Context), false, Object(Psalm\Context), true)
#9 /home/tjv/php-projects/temp/psalm-crash-reproducer/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/FunctionLikeAnalyzer.php(541): Psalm\Internal\Analyzer\StatementsAnalyzer->analyze(Array, Object(Psalm\Context), Object(Psalm\Context), true)
#10 /home/tjv/php-projects/temp/psalm-crash-reproducer/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/ClassAnalyzer.php(1750): Psalm\Internal\Analyzer\FunctionLikeAnalyzer->analyze(Object(Psalm\Context), Object(Psalm\Internal\Provider\NodeDataProvider), Object(Psalm\Context))
#11 /home/tjv/php-projects/temp/psalm-crash-reproducer/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/ClassAnalyzer.php(730): Psalm\Internal\Analyzer\ClassAnalyzer->analyzeClassMethod(Object(PhpParser\Node\Stmt\ClassMethod), Object(Psalm\Storage\ClassLikeStorage), Object(Psalm\Internal\Analyzer\ClassAnalyzer), Object(Psalm\Context), Object(Psalm\Context))
#12 /home/tjv/php-projects/temp/psalm-crash-reproducer/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/FileAnalyzer.php(201): Psalm\Internal\Analyzer\ClassAnalyzer->analyze(Object(Psalm\Context), Object(Psalm\Context))
#13 /home/tjv/php-projects/temp/psalm-crash-reproducer/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Analyzer.php(357): Psalm\Internal\Analyzer\FileAnalyzer->analyze(NULL)
#14 /home/tjv/php-projects/temp/psalm-crash-reproducer/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Analyzer.php(589): Psalm\Internal\Codebase\Analyzer->Psalm\Internal\Codebase\{closure}(0, '/home/tjv/php-p...')
#15 /home/tjv/php-projects/temp/psalm-crash-reproducer/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Analyzer.php(267): Psalm\Internal\Codebase\Analyzer->doAnalysis(Object(Psalm\Internal\Analyzer\ProjectAnalyzer), 3)
#16 /home/tjv/php-projects/temp/psalm-crash-reproducer/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/ProjectAnalyzer.php(568): Psalm\Internal\Codebase\Analyzer->analyzeFiles(Object(Psalm\Internal\Analyzer\ProjectAnalyzer), 3, false, true)
#17 /home/tjv/php-projects/temp/psalm-crash-reproducer/vendor/vimeo/psalm/src/psalm.php(588): Psalm\Internal\Analyzer\ProjectAnalyzer->check('/home/tjv/php-p...', false)
#18 /home/tjv/php-projects/temp/psalm-crash-reproducer/vendor/vimeo/psalm/psalm(2): require_once('/home/tjv/php-p...')
#19 {main}
(Psalm 3.11.2@d470903722cfcbc1cd04744c5491d3e6d13ec3d9 crashed due to an uncaught Throwable)
```

**Comment by muglug** [comment]
Oh ok, this is more accurately a bug with the Symfony Psalm plugin, going to close and reopen there. If you disable the plugin this issue should disappear.
