### ISSUE TITLE
Internal Psalm error: Intersection types

### ISSUE THREAD

**Issue by M1ke** [vimeo/psalm#3340]
*Version:* Psalm 3.11.2@d470903722cfcbc1cd04744c5491d3e6d13ec3d9

Please see the [demo project here](https://github.com/m1ke/psalm-ftp-bug) for a working demo of this issue.

Alternatively the contents of [this file](https://github.com/dg/ftp-php/blob/master/src/Ftp.php) can be pasted into the psalm.dev home page to show the error.

In short: trying to analyse a project containing the dependency `dg/ftp` throws the following internal error, even in the case where `vendor/` is ignored in `psalm.xml`.

```
Uncaught Psalm\Exception\TypeParseTreeException: Intersection types must be all objects or all object-like arrays, Psalm\Type\Atomic\TString provided in ~/psalm-ftp-bug/vendor/vimeo/psalm/src/Psalm/Type.php:586
Stack trace:
#0 ~/psalm-ftp-bug/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/CommentAnalyzer.php(1041): Psalm\Type::getTypeFromTree(Object(Psalm\Internal\Type\ParseTree\IntersectionTree), Object(Psalm\Codebase))
#1 ~/psalm-ftp-bug/vendor/vimeo/psalm/src/Psalm/Internal/PhpVisitor/ReflectorVisitor.php(1105): Psalm\Internal\Analyzer\CommentAnalyzer::extractClassLikeDocblockInfo(Object(PhpParser\Node\Stmt\Class_), Object(PhpParser\Comment\Doc), Object(Psalm\Aliases))
#2 ~/psalm-ftp-bug/vendor/vimeo/psalm/src/Psalm/Internal/PhpVisitor/ReflectorVisitor.php(272): Psalm\Internal\PhpVisitor\ReflectorVisitor->registerClassLike(Object(PhpParser\Node\Stmt\Class_))
#3 ~/psalm-ftp-bug/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(200): Psalm\Internal\PhpVisitor\ReflectorVisitor->enterNode(Object(PhpParser\Node\Stmt\Class_))
#4 ~/psalm-ftp-bug/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(91): PhpParser\NodeTraverser->traverseArray(Array)
#5 ~/psalm-ftp-bug/vendor/vimeo/psalm/src/Psalm/Internal/Scanner/FileScanner.php(94): PhpParser\NodeTraverser->traverse(Array)
#6 ~/psalm-ftp-bug/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Scanner.php(586): Psalm\Internal\Scanner\FileScanner->scan(Object(Psalm\Codebase), Object(Psalm\Storage\FileStorage), false, Object(Psalm\Progress\DefaultProgress))
#7 ~/psalm-ftp-bug/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Scanner.php(367): Psalm\Internal\Codebase\Scanner->scanFile('~/psalm-ftp-bug/...', Array, false)
#8 ~/psalm-ftp-bug/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Scanner.php(475): Psalm\Internal\Codebase\Scanner->Psalm\Internal\Codebase\{closure}(0, '~/psalm-ftp-bug/...')
#9 ~/psalm-ftp-bug/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Scanner.php(325): Psalm\Internal\Codebase\Scanner->scanFilePaths(1)
#10 ~/psalm-ftp-bug/vendor/vimeo/psalm/src/Psalm/Codebase.php(477): Psalm\Internal\Codebase\Scanner->scanFiles(Object(Psalm\Internal\Codebase\ClassLikes), 3)
#11 ~/psalm-ftp-bug/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/ProjectAnalyzer.php(519): Psalm\Codebase->scanFiles(3)
#12 ~/psalm-ftp-bug/vendor/vimeo/psalm/src/psalm.php(588): Psalm\Internal\Analyzer\ProjectAnalyzer->check('~/psalm-ftp-bug/...', false)
#13 ~/psalm-ftp-bug/vendor/vimeo/psalm/psalm(2): require_once('~/psalm-ftp-bug/...')
#14 {main}
(Psalm 3.11.2@d470903722cfcbc1cd04744c5491d3e6d13ec3d9 crashed due to an uncaught Throwable)
```

If it's in scope I'd be happy to look into a fix for this; I presume that whether or not users have dependencies with any odd formatting of types, Psalm shouldn't hard error, as bringing it into a large existing codebase it's unfeasible to ensure all dependencies conform to a specification. So I'd guess that's not the intention here and we've just stumbled across possibly a legitimate bug.

**Comment by M1ke** [comment]
I should have dug slightly more; it's this line in the docblock that breaks Psalm:

```
@method void alloc(int $filesize, string & $result) - Allocates space for a file to be uploaded
```

Note `string & $result` which doesn't seem valid annotation syntax.

**Comment by muglug** [comment]
> So depending on complexity of the parser it might be a simple fix?

It's just a matter of catching the exception and providing a sane error message – feel free to PR, and thanks for digging

**Comment by M1ke** [comment]
@muglug PR now open but there's a fail in CI which I think could be unrelated but don't know enough to say for sure
