### ISSUE TITLE
PackageVersions breaks installation when composer.lock is missing

### ISSUE THREAD

**Issue by weirdan** [vimeo/psalm#338]
I'm not sure where I have to report this, but since issues are not enabled on `muglug/PackageVersions` (you can enable that in the repository settings), and `vimeo/psalm` is likely the only package that uses that fork I figured I would do it here.

When I'm trying to do `composer install -v` in a directory missing `composer.lock` (`composer.json` is there), I get the following exception:
```

  [LogicException]
  No lockfile found. Unable to read locked packages


Exception trace:
 () at /home/weirdan/.composer/vendor/composer/composer/src/Composer/Package/Locker.php:266
 Composer\Package\Locker->getLockData() at /home/weirdan/.composer/vendor/muglug/package-versions/src/PackageVersions/Installer.php:188
 PackageVersions\Installer::getVersions() at n/a:n/a
 iterator_to_array() at /home/weirdan/.composer/vendor/muglug/package-versions/src/PackageVersions/Installer.php:102
 PackageVersions\Installer::dumpVersionsClass() at n/a:n/a
 call_user_func() at /home/weirdan/.composer/vendor/composer/composer/src/Composer/EventDispatcher/EventDispatcher.php:171
 Composer\EventDispatcher\EventDispatcher->doDispatch() at /home/weirdan/.composer/vendor/composer/composer/src/Composer/EventDispatcher/EventDispatcher.php:96
 Composer\EventDispatcher\EventDispatcher->dispatchScript() at /home/weirdan/.composer/vendor/composer/composer/src/Composer/Installer.php:307
 Composer\Installer->run() at /home/weirdan/.composer/vendor/composer/composer/src/Composer/Command/InstallCommand.php:119
 Composer\Command\InstallCommand->execute() at /home/weirdan/.composer/vendor/symfony/console/Command/Command.php:240
 Symfony\Component\Console\Command\Command->run() at /home/weirdan/.composer/vendor/symfony/console/Application.php:858
 Symfony\Component\Console\Application->doRunCommand() at /home/weirdan/.composer/vendor/symfony/console/Application.php:216
 Symfony\Component\Console\Application->doRun() at /home/weirdan/.composer/vendor/composer/composer/src/Composer/Console/Application.php:245
 Composer\Console\Application->doRun() at /home/weirdan/.composer/vendor/symfony/console/Application.php:122
 Symfony\Component\Console\Application->run() at /home/weirdan/.composer/vendor/composer/composer/src/Composer/Console/Application.php:100
 Composer\Console\Application->run() at /home/weirdan/.composer/vendor/composer/composer/bin/composer:55
```

**Comment by weirdan** [comment]
No, I can't reproduce it anymore. Looking at the stack trace it looks like globally installed package-version has been triggered for local (project-wise) install.

**Comment by voku** [comment]
Same problem with the "phar" (version 3.0.17) file.

**no problem:**
cd ~
php7.2 ~/Downloads/psalm.phar ~/PROJECT_DIR

**problem:**
cd ~/PROJECT_DIR
php7.2 ~/Downloads/psalm.phar

```
PHP Fatal error:  Uncaught Error: Class '_HumbugBox80cedda9eb6a\Muglug\PackageVersions\Versions' not found in phar:///home/lmoelleken/Downloads/psalm.phar/src/command_functions.php:54
Stack trace:
#0 phar:///home/lmoelleken/Downloads/psalm.phar/src/psalm.php(171): _HumbugBox80cedda9eb6a\requireAutoloaders('/home/lmoelleke...', false, 'Framework/third...')
#1 phar:///home/lmoelleken/Downloads/psalm.phar/psalm(5): require_once('phar:///home/lm...')
#2 /home/lmoelleken/Downloads/psalm.phar(14): require('phar:///home/lm...')
#3 {main}
  thrown in phar:///home/lmoelleken/Downloads/psalm.phar/src/command_functions.php on line 54

Fatal error: Uncaught Error: Class '_HumbugBox80cedda9eb6a\Muglug\PackageVersions\Versions' not found in phar:///home/lmoelleken/Downloads/psalm.phar/src/command_functions.php:54
Stack trace:
#0 phar:///home/lmoelleken/Downloads/psalm.phar/src/psalm.php(171): _HumbugBox80cedda9eb6a\requireAutoloaders('/home/lmoelleke...', false, 'Framework/third...')
#1 phar:///home/lmoelleken/Downloads/psalm.phar/psalm(5): require_once('phar:///home/lm...')
#2 /home/lmoelleken/Downloads/psalm.phar(14): require('phar:///home/lm...')
#3 {main}
  thrown in phar:///home/lmoelleken/Downloads/psalm.phar/src/command_functions.php on line 54
```
