### ISSUE TITLE
Crash with a class named Event

### ISSUE THREAD

**Issue by weirdan** [vimeo/psalm#339]
```php
<?php
class Event {}
class AClass
{
    public function get(): Event
    {
        return new Event;
    }
}
```
Crashes Psalm with the following exception trace:
```
PHP Fatal error:  Uncaught UnexpectedValueException: Cannot get method params for  in /home/weirdan/.composer/vendor/vimeo/psalm/src/Psalm/Checker/MethodChecker.php:45
Stack trace:
#0 /home/weirdan/.composer/vendor/vimeo/psalm/src/Psalm/Checker/FunctionLikeChecker.php(1300): Psalm\Checker\MethodChecker::getMethodParams(Object(Psalm\Checker\ProjectChecker), NULL)
#1 /home/weirdan/.composer/vendor/vimeo/psalm/src/Psalm/Checker/Statements/Expression/CallChecker.php(1522): Psalm\Checker\FunctionLikeChecker::getMethodParamsById(Object(Psalm\Checker\ProjectChecker), 'Event::__constr...', Array)
#2 /home/weirdan/.composer/vendor/vimeo/psalm/src/Psalm/Checker/Statements/Expression/CallChecker.php(557): Psalm\Checker\Statements\Expression\CallChecker::checkMethodArgs('Event::__constr...', Array, NULL, Object(Psalm\Context), Object(Psalm\CodeLocation), Object(Psalm\Checker\StatementsChecker))
#3 /home/weirdan/.composer/vendor/vimeo/psalm/src/Psalm/Checker/Statements/ExpressionChecker.php(186): Psalm\Checker\Statements\Expression\CallChe in /home/weirdan/.composer/vendor/vimeo/psalm/src/Psalm/Checker/MethodChecker.php on line 45
```
If I rename `Event` to something else the crash is gone.

**Comment by muglug** [comment]
Ah, I think the problem is a class with http://php.net/manual/en/class.event.php

I'll add a workaround

**Comment by weirdan** [comment]
Maybe Psalm could check what extensions are loaded (or depended upon in `composer.json`)?

Apparently it only concerns global namespace, so it's less problematic than I thought.

**Comment by muglug** [comment]
Was slow to add the workaround, but should be good now.
