### ISSUE TITLE
Uncaught Psalm\Exception\TypeParseTreeException: Unexpected token

### ISSUE THREAD

**Issue by gemal** [vimeo/psalm#3430]
I just installed psalm and did a psalm --init and crash:

```
Uncaught Psalm\Exception\TypeParseTreeException: Unexpected token . in x\app\Vendor\vimeo\psalm\src\Psalm\Type.php:1225
Stack trace:
#0 x\app\Vendor\vimeo\psalm\src\Psalm\Type.php(1268): Psalm\Type::tokenize('Facebook.Facebo...')
#1 x\app\Vendor\vimeo\psalm\src\Psalm\Internal\PhpVisitor\ReflectorVisitor.php(1204): Psalm\Type::fixUpLocalType('Facebook.Facebo...', Object(Psalm\Aliases), NULL, Array)
#2 x\app\Vendor\vimeo\psalm\src\Psalm\Internal\PhpVisitor\ReflectorVisitor.php(269): Psalm\Internal\PhpVisitor\ReflectorVisitor->registerClassLike(Object(PhpParser\Node\Stmt\Class_))
#3 x\app\Vendor\nikic\php-parser\lib\PhpParser\NodeTraverser.php(200): Psalm\Internal\PhpVisitor\ReflectorVisitor->enterNode(Object(PhpParser\Node\Stmt\Class_))
#4 x\app\Vendor\nikic\php-parser\lib\PhpParser\NodeTraverser.php(91): PhpParser\NodeTraverser->traverseArray(Array)
#5 x\app\Vendor\vimeo\psalm\src\Psalm\Internal\Scanner\FileScanner.php(94): PhpParser\NodeTraverser->traverse(Array)
#6 x\app\Vendor\vimeo\psalm\src\Psalm\Internal\Codebase\Scanner.php(586): Psalm\Internal\Scanner\FileScanner->scan(Object(Psalm\Codebase), Object(Psalm\Storage\FileStorage), false, Object(Psalm\Progress\DefaultProgress))
#7 x\app\Vendor\vimeo\psalm\src\Psalm\Internal\Codebase\Scanner.php(367): Psalm\Internal\Codebase\Scanner->scanFile('x\\...', Array, true)
#8 x\app\Vendor\vimeo\psalm\src\Psalm\Internal\Codebase\Scanner.php(475): Psalm\Internal\Codebase\Scanner->Psalm\Internal\Codebase\{closure}(1240, 'x\\...')
#9 x\app\Vendor\vimeo\psalm\src\Psalm\Internal\Codebase\Scanner.php(325): Psalm\Internal\Codebase\Scanner->scanFilePaths(1)
#10 x\app\Vendor\vimeo\psalm\src\Psalm\Codebase.php(477): Psalm\Internal\Codebase\Scanner->scanFiles(Object(Psalm\Internal\Codebase\ClassLikes), 1)
#11 x\app\Vendor\vimeo\psalm\src\Psalm\Internal\Analyzer\ProjectAnalyzer.php(533): Psalm\Codebase->scanFiles(1)
#12 x\app\Vendor\vimeo\psalm\src\psalm.php(588): Psalm\Internal\Analyzer\ProjectAnalyzer->check('x\\...', false)
#13 x\app\Vendor\vimeo\psalm\psalm(2): require_once('x\\...')
#14 {main}
(Psalm 3.11.4@58e1d8e68e5098bf4fbfdfb420c38d563f882549 crashed due to an uncaught Throwable)

```

**Comment by gemal** [comment]
https://psalm.dev/r/7891af1e2b

**Comment by muglug** [comment]
Ah thanks, it’s the . `Facebook.Facebook`
