### ISSUE TITLE
Error while initializing in Laravel Projects

### ISSUE THREAD

**Issue by kinnngg** [vimeo/psalm#3449]
I am getting this while running below command in Laravel projects.
`./vendor/bin/psalm --init`

```
Uncaught InvalidArgumentException: Could not get class storage for eloquent in E:\laragon\www\app\vendor\vimeo\psalm\src\Psalm\Internal\Provider\ClassLikeStoragePro
vider.php:45
```

Did anyone get any idea how to fix it?

**Comment by weirdan** [comment]
@kinnngg try running with `--debug` and `--debug-by-line` to see if there could be some hints there
@mr-feek, can you lend a hand here?

**Comment by mr-feek** [comment]
Hey @kinnngg , would you mind opening an issue over at https://github.com/psalm/psalm-plugin-laravel please?

I'll need to know what version of the plugin you are using  (if at all!). I made some changes in dev-master last night regarding the `\Eloquent` class generated by ide-helper.

I'm 🤞 that you aren't using the plugin, as then this issue would make sense. Otherwise I'm happy to help debug!

**Comment by kinnngg** [comment]
> Hey @kinnngg , would you mind opening an issue over at https://github.com/psalm/psalm-plugin-laravel please?
> 
> I'll need to know what version of the plugin you are using (if at all!). I made some changes in dev-master last night regarding the `\Eloquent` class generated by ide-helper.
> 
> I'm 🤞 that you aren't using the plugin, as then this issue would make sense. Otherwise I'm happy to help debug!

Yes I haven't run composer install for laravel-plugin as in documentation it asks to run `./vendor/bin/psalm --init` first.

**Comment by kinnngg** [comment]
> @kinnngg try running with `--debug` and `--debug-by-line` to see if there could be some hints there
> @mr-feek, can you lend a hand here?

Yes I ran with it and debug showing it throws that error where ever a Model is referenced.

Eg:
```
return new PresenceChannel('chatroom.'.$this->chatMessage->chatroom_id);
```

**Comment by mr-feek** [comment]
Do you have `@mixin \Eloquent` in your model classes? (they would be added by laravel-ide-helper)

**Comment by kinnngg** [comment]
> Do you have `@mixin \Eloquent` in your model classes? (they would be added by laravel-ide-helper)

Yes it seems some of my Models have those. Let me give a try removing them.

**Comment by mr-feek** [comment]
It seems there may be something psalm can fix here to give a better error message.

@kinnngg could you provide the entire stacktrace please?

**Comment by kinnngg** [comment]
> Do you have `@mixin \Eloquent` in your model classes? (they would be added by laravel-ide-helper)

@mr-feek Removing those mixins from all models fixed that error. I removed mixin from my models and generated separate ide_models.php file for them. 

Do you still want the stack trace? I will have to add those mixing again 😄

**Comment by kinnngg** [comment]
Here you go.
```php
Uncaught InvalidArgumentException: Could not get class storage for eloquent in E:\laragon\www\quizapp\vendor\vimeo\psalm\src\Psalm\Internal\Provider\ClassLikeStoragePro
vider.php:45
Stack trace:
#0 E:\laragon\www\quizapp\vendor\vimeo\psalm\src\Psalm\Internal\Analyzer\Statements\Expression\Fetch\PropertyFetchAnalyzer.php(509): Psalm\Internal\Provider\ClassLikeSt
orageProvider->get('Eloquent')
#1 E:\laragon\www\quizapp\vendor\vimeo\psalm\src\Psalm\Internal\Analyzer\Statements\ExpressionAnalyzer.php(256): Psalm\Internal\Analyzer\Statements\Expression\Fetch\Pro
pertyFetchAnalyzer::analyzeInstance(Object(Psalm\Internal\Analyzer\StatementsAnalyzer), Object(PhpParser\Node\Expr\PropertyFetch), Object(Psalm\Context))
#2 E:\laragon\www\quizapp\vendor\vimeo\psalm\src\Psalm\Internal\Analyzer\Statements\ExpressionAnalyzer.php(610): Psalm\Internal\Analyzer\Statements\ExpressionAnalyzer::
analyze(Object(Psalm\Internal\Analyzer\StatementsAnalyzer), Object(PhpParser\Node\Expr\PropertyFetch), Object(Psalm\Context))
#3 E:\laragon\www\quizapp\vendor\vimeo\psalm\src\Psalm\Internal\Analyzer\Statements\Expression\CallAnalyzer.php(582): Psalm\Internal\Analyzer\Statements\ExpressionAnaly
zer::analyze(Object(Psalm\Internal\Analyzer\StatementsAnalyzer), Object(PhpParser\Node\Expr\Cast\String_), Object(Psalm\Context))
#4 E:\laragon\www\quizapp\vendor\vimeo\psalm\src\Psalm\Internal\Analyzer\Statements\Expression\Call\FunctionCallAnalyzer.php(294): Psalm\Internal\Analyzer\Statements\Ex
pression\CallAnalyzer::checkFunctionArguments(Object(Psalm\Internal\Analyzer\StatementsAnalyzer), Array, Array, 'strpos', Object(Psalm\Context))
#5 E:\laragon\www\quizapp\vendor\vimeo\psalm\src\Psalm\Internal\Analyzer\Statements\ExpressionAnalyzer.php(442): Psalm\Internal\Analyzer\Statements\Expression\Call\Func
tionCallAnalyzer::analyze(Object(Psalm\Internal\Analyzer\StatementsAnalyzer), Object(PhpParser\Node\Expr\FuncCall), Object(Psalm\Context))
#6 E:\laragon\www\quizapp\vendor\vimeo\psalm\src\Psalm\Internal\Analyzer\Statements\Expression\AssignmentAnalyzer.php(245): Psalm\Internal\Analyzer\Statements\Expressio
nAnalyzer::analyze(Object(Psalm\Internal\Analyzer\StatementsAnalyzer), Object(PhpParser\Node\Expr\FuncCall), Object(Psalm\Context))
#7 E:\laragon\www\quizapp\vendor\vimeo\psalm\src\Psalm\Internal\Analyzer\Statements\ExpressionAnalyzer.php(120): Psalm\Internal\Analyzer\Statements\Expression\Assignmen
tAnalyzer::analyze(Object(Psalm\Internal\Analyzer\StatementsAnalyzer), Object(PhpParser\Node\Expr\Variable), Object(PhpParser\Node\Expr\FuncCall), NULL, Object(Psalm\Co
ntext), NULL)
#8 E:\laragon\www\quizapp\vendor\vimeo\psalm\src\Psalm\Internal\Analyzer\StatementsAnalyzer.php(751): Psalm\Internal\Analyzer\Statements\ExpressionAnalyzer::analyze(Obj
ect(Psalm\Internal\Analyzer\StatementsAnalyzer), Object(PhpParser\Node\Expr\Assign), Object(Psalm\Context), false, NULL, true)
#9 E:\laragon\www\quizapp\vendor\vimeo\psalm\src\Psalm\Internal\Analyzer\Statements\Block\IfAnalyzer.php(1609): Psalm\Internal\Analyzer\StatementsAnalyzer->analyze(Arra
y, Object(Psalm\Context))
#10 E:\laragon\www\quizapp\vendor\vimeo\psalm\src\Psalm\Internal\Analyzer\Statements\Block\IfAnalyzer.php(385): Psalm\Internal\Analyzer\Statements\Block\IfAnalyzer::ana
lyzeElseBlock(Object(Psalm\Internal\Analyzer\StatementsAnalyzer), Object(PhpParser\Node\Stmt\Else_), Object(Psalm\Internal\Scope\IfScope), Object(Psalm\Context), Object
(Psalm\Context))
#11 E:\laragon\www\quizapp\vendor\vimeo\psalm\src\Psalm\Internal\Analyzer\StatementsAnalyzer.php(382): Psalm\Internal\Analyzer\Statements\Block\IfAnalyzer::analyze(Obje
ct(Psalm\Internal\Analyzer\StatementsAnalyzer), Object(PhpParser\Node\Stmt\If_), Object(Psalm\Context))
#12 E:\laragon\www\quizapp\vendor\vimeo\psalm\src\Psalm\Internal\Analyzer\FunctionLikeAnalyzer.php(541): Psalm\Internal\Analyzer\StatementsAnalyzer->analyze(Array, Obje
ct(Psalm\Context), Object(Psalm\Context), true)
#13 E:\laragon\www\quizapp\vendor\vimeo\psalm\src\Psalm\Internal\Analyzer\ClassAnalyzer.php(1767): Psalm\Internal\Analyzer\FunctionLikeAnalyzer->analyze(Object(Psalm\Co
ntext), Object(Psalm\Internal\Provider\NodeDataProvider), Object(Psalm\Context))
#14 E:\laragon\www\quizapp\vendor\vimeo\psalm\src\Psalm\Internal\Analyzer\ClassAnalyzer.php(727): Psalm\Internal\Analyzer\ClassAnalyzer->analyzeClassMethod(Object(PhpPa
rser\Node\Stmt\ClassMethod), Object(Psalm\Storage\ClassLikeStorage), Object(Psalm\Internal\Analyzer\ClassAnalyzer), Object(Psalm\Context), Object(Psalm\Context))
#15 E:\laragon\www\quizapp\vendor\vimeo\psalm\src\Psalm\Internal\Analyzer\FileAnalyzer.php(201): Psalm\Internal\Analyzer\ClassAnalyzer->analyze(Object(Psalm\Context), O
bject(Psalm\Context))
#16 E:\laragon\www\quizapp\vendor\vimeo\psalm\src\Psalm\Internal\Codebase\Analyzer.php(357): Psalm\Internal\Analyzer\FileAnalyzer->analyze(NULL)
#17 E:\laragon\www\quizapp\vendor\vimeo\psalm\src\Psalm\Internal\Codebase\Analyzer.php(589): Psalm\Internal\Codebase\Analyzer->Psalm\Internal\Codebase\{closure}(0, 'E:\
\laragon\\www\\...')
#18 E:\laragon\www\quizapp\vendor\vimeo\psalm\src\Psalm\Internal\Codebase\Analyzer.php(267): Psalm\Internal\Codebase\Analyzer->doAnalysis(Object(Psalm\Internal\Analyzer
\ProjectAnalyzer), 1)
#19 E:\laragon\www\quizapp\vendor\vimeo\psalm\src\Psalm\Internal\Analyzer\ProjectAnalyzer.php(582): Psalm\Internal\Codebase\Analyzer->analyzeFiles(Object(Psalm\Internal
\Analyzer\ProjectAnalyzer), 1, false, true)
#20 E:\laragon\www\quizapp\vendor\vimeo\psalm\src\psalm.php(588): Psalm\Internal\Analyzer\ProjectAnalyzer->check('E:\\laragon\\www\\...', false)
#21 E:\laragon\www\quizapp\vendor\vimeo\psalm\psalm(2): require_once('E:\\laragon\\www\\...')
#22 {main}
(Psalm 3.11.4@58e1d8e68e5098bf4fbfdfb420c38d563f882549 crashed due to an uncaught Throwable)
```

**Comment by mr-feek** [comment]
I'm still working on figuring out the best way to work with  `\Eloquent` in the laravel psalm plugin. It's a  fake class that ide-helper generates to help out phpstorm. Psalm can actually do a better job than that class, so I recommend removing `\Eloquent` references and instead use the LSP phpstorm plugin.

Regardless, I think we can fix this error message in psalm, ill take a look

**Comment by mr-feek** [comment]
@kinnngg any chance your code is open source and available for me to play with to reproduce the problem?

**Comment by kinnngg** [comment]
> @kinnngg any chance your code is open source and available for me to play with to reproduce the problem?

@mr-feek That project is not opensource but I have create a sample repo that will give you the same error when running `./vendor/bin/psalm --init`
I hope this will help. 
https://github.com/kinnngg/psalm-eloquent-issue-reproducer

I will be able to add some models of the project if needed. 👍

**Comment by mr-feek** [comment]
thank you @kinnngg ! Let's close this issue out as you are unblocked, and I believe we can track the psalm fix here https://github.com/vimeo/psalm/issues/3452
