### ISSUE TITLE
Psalm crash

### ISSUE THREAD

**Issue by enumag** [vimeo/psalm#3510]
The latest version is causing a crash for me. I updated to dev-master but the bug is there as well. I'm posting the stack trace below. Is it enough for you to fix it?

```
vendor/bin/psalm
Scanning files...
Analyzing files...

Uncaught Exception: Misplaced brackets░░░░░░░░░░░░░░░░░░░░░░   453 / 1960 (23%)
Stack trace in the forked worker:
#0 /vendor/vimeo/psalm/src/Psalm/Internal/Type/TypeParser.php(92): Psalm\Internal\Type\TypeParser::getTypeFromTree(Object(Psalm\Internal\Type\ParseTree\MethodTree), Object(Psalm\Codebase), NULL, Array, Array)
#1 /vendor/vimeo/psalm/src/Psalm/Type.php(67): Psalm\Internal\Type\TypeParser::parseTokens(Array, NULL, Array)
#2 /vendor/vimeo/psalm/src/Psalm/Internal/Type/SimpleAssertionReconciler.php(357): Psalm\Type::parseString('string(deposit)')
#3 /vendor/vimeo/psalm/src/Psalm/Internal/Type/AssertionReconciler.php(143): Psalm\Internal\Type\SimpleAssertionReconciler::reconcile('string(deposit)', Object(Psalm\Codebase), Object(Psalm\Type\Union), '$feeType->getva...', NULL, Array, 0, true, true, true)
#4 /vendor/vimeo/psalm/src/Psalm/Type/Reconciler.php(269): Psalm\Internal\Type\AssertionReconciler::reconcile('string(deposit)', Object(Psalm\Type\Union), '$feeType->getva...', Object(Psalm\Internal\Analyzer\StatementsAnalyzer), true, Array, NULL, Array, 0)
#5 /vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/Statements/Expression/BinaryOp/AndAnalyzer.php(134): Psalm\Type\Reconciler::reconcileKeyedTypes(Array, Array, Array, Array, Array, Object(Psalm\Internal\Analyzer\StatementsAnalyzer), Array, true, Object(Psalm\CodeLocation))
#6 /vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/Statements/Expression/BinaryOpAnalyzer.php(38): Psalm\Internal\Analyzer\Statements\Expression\BinaryOp\AndAnalyzer::analyze(Object(Psalm\Internal\Analyzer\StatementsAnalyzer), Object(PhpParser\Node\Expr\BinaryOp\BooleanAnd), Object(Psalm\Context), false)
#7 /vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/Statements/ExpressionAnalyzer.php(226): Psalm\Internal\Analyzer\Statements\Expression\BinaryOpAnalyzer::analyze(Object(Psalm\Internal\Analyzer\StatementsAnalyzer), Object(PhpParser\Node\Expr\BinaryOp\BooleanAnd), Object(Psalm\Context), 0, false)
#8 /vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/Statements/ExpressionAnalyzer.php(45): Psalm\Internal\Analyzer\Statements\ExpressionAnalyzer::handleExpression(Object(Psalm\Internal\Analyzer\StatementsAnalyzer), Object(PhpParser\Node\Expr\BinaryOp\BooleanAnd), Object(Psalm\Context), false, NULL, false)
#9 /vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/Statements/Block/IfAnalyzer.php(649): Psalm\Internal\Analyzer\Statements\ExpressionAnalyzer::analyze(Object(Psalm\Internal\Analyzer\StatementsAnalyzer), Object(PhpParser\Node\Expr\BinaryOp\BooleanAnd), Object(Psalm\Context))
#10 /vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/Statements/Block/IfAnalyzer.php(90): Psalm\Internal\Analyzer\Statements\Block\IfAnalyzer::analyzeIfConditional(Object(Psalm\Internal\Analyzer\StatementsAnalyzer), Object(PhpParser\Node\Expr\BinaryOp\BooleanAnd), Object(Psalm\Context), Object(Psalm\Codebase), Object(Psalm\Internal\Scope\IfScope), 29201)
#11 /vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/StatementsAnalyzer.php(387): Psalm\Internal\Analyzer\Statements\Block\IfAnalyzer::analyze(Object(Psalm\Internal\Analyzer\StatementsAnalyzer), Object(PhpParser\Node\Stmt\If_), Object(Psalm\Context))
#12 /vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/StatementsAnalyzer.php(163): Psalm\Internal\Analyzer\StatementsAnalyzer::analyzeStatement(Object(Psalm\Internal\Analyzer\StatementsAnalyzer), Object(PhpParser\Node\Stmt\If_), Object(Psalm\Context), NULL)
#13 /vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/Statements/Block/LoopAnalyzer.php(195): Psalm\Internal\Analyzer\StatementsAnalyzer->analyze(Array, Object(Psalm\Context))
#14 /vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/Statements/Block/ForeachAnalyzer.php(307): Psalm\Internal\Analyzer\Statements\Block\LoopAnalyzer::analyze(Object(Psalm\Internal\Analyzer\StatementsAnalyzer), Array, Array, Array, Object(Psalm\Internal\Scope\LoopScope), Object(Psalm\Context))
#15 /vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/StatementsAnalyzer.php(399): Psalm\Internal\Analyzer\Statements\Block\ForeachAnalyzer::analyze(Object(Psalm\Internal\Analyzer\StatementsAnalyzer), Object(PhpParser\Node\Stmt\Foreach_), Object(Psalm\Context))
#16 /vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/StatementsAnalyzer.php(163): Psalm\Internal\Analyzer\StatementsAnalyzer::analyzeStatement(Object(Psalm\Internal\Analyzer\StatementsAnalyzer), Object(PhpParser\Node\Stmt\Foreach_), Object(Psalm\Context), Object(Psalm\Context))
#17 /vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/FunctionLikeAnalyzer.php(541): Psalm\Internal\Analyzer\StatementsAnalyzer->analyze(Array, Object(Psalm\Context), Object(Psalm\Context), true)
#18 /vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/ClassAnalyzer.php(1780): Psalm\Internal\Analyzer\FunctionLikeAnalyzer->analyze(Object(Psalm\Context), Object(Psalm\Internal\Provider\NodeDataProvider), Object(Psalm\Context))
#19 /vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/ClassAnalyzer.php(740): Psalm\Internal\Analyzer\ClassAnalyzer->analyzeClassMethod(Object(PhpParser\Node\Stmt\ClassMethod), Object(Psalm\Storage\ClassLikeStorage), Object(Psalm\Internal\Analyzer\ClassAnalyzer), Object(Psalm\Context), Object(Psalm\Context))
#20 /vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/FileAnalyzer.php(201): Psalm\Internal\Analyzer\ClassAnalyzer->analyze(Object(Psalm\Context), Object(Psalm\Context))
#21 /vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Analyzer.php(340): Psalm\Internal\Analyzer\FileAnalyzer->analyze(NULL)
#22 /vendor/vimeo/psalm/src/Psalm/Internal/Fork/Pool.php(184): Psalm\Internal\Codebase\Analyzer->Psalm\Internal\Codebase\{closure}(89, '...')
#23 /vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Analyzer.php(406): Psalm\Internal\Fork\Pool->__construct(Array, Object(Closure), Object(Closure), Object(Closure), Object(Closure))
#24 /vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Analyzer.php(266): Psalm\Internal\Codebase\Analyzer->doAnalysis(Object(Psalm\Internal\Analyzer\ProjectAnalyzer), 7)
#25 /vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/ProjectAnalyzer.php(582): Psalm\Internal\Codebase\Analyzer->analyzeFiles(Object(Psalm\Internal\Analyzer\ProjectAnalyzer), 7, false, true)
#26 /vendor/vimeo/psalm/src/psalm.php(590): Psalm\Internal\Analyzer\ProjectAnalyzer->check('...', false)
#27 /vendor/vimeo/psalm/psalm(2): require_once('...')
#28 {main} in /vendor/vimeo/psalm/src/Psalm/Internal/Fork/Pool.php:348
Stack trace:
#0 /vendor/vimeo/psalm/src/Psalm/Internal/Fork/Pool.php(380): Psalm\Internal\Fork\Pool->readResultsFromChildren()
#1 /vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Analyzer.php(471): Psalm\Internal\Fork\Pool->wait()
#2 /vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Analyzer.php(266): Psalm\Internal\Codebase\Analyzer->doAnalysis(Object(Psalm\Internal\Analyzer\ProjectAnalyzer), 7)
#3 /vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/ProjectAnalyzer.php(582): Psalm\Internal\Codebase\Analyzer->analyzeFiles(Object(Psalm\Internal\Analyzer\ProjectAnalyzer), 7, false, true)
#4 /vendor/vimeo/psalm/src/psalm.php(590): Psalm\Internal\Analyzer\ProjectAnalyzer->check('...', false)
#5 /vendor/vimeo/psalm/psalm(2): require_once('...')
#6 {main}
(Psalm dev-master@4d149de764a4980c8c20e5d7ae83de9e5cb41510 crashed due to an uncaught Throwable)
```

**Comment by orklah** [comment]
Can you launch psalm with --debug-by-line param? It should tell you what's causing the issue

**Comment by enumag** [comment]
No it does not. The process just hangs without telling me anything useful. The exception trace does not appear either (or possibly is lost somewhere in the output).

**Comment by muglug** [comment]
> No it does not. The process just hangs without telling me anything useful

> The exception trace does not appear either (or possibly is lost somewhere in the output).

It looks like it's something to do with a string called "deposit" – does that make any sense given the output?

Also you can use `--debug` first to narrow it down to the file it's failing on.

**Comment by enumag** [comment]
That did help me find the code but there is nothing wrong with it... It's just a `if ($feeType->getValue() ==== FeeType::DEPOSIT) {` - "deposit" is a value of the constant. FeeType is a subclass of https://github.com/myclabs/php-enum/blob/master/src/Enum.php.

**Comment by mr-feek** [comment]
> That did help me find the code but there is nothing wrong with it... It's just a `if ($feeType->getValue() ==== FeeType::DEPOSIT) {` - "deposit" is a value of the constant. FeeType is a subclass of https://github.com/myclabs/php-enum/blob/master/src/Enum.php.

are there 4 equals signs?

**Comment by enumag** [comment]
That's just a typo when I was writing the gthub comment. There were just 3
in the code.

**Comment by muglug** [comment]
I'll need a proper reproducer – either on psalm.dev, or in a repo.

Running with `--debug-by-line` will show you every line Psalm analyses up to the crash – if it's not working, then something is _really_ wrong.

**Comment by enumag** [comment]
@muglug I managed to reproduce it on psalm.dev: https://psalm.dev/r/eafcfe536c
