### ISSUE TITLE
psalm crashes on phpdocumentor code

### ISSUE THREAD

**Issue by jaapio** [vimeo/psalm#3537]
Crashes on phpdocumentor master branch.

```
Uncaught Psalm\Exception\TypeParseTreeException: Invalid type 'Highlight\ModeDeprecations

' in phar:///data/tools/psalm/src/Psalm/Internal/Type/TypeParser.php:500
Stack trace:
#0 phar:///data/tools/psalm/src/Psalm/Internal/Type/TypeParser.php(80): Psalm\Internal\Type\TypeParser::getTypeFromTree(Object(Psalm\Internal\Type\ParseTree\Value), Object(Psalm\Codebase), NULL, Array, Array)
#1 phar:///data/tools/psalm/src/Psalm/Internal/PhpVisitor/ReflectorVisitor.php(849): Psalm\Internal\Type\TypeParser::parseTokens(Array, NULL, Array, Array)
#2 phar:///data/tools/psalm/src/Psalm/Internal/PhpVisitor/ReflectorVisitor.php(221): Psalm\Internal\PhpVisitor\ReflectorVisitor->registerClassLike(Object(_HumbugBox3c32a251b752\PhpParser\Node\Stmt\Class_))
#3 phar:///data/tools/psalm/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(176): Psalm\Internal\PhpVisitor\ReflectorVisitor->enterNode(Object(_HumbugBox3c32a251b752\PhpParser\Node\Stmt\Class_))
#4 phar:///data/tools/psalm/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(105): _HumbugBox3c32a251b752\PhpParser\NodeTraverser->traverseArray(Array)
#5 phar:///data/tools/psalm/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(196): _HumbugBox3c32a251b752\PhpParser\NodeTraverser->traverseNode(Object(_HumbugBox3c32a251b752\PhpParser\Node\Stmt\Namespace_))
#6 phar:///data/tools/psalm/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(85): _HumbugBox3c32a251b752\PhpParser\NodeTraverser->traverseArray(Array)
#7 phar:///data/tools/psalm/src/Psalm/Internal/Scanner/FileScanner.php(68): _HumbugBox3c32a251b752\PhpParser\NodeTraverser->traverse(Array)
#8 phar:///data/tools/psalm/src/Psalm/Internal/Codebase/Scanner.php(439): Psalm\Internal\Scanner\FileScanner->scan(Object(Psalm\Codebase), Object(Psalm\Storage\FileStorage), false, Object(Psalm\Progress\DefaultProgress))
#9 phar:///data/tools/psalm/src/Psalm/Internal/Codebase/Scanner.php(292): Psalm\Internal\Codebase\Scanner->scanFile('/data/vendor/sc...', Array, false)
#10 phar:///data/tools/psalm/src/Psalm/Internal/Codebase/Scanner.php(361): Psalm\Internal\Codebase\Scanner->Psalm\Internal\Codebase\{closure}(185, '/data/vendor/sc...')
#11 phar:///data/tools/psalm/src/Psalm/Internal/Codebase/Scanner.php(271): Psalm\Internal\Codebase\Scanner->scanFilePaths(1)
#12 phar:///data/tools/psalm/src/Psalm/Codebase.php(360): Psalm\Internal\Codebase\Scanner->scanFiles(Object(Psalm\Internal\Codebase\ClassLikes), 1)
#13 phar:///data/tools/psalm/src/Psalm/Internal/Analyzer/ProjectAnalyzer.php(394): Psalm\Codebase->scanFiles(1)
#14 phar:///data/tools/psalm/src/psalm.php(399): Psalm\Internal\Analyzer\ProjectAnalyzer->check('/data/', false)
#15 phar:///data/tools/psalm/psalm(5): require_once('phar:///data/to...')
#16 /data/tools/psalm(14): require('phar:///data/to...')
#17 {main}
(Psalm 3.11.5@3c60609c218d4d4b3b257728b8089094e5c6c6c2 crashed due to an uncaught Throwable)
```

**Comment by jaapio** [comment]
This issue was introduced in 3.11.3.

**Comment by muglug** [comment]
Reproduced with
```php
<?php
/**
 * @mixin M
 * Hello
 */
class C {}
```

**Comment by jaapio** [comment]
Thanks for fixing this!
