### ISSUE TITLE
Live demo (getpsalm.org) fails with InvalidArgumentException

### ISSUE THREAD

**Issue by rmccue** [vimeo/psalm#370]
```
<br />
<b>Fatal error</b>:  Uncaught InvalidArgumentException: Could not get class storage for /var/www/vhosts/getpsalm.org/httpdocs/src/somefile.php:60 in /var/www/vhosts/getpsalm.org/httpdocs/vendor/vimeo/psalm/src/Psalm/Provider/ClassLikeStorageProvider.php:21
Stack trace:
#0 /var/www/vhosts/getpsalm.org/httpdocs/vendor/vimeo/psalm/src/Psalm/Checker/MethodChecker.php(674): Psalm\Provider\ClassLikeStorageProvider-&gt;get('/var/www/vhosts...')
#1 /var/www/vhosts/getpsalm.org/httpdocs/vendor/vimeo/psalm/src/Psalm/Checker/FunctionLikeChecker.php(837): Psalm\Checker\MethodChecker::getDeclaringMethodId(Object(Psalm\Checker\ProjectChecker), '/var/www/vhosts...')
#2 /var/www/vhosts/getpsalm.org/httpdocs/vendor/vimeo/psalm/src/Psalm/Checker/Statements/Expression/CallChecker.php(2408): Psalm\Checker\FunctionLikeChecker-&gt;getFunctionLikeStorage()
#3 /var/www/vhosts/getpsalm.org/httpdocs/vendor/vimeo/psalm/src/Psalm/Checker/Statements/Expression/CallChecker.php(2089): Psalm\Checker\Statements\Expression\CallChecker::checkFunctionArgumentType(Object( in <b>/var/www/vhosts/getpsalm.org/httpdocs/vendor/vimeo/psalm/src/Psalm/Provider/ClassLikeStorageProvider.php</b> on line <b>21</b><br />
```

**Comment by muglug** [comment]
With what code?

**Comment by muglug** [comment]
If there's a 500 error, pretty sure Psalm will error too.

**Comment by rmccue** [comment]
Sorry, was just working on getting a reduced test case and submitted too early!

This minimal code appears to cause it:

```php
<?php

uasort( $manifest, function ( $a, $b ) {
	return strcmp( $a['parent'], $b['parent'] );
} );
```

Can't speak for local usage though.

**Comment by muglug** [comment]
Ah, thanks, should be fixed now. The issue was that untyped param inference (which is only available on getpsalm.org) wasn't cooperating with closure definitions.

Fixed by https://github.com/vimeo/psalm/commit/a8a1489a8f22105963f7a7e7bbc64b45defaed40

**Comment by rmccue** [comment]
Thanks for that, and for the amazingly quick response.

**Comment by muglug** [comment]
Also, goodnight.
