### ISSUE TITLE
Could not get class storage for guzzlehttp/guzzleexception

### ISSUE THREAD

**Issue by patrickkusebauch** [vimeo/psalm#3755]
Command: `bin/psalm --debug-by-line`
0utput:
```
.
.
.
/var/www/app/Saas/Plugins/GoogleFit/GoogleFitController.php:258
Uncaught InvalidArgumentException: Could not get class storage for guzzlehttp\guzzleexception in /var/www/vendor/vimeo/psalm/src/Psalm/Internal/Provider/ClassLikeStorageProvider.php:45
Stack trace:
#0 /var/www/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/ClassLikes.php(525): Psalm\Internal\Provider\ClassLikeStorageProvider->get('guzzlehttp\\guzz...')
#1 /var/www/vendor/vimeo/psalm/src/Psalm/Codebase.php(744): Psalm\Internal\Codebase\ClassLikes->classExtends('GuzzleHttp\\Guzz...', 'logicexception', true)
#2 /var/www/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/StatementsAnalyzer.php(2414): Psalm\Codebase->classExtends('GuzzleHttp\\Guzz...', 'logicexception')
#3 /var/www/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/FunctionLikeAnalyzer.php(692): Psalm\Internal\Analyzer\StatementsAnalyzer->getUncaughtThrows(Object(Psalm\Context))
#4 /var/www/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/ClassAnalyzer.php(1740): Psalm\Internal\Analyzer\FunctionLikeAnalyzer->analyze(Object(Psalm\Context), Object(Psalm\Internal\Provider\NodeDataProvider), Object(Psalm\Context))
#5 /var/www/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/ClassAnalyzer.php(721): Psalm\Internal\Analyzer\ClassAnalyzer->analyzeClassMethod(Object(PhpParser\Node\Stmt\ClassMethod), Object(Psalm\Storage\ClassLikeStorage), Object(Psalm\Internal\Analyzer\ClassAnalyzer), Object(Psalm\Context), Object(Psalm\Context))
#6 /var/www/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/FileAnalyzer.php(198): Psalm\Internal\Analyzer\ClassAnalyzer->analyze(Object(Psalm\Context), Object(Psalm\Context))
#7 /var/www/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Analyzer.php(318): Psalm\Internal\Analyzer\FileAnalyzer->analyze(NULL)
#8 /var/www/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Analyzer.php(552): Psalm\Internal\Codebase\Analyzer->Psalm\Internal\Codebase\{closure}(61, '/var/www/app/Sa...')
#9 /var/www/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Analyzer.php(241): Psalm\Internal\Codebase\Analyzer->doAnalysis(Object(Psalm\Internal\Analyzer\ProjectAnalyzer), 1)
#10 /var/www/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/ProjectAnalyzer.php(527): Psalm\Internal\Codebase\Analyzer->analyzeFiles(Object(Psalm\Internal\Analyzer\ProjectAnalyzer), 1, false)
#11 /var/www/vendor/vimeo/psalm/src/psalm.php(594): Psalm\Internal\Analyzer\ProjectAnalyzer->check('/var/www/', false)
#12 /var/www/vendor/vimeo/psalm/psalm(2): require_once('/var/www/vendor...')
#13 {main}
(Psalm 3.10.1@eeed5ecccc10131397f0eb7ee6da810c0be3a7fc crashed due to an uncaught Throwable)
```

Relevant class code(lined 199-259) - `$this-googleFit` is `GuzzleHttp\Client`:
```php
    public function activitySummary(string $userId, DateTimeInterface $date = null): ActivitySummaryInterface
    {
        if ($date === null) {
            $date = new DateTimeImmutable('now', new \DateTimeZone('UTC'));
        } else {
            $date = new DateTimeImmutable($date->format('Y-m-d'), new \DateTimeZone('UTC'));
        }

        $start       = $date->setTime(0, 0, 0, 0);
        $end         = $date->setTime(23, 59, 59, 999999);
        $accessToken = $this->accessToken($userId);

        $stepsAggregate       = json_decode($this->googleFit->request('POST',
            'https://www.googleapis.com/fitness/v1/users/me/dataset:aggregate', [
                'headers' => [
                    'Accept' => 'application/json', 'Authorization' => 'Bearer '.$accessToken->getToken(),
                ], 'body' => json_encode([
                    'aggregateBy'     => [
                        [
                            'dataTypeName' => 'com.google.step_count.delta',
                            'dataSourceId' => 'derived:com.google.step_count.delta:com.google.android.gms:estimated_steps',
                        ],
                    ], "bucketByTime" => ['durationMillis' => self::ONE_DAY_IN_MILLISECONDS],
                    'startTimeMillis' => (int) $start->format('U') * 1000, 'endTimeMillis' => (int) $end->format('U') * 1000,
                ], JSON_THROW_ON_ERROR),
            ])->getBody()->getContents(), true, 512, JSON_THROW_ON_ERROR);
        $steps                = $stepsAggregate['bucket'][0]['dataset'][0]['point'] === [] ? 0
            : (int) $stepsAggregate['bucket'][0]['dataset'][0]['point'][0]['value'][0]['intVal'];
        $caloriesAggregate    = json_decode($this->googleFit->request('POST',
            'https://www.googleapis.com/fitness/v1/users/me/dataset:aggregate', [
                'headers' => [
                    'Accept' => 'application/json', 'Authorization' => 'Bearer '.$accessToken->getToken(),
                ], 'body' => json_encode([
                    'aggregateBy'     => [
                        [
                            'dataTypeName' => 'com.google.calories.expended',
                        ],
                    ], "bucketByTime" => ['durationMillis' => self::ONE_DAY_IN_MILLISECONDS],
                    'startTimeMillis' => (int) $start->format('U') * 1000, 'endTimeMillis' => (int) $end->format('U') * 1000,
                ], JSON_THROW_ON_ERROR),
            ])->getBody()->getContents(), true, 512, JSON_THROW_ON_ERROR);
        $calories             = $caloriesAggregate['bucket'][0]['dataset'][0]['point'] === [] ? 0
            : (int) $caloriesAggregate['bucket'][0]['dataset'][0]['point'][0]['value'][0]['fpVal'];
        $moveMinutesAggregate = json_decode($this->googleFit->request('POST',
            'https://www.googleapis.com/fitness/v1/users/me/dataset:aggregate', [
                'headers' => [
                    'Accept' => 'application/json', 'Authorization' => 'Bearer '.$accessToken->getToken(),
                ], 'body' => json_encode([
                    'aggregateBy'     => [
                        [
                            'dataTypeName' => 'com.google.active_minutes',
                        ],
                    ], "bucketByTime" => ['durationMillis' => self::ONE_DAY_IN_MILLISECONDS],
                    'startTimeMillis' => (int) $start->format('U') * 1000, 'endTimeMillis' => (int) $end->format('U') * 1000,
                ], JSON_THROW_ON_ERROR),
            ])->getBody()->getContents(), true, 512, JSON_THROW_ON_ERROR);
        $moveMinutes          = $moveMinutesAggregate['bucket'][0]['dataset'][0]['point'] === [] ? 0
            : (int) $moveMinutesAggregate['bucket'][0]['dataset'][0]['point'][0]['value'][0]['intVal'];

        return new ActivitySummary($steps, $calories, $moveMinutes);
    }
```

# Additional info
psalm.xml:
```xml
<?xml version="1.0"?>
<psalm
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        errorLevel="2"
        strictBinaryOperands="true"
        resolveFromConfigFile="true"
        checkForThrowsDocblock="true"
        ignoreInternalFunctionNullReturn="false"
        findUnusedVariablesAndParams="true"
        skipChecksOnUnresolvableIncludes="false"
        xmlns="https://getpsalm.org/schema/config"
        xsi:schemaLocation="https://getpsalm.org/schema/config vendor/vimeo/psalm/config.xsd"
        checkForThrowsInGlobalScope="true"
        autoloader="app/Booting.php"
>
    <projectFiles>
        <directory name="app"/>
        <ignoreFiles>
            <directory name="vendor"/>
        </ignoreFiles>
    </projectFiles>
    <plugins>
        <pluginClass class="Weirdan\DoctrinePsalmPlugin\Plugin"/>
        <pluginClass class="DanceEngineer\PsalmKnapsackCollections\Plugin"/>
        <pluginClass class="PatrickKusebauch\NettePsalmPlugin\Plugin"/>
    </plugins>
    <stubs>
        <file name="stubs/BootstrapContainerTrait.phpstub"/>
    </stubs>
    <ignoreExceptions>
        <!-- Logic exception can appear anywhere and should be expected nowhere -->
        <classAndDescendants name="LogicException" onlyGlobalScope="false"/>
    </ignoreExceptions>
    <issueHandlers>
        <!-- todo Templates, Presenters and Controls - would be really useful to ignore only for those -->
        <PropertyNotSetInConstructor errorLevel="suppress"/>
        <!-- todo Errors on form components-->
        <UndefinedInterfaceMethod errorLevel="suppress"/>
        <!-- todo Fix PHPStan....-->
        <UnnecessaryVarAnnotation errorLevel="suppress" />
    </issueHandlers>
</psalm>
```

Full class code:
```php
<?php

declare(strict_types = 1);

namespace SfEngineer\Website\Saas\Plugins\GoogleFit;

use Contributte\OAuth2Client\Flow\Google\GoogleProvider;
use DateInterval;
use DatePeriod;
use DateTimeImmutable;
use DateTimeInterface;
use DusanKasan\Knapsack\Collection;
use GuzzleHttp\Client;
use League\OAuth2\Client\Token\AccessTokenInterface;
use SfEngineer\Website\Saas\Model\Activity\ActivityInterface;
use SfEngineer\Website\Saas\Model\Activity\ActivitySummaryInterface;
use SfEngineer\Website\Saas\Model\Sleep\SleepInterface;
use SfEngineer\Website\Saas\Plugins\AccessTokens\AccessTokenController;
use SfEngineer\Website\Saas\Plugins\ExternalDataSource\DataSourceInterface;
use Tracy\Debugger;

final class GoogleFitController implements DataSourceInterface
{
    private const MAX_AGGREGATE_RANGE = 'P90D';

    private const GOOGLE_FIT_SLEEP       = 72;
    private const GOOGLE_FIT_LIGHT_SLEEP = 109;
    private const GOOGLE_FIT_DEEP_SLEEP  = 110;
    private const GOOGLE_FIT_REM_SLEEP   = 111;
    private const GOOGLE_FIT_AWAKE_SLEEP  = 112;
    private const ONE_DAY_IN_MILLISECONDS = 86400000;

    private Client $googleFit;

    private AccessTokenController $accessTokenController;

    private GoogleProvider $googleProvider;

    public function __construct(
        Client $googleFit,
        GoogleProvider $googleProvider,
        AccessTokenController $accessTokenController
    ) {
        $this->accessTokenController = $accessTokenController;
        $this->googleFit             = $googleFit;
        $this->googleProvider        = $googleProvider;
    }

    public function lastSync(string $userId): ?DateTimeImmutable
    {
        return new DateTimeImmutable();
    }

    public function calories(string $userId, DateTimeInterface $start = null, DateTimeInterface $end = null): Collection
    {
        if ($start === null) {
            $start = new DateTimeImmutable('- 30 days', new \DateTimeZone('UTC'));
        } else {
            $start = new DateTimeImmutable($start->format('Y-m-d'), new \DateTimeZone('UTC'));
        }

        if ($end === null) {
            $end = new DateTimeImmutable('now', new \DateTimeZone('UTC'));
        } else {
            $end = new DateTimeImmutable($end->format('Y-m-d'), new \DateTimeZone('UTC'));
        }

        $maxAggregateRange = new DateInterval(self::MAX_AGGREGATE_RANGE);
        $period            = new DatePeriod($start, $maxAggregateRange, $end->add(new DateInterval('P1D')));
        $accessToken       = $this->accessToken($userId);

        return Collection::from(iterator_to_array($period))->map(function (DateTimeImmutable $periodStart) use (
            $end,
            $accessToken,
            $maxAggregateRange
        ) {
            $periodEnd =
                $periodStart->add($maxAggregateRange)->sub(new DateInterval('P1D'))->setTime(23, 59, 59, 999999);
            if ($periodEnd > $end) {
                $periodEnd = $end->setTime(23, 59, 59, 999999);
            }

            $caloriesAggregate = json_decode($this->googleFit->request('POST',
                'https://www.googleapis.com/fitness/v1/users/me/dataset:aggregate', [
                    'headers' => [
                        'Accept' => 'application/json', 'Authorization' => 'Bearer '.$accessToken->getToken(),
                    ], 'body' => json_encode([
                        'aggregateBy'     => [
                            [
                                'dataTypeName' => 'com.google.calories.expended',
                            ],
                        ], "bucketByTime" => ['durationMillis' => self::ONE_DAY_IN_MILLISECONDS],
                        'startTimeMillis' => (int) $periodStart->format('U') * 1000,
                        'endTimeMillis'   => (int) $periodEnd->format('U') * 1000,
                    ], JSON_THROW_ON_ERROR),
                ])->getBody()->getContents(), true, 512, JSON_THROW_ON_ERROR);

            return Collection::from($caloriesAggregate['bucket'])
                ->indexBy(static function (array $session): string {
                    $date =
                        DateTimeImmutable::createFromFormat('U', (string) ((int) ($session['endTimeMillis'] / 1000)),
                            new
                            \DateTimeZone('UTC'));
                    assert($date !== false);
                    return $date->format('Y-m-d');
                })
                ->groupBy(static fn($_, string $key): string => $key)
                ->map(static function (Collection $buckets): ?int {
                    return $buckets->reduce(static function (?int $carry, array $bucket): ?int {
                        $dataPoint = $bucket['dataset'][0]['point'];
                        if ($dataPoint === []) {
                            return $carry;
                        }
                        $dataPoint = $bucket['dataset'][0]['point'][0]['value'] ;
                        if ($dataPoint === []) {
                            return $carry;
                        }
                        if ($carry === null) {
                            return (int) $dataPoint[0]['fpVal'];
                        }
                        return (int) min($carry, $dataPoint[0]['fpVal']);
                    }, null);
                });
        })->flatten(1)->realize();
    }

    public function bodyFat(
        string $userId,
        ?DateTimeImmutable $start = null,
        ?DateTimeImmutable $end = null
    ): Collection {
        if ($start === null) {
            $start = new DateTimeImmutable('- 30 days', new \DateTimeZone('UTC'));
        } else {
            $start = new DateTimeImmutable($start->format('Y-m-d'), new \DateTimeZone('UTC'));
        }

        if ($end === null) {
            $end = new DateTimeImmutable('now', new \DateTimeZone('UTC'));
        } else {
            $end = new DateTimeImmutable($end->format('Y-m-d'), new \DateTimeZone('UTC'));
        }

        $maxAggregateRange = new DateInterval(self::MAX_AGGREGATE_RANGE);
        $period            = new DatePeriod($start, $maxAggregateRange, $end->add(new DateInterval('P1D')));
        $accessToken       = $this->accessToken($userId);

        return Collection::from(iterator_to_array($period))->map(function (DateTimeImmutable $periodStart) use (
            $end,
            $accessToken,
            $maxAggregateRange
        ) {
            $periodEnd =
                $periodStart->add($maxAggregateRange)->sub(new DateInterval('P1D'))->setTime(23, 59, 59, 999999);
            if ($periodEnd > $end) {
                $periodEnd = $end->setTime(23, 59, 59, 999999);
            }

            $bodyFatAggregate = json_decode($this->googleFit->request('POST',
                'https://www.googleapis.com/fitness/v1/users/me/dataset:aggregate', [
                    'headers' => [
                        'Accept' => 'application/json', 'Authorization' => 'Bearer '.$accessToken->getToken(),
                    ], 'body' => json_encode([
                        'aggregateBy'     => [
                            [
                                'dataTypeName' => 'com.google.body.fat.percentage',
                            ],
                        ], "bucketByTime" => ['durationMillis' => self::ONE_DAY_IN_MILLISECONDS],
                        'startTimeMillis' => (int) $periodStart->format('U') * 1000,
                        'endTimeMillis'   => (int) $periodEnd->format('U') * 1000,
                    ], JSON_THROW_ON_ERROR),
                ])->getBody()->getContents(), true, 512, JSON_THROW_ON_ERROR);

            return Collection::from($bodyFatAggregate['bucket'])
                ->indexBy(static function (array $session): string {
                    $date =
                        DateTimeImmutable::createFromFormat('U', (string) ((int) ($session['endTimeMillis'] / 1000)),
                            new
                            \DateTimeZone('UTC'));
                    assert($date !== false);
                    return $date->format('Y-m-d');
                })
                ->groupBy(static fn($_, string $key): string => $key)
                ->map(static function (Collection $buckets): ?float {
                    return $buckets->reduce(static function (?float $carry, array $bucket): ?float {
                        $dataPoint = $bucket['dataset'][0]['point'];
                        if ($dataPoint === []) {
                            return $carry;
                        }
                        if ($carry === null) {
                            return $dataPoint[0]['ftVal'];
                        }
                        return min($carry, $dataPoint[0]['ftVal']);
                    }, null);
                });
        })->flatten(1)->realize();
    }

    public function activitySummary(string $userId, DateTimeInterface $date = null): ActivitySummaryInterface
    {
        if ($date === null) {
            $date = new DateTimeImmutable('now', new \DateTimeZone('UTC'));
        } else {
            $date = new DateTimeImmutable($date->format('Y-m-d'), new \DateTimeZone('UTC'));
        }

        $start       = $date->setTime(0, 0, 0, 0);
        $end         = $date->setTime(23, 59, 59, 999999);
        $accessToken = $this->accessToken($userId);

        $stepsAggregate       = json_decode($this->googleFit->request('POST',
            'https://www.googleapis.com/fitness/v1/users/me/dataset:aggregate', [
                'headers' => [
                    'Accept' => 'application/json', 'Authorization' => 'Bearer '.$accessToken->getToken(),
                ], 'body' => json_encode([
                    'aggregateBy'     => [
                        [
                            'dataTypeName' => 'com.google.step_count.delta',
                            'dataSourceId' => 'derived:com.google.step_count.delta:com.google.android.gms:estimated_steps',
                        ],
                    ], "bucketByTime" => ['durationMillis' => self::ONE_DAY_IN_MILLISECONDS],
                    'startTimeMillis' => (int) $start->format('U') * 1000, 'endTimeMillis' => (int) $end->format('U') * 1000,
                ], JSON_THROW_ON_ERROR),
            ])->getBody()->getContents(), true, 512, JSON_THROW_ON_ERROR);
        $steps                = $stepsAggregate['bucket'][0]['dataset'][0]['point'] === [] ? 0
            : (int) $stepsAggregate['bucket'][0]['dataset'][0]['point'][0]['value'][0]['intVal'];
        $caloriesAggregate    = json_decode($this->googleFit->request('POST',
            'https://www.googleapis.com/fitness/v1/users/me/dataset:aggregate', [
                'headers' => [
                    'Accept' => 'application/json', 'Authorization' => 'Bearer '.$accessToken->getToken(),
                ], 'body' => json_encode([
                    'aggregateBy'     => [
                        [
                            'dataTypeName' => 'com.google.calories.expended',
                        ],
                    ], "bucketByTime" => ['durationMillis' => self::ONE_DAY_IN_MILLISECONDS],
                    'startTimeMillis' => (int) $start->format('U') * 1000, 'endTimeMillis' => (int) $end->format('U') * 1000,
                ], JSON_THROW_ON_ERROR),
            ])->getBody()->getContents(), true, 512, JSON_THROW_ON_ERROR);
        $calories             = $caloriesAggregate['bucket'][0]['dataset'][0]['point'] === [] ? 0
            : (int) $caloriesAggregate['bucket'][0]['dataset'][0]['point'][0]['value'][0]['fpVal'];
        $moveMinutesAggregate = json_decode($this->googleFit->request('POST',
            'https://www.googleapis.com/fitness/v1/users/me/dataset:aggregate', [
                'headers' => [
                    'Accept' => 'application/json', 'Authorization' => 'Bearer '.$accessToken->getToken(),
                ], 'body' => json_encode([
                    'aggregateBy'     => [
                        [
                            'dataTypeName' => 'com.google.active_minutes',
                        ],
                    ], "bucketByTime" => ['durationMillis' => self::ONE_DAY_IN_MILLISECONDS],
                    'startTimeMillis' => (int) $start->format('U') * 1000, 'endTimeMillis' => (int) $end->format('U') * 1000,
                ], JSON_THROW_ON_ERROR),
            ])->getBody()->getContents(), true, 512, JSON_THROW_ON_ERROR);
        $moveMinutes          = $moveMinutesAggregate['bucket'][0]['dataset'][0]['point'] === [] ? 0
            : (int) $moveMinutesAggregate['bucket'][0]['dataset'][0]['point'][0]['value'][0]['intVal'];

        return new ActivitySummary($steps, $calories, $moveMinutes);
    }

    public function restingHeartRate(
        string $userId,
        DateTimeImmutable $start = null,
        DateTimeImmutable $end = null
    ): Collection {
        return Collection::from([]);
    }

    public function sleepData(string $userId, DateTimeImmutable $start = null, ?DateTimeImmutable $end = null): array
    {
        if ($start === null) {
            $start = new DateTimeImmutable('- 30 days', new \DateTimeZone('UTC'));
        } else {
            $start = new DateTimeImmutable($start->format('Y-m-d'), new \DateTimeZone('UTC'));
        }
        $start = $start->setTime(0, 0, 0, 0);

        if ($end === null) {
            $end = new DateTimeImmutable('now', new \DateTimeZone('UTC'));
        } else {
            $end = new DateTimeImmutable($end->format('Y-m-d'), new \DateTimeZone('UTC'));
        }
        $end = $end->setTime(23, 59, 59, 999999);

        $uri      = 'https://www.googleapis.com/fitness/v1/users/me/sessions?activityType=72&startTime='
                    .$start->format('Y-m-d\TH:i:s.v\Z').'&endTime='.$end->format('Y-m-d\TH:i:s.v\Z');
        $response = $this->googleFit->request('GET', $uri, [
            'headers' => [
                'Accept' => 'application/json', 'Authorization' => 'Bearer '.$this->accessToken($userId)->getToken(),
            ],
        ]);

        $parsedResponse = json_decode($response->getBody()->getContents(), true, 512, JSON_THROW_ON_ERROR);
        if (array_key_exists('session', $parsedResponse) === false || $parsedResponse['session'] === []) {
            return ['history' => Collection::from([])];
        }

        $data = Collection::from($parsedResponse['session'])->groupBy(static function (array $session
        ): string {
            $date =
                DateTimeImmutable::createFromFormat('U', (string) ((int) ($session['endTimeMillis'] / 1000)), new
                \DateTimeZone('UTC'));
            assert($date !== false);
            return $date->format('Y-m-d');
        })->map(static function (Collection $sessionsInADay): Collection {
            return Collection::from($sessionsInADay->reduce(static function (array $carry, array $session): array {
                $time = ($session['endTimeMillis'] - $session['startTimeMillis']) / 1000 / 60;
                return [
                    'duration'      => (int) ($carry['duration'] + $time),
                    'minutesAsleep' => (int) ($carry['minutesAsleep'] + $time),
                ];
            }, ['duration' => 0, 'minutesAsleep' => 0]));
        });

        return [
            'history' => $this->defaultCollection($start, $end)->map(static fn($_): Collection => Collection::from([
                'duration' => null, 'minutesAsleep' => null,
            ]))->replaceByKeys($data),
        ];
    }

    public function sleep(string $userId, DateTimeInterface $date = null): SleepInterface
    {
        if ($date === null) {
            $date = new DateTimeImmutable('now', new \DateTimeZone('UTC'));
        } else {
            $date = new DateTimeImmutable($date->format('Y-m-d'), new \DateTimeZone('UTC'));
        }

        $start = $date->setTime(0, 0, 0, 0);
        $end   = $date->setTime(23, 59, 59, 999999);

        $accessToken = $this->accessToken($userId);

        $uri      = 'https://www.googleapis.com/fitness/v1/users/me/sessions?activityType=72&startTime='
                    .$start->format('Y-m-d\TH:i:s.v\Z').'&endTime='.$end->format('Y-m-d\TH:i:s.v\Z');
        $response = $this->googleFit->request('GET', $uri, [
            'headers' => [
                'Accept' => 'application/json', 'Authorization' => 'Bearer '.$accessToken->getToken(),
            ],
        ]);

        $parsedResponse = json_decode($response->getBody()->getContents(), true, 512, JSON_THROW_ON_ERROR);

        if (array_key_exists('session', $parsedResponse) === false || $parsedResponse['session'] === []) {
            return new class implements SleepInterface {

                private const GOAL = 8.0;

                public function hoursSlept(): float
                {
                    return 0.0;
                }

                public function hoursGoal(): float
                {
                    return self::GOAL;
                }

                public function hoursRemainingToGoal(): float
                {
                    return $this->hoursGoal() - $this->hoursSlept();
                }

                public function sleptRatioOfGoal(): float
                {
                    return $this->hoursSlept() / $this->hoursGoal();
                }

                public function score(): ?int
                {
                    return null;
                }
            };
        }

        $sleptNanoseconds = Collection::from($parsedResponse['session'])->map(function (array $session) use (
            $end,
            $start,
            $accessToken
        ): Collection {
            $response       =
                $this->googleFit->request('POST', 'https://www.googleapis.com/fitness/v1/users/me/dataset:aggregate', [
                    'headers' => [
                        'Accept' => 'application/json', 'Authorization' => 'Bearer '.$accessToken->getToken(),
                    ], 'body' => json_encode([
                        'aggregateBy'        => [
                            [
                                'dataTypeName' => 'com.google.activity.segment',
                            ],
                        ], 'startTimeMillis' => $session['startTimeMillis'],
                        'endTimeMillis'      => $session['endTimeMillis'],
                    ], JSON_THROW_ON_ERROR),
                ]);
            $parsedResponse = json_decode($response->getBody()->getContents(), true, 512, JSON_THROW_ON_ERROR);
            return Collection::from($parsedResponse['bucket'][0]['dataset'][0]['point'])->reject(static fn(
                array $dataPoint
            ): bool => $dataPoint['value'][0]['intVal'] !== self::GOOGLE_FIT_SLEEP)->filter(static function (
                array $dataPoint
            ) use ($start, $end): bool {
                $dataEnd =
                    DateTimeImmutable::createFromFormat('U', (string) ($dataPoint['endTimeNanos'] / 1000000000), new
                    \DateTimeZone('UTC'));
                return $dataEnd > $start && $dataEnd < $end;
            });
        })->flatten(1)->reduce(static function (int $carry, array $current): int {
            return $carry + $current['endTimeNanos'] - $current['startTimeNanos'];
        }, 0);

        return new class($sleptNanoseconds) implements SleepInterface {

            private const GOAL = 8.0;

            private float $slept;

            public function __construct(int $sleptNanoseconds)
            {
                $this->slept = (float) $sleptNanoseconds / 1000000000.0 / 3600.0;
            }

            public function hoursSlept(): float
            {
                return $this->slept;
            }

            public function hoursGoal(): float
            {
                return self::GOAL;
            }

            public function hoursRemainingToGoal(): float
            {
                return $this->hoursGoal() - $this->hoursSlept();
            }

            public function sleptRatioOfGoal(): float
            {
                return $this->hoursSlept() / $this->hoursGoal();
            }

            public function score(): ?int
            {
                return null;
            }
        };
    }

    /**
     * @param  string  $userId
     * @return \League\OAuth2\Client\Token\AccessTokenInterface
     * @throws \RuntimeException if there is no access token for the user
     * @throws \League\OAuth2\Client\Provider\Exception\IdentityProviderException
     */
    private function accessToken(string $userId): AccessTokenInterface
    {
        $accessToken = $this->accessTokenController->getTokenFor($userId, AccessTokenController::GOOGLE_FIT);
        if ($accessToken->hasExpired()) {
            $newToken = $this->googleProvider->getAccessToken('refreshToken', [
                'refresh_token' => $accessToken->getRefreshToken(),
            ]);
            $this->accessTokenController->storeTokenFor($newToken, $userId, AccessTokenController::GOOGLE_FIT);
            return $newToken;
        }
        return $accessToken;
    }

    /**
     * @return \DusanKasan\Knapsack\Collection<string, null>
     * @throws \Exception
     */
    private function defaultCollection(DateTimeImmutable $start, DateTimeImmutable $end): Collection
    {
        $period = new DatePeriod($start, new DateInterval('P1D'), $end->add(new DateInterval('P1D')));
        return Collection::from(iterator_to_array($period))->map(static fn(DateTimeInterface $dateTime
        ): string => $dateTime->format('Y-m-d'))->flip()->map(static fn(string $_): ?bool => null);
    }

    public function weight(string $userId, ?DateTimeImmutable $start, ?DateTimeImmutable $end): Collection
    {
        if ($start === null) {
            $start = new DateTimeImmutable('- 30 days', new \DateTimeZone('UTC'));
        } else {
            $start = new DateTimeImmutable($start->format('Y-m-d'), new \DateTimeZone('UTC'));
        }

        if ($end === null) {
            $end = new DateTimeImmutable('now', new \DateTimeZone('UTC'));
        } else {
            $end = new DateTimeImmutable($end->format('Y-m-d'), new \DateTimeZone('UTC'));
        }

        $maxAggregateRange = new DateInterval(self::MAX_AGGREGATE_RANGE);
        $period            = new DatePeriod($start, $maxAggregateRange, $end->add(new DateInterval('P1D')));
        $accessToken       = $this->accessToken($userId);

        $bodyFat = $this->bodyFat($userId, $start, $end);

        return Collection::from(iterator_to_array($period))->map(function (DateTimeImmutable $periodStart) use (
            $bodyFat,
            $accessToken,
            $maxAggregateRange,
            $end
        ) {
            $periodEnd =
                $periodStart->add($maxAggregateRange)->sub(new DateInterval('P1D'))->setTime(23, 59, 59, 999999);
            if ($periodEnd > $end) {
                $periodEnd = $end->setTime(23, 59, 59, 999999);
            }

            $weightAggregate = json_decode($this->googleFit->request('POST',
                'https://www.googleapis.com/fitness/v1/users/me/dataset:aggregate', [
                    'headers' => [
                        'Accept' => 'application/json', 'Authorization' => 'Bearer '.$accessToken->getToken(),
                    ], 'body' => json_encode([
                        'aggregateBy'     => [
                            [
                                'dataTypeName' => 'com.google.weight',
                            ],
                        ], "bucketByTime" => ['durationMillis' => self::ONE_DAY_IN_MILLISECONDS],
                        'startTimeMillis' => (int) $periodStart->format('U') * 1000,
                        'endTimeMillis'   => (int) $periodEnd->format('U') * 1000,
                    ], JSON_THROW_ON_ERROR),
                ])->getBody()->getContents(), true, 512, JSON_THROW_ON_ERROR);
            return Collection::from($weightAggregate['bucket'])
                ->indexBy(static function (array $session): string {
                    $date = DateTimeImmutable::createFromFormat('U',
                        (string) ((int) ((int) $session['endTimeMillis'] / 1000)), new
                        \DateTimeZone('UTC'));
                    assert($date !== false);
                    return $date->format('Y-m-d');
                })
                ->groupBy(static fn($_, string $key): string => $key)
                ->map(static function (Collection $buckets): ?float {
                    return $buckets->reduce(static function (?float $carry, array $bucket): ?float {
                        $dataPoint = $bucket['dataset'][0]['point'];
                        if ($dataPoint === []) {
                            return $carry;
                        }
                        $weight = Collection::from($dataPoint[0]['value'])->reduce(static function (
                            ?float $carry,
                            array $data
                        ): ?float {
                            $value = $data['fpVal'];
                            if ($carry === null) {
                                return $value;
                            }
                            return min($carry, $value);
                        }, null);
                        if ($carry === null) {
                            return $weight;
                        }
                        if ($weight === null) {
                            return $carry;
                        }
                        return min($carry, $weight);
                    }, null);
                })
                ->map(static function (?float $weight, string $date) use ($bodyFat): array {
                    $fat = $bodyFat->get($date);
                    return [
                        'fatPercentage' => $fat, 'weight' => $weight,
                        'fatMass'       => $fat === null || $weight === null ? null : round($fat * $weight / 100, 2),
                        'BMI'           => null,
                    ];
                });
        })->flatten(1)->realize();
    }

}
```

**Comment by patrickkusebauch** [comment]
FYI: Updated to `(Psalm 3.12.2@7c7ebd068f8acaba211d4a2c707c4ba90874fa26`, the issue still persists.
