### ISSUE TITLE
Crash due to an uncaught Throwable

### ISSUE THREAD

**Issue by sebastianbergmann** [vimeo/psalm#3854]
Ran into this while experimenting with configuration options for PHPUnit:
```
$ git clone https://github.com/sebastianbergmann/phpunit.git
$ cd phpunit
$ git checkout 8.5
$ composer install
```
```patch
diff --git a/.psalm/config.xml b/.psalm/config.xml
index f8db545fd..641b848e4 100644
--- a/.psalm/config.xml
+++ b/.psalm/config.xml
@@ -6,6 +6,10 @@
     cacheDirectory=".psalm/cache"
     errorBaseline=".psalm/baseline.xml"
     totallyTyped="false"
+    reportMixedIssues="true"
+    checkForThrowsDocblock="true"
+    findUnusedVariablesAndParams="true"
+    findUnusedCode="true"
 >
     <projectFiles>
         <directory name="src" />
@@ -13,43 +17,4 @@
             <directory name="vendor" />
         </ignoreFiles>
     </projectFiles>
-
-    <issueHandlers>
-        <LessSpecificReturnType errorLevel="info" />
-
-        <!-- level 3 issues - slightly lazy code writing, but provably low false-negatives -->
-
-        <DeprecatedMethod errorLevel="info" />
-        <DeprecatedProperty errorLevel="info" />
-        <DeprecatedClass errorLevel="info" />
-        <DeprecatedConstant errorLevel="info" />
-        <DeprecatedInterface errorLevel="info" />
-        <DeprecatedTrait errorLevel="info" />
-
-        <InternalMethod errorLevel="info" />
-        <InternalProperty errorLevel="info" />
-        <InternalClass errorLevel="info" />
-
-        <MissingClosureReturnType errorLevel="info" />
-        <MissingReturnType errorLevel="info" />
-        <MissingPropertyType errorLevel="info" />
-        <InvalidDocblock errorLevel="info" />
-        <MisplacedRequiredParam errorLevel="info" />
-
-        <PropertyNotSetInConstructor errorLevel="info" />
-        <MissingConstructor errorLevel="info" />
-        <MissingClosureParamType errorLevel="info" />
-        <MissingParamType errorLevel="info" />
-
-        <RedundantCondition errorLevel="info" />
-
-        <DocblockTypeContradiction errorLevel="info" />
-        <RedundantConditionGivenDocblockType errorLevel="info" />
-
-        <UnresolvableInclude errorLevel="info" />
-
-        <RawObjectIteration errorLevel="info" />
-
-        <InvalidStringClass errorLevel="info" />
-    </issueHandlers>
 </psalm>
```
```
./tools/psalm --config=.psalm/config.xml
Scanning files...
Analyzing files...

░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░  60 / 217 (27%)
░░░░░░░░░░░░░░░░░░░░░░░░░░░░░Uncaught Exception: Could not get class storage for sebastianbergmann\codecoverage\coveredcodenotexecutedexception
Stack trace in the forked worker:
#0 phar:///usr/local/src/phpunit/tools/psalm/src/Psalm/Internal/Codebase/ClassLikes.php(398): Psalm\Internal\Provider\ClassLikeStorageProvider->get('sebastianbergma...')
#1 phar:///usr/local/src/phpunit/tools/psalm/src/Psalm/Codebase.php(557): Psalm\Internal\Codebase\ClassLikes->classExtends('SebastianBergma...', 'PHPUnit\\Framewo...')
#2 phar:///usr/local/src/phpunit/tools/psalm/src/Psalm/Internal/Analyzer/FunctionLikeAnalyzer.php(394): Psalm\Codebase->classExtendsOrImplements('SebastianBergma...', 'PHPUnit\\Framewo...')
#3 phar:///usr/local/src/phpunit/tools/psalm/src/Psalm/Internal/Analyzer/ClassAnalyzer.php(822): Psalm\Internal\Analyzer\FunctionLikeAnalyzer->analyze(Object(Psalm\Context), Object(Psalm\Internal\Provider\NodeDataProvider), Object(Psalm\Context))
#4 phar:///usr/local/src/phpunit/tools/psalm/src/Psalm/Internal/Analyzer/ClassAnalyzer.php(349): Psalm\Internal\Analyzer\ClassAnalyzer->analyzeClassMethod(Object(_HumbugBox49e3974037c0\PhpParser\Node\Stmt\ClassMethod), Object(Psalm\Storage\ClassLikeStorage), Object(Psalm\Internal\Analyzer\ClassAnalyzer), Object(Psalm\Context), Object(Psalm\Context))
#5 phar:///usr/local/src/phpunit/tools/psalm/src/Psalm/Internal/Analyzer/FileAnalyzer.php(175): Psalm\Internal\Analyzer\ClassAnalyzer->analyze(Object(Psalm\Context), Object(Psalm\Context))
#6 phar:///usr/local/src/phpunit/tools/psalm/src/Psalm/Internal/Codebase/Analyzer.php(269): Psalm\Internal\Analyzer\FileAnalyzer->analyze(NULL)
#7 phar:///usr/local/src/phpunit/tools/psalm/src/Psalm/Internal/Fork/Pool.php(143): Psalm\Internal\Codebase\Analyzer->Psalm\Internal\Codebase\{closure}(46, '/usr/local/src/...')
#8 phar:///usr/local/src/phpunit/tools/psalm/src/Psalm/Internal/Codebase/Analyzer.php(316): Psalm\Internal\Fork\Pool->__construct(Array, Object(Closure), Object(Closure), Object(Closure), Object(Closure))
#9 phar:///usr/local/src/phpunit/tools/psalm/src/Psalm/Internal/Codebase/Analyzer.php(224): Psalm\Internal\Codebase\Analyzer->doAnalysis(Object(Psalm\Internal\Analyzer\ProjectAnalyzer), 3)
#10 phar:///usr/local/src/phpunit/tools/psalm/src/Psalm/Internal/Analyzer/ProjectAnalyzer.php(452): Psalm\Internal\Codebase\Analyzer->analyzeFiles(Object(Psalm\Internal\Analyzer\ProjectAnalyzer), 3, false, true)
#11 phar:///usr/local/src/phpunit/tools/psalm/src/psalm.php(406): Psalm\Internal\Analyzer\ProjectAnalyzer->check('/usr/local/src/...', false)
#12 phar:///usr/local/src/phpunit/tools/psalm/psalm(5): require_once('phar:///usr/loc...')
#13 /usr/local/src/phpunit/tools/psalm(14): require('phar:///usr/loc...')
#14 {main} in phar:///usr/local/src/phpunit/tools/psalm/src/Psalm/Internal/Fork/Pool.php:276
Stack trace:
#0 phar:///usr/local/src/phpunit/tools/psalm/src/Psalm/Internal/Fork/Pool.php(304): Psalm\Internal\Fork\Pool->readResultsFromChildren()
#1 phar:///usr/local/src/phpunit/tools/psalm/src/Psalm/Internal/Codebase/Analyzer.php(352): Psalm\Internal\Fork\Pool->wait()
#2 phar:///usr/local/src/phpunit/tools/psalm/src/Psalm/Internal/Codebase/Analyzer.php(224): Psalm\Internal\Codebase\Analyzer->doAnalysis(Object(Psalm\Internal\Analyzer\ProjectAnalyzer), 3)
#3 phar:///usr/local/src/phpunit/tools/psalm/src/Psalm/Internal/Analyzer/ProjectAnalyzer.php(452): Psalm\Internal\Codebase\Analyzer->analyzeFiles(Object(Psalm\Internal\Analyzer\ProjectAnalyzer), 3, false, true)
#4 phar:///usr/local/src/phpunit/tools/psalm/src/psalm.php(406): Psalm\Internal\Analyzer\ProjectAnalyzer->check('/usr/local/src/...', false)
#5 phar:///usr/local/src/phpunit/tools/psalm/psalm(5): require_once('phar:///usr/loc...')
#6 /usr/local/src/phpunit/tools/psalm(14): require('phar:///usr/loc...')
#7 {main}
(Psalm 3.12.2@7c7ebd068f8acaba211d4a2c707c4ba90874fa26 crashed due to an uncaught Throwable)
```

**Comment by weirdan** [comment]
I cannot reproduce this using the steps provided, on PHP7.4. Can you provide the output of the run with `--debug --debug-by-line` switches enabled? Also, what PHP/OS you're running this on?

**Comment by sebastianbergmann** [comment]
#### PHP Version
```
$ php --version
PHP 7.4.8 (cli) (built: Jul  9 2020 08:57:23) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.8, Copyright (c), by Zend Technologies
```
#### Operating System
```
$ cat /etc/os-release        
NAME=Fedora
VERSION="32 (Workstation Edition)"
ID=fedora
VERSION_ID=32
VERSION_CODENAME=""
PLATFORM_ID="platform:f32"
PRETTY_NAME="Fedora 32 (Workstation Edition)"
ANSI_COLOR="0;34"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:32"
HOME_URL="https://fedoraproject.org/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora/f32/system-administrators-guide/"
SUPPORT_URL="https://fedoraproject.org/wiki/Communicating_and_getting_help"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=32
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=32
PRIVACY_POLICY_URL="https://fedoraproject.org/wiki/Legal:PrivacyPolicy"
VARIANT="Workstation Edition"
VARIANT_ID=workstation
```
#### Debug Output
* https://gist.github.com/sebastianbergmann/bb795ee2e7a83a0613a8c81c9721b08a

**Comment by muglug** [comment]
I'm also unable to reproduce it (and it won't reproduce in CI either, where PHPUnit is checked with every commit).

It's really telling that the composer autoloader is failing for you (in that debug output it appears a bunch of files aren't available through it). What version of composer are you using?

**Comment by sebastianbergmann** [comment]
The one that is under version control in `tools`:
```
$ ./tools/composer --version              
Composer version 1.10.9 2020-07-16 12:57:00
```

**Comment by muglug** [comment]
Hmm still unable to reproduce. Can you run phpunit on itself there? It looks like the composer autoloader cannot find `PHPUnit\Framework\Constraint\LogicalAnd`, among other files.

**Comment by sebastianbergmann** [comment]
I cannot reproduce it any more, sorry for the noise.

**Comment by jawira** [comment]
Had a similar issue, the problem disappeared after clearing cache:

```console
$ vendor/bin/psalm --clear-cache
```
