### ISSUE TITLE
[Crash] Issue on type imports

### ISSUE THREAD

**Issue by SCIF** [vimeo/psalm#3875]
Cannot do a full repro. As result of attempts I created #3874 but it doesn't crash website version of Psalm :)

A file crashing the Psalm:
```
/**
 * @psalm-import-type IngredientObj from IngredientScalerInterface
 * @psalm-import-type IngredientScaledObj from IngredientScalerInterface
 * @psalm-type SortedIngredients=array<int, non-empty-array<int, IngredientScaledObj>>
 */
final class IngredientScaler implements IngredientScalerInterface
```

IngredientScalerInterface:
```
/**
 * @psalm-type IngredientObj=object{
 *  code: string,
 *  id: int,
 *  riid: int,
 *  recipe_id: int,
 *  ingredient_id: int,
 *  substitute_for_id: ?int,
 *  quantity: float,
 *  unit_amount: float,
 *  scale_max: float,
 *  scale_round: float,
 *  scale_min: float,
 *  protein: float,
 *  fat: float,
 *  carbohydrates: float,
 *  nutrients: \App\ValueObjects\Nutrients,
 *  perUnit: \App\ValueObjects\Nutrients,
 *  energy: float
 * }
 * @psalm-type IngredientScaledObj=object{required_quantity: float}&IngredientObj
 */
interface IngredientScalerInterface
```

```
$ ./vendor/bin/psalm app/Nutrition/ --no-cache
Scanning files...
Analyzing files...

Uncaught InvalidArgumentException: Could not get class storage for app\nutrition\ingredientscaledobj in /www/platform/vendor/vimeo/psalm/src/Psalm/Internal/Provider/ClassLikeStorageProvider.php:45
Stack trace:
#0 /www/platform/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Properties.php(98): Psalm\Internal\Provider\ClassLikeStorageProvider->get('App\\Nutrition\\I...')
#1 /www/platform/vendor/vimeo/psalm/src/Psalm/Internal/Type/Comparator/ObjectLikeComparator.php(104): Psalm\Internal\Codebase\Properties->propertyExists('App\\Nutrition\\I...', true)
#2 /www/platform/vendor/vimeo/psalm/src/Psalm/Internal/Type/Comparator/AtomicTypeComparator.php(565): Psalm\Internal\Type\Comparator\ObjectLikeComparator::isContainedByObjectWithProperties(Object(Psalm\Codebase), Object(Psalm\Type\Atomic\TNamedObject), Object(Psalm\Type\Atomic\TObjectWithProperties), false, Object(Psalm\Internal\Type\Comparator\TypeComparisonResult))
#3 /www/platform/vendor/vimeo/psalm/src/Psalm/Internal/Type/Comparator/UnionTypeComparator.php(111): Psalm\Internal\Type\Comparator\AtomicTypeComparator::isContainedBy(Object(Psalm\Codebase), Object(Psalm\Type\Atomic\TNamedObject), Object(Psalm\Type\Atomic\TObjectWithProperties), false, true, Object(Psalm\Internal\Type\Comparator\TypeComparisonResult))
#4 /www/platform/vendor/vimeo/psalm/src/Psalm/Internal/Type/Comparator/ArrayTypeComparator.php(197): Psalm\Internal\Type\Comparator\UnionTypeComparator::isContainedBy(Object(Psalm\Codebase), Object(Psalm\Type\Union), Object(Psalm\Type\Union), false, false, Object(Psalm\Internal\Type\Comparator\TypeComparisonResult), false)
#5 /www/platform/vendor/vimeo/psalm/src/Psalm/Internal/Type/Comparator/AtomicTypeComparator.php(250): Psalm\Internal\Type\Comparator\ArrayTypeComparator::isContainedBy(Object(Psalm\Codebase), Object(Psalm\Type\Atomic\TNonEmptyArray), Object(Psalm\Type\Atomic\TNonEmptyArray), false, Object(Psalm\Internal\Type\Comparator\TypeComparisonResult))
#6 /www/platform/vendor/vimeo/psalm/src/Psalm/Internal/Type/Comparator/UnionTypeComparator.php(111): Psalm\Internal\Type\Comparator\AtomicTypeComparator::isContainedBy(Object(Psalm\Codebase), Object(Psalm\Type\Atomic\TNonEmptyArray), Object(Psalm\Type\Atomic\TNonEmptyArray), false, true, Object(Psalm\Internal\Type\Comparator\TypeComparisonResult))
#7 /www/platform/vendor/vimeo/psalm/src/Psalm/Internal/Type/Comparator/ArrayTypeComparator.php(197): Psalm\Internal\Type\Comparator\UnionTypeComparator::isContainedBy(Object(Psalm\Codebase), Object(Psalm\Type\Union), Object(Psalm\Type\Union), false, false, Object(Psalm\Internal\Type\Comparator\TypeComparisonResult), false)
#8 /www/platform/vendor/vimeo/psalm/src/Psalm/Internal/Type/Comparator/AtomicTypeComparator.php(250): Psalm\Internal\Type\Comparator\ArrayTypeComparator::isContainedBy(Object(Psalm\Codebase), Object(Psalm\Type\Atomic\TArray), Object(Psalm\Type\Atomic\TArray), false, Object(Psalm\Internal\Type\Comparator\TypeComparisonResult))
#9 /www/platform/vendor/vimeo/psalm/src/Psalm/Internal/Type/Comparator/UnionTypeComparator.php(111): Psalm\Internal\Type\Comparator\AtomicTypeComparator::isContainedBy(Object(Psalm\Codebase), Object(Psalm\Type\Atomic\TArray), Object(Psalm\Type\Atomic\TArray), false, true, Object(Psalm\Internal\Type\Comparator\TypeComparisonResult))
#10 /www/platform/vendor/vimeo/psalm/src/Psalm/Internal/Type/Comparator/ObjectLikeComparator.php(65): Psalm\Internal\Type\Comparator\UnionTypeComparator::isContainedBy(Object(Psalm\Codebase), Object(Psalm\Type\Union), Object(Psalm\Type\Union), false, false, Object(Psalm\Internal\Type\Comparator\TypeComparisonResult), false)
#11 /www/platform/vendor/vimeo/psalm/src/Psalm/Internal/Type/Comparator/AtomicTypeComparator.php(232): Psalm\Internal\Type\Comparator\ObjectLikeComparator::isContainedBy(Object(Psalm\Codebase), Object(Psalm\Type\Atomic\ObjectLike), Object(Psalm\Type\Atomic\ObjectLike), false, Object(Psalm\Internal\Type\Comparator\TypeComparisonResult))
#12 /www/platform/vendor/vimeo/psalm/src/Psalm/Internal/Type/Comparator/UnionTypeComparator.php(111): Psalm\Internal\Type\Comparator\AtomicTypeComparator::isContainedBy(Object(Psalm\Codebase), Object(Psalm\Type\Atomic\ObjectLike), Object(Psalm\Type\Atomic\ObjectLike), false, true, Object(Psalm\Internal\Type\Comparator\TypeComparisonResult))
#13 /www/platform/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/Statements/Expression/Assignment/InstancePropertyAssignmentAnalyzer.php(923): Psalm\Internal\Type\Comparator\UnionTypeComparator::isContainedBy(Object(Psalm\Codebase), Object(Psalm\Type\Union), Object(Psalm\Type\Union), true, true, Object(Psalm\Internal\Type\Comparator\TypeComparisonResult))
#14 /www/platform/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/Statements/Expression/Assignment/ArrayAssignmentAnalyzer.php(638): Psalm\Internal\Analyzer\Statements\Expression\Assignment\InstancePropertyAssignmentAnalyzer::analyze(Object(Psalm\Internal\Analyzer\StatementsAnalyzer), Object(PhpParser\Node\Expr\PropertyFetch), 'sortedIngredien...', NULL, Object(Psalm\Type\Union), Object(Psalm\Context), false)
#15 /www/platform/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/Statements/Expression/Assignment/ArrayAssignmentAnalyzer.php(62): Psalm\Internal\Analyzer\Statements\Expression\Assignment\ArrayAssignmentAnalyzer::updateArrayType(Object(Psalm\Internal\Analyzer\StatementsAnalyzer), Object(PhpParser\Node\Expr\ArrayDimFetch), Object(PhpParser\Node\Expr\Variable), Object(Psalm\Type\Union), Object(Psalm\Context))
#16 /www/platform/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/Statements/Expression/AssignmentAnalyzer.php(811): Psalm\Internal\Analyzer\Statements\Expression\Assignment\ArrayAssignmentAnalyzer::analyze(Object(Psalm\Internal\Analyzer\StatementsAnalyzer), Object(PhpParser\Node\Expr\ArrayDimFetch), Object(Psalm\Context), Object(PhpParser\Node\Expr\Variable), Object(Psalm\Type\Union))
#17 /www/platform/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/Statements/ExpressionAnalyzer.php(131): Psalm\Internal\Analyzer\Statements\Expression\AssignmentAnalyzer::analyze(Object(Psalm\Internal\Analyzer\StatementsAnalyzer), Object(PhpParser\Node\Expr\ArrayDimFetch), Object(PhpParser\Node\Expr\Variable), Object(Psalm\Type\Union), Object(Psalm\Context), NULL)
#18 /www/platform/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/Statements/ExpressionAnalyzer.php(50): Psalm\Internal\Analyzer\Statements\ExpressionAnalyzer::handleExpression(Object(Psalm\Internal\Analyzer\StatementsAnalyzer), Object(PhpParser\Node\Expr\Assign), Object(Psalm\Context), false, NULL, true)
#19 /www/platform/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/StatementsAnalyzer.php(439): Psalm\Internal\Analyzer\Statements\ExpressionAnalyzer::analyze(Object(Psalm\Internal\Analyzer\StatementsAnalyzer), Object(PhpParser\Node\Expr\Assign), Object(Psalm\Context), false, NULL, true)
#20 /www/platform/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/StatementsAnalyzer.php(163): Psalm\Internal\Analyzer\StatementsAnalyzer::analyzeStatement(Object(Psalm\Internal\Analyzer\StatementsAnalyzer), Object(PhpParser\Node\Stmt\Expression), Object(Psalm\Context), NULL)
#21 /www/platform/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/Statements/Block/LoopAnalyzer.php(198): Psalm\Internal\Analyzer\StatementsAnalyzer->analyze(Array, Object(Psalm\Context))
#22 /www/platform/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/Statements/Block/ForeachAnalyzer.php(315): Psalm\Internal\Analyzer\Statements\Block\LoopAnalyzer::analyze(Object(Psalm\Internal\Analyzer\StatementsAnalyzer), Array, Array, Array, Object(Psalm\Internal\Scope\LoopScope), Object(Psalm\Context), false, false)
#23 /www/platform/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/StatementsAnalyzer.php(399): Psalm\Internal\Analyzer\Statements\Block\ForeachAnalyzer::analyze(Object(Psalm\Internal\Analyzer\StatementsAnalyzer), Object(PhpParser\Node\Stmt\Foreach_), Object(Psalm\Context))
#24 /www/platform/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/StatementsAnalyzer.php(163): Psalm\Internal\Analyzer\StatementsAnalyzer::analyzeStatement(Object(Psalm\Internal\Analyzer\StatementsAnalyzer), Object(PhpParser\Node\Stmt\Foreach_), Object(Psalm\Context), Object(Psalm\Context))
#25 /www/platform/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/FunctionLikeAnalyzer.php(560): Psalm\Internal\Analyzer\StatementsAnalyzer->analyze(Array, Object(Psalm\Context), Object(Psalm\Context), true)
#26 /www/platform/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/ClassAnalyzer.php(1906): Psalm\Internal\Analyzer\FunctionLikeAnalyzer->analyze(Object(Psalm\Context), Object(Psalm\Internal\Provider\NodeDataProvider), Object(Psalm\Context))
#27 /www/platform/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/ClassAnalyzer.php(765): Psalm\Internal\Analyzer\ClassAnalyzer->analyzeClassMethod(Object(PhpParser\Node\Stmt\ClassMethod), Object(Psalm\Storage\ClassLikeStorage), Object(Psalm\Internal\Analyzer\ClassAnalyzer), Object(Psalm\Context), Object(Psalm\Context))
#28 /www/platform/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/FileAnalyzer.php(217): Psalm\Internal\Analyzer\ClassAnalyzer->analyze(Object(Psalm\Context), Object(Psalm\Context))
#29 /www/platform/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Analyzer.php(341): Psalm\Internal\Analyzer\FileAnalyzer->analyze(NULL)
#30 /www/platform/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Analyzer.php(577): Psalm\Internal\Codebase\Analyzer->Psalm\Internal\Codebase\{closure}(0, '/www/platform/a...')
#31 /www/platform/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Analyzer.php(267): Psalm\Internal\Codebase\Analyzer->doAnalysis(Object(Psalm\Internal\Analyzer\ProjectAnalyzer), 1)
#32 /www/platform/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/ProjectAnalyzer.php(1207): Psalm\Internal\Codebase\Analyzer->analyzeFiles(Object(Psalm\Internal\Analyzer\ProjectAnalyzer), 1, false, false)
#33 /www/platform/vendor/vimeo/psalm/src/psalm.php(619): Psalm\Internal\Analyzer\ProjectAnalyzer->checkPaths(Array)
#34 /www/platform/vendor/vimeo/psalm/psalm(2): require_once('/www/platform/v...')
#35 {main}
(Psalm dev-master@fc8c899b3ac3c4c5c84042bd1d7d80f6541748a5 crashed due to an uncaught Throwable)```

**Comment by SCIF** [comment]
If I would format `IngredientScalerInterface` like:
```
interface
/**
 * @psalm-type IngredientObj=object{
 *  code: string,
 *  id: int,
 *  riid: int,
 *  recipe_id: int,
 *  ingredient_id: int,
 *  substitute_for_id: ?int,
 *  quantity: float,
 *  unit_amount: float,
 *  scale_max: float,
 *  scale_round: float,
 *  scale_min: float,
 *  protein: float,
 *  fat: float,
 *  carbohydrates: float,
 *  nutrients: \App\ValueObjects\Nutrients,
 *  perUnit: \App\ValueObjects\Nutrients,
 *  energy: float
 * }
 * @psalm-type IngredientScaledObj=object{required_quantity: float}&IngredientObj
 */
 IngredientScalerInterface
{
```

then it works and comes to: 140 errors and 2 issues.

**Comment by SCIF** [comment]
```/**
 * @psalm-import-type IngredientObj from IngredientScalerInterface
 * @psalm-import-type IngredientScaledObj from IngredientScalerInterface
 * psalm-type SortedIngredients=array<int, non-empty-array<int, IngredientScaledObj>>
 */
final class IngredientScaler implements IngredientScalerInterface

**Comment by SCIF** [comment]
One more way to get it working is to remove a psalm return definition from one of methods:

```
    /**
     * @psalm-param IngredientObj $ingredient
     *
     * @psalm-return IngredientScaledObj    <------------------ remove this one
     */
    private static function scaleQuantity(object $ingredient, float $unitQuantity): object
```

Comes to 32 and 4.

**Comment by SCIF** [comment]
I narrowed down a bit. Crash happens on next line:


```
$this->sortedIngredients['protein'][$proteinRate][]                               = $newIngredient;
```

and here is a definition:

```

    /**
     * @psalm-var array{protein: SortedIngredients, fat: SortedIngredients, carbohydrates: SortedIngredients} $sortedIngredients
     */
    private $sortedIngredients;
```

and `$newIngredient` is a clone of `IngredientScaledObj` instance.

**Comment by SCIF** [comment]
If I put `IngredientScalerInterface` into the same file as implementation seats, then it works fine.

**Comment by muglug** [comment]
Please see if you can reproduce in a separate repository

**Comment by SCIF** [comment]
Something weird happened. I tried to reproduce a bug and created a separated project, copied files. It works. Remove vendor and made one more `composer update` and it works in my project now. Some cache issues, probably.
