### ISSUE TITLE
Bool analysis breaks down beyond 4 levels deep

### ISSUE THREAD

**Issue by still-dreaming-1** [vimeo/psalm#3932]
Not sure if this is an intentional limitation or a bug, but it is something I ran into:
https://psalm.dev/r/453ebf163e

**Comment by weirdan** [comment]
I think you might be triggering `ComplicatedExpressionException` here .

See https://github.com/vimeo/psalm/blob/2399643472a936b03dcf62bd981a75cdc8d32261/src/Psalm/Type/Algebra.php#L669-L671
Transforming the expression using [De Morgan's laws](https://en.wikipedia.org/wiki/De_Morgan%27s_laws) may help: https://psalm.dev/r/37f9fd9f39

**Comment by muglug** [comment]
The error occurs while Psalm is in the midst of trying to convert an expression in Disjunctive Normal Form to one in Conjunctive Normal Form (which it uses for all its logical dealings).

There are definitely some optimisations that could be added to avoid hitting that limit, but I'd really need someone who knows the area better than I do.

**Comment by still-dreaming-1** [comment]
Okay, yeah not a big deal I guess. I actually refactored the code to avoid the issue and I think the result was more readable anyways. It seems like it's not exactly a bug, just a limitation. Perhaps a better error message would be nice since the can't verify return type was a little misleading at first until I figured out what was going on.

**Comment by muglug** [comment]
@weirdan's suggested workaround was actually the best (if slightly hacky) solution:

if
```
negateCNF(getFormula($php_expr))
```
 runs into issues, it now tries
```
getFormula(new PhpParser\Node\Expr\BooleanNot($php_expr))
```
which works, at least in the example given

**Comment by morozov** [comment]
Not sure how relevant it is, but Psalm `3.x-dev` sill fails with a `ComplicatedExpressionException` on doctrine/dbal:
```
$ psalm --threads=1
Scanning files...
Analyzing files...

░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░E░░░░░░░░░░░░░░  60 / 431 (13%)
░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ 120 / 431 (27%)
░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░Uncaught Psalm\Exception\ComplicatedExpressionException in /home/morozov/Projects/dbal/vendor/vimeo/psalm/src/Psalm/Type/Algebra.php:670
Stack trace:
#0 /home/morozov/Projects/dbal/vendor/vimeo/psalm/src/Psalm/Type/Algebra.php(816): Psalm\Type\Algebra::groupImpossibilities(Array)
#1 /home/morozov/Projects/dbal/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/Statements/Block/SwitchCaseAnalyzer.php(381): Psalm\Type\Algebra::negateFormula(Array)
#2 /home/morozov/Projects/dbal/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/Statements/Block/SwitchAnalyzer.php(118): Psalm\Internal\Analyzer\Statements\Block\SwitchCaseAnalyzer::analyze(Object(Psalm\Internal\Analyzer\StatementsAnalyzer), Object(Psalm\Codebase), Object(PhpParser\Node\Stmt\Switch_), NULL, Object(PhpParser\Node\Stmt\Case_), Object(Psalm\Context), Object(Psalm\Context), 'return_throw', Array, true, Object(Psalm\Internal\Scope\SwitchScope))
#3 /home/morozov/Projects/dbal/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/StatementsAnalyzer.php(480): Psalm\Internal\Analyzer\Statements\Block\SwitchAnalyzer::analyze(Object(Psalm\Internal\Analyzer\StatementsAnalyzer), Object(PhpParser\Node\Stmt\Switch_), Object(Psalm\Context))
#4 /home/morozov/Projects/dbal/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/StatementsAnalyzer.php(169): Psalm\Internal\Analyzer\StatementsAnalyzer::analyzeStatement(Object(Psalm\Internal\Analyzer\StatementsAnalyzer), Object(PhpParser\Node\Stmt\Switch_), Object(Psalm\Context), NULL)
#5 /home/morozov/Projects/dbal/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/Statements/Block/LoopAnalyzer.php(198): Psalm\Internal\Analyzer\StatementsAnalyzer->analyze(Array, Object(Psalm\Context))
#6 /home/morozov/Projects/dbal/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/Statements/Block/ForeachAnalyzer.php(308): Psalm\Internal\Analyzer\Statements\Block\LoopAnalyzer::analyze(Object(Psalm\Internal\Analyzer\StatementsAnalyzer), Array, Array, Array, Object(Psalm\Internal\Scope\LoopScope), Object(Psalm\Context), false, false)
#7 /home/morozov/Projects/dbal/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/StatementsAnalyzer.php(460): Psalm\Internal\Analyzer\Statements\Block\ForeachAnalyzer::analyze(Object(Psalm\Internal\Analyzer\StatementsAnalyzer), Object(PhpParser\Node\Stmt\Foreach_), Object(Psalm\Context))
#8 /home/morozov/Projects/dbal/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/StatementsAnalyzer.php(169): Psalm\Internal\Analyzer\StatementsAnalyzer::analyzeStatement(Object(Psalm\Internal\Analyzer\StatementsAnalyzer), Object(PhpParser\Node\Stmt\Foreach_), Object(Psalm\Context), Object(Psalm\Context))
#9 /home/morozov/Projects/dbal/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/FunctionLikeAnalyzer.php(569): Psalm\Internal\Analyzer\StatementsAnalyzer->analyze(Array, Object(Psalm\Context), Object(Psalm\Context), true)
#10 /home/morozov/Projects/dbal/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/ClassAnalyzer.php(1891): Psalm\Internal\Analyzer\FunctionLikeAnalyzer->analyze(Object(Psalm\Context), Object(Psalm\Internal\Provider\NodeDataProvider), Object(Psalm\Context))
#11 /home/morozov/Projects/dbal/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/ClassAnalyzer.php(743): Psalm\Internal\Analyzer\ClassAnalyzer->analyzeClassMethod(Object(PhpParser\Node\Stmt\ClassMethod), Object(Psalm\Storage\ClassLikeStorage), Object(Psalm\Internal\Analyzer\ClassAnalyzer), Object(Psalm\Context), Object(Psalm\Context))
#12 /home/morozov/Projects/dbal/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/FileAnalyzer.php(218): Psalm\Internal\Analyzer\ClassAnalyzer->analyze(Object(Psalm\Context), Object(Psalm\Context))
#13 /home/morozov/Projects/dbal/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Analyzer.php(349): Psalm\Internal\Analyzer\FileAnalyzer->analyze(NULL)
#14 /home/morozov/Projects/dbal/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Analyzer.php(583): Psalm\Internal\Codebase\Analyzer->Psalm\Internal\Codebase\{closure}(161, '/home/morozov/P...')
#15 /home/morozov/Projects/dbal/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Analyzer.php(275): Psalm\Internal\Codebase\Analyzer->doAnalysis(Object(Psalm\Internal\Analyzer\ProjectAnalyzer), 1)
#16 /home/morozov/Projects/dbal/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/ProjectAnalyzer.php(630): Psalm\Internal\Codebase\Analyzer->analyzeFiles(Object(Psalm\Internal\Analyzer\ProjectAnalyzer), 1, false, true)
#17 /home/morozov/Projects/dbal/vendor/vimeo/psalm/src/psalm.php(680): Psalm\Internal\Analyzer\ProjectAnalyzer->check('/home/morozov/P...', false)
#18 /home/morozov/Projects/dbal/vendor/vimeo/psalm/psalm(2): require_once('/home/morozov/P...')
#19 {main}
(Psalm dev-master@afce2dc66ff83ccad3f3a7aa26740a5eb829b2ca crashed due to an uncaught Throwable)
```
Please let me know if you need a reproduction scenario.

**Comment by morozov** [comment]
This is the excerpt from the code causing the failure: https://psalm.dev/r/1f175f5f23.

**Comment by muglug** [comment]
I've ticketed that separately, that exception needs to be caught
