### ISSUE TITLE
3.14.0 crashes

### ISSUE THREAD

**Issue by ADmad** [vimeo/psalm#4005]
```
Analyzing /path/to/cakephp/src/Collection/Collection.php
PHP Notice:  Undefined index: $currentIndexes[$changeIndex] in phar:///path/to/psalm-3.14.0.phar/src/Psalm/Internal/Analyzer/Statements/Block/LoopAnalyzer.php on line 216

Notice: Undefined index: $currentIndexes[$changeIndex] in phar:///path/to/psalm-3.14.0.phar/src/Psalm/Internal/Analyzer/Statements/Block/LoopAnalyzer.php on line 216
Uncaught Error: __clone method called on non-object in phar:///path/to/psalm-3.14.0.phar/src/Psalm/Internal/Analyzer/Statements/Block/LoopAnalyzer.php:216
Stack trace:
#0 phar:///path/to/psalm-3.14.0.phar/src/Psalm/Internal/Analyzer/Statements/Block/ForAnalyzer.php(59): Psalm\Internal\Analyzer\Statements\Block\LoopAnalyzer::analyze(Object(Psalm\Internal\Analyzer\StatementsAnalyzer), Array, Array, Array, Object(Psalm\Internal\Scope\LoopScope), Object(Psalm\Context))
#1 phar:///path/to/psalm-3.14.0.phar/src/Psalm/Internal/Analyzer/StatementsAnalyzer.php(307): Psalm\Internal\Analyzer\Statements\Block\ForAnalyzer::analyze(Object(Psalm\Internal\Analyzer\StatementsAnalyzer), Object(_HumbugBoxc9318a1bb87d\PhpParser\Node\Stmt\For_), Object(Psalm\Context))
#2 phar:///path/to/psalm-3.14.0.phar/src/Psalm/Internal/Analyzer/StatementsAnalyzer.php(147): Psalm\Internal\Analyzer\StatementsAnalyzer::analyzeStatement(Object(Psalm\Internal\Analyzer\StatementsAnalyzer), Object(_HumbugBoxc9318a1bb87d\PhpParser\Node\Stmt\For_), Object(Psalm\Context), NULL)
#3 phar:///path/to/psalm-3.14.0.phar/src/Psalm/Internal/Analyzer/Statements/Block/LoopAnalyzer.php(113): Psalm\Internal\Analyzer\StatementsAnalyzer->analyze(Array, Object(Psalm\Context))
#4 phar:///path/to/psalm-3.14.0.phar/src/Psalm/Internal/Analyzer/Statements/Block/WhileAnalyzer.php(42): Psalm\Internal\Analyzer\Statements\Block\LoopAnalyzer::analyze(Object(Psalm\Internal\Analyzer\StatementsAnalyzer), Array, Array, Array, Object(Psalm\Internal\Scope\LoopScope), Object(Psalm\Context))
#5 phar:///path/to/psalm-3.14.0.phar/src/Psalm/Internal/Analyzer/StatementsAnalyzer.php(315): Psalm\Internal\Analyzer\Statements\Block\WhileAnalyzer::analyze(Object(Psalm\Internal\Analyzer\StatementsAnalyzer), Object(_HumbugBoxc9318a1bb87d\PhpParser\Node\Stmt\While_), Object(Psalm\Context))
#6 phar:///path/to/psalm-3.14.0.phar/src/Psalm/Internal/Analyzer/StatementsAnalyzer.php(147): Psalm\Internal\Analyzer\StatementsAnalyzer::analyzeStatement(Object(Psalm\Internal\Analyzer\StatementsAnalyzer), Object(_HumbugBoxc9318a1bb87d\PhpParser\Node\Stmt\While_), Object(Psalm\Context), Object(Psalm\Context))
#7 phar:///path/to/psalm-3.14.0.phar/src/Psalm/Internal/Analyzer/FunctionLikeAnalyzer.php(343): Psalm\Internal\Analyzer\StatementsAnalyzer->analyze(Array, Object(Psalm\Context), Object(Psalm\Context), true)
#8 phar:///path/to/psalm-3.14.0.phar/src/Psalm/Internal/Analyzer/ClassAnalyzer.php(872): Psalm\Internal\Analyzer\FunctionLikeAnalyzer->analyze(Object(Psalm\Context), Object(Psalm\Internal\Provider\NodeDataProvider), Object(Psalm\Context))
#9 phar:///path/to/psalm-3.14.0.phar/src/Psalm/Internal/Analyzer/ClassAnalyzer.php(732): Psalm\Internal\Analyzer\ClassAnalyzer->analyzeClassMethod(Object(_HumbugBoxc9318a1bb87d\PhpParser\Node\Stmt\ClassMethod), Object(Psalm\Storage\ClassLikeStorage), Object(Psalm\Internal\Analyzer\TraitAnalyzer), Object(Psalm\Context), Object(Psalm\Context))
#10 phar:///path/to/psalm-3.14.0.phar/src/Psalm/Internal/Analyzer/ClassAnalyzer.php(358): Psalm\Internal\Analyzer\ClassAnalyzer->analyzeTraitUse(Object(Psalm\Aliases), Object(_HumbugBoxc9318a1bb87d\PhpParser\Node\Stmt\TraitUse), Object(Psalm\Internal\Analyzer\ProjectAnalyzer), Object(Psalm\Storage\ClassLikeStorage), Object(Psalm\Context), Object(Psalm\Context), NULL)
#11 phar:///path/to/psalm-3.14.0.phar/src/Psalm/Internal/Analyzer/FileAnalyzer.php(179): Psalm\Internal\Analyzer\ClassAnalyzer->analyze(Object(Psalm\Context), Object(Psalm\Context))
#12 phar:///path/to/psalm-3.14.0.phar/src/Psalm/Internal/Codebase/Analyzer.php(277): Psalm\Internal\Analyzer\FileAnalyzer->analyze(NULL)
#13 phar:///path/to/psalm-3.14.0.phar/src/Psalm/Internal/Codebase/Analyzer.php(422): Psalm\Internal\Codebase\Analyzer->Psalm\Internal\Codebase\{closure}(12, '/path/to...')
#14 phar:///path/to/psalm-3.14.0.phar/src/Psalm/Internal/Codebase/Analyzer.php(232): Psalm\Internal\Codebase\Analyzer->doAnalysis(Object(Psalm\Internal\Analyzer\ProjectAnalyzer), 1)
#15 phar:///path/to/psalm-3.14.0.phar/src/Psalm/Internal/Analyzer/ProjectAnalyzer.php(459): Psalm\Internal\Codebase\Analyzer->analyzeFiles(Object(Psalm\Internal\Analyzer\ProjectAnalyzer), 1, false, true)
#16 phar:///path/to/psalm-3.14.0.phar/src/psalm.php(473): Psalm\Internal\Analyzer\ProjectAnalyzer->check('/path/to...', false)
#17 phar:///path/to/psalm-3.14.0.phar/psalm(5): require_once('phar:///path/to...')
#18 /path/to/psalm-3.14.0.phar(14): require('phar:///path/to...')
#19 {main}
(Psalm 3.14.0@f48a362fcd5665f3938adc6ea1b5f50d2c925262 crashed due to an uncaught Throwable)
```

https://github.com/cakephp/cakephp/blob/master/src/Collection/Collection.php

**Comment by muglug** [comment]
Tagged a new release with 3.14.1
