### ISSUE TITLE
Cannot run psalm --init without `vendor` directory

### ISSUE THREAD

**Issue by matthijskooijman** [vimeo/psalm#4025]
When running `psalm --init` without a `vendor` directory (e.g. when not using composer for the project, with psalm installed with `composer global`):

```
psalm --init src/
Calculating best config level based on project files
Uncaught Psalm\Exception\ConfigException: Could not resolve config path to /home/matthijs/test//vendor in /home/matthijs/.config/composer/vendor/vimeo/psalm/src/Psalm/Config/FileFilter.php:175
Stack trace:
#0 /home/matthijs/.config/composer/vendor/vimeo/psalm/src/Psalm/Config/ProjectFileFilter.php(27): Psalm\Config\FileFilter::loadFromXMLElement()
#1 /home/matthijs/.config/composer/vendor/vimeo/psalm/src/Psalm/Config/ProjectFileFilter.php(35): Psalm\Config\ProjectFileFilter::loadFromXMLElement()
#2 /home/matthijs/.config/composer/vendor/vimeo/psalm/src/Psalm/Config.php(952): Psalm\Config\ProjectFileFilter::loadFromXMLElement()
#3 /home/matthijs/.config/composer/vendor/vimeo/psalm/src/Psalm/Config.php(721): Psalm\Config::fromXmlAndPaths()
#4 /home/matthijs/.config/composer/vendor/vimeo/psalm/src/Psalm/Config/Creator.php(85): Psalm\Config::loadFromXML()
#5 /home/matthijs/.config/composer/vendor/vimeo/psalm/src/psalm.php(344): Psalm\Config\Creator::createBareConfig()
#6 /home/matthijs/.config/composer/vendor/vimeo/psalm/psalm(2): require_once('/home/matthijs/...')
#7 {main}
(Psalm 3.14.1@9822043ca46d6682b76097bfa97d7c450eef9e90 crashed due to an uncaught Throwable)
```

When I create an empty `vendor` directory, the following `psalm.xml` is created:

```
<?xml version="1.0"?>
<psalm
    errorLevel="3"
    resolveFromConfigFile="true"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns="https://getpsalm.org/schema/config"
    xsi:schemaLocation="https://getpsalm.org/schema/config vendor/vimeo/psalm/config.xsd"
>
    <projectFiles>
        <directory name="src/" />
        <ignoreFiles>
            <directory name="vendor" />
        </ignoreFiles>
    </projectFiles>
</psalm>
```

When I then remove the `vendor` directory again and run psalm normally, I get essentially the same error.

```
matthijs@grubby:~/test$ psalm
Problem parsing /home/matthijs/test/psalm.xml:
  Could not resolve config path to /home/matthijs/test//vendor
```

Removing the `ignoreFiles` section from `psalm.xml` fixes this error and allows running psalm normally, it seems.

This make me suspect the error during `--init` is only caused because it unconditionally tries to ignore the `vendor` directory. Maybe a simple fix would be to only apply this ignore when the directory actually exists?

**Comment by simPod** [comment]
This happens to me even with vendor installed.

1. https://github.com/simPod/php-bugs/tree/psalm-cannot-init
2. `composer install`
3. `vendor/bin/psalm --init`
4. `Uncaught Psalm\Exception\ConfigException: Could not resolve config path to /fullpath/php-bugs//src in /Users/user/Work/php-bugs/vendor/vimeo/psalm/src/Psalm/Config/FileFilter.php:175

**Comment by matthijskooijman** [comment]
That seems to be a subtly different problem: Apparently `psalm --init` assumes that here is a `src/` directory containing the sources, but you don't have that. Arguably your error is by design and to expected, given the `--help` docs for `--init` say:

```
    -i, --init [source_dir=src] [level=3]
        Create a psalm config file in the current directory that points to [source_dir]       
        at the required level, from 1, most strict, to 8, most permissive.
```

So by not specifying any `source_dir` argument, you're using the default of `src`, so you must then probably ensure that it actually exists. Running `psalm --init .` would probably work in your case.

**Comment by TysonAndre** [comment]
Separately from `--init`, it'd potentially be useful to run psalm without a vendor directory, if the project really didn't have any configured autoloaders (e.g. a collection of shell scripts).

This patch is similar to an incomplete one I had in a fork, so that I could easily run psalm on self-contained projects

```patch
--- a/src/command_functions.php
+++ b/src/command_functions.php
@@ -41,12 +41,13 @@ use function strtoupper;
  * @param  string $current_dir
  * @param  bool   $has_explicit_root
  * @param  string $vendor_dir
+ * @param  bool   $skipAutoloaderCheck
  *
  * @return ?\Composer\Autoload\ClassLoader
  */
-function requireAutoloaders($current_dir, $has_explicit_root, $vendor_dir)
+function requireAutoloaders($current_dir, $has_explicit_root, $vendor_dir, $skip_autoloader_check = false)
 {
-    $autoload_roots = [$current_dir];
+    $autoload_roots = $skip_autoloader_check ? [] : [$current_dir];
 
     $psalm_dir = dirname(__DIR__);
 
@@ -423,6 +424,9 @@ Miscellaneous:
     -h, --help
         Display this help message
 
+    --no-vendor-autoloader
+        Set this option to allow Psalm to run when vendor/autoload.php doesn't exist (e.g. for analyzing standalone scripts).
+
     -v, --version
         Display the Psalm version

--- a/src/psalm.php
+++ b/src/psalm.php
@@ -98,6 +98,7 @@ $valid_long_options = [
     'monochrome',
     'no-cache',
     'no-reflection-cache',
+    'no-vendor-autoloader',
     'no-file-cache',
     'output-format:',
     'plugin:',
@@ -278,7 +280,7 @@ require_once __DIR__ . '/' . 'Psalm/Internal/IncludeCollector.php';
 $include_collector = new IncludeCollector();
 $first_autoloader = $include_collector->runAndCollect(
     function () use ($current_dir, $options, $vendor_dir) {
-        return requireAutoloaders($current_dir, isset($options['r']), $vendor_dir);
+        return requireAutoloaders($current_dir, isset($options['r']), $vendor_dir, isset($options['no-vendor-autoloader']));
     }
 );
 ```

And repeat for other scripts like src/psalter.php, src/psalm-language-server.php, etc.

**Comment by matthijskooijman** [comment]
Hm, in my experience, psalm already runs (but not `--init`s) without a vendor directory, but only when there are no `composer.json` / `composer.lock` files?

**Comment by TysonAndre** [comment]
> Hm, in my experience, psalm already runs (but not --inits) without a vendor directory, but only when there are no composer.json / composer.lock files?

It checks for composer.json, apparently. I didn't realize it was doing that - the **stub** project in question had a composer.json but no psr-4 config or dependencies, so I didn't think whether or not it was installed would matter, but it does.

```php
        if (!$has_autoloader && file_exists($autoload_root . '/composer.json')) {
            $error_message = 'Could not find any composer autoloaders in ' . $autoload_root;

            if (!$has_explicit_root) {
                $error_message .= PHP_EOL . 'Add a --root=[your/project/directory] flag '
                    . 'to specify a particular project to run Psalm on.';
            }

            fwrite(STDERR, $error_message . PHP_EOL);
            exit(1);
        }
```

The patch doesn't help here, because `--init` parses arguments completely differently and doesn't even allow passing arguments before --init - psalm still crashes

**Comment by thomasbley** [comment]
Would be great to run:

```
// no init, no composer, assume level 1 by default, etc.
php psalm.phar test.php
or:
php psalm.phar --autoloader=vendor/autoload.php ./
```
