### ISSUE TITLE
Exception with latest release

### ISSUE THREAD

**Issue by dereuromark** [vimeo/psalm#4111]
```
Uncaught UnexpectedValueException: $storage should not be null for Zend\Filter\Word\CamelCaseToDash::__invoke in phar:///home/travis/build/spryker/suite-nonsplit/vendor/psalm/phar/psalm.phar/src/Psalm/Internal/Codebase/Methods.php:645

Stack trace:

#0 phar:///home/travis/build/spryker/suite-nonsplit/vendor/psalm/phar/psalm.phar/src/Psalm/Internal/Type/Comparator/CallableTypeComparator.php(196): Psalm\Internal\Codebase\Methods->getStorage(Object(Psalm\Internal\MethodIdentifier))

#1 phar:///home/travis/build/spryker/suite-nonsplit/vendor/psalm/phar/psalm.phar/src/Psalm/Internal/Type/Comparator/CallableTypeComparator.php(139): Psalm\Internal\Type\Comparator\CallableTypeComparator::getCallableFromAtomic(Object(Psalm\Codebase), Object(Psalm\Type\Atomic\TNamedObject), Object(Psalm\Type\Atomic\TCallable))

#2 phar:///home/travis/build/spryker/suite-nonsplit/vendor/psalm/phar/psalm.phar/src/Psalm/Internal/Type/Comparator/AtomicTypeComparator.php(255): Psalm\Internal\Type\Comparator\CallableTypeComparator::isNotExplicitlyCallableTypeCallable(Object(Psalm\Codebase), Object(Psalm\Type\Atomic\TNamedObject), Object(Psalm\Type\Atomic\TCallable), Object(Psalm\Internal\Type\Comparator\TypeComparisonResult))

#3 phar:///home/travis/build/spryker/suite-nonsplit/vendor/psalm/phar/psalm.phar/src/Psalm/Internal/Type/Comparator/UnionTypeComparator.php(71): Psalm\Internal\Type\Comparator\AtomicTypeComparator::isContainedBy(Object(Psalm\Codebase), Object(Psalm\Type\Atomic\TNamedObject), Object(Psalm\Type\Atomic\TCallable), false, true, Object(Psalm\Internal\Type\Comparator\TypeComparisonResult))

#4 phar:///home/travis/build/spryker/suite-nonsplit/vendor/psalm/phar/psalm.phar/src/Psalm/Internal/Analyzer/Statements/Expression/Call/ArgumentAnalyzer.php(282): Psalm\Internal\Type\Comparator\UnionTypeComparator::isContainedBy(Object(Psalm\Codebase), Object(Psalm\Type\Union), Object(Psalm\Type\Union), true, true, Object(Psalm\Internal\Type\Comparator\TypeComparisonResult))

#5 phar:///home/travis/build/spryker/suite-nonsplit/vendor/psalm/phar/psalm.phar/src/Psalm/Internal/Analyzer/Statements/Expression/Call/ArgumentAnalyzer.php(210): Psalm\Internal\Analyzer\Statements\Expression\Call\ArgumentAnalyzer::verifyType(Object(Psalm\Internal\Analyzer\StatementsAnalyzer), Object(Psalm\Type\Union), Object(Psalm\Type\Union), NULL, 'Zend\\Filter\\Fil...', 0, Object(Psalm\CodeLocation), Object(_HumbugBoxc22010bd12b9\PhpParser\Node\Expr\New_), Object(Psalm\Context), Object(Psalm\Storage\FunctionLikeParameter), false, NULL, false, false, Object(Psalm\CodeLocation))
```

**Comment by muglug** [comment]
Do you still get the error when running without the Phar? All that code in `CallableTypeComparator` is wrapped in a try/catch block, so this is at little mystifying

**Comment by weirdan** [comment]
> All that code in CallableTypeComparator is wrapped in a try/catch block

Is it? The exception comes from here: 

https://github.com/vimeo/psalm/blob/73f6fcde48b3970ea750c8806158fcde9e0ee2ea/src/Psalm/Internal/Type/Comparator/CallableTypeComparator.php#L202

and it doesn't seem to be wrapped into try/catch.

**Comment by muglug** [comment]
Really? Not https://github.com/vimeo/psalm/blob/73f6fcde48b3970ea750c8806158fcde9e0ee2ea/src/Psalm/Internal/Type/Comparator/CallableTypeComparator.php#L196?

**Comment by weirdan** [comment]
Nope. The code in phar has a lot of empty lines stripped and multi-line calls collapsed to single line. So the line 196 in phar corresponds to this: https://github.com/vimeo/psalm/blob/73f6fcde48b3970ea750c8806158fcde9e0ee2ea/src/Psalm/Internal/Type/Comparator/CallableTypeComparator.php#L323

and line 139 (one stack frame above that) - to this: https://github.com/vimeo/psalm/blob/73f6fcde48b3970ea750c8806158fcde9e0ee2ea/src/Psalm/Internal/Type/Comparator/CallableTypeComparator.php#L202

You can unpack the phar file with `phar extract -f psalm.phar` if you're interested.

**Comment by muglug** [comment]
> You can unpack the phar file with phar extract -f psalm.phar if you're interested.

Oh awesome, did not know about this

**Comment by muglug** [comment]
@dereuromark are you running PHP 7.1 by any chance?

**Comment by muglug** [comment]
Yeah, this was fixed in PHP 7.2.19: https://bugs.php.net/bug.php?id=75186

**Comment by dereuromark** [comment]
7.2

**Comment by drupol** [comment]
Thanks @muglug !
