### ISSUE TITLE
Uncaught UnexpectedValueException in CallableTypeComparator.php

### ISSUE THREAD

**Issue by lksnmnn** [vimeo/psalm#4233]
Hi there,

Psalm is crashing on my project, which uses this SDK to connect to Azure's Blob Storage: https://github.com/Azure/azure-storage-php/tree/master/azure-storage-blob
 
**Exception**

```
Uncaught UnexpectedValueException: $storage should not be null for MicrosoftAzure\Storage\Common\Middlewares\RetryMiddleware::__invoke in <path_to>/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Methods.php:1034
Stack trace:
#0 <path_to>/vendor/vimeo/psalm/src/Psalm/Internal/Type/Comparator/CallableTypeComparator.php(327): Psalm\Internal\Codebase\Methods->getStorage(Object(Psalm\Internal\MethodIdentifier))
1 <path_to>/vendor/vimeo/psalm/src/Psalm/Internal/Type/Comparator/CallableTypeComparator.php(202): Psalm\Internal\Type\Comparator\CallableTypeComparator::getCallableFromAtomic(Object(Psalm\Codebase), Object(Psalm\Type\Atomic\TNamedObject), Object(Psalm\Type\Atomic\TCallable))
#2 <path_to>/vendor/vimeo/psalm/src/Psalm/Internal/Type/Comparator/AtomicTypeComparator.php(547): Psalm\Internal\Type\Comparator\CallableTypeComparator::isNotExplicitlyCallableTypeCallable(Object(Psalm\Codebase), Object(Psalm\Type\Atomic\TNamedObject), Object(Psalm\Type\Atomic\TCallable), Object(Psalm\Internal\Type\Comparator\TypeComparisonResult))
#3 <path_to>/vendor/vimeo/psalm/src/Psalm/Internal/Type/Comparator/UnionTypeComparator.php(106): Psalm\Internal\Type\Comparator\AtomicTypeComparator::isContainedBy(Object(Psalm\Codebase), Object(Psalm\Type\Atomic\TNamedObject), Object(Psalm\Type\Atomic\TCallable), false, true, Object(Psalm\Internal\Type\Comparator\TypeComparisonResult))
#4 <path_to>/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/Statements/Expression/Call/ArgumentAnalyzer.php(667): Psalm\Internal\Type\Comparator\UnionTypeComparator::isContainedBy(Object(Psalm\Codebase), Object(Psalm\Type\Union), Object(Psalm\Type\Union), true, true, Object(Psalm\Internal\Type\Comparator\TypeComparisonResult))
#5 <path_to>/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/Statements/Expression/Call/ArgumentAnalyzer.php(451): Psalm\Internal\Analyzer\Statements\Expression\Call\ArgumentAnalyzer::verifyType(Object(Psalm\Internal\Analyzer\StatementsAnalyzer), Object(Psalm\Type\Union), Object(Psalm\Type\Union), NULL, 'MicrosoftAzure\\...', 0, Object(Psalm\CodeLocation), Object(PhpParser\Node\Expr\Variable), Object(Psalm\Context), Object(Psalm\Storage\FunctionLikeParameter), false, NULL, false, false, Object(Psalm\CodeLocation))
#6 <path_to>/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/Statements/Expression/Call/ArgumentAnalyzer.php(166): Psalm\Internal\Analyzer\Statements\Expression\Call\ArgumentAnalyzer::checkFunctionLikeTypeMatches(Object(Psalm\Internal\Analyzer\StatementsAnalyzer), Object(Psalm\Codebase), 'MicrosoftAzure\\...', 'MicrosoftAzure\\...', 'MicrosoftAzure\\...', Object(Psalm\CodeLocation), Object(Psalm\Storage\FunctionLikeParameter), Object(Psalm\Type\Union), 0, Object(PhpParser\Node\Arg), Object(Psalm\Context), Array, NULL, false, false)
#7 <path_to>/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/Statements/Expression/Call/ArgumentsAnalyzer.php(662): Psalm\Internal\Analyzer\Statements\Expression\Call\ArgumentAnalyzer::checkArgumentMatches(Object(Psalm\Internal\Analyzer\StatementsAnalyzer), 'MicrosoftAzure\\...', 'MicrosoftAzure\\...', 'MicrosoftAzure\\...', Object(Psalm\CodeLocation), Object(Psalm\Storage\FunctionLikeParameter), 0, Object(PhpParser\Node\Arg), Object(Psalm\Type\Union), Object(Psalm\Context), Array, NULL, false, false)
#8 <path_to>/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/Statements/Expression/CallAnalyzer.php(312): Psalm\Internal\Analyzer\Statements\Expression\Call\ArgumentsAnalyzer::checkArgumentsMatch(Object(Psalm\Internal\Analyzer\StatementsAnalyzer), Array, Object(Psalm\Internal\MethodIdentifier), Array, Object(Psalm\Storage\MethodStorage), Object(Psalm\Storage\ClassLikeStorage), Object(Psalm\Internal\Type\TemplateResult), Object(Psalm\CodeLocation), Object(Psalm\Context))
#9 <path_to>/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/Statements/Expression/Call/Method/AtomicMethodCallAnalyzer.php(665): Psalm\Internal\Analyzer\Statements\Expression\CallAnalyzer::checkMethodArgs(Object(Psalm\Internal\MethodIdentifier), Array, Object(Psalm\Internal\Type\TemplateResult), Object(Psalm\Context), Object(Psalm\CodeLocation), Object(Psalm\Internal\Analyzer\StatementsAnalyzer))
#10 <path_to>/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/Statements/Expression/Call/MethodCallAnalyzer.php(168): Psalm\Internal\Analyzer\Statements\Expression\Call\Method\AtomicMethodCallAnalyzer::analyze(Object(Psalm\Internal\Analyzer\StatementsAnalyzer), Object(PhpParser\Node\Expr\MethodCall), Object(Psalm\Codebase), Object(Psalm\Context), Object(Psalm\Type\Atomic\TNamedObject), Object(Psalm\Type\Atomic\TNamedObject), false, '$this->client', Object(Psalm\Internal\Analyzer\Statements\Expression\Call\Method\AtomicMethodCallAnalysisResult))
#11 <path_to>/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/Statements/ExpressionAnalyzer.php(144): Psalm\Internal\Analyzer\Statements\Expression\Call\MethodCallAnalyzer::analyze(Object(Psalm\Internal\Analyzer\StatementsAnalyzer), Object(PhpParser\Node\Expr\MethodCall), Object(Psalm\Context))
#12 <path_to>/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/Statements/ExpressionAnalyzer.php(39): Psalm\Internal\Analyzer\Statements\ExpressionAnalyzer::handleExpression(Object(Psalm\Internal\Analyzer\StatementsAnalyzer), Object(PhpParser\Node\Expr\MethodCall), Object(Psalm\Context), false, Object(Psalm\Context), true)
#13 <path_to>/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/StatementsAnalyzer.php(483): Psalm\Internal\Analyzer\Statements\ExpressionAnalyzer::analyze(Object(Psalm\Internal\Analyzer\StatementsAnalyzer), Object(PhpParser\Node\Expr\MethodCall), Object(Psalm\Context), false, Object(Psalm\Context), true)
#14 <path_to>/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/StatementsAnalyzer.php(164): Psalm\Internal\Analyzer\StatementsAnalyzer::analyzeStatement(Object(Psalm\Internal\Analyzer\StatementsAnalyzer), Object(PhpParser\Node\Stmt\Expression), Object(Psalm\Context), Object(Psalm\Context))
#15 <path_to>/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/FunctionLikeAnalyzer.php(591): Psalm\Internal\Analyzer\StatementsAnalyzer->analyze(Array, Object(Psalm\Context), Object(Psalm\Context), true)
#16 <path_to>/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/ClassAnalyzer.php(1897): Psalm\Internal\Analyzer\FunctionLikeAnalyzer->analyze(Object(Psalm\Context), Object(Psalm\Internal\Provider\NodeDataProvider), Object(Psalm\Context))
#17 <path_to>/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/ClassAnalyzer.php(734): Psalm\Internal\Analyzer\ClassAnalyzer->analyzeClassMethod(Object(PhpParser\Node\Stmt\ClassMethod), Object(Psalm\Storage\ClassLikeStorage), Object(Psalm\Internal\Analyzer\ClassAnalyzer), Object(Psalm\Context), Object(Psalm\Context))
#18 <path_to>/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/FileAnalyzer.php(215): Psalm\Internal\Analyzer\ClassAnalyzer->analyze(Object(Psalm\Context), Object(Psalm\Context))
#19 <path_to>/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Analyzer.php(336): Psalm\Internal\Analyzer\FileAnalyzer->analyze(NULL)
#20 <path_to>/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Analyzer.php(576): Psalm\Internal\Codebase\Analyzer->Psalm\Internal\Codebase\{closure}(0, '...')
#21 <path_to>/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Analyzer.php(268): Psalm\Internal\Codebase\Analyzer->doAnalysis(Object(Psalm\Internal\Analyzer\ProjectAnalyzer), 1)
#22 <path_to>/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/ProjectAnalyzer.php(639): Psalm\Internal\Codebase\Analyzer->analyzeFiles(Object(Psalm\Internal\Analyzer\ProjectAnalyzer), 1, false, true)
#23 <path_to>/vendor/vimeo/psalm/src/psalm.php(677): Psalm\Internal\Analyzer\ProjectAnalyzer->check('...', false)
#24 <path_to>/vendor/vimeo/psalm/psalm(2): require_once('...')
#25 {main}
(Psalm 3.16@d03e5ef057d6adc656c0ff7e166c50b73b4f48f3 crashed due to an uncaught Throwable)
```

Edit: It seems to go wrong when calling the following code:
`$retry_middleware = RetryMiddlewareFactory::create(RetryMiddlewareFactory::GENERAL_RETRY_TYPE, 5, 1);`

Please let me know if you need additional info's. Using the `--debug` and `--debug-by-lines` flags did not yield any more insight.

Cheers,
Lukas

**Comment by lksnmnn** [comment]
No.

**Comment by weirdan** [comment]
Mind running with `--debug --debug-by-line` switches? It'll produce a lot of output, so you may want to redirect the output to a file and upload the resulting file.

**Comment by muglug** [comment]
What exact version of PHP are you running Psalm under?

**Comment by lksnmnn** [comment]
I am using PHP v7.3.22. I'll attach the `debug` and `debug-by-line` output tomorrow.

**Comment by merlindiavova** [comment]
Hey I'm having the same trouble but with [Aura Di](https://github.com/auraphp/Aura.Di) ([Aura\Di\Injection\LazyNew::__invoke](https://github.com/auraphp/Aura.Di/blob/4.x/src/Injection/LazyNew.php))

Please see the attached `debug` and `debug-by-line`

[psalm_debug.txt](https://github.com/vimeo/psalm/files/5294661/psalm_debug.txt)

```sh
PHP 7.4.10 (cli) (built: Sep  9 2020 06:36:30) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.10, Copyright (c), by Zend Technologies
    with Xdebug v2.9.6, Copyright (c) 2002-2020, by Derick Rethans
```

**Comment by merlindiavova** [comment]
Seems to work just fine on dev-master

**Comment by lksnmnn** [comment]
I am able to confirm, that this issue is not occuring on `dev-master`.

**Comment by muglug** [comment]
I assume this is the same bug as https://github.com/vimeo/psalm/issues/4210, given it doesn't occur on master
