### ISSUE TITLE
Generating baseline file fails when PluginIssue child is anonymous class

### ISSUE THREAD

**Issue by janedbal** [vimeo/psalm#4284]
Hi,
I created simple custom rule which adds anonymous child of PluginIssue to IssueBuffer like this:

```php
class SomeCustomChecker implements AfterClassLikeAnalysisInterface
{

    public static function afterStatementAnalysis(
        ClassLike $classLike,
        ClassLikeStorage $classlikeStorage,
        StatementsSource $statementsSource,
        Codebase $codebase,
        array &$fileReplacements = []
    ) {
            IssueBuffer::add(new class('Some msg', new CodeLocation($statementsSource, $classLike, null, true)) extends PluginIssue {});
    }
}
```

When trying to generate baseline, psalm fails:

```bash
$ vendor/bin/psalm --set-baseline=psalm.baseline.xml
Scanning files...
Analyzing files...

Writing error baseline to file...                                               
Uncaught DOMException: Invalid Character Error in /app/vendor/vimeo/psalm/src/Psalm/ErrorBaseline.php:280
Stack trace:
#0 /app/vendor/vimeo/psalm/src/Psalm/ErrorBaseline.php(280): DOMDocument->createElement('class@anonymous...')
#1 /app/vendor/vimeo/psalm/src/Psalm/ErrorBaseline.php(71): Psalm\ErrorBaseline::writeToFile(Object(Psalm\Internal\Provider\FileProvider), 'psalm.baseline....', Array, false)
#2 /app/vendor/vimeo/psalm/src/psalm.php(699): Psalm\ErrorBaseline::create(Object(Psalm\Internal\Provider\FileProvider), 'psalm.baseline....', Array, false)
#3 /app/vendor/vimeo/psalm/psalm(2): require_once('/app/vendor/vim...')
#4 {main}
(Psalm 3.15@de6e7f324f44dde540ebe7ebd4eb481b97c86f30 crashed due to an uncaught Throwable)
```

Problem disappears if I do not use anonymous class.

**Comment by janedbal** [comment]
No, as I cannot configure the custom checker there.

**Comment by weirdan** [comment]
I don't think this can be supported, as Psalm identifies issues by the class name.
