### ISSUE TITLE
Fatal Error when using functions from composer auto included files inside namespace

### ISSUE THREAD

**Issue by maxarvidsson** [vimeo/psalm#436]
Small example to reproduce (with psalm globally installed)

src/autoload.php
``` 
<?php

/**
 * @return void
 */
function foo()
{
    echo "Hello, World\n";
}
```
src/main.php 
```
<?php

namespace Test;

require __DIR__ . '/../vendor/autoload.php';

foo();
```
composer.json 
```
{
    "autoload": {
        "files": [
            "src/autoload.php"
        ]
    }
}
```
To test and setup composer/psalm
```
$ composer dump-autoload
Generating autoload files
$ php src/main.php 
Hello, World
$ psalm --init
Config file created successfully. Please re-run psalm.
```
Finally, running psalm gives PHP Fatal Error
```
$ psalm
PHP Fatal error:  Uncaught exception 'UnexpectedValueException' with message 'Expecting test\foo to have storage in /home/max/php/psalm3/src/main.php' in /home/max/.composer/vendor/vimeo/psalm/src/Psalm/Checker/FunctionChecker.php:116
Stack trace:
#0 /home/max/.composer/vendor/vimeo/psalm/src/Psalm/Checker/Statements/Expression/CallChecker.php(286): Psalm\Checker\FunctionChecker::getStorage(Object(Psalm\Checker\StatementsChecker), 'test\\foo')
#1 /home/max/.composer/vendor/vimeo/psalm/src/Psalm/Checker/Statements/ExpressionChecker.php(220): Psalm\Checker\Statements\Expression\CallChecker::analyzeFunctionCall(Object(Psalm\Checker\ProjectChecker), Object(Psalm\Checker\StatementsChecker), Object(PhpParser\Node\Expr\FuncCall), Object(Psalm\Context))
#2 /home/max/.composer/vendor/vimeo/psalm/src/Psalm/Checker/StatementsChecker.php(348): Psalm\Checker\Statements\ExpressionChecker::analyze(Object(Psalm\Checker\StatementsChecker), Object(PhpParser\Node\Expr\FuncCall), Object(Psalm\Context))
#3 /home/max/.composer/vendor/vimeo/psalm/sr in /home/max/.composer/vendor/vimeo/psalm/src/Psalm/Checker/FunctionChecker.php on line 116

Fatal error: Uncaught exception 'UnexpectedValueException' with message 'Expecting test\foo to have storage in /home/max/php/psalm3/src/main.php' in /home/max/.composer/vendor/vimeo/psalm/src/Psalm/Checker/FunctionChecker.php:116
Stack trace:
#0 /home/max/.composer/vendor/vimeo/psalm/src/Psalm/Checker/Statements/Expression/CallChecker.php(286): Psalm\Checker\FunctionChecker::getStorage(Object(Psalm\Checker\StatementsChecker), 'test\\foo')
#1 /home/max/.composer/vendor/vimeo/psalm/src/Psalm/Checker/Statements/ExpressionChecker.php(220): Psalm\Checker\Statements\Expression\CallChecker::analyzeFunctionCall(Object(Psalm\Checker\ProjectChecker), Object(Psalm\Checker\StatementsChecker), Object(PhpParser\Node\Expr\FuncCall), Object(Psalm\Context))
#2 /home/max/.composer/vendor/vimeo/psalm/src/Psalm/Checker/StatementsChecker.php(348): Psalm\Checker\Statements\ExpressionChecker::analyze(Object(Psalm\Checker\StatementsChecker), Object(PhpParser\Node\Expr\FuncCall), Object(Psalm\Context))
#3 /home/max/.composer/vendor/vimeo/psalm/sr in /home/max/.composer/vendor/vimeo/psalm/src/Psalm/Checker/FunctionChecker.php on line 116
```

**Comment by muglug** [comment]
Script to repro:
```bash
mkdir src
touch src/foo.php
echo "<?php function foo() : void { echo 'Hi'; }" >> src/foo.php
touch src/main.php
echo "<?php namespace Test; require __DIR__ . '/../vendor/autoload.php'; foo();" >> src/main.php
touch composer.json
echo '{"autoload":{"files":["src/foo.php"]}}' >> composer.json
composer require --dev vimeo/psalm:dev-master
vendor/bin/psalm --init
vendor/bin/psalm
```

**Comment by muglug** [comment]
You can mitigate this by adding a leading `\` to the function call

**Comment by muglug** [comment]
Fixed in latest – let me know if it works for you. Thanks for a great testcase!

**Comment by maxarvidsson** [comment]
Looks like it is working again, thank you!
