### ISSUE TITLE
Uncaught InvalidArgumentException: Could not get class storage for ...

### ISSUE THREAD

**Issue by BenMorel** [vimeo/psalm#4407]
Almost 1 time out of 2, when I run Psalm, I get this error:

```
$ vendor/bin/psalm
Scanning files...
Analyzing files...

Uncaught InvalidArgumentException: Could not get class storage for example\view\activityview in /home/benjamin/Projects/example.com/vendor/vimeo/psalm/src/Psalm/Internal/Provider/ClassLikeStorageProvider.php:42
Stack trace:
#0 /home/benjamin/Projects/example.com/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/Statements/Expression/Call/Method/AtomicMethodCallAnalyzer.php(162): Psalm\Internal\Provider\ClassLikeStorageProvider->get()
#1 /home/benjamin/Projects/example.com/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/Statements/Expression/Call/MethodCallAnalyzer.php(182): Psalm\Internal\Analyzer\Statements\Expression\Call\Method\AtomicMethodCallAnalyzer::analyze()
#2 /home/benjamin/Projects/example.com/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/Statements/ExpressionAnalyzer.php(144): Psalm\Internal\Analyzer\Statements\Expression\Call\MethodCallAnalyzer::analyze()
#3 /home/benjamin/Projects/example.com/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/Statements/ExpressionAnalyzer.php(39): Psalm\Internal\Analyzer\Statements\ExpressionAnalyzer::handleExpression()
#4 /home/benjamin/Projects/example.com/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/Statements/Expression/AssignmentAnalyzer.php(194): Psalm\Internal\Analyzer\Statements\ExpressionAnalyzer::analyze()
#5 /home/benjamin/Projects/example.com/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/Statements/ExpressionAnalyzer.php(125): Psalm\Internal\Analyzer\Statements\Expression\AssignmentAnalyzer::analyze()
#6 /home/benjamin/Projects/example.com/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/Statements/ExpressionAnalyzer.php(39): Psalm\Internal\Analyzer\Statements\ExpressionAnalyzer::handleExpression()
#7 /home/benjamin/Projects/example.com/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/StatementsAnalyzer.php(519): Psalm\Internal\Analyzer\Statements\ExpressionAnalyzer::analyze()
#8 /home/benjamin/Projects/example.com/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/StatementsAnalyzer.php(169): Psalm\Internal\Analyzer\StatementsAnalyzer::analyzeStatement()
#9 /home/benjamin/Projects/example.com/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/Statements/Block/LoopAnalyzer.php(202): Psalm\Internal\Analyzer\StatementsAnalyzer->analyze()
#10 /home/benjamin/Projects/example.com/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/Statements/Block/ForeachAnalyzer.php(304): Psalm\Internal\Analyzer\Statements\Block\LoopAnalyzer::analyze()
#11 /home/benjamin/Projects/example.com/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/StatementsAnalyzer.php(479): Psalm\Internal\Analyzer\Statements\Block\ForeachAnalyzer::analyze()
#12 /home/benjamin/Projects/example.com/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/StatementsAnalyzer.php(169): Psalm\Internal\Analyzer\StatementsAnalyzer::analyzeStatement()
#13 /home/benjamin/Projects/example.com/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/FileAnalyzer.php(188): Psalm\Internal\Analyzer\StatementsAnalyzer->analyze()
#14 /home/benjamin/Projects/example.com/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Analyzer.php(341): Psalm\Internal\Analyzer\FileAnalyzer->analyze()
#15 /home/benjamin/Projects/example.com/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Analyzer.php(580): Psalm\Internal\Codebase\Analyzer->Psalm\Internal\Codebase\{closure}()
#16 /home/benjamin/Projects/example.com/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Analyzer.php(270): Psalm\Internal\Codebase\Analyzer->doAnalysis()
#17 /home/benjamin/Projects/example.com/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/ProjectAnalyzer.php(634): Psalm\Internal\Codebase\Analyzer->analyzeFiles()
#18 /home/benjamin/Projects/example.com/vendor/vimeo/psalm/src/psalm.php(675): Psalm\Internal\Analyzer\ProjectAnalyzer->check()
#19 /home/benjamin/Projects/example.com/vendor/vimeo/psalm/psalm(2): require_once('/home/benjamin/...')
#20 {main}
(Psalm 4.0.1@b1e2e30026936ef8d5bf6a354d1c3959b6231f44 crashed due to an uncaught Throwable)
```

A `vendor/bin/psalm --clear-cache` always fixes the issue, but it gets really annoying.

Any idea what could be causing this?

**Comment by muglug** [comment]
@BenMorel almost certainly related to diffing.

Run with `--no-diff` to fix this for now

To diagnose the issue, please run with `--debug-by-line` and update the ticket with the code that triggered this exception

**Comment by BenMorel** [comment]
With `--debug-by-line`:

```
...
Have populated RecursiveIterator
Have populated UnderflowException
Have populated OutOfRangeException
ClassLikeStorage is populated
FileStorage is populating
FileStorage is populated
Finished registering stub files
Analyzing files...
Getting /home/benjamin/Projects/example.com/src/View/ActivityView.phtml
Analyzing /home/benjamin/Projects/example.com/src/View/ActivityView.phtml
/home/benjamin/Projects/example.com/src/View/ActivityView.phtml:1
/home/benjamin/Projects/example.com/src/View/ActivityView.phtml:2
/home/benjamin/Projects/example.com/src/View/ActivityView.phtml:8
/home/benjamin/Projects/example.com/src/View/ActivityView.phtml:10
/home/benjamin/Projects/example.com/src/View/ActivityView.phtml:11
/home/benjamin/Projects/example.com/src/View/ActivityView.phtml:11
Uncaught InvalidArgumentException: Could not get class storage for example\view\activityview in /home/benjamin/Projects/example.com/vendor/vimeo/psalm/src/Psalm/Internal/Provider/ClassLikeStorageProvider.php:42
Stack trace:
...
```

ActivityView.phtml:11 is the last line here:

```php
<div class="activities">
    <?php foreach ($this->activities as $activity): ?>
        <?php $showCommentFormByDefault = $this->showCommentFormByDefault($activity); ?>
```

**Comment by arjenm** [comment]
This issue occurs in 3.18.2 as well and did not in 3.17.2

**Comment by BenMorel** [comment]
The issue in question: #4419.

**Comment by muglug** [comment]
@BenMorel how does Psalm know what `$this` is in the template?

**Comment by muglug** [comment]
if it's via `@psalm-scope-this`, I see what the bug is

**Comment by BenMorel** [comment]
@muglug It's via `@var`. First two lines of the view script:

```php
<?php declare(strict_types=1); ?>
<?php /** @var Example\View\ActivityView $this */ ?>
```

**Comment by muglug** [comment]
what's the _next_ line?

**Comment by muglug** [comment]
never mind, the issue is that Psalm doesn't currently expect `@var` types to be set like that (in self-enclosed PHP blocks).

**Comment by BenMorel** [comment]
Thank you! Looking forward to the next release :+1:

**Comment by olleharstedt** [comment]
Hm, I'm having this problem with Joomla. Trying to ignore it without success.

**Comment by orklah** [comment]
Please create a new issue with a reproducer. This error can have a lot of causes
