### ISSUE TITLE
InvalidArgumentException when adding class alias

### ISSUE THREAD

**Issue by othercorey** [vimeo/psalm#4462]
I'm not sure how to reproduce this in the sandbox since it requires 2 files.

We had a class `Cake\Core\Exception\Exception` that we moved to `Cake\Core\Exception\CoreException`.

In CoreException.php (after the class declaration):

`class_alias('Cake\Core\Exception\CoreException', 'Cake\Core\Exception\Exception');`

In Exception.php:

`class_exists('Cake\Core\Exception\CoreException');`

```
Uncaught InvalidArgumentException: Could not get class storage for cake\core\exception\exception in phar:///home/runner/work/cakephp/cakephp/vendor/psalm/phar/psalm.phar/src/Psalm/Internal/Provider/ClassLikeStorageProvider.php:38
Stack trace:
#0 phar:///home/runner/work/cakephp/cakephp/vendor/psalm/phar/psalm.phar/src/Psalm/Internal/Analyzer/Statements/Expression/Call/StaticCallAnalyzer.php(71): Psalm\Internal\Provider\ClassLikeStorageProvider->get('Cake\\Core\\Excep...')
#1 phar:///home/runner/work/cakephp/cakephp/vendor/psalm/phar/psalm.phar/src/Psalm/Internal/Analyzer/Statements/ExpressionAnalyzer.php(76): Psalm\Internal\Analyzer\Statements\Expression\Call\StaticCallAnalyzer::analyze(Object(Psalm\Internal\Analyzer\StatementsAnalyzer), Object(_HumbugBoxc0bfaad63871\PhpParser\Node\Expr\StaticCall), Object(Psalm\Context))
#2 phar:///home/runner/work/cakephp/cakephp/vendor/psalm/phar/psalm.phar/src/Psalm/Internal/Analyzer/Statements/ExpressionAnalyzer.php(31): Psalm\Internal\Analyzer\Statements\ExpressionAnalyzer::handleExpression(Object(Psalm\Internal\Analyzer\StatementsAnalyzer), Object(_HumbugBoxc0bfaad63871\PhpParser\Node\Expr\StaticCall), Object(Psalm\Context), false, Object(Psalm\Context), true)
#3 phar:///home/runner/work/cakephp/cakephp/vendor/psalm/phar/psalm.phar/src/Psalm/Internal/Analyzer/StatementsAnalyzer.php(341): Psalm\Internal\Analyzer\Statements\ExpressionAnalyzer::analyze(Object(Psalm\Internal\Analyzer\StatementsAnalyzer), Object(_HumbugBoxc0bfaad63871\PhpParser\Node\Expr\StaticCall), Object(Psalm\Context), false, Object(Psalm\Context), true)
#4 phar:///home/runner/work/cakephp/cakephp/vendor/psalm/phar/psalm.phar/src/Psalm/Internal/Analyzer/StatementsAnalyzer.php(149): Psalm\Internal\Analyzer\StatementsAnalyzer::analyzeStatement(Object(Psalm\Internal\Analyzer\StatementsAnalyzer), Object(_HumbugBoxc0bfaad63871\PhpParser\Node\Stmt\Expression), Object(Psalm\Context), Object(Psalm\Context))
#5 phar:///home/runner/work/cakephp/cakephp/vendor/psalm/phar/psalm.phar/src/Psalm/Internal/Analyzer/FunctionLikeAnalyzer.php(355): Psalm\Internal\Analyzer\StatementsAnalyzer->analyze(Array, Object(Psalm\Context), Object(Psalm\Context), true)
#6 phar:///home/runner/work/cakephp/cakephp/vendor/psalm/phar/psalm.phar/src/Psalm/Internal/Analyzer/ClassAnalyzer.php(847): Psalm\Internal\Analyzer\FunctionLikeAnalyzer->analyze(Object(Psalm\Context), Object(Psalm\Internal\Provider\NodeDataProvider), Object(Psalm\Context))
#7 phar:///home/runner/work/cakephp/cakephp/vendor/psalm/phar/psalm.phar/src/Psalm/Internal/Analyzer/ClassAnalyzer.php(338): Psalm\Internal\Analyzer\ClassAnalyzer->analyzeClassMethod(Object(_HumbugBoxc0bfaad63871\PhpParser\Node\Stmt\ClassMethod), Object(Psalm\Storage\ClassLikeStorage), Object(Psalm\Internal\Analyzer\ClassAnalyzer), Object(Psalm\Context), Object(Psalm\Context))
#8 phar:///home/runner/work/cakephp/cakephp/vendor/psalm/phar/psalm.phar/src/Psalm/Internal/Analyzer/FileAnalyzer.php(173): Psalm\Internal\Analyzer\ClassAnalyzer->analyze(Object(Psalm\Context), Object(Psalm\Context))
#9 phar:///home/runner/work/cakephp/cakephp/vendor/psalm/phar/psalm.phar/src/Psalm/Internal/Codebase/Analyzer.php(268): Psalm\Internal\Analyzer\FileAnalyzer->analyze(NULL)
#10 phar:///home/runner/work/cakephp/cakephp/vendor/psalm/phar/psalm.phar/src/Psalm/Internal/Codebase/Analyzer.php(415): Psalm\Internal\Codebase\Analyzer->Psalm\Internal\Codebase\{closure}(144, '/home/runner/wo...')
#11 phar:///home/runner/work/cakephp/cakephp/vendor/psalm/phar/psalm.phar/src/Psalm/Internal/Codebase/Analyzer.php(223): Psalm\Internal\Codebase\Analyzer->doAnalysis(Object(Psalm\Internal\Analyzer\ProjectAnalyzer), 1)
#12 phar:///home/runner/work/cakephp/cakephp/vendor/psalm/phar/psalm.phar/src/Psalm/Internal/Analyzer/ProjectAnalyzer.php(457): Psalm\Internal\Codebase\Analyzer->analyzeFiles(Object(Psalm\Internal\Analyzer\ProjectAnalyzer), 1, false, true)
#13 phar:///home/runner/work/cakephp/cakephp/vendor/psalm/phar/psalm.phar/src/psalm.php(465): Psalm\Internal\Analyzer\ProjectAnalyzer->check('/home/runner/wo...', false)
#14 phar:///home/runner/work/cakephp/cakephp/vendor/psalm/phar/psalm.phar/psalm(5): require_once('phar:///home/ru...')
#15 /home/runner/work/cakephp/cakephp/vendor/psalm/phar/psalm.phar(14): require('phar:///home/ru...')
#16 {main}
(Psalm 3.17.2@9e526d9cb569fe4631e6a737bbb7948d05596e3f crashed due to an uncaught Throwable)
```

**Comment by othercorey** [comment]
Btw, the work around for this was putting the class_alias in the old Exception.php file and class_exists for Exception in the new CakeException.php file.
