### ISSUE TITLE
PHP Warning

### ISSUE THREAD

**Issue by enumag** [vimeo/psalm#4483]
Occasionally psalm gives me this PHP warning:

```
PHP Warning:  mkdir(): File exists in /app/vendor/vimeo/psalm/src/Psalm/Internal/Provider/ParserCacheProvider.php on line 244
```

**Comment by weirdan** [comment]
Are you running multiple instances of Psalm simultaneously?

**Comment by enumag** [comment]
No. But maybe psalm splits to multiple processes internally just like phpstan does?

**Comment by ndench** [comment]
I am also getting this issue intermittently in CI builds, retrying the build usually works though. Unsure how to provide more information or debug further though.

**Comment by ndench** [comment]
I added `ls -la ~/.cache/psalm` to my CI builds before and after psalm runs. When this issue happens the cache directory is not present before psalm is run but is present afterwards. I'm still unable to reliably reproduce it though.

**Comment by honca** [comment]
Hi, this error also appears to me quite often when I run psalm. Is there any movement with resolving this issue?
```
> ./vendor/bin/psalm --config=.psalm/psalm.xml '--update-baseline'
Scanning files...
Uncaught Exception: PHP Error: mkdir(): File exists in /projects/flashscore/vendor/vimeo/psalm/src/Psalm/Internal/Provider/ParserCacheProvider.php:312

(Psalm 4.6.4@97fe86c4e158b5a57c5150aa5055c38b5a809aab crashed due to an uncaught Throwable)
Script ./vendor/bin/psalm --config=.psalm/psalm.xml handling the psalm event returned with error code 1
Script @psalm --update-baseline was called via psalm-update-baseline
```
I use composer script to run this command.
Thanks very much.

**Comment by ddlzz** [comment]
It happens to me every other time also:
```
Scanning files...
Uncaught Exception: PHP Error: mkdir(): File exists in /var/www/app/vendor/vimeo/psalm/src/Psalm/Internal/Provider/ParserCacheProvider.php:312
Stack trace in the forked worker:
#0 [internal function]: Psalm\Internal\ErrorHandler::Psalm\Internal\{closure}()
#1 /var/www/app/vendor/vimeo/psalm/src/Psalm/Internal/Provider/ParserCacheProvider.php(312): mkdir()
#2 /var/www/app/vendor/vimeo/psalm/src/Psalm/Internal/Provider/StatementsProvider.php(287): Psalm\Internal\Provider\ParserCacheProvider->cacheFileContents()
#3 /var/www/app/vendor/vimeo/psalm/src/Psalm/Internal/Scanner/FileScanner.php(59): Psalm\Internal\Provider\StatementsProvider->getStatementsForFile()
#4 /var/www/app/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Scanner.php(575): Psalm\Internal\Scanner\FileScanner->scan()
#5 /var/www/app/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Scanner.php(326): Psalm\Internal\Codebase\Scanner->scanFile()
#6 /var/www/app/vendor/vimeo/psalm/src/Psalm/Internal/Fork/Pool.php(193): Psalm\Internal\Codebase\Scanner->Psalm\Internal\Codebase\{closure}()
#7 /var/www/app/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Scanner.php(394): Psalm\Internal\Fork\Pool->__construct()
#8 /var/www/app/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Scanner.php(290): Psalm\Internal\Codebase\Scanner->scanFilePaths()
#9 /var/www/app/vendor/vimeo/psalm/src/Psalm/Codebase.php(471): Psalm\Internal\Codebase\Scanner->scanFiles()
#10 /var/www/app/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/ProjectAnalyzer.php(589): Psalm\Codebase->scanFiles()
#11 /var/www/app/vendor/vimeo/psalm/src/psalm.php(700): Psalm\Internal\Analyzer\ProjectAnalyzer->check()
#12 /var/www/app/vendor/vimeo/psalm/src/psalm.php(884): Psalm\{closure}()
#13 /var/www/app/vendor/vimeo/psalm/psalm(2): require_once('/var/www/app/ve...')
#14 {main} in /var/www/app/vendor/vimeo/psalm/src/Psalm/Internal/Fork/Pool.php:357
Stack trace:
#0 /var/www/app/vendor/vimeo/psalm/src/Psalm/Internal/Fork/Pool.php(389): Psalm\Internal\Fork\Pool->readResultsFromChildren()
#1 /var/www/app/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Scanner.php(401): Psalm\Internal\Fork\Pool->wait()
#2 /var/www/app/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Scanner.php(290): Psalm\Internal\Codebase\Scanner->scanFilePaths()
#3 /var/www/app/vendor/vimeo/psalm/src/Psalm/Codebase.php(471): Psalm\Internal\Codebase\Scanner->scanFiles()
#4 /var/www/app/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/ProjectAnalyzer.php(589): Psalm\Codebase->scanFiles()
#5 /var/www/app/vendor/vimeo/psalm/src/psalm.php(700): Psalm\Internal\Analyzer\ProjectAnalyzer->check()
#6 /var/www/app/vendor/vimeo/psalm/src/psalm.php(884): Psalm\{closure}()
#7 /var/www/app/vendor/vimeo/psalm/psalm(2): require_once('/var/www/app/ve...')
#8 {main}
(Psalm 4.6.4@97fe86c4e158b5a57c5150aa5055c38b5a809aab crashed due to an uncaught Throwable)
```

**Comment by icron** [comment]
me too the same error
```
Scanning files...
Uncaught Exception: PHP Error: mkdir(): File exists in /app/vendor/vimeo/psalm/src/Psalm/Internal/Provider/ParserCacheProvider.php:312
Stack trace in the forked worker:
#0 [internal function]: Psalm\Internal\ErrorHandler::Psalm\Internal\{closure}(2, 'mkdir(): File e...', '/app/vendor/vim...', 312, Array)
```
