### ISSUE TITLE
Psalm 4.1.1@16bfbd9224698bd738c665f33039fade2a1a3977 crashed due to an uncaught Throwable

### ISSUE THREAD

**Issue by emmanuelGuiton** [vimeo/psalm#4489]
Psalm crashed during the analysis of a project :

```
Scanning files...
Analyzing files...

EEEE░EEEEEUncaught Exception: Union types are not allowed in class string param
Stack trace in the forked worker:
#0 /project-path/vendor/vimeo/psalm/src/Psalm/Internal/Type/TypeParser.php(97): Psalm\Internal\Type\TypeParser::getTypeFromTree()
#1 /project-path/vendor/vimeo/psalm/src/Psalm/Type.php(64): Psalm\Internal\Type\TypeParser::parseTokens()
#2 /project-path/vendor/vimeo/psalm/src/Psalm/Internal/Type/AssertionReconciler.php(332): Psalm\Type::parseString()
#3 /project-path/vendor/vimeo/psalm/src/Psalm/Type/Reconciler.php(271): Psalm\Internal\Type\AssertionReconciler::reconcile()
#4 /project-path/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/Statements/Block/IfAnalyzer.php(293): Psalm\Type\Reconciler::reconcileKeyedTypes()
#5 /project-path/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/StatementsAnalyzer.php(467): Psalm\Internal\Analyzer\Statements\Block\IfAnalyzer::analyze()
#6 /project-path/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/StatementsAnalyzer.php(169): Psalm\Internal\Analyzer\StatementsAnalyzer::analyzeStatement()
#7 /project-path/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/Statements/Block/LoopAnalyzer.php(202): Psalm\Internal\Analyzer\StatementsAnalyzer->analyze()
#8 /project-path/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/Statements/Block/ForeachAnalyzer.php(311): Psalm\Internal\Analyzer\Statements\Block\LoopAnalyzer::analyze()
#9 /project-path/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/StatementsAnalyzer.php(479): Psalm\Internal\Analyzer\Statements\Block\ForeachAnalyzer::analyze()
#10 /project-path/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/StatementsAnalyzer.php(169): Psalm\Internal\Analyzer\StatementsAnalyzer::analyzeStatement()
#11 /project-path/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/FileAnalyzer.php(188): Psalm\Internal\Analyzer\StatementsAnalyzer->analyze()
#12 /project-path/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Analyzer.php(341): Psalm\Internal\Analyzer\FileAnalyzer->analyze()
#13 /project-path/vendor/vimeo/psalm/src/Psalm/Internal/Fork/Pool.php(193): Psalm\Internal\Codebase\Analyzer->Psalm\Internal\Codebase\{closure}()
#14 /project-path/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Analyzer.php(407): Psalm\Internal\Fork\Pool->__construct()
#15 /project-path/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Analyzer.php(270): Psalm\Internal\Codebase\Analyzer->doAnalysis()
#16 /project-path/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/ProjectAnalyzer.php(638): Psalm\Internal\Codebase\Analyzer->analyzeFiles()
#17 /project-path/vendor/vimeo/psalm/src/psalm.php(675): Psalm\Internal\Analyzer\ProjectAnalyzer->check()
#18 /project-path/vendor/vimeo/psalm/psalm(2): require_once('/project-path/...')
#19 {main} in /project-path/vendor/vimeo/psalm/src/Psalm/Internal/Fork/Pool.php:358
Stack trace:
#0 /project-path/vendor/vimeo/psalm/src/Psalm/Internal/Fork/Pool.php(390): Psalm\Internal\Fork\Pool->readResultsFromChildren()
#1 /project-path/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Analyzer.php(474): Psalm\Internal\Fork\Pool->wait()
#2 /project-path/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Analyzer.php(270): Psalm\Internal\Codebase\Analyzer->doAnalysis()
#3 /project-path/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/ProjectAnalyzer.php(638): Psalm\Internal\Codebase\Analyzer->analyzeFiles()
#4 /project-path/vendor/vimeo/psalm/src/psalm.php(675): Psalm\Internal\Analyzer\ProjectAnalyzer->check()
#5 /project-path/vendor/vimeo/psalm/psalm(2): require_once('/project-path/...')
#6 {main}
(Psalm 4.1.1@16bfbd9224698bd738c665f33039fade2a1a3977 crashed due to an uncaught Throwable)
```

**Comment by orklah** [comment]
I think you have something like `class-string<a|b>` this should be `class-string<a>|class-string<b>`

**Comment by emmanuelGuiton** [comment]
It is Psalm code that triggers the error, not mine.
Whatever the analyzed code is, Psalm should not crash.

**Comment by orklah** [comment]
For me, it's Psalm reacting to a forbidden syntax in your code.

This is a rather crude error message but the error is right anyway.

I suggest you find the culprit in your doc and fix it. You should be able to find the file/line with --debug-by-line

**Comment by muglug** [comment]
@emmanuelGuiton please run with `--debug-by-line`, reporting the code that triggers the exception

**Comment by emmanuelGuiton** [comment]
@orklah Again : Psalm is crashing. How could we consider this a legitimate behaviour ?

To add a some context : I have launched Psalm on a project with a lot of (old) code. There are no annotations in the doc.
Psalm does not completely crash : 2 processes out of 8 crashed / exited. The main process (I get back the control of the console from which I launched Psalm) and 1 of 7 children. The 6 others continue in the background and in the end it is my computer that crashes (when I tried several times without noticing what was really happening).

Unfortunatley, so far I have not been able to identify the issue with `--debug-by-line`. The output is too enormous and since there are processes that still continue running it is pretty hard to locate the issue.

I try with `--thread=1`.

**Comment by emmanuelGuiton** [comment]
It worked. Psalm crashed on the 3rd line of that code snippet `if ($_REQUEST['do'] == get_class($action))` :
```
foreach ($actionsArray as $action) {
  $action->db = $db;
  if ($_REQUEST['do'] == get_class($action))
    $action->open = !$_REQUEST[get_class($action).'_open'];
  else
    $action->open = $_REQUEST[get_class($action).'_open'];
  $action->varDisplay("open");
  $action->display();
  $action->historize();
}
```

**Comment by emmanuelGuiton** [comment]
Hum :-/ I have a doubt.
How can I be sure which line triggered the error ?
Although I am running Psalm with a single thread, according to the output it parallelizes work. So the last line that appears on the console may not be the one that triggers the error.

**Comment by orklah** [comment]
What was the type of $action at this time? Could you try to reproduce that snippet on psalm.dev?

**Comment by emmanuelGuiton** [comment]
I cannot reproduce the bug anymore.
Our code base has changed a lot, I just ran Psalm on it and it worked.
There was just an issue when reading the baseline, because of a source file that included a non-UTF8 character. Psalm did not crash, it only complained about the baseline not ending with </file> tag. I.e. the file was corrupted, it could not read it.

**Comment by orklah** [comment]
Thanks for your answer. I'll close this, no use to keep it open if we don't have reproducers anywhere.

I think we have another issue for non-utf8 chars in the baseline already
