### ISSUE TITLE
`This should never happen` error

### ISSUE THREAD

**Issue by leighman** [vimeo/psalm#4532]
```
Uncaught UnexpectedValueException: This should never happen in blah/vendor/vimeo/psalm/src/Psalm/Type/Atomic.php:264
Stack trace:
#0 blah/vendor/vimeo/psalm/src/Psalm/Internal/Type/TypeParser.php(921): Psalm\Type\Atomic::create('LegacyUncharged...', NULL, Array, Array)
#1 blah/vendor/vimeo/psalm/src/Psalm/Internal/Type/TypeParser.php(133): Psalm\Internal\Type\TypeParser::getTypeFromTree(Object(Psalm\Internal\Type\ParseTree\Value), Object(Psalm\Codebase), NULL, Array, Array)
#2 blah/vendor/vimeo/psalm/src/Psalm/Internal/Type/TypeParser.php(94): Psalm\Internal\Type\TypeParser::getTypeFromTree(Object(Psalm\Internal\Type\ParseTree\GenericTree), Object(Psalm\Codebase), NULL, Array, Array)
#3 blah/vendor/vimeo/psalm/src/Psalm/Internal/PhpVisitor/ReflectorVisitor.php(3001): Psalm\Internal\Type\TypeParser::parseTokens(Array, NULL, Array, Array)
#4 blah/vendor/vimeo/psalm/src/Psalm/Internal/PhpVisitor/ReflectorVisitor.php(2380): Psalm\Internal\PhpVisitor\ReflectorVisitor->handleFunctionLikeDocblock(Object(PhpParser\Node\Stmt\ClassMethod), Object(Psalm\Storage\MethodStorage), Object(Psalm\Internal\Scanner\FunctionDocblockComment), Object(Psalm\Storage\ClassLikeStorage), false, false, 'Fergus\\TimeEntr...')
#5 blah/vendor/vimeo/psalm/src/Psalm/Internal/PhpVisitor/ReflectorVisitor.php(335): Psalm\Internal\PhpVisitor\ReflectorVisitor->registerFunctionLike(Object(PhpParser\Node\Stmt\ClassMethod))
#6 blah/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(200): Psalm\Internal\PhpVisitor\ReflectorVisitor->enterNode(Object(PhpParser\Node\Stmt\ClassMethod))
#7 blah/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(114): PhpParser\NodeTraverser->traverseArray(Array)
#8 blah/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(223): PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Stmt\Class_))
#9 blah/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(114): PhpParser\NodeTraverser->traverseArray(Array)
#10 blah/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(223): PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Stmt\Namespace_))
#11 blah/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(91): PhpParser\NodeTraverser->traverseArray(Array)
#12 blah/vendor/vimeo/psalm/src/Psalm/Internal/Scanner/FileScanner.php(89): PhpParser\NodeTraverser->traverse(Array)
#13 blah/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Scanner.php(565): Psalm\Internal\Scanner\FileScanner->scan(Object(Psalm\Codebase), Object(Psalm\Storage\FileStorage), false, Object(Psalm\Progress\VoidProgress))
#14 blah/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Scanner.php(328): Psalm\Internal\Codebase\Scanner->scanFile('blah...', Array, true)
#15 blah/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Scanner.php(440): Psalm\Internal\Codebase\Scanner->Psalm\Internal\Codebase\{closure}(0, 'blah...')
#16 blah/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Scanner.php(289): Psalm\Internal\Codebase\Scanner->scanFilePaths(1)
#17 blah/vendor/vimeo/psalm/src/Psalm/Codebase.php(408): Psalm\Internal\Codebase\Scanner->scanFiles(Object(Psalm\Internal\Codebase\ClassLikes))
#18 blah/vendor/vimeo/psalm/src/Psalm/Internal/LanguageServer/LanguageServer.php(312): Psalm\Codebase->reloadFiles(Object(Psalm\Internal\Analyzer\ProjectAnalyzer), Array)
#19 blah/vendor/vimeo/psalm/src/Psalm/Internal/LanguageServer/LanguageServer.php(171): Psalm\Internal\LanguageServer\LanguageServer->doAnalysis()
#20 blah/vendor/vimeo/psalm/src/Psalm/Internal/LanguageServer/EmitterTrait.php(80): Psalm\Internal\LanguageServer\LanguageServer->Psalm\Internal\LanguageServer\{closure}()
#21 blah/vendor/vimeo/psalm/src/Psalm/Internal/LanguageServer/ProtocolStreamReader.php(67): Psalm\Internal\LanguageServer\ProtocolStreamReader->emit('readMessageGrou...')
#22 [internal function]: Psalm\Internal\LanguageServer\ProtocolStreamReader->Psalm\Internal\LanguageServer\{closure}()
#23 blah/vendor/amphp/amp/lib/Coroutine.php(118): Generator->send('Content-Length:...')
#24 blah/vendor/amphp/amp/lib/Internal/Placeholder.php(149): Amp\Coroutine->Amp\{closure}(NULL, 'Content-Length:...')
#25 blah/vendor/amphp/amp/lib/Deferred.php(52): class@anonymous->resolve('Content-Length:...')
#26 blah/vendor/amphp/byte-stream/lib/ResourceInputStream.php(101): Amp\Deferred->resolve('Content-Length:...')
#27 blah/vendor/amphp/amp/lib/Loop/NativeDriver.php(201): Amp\ByteStream\ResourceInputStream::Amp\ByteStream\{closure}('a', Resource id #1, NULL)
#28 blah/vendor/amphp/amp/lib/Loop/NativeDriver.php(104): Amp\Loop\NativeDriver->selectStreams(Array, Array, -0.001)
#29 blah/vendor/amphp/amp/lib/Loop/Driver.php(138): Amp\Loop\NativeDriver->dispatch(true)
#30 blah/vendor/amphp/amp/lib/Loop/Driver.php(72): Amp\Loop\Driver->tick()
#31 blah/vendor/amphp/amp/lib/Loop.php(95): Amp\Loop\Driver->run()
#32 blah/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/ProjectAnalyzer.php(530): Amp\Loop::run()
#33 blah/vendor/vimeo/psalm/src/psalm-language-server.php(303): Psalm\Internal\Analyzer\ProjectAnalyzer->server(NULL, false)
#34 blah/vendor/vimeo/psalm/psalm-language-server(2): require_once('blah...')
#35 {main}
(Psalm 3.18.0@a463c894c4323e84121b5978867923efc6f8554a crashed due to an uncaught Throwable)
```

Possibly related to this class docblock?

```
/**
 * @psalm-import-type X from Operations
 * @psalm-import-type Y from Operations
 * @psalm-import-type Z from Operations
 *
 * @psalm-type LegacyUncharged = array{
 *   something: int,
 *   start_time: LocalTime,
 *   hours: float,
 * }
 *
 * @psalm-type Foo = array{
 *   a: LocalDate,
 *   b: int,
 *   c, LocalTime,
 *   d: LocalTime,
 *   e: int
 *   f: int,
 *   g: int,
 *   h: non-empty-string,
 *   i?: list<LegacyUncharged>,
 * }
 */
```

Probably missing something stupid, but doesn't seem like it should crash

**Comment by leighman** [comment]
Ah, `,` after the `c` in `Foo`, maybe?

**Comment by orklah** [comment]
Yeah, I think it was it. Please provide a psalm.dev reproducer if it's still an issue
