### ISSUE TITLE
Unit tests fail with ext-ds enabled

### ISSUE THREAD

**Issue by BenMorel** [vimeo/psalm#4578]
With [ext-ds](https://github.com/php-ds/ext-ds) enabled, I get the error below.
With the extension disabled, the tests run fine.

Is this an issue with Psalm or with `ext-ds`?

```
There was 1 error:

1) Psalm\Tests\EndToEnd\SuicidalAutoloaderTest::testSucceedsWithEmptyFile
Symfony\Component\Process\Exception\ProcessFailedException: The command "'php' '/home/benjamin/Projects/psalm/tests/EndToEnd/../../psalm' '-c=/home/benjamin/Projects/psalm/tests/EndToEnd/../fixtures/SuicidalAutoloader//psalm.xml' '--no-cache'" failed.

Exit Code: 70(Unknown error)

Working directory: /home/benjamin/Projects/psalm

Output:
================
RuntimeException: Attempted to load Ds\number in /home/benjamin/Projects/psalm/tests/fixtures/SuicidalAutoloader/autoloader.php:25
Stack trace:
#0 [internal function]: Psalm\Config->{closure}()
#1 [internal function]: spl_autoload_call()
#2 /home/benjamin/Projects/psalm/src/Psalm/Internal/Codebase/Scanner.php(687): ReflectionClass->__construct()
#3 /home/benjamin/Projects/psalm/src/Psalm/Internal/Codebase/Scanner.php(497): Psalm\Internal\Codebase\Scanner->fileExistsForClassLike()
#4 /home/benjamin/Projects/psalm/src/Psalm/Internal/Codebase/Scanner.php(289): Psalm\Internal\Codebase\Scanner->convertClassesToFilePaths()
#5 /home/benjamin/Projects/psalm/src/Psalm/Codebase.php(463): Psalm\Internal\Codebase\Scanner->scanFiles()
#6 /home/benjamin/Projects/psalm/src/Psalm/Config.php(1866): Psalm\Codebase->scanFiles()
#7 /home/benjamin/Projects/psalm/src/Psalm/Internal/Analyzer/ProjectAnalyzer.php(621): Psalm\Config->visitStubFiles()
#8 /home/benjamin/Projects/psalm/src/psalm.php(675): Psalm\Internal\Analyzer\ProjectAnalyzer->check()
#9 /home/benjamin/Projects/psalm/psalm(2): require_once('/home/benjamin/...')
#10 {main}

#0 [internal function]: Psalm\Config->{closure}()
#1 [internal function]: spl_autoload_call()
#2 /home/benjamin/Projects/psalm/src/Psalm/Internal/Codebase/Scanner.php(687): ReflectionClass->__construct()
#3 /home/benjamin/Projects/psalm/src/Psalm/Internal/Codebase/Scanner.php(497): Psalm\Internal\Codebase\Scanner->fileExistsForClassLike()
#4 /home/benjamin/Projects/psalm/src/Psalm/Internal/Codebase/Scanner.php(289): Psalm\Internal\Codebase\Scanner->convertClassesToFilePaths()
#5 /home/benjamin/Projects/psalm/src/Psalm/Codebase.php(463): Psalm\Internal\Codebase\Scanner->scanFiles()
#6 /home/benjamin/Projects/psalm/src/Psalm/Config.php(1866): Psalm\Codebase->scanFiles()
#7 /home/benjamin/Projects/psalm/src/Psalm/Internal/Analyzer/ProjectAnalyzer.php(621): Psalm\Config->visitStubFiles()
#8 /home/benjamin/Projects/psalm/src/psalm.php(675): Psalm\Internal\Analyzer\ProjectAnalyzer->check()
#9 /home/benjamin/Projects/psalm/psalm(2): require_once('/home/benjamin/...')
#10 {main}
```

**Comment by muglug** [comment]
Thanks! The suicidal autoloader tests fails if any stubs have types that cannot be autoloaded.
