### ISSUE TITLE
Uncaught Error: Class "Phar" not found in /opt/composer/vendor/vimeo/psalm/src/command_functions.php:47

### ISSUE THREAD

**Issue by kkmuffme** [vimeo/psalm#4671]
For some reason I get the following error: (I'm running psalm on a single php file)

I don't use any autoloaders in psalm.xml

```
Uncaught Error: Class "Phar" not found in /opt/composer/vendor/vimeo/psalm/src/command_functions.php:47
Stack trace:
#0 /opt/composer/vendor/vimeo/psalm/src/psalm.php(277): Psalm\requireAutoloaders('/var/www/vhosts...', false, 'vendor')
#1 /opt/composer/vendor/vimeo/psalm/src/Psalm/Internal/IncludeCollector.php(34): Psalm\{closure}()
#2 /opt/composer/vendor/vimeo/psalm/src/psalm.php(278): Psalm\Internal\IncludeCollector->runAndCollect(Object(Closure))
#3 /opt/composer/vendor/vimeo/psalm/psalm(2): require_once('/opt/composer/v...')
#4 {main}
(Psalm (unknown version) crashed due to an uncaught Throwable)
```

Tested with 4.2.1 and 4.1.1

Please let me know what additional info I can contribute to get this issue fixed.

**Comment by kkmuffme** [comment]
Nope :-)

**Comment by muglug** [comment]
Your PHP version probably doesn’t have the Phar extension
