### ISSUE TITLE
PHP Fatal error:  Uncaught UnexpectedValueException: The declaring method of FeatureContext::getcurrentuser should not be null 

### ISSUE THREAD

**Issue by DeepDiver1975** [vimeo/psalm#468]
The class causing this https://github.com/owncloud/core/blob/add-psalm/tests/ui/features/bootstrap/FeatureContext.php#L40

```
PHP Fatal error:  Uncaught UnexpectedValueException: The declaring method of FeatureContext::getcurrentuser should not be null in ...lib/composer/vimeo/psalm/src/Psalm/Checker/FunctionLikeChecker.php:168
Stack trace:
#0 ...lib/composer/vimeo/psalm/src/Psalm/Checker/ClassChecker.php(755): Psalm\Checker\FunctionLikeChecker->analyze(Object(Psalm\Context), Object(Psalm\Context))
#1 ...lib/composer/vimeo/psalm/src/Psalm/Checker/ClassChecker.php(393): Psalm\Checker\ClassChecker->analyzeClassMethod(Object(PhpParser\Node\Stmt\ClassMethod), Object(Psalm\Checker\ClassChecker), Object(Psalm\Context), Object(Psalm\Context))
#2 ...lib/composer/vimeo/psalm/src/Psalm/Checker/FileChecker.php(153): Psalm\Checker\ClassChecker->analyze(Object(Psalm\Context), Object(Psalm\Context))
#3 ...lib/composer/vimeo in ...lib/composer/vimeo/psalm/src/Psalm/Checker/FunctionLikeChecker.php on line 168

**Comment by muglug** [comment]
OK, that config explains the memory issues you're seeing.

Replace

```xml
        <directory name="." />
```

with

```xml
        <directory name="apps" />
        <directory name="core" />
        <directory name="lib" />
        <directory name="ocs" />
        <directory name="ocs-provider" />
        <directory name="settings" />
        <directory name="tests" />
```

and Psalm will not analyse the vendor directory (as those files are not something you can change anyway)

**Comment by muglug** [comment]
You're not namespacing your classes properly in your test files – so you have two separate FeatureContext classes in different files. Psalm assumes one file per class, and breaks under any other circumstance
