### ISSUE TITLE
Uncaught UnexpectedValueException: bad in psalm/src/Psalm/CodeLocation.php:320

### ISSUE THREAD

**Issue by staabm** [vimeo/psalm#4689]
just checked out psalm on 2bf25d5f5 and tried to invoke it (after a composer install).

I guess the error I am seeing here is not specific for this commit, but just a problem one will have when checking out the repo to a windows based machine.

```
php psalm test.php

Scanning files...
Analyzing files...

Uncaught UnexpectedValueException: bad in /cluster/www/www/www/psalm/src/Psalm/CodeLocation.php:320
Stack trace:
#0 /cluster/www/www/www/psalm/src/Psalm/CodeLocation.php(352): Psalm\CodeLocation->calculateRealLocation()
#1 /cluster/www/www/www/psalm/src/Psalm/IssueBuffer.php(230): Psalm\CodeLocation->getColumn()
#2 /cluster/www/www/www/psalm/src/Psalm/IssueBuffer.php(104): Psalm\IssueBuffer::add(Object(Psalm\Issue\Trace), false)
#3 /cluster/www/www/www/psalm/src/Psalm/Internal/Analyzer/StatementsAnalyzer.php(616): Psalm\IssueBuffer::accepts(Object(Psalm\Issue\Trace), Array)
#4 /cluster/www/www/www/psalm/src/Psalm/Internal/Analyzer/StatementsAnalyzer.php(168): Psalm\Internal\Analyzer\StatementsAnalyzer::analyzeStatement(Object(Psalm\Internal\Analyzer\StatementsAnalyzer), Object(PhpParser\Node\Stmt\Nop), Object(Psalm\Context), NULL)
#5 /cluster/www/www/www/psalm/src/Psalm/Internal/Analyzer/FileAnalyzer.php(187): Psalm\Internal\Analyzer\StatementsAnalyzer->analyze(Array, Object(Psalm\Context), NULL, true)
#6 /cluster/www/www/www/psalm/src/Psalm/Internal/Codebase/Analyzer.php(340): Psalm\Internal\Analyzer\FileAnalyzer->analyze(NULL)
#7 /cluster/www/www/www/psalm/src/Psalm/Internal/Codebase/Analyzer.php(579): Psalm\Internal\Codebase\Analyzer->Psalm\Internal\Codebase\{closure}(0, '/cluster/www/ww...')
#8 /cluster/www/www/www/psalm/src/Psalm/Internal/Codebase/Analyzer.php(269): Psalm\Internal\Codebase\Analyzer->doAnalysis(Object(Psalm\Internal\Analyzer\ProjectAnalyzer), 3)
#9 /cluster/www/www/www/psalm/src/Psalm/Internal/Analyzer/ProjectAnalyzer.php(1182): Psalm\Internal\Codebase\Analyzer->analyzeFiles(Object(Psalm\Internal\Analyzer\ProjectAnalyzer), 3, false, false)
#10 /cluster/www/www/www/psalm/src/psalm.php(678): Psalm\Internal\Analyzer\ProjectAnalyzer->checkPaths(Array)
#11 /cluster/www/www/www/psalm/psalm(2): require_once('/cluster/www/ww...')
#12 {main}
(Psalm 4.x-dev@2bf25d5f503811c6c74bbb8488f857559b23ed7b crashed due to an uncaught Throwable)

```

with my test.php
```php
<?php

class User {
    // Private properties
    private $id, $name;

    private function __construct () {}

    public static function load_by_id ($id):self {
        $pdo = new pdo("my-dsn");
        $stmt = $pdo->prepare('SELECT id, name FROM users WHERE id=?');
        $stmt->execute([$id]);
        return $stmt->fetchObject(__CLASS__);
    }

}

$user = User::load_by_id(1);
/** @psalm-trace $user */
```

observations:
- the exception thrown is not helpful. I don't know why it happend and what I should do or what the exception is trying to tell me.

Looking at `src/Psalm/CodeLocation.php` arround line `320`  I see some lines handling `\n` in strings.
Since I checked out the source-code on a windows compouter, I guess there is something going on regarding a CRLF vs. LF mismatch (line-endings).

```
php -v
PHP 7.4.12 (cli) (built: Oct 31 2020 17:04:25) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.12, Copyright (c), by Zend Technologies
    with Xdebug v2.9.8, Copyright (c) 2002-2020, by Derick Rethans
    with blackfire v1.44.0~linux-x64-non_zts74, https://blackfire.io, by Blackfire
```

**Comment by muglug** [comment]
Fixed bad debug error in 8ede667ca
