### ISSUE TITLE
Uncaught TypeError: Argument 2 to Psalm\Type::combineUnionTypes() ...

### ISSUE THREAD

**Issue by ptomulik** [vimeo/psalm#4825]
This bug first appears in 3.17.0 (tested with PHAR) and seems to be in all versions up to 4.3.1. Didn't check master.

I couldn't replicate it with psaml.dev, so I created the following minimal project ([test.tar.gz](https://github.com/vimeo/psalm/files/5672247/test.tar.gz)) consisting of two files:

src/X.php
```php
<?php declare(strict_types=1);

namespace Foo;

final class X
{
    /**
     * @var \SplObjectStorage
     */
    private $seen;

    /**
     * @var int
     */
    private $failures;

    public function __construct()
    {
        $this->seen = new \SplObjectStorage();
        $this->failures = 0;
    }

    public function validate(array $expected, int $argument, int $distance = 1): void
    {
        // The bug appears only when the following assignments are within
        // finally block and in this specific order.
        try {
        } finally {
            $this->failures = 0;
            $this->seen = new \SplObjectStorage();
        }
    }
}

// vim: syntax=php sw=4 ts=4 et:
```

and  psalm.xml

```xml
<?xml version="1.0"?>
<psalm
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns="https://getpsalm.org/schema/config"
    xsi:schemaLocation="https://getpsalm.org/schema/config vendor/vimeo/psalm/config.xsd"
    xmlns:xi="http://www.w3.org/2001/XInclude"
    rememberPropertyAssignmentsAfterCall="false"
>
    <projectFiles>
        <directory name="src" />
    </projectFiles>
</psalm>
```

Running psalm (PHAR, any version between 3.17.0 and 4.3.1 inclusive) yields the following error

```console
ptomulik@tea:$ ../psalm-3.17.0 
Scanning files...
Analyzing files...

PHP Notice:  Undefined index: $this->failures in phar:///tmp/psalm-3.17.0/src/Psalm/Internal/Analyzer/Statements/Block/TryAnalyzer.php on line 306
Notice: Undefined index: $this->failures in phar:///tmp/psalm-3.17.0/src/Psalm/Internal/Analyzer/Statements/Block/TryAnalyzer.php on line 306
Uncaught TypeError: Argument 2 passed to Psalm\Type::combineUnionTypes() must be an instance of Psalm\Type\Union, null given, called in phar:///tmp/psalm-3.17.0/src/Psalm/Internal/Analyzer/Statements/Block/TryAnalyzer.php on line 306 and defined in phar:///tmp/psalm-3.17.0/src/Psalm/Type.php:301
Stack trace:
#0 phar:///tmp/psalm-3.17.0/src/Psalm/Internal/Analyzer/Statements/Block/TryAnalyzer.php(306): Psalm\Type::combineUnionTypes()
#1 phar:///tmp/psalm-3.17.0/src/Psalm/Internal/Analyzer/StatementsAnalyzer.php(299): Psalm\Internal\Analyzer\Statements\Block\TryAnalyzer::analyze()
#2 phar:///tmp/psalm-3.17.0/src/Psalm/Internal/Analyzer/StatementsAnalyzer.php(149): Psalm\Internal\Analyzer\StatementsAnalyzer::analyzeStatement()
#3 phar:///tmp/psalm-3.17.0/src/Psalm/Internal/Analyzer/FunctionLikeAnalyzer.php(355): Psalm\Internal\Analyzer\StatementsAnalyzer->analyze()
#4 phar:///tmp/psalm-3.17.0/src/Psalm/Internal/Analyzer/ClassAnalyzer.php(847): Psalm\Internal\Analyzer\FunctionLikeAnalyzer->analyze()
#5 phar:///tmp/psalm-3.17.0/src/Psalm/Internal/Analyzer/ClassAnalyzer.php(338): Psalm\Internal\Analyzer\ClassAnalyzer->analyzeClassMethod()
#6 phar:///tmp/psalm-3.17.0/src/Psalm/Internal/Analyzer/FileAnalyzer.php(173): Psalm\Internal\Analyzer\ClassAnalyzer->analyze()
#7 phar:///tmp/psalm-3.17.0/src/Psalm/Internal/Codebase/Analyzer.php(268): Psalm\Internal\Analyzer\FileAnalyzer->analyze()
#8 phar:///tmp/psalm-3.17.0/src/Psalm/Internal/Codebase/Analyzer.php(415): Psalm\Internal\Codebase\Analyzer->Psalm\Internal\Codebase\{closure}()
#9 phar:///tmp/psalm-3.17.0/src/Psalm/Internal/Codebase/Analyzer.php(223): Psalm\Internal\Codebase\Analyzer->doAnalysis()
#10 phar:///tmp/psalm-3.17.0/src/Psalm/Internal/Analyzer/ProjectAnalyzer.php(457): Psalm\Internal\Codebase\Analyzer->analyzeFiles()
#11 phar:///tmp/psalm-3.17.0/src/psalm.php(465): Psalm\Internal\Analyzer\ProjectAnalyzer->check()
#12 phar:///tmp/psalm-3.17.0/psalm(5): require_once('phar:///tmp/psa...')
#13 /tmp/psalm-3.17.0(14): require('phar:///tmp/psa...')
#14 {main}
(Psalm 3.17.0@a6c73a9a0da841151cfcada5e7e25f142860eb17 crashed due to an uncaught Throwable)
```

**Comment by ptomulik** [comment]
Additional info: I was only able to replicate this bu g with ``rememberPropertyAssignmentsAfterCall="false"`` setting in psaml.xml.

**Comment by weirdan** [comment]
Reproduced: https://psalm.dev/r/7bfc596ee7

**Comment by muglug** [comment]
Weirdly I can't reproduce this in a unit test

**Comment by ptomulik** [comment]
> Weirdly I can't reproduce this in a unit test

From my observation - the error appears under following circumstances:

1. (In?)appropriate config settings, i.e ``rememberPropertyAssignmentsAfterCall="false"``, and
2. The code as above involving ``SplObjectStorage``, ``finally``, and
3. Cache disabled (enabling cache makes it appear once, and consecutive calls do not throw).

**Comment by muglug** [comment]
Ah thanks, I just fixed the original solution and added a test
