### ISSUE TITLE
Crash with symfony/mailer when class does not exist

### ISSUE THREAD

**Issue by asgrim** [vimeo/psalm#4829]
Using the latest Psalm version, Psalm execution is crashing on a codebase I'm trying to run it on:

```
░░░░░░░░░░░░░EEEEEEEEEEEEEEEEEEEEE░░░EEEE░░EEEEEEE░EEE░EEEEE  60 / 227 (26%)
EE░░░E░EEEE░░░EEEEEEE░EE░EEEEEEE░░░E░░EEEEEEEEEEEEE░EEEEEEEE 120 / 227 (52%)
░EE░░EEEE░░░EEEE░EE░E░░E░EE░░░EEEEEEEE░░░░EE░EEEEE░E░E░░EEEE 180 / 227 (79%)
EE░EE░E░EEEEEE░░░░░E░░EEE░░░EE░Uncaught Exception: Could not get class storage for symfony\component\mailer\bridge\sendinblue\transport\sendinbluetransportfactory
Stack trace in the forked worker:
#0 /path/to/project/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/Statements/Expression/YieldAnalyzer.php(145): Psalm\Internal\Provider\ClassLikeStorageProvider->get()
#1 /path/to/project/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/Statements/ExpressionAnalyzer.php(370): Psalm\Internal\Analyzer\Statements\Expression\YieldAnalyzer::analyze()
#2 /path/to/project/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/Statements/ExpressionAnalyzer.php(39): Psalm\Internal\Analyzer\Statements\ExpressionAnalyzer::handleExpression()
#3 /path/to/project/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/StatementsAnalyzer.php(522): Psalm\Internal\Analyzer\Statements\ExpressionAnalyzer::analyze()
<...snip...>
#5 /path/to/project/vendor/vimeo/psalm/psalm(2): require_once('...')
#6 {main}
(Psalm 4.3.1@2feba22a005a18bf31d4c7b9bdb9252c73897476 crashed due to an uncaught Throwable)
```

I *think* judging by the top of the stack, it is a `yield` statement, and with that class, it is coming from the following block in `symfony/mailer` package (which is used):

https://github.com/symfony/mailer/blob/f30fe13d4c9049f3c1f63be2c7f580779b058522/Transport.php#L159-L163
```php
        foreach (self::FACTORY_CLASSES as $factoryClass) {
            if (class_exists($factoryClass)) {
                yield new $factoryClass($dispatcher, $client, $logger);
            }
        }
```

I wondered if `psalm/symfony-plugin` might have stubs for this missing class, but no joy. I also don't really understand why it doesn't crash on any of the other missing classes in that `self::FACTORY_CLASSES`:

```php
    private const FACTORY_CLASSES = [
        SesTransportFactory::class,
        GmailTransportFactory::class,
        MandrillTransportFactory::class,
        MailgunTransportFactory::class,
        PostmarkTransportFactory::class,
        SendgridTransportFactory::class,
        MailjetTransportFactory::class,
        SendinblueTransportFactory::class,
    ];
```

Just to be clear, the project is not actually using `Symfony\Component\Mailer\Bridge\Sendinblue\Transport\SendinblueTransportFactory`, so the package where that class resides (presumably `symfony/sendinblue-mailer`) is not installed.

Unsure of the workaround here, since this is vendor code, I'm not sure how to tell Psalm to ignore that the class does not exist etc.

If it's any help, my Psalm configuration is:

```xml
<?xml version="1.0"?>
<psalm
    errorLevel="1"
    resolveFromConfigFile="true"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns="https://getpsalm.org/schema/config"
    xsi:schemaLocation="https://getpsalm.org/schema/config vendor/vimeo/psalm/config.xsd"
>
    <projectFiles>
        <directory name="src"/>
        <ignoreFiles>
            <directory name="vendor"/>
        </ignoreFiles>
    </projectFiles>
    <plugins>
        <pluginClass class="Psalm\SymfonyPsalmPlugin\Plugin">
            <containerXml>var/cache/dev/App_KernelDevDebugContainer.xml</containerXml>
        </pluginClass>
    </plugins>
</psalm>
```

**Comment by asgrim** [comment]
Yay, managed to reproduce it outside of `symfony/mailer` with the same structure: https://psalm.dev/r/c226c9bcd6

**Comment by asgrim** [comment]
@weirdan @muglug thank you both so much :) https://twitter.com/asgrim/status/1337414146023944192
