### ISSUE TITLE
Uncaught UnexpectedValueException: Error with core stub file docblocks

### ISSUE THREAD

**Issue by rvelhote** [vimeo/psalm#4851]
Hello,

I am testing Psalm 4.1.0 in our codebase (Magento 1.9 based) and got the following exception.

After setting breakpoint in `ReflectorVisitor.php` it turned out to be due to the [return type](https://github.com/OpenMage/magento-lts/blob/d04ac130cfa7cfd038668e846f79b475d7931f52/lib/Zend/Stdlib/SplPriorityQueue.php#L159) having a `;` in it.

The message in the exception was not explicit but the information of the variables available when the exception was thrown contained more information.

```
Scanning files...
Uncaught UnexpectedValueException: Error with core stub file docblocks in vendor/vimeo/psalm/src/Psalm/Internal/PhpVisitor/ReflectorVisitor.php:584
Stack trace:
#0 vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(230): Psalm\Internal\PhpVisitor\ReflectorVisitor->leaveNode()
#1 vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(114): PhpParser\NodeTraverser->traverseArray()
#2 vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(223): PhpParser\NodeTraverser->traverseNode()
#3 vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(91): PhpParser\NodeTraverser->traverseArray()
#4 vendor/vimeo/psalm/src/Psalm/Internal/Scanner/FileScanner.php(86): PhpParser\NodeTraverser->traverse()
#5 vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Scanner.php(558): Psalm\Internal\Scanner\FileScanner->scan()
#6 vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Scanner.php(321): Psalm\Internal\Codebase\Scanner->scanFile()
#7 vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Scanner.php(433): Psalm\Internal\Codebase\Scanner->Psalm\Internal\Codebase\{closure}()
#8 vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Scanner.php(285): Psalm\Internal\Codebase\Scanner->scanFilePaths()
#9 vendor/vimeo/psalm/src/Psalm/Codebase.php(463): Psalm\Internal\Codebase\Scanner->scanFiles()
#10 vendor/vimeo/psalm/src/Psalm/Config.php(1888): Psalm\Codebase->scanFiles()
#11 vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/ProjectAnalyzer.php(622): Psalm\Config->visitStubFiles()
#12 vendor/vimeo/psalm/src/psalm.php(676): Psalm\Internal\Analyzer\ProjectAnalyzer->check()
#13 vendor/vimeo/psalm/psalm(2): require_once('/...')
#14 {main}
(Psalm 4.3.1@2feba22a005a18bf31d4c7b9bdb9252c73897476 crashed due to an uncaught Throwable)
```

Thank you,
Ricardo

**Comment by rvelhote** [comment]
Hello Bot! Yes I can reproduce this issue. https://psalm.dev/r/2ba93e9724

**Comment by weirdan** [comment]
Simplified: https://psalm.dev/r/edafa5f377

**Comment by weirdan** [comment]
To clarify: there's a version-guarded polyfill with an invalid docblock for the class that Psalm has its own stub for. The polyfill is a part of ZF1 (?) which was quite popular, so it's likely it still can be seen in the wild.
