### ISSUE TITLE
Uncaught Exception: $storage should not be null

### ISSUE THREAD

**Issue by danog** [vimeo/psalm#4899]
Getting the following exception while scanning a huge project with multiple threads enabled.

```
Uncaught Exception: $storage should not be null for Module\Comment\Orm\MarkFakeMapper::getkey
Stack trace in the forked worker:
#0 /root/.composer/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/ClassAnalyzer.php(2038): Psalm\Internal\Codebase\Methods->getStorage()
#1 /root/.composer/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/ClassAnalyzer.php(2009): Psalm\Internal\Analyzer\ClassAnalyzer::analyzeClassMethodReturnType()
#2 /root/.composer/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/ClassAnalyzer.php(758): Psalm\Internal\Analyzer\ClassAnalyzer->analyzeClassMethod()
#3 /root/.composer/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/FileAnalyzer.php(210): Psalm\Internal\Analyzer\ClassAnalyzer->analyze()
#4 /root/.composer/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Analyzer.php(340): Psalm\Internal\Analyzer\FileAnalyzer->analyze()
#5 /root/.composer/vendor/vimeo/psalm/src/Psalm/Internal/Fork/Pool.php(193): Psalm\Internal\Codebase\Analyzer->Psalm\Internal\Codebase\{closure}()
#6 /root/.composer/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Analyzer.php(406): Psalm\Internal\Fork\Pool->__construct()
#7 /root/.composer/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Analyzer.php(269): Psalm\Internal\Codebase\Analyzer->doAnalysis()
#8 /root/.composer/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/ProjectAnalyzer.php(639): Psalm\Internal\Codebase\Analyzer->analyzeFiles()
#9 /root/.composer/vendor/vimeo/psalm/src/psalm.php(676): Psalm\Internal\Analyzer\ProjectAnalyzer->check()
#10 /root/.composer/vendor/vimeo/psalm/psalm(2): require_once('/root/.composer...')
#11 {main} in /root/.composer/vendor/vimeo/psalm/src/Psalm/Internal/Fork/Pool.php:357
Stack trace:
#0 /root/.composer/vendor/vimeo/psalm/src/Psalm/Internal/Fork/Pool.php(389): Psalm\Internal\Fork\Pool->readResultsFromChildren()
#1 /root/.composer/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Analyzer.php(473): Psalm\Internal\Fork\Pool->wait()
#2 /root/.composer/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Analyzer.php(269): Psalm\Internal\Codebase\Analyzer->doAnalysis()
#3 /root/.composer/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/ProjectAnalyzer.php(639): Psalm\Internal\Codebase\Analyzer->analyzeFiles()
#4 /root/.composer/vendor/vimeo/psalm/src/psalm.php(676): Psalm\Internal\Analyzer\ProjectAnalyzer->check()
#5 /root/.composer/vendor/vimeo/psalm/psalm(2): require_once('/root/.composer...')
#6 {main}
(Psalm dev-master@3b6550f892b97039bcdca0bd44f89c791da0c883 crashed due to an uncaught Throwable)
```

This is caused by the fact that Module\Comment\Orm\MarkFakeMapper class is present in two different files: the full version with the getKey is autoloaded normally from a PSR-4 path, while a stub version (with no methods) is conditionally included in another place of the code.

Indeed, the MarkFakeMapper ClassStorage is created twice, in two different threads.
In the first one, the full class is scanned and the class storage is populated with the the MethodStorage associated with `Module\Comment\Orm\MarkFakeMapper::getkey`.
In another thread, the stub class is scanned instead, causing an error while fetching the MethodStorage associated with getkey later on in the code.

I can (and will) blacklist the stubs from scanning, but it would be nice if psalm could nicely handle such conditions, instead of throwing a weird error :)

**Comment by sc0ttdav3y** [comment]
I just got the same error on my code. 

As a first time psalm user, I just pointed it to my code and told it to go for it. I don't yet understand enough about it to debug, configure or fix it. 

My stack trace looks a little different to @danog's, so I've reproduced it below.

```
$ ./vendor/psalm/phar/psalm.phar --version
Psalm 4.x-dev@


$ ./vendor/psalm/phar/psalm.phar --init
Calculating best config level based on project files
Scanning files...
Analyzing files...

Uncaught Exception: $storage should not be null for PortalServiceTest::setup6%)
Stack trace in the forked worker:
#0 phar://./vendor/psalm/phar/psalm.phar/src/Psalm/Internal/Analyzer/ClassAnalyzer.php(841): Psalm\Internal\Codebase\Methods->getStorage(Object(Psalm\Internal\MethodIdentifier))
#1 phar://./vendor/psalm/phar/psalm.phar/src/Psalm/Internal/Analyzer/ClassAnalyzer.php(819): Psalm\Internal\Analyzer\ClassAnalyzer::analyzeClassMethodReturnType(Object(_HumbugBoxa82ee8abad93\PhpParser\Node\Stmt\ClassMethod), Object(Psalm\Internal\Analyzer\MethodAnalyzer), Object(Psalm\Internal\Analyzer\ClassAnalyzer), Object(Psalm\Internal\Provider\NodeDataProvider), Object(Psalm\Codebase), Object(Psalm\Storage\ClassLikeStorage), 'PortalServiceTe...', Object(Psalm\Internal\MethodIdentifier), Object(Psalm\Internal\MethodIdentifier), false)
#2 phar://./vendor/psalm/phar/psalm.phar/src/Psalm/Internal/Analyzer/ClassAnalyzer.php(224): Psalm\Internal\Analyzer\ClassAnalyzer->analyzeClassMethod(Object(_HumbugBoxa82ee8abad93\PhpParser\Node\Stmt\ClassMethod), Object(Psalm\Storage\ClassLikeStorage), Object(Psalm\Internal\Analyzer\ClassAnalyzer), Object(Psalm\Context), Object(Psalm\Context))
#3 phar://./vendor/psalm/phar/psalm.phar/src/Psalm/Internal/Analyzer/FileAnalyzer.php(170): Psalm\Internal\Analyzer\ClassAnalyzer->analyze(Object(Psalm\Context), Object(Psalm\Context))
#4 phar://./vendor/psalm/phar/psalm.phar/src/Psalm/Internal/Codebase/Analyzer.php(268): Psalm\Internal\Analyzer\FileAnalyzer->analyze(NULL)
#5 phar://./vendor/psalm/phar/psalm.phar/src/Psalm/Internal/Fork/Pool.php(150): Psalm\Internal\Codebase\Analyzer->Psalm\Internal\Codebase\{closure}(319, '/Users/sdavey/C...')
#6 phar://./vendor/psalm/phar/psalm.phar/src/Psalm/Internal/Codebase/Analyzer.php(315): Psalm\Internal\Fork\Pool->__construct(Array, Object(Closure), Object(Closure), Object(Closure), Object(Closure))
#7 phar://./vendor/psalm/phar/psalm.phar/src/Psalm/Internal/Codebase/Analyzer.php(223): Psalm\Internal\Codebase\Analyzer->doAnalysis(Object(Psalm\Internal\Analyzer\ProjectAnalyzer), 7)
#8 phar://./vendor/psalm/phar/psalm.phar/src/Psalm/Internal/Analyzer/ProjectAnalyzer.php(447): Psalm\Internal\Codebase\Analyzer->analyzeFiles(Object(Psalm\Internal\Analyzer\ProjectAnalyzer), 7, false, true)
#9 phar://./vendor/psalm/phar/psalm.phar/src/psalm.php(472): Psalm\Internal\Analyzer\ProjectAnalyzer->check('/Users/sdavey/C...', true)
#10 phar://./vendor/psalm/phar/psalm.phar/src/psalm.php(571): Psalm\{closure}(Array)
#11 phar://./vendor/psalm/phar/psalm.phar/psalm(5): require_once('phar:///Users/s...')
#12 ./vendor/psalm/phar/psalm.phar(14): require('phar:///Users/s...')
#13 {main} in phar://./vendor/psalm/phar/psalm.phar/src/Psalm/Internal/Fork/Pool.php:283
Stack trace:
#0 phar://./vendor/psalm/phar/psalm.phar/src/Psalm/Internal/Fork/Pool.php(311): Psalm\Internal\Fork\Pool->readResultsFromChildren()
#1 phar://./vendor/psalm/phar/psalm.phar/src/Psalm/Internal/Codebase/Analyzer.php(350): Psalm\Internal\Fork\Pool->wait()
#2 phar://./vendor/psalm/phar/psalm.phar/src/Psalm/Internal/Codebase/Analyzer.php(223): Psalm\Internal\Codebase\Analyzer->doAnalysis(Object(Psalm\Internal\Analyzer\ProjectAnalyzer), 7)
#3 phar://./vendor/psalm/phar/psalm.phar/src/Psalm/Internal/Analyzer/ProjectAnalyzer.php(447): Psalm\Internal\Codebase\Analyzer->analyzeFiles(Object(Psalm\Internal\Analyzer\ProjectAnalyzer), 7, false, true)
#4 phar://./vendor/psalm/phar/psalm.phar/src/psalm.php(472): Psalm\Internal\Analyzer\ProjectAnalyzer->check('/Users/XXX/C...', true)
#5 phar://./vendor/psalm/phar/psalm.phar/src/psalm.php(571): Psalm\{closure}(Array)
#6 phar://./vendor/psalm/phar/psalm.phar/psalm(5): require_once('phar:///Users/s...')
#7 ./vendor/psalm/phar/psalm.phar(14): require('phar:///Users/s...')
#8 {main}
(Psalm 4.x-dev@ crashed due to an uncaught Throwable)
```

**Comment by orklah** [comment]
Please try to run with --debug-by-line . It should give you the approximative location of the issue.

However this part `for PortalServiceTest::setup6%)` seems strange. Please look if you have an exotic syntax/code somewhere around that method or where it's used

**Comment by sc0ttdav3y** [comment]
There's nothing odd about any of the classes it fails on. For example, the original file `PortalServiceTest` had the following on that line:

```
public function setUp()
```

It's a PHPUnit class so there are no explicit calls to that method (it's all done in PHPUnit by reflection). I even grabbed a hex editor to ensure there weren't any odd characters and it was clean. One interesting point is that the error message has lowercased the method name to `setup`. Not sure if there's anything there to go on.

I changed the base directory in configuration to include the project at a higher point (including more files), and I got the same error but for a different file. Again, nothing wrong with the file.

I then followed the debug tip from @orklah (unfortunately it got stuck on collecting data from the other processes at the end), and following https://github.com/vimeo/psalm/issues/4973 I added `--threads=1` and it completed without crashing (but took well over an hour) 🎉 .

```
Checks took 3,174.79 seconds and used 2,144.575MB of memory
Psalm was able to infer types for 89.4124% of the codebase
```

Now, I can run it normally and it runs in a few seconds, using the cache:

Environment: MacOS 11 (Intel MBP) running brew php 7.4.16
Project: 646 KLOC (3 MLOC with vendor library)

I'll keep chipping away and see if I can get more info about this problem, but in the meantime it seems `--threads=1` stops the problem from occurring when the cache is empty, and when the cache is full it seems to work okay.

**Comment by orklah** [comment]
Must be a concurrency issue then. The lowercase part is normal. PHP is case insensitive so Psalm's internals have evey symbol in lowercase.

Any common point between the two files that failed?

**Comment by Cerberooo** [comment]
I have the same issue when running it with `--init`, so I can't use `--threads` or `--memory-limit` :/

**Comment by yoshifp** [comment]
I was seeing a similar issue when I set the threads manually, I have an 8 core CPU and it's a big project so I wanted to maximise CPU usage. I tried `--threads=8` and `--threads=6` multiple times, then gave up and tried `--threads=1`.

Psalm provides different errors as to what $storage should be null for depending on the threads set, but seem to be the same root cause within:
```
#0 phar:///home/yoshifp/Apps/psalm/psalm.phar/src/Psalm/Internal/Analyzer/ClassAnalyzer.php(842): Psalm\Internal\Codebase\Methods->getStorage(Object(Psalm\Internal\MethodIdentifier))
```

Sample full stack trace.
```
~/Apps/psalm/psalm.phar --taint-analysis --threads=1 --no-diff | tee psalm_taint.log
Scanning files...
Analyzing files...

Uncaught UnexpectedValueException: $storage should not be null for DefaultController::getpagetitle in phar:///home/yoshifp/Apps/psalm/psalm.phar/src/Psalm/Internal/Codebase/Methods.php:665
Stack trace:
#0 phar:///home/yoshifp/Apps/psalm/psalm.phar/src/Psalm/Internal/Analyzer/ClassAnalyzer.php(842): Psalm\Internal\Codebase\Methods->getStorage(Object(Psalm\Internal\MethodIdentifier))
#1 phar:///home/yoshifp/Apps/psalm/psalm.phar/src/Psalm/Internal/Analyzer/ClassAnalyzer.php(820): Psalm\Internal\Analyzer\ClassAnalyzer::analyzeClassMethodReturnType(Object(_HumbugBoxaf3fb728a79d\PhpParser\Node\Stmt\ClassMethod), Object(Psalm\Internal\Analyzer\MethodAnalyzer), Object(Psalm\Internal\Analyzer\ClassAnalyzer), Object(Psalm\Internal\Provider\NodeDataProvider), Object(Psalm\Codebase), Object(Psalm\Storage\ClassLikeStorage), 'DefaultControll...', Object(Psalm\Internal\MethodIdentifier), Object(Psalm\Internal\MethodIdentifier), true)
#2 phar:///home/yoshifp/Apps/psalm/psalm.phar/src/Psalm/Internal/Analyzer/ClassAnalyzer.php(224): Psalm\Internal\Analyzer\ClassAnalyzer->analyzeClassMethod(Object(_HumbugBoxaf3fb728a79d\PhpParser\Node\Stmt\ClassMethod), Object(Psalm\Storage\ClassLikeStorage), Object(Psalm\Internal\Analyzer\ClassAnalyzer), Object(Psalm\Context), Object(Psalm\Context))
#3 phar:///home/yoshifp/Apps/psalm/psalm.phar/src/Psalm/Internal/Analyzer/FileAnalyzer.php(170): Psalm\Internal\Analyzer\ClassAnalyzer->analyze(Object(Psalm\Context), Object(Psalm\Context))
#4 phar:///home/yoshifp/Apps/psalm/psalm.phar/src/Psalm/Internal/Codebase/Analyzer.php(268): Psalm\Internal\Analyzer\FileAnalyzer->analyze(NULL)
#5 phar:///home/yoshifp/Apps/psalm/psalm.phar/src/Psalm/Internal/Codebase/Analyzer.php(414): Psalm\Internal\Codebase\Analyzer->Psalm\Internal\Codebase\{closure}(156, '/home/yoshifp/proj...')
#6 phar:///home/yoshifp/Apps/psalm/psalm.phar/src/Psalm/Internal/Codebase/Analyzer.php(223): Psalm\Internal\Codebase\Analyzer->doAnalysis(Object(Psalm\Internal\Analyzer\ProjectAnalyzer), 1)
#7 phar:///home/yoshifp/Apps/psalm/psalm.phar/src/Psalm/Internal/Analyzer/ProjectAnalyzer.php(447): Psalm\Internal\Codebase\Analyzer->analyzeFiles(Object(Psalm\Internal\Analyzer\ProjectAnalyzer), 1, false, true)
#8 phar:///home/yoshifp/Apps/psalm/psalm.phar/src/psalm.php(472): Psalm\Internal\Analyzer\ProjectAnalyzer->check('/home/yoshifp/proj...', false)
#9 phar:///home/yoshifp/Apps/psalm/psalm.phar/src/psalm.php(571): Psalm\{closure}(Array)
#10 phar:///home/yoshifp/Apps/psalm/psalm.phar/psalm(5): require_once('phar:///home/to...')
#11 /home/yoshifp/Apps/psalm/psalm.phar(14): require('phar:///home/to...')
#12 {main}
(Psalm 4.x-dev@ crashed due to an uncaught Throwable)
```

Sample alternative error
```
Uncaught Exception: $storage should not be null for UserIdentity::getid
Stack trace in the forked worker:
#0 phar:///home/todd/Apps/psalm/psalm.phar/src/Psalm/Internal/Analyzer/ClassAnalyzer.php(842): Psalm\Internal\Codebase\Methods->getStorage(Object(Psalm\Internal\MethodIdentifier))
#1 phar:///home/todd/Apps/psalm/psalm.phar/src/Psalm/Internal/Analyzer/ClassAnalyzer.php(820): Psalm\Internal\Analyzer\ClassAnalyzer::analyzeClassMethodReturnType(Object(_HumbugBoxaf3fb728a79d\PhpParser\Node\Stmt\ClassMethod), Object(Psalm\Internal\Analyzer\MethodAnalyzer), Object(Psalm\Internal\Analyzer\ClassAnalyzer), Object(Psalm\Internal\Provider\NodeDataProvider), Object(Psalm\Codebase), Object(Psalm\Storage\ClassLikeStorage), 'UserIdentity', Object(Psalm\Internal\MethodIdentifier), Object(Psalm\Internal\MethodIdentifier), true)
...
```

When I leave Psalm to determine threads on it's own, I didn't see errors like the above. Eg.
```
~/Apps/psalm/psalm.phar --taint-analysis | tee psalm_taint.log
```

However, I did not have any success, it appears to have got stuck at 2600 / 4352 (59%), following the below memory error, while holding 4 of 8 CPU cores hostage for about 3 hours, before I finally stopped the analysis. Psalm hasn't shown progress from 2600 files for majority of that time.

I'm running the PHAR version which is attached to the 4.7.1 release (https://github.com/vimeo/psalm/releases/tag/4.7.1). The 4.7.2 release didn't have a PHAR attached.

I'm trying to run this on a large project (more than 1.5 million lines of code).

I tried leaving it running even with the above errors, and after 1.5 hours at 8 threads, it still didn't complete.

Psalm threw another issue afterwards (when specifying threads or not) where it exceeded the 8GB memory limit (cli is set to -1 (unlimited)) for PHP and RAM had plenty of room left. eg.
```
PHP Fatal error:  Allowed memory size of 8589934592 bytes exhausted (tried to allocate 20480 bytes) in phar:///home/yoshifp/Apps/psalm/psalm.phar/src/Psalm/Internal/Clause.php on line 197
```

**Comment by iandunn** [comment]
I see this w/ `threads=8`, but not `threads=6`. I thought my CPU had 8 cores, but I just double-checked and it only has 4. 

So, it's odd that `8` and `6` don't behave the same way 🤷🏻‍♂️

**Comment by iandunn** [comment]
Possibly related: #5200 / #4662. I did have taint analysis enabled when I got the error.

**Comment by tmuras** [comment]
I get the same "Uncaught UnexpectedValueException: $storage should not be null" error when running against big (Moodle) code base:
vendor/bin/psalm --init

The execution, however finishes fine when running:
vendor/bin/psalm --init --debug

I understand that in the first case multiple threads are used and in the second, --debug flag causes to run in 1 thread only. Also, with --init option  --threads option can not be used.

So it seems that concurrency is an issue here.

Psalm 5.4.0@62db5d4f6a7ae0a20f7cc5a4952d730272fc0863
PHP 7.4.3

**Comment by sbraaa** [comment]
Similar behaviour for me on a very big project with legacy code.
I was unable to complete init step. At the end with --debug the step was done.
Unfortunately I cannot proceed with normal usage (vendor/bin/psalm)
I've tried all the options I know (--debug, --threads=?, --memory-limit ) but i'm not able to execute normal analysis.

Psalm 5.4.0@62db5d4f6a7ae0a20f7cc5a4952d730272fc0863
PHP 8.1.2

**Comment by iMu3ic** [comment]
Hello, guys! Are you planning to fix this?

**Comment by danog** [comment]
Could you try debugging with debug-by-line?

**Comment by iMu3ic** [comment]
Yeah, sure. I already checked this. The output is the same. I was tested this issue on the open source project called ILIAS https://github.com/ILIAS-eLearning/ILIAS.

**Comment by iMu3ic** [comment]
The problem is the same with https://github.com/vimeo/psalm/issues/4899#issuecomment-816467402. But this time the point is in the interface ILIAS\UI\Interfaces\ProperEntry.

**Comment by danog** [comment]
@iMu3ic Scanning the ILIAS project with psalm works fine on my machine, how do you reproduce the issue?

**Comment by iMu3ic** [comment]
I'm using this command:
```php -dopcache.enable_cli=1 -dopcache.jit_buffer_size=100M
-dopcache.jit=1255 vendor/bin/psalm --memory-limit=7G --threads=2
--taint-analysis --report=results3.sarif ILIAS/
```
The point is in threads number. It must be greater than 1.

ср, 20 дек. 2023 г. в 13:30, Daniil Gentili ***@***.***>:
