### ISSUE TITLE
Bug?  Analysing two files, expected only one

### ISSUE THREAD

**Issue by klebann** [vimeo/psalm#4921]
This command shows two files:
vendor/bin/psalm --config=psalm-plugin.xml --no-diff --show-info=true "lib.php" | less

lib.php and locallib.php

is this correct behavior?

**Comment by orklah** [comment]
Can you show us the content of your `projectFiles` tag in your config file please?

**Comment by klebann** [comment]
```xml
<projectFiles>
        <file name="version.php"/>
        <file name="view.php"/>
        <file name="updatechecks.php"/>
        <file name="autoupdate.php"/>
        <file name="export.php"/>
        <file name="importexportfields.php"/>
        <file name="mod_form.php"/>
        <file name="index.php"/>
        <file name="renderer.php"/>
        <file name="lib.php"/>
        <file name="report.php"/>
        <file name="import.php"/>
        <file name="locallib.php"/>
        <file name="settings.php"/>
        <file name="edit.php"/>
        <directory name="db"/>
        <directory name="lang"/>
        <directory name="backup"/>
        <directory name="classes"/>
        <ignoreFiles>
            <directory name="vendor"/>
        </ignoreFiles>
    </projectFiles>
```

**Comment by orklah** [comment]
Can you show us the complete output and tell us if the two files are related somehow?

**Comment by klebann** [comment]
lib.php:
`require_once(dirname(__FILE__).'/locallib.php');`


Output:
```
INFO: PossibleSqlInjection - lib.php:692:22 - Calling unsafe sql method $DB->get_records
_sql
Description:
    Info: Arg1 Type = Expr_Variable
SQL:
    SELECT DISTINCT u.id
              FROM {user} u
              JOIN {checklist_check} c ON c.userid = u.id
              JOIN {checklist_item} i ON i.id = c.item
             WHERE i.checklist = ?
Documentation - (see https://psalm.dev/000)
    $userids2 = $DB->get_records_sql($sql, $params);


INFO: PossibleSqlInjection - locallib.php:180:28 - Calling unsafe sql method $DB->get_re
cords_sql
Description:
    Info: Arg1 Type = Expr_Variable
SQL:
    SELECT i.id, c.usertimestamp, c.teachermark, c.teachertimestamp, c.teacherid
                      FROM {checklist_item} i
                 LEFT JOIN {checklist_check} c ON (i.id = c.item AND c.userid = ?) WHERE i.checklist = ? 
Documentation - (see https://psalm.dev/000)
            $checks = $DB->get_records_sql($sql, array($this->userid, $this->checklist->id));
```

**Comment by orklah** [comment]
Oh, then I guess this is expected. When Psalm can, it will follow your requires to have a clue of what variables/symbols are in your scope.

Can you check what this does: https://psalm.dev/docs/running_psalm/configuration/#allowfileincludes

I'm not sure if it will just emit an issue on your require or if it will stop visiting it

**Comment by klebann** [comment]
```linux
Uncaught Psalm\Exception\FileIncludeException: File includes are not allowed per your Psalm config - check the allowFileIncludes flag. in /opt/moodle/mod/checklist/vendor/vimeo/psalm/src/Psalm/Internal/PhpVisitor/Reflector/ExpressionScanner.php:272
Stack trace:
#0 /opt/moodle/mod/checklist/vendor/vimeo/psalm/src/Psalm/Internal/PhpVisitor/Reflector/ExpressionScanner.php(46): Psalm\Internal\PhpVisitor\Reflector\ExpressionScanner::visitInclude(Object(Psalm\Codebase), Object(Psalm\Storage\FileStorage), Object(PhpParser\Node\Expr\Include_), true)
#1 /opt/moodle/mod/checklist/vendor/vimeo/psalm/src/Psalm/Internal/PhpVisitor/ReflectorVisitor.php(344): Psalm\Internal\PhpVisitor\Reflector\ExpressionScanner::scan(Object(Psalm\Codebase), Object(Psalm\Internal\Scanner\FileScanner), Object(Psalm\Storage\FileStorage), Object(Psalm\Aliases), Object(PhpParser\Node\Expr\Include_), NULL, NULL)
#2 /opt/moodle/mod/checklist/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(123): Psalm\Internal\PhpVisitor\ReflectorVisitor->enterNode(Object(PhpParser\Node\Expr\Include_))
#3 /opt/moodle/mod/checklist/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(223): PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Stmt\Expression))
#4 /opt/moodle/mod/checklist/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(91): PhpParser\NodeTraverser->traverseArray(Array)
#5 /opt/moodle/mod/checklist/vendor/vimeo/psalm/src/Psalm/Internal/Scanner/FileScanner.php(86): PhpParser\NodeTraverser->traverse(Array)
#6 /opt/moodle/mod/checklist/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Scanner.php(558): Psalm\Internal\Scanner\FileScanner->scan(Object(Psalm\Codebase), Object(Psalm\Storage\FileStorage), false, Object(Psalm\Progress\DefaultProgress))
#7 /opt/moodle/mod/checklist/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Scanner.php(321): Psalm\Internal\Codebase\Scanner->scanFile('/opt/moodle/mod...', Array, true)
#8 /opt/moodle/mod/checklist/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Scanner.php(433): Psalm\Internal\Codebase\Scanner->Psalm\Internal\Codebase\{closure}(0, '/opt/moodle/mod...')
#9 /opt/moodle/mod/checklist/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Scanner.php(285): Psalm\Internal\Codebase\Scanner->scanFilePaths(1)
#10 /opt/moodle/mod/checklist/vendor/vimeo/psalm/src/Psalm/Config.php(2010): Psalm\Internal\Codebase\Scanner->scanFiles(Object(Psalm\Internal\Codebase\ClassLikes))
#11 /opt/moodle/mod/checklist/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/ProjectAnalyzer.php(398): Psalm\Config->visitComposerAutoloadFiles(Object(Psalm\Internal\Analyzer\ProjectAnalyzer), Object(Psalm\Progress\DefaultProgress))
#12 /opt/moodle/mod/checklist/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/ProjectAnalyzer.php(1151): Psalm\Internal\Analyzer\ProjectAnalyzer->visitAutoloadFiles()
#13 /opt/moodle/mod/checklist/vendor/vimeo/psalm/src/psalm.php(678): Psalm\Internal\Analyzer\ProjectAnalyzer->checkPaths(Array)
#14 /opt/moodle/mod/checklist/vendor/vimeo/psalm/psalm(2): require_once('/opt/moodle/mod...')
#15 {main}
(Psalm 4.3.1@2feba22a005a18bf31d4c7b9bdb9252c73897476 crashed due to an uncaught Throwable)
```

**Comment by klebann** [comment]
Okey, so if it works so, it's not a problem for me anymore.
If program includes another file, then that's logic that Psalm should scan both files.

**Comment by klebann** [comment]
Thanks
