### ISSUE TITLE
Uncaught UnexpectedValueException & Failed to load plugin

### ISSUE THREAD

**Issue by klebann** [vimeo/psalm#4947]
How can I fix this problem?
I created plugin based on orklah/psalm-strict-visibility files.
It was working
Then i changed folders and namespaces to klebann/moodle-psalm-plugin and dumped composer. Now it's not working.
What can I do to make this work?

```
➜ vendor/bin/psalm --config=psalm-plugin.xml --no-diff --show-info=true ../../mod/checklist

Scanning files...
Uncaught UnexpectedValueException: Klebann\MoodlePsalmPlugin\Plugin is not a known class in /home/jkleban/git/psalm-moodle/local/psalm/vendor/vimeo/psalm/src/Psalm/Config.php:1235
Stack trace:
#0 /home/jkleban/git/psalm-moodle/local/psalm/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/ProjectAnalyzer.php(1165): Psalm\Config->initializePlugins(Object(Psalm\Internal\Analyzer\ProjectAnalyzer))
#1 /home/jkleban/git/psalm-moodle/local/psalm/vendor/vimeo/psalm/src/psalm.php(678): Psalm\Internal\Analyzer\ProjectAnalyzer->checkPaths(Array)
#2 /home/jkleban/git/psalm-moodle/local/psalm/vendor/vimeo/psalm/psalm(2): require_once('/home/jkleban/g...')
#3 {main}

Next Psalm\Exception\ConfigException: Failed to load plugin Klebann\MoodlePsalmPlugin\Plugin in /home/jkleban/git/psalm-moodle/local/psalm/vendor/vimeo/psalm/src/Psalm/Config.php:1247
Stack trace:
#0 /home/jkleban/git/psalm-moodle/local/psalm/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/ProjectAnalyzer.php(1165): Psalm\Config->initializePlugins(Object(Psalm\Internal\Analyzer\ProjectAnalyzer))
#1 /home/jkleban/git/psalm-moodle/local/psalm/vendor/vimeo/psalm/src/psalm.php(678): Psalm\Internal\Analyzer\ProjectAnalyzer->checkPaths(Array)
#2 /home/jkleban/git/psalm-moodle/local/psalm/vendor/vimeo/psalm/psalm(2): require_once('/home/jkleban/g...')
#3 {main}
(Psalm 4.3.2@57b53ff26237074fdf5cbcb034f7da5172be4524 crashed due to an uncaught Throwable)
```

```php
<?xml version="1.0"?>
    <psalm
        errorLevel="7"
        resolveFromConfigFile="true"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xmlns="https://getpsalm.org/schema/config"
        xsi:schemaLocation="https://getpsalm.org/schema/config vendor/vimeo/psalm/config.xsd"
        autoloader="psalm-autoload.php"
    >
    <globals>
        <var name="DB" type="moodle_database|null" />
    </globals>
    <issueHandlers>
        <AbstractInstantiation errorLevel="suppress" />
        ...
        <RedundantCastGivenDocblockType errorLevel="suppress" />

        <PluginIssue name="PossibleSqlInjection" errorLevel="info" />
    </issueHandlers>
    <projectFiles>
        <file name="../../mod/checklist/autoupdate.php"/>
        <ignoreFiles>
            <directory name="vendor"/>
        </ignoreFiles>
    </projectFiles>
    <plugins><pluginClass class="Klebann\MoodlePsalmPlugin\Plugin"/></plugins></psalm>
```

**Comment by weirdan** [comment]
`Klebann\MoodlePsalmPlugin\Plugin` needs to be autoloadable. Does running the following in the folder where you run Psalm
```sh
php -r 'require "vendor/autoload.php"; var_dump(class_exist(Klebann\MoodlePsalmPlugin\Plugin::class));'
```
return `true`?

**Comment by orklah** [comment]
Yeah, I'd bet on a wrong namespace/plugin in composer.json

**Comment by klebann** [comment]
```
18:16 in ~/git/psalm-moodle/local/psalm on  Main [ef8eb8ef1a18] [✘!+?] 
➜ php -r 'require "vendor/autoload.php"; var_dump(class_exist(Klebann\MoodlePsalmPlugin\Plugin::class));'
PHP Fatal error:  Uncaught Error: Call to undefined function class_exist() in Command line code:1
Stack trace:
#0 {main}
  thrown in Command line code on line 1
```

**Comment by klebann** [comment]
```
18:16 in ~/git/psalm-moodle/local/psalm on  Main [ef8eb8ef1a18] [✘!+?] 
✘255 ➜ php -r 'require "vendor/autoload.php"; var_dump(class_exists(Klebann\MoodlePsalmPlugin\Plugin::class));'
bool(false)
```

**Comment by klebann** [comment]
Composer.json

```
{
    "require-dev": {
        "vimeo/psalm": "^4.3"
    }
}
```

**Comment by orklah** [comment]
Oh, look at the composer.json in my repo. There's a few things you need to keep
- extra > plugin
- autoload > psr4
- type > "psalm-plugin"

**Comment by klebann** [comment]
Okey I modified composer.json in plugin files.

```
{
    "name": "klebann/moodle-psalm-plugin",
    "description": "A Psalm plugin to detect unsafe usage of $DB methods with SQL",
    "type": "psalm-plugin",
    "minimum-stability": "stable",
    "license": "MIT",
    "authors": [
        {
            "name": "klebann"
        }
    ],
    "extra": {
        "psalm" : {
            "pluginClass": "Klebann\\MoodlePsalmPlugin\\Plugin"
        }
    },
    "require": {
        "php": "^7.1",
        "ext-simplexml": "*"
    },
    "autoload": {
        "psr-4": {
            "Klebann\\MoodlePsalmPlugin\\": ["."],
            "Klebann\\MoodlePsalmPlugin\\Hooks\\": ["hooks"]
        }
    },
    "require-dev": {
        "vimeo/psalm": "^4.3",
        "nikic/php-parser": "^4.0"
    }
}
```

but 
```
php -r 'require "vendor/autoload.php"; var_dump(class_exists(Klebann\MoodlePsalmPlugin\Plugin::class));'
bool(false)
```
still returns false

**Comment by andrew-demb** [comment]
@klebann did you try to run composer update or composer dump-autoload (https://getcomposer.org/doc/03-cli.md#dump-autoload-dumpautoload-) after composer.json changes?

**Comment by klebann** [comment]
Yes, I did composer update and composer dump.

Do I need to upload my psalm plugin to github?

**Comment by weirdan** [comment]
No, you don't have to necessarily host the plugin on github, it doesn't even have to be a composer package (unless you want to distribute it or manage with `psalm-plugin` cli tool). All that is required is the class referenced in `<pluginClass>` to be autoloadable.

**Comment by klebann** [comment]
`<plugins><pluginClass class="Klebann\MoodlePsalmPlugin\Plugin"/></plugins></psalm>`

**Comment by klebann** [comment]
```
composer update
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires klebann/moodle-psalm-plugin, it could not be found in any version, there may be a typo in the package name.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.
 - It's a private package and you forgot to add a custom repository to find it

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.
```

**Comment by klebann** [comment]
I added plugin to packagist.

now it returns true
```
php -r 'require "vendor/autoload.php"; var_dump(class_exists(Klebann\MoodlePsalmPlugin\Plugin::class));'
bool(true)
```

**Comment by klebann** [comment]
Why this is showing ParseError in vendor files?

```
vendor/bin/psalm --config="psalm-plugin.xml" ../../mod/checklist/autoupdate.php
Scanning files...
Analyzing files...

ERROR: ParseError - vendor/symfony/polyfill-mbstring/bootstrap80.php:125:86 - Syntax error, unexpected '=' on line 125 (see https://psalm.dev/173)
    function mb_scrub(string $string, string $encoding = null): string { $encoding ??= mb_internal_encoding(); return mb_convert_encoding($string, $encoding, $encoding); }


------------------------------
1 errors found
------------------------------

Checks took 1.02 seconds and used 71.086MB of memory
Psalm was able to infer types for 82.0359% of the codebase
```

```
<projectFiles>
        <directory name="../../mod/checklist"/>
        <ignoreFiles>
            <directory name="vendor"/>
        </ignoreFiles>
    </projectFiles>
```

**Comment by klebann** [comment]
So, thanks for reply, this worked for me:

> Oh, look at the composer.json in my repo. There's a few things you need to keep
extra > plugin
autoload > psr4
type > "psalm-plugin"

I'm closing this Issue.
