### ISSUE TITLE
MissingClass is marked as stub override, but no original counterpart found

### ISSUE THREAD

**Issue by XedinUnknown** [vimeo/psalm#5015]
When using latest stable, I get the following error in one of the projects:

```
Uncaught Exception: Class/interface/trait NS\MissingClass is marked as stub override, but no original counterpart found
Stack trace in the forked worker:
#0 /app/vendor/vimeo/psalm/src/Psalm/Internal/PhpVisitor/ReflectorVisitor.php(183): Psalm\Internal\PhpVisitor\Reflector\ClassLikeNodeScanner->start(Object(PhpParser\Node\Stmt\Class_))
#1 /app/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(200): Psalm\Internal\PhpVisitor\ReflectorVisitor->enterNode(Object(PhpParser\Node\Stmt\Class_))
#2 /app/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(114): PhpParser\NodeTraverser->traverseArray(Array)
#3 /app/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(223): PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Stmt\Namespace_))
#4 /app/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(91): PhpParser\NodeTraverser->traverseArray(Array)
#5 /app/vendor/vimeo/psalm/src/Psalm/Internal/Scanner/FileScanner.php(86): PhpParser\NodeTraverser->traverse(Array)
#6 /app/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Scanner.php(563): Psalm\Internal\Scanner\FileScanner->scan(Object(Psalm\Codebase), Object(Psalm\Storage\FileStorage), false, Object(Psalm\Progress\DefaultProgress))
#7 /app/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Scanner.php(321): Psalm\Internal\Codebase\Scanner->scanFile('/app/vendor/vim...', Array, false)
#8 /app/vendor/vimeo/psalm/src/Psalm/Internal/Fork/Pool.php(193): Psalm\Internal\Codebase\Scanner->Psalm\Internal\Codebase\{closure}(1219, '/app/vendor/vim...')
#9 /app/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Scanner.php(387): Psalm\Internal\Fork\Pool->__construct(Array, Object(Closure), Object(Closure), Object(Closure))
#10 /app/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Scanner.php(285): Psalm\Internal\Codebase\Scanner->scanFilePaths(3)
#11 /app/vendor/vimeo/psalm/src/Psalm/Codebase.php(463): Psalm\Internal\Codebase\Scanner->scanFiles(Object(Psalm\Internal\Codebase\ClassLikes), 3)
#12 /app/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/ProjectAnalyzer.php(588): Psalm\Codebase->scanFiles(3)
#13 /app/vendor/vimeo/psalm/src/psalm.php(676): Psalm\Internal\Analyzer\ProjectAnalyzer->check('/app/', true)
#14 /app/vendor/vimeo/psalm/psalm(2): require_once('/app/vendor/vim...')
#15 {main} in /app/vendor/vimeo/psalm/src/Psalm/Internal/Fork/Pool.php:357
Stack trace:
#0 /app/vendor/vimeo/psalm/src/Psalm/Internal/Fork/Pool.php(389): Psalm\Internal\Fork\Pool->readResultsFromChildren()
#1 /app/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Scanner.php(394): Psalm\Internal\Fork\Pool->wait()
#2 /app/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Scanner.php(285): Psalm\Internal\Codebase\Scanner->scanFilePaths(3)
#3 /app/vendor/vimeo/psalm/src/Psalm/Codebase.php(463): Psalm\Internal\Codebase\Scanner->scanFiles(Object(Psalm\Internal\Codebase\ClassLikes), 3)
#4 /app/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/ProjectAnalyzer.php(588): Psalm\Codebase->scanFiles(3)
#5 /app/vendor/vimeo/psalm/src/psalm.php(676): Psalm\Internal\Analyzer\ProjectAnalyzer->check('/app/', true)
#6 /app/vendor/vimeo/psalm/psalm(2): require_once('/app/vendor/vim...')
#7 {main}
(Psalm dev-master@ef4afd72bca50a0aff61599d3e433c9ee64287ac crashed due to an uncaught Throwable)
xedinunknown@XAGEN:~/projects/dhii/validator$ docker-compose run --rm test vendor/bin/psalm
Creating validator_test_run ... done
Scanning files...
Uncaught Exception: Class/interface/trait NS\MissingClass is marked as stub override, but no original counterpart found
Stack trace in the forked worker:
#0 /app/vendor/vimeo/psalm/src/Psalm/Internal/PhpVisitor/ReflectorVisitor.php(183): Psalm\Internal\PhpVisitor\Reflector\ClassLikeNodeScanner->start(Object(PhpParser\Node\Stmt\Class_))
#1 /app/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(200): Psalm\Internal\PhpVisitor\ReflectorVisitor->enterNode(Object(PhpParser\Node\Stmt\Class_))
#2 /app/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(114): PhpParser\NodeTraverser->traverseArray(Array)
#3 /app/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(223): PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Stmt\Namespace_))
#4 /app/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(91): PhpParser\NodeTraverser->traverseArray(Array)
#5 /app/vendor/vimeo/psalm/src/Psalm/Internal/Scanner/FileScanner.php(86): PhpParser\NodeTraverser->traverse(Array)
#6 /app/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Scanner.php(563): Psalm\Internal\Scanner\FileScanner->scan(Object(Psalm\Codebase), Object(Psalm\Storage\FileStorage), false, Object(Psalm\Progress\DefaultProgress))
#7 /app/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Scanner.php(321): Psalm\Internal\Codebase\Scanner->scanFile('/app/vendor/vim...', Array, false)
#8 /app/vendor/vimeo/psalm/src/Psalm/Internal/Fork/Pool.php(193): Psalm\Internal\Codebase\Scanner->Psalm\Internal\Codebase\{closure}(1219, '/app/vendor/vim...')
#9 /app/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Scanner.php(387): Psalm\Internal\Fork\Pool->__construct(Array, Object(Closure), Object(Closure), Object(Closure))
#10 /app/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Scanner.php(285): Psalm\Internal\Codebase\Scanner->scanFilePaths(3)
#11 /app/vendor/vimeo/psalm/src/Psalm/Codebase.php(463): Psalm\Internal\Codebase\Scanner->scanFiles(Object(Psalm\Internal\Codebase\ClassLikes), 3)
#12 /app/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/ProjectAnalyzer.php(588): Psalm\Codebase->scanFiles(3)
#13 /app/vendor/vimeo/psalm/src/psalm.php(676): Psalm\Internal\Analyzer\ProjectAnalyzer->check('/app/', true)
#14 /app/vendor/vimeo/psalm/psalm(2): require_once('/app/vendor/vim...')
#15 {main} in /app/vendor/vimeo/psalm/src/Psalm/Internal/Fork/Pool.php:357
Stack trace:
#0 /app/vendor/vimeo/psalm/src/Psalm/Internal/Fork/Pool.php(389): Psalm\Internal\Fork\Pool->readResultsFromChildren()
#1 /app/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Scanner.php(394): Psalm\Internal\Fork\Pool->wait()
#2 /app/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Scanner.php(285): Psalm\Internal\Codebase\Scanner->scanFilePaths(3)
#3 /app/vendor/vimeo/psalm/src/Psalm/Codebase.php(463): Psalm\Internal\Codebase\Scanner->scanFiles(Object(Psalm\Internal\Codebase\ClassLikes), 3)
#4 /app/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/ProjectAnalyzer.php(588): Psalm\Codebase->scanFiles(3)
#5 /app/vendor/vimeo/psalm/src/psalm.php(676): Psalm\Internal\Analyzer\ProjectAnalyzer->check('/app/', true)
#6 /app/vendor/vimeo/psalm/psalm(2): require_once('/app/vendor/vim...')
#7 {main}
(Psalm 4.4.0@ef4afd72bca50a0aff61599d3e433c9ee64287ac crashed due to an uncaught Throwable)
```

`psalm.xml.dist`:

```xml
<?xml version="1.0"?>
<psalm
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xmlns="https://getpsalm.org/schema/config"
        xsi:schemaLocation="https://getpsalm.org/schema/config vendor/vimeo/psalm/config.xsd"
        xmlns:xi="http://www.w3.org/2001/XInclude"
        totallyTyped="false"
        useDocblockTypes="true"
        usePhpDocMethodsWithoutMagicCall="false"
        strictBinaryOperands="true"
        rememberPropertyAssignmentsAfterCall="true"
        allowPhpStormGenerics="true"
        allowCoercionFromStringToClassConst="false"
        allowStringToStandInForClass="false"
        memoizeMethodCallResults="false"
        hoistConstants="false"
        addParamDefaultToDocblockType="false"
        checkForThrowsDocblock="true"
        checkForThrowsInGlobalScope="false"
        ignoreInternalFunctionFalseReturn="false"
        ignoreInternalFunctionNullReturn="false"
        throwExceptionOnError="false"
        hideExternalErrors="true"
        allowFileIncludes="true"
>
    <projectFiles>
        <directory name="src"/>
        <ignoreFiles>
            <directory name="vendor"/>
        </ignoreFiles>
    </projectFiles>

    <extraFiles>
        <ignoreFiles>
            <directory name="vendor/phpunit/php-code-coverage/tests"/>
            <directory name="vendor/phpspec/prophecy"/>
        </ignoreFiles>
        <directory name="vendor" />
    </extraFiles>


    <issueHandlers>
        <ConflictingReferenceConstraint errorLevel="error"/>
        <ContinueOutsideLoop errorLevel="error"/>
        <DuplicateArrayKey errorLevel="error"/>
        <DuplicateClass errorLevel="error"/>
        <DuplicateFunction errorLevel="error"/>
        <DuplicateMethod errorLevel="error"/>
        <DuplicateParam errorLevel="error"/>
        <EmptyArrayAccess errorLevel="error"/>
        <FalsableReturnStatement errorLevel="error"/>
        <FalseOperand errorLevel="error"/>
        <ForbiddenCode errorLevel="error"/>
        <ForbiddenEcho errorLevel="error"/>
        <InaccessibleClassConstant errorLevel="error"/>
        <InaccessibleMethod errorLevel="error"/>
        <InterfaceInstantiation errorLevel="error"/>
        <InaccessibleProperty errorLevel="error"/>
        <InternalClass errorLevel="error"/>
        <InternalMethod errorLevel="error"/>
        <InternalProperty errorLevel="error"/>
        <InvalidArgument errorLevel="error"/>
        <InvalidArrayAccess errorLevel="error"/>
        <InvalidArrayAssignment errorLevel="error"/>
        <InvalidArrayOffset errorLevel="error"/>
        <InvalidCast errorLevel="error"/>
        <InvalidCatch errorLevel="error"/>
        <InvalidClass errorLevel="error"/>
        <InvalidClone errorLevel="error"/>
        <InvalidFalsableReturnType errorLevel="error"/>
        <InvalidThrow errorLevel="error"/>
        <InvalidToString errorLevel="error"/>
        <LoopInvalidation errorLevel="error"/>
        <InvalidNullableReturnType errorLevel="error"/>
        <LessSpecificReturnType errorLevel="error"/>
        <InvalidGlobal errorLevel="error"/>
        <InvalidIterator errorLevel="error"/>
        <InvalidMethodCall errorLevel="error"/>
        <InvalidFunctionCall errorLevel="error"/>
        <ImplicitToStringCast errorLevel="error"/>
        <ImplementedReturnTypeMismatch errorLevel="error"/>
        <InvalidParamDefault errorLevel="error"/>
        <InvalidPassByReference errorLevel="error"/>
        <InvalidPropertyAssignment errorLevel="error"/>
        <InvalidPropertyAssignmentValue errorLevel="error"/>
        <InvalidPropertyFetch errorLevel="error"/>
        <InvalidReturnStatement errorLevel="error"/>
        <InvalidReturnType errorLevel="error"/>
        <InvalidScalarArgument errorLevel="error"/>
        <InvalidScope errorLevel="error"/>
        <InvalidStaticInvocation errorLevel="error"/>
        <MissingConstructor errorLevel="error"/>
        <MissingDependency errorLevel="error"/>
        <MissingFile errorLevel="error"/>
        <MixedArgument errorLevel="error"/>
        <MoreSpecificImplementedParamType errorLevel="error"/>
        <MoreSpecificReturnType errorLevel="error"/>
        <NoValue errorLevel="error"/>
        <NoInterfaceProperties errorLevel="error"/>
        <NonStaticSelfCall errorLevel="error"/>
        <NullableReturnStatement errorLevel="error"/>
        <NullArgument errorLevel="error"/>
        <NullArrayAccess errorLevel="error"/>
        <NullArrayOffset errorLevel="error"/>
        <NullFunctionCall errorLevel="error"/>
        <NullIterator errorLevel="error"/>
        <NullOperand errorLevel="error"/>
        <NullPropertyAssignment errorLevel="error"/>
        <NullPropertyFetch errorLevel="error"/>
        <NullReference errorLevel="error"/>
        <OverriddenMethodAccess errorLevel="error"/>
        <OverriddenPropertyAccess errorLevel="error"/>
        <ParadoxicalCondition errorLevel="error"/>
        <ParentNotFound errorLevel="error"/>
        <LessSpecificImplementedReturnType errorLevel="error"/>
        <MissingParamType errorLevel="error"/>
        <MissingClosureParamType errorLevel="error"/>
        <MissingClosureReturnType errorLevel="error"/>
        <MissingPropertyType errorLevel="error"/>
        <UndefinedConstant errorLevel="error"/>

        <AssignmentToVoid errorLevel="info"/>
        <DeprecatedClass errorLevel="info"/>
        <DeprecatedConstant errorLevel="info"/>
        <DeprecatedTrait errorLevel="info"/>
        <DocblockTypeContradiction errorLevel="info"/>
        <InvalidDocblock errorLevel="info"/>
        <InvalidDocblockParamName errorLevel="info"/>
        <InvalidTemplateParam errorLevel="info"/>
        <DeprecatedInterface errorLevel="info"/>
        <DeprecatedMethod errorLevel="info"/>
        <DeprecatedProperty errorLevel="info"/>
        <MethodSignatureMustOmitReturnType errorLevel="info"/>
        <MismatchingDocblockParamType errorLevel="info"/>
        <MismatchingDocblockReturnType errorLevel="info"/>
        <MissingDocblockType errorLevel="info"/>
        <MissingParamType errorLevel="info"/>
        <MissingTemplateParam errorLevel="info"/>
        <MissingThrowsDocblock errorLevel="info"/>
        <MixedArgumentTypeCoercion errorLevel="info"/>
        <MixedArrayAccess errorLevel="info"/>
        <MixedArrayAssignment errorLevel="info"/>
        <MixedArrayOffset errorLevel="info"/>
        <MixedArrayTypeCoercion errorLevel="info"/>
        <MixedAssignment errorLevel="info"/>
        <MixedFunctionCall errorLevel="info"/>
        <MixedInferredReturnType errorLevel="info"/>
        <MixedMethodCall errorLevel="info"/>
        <MixedOperand errorLevel="info"/>
        <MixedPropertyAssignment errorLevel="info"/>
        <MixedPropertyFetch errorLevel="info"/>
        <MixedPropertyTypeCoercion errorLevel="info"/>
        <MixedReturnStatement errorLevel="info"/>
        <MixedReturnTypeCoercion errorLevel="info"/>
        <MixedStringOffsetAssignment errorLevel="info"/>
    </issueHandlers>
</psalm>
```

Same happens on `master`. I am able to use Psalm no problem in other projects, so far. Of course, I made sure all vendor libs are re-installed by first removing the `vendor` folder.

**Comment by weirdan** [comment]
Somehow https://github.com/vimeo/psalm/blob/master/tests/fixtures/stubs/MissingClass.php gets picked up. Does you other projects use `extraFiles=vendor`? And why would you need it at all?

**Comment by XedinUnknown** [comment]
Thanks for the reply! I have `vendor` in `extraFiles` because when I was setting up Psalmm a long time ago, it looked like one needs to specify everything that should be scanned but not analyzed there, and it wasn't very clear that `vendor` is automatically included in scanning and excluded from analysis. In fact, I now removed it, and the problem appears to have gone away: I now see legit Psalm errors. So, I guess the question remains: if Psalm automatically adds `vendor` to scanned files, and excludes it from analyzed files, then why isn't `MissingClass` being picked up now

**Comment by orklah** [comment]
Psalm automatically use composer to load your dependancies, whether or not you specify it. ExtraFiles are needed when your autoloader is not enough to load classes or functions.

**Comment by weirdan** [comment]
:point_up: this.

**Comment by DWMcload** [comment]
Hi, I've a very similar issue in my phpstorm. When it is running psalm checks, I always get the following error message:
```
Psalm
			psalm: Scanning files...
			Uncaught Psalm\Exception\InvalidClasslikeOverrideException: Class/interface/trait Sonata\AdminBundle\Admin\AdminInterface is marked as stub override, but no original counterpart found in /Users/mcload/Sites/zorro/vendor/vimeo/psalm/src/Psalm/Internal/PhpVisitor/Reflector/ClassLikeNodeScanner.php:334
			Stack trace:
			#0 /Users/mcload/Sites/zorro/vendor/vimeo/psalm/src/Psalm/Internal/PhpVisitor/ReflectorVisitor.php(183): Psalm\Internal\PhpVisitor\Reflector\ClassLikeNodeScanner->start(Object(PhpParser\Node\Stmt\Interface_))
```
			
I do not have vendor in extraFiles. If I remove the marked as stub override, then a second class pops up with the same error and so on. Any ideas for help?

Would appreciate it, thank you.
