### ISSUE TITLE
Uncaught exception running Psalm 4.4.1

### ISSUE THREAD

**Issue by jaikdean** [vimeo/psalm#5025]
I'm updating a project from Psalm 3 to 4, and have run into a crash caused by an uncaught exception. I'm running PHP 7.4.13, and I've confirmed this crash appears in the latest versions of 4.4, 4.3.

I think I've narrowed down the file that's causing the crash, but am unable to share it as it's part of a private, commercial project. Is there anything I can do to aid debugging?

```
$ vendor/bin/psalm --debug-by-line --threads=1
…
Uncaught Psalm\Exception\ComplicatedExpressionException in /Users/jaikdean/Documents/REDACTED/vendor/vimeo/psalm/src/Psalm/Internal/Algebra.php:408
Stack trace:
#0 /Users/jaikdean/Documents/REDACTED/vendor/vimeo/psalm/src/Psalm/Internal/Algebra.php(573): Psalm\Internal\Algebra::groupImpossibilities(Array)
#1 /Users/jaikdean/Documents/REDACTED/vendor/vimeo/psalm/src/Psalm/Internal/PhpVisitor/Reflector/FunctionLikeNodeScanner.php(300): Psalm\Internal\Algebra::negateFormula(NULL)
#2 /Users/jaikdean/Documents/REDACTED/vendor/vimeo/psalm/src/Psalm/Internal/PhpVisitor/ReflectorVisitor.php(233): Psalm\Internal\PhpVisitor\Reflector\FunctionLikeNodeScanner->start(Object(PhpParser\Node\Stmt\ClassMethod))
#3 /Users/jaikdean/Documents/REDACTED/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(200): Psalm\Internal\PhpVisitor\ReflectorVisitor->enterNode(Object(PhpParser\Node\Stmt\ClassMethod))
#4 /Users/jaikdean/Documents/REDACTED/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(114): PhpParser\NodeTraverser->traverseArray(Array)
#5 /Users/jaikdean/Documents/REDACTED/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(223): PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Stmt\Class_))
#6 /Users/jaikdean/Documents/REDACTED/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(114): PhpParser\NodeTraverser->traverseArray(Array)
#7 /Users/jaikdean/Documents/REDACTED/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(223): PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Stmt\Namespace_))
#8 /Users/jaikdean/Documents/REDACTED/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(91): PhpParser\NodeTraverser->traverseArray(Array)
#9 /Users/jaikdean/Documents/REDACTED/vendor/vimeo/psalm/src/Psalm/Internal/Scanner/FileScanner.php(86): PhpParser\NodeTraverser->traverse(Array)
#10 /Users/jaikdean/Documents/REDACTED/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Scanner.php(563): Psalm\Internal\Scanner\FileScanner->scan(Object(Psalm\Codebase), Object(Psalm\Storage\FileStorage), false, Object(Psalm\Progress\DebugProgress))
#11 /Users/jaikdean/Documents/REDACTED/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Scanner.php(321): Psalm\Internal\Codebase\Scanner->scanFile('/Users/jaikdean...', Array, true)
#12 /Users/jaikdean/Documents/REDACTED/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Scanner.php(433): Psalm\Internal\Codebase\Scanner->Psalm\Internal\Codebase\{closure}(518, '/Users/jaikdean...')
#13 /Users/jaikdean/Documents/REDACTED/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Scanner.php(285): Psalm\Internal\Codebase\Scanner->scanFilePaths(1)
#14 /Users/jaikdean/Documents/REDACTED/vendor/vimeo/psalm/src/Psalm/Codebase.php(463): Psalm\Internal\Codebase\Scanner->scanFiles(Object(Psalm\Internal\Codebase\ClassLikes), 1)
#15 /Users/jaikdean/Documents/REDACTED/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/ProjectAnalyzer.php(588): Psalm\Codebase->scanFiles(1)
#16 /Users/jaikdean/Documents/REDACTED/vendor/vimeo/psalm/src/psalm.php(676): Psalm\Internal\Analyzer\ProjectAnalyzer->check('/Users/jaikdean...', true)
#17 /Users/jaikdean/Documents/REDACTED/vendor/vimeo/psalm/psalm(2): require_once('/Users/jaikdean...')
#18 {main}
(Psalm 4.4.1@9fd7a7d885b3a216cff8dec9d8c21a132f275224 crashed due to an uncaught Throwable)
```

**Comment by weirdan** [comment]
This works though: https://psalm.dev/r/388881f12a

**Comment by muglug** [comment]
Ah ok this is happening in `ReflectorVisitor` due to the function starting with the name `assert`, and errors caught elsewhere are not being caught there
