### ISSUE TITLE
how to debug: "Child terminated with return code 0 and signal 9" and "Could not get class storage"

### ISSUE THREAD

**Issue by michabbb** [vimeo/psalm#5056]
hi there,

while trying to scan a whole project, I got the error:

`Uncaught Exception: Could not get class storage for kint`
 [here's the output](https://gist.github.com/michabbb/74e97bd2358521e73d1139bb301f8127).
(Kint can be found [here](https://github.com/kint-php/kint))

because I don´t know how to fix this, I just tried to ignore "Kint" at this point: 
`vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Properties.php` and added:

```php
/** in method propertyExists */
if ($fq_class_name==='Kint') {
  return false;
}
```

just to see, what happens. with that change I got the error:

```
Scanning files...
Analyzing files...

E░░EE░░░░░E░░░░E░EE░EEEE░░E░░░E░E░EEE░E░EEEEEEEEEEEEEEEEE░EE  60 / 791 (7%)
░EEEEEEEEEEEEEEEEEEE░EEEEEEEEEEEEEEE░EEEE░░E░EE░E░░EEEEE░EEE 120 / 791 (15%)
EEEEEEEEEEEEEEEEEEEEEEEE░E░EEE░EEEEEEEEEEE░E░E░░░E░E░░░░E░EE 180 / 791 (22%)
EE░EEE░░EEEEEEEEEEEEEEEEEEEE░E░░░░EEEEEE░░░░░░░░EEEEE░░E░░░E 240 / 791 (30%)
EEE░EEEE░EEEEEEEEEEEEEEEEEEEEEEEEEEE░░E░E░EEEE░░EEEEEEEEEEE░ 300 / 791 (37%)
E░░░░░░EEEEEEEEEEE░░EEEEEE░░░E░EEE░EE░░░░░░░EEEEEE░░EE░░░EEE 360 / 791 (45%)
░EEE░░EEEEEEEEEEEEEEEEEEE░EEEEEE░░E░░░EEEE░░░░░░░░EEEEE░░EE░ 420 / 791 (53%)
░░░EEE░E░E░EEEEEEEEEEEEEEEEEE░EEEEEEEEE░EE░EE░E░E░░░░░░░EEEE 480 / 791 (60%)
E░░EE░░░░░░E░EEE░EEEEEE░EEEEEEEEEEE░EEEEEEEEE░EEEEEEEEE░░░░░ 540 / 791 (68%)
░░EEEEEChild terminated with return code 0 and signal 9
```

after digging in psalm issues I have seen, that people tried to use `--debug-by-line` but I don´t see anything,
running psalm multiple times, show me different files and different lines before psalm gets terminated.
I removed `--threads` and disabled opcache, I tried PHP 7.4 and 8.0.1, same problems.
I tested with and without `--no-cache`, same results.

psalm version: `Psalm 4.3.2@57b53ff26237074fdf5cbcb034f7da5172be4524`
PHP: tested with 7.4 and 8.0.1 (with and without opcache) also tried `pcre.jit=0` but has no effect

so please let me know, how I can debug these errors and find the piece of code that is responsible for all this.

thanks!

**Comment by muglug** [comment]
Have you tried `--threads=1`?

**Comment by weirdan** [comment]
9 is `SIGKILL`, indicating the process has been likely killed by OOM killer (more info should be available in `dmesg`).

**Comment by michabbb** [comment]
@muglug same result with `--threads=1`

**Comment by michabbb** [comment]
@weirdan good notice, yes, i made a `htop` while running and i see, that my dev host is running out of memory 😖 

```
[29375.143027] Out of memory: Kill process 10382 (php) score 436 or sacrifice child
[29375.143996] Killed process 10382 (php) total-vm:3634448kB, anon-rss:3197508kB, file-rss:0kB, shmem-rss:0kB
```
okay, simple as that but this didn´t come into my mind, sorry 🙈 

but how can i debug the error `Could not get class storage for kint` ??

**Comment by weirdan** [comment]
Can you provide a minimal reproducer in a separate repo? 


<details>
<summary>Note: Backtrace from the gist</summary>

```
Stack trace in the forked worker:
#0 /app/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Properties.php(100): Psalm\Internal\Provider\ClassLikeStorageProvider->get('Kint')
#1 /app/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/Statements/Expression/Fetch/StaticPropertyFetchAnalyzer.php(231): Psalm\Internal\Codebase\Properties->propertyExists('Kint::$plugins', true, Object(Psalm\Internal\Analyzer\StatementsAnalyzer), Object(Psalm\Context), NULL)
#2 /app/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/Statements/ExpressionAnalyzer.php(219): Psalm\Internal\Analyzer\Statements\Expression\Fetch\StaticPropertyFetchAnalyzer::analyze(Object(Psalm\Internal\Analyzer\StatementsAnalyzer), Object(PhpParser\Node\Expr\StaticPropertyFetch), Object(Psalm\Context))
#3 /app/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/Statements/ExpressionAnalyzer.php(39): Psalm\Internal\Analyzer\Statements\ExpressionAnalyzer::handleExpression(Object(Psalm\Internal\Analyzer\StatementsAnalyzer), Object(PhpParser\Node\Expr\StaticPropertyFetch), Object(Psalm\Context), true, NULL, false)
#4 /app/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/Statements/Expression/Assignment/ArrayAssignmentAnalyzer.php(89): Psalm\Internal\Analyzer\Statements\ExpressionAnalyzer::analyze(Object(Psalm\Internal\Analyzer\StatementsAnalyzer), Object(PhpParser\Node\Expr\StaticPropertyFetch), Object(Psalm\Context), true)
#5 /app/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/Statements/Expression/Assignment/ArrayAssignmentAnalyzer.php(51): Psalm\Internal\Analyzer\Statements\Expression\Assignment\ArrayAssignmentAnalyzer::updateArrayType(Object(Psalm\Internal\Analyzer\StatementsAnalyzer), Object(PhpParser\Node\Expr\ArrayDimFetch), Object(PhpParser\Node\Scalar\String_), Object(Psalm\Type\Union), Object(Psalm\Context))
#6 /app/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/Statements/Expression/AssignmentAnalyzer.php(442): Psalm\Internal\Analyzer\Statements\Expression\Assignment\ArrayAssignmentAnalyzer::analyze(Object(Psalm\Internal\Analyzer\StatementsAnalyzer), Object(PhpParser\Node\Expr\ArrayDimFetch), Object(Psalm\Context), Object(PhpParser\Node\Scalar\String_), Object(Psalm\Type\Union))
#7 /app/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/Statements/ExpressionAnalyzer.php(132): Psalm\Internal\Analyzer\Statements\Expression\AssignmentAnalyzer::analyze(Object(Psalm\Internal\Analyzer\StatementsAnalyzer), Object(PhpParser\Node\Expr\ArrayDimFetch), Object(PhpParser\Node\Scalar\String_), Object(Psalm\Type\Union), Object(Psalm\Context), NULL)
#8 /app/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/Statements/ExpressionAnalyzer.php(39): Psalm\Internal\Analyzer\Statements\ExpressionAnalyzer::handleExpression(Object(Psalm\Internal\Analyzer\StatementsAnalyzer), Object(PhpParser\Node\Expr\Assign), Object(Psalm\Context), false, NULL, true)
#9 /app/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/StatementsAnalyzer.php(522): Psalm\Internal\Analyzer\Statements\ExpressionAnalyzer::analyze(Object(Psalm\Internal\Analyzer\StatementsAnalyzer), Object(PhpParser\Node\Expr\Assign), Object(Psalm\Context), false, NULL, true)
#10 /app/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/StatementsAnalyzer.php(171): Psalm\Internal\Analyzer\StatementsAnalyzer::analyzeStatement(Object(Psalm\Internal\Analyzer\StatementsAnalyzer), Object(PhpParser\Node\Stmt\Expression), Object(Psalm\Context), NULL)
#11 /app/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/Statements/Block/IfElse/IfAnalyzer.php(56): Psalm\Internal\Analyzer\StatementsAnalyzer->analyze(Array, Object(Psalm\Context))
#12 /app/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/Statements/Block/IfElseAnalyzer.php(346): Psalm\Internal\Analyzer\Statements\Block\IfElse\IfAnalyzer::analyze(Object(Psalm\Internal\Analyzer\StatementsAnalyzer), Object(PhpParser\Node\Stmt\If_), Object(Psalm\Internal\Scope\IfScope), Object(Psalm\Internal\Scope\IfConditionalScope), Object(Psalm\Context), Object(Psalm\Context), Object(Psalm\Context), Array)
#13 /app/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/StatementsAnalyzer.php(470): Psalm\Internal\Analyzer\Statements\Block\IfElseAnalyzer::analyze(Object(Psalm\Internal\Analyzer\StatementsAnalyzer), Object(PhpParser\Node\Stmt\If_), Object(Psalm\Context))
#14 /app/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/StatementsAnalyzer.php(171): Psalm\Internal\Analyzer\StatementsAnalyzer::analyzeStatement(Object(Psalm\Internal\Analyzer\StatementsAnalyzer), Object(PhpParser\Node\Stmt\If_), Object(Psalm\Context), NULL)
#15 /app/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/Statements/Block/IfElse/IfAnalyzer.php(56): Psalm\Internal\Analyzer\StatementsAnalyzer->analyze(Array, Object(Psalm\Context))
#16 /app/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/Statements/Block/IfElseAnalyzer.php(346): Psalm\Internal\Analyzer\Statements\Block\IfElse\IfAnalyzer::analyze(Object(Psalm\Internal\Analyzer\StatementsAnalyzer), Object(PhpParser\Node\Stmt\If_), Object(Psalm\Internal\Scope\IfScope), Object(Psalm\Internal\Scope\IfConditionalScope), Object(Psalm\Context), Object(Psalm\Context), Object(Psalm\Context), Array)
#17 /app/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/StatementsAnalyzer.php(470): Psalm\Internal\Analyzer\Statements\Block\IfElseAnalyzer::analyze(Object(Psalm\Internal\Analyzer\StatementsAnalyzer), Object(PhpParser\Node\Stmt\If_), Object(Psalm\Context))
#18 /app/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/StatementsAnalyzer.php(171): Psalm\Internal\Analyzer\StatementsAnalyzer::analyzeStatement(Object(Psalm\Internal\Analyzer\StatementsAnalyzer), Object(PhpParser\Node\Stmt\If_), Object(Psalm\Context), NULL)
#19 /app/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/Statements/Block/IfElse/IfAnalyzer.php(56): Psalm\Internal\Analyzer\StatementsAnalyzer->analyze(Array, Object(Psalm\Context))
#20 /app/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/Statements/Block/IfElseAnalyzer.php(346): Psalm\Internal\Analyzer\Statements\Block\IfElse\IfAnalyzer::analyze(Object(Psalm\Internal\Analyzer\StatementsAnalyzer), Object(PhpParser\Node\Stmt\If_), Object(Psalm\Internal\Scope\IfScope), Object(Psalm\Internal\Scope\IfConditionalScope), Object(Psalm\Context), Object(Psalm\Context), Object(Psalm\Context), Array)
#21 /app/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/StatementsAnalyzer.php(470): Psalm\Internal\Analyzer\Statements\Block\IfElseAnalyzer::analyze(Object(Psalm\Internal\Analyzer\StatementsAnalyzer), Object(PhpParser\Node\Stmt\If_), Object(Psalm\Context))
#22 /app/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/StatementsAnalyzer.php(171): Psalm\Internal\Analyzer\StatementsAnalyzer::analyzeStatement(Object(Psalm\Internal\Analyzer\StatementsAnalyzer), Object(PhpParser\Node\Stmt\If_), Object(Psalm\Context), NULL)
#23 /app/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/FileAnalyzer.php(186): Psalm\Internal\Analyzer\StatementsAnalyzer->analyze(Array, Object(Psalm\Context), NULL, true)
#24 /app/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Analyzer.php(340): Psalm\Internal\Analyzer\FileAnalyzer->analyze(NULL)
#25 /app/vendor/vimeo/psalm/src/Psalm/Internal/Fork/Pool.php(193): Psalm\Internal\Codebase\Analyzer->Psalm\Internal\Codebase\{closure}(47, '/app...')
#26 /app/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Analyzer.php(406): Psalm\Internal\Fork\Pool->__construct(Array, Object(Closure), Object(Closure), Object(Closure), Object(Closure))
#27 /app/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Analyzer.php(269): Psalm\Internal\Codebase\Analyzer->doAnalysis(Object(Psalm\Internal\Analyzer\ProjectAnalyzer), 3)
#28 /app/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/ProjectAnalyzer.php(638): Psalm\Internal\Codebase\Analyzer->analyzeFiles(Object(Psalm\Internal\Analyzer\ProjectAnalyzer), 3, false, true)
#29 /app/vendor/vimeo/psalm/src/psalm.php(676): Psalm\Internal\Analyzer\ProjectAnalyzer->check('/app...', true)
#30 /app/vendor/vimeo/psalm/psalm(2): require_once('/app...')
#31 {main} in /app/vendor/vimeo/psalm/src/Psalm/Internal/Fork/Pool.php:357
Stack trace:
#0 /app/vendor/vimeo/psalm/src/Psalm/Internal/Fork/Pool.php(389): Psalm\Internal\Fork\Pool->readResultsFromChildren()
#1 /app/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Analyzer.php(473): Psalm\Internal\Fork\Pool->wait()
#2 /app/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Analyzer.php(269): Psalm\Internal\Codebase\Analyzer->doAnalysis(Object(Psalm\Internal\Analyzer\ProjectAnalyzer), 3)
#3 /app/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/ProjectAnalyzer.php(638): Psalm\Internal\Codebase\Analyzer->analyzeFiles(Object(Psalm\Internal\Analyzer\ProjectAnalyzer), 3, false, true)
#4 /app/vendor/vimeo/psalm/src/psalm.php(676): Psalm\Internal\Analyzer\ProjectAnalyzer->check('/app...', true)
#5 /app/vendor/vimeo/psalm/psalm(2): require_once('/app...')
#6 {main}
(Psalm 4.3.2@57b53ff26237074fdf5cbcb034f7da5172be4524 crashed due to an uncaught Throwable)
```

</details>

**Comment by michabbb** [comment]
@weirdan https://github.com/michabbb/test-psalm-kint
calling psalm with `--show-info --find-unused-psalm-suppress --show-info --threads=1`
I found the line that causes the error, but I still don´t know why or how to fix it 😏

**Comment by michabbb** [comment]
oh... 💡 ... it seems like I have to add `use Kint\Kint;` 🤔 then I don´t get that error.

**Comment by michabbb** [comment]
so in case that is the problem, the last question would be: is there anything I can do if my host runs out of memory?
I mean, something else than giving the host more memory? 😏 are there any options to tell psalm to scan things
sequential instead of parallel or something like that?

**Comment by weirdan** [comment]
`--threads=1` disables parallel processing. Ignore `vendor` dir (you seem to be doing it already). Make sure composer autoloader is working for you (run with `--debug` and check that there are more 'Using composer to locate file' lines than 'Using reflection to locate file'). Other than that, I'm not sure what can be done to conserve memory.

**Comment by orklah** [comment]
Try to disable cache. In certain conditions, it be very memory consuming. You'll trade analysis time for memory though...

**Comment by michabbb** [comment]
```
grep -i "Using composer to locate file" /tmp/psalm.debug|wc -l
2191
grep -i "Using reflection to locate file" /tmp/psalm.debug|wc -l
179
```
okay, I guess this looks "okay". before the memory is running out, I can see in the debug output,
that psalm always halts at one specific file. the code there is very messy and there are extreme long
"if" "else" in there... I will do further checks...

@orklah thanks for the tip, but using `--no-cache` doesn´t change anything in my situation.

**Comment by michabbb** [comment]
funny... please don´t blame for this 10-year-old code 🙈 😂 but psalm stops [here](https://gist.github.com/michabbb/bebccc1fdb3aacae3a3595e459ce7ec8#file-test-php-L18) and runs out of memory.
if the method `checkAUTH` gets modified like: `return false;` instead of this super terrible long compare.... then psalm runs without any issues and finishes its scan and offers me a result 😏

**Comment by weirdan** [comment]
This expression requires more than 16GB of memory to analyze.

**Comment by michabbb** [comment]
@weirdan in case that is a statement and not a question: why? pardon, I am not that familiar with psalms internals.

**Comment by weirdan** [comment]
That's empirical fact - I've run Psalm locally on that gist and it crashed after hitting the memory limit I've set (16GB).

**Comment by michabbb** [comment]
but just for interest to understand this better: what exactly is psalm doing there? does psalm internally generate millions of combinations of this compare to find problems? something like that?

**Comment by michabbb** [comment]
btw, I will close this issue, because all my (main) questions are answered and I learned a lot. 
a big thank you to everybody who is involved here! 👍

**Comment by weirdan** [comment]
Unhandled exception still needs to be addressed (https://github.com/vimeo/psalm/issues/5056#issuecomment-763509642).

**Comment by weirdan** [comment]
This is the part that confuses Psalm:
```
if ((!\defined('KINT_SKIP_FACADE') || !KINT_SKIP_FACADE) && !\class_exists('Kint')) {
    \class_alias('Kint\\Kint', 'Kint');
}
```
Reproducer: https://psalm.dev/r/85a57c9dbe

Probable solution is to make `propertyExist()` handle the class name here:

https://github.com/vimeo/psalm/blob/9e0525439d3024e12b3402b2ef7f908ca2cb2e56/src/Psalm/Internal/Codebase/Properties.php#L97

the same way as `methodExists()` does: 
https://github.com/vimeo/psalm/blob/9e0525439d3024e12b3402b2ef7f908ca2cb2e56/src/Psalm/Internal/Codebase/Methods.php#L111-L117
