### ISSUE TITLE
Uncaught OutOfBoundsException: Package "vimeo/psalm" is not installed

### ISSUE THREAD

**Issue by esbobkov** [vimeo/psalm#5120]
I have installed Psalm 4.3.2 in custom directory of project

my `composer.json` in `tools/psalm`
```
{
    "require": {
        "vimeo/psalm": "^4.3"
    }
}
```

Run it in this way
```
/opt/app $ ./tools/psalm/vendor/bin/psalm --version
Psalm 4.3.2@57b53ff26237074fdf5cbcb034f7da5172be4524
```

After upgrade Psalm to 4.4.0 I get error
```
/opt/app $ ./tools/psalm/vendor/bin/psalm --version
Uncaught OutOfBoundsException: Package "vimeo/psalm" is not installed in /opt/app/vendor/composer/InstalledVersions.php:2151
Stack trace:
#0 /opt/app/tools/psalm/vendor/composer/package-versions-deprecated/src/PackageVersions/Versions.php(99): Composer\InstalledVersions::getPrettyVersion('vimeo/psalm')
#1 /opt/app/tools/psalm/vendor/vimeo/psalm/src/command_functions.php(132): PackageVersions\Versions::getVersion('vimeo/psalm')
#2 /opt/app/tools/psalm/vendor/vimeo/psalm/src/psalm.php(277): Psalm\requireAutoloaders('/opt/app/', false, 'vendor')
#3 /opt/app/tools/psalm/vendor/vimeo/psalm/src/Psalm/Internal/IncludeCollector.php(34): Psalm\{closure}()
#4 /opt/app/tools/psalm/vendor/vimeo/psalm/src/psalm.php(278): Psalm\Internal\IncludeCollector->runAndCollect(Object(Closure))
#5 /opt/app/tools/psalm/vendor/vimeo/psalm/psalm(2): require_once('/opt/app/tools/...')
#6 {main}
(Psalm (unknown version) crashed due to an uncaught Throwable)

```

**Comment by esbobkov** [comment]
Issue has gone after update Composer to [2.0.9](https://github.com/composer/composer/releases/tag/2.0.9)
