### ISSUE TITLE
[regression] TypeError in LoopAnalyzer

### ISSUE THREAD

**Issue by orklah** [vimeo/psalm#5189]
On last master, I get this stack:

```
Uncaught TypeError: Argument 2 passed to Psalm\Type::combineUnionTypes() must be an instance of Psalm\Type\Union, null given, called in C:\...\vendor\vimeo\psalm\src\Psalm\Internal\Analyzer\Statements\Block\LoopAnalyzer.php on line 428 and defined in C:\...\vendor\vimeo\psalm\src\Psalm\Type.php:406

Stack trace:

#0 C:\...\vendor\vimeo\psalm\src\Psalm\Internal\Analyzer\Statements\Block\LoopAnalyzer.php(428): Psalm\Type::combineUnionTypes(Object(Psalm\Type\Union), NULL)

#1 C:\...\vendor\vimeo\psalm\src\Psalm\Internal\Analyzer\Statements\Block\ForAnalyzer.php(86): Psalm\Internal\Analyzer\Statements\Block\LoopAnalyzer::analyze(Object(Psalm\Internal\Analyzer\StatementsAnalyzer), Array, Array, Array, Object(Psalm\Internal\Scope\LoopScope), Object(Psalm\Context))

#2 C:\...\vendor\vimeo\psalm\src\Psalm\Internal\Analyzer\StatementsAnalyzer.php(486): Psalm\Internal\Analyzer\Statements\Block\ForAnalyzer::analyze(Object(Psalm\Internal\Analyzer\StatementsAnalyzer), Object(PhpParser\Node\Stmt\For_), Object(Psalm\Context))

#3 C:\...\vendor\vimeo\psalm\src\Psalm\Internal\Analyzer\StatementsAnalyzer.php(172): Psalm\Internal\Analyzer\StatementsAnalyzer::analyzeStatement(Object(Psalm\Internal\Analyzer\StatementsAnalyzer), Object(PhpParser\Node\Stmt\For_), Object(Psalm\Context), Object(Psalm\Context))

#4 C:\...\vendor\vimeo\psalm\src\Psalm\Internal\Analyzer\FunctionLikeAnalyzer.php(416): Psalm\Internal\Analyzer\StatementsAnalyzer->analyze(Array, Object(Psalm\Context), Object(Psalm\Context), true)

#5 C:\...\vendor\vimeo\psalm\src\Psalm\Internal\Analyzer\ClassAnalyzer.php(1694): Psalm\Internal\Analyzer\FunctionLikeAnalyzer->analyze(Object(Psalm\Context), Object(Psalm\Internal\Provider\NodeDataProvider), Object(Psalm\Context))

#6 C:\...\vendor\vimeo\psalm\src\Psalm\Internal\Analyzer\ClassAnalyzer.php(390): Psalm\Internal\Analyzer\ClassAnalyzer->analyzeClassMethod(Object(PhpParser\Node\Stmt\ClassMethod), Object(Psalm\Storage\ClassLikeStorage), Object(Psalm\Internal\Analyzer\ClassAnalyzer), Object(Psalm\Context), Object(Psalm\Context))

#7 C:\...\vendor\vimeo\psalm\src\Psalm\Internal\Analyzer\FileAnalyzer.php(213): Psalm\Internal\Analyzer\ClassAnalyzer->analyze(Object(Psalm\Context), Object(Psalm\Context))

#8 C:\...\vendor\vimeo\psalm\src\Psalm\Internal\Codebase\Analyzer.php(340): Psalm\Internal\Analyzer\FileAnalyzer->analyze(NULL)

#9 C:\...\vendor\vimeo\psalm\src\Psalm\Internal\Codebase\Analyzer.php(584): Psalm\Internal\Codebase\Analyzer->Psalm\Internal\Codebase\{closure}(7373, 'C:\\...')

#10 C:\...\vendor\vimeo\psalm\src\Psalm\Internal\Codebase\Analyzer.php(269): Psalm\Internal\Codebase\Analyzer->doAnalysis(Object(Psalm\Internal\Analyzer\ProjectAnalyzer), 1)

#11 C:\...\vendor\vimeo\psalm\src\Psalm\Internal\Analyzer\ProjectAnalyzer.php(636): Psalm\Internal\Codebase\Analyzer->analyzeFiles(Object(Psalm\Internal\Analyzer\ProjectAnalyzer), 1, false, true)

#12 C:\...\vendor\vimeo\psalm\src\psalm.php(681): Psalm\Internal\Analyzer\ProjectAnalyzer->check('C:\\...', true)

#13 C:\...\vendor\vimeo\psalm\psalm(2): require_once('C:\\...')

#14 {main}

(Psalm dev-master@2dc86651a411df6c673079b37df20103705bb4d2 crashed due to an uncaught Throwable)
```

I'm still tracking the incriminated code

**Comment by orklah** [comment]
Well the code is not really special. It's a catch inside a for loop that push the exception to a method

**Comment by muglug** [comment]
I should have a fix pushed in five minutes

**Comment by muglug** [comment]
More like 20 minutes. Try with ccdb29abf
