### ISSUE TITLE
Uncaught InvalidArgumentException: Could not get class storage for yii\gii\module

### ISSUE THREAD

**Issue by Patrick-Remy** [vimeo/psalm#5307]
When running psalm with cache it throws `Could not get class storage for yii\gii\module`. After `rm -rf .psalm.cache` the issue is gone one time, but after a second execution it fails with the same error. So it looks like it is cache related.

The code that causes the issue looks like
```php
define('ENV', getenv('ENV') ?: 'development');
defined('YII_DEBUG') or define('YII_DEBUG', (ENV === 'development'));

if (YII_DEBUG) {
    $config['bootstrap'][] = 'gii';
    $config['modules']['gii'] = 'yii\gii\Module';
}
```

Psalm Version: 4.6.1, 4.6.2
composer.json
```
"require-dev": {
    "yiisoft/yii2-gii": "~2.2.0"
},
```

Unfortunately a minimal repro without any other source/dependencies does not have this issue. But if I comment-out the if statement or set `false` as if-expression, the bug is gone.

Full stacktrace:
```
Scanning files...
Uncaught InvalidArgumentException: Could not get class storage for yii\gii\module in /root/.composer/vendor/vimeo/psalm/src/Psalm/Internal/Provider/ClassLikeStorageProvider.php:42
Stack trace:
#0 /root/.composer/vendor/vimeo/psalm/src/Psalm/Internal/PhpVisitor/Reflector/ClassLikeNodeScanner.php(193): Psalm\Internal\Provider\ClassLikeStorageProvider->get('yii\\gii\\module')
#1 /root/.composer/vendor/vimeo/psalm/src/Psalm/Internal/PhpVisitor/ReflectorVisitor.php(183): Psalm\Internal\PhpVisitor\Reflector\ClassLikeNodeScanner->start(Object(PhpParser\Node\Stmt\Class_))
#2 /root/.composer/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(200): Psalm\Internal\PhpVisitor\ReflectorVisitor->enterNode(Object(PhpParser\Node\Stmt\Class_))
#3 /root/.composer/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(114): PhpParser\NodeTraverser->traverseArray(Array)
#4 /root/.composer/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(223): PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Stmt\Namespace_))
#5 /root/.composer/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(91): PhpParser\NodeTraverser->traverseArray(Array)
#6 /root/.composer/vendor/vimeo/psalm/src/Psalm/Internal/Scanner/FileScanner.php(86): PhpParser\NodeTraverser->traverse(Array)
#7 /root/.composer/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Scanner.php(567): Psalm\Internal\Scanner\FileScanner->scan(Object(Psalm\Codebase), Object(Psalm\Storage\FileStorage), true, Object(Psalm\Progress\LongProgress))
#8 /root/.composer/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Scanner.php(322): Psalm\Internal\Codebase\Scanner->scanFile('/builds/core/sr...', Array, true)
#9 /root/.composer/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Scanner.php(437): Psalm\Internal\Codebase\Scanner->Psalm\Internal\Codebase\{closure}(2, '/builds/core/sr...')
#10 /root/.composer/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Scanner.php(286): Psalm\Internal\Codebase\Scanner->scanFilePaths(1)
#11 /root/.composer/vendor/vimeo/psalm/src/Psalm/Codebase.php(470): Psalm\Internal\Codebase\Scanner->scanFiles(Object(Psalm\Internal\Codebase\ClassLikes), 1)
#12 /root/.composer/vendor/vimeo/psalm/src/Psalm/Config.php(1811): Psalm\Codebase->scanFiles()
#13 /root/.composer/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/ProjectAnalyzer.php(623): Psalm\Config->visitStubFiles(Object(Psalm\Codebase), Object(Psalm\Progress\LongProgress))
#14 /root/.composer/vendor/vimeo/psalm/src/psalm.php(681): Psalm\Internal\Analyzer\ProjectAnalyzer->check('/builds/core/sr...', true)
#15 /root/.composer/vendor/vimeo/psalm/psalm(2): require_once('/root/.composer...')
#16 {main}
(Psalm 4.6.1@e93e532e4eaad6d68c4d7b606853800eaceccc72 crashed due to an uncaught Throwable)
```

**Comment by Patrick-Remy** [comment]
This crash didn't happen again the last months on latest versions.
