### ISSUE TITLE
Option to not report errors for required/included files

### ISSUE THREAD

**Issue by kkmuffme** [vimeo/psalm#5322]
By default, psalm reports errors for files that were included in the current file if running pslam for 1 file:
`psalm foo.php`

foo.php

```php
echo 'foo';

require 'bar.php';
```

will also report errors for bar.php

When I specify just a single file, I expect that I only get errors from that 1 file. Is there an option to get this behavior?

**Comment by kkmuffme** [comment]
No, not possible

**Comment by orklah** [comment]
Maybe try that one:
https://psalm.dev/docs/running_psalm/configuration/#allowfileincludes

**Comment by kkmuffme** [comment]
No, that just throws an error when require/include is used, which will lead to the current file not being checked by psalm.

```
Uncaught Psalm\Exception\FileIncludeException: File includes are not allowed per your Psalm config - check the allowFileIncludes flag. in /opt/composer/vendor/vimeo/psalm/src/Psalm/Internal/PhpVisitor/Reflector/ExpressionScanner.php:272
Stack trace:
#0 /opt/composer/vendor/vimeo/psalm/src/Psalm/Internal/PhpVisitor/Reflector/ExpressionScanner.php(46): Psalm\Internal\PhpVisitor\Reflector\ExpressionScanner::visitInclude(Object(Psalm\Codebase), Object(Psalm\Storage\FileStorage), Object(PhpParser\Node\Expr\Include_), true)
#1 /opt/composer/vendor/vimeo/psalm/src/Psalm/Internal/PhpVisitor/ReflectorVisitor.php(344): Psalm\Internal\PhpVisitor\Reflector\ExpressionScanner::scan(Object(Psalm\Codebase), Object(Psalm\Internal\Scanner\FileScanner), Object(Psalm\Storage\FileStorage), Object(Psalm\Aliases), Object(PhpParser\Node\Expr\Include_), NULL, NULL)
#2 /opt/composer/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(123): Psalm\Internal\PhpVisitor\ReflectorVisitor->enterNode(Object(PhpParser\Node\Expr\Include_))
#3 /opt/composer/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(223): PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Stmt\Expression))
#4 /opt/composer/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(91): PhpParser\NodeTraverser->traverseArray(Array)
#5 /opt/composer/vendor/vimeo/psalm/src/Psalm/Internal/Scanner/FileScanner.php(86): PhpParser\NodeTraverser->traverse(Array)
#6 /opt/composer/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Scanner.php(570): Psalm\Internal\Scanner\FileScanner->scan(Object(Psalm\Codebase), Object(Psalm\Storage\FileStorage), false, Object(Psalm\Progress\DefaultProgress))
#7 /opt/composer/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Scanner.php(325): Psalm\Internal\Codebase\Scanner->scanFile('/opt/composer/v...', Array, true)
#8 /opt/composer/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Scanner.php(440): Psalm\Internal\Codebase\Scanner->Psalm\Internal\Codebase\{closure}(0, '/opt/composer/v...')
#9 /opt/composer/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Scanner.php(289): Psalm\Internal\Codebase\Scanner->scanFilePaths(1)
#10 /opt/composer/vendor/vimeo/psalm/src/Psalm/Config.php(1933): Psalm\Internal\Codebase\Scanner->scanFiles(Object(Psalm\Internal\Codebase\ClassLikes))
#11 /opt/composer/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/ProjectAnalyzer.php(399): Psalm\Config->visitComposerAutoloadFiles(Object(Psalm\Internal\Analyzer\ProjectAnalyzer), Object(Psalm\Progress\DefaultProgress))
#12 /opt/composer/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/ProjectAnalyzer.php(1144): Psalm\Internal\Analyzer\ProjectAnalyzer->visitAutoloadFiles()
#13 /opt/composer/vendor/vimeo/psalm/src/psalm.php(685): Psalm\Internal\Analyzer\ProjectAnalyzer->checkPaths(Array)
#14 /opt/composer/vendor/vimeo/psalm/psalm(2): require_once('/opt/composer/v...')
#15 {main}
(Psalm 4.6.2@bca09d74adc704c4eaee36a3c3e9d379e290fc3b crashed due to an uncaught Throwable)
```
