### ISSUE TITLE
Psalm crashes while parsing array access in conditional type

### ISSUE THREAD

**Issue by danog** [vimeo/psalm#5423]
https://psalm.dev/r/cd2e7e5f3f:

```
Uncaught RuntimeException: PHP Error: Uninitialized string offset 0 in /home/daniil/.config/composer/vendor/vimeo/psalm/src/Psalm/Internal/Type/TypeTokenizer.php:367 in /home/daniil/.config/composer/vendor/vimeo/psalm/src/Psalm/Internal/ErrorHandler.php:66
Stack trace:
#0 /home/daniil/.config/composer/vendor/vimeo/psalm/src/Psalm/Internal/Type/TypeTokenizer.php(367): Psalm\Internal\ErrorHandler::Psalm\Internal\{closure}(2, 'Uninitialized s...', '/home/daniil/.c...', 367)
#1 /home/daniil/.config/composer/vendor/vimeo/psalm/src/Psalm/Internal/PhpVisitor/Reflector/FunctionLikeDocblockScanner.php(386): Psalm\Internal\Type\TypeTokenizer::getFullyQualifiedTokens('(TArray[TKey] i...', Object(Psalm\Aliases), Array, Array, NULL)
#2 /home/daniil/.config/composer/vendor/vimeo/psalm/src/Psalm/Internal/PhpVisitor/Reflector/FunctionLikeDocblockScanner.php(867): Psalm\Internal\PhpVisitor\Reflector\FunctionLikeDocblockScanner::getConditionalSanitizedTypeTokens('(TArray[TKey] i...', Object(Psalm\Aliases), Array, Array, Object(Psalm\Storage\FunctionStorage), NULL, 'get', Array)
#3 /home/daniil/.config/composer/vendor/vimeo/psalm/src/Psalm/Internal/PhpVisitor/Reflector/FunctionLikeDocblockScanner.php(339): Psalm\Internal\PhpVisitor\Reflector\FunctionLikeDocblockScanner::handleReturn(Object(Psalm\Codebase), Object(Psalm\Internal\Scanner\FunctionDocblockComment), '(TArray[TKey] i...', false, Object(Psalm\Internal\Scanner\FileScanner), Object(Psalm\Storage\FunctionStorage), Object(PhpParser\Node\Stmt\Function_), Object(Psalm\Aliases), Array, Array, Array, NULL, 'get', Object(Psalm\Storage\FileStorage))
#4 /home/daniil/.config/composer/vendor/vimeo/psalm/src/Psalm/Internal/PhpVisitor/Reflector/FunctionLikeNodeScanner.php(459): Psalm\Internal\PhpVisitor\Reflector\FunctionLikeDocblockScanner::addDocblockInfo(Object(Psalm\Codebase), Object(Psalm\Internal\Scanner\FileScanner), Object(Psalm\Storage\FileStorage), Object(Psalm\Aliases), Array, NULL, Array, Object(Psalm\Storage\FunctionStorage), Object(PhpParser\Node\Stmt\Function_), Object(Psalm\Internal\Scanner\FunctionDocblockComment), false, false, 'get')
#5 /home/daniil/.config/composer/vendor/vimeo/psalm/src/Psalm/Internal/PhpVisitor/ReflectorVisitor.php(233): Psalm\Internal\PhpVisitor\Reflector\FunctionLikeNodeScanner->start(Object(PhpParser\Node\Stmt\Function_))
#6 /home/daniil/.config/composer/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(200): Psalm\Internal\PhpVisitor\ReflectorVisitor->enterNode(Object(PhpParser\Node\Stmt\Function_))
#7 /home/daniil/.config/composer/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(91): PhpParser\NodeTraverser->traverseArray(Array)
#8 /home/daniil/.config/composer/vendor/vimeo/psalm/src/Psalm/Internal/Scanner/FileScanner.php(86): PhpParser\NodeTraverser->traverse(Array)
#9 /home/daniil/.config/composer/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Scanner.php(575): Psalm\Internal\Scanner\FileScanner->scan(Object(Psalm\Codebase), Object(Psalm\Storage\FileStorage), false, Object(Psalm\Progress\DefaultProgress))
#10 /home/daniil/.config/composer/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Scanner.php(326): Psalm\Internal\Codebase\Scanner->scanFile('/home/daniil/re...', Array, true)
#11 /home/daniil/.config/composer/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Scanner.php(445): Psalm\Internal\Codebase\Scanner->Psalm\Internal\Codebase\{closure}(0, '/home/daniil/re...')
#12 /home/daniil/.config/composer/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Scanner.php(290): Psalm\Internal\Codebase\Scanner->scanFilePaths(1)
#13 /home/daniil/.config/composer/vendor/vimeo/psalm/src/Psalm/Codebase.php(471): Psalm\Internal\Codebase\Scanner->scanFiles(Object(Psalm\Internal\Codebase\ClassLikes), 3)
#14 /home/daniil/.config/composer/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/ProjectAnalyzer.php(1167): Psalm\Codebase->scanFiles(3)
#15 /home/daniil/.config/composer/vendor/vimeo/psalm/src/psalm.php(702): Psalm\Internal\Analyzer\ProjectAnalyzer->checkPaths(Array)
#16 /home/daniil/.config/composer/vendor/vimeo/psalm/src/psalm.php(884): Psalm\{closure}(Array)
#17 /home/daniil/.config/composer/vendor/vimeo/psalm/psalm(2): require_once('/home/daniil/.c...')
#18 {main}
(Psalm dev-master@d19088bb107e5e2f12cf12c59f05f4cb556f546c crashed due to an uncaught Throwable)
```

**Comment by weirdan** [comment]
@danog did you expect this to work? Psalm currently does not support index types on the left hand side of `is`.
