### ISSUE TITLE
Could not get class storage for cache\php\mastercontroller

### ISSUE THREAD

**Issue by lperamo** [vimeo/psalm#5429]
Even when I launch Psalm with the `--no-cache` parameter, I get this error :
```
Uncaught InvalidArgumentException: Could not get class storage for cache\php\mastercontroller in phar:///var/www/html/lib/psalm.phar/src/Psalm/Internal/Provider/ClassLikeStorageProvider.php:38
Stack trace:
#0 phar:///var/www/html/lib/psalm.phar/src/Psalm/Internal/Codebase/ClassLikes.php(382): Psalm\Internal\Provider\ClassLikeStorageProvider->get()
#1 phar:///var/www/html/lib/psalm.phar/src/Psalm/Codebase.php(506): Psalm\Internal\Codebase\ClassLikes->classImplements()
#2 phar:///var/www/html/lib/psalm.phar/src/Psalm/Internal/Codebase/ClassLikes.php(904): Psalm\Codebase->classImplements()
#3 phar:///var/www/html/lib/psalm.phar/src/Psalm/Internal/Codebase/ClassLikes.php(501): Psalm\Internal\Codebase\ClassLikes->checkMethodReferences()
#4 phar:///var/www/html/lib/psalm.phar/src/Psalm/Internal/Analyzer/ProjectAnalyzer.php(460): Psalm\Internal\Codebase\ClassLikes->consolidateAnalyzedData()
#5 phar:///var/www/html/lib/psalm.phar/src/Psalm/Internal/Codebase/Analyzer.php(230): Psalm\Internal\Analyzer\ProjectAnalyzer->consolidateAnalyzedData()
#6 phar:///var/www/html/lib/psalm.phar/src/Psalm/Internal/Analyzer/ProjectAnalyzer.php(447): Psalm\Internal\Codebase\Analyzer->analyzeFiles()
#7 phar:///var/www/html/lib/psalm.phar/src/psalm.php(472): Psalm\Internal\Analyzer\ProjectAnalyzer->check()
#8 phar:///var/www/html/lib/psalm.phar/src/psalm.php(571): Psalm\{closure}()
#9 phar:///var/www/html/lib/psalm.phar/psalm(5): require_once('...')
#10 /var/www/html/lib/psalm.phar(14): require('...')
#11 {main}
(Psalm 4.x-dev@ crashed due to an uncaught Throwable)
```

After isolating the code that make Psalm crash, it is essentially related to three files.
The problem occurs in the file `src/OtraException.php` in the method `errorMessage` when I instantiate a `Controller` at line `93`.
`Controller` that extends `MasterController` and this _is_ the file mentioned by Psalm.
You can see my big project on [this repository](https://github.com/lperamo/otra) for further investigation.

**Comment by lperamo** [comment]
No, I do not succeed to reproduce it on https://psalm.dev with a little amount of code. It uses lots of things and unless I put the content of numerous files in there...it is very complicated.

**Comment by weirdan** [comment]
Likely caused by class aliasing / conditional class definition or something similar. I would suggest to disable dead code detection and try to fix other issues Psalm reports first.

**Comment by lperamo** [comment]
Yes I have a condition class definition based on the environment. If we are in a development environment I load a trait DevControllerTrait, if we are in a production environment I load a trait ProdControllerTrait.
I am not really satisfy by this but I am not sure what is the best (and light) solution.
So indeed, I tried to remove the other errors until I find a solution for this Psalm crash.
For now, I just test the part that make Psalm crash and the other part separately.
