### ISSUE TITLE
Could not get class storage for iterable with allowPhpStormGenerics

### ISSUE THREAD

**Issue by Soullivaneuh** [vimeo/psalm#546]
If I add the `allowPhpStormGenerics="true"` setting, I have:

```
$ psalm 
Scanning files...

Fatal error: Uncaught InvalidArgumentException: Could not get class storage for iterable in /home/developer/.composer/vendor/vimeo/psalm/src/Psalm/Provider/ClassLikeStorageProvider.php:35
Stack trace:
#0 /home/developer/.composer/vendor/vimeo/psalm/src/Psalm/Codebase/ClassLikes.php(502): Psalm\Provider\ClassLikeStorageProvider->get('iterable')
#1 /home/developer/.composer/vendor/vimeo/psalm/src/Psalm/Codebase/ClassLikes.php(490): Psalm\Codebase\ClassLikes->getParentInterfaces('iterable')
#2 /home/developer/.composer/vendor/vimeo/psalm/src/Psalm/Codebase/Populator.php(439): Psalm\Codebase\ClassLikes->interfaceExtends('iterable', 'Traversable')
#3 /home/developer/.composer/vendor/vimeo/psalm/src/Psalm/Codebase/Populator.php(117): Psalm\Codebase\Populator->convertPhpStormGenericToPsalmGeneric(Object(Psalm\Type\Union))
#4 /home/developer/.composer/vendor/vimeo/psalm/src/Psalm/Codebase.php(219): Psalm\Codebase\Populator->populateCodebase()
#5 /home/developer/.composer/vendor/vimeo/psalm/src/Psalm/Checker/ProjectChecker.php(272 in /home/developer/.composer/vendor/vimeo/psalm/src/Psalm/Provider/ClassLikeStorageProvider.php on line 35
```

**Comment by muglug** [comment]
Thanks - should be fixed now. I had been focussing on interfaces that extend `Iterator`, but `iterable` obviously counts.
