### ISSUE TITLE
Psalm 4.6.3 and 4.7.0 crashed due to an uncaught Throwable when int overflows

### ISSUE THREAD

**Issue by ufoproger** [vimeo/psalm#5505]
#### Example bug.php
```php
<?php

$value = 2 ** 80;
```

#### Example psalm.xml
```xml
<?xml version="1.0"?>
<psalm
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns="https://getpsalm.org/schema/config"
    xsi:schemaLocation="https://getpsalm.org/schema/config vendor/vimeo/psalm/config.xsd"
    xmlns:xi="http://www.w3.org/2001/XInclude"
>
	<projectFiles>
	    <file name="bug.php" />
	</projectFiles>
</psalm>
```

#### Psalm output with --debug-by-line
```
Analyzing files...
Getting /var/www/html/bug.php
Analyzing /var/www/html/bug.php
/var/www/html/bug.php:3
Uncaught TypeError: Argument 2 passed to Psalm\Type::getInt() must be of the type int or null, float given, called in phar:///var/www/html/vendor/psalm/phar/psalm.phar/src/Psalm/Internal/Analyzer/Statements/Expression/BinaryOp/NonDivArithmeticOpAnalyzer.php on line 173 and defined in phar:///var/www/html/vendor/psalm/phar/psalm.phar/src/Psalm/Type.php:124
Stack trace:
#0 phar:///var/www/html/vendor/psalm/phar/psalm.phar/src/Psalm/Internal/Analyzer/Statements/Expression/BinaryOp/NonDivArithmeticOpAnalyzer.php(173): Psalm\Type::getInt(false, 1.2089258196146E+24)
#1 phar:///var/www/html/vendor/psalm/phar/psalm.phar/src/Psalm/Internal/Analyzer/Statements/Expression/BinaryOp/NonDivArithmeticOpAnalyzer.php(112): Psalm\Internal\Analyzer\Statements\Expression\BinaryOp\NonDivArithmeticOpAnalyzer::analyzeNonDivOperands(Object(Psalm\Internal\Analyzer\StatementsAnalyzer), Object(Psalm\Codebase), Object(Psalm\Config), Object(Psalm\Context), Object(_HumbugBox0e2a9704dbbd\PhpParser\Node\Scalar\LNumber), Object(_HumbugBox0e2a9704dbbd\PhpParser\Node\Scalar\LNumber), Object(_HumbugBox0e2a9704dbbd\PhpParser\Node\Expr\BinaryOp\Pow), Object(Psalm\Type\Atomic\TLiteralInt), Object(Psalm\Type\Atomic\TLiteralInt), Array, Array, false, false, false, NULL)
#2 phar:///var/www/html/vendor/psalm/phar/psalm.phar/src/Psalm/Internal/Analyzer/Statements/Expression/BinaryOp/NonComparisonOpAnalyzer.php(28): Psalm\Internal\Analyzer\Statements\Expression\BinaryOp\NonDivArithmeticOpAnalyzer::analyze(Object(Psalm\Internal\Analyzer\StatementsAnalyzer), Object(Psalm\Internal\Provider\NodeDataProvider), Object(_HumbugBox0e2a9704dbbd\PhpParser\Node\Scalar\LNumber), Object(_HumbugBox0e2a9704dbbd\PhpParser\Node\Scalar\LNumber), Object(_HumbugBox0e2a9704dbbd\PhpParser\Node\Expr\BinaryOp\Pow), NULL, Object(Psalm\Context))
#3 phar:///var/www/html/vendor/psalm/phar/psalm.phar/src/Psalm/Internal/Analyzer/Statements/Expression/BinaryOpAnalyzer.php(155): Psalm\Internal\Analyzer\Statements\Expression\BinaryOp\NonComparisonOpAnalyzer::analyze(Object(Psalm\Internal\Analyzer\StatementsAnalyzer), Object(_HumbugBox0e2a9704dbbd\PhpParser\Node\Expr\BinaryOp\Pow), Object(Psalm\Context))
#4 phar:///var/www/html/vendor/psalm/phar/psalm.phar/src/Psalm/Internal/Analyzer/Statements/ExpressionAnalyzer.php(124): Psalm\Internal\Analyzer\Statements\Expression\BinaryOpAnalyzer::analyze(Object(Psalm\Internal\Analyzer\StatementsAnalyzer), Object(_HumbugBox0e2a9704dbbd\PhpParser\Node\Expr\BinaryOp\Pow), Object(Psalm\Context), 0, false)
#5 phar:///var/www/html/vendor/psalm/phar/psalm.phar/src/Psalm/Internal/Analyzer/Statements/ExpressionAnalyzer.php(32): Psalm\Internal\Analyzer\Statements\ExpressionAnalyzer::handleExpression(Object(Psalm\Internal\Analyzer\StatementsAnalyzer), Object(_HumbugBox0e2a9704dbbd\PhpParser\Node\Expr\BinaryOp\Pow), Object(Psalm\Context), false, NULL, false)
#6 phar:///var/www/html/vendor/psalm/phar/psalm.phar/src/Psalm/Internal/Analyzer/Statements/Expression/AssignmentAnalyzer.php(125): Psalm\Internal\Analyzer\Statements\ExpressionAnalyzer::analyze(Object(Psalm\Internal\Analyzer\StatementsAnalyzer), Object(_HumbugBox0e2a9704dbbd\PhpParser\Node\Expr\BinaryOp\Pow), Object(Psalm\Context))
#7 phar:///var/www/html/vendor/psalm/phar/psalm.phar/src/Psalm/Internal/Analyzer/Statements/ExpressionAnalyzer.php(62): Psalm\Internal\Analyzer\Statements\Expression\AssignmentAnalyzer::analyze(Object(Psalm\Internal\Analyzer\StatementsAnalyzer), Object(_HumbugBox0e2a9704dbbd\PhpParser\Node\Expr\Variable), Object(_HumbugBox0e2a9704dbbd\PhpParser\Node\Expr\BinaryOp\Pow), NULL, Object(Psalm\Context), NULL)
#8 phar:///var/www/html/vendor/psalm/phar/psalm.phar/src/Psalm/Internal/Analyzer/Statements/ExpressionAnalyzer.php(32): Psalm\Internal\Analyzer\Statements\ExpressionAnalyzer::handleExpression(Object(Psalm\Internal\Analyzer\StatementsAnalyzer), Object(_HumbugBox0e2a9704dbbd\PhpParser\Node\Expr\Assign), Object(Psalm\Context), false, NULL, true)
#9 phar:///var/www/html/vendor/psalm/phar/psalm.phar/src/Psalm/Internal/Analyzer/StatementsAnalyzer.php(360): Psalm\Internal\Analyzer\Statements\ExpressionAnalyzer::analyze(Object(Psalm\Internal\Analyzer\StatementsAnalyzer), Object(_HumbugBox0e2a9704dbbd\PhpParser\Node\Expr\Assign), Object(Psalm\Context), false, NULL, true)
#10 phar:///var/www/html/vendor/psalm/phar/psalm.phar/src/Psalm/Internal/Analyzer/StatementsAnalyzer.php(149): Psalm\Internal\Analyzer\StatementsAnalyzer::analyzeStatement(Object(Psalm\Internal\Analyzer\StatementsAnalyzer), Object(_HumbugBox0e2a9704dbbd\PhpParser\Node\Stmt\Expression), Object(Psalm\Context), NULL)
#11 phar:///var/www/html/vendor/psalm/phar/psalm.phar/src/Psalm/Internal/Analyzer/FileAnalyzer.php(152): Psalm\Internal\Analyzer\StatementsAnalyzer->analyze(Array, Object(Psalm\Context), NULL, true)
#12 phar:///var/www/html/vendor/psalm/phar/psalm.phar/src/Psalm/Internal/Codebase/Analyzer.php(268): Psalm\Internal\Analyzer\FileAnalyzer->analyze(NULL)
#13 phar:///var/www/html/vendor/psalm/phar/psalm.phar/src/Psalm/Internal/Codebase/Analyzer.php(414): Psalm\Internal\Codebase\Analyzer->Psalm\Internal\Codebase\{closure}(0, '/var/www/html/b...')
#14 phar:///var/www/html/vendor/psalm/phar/psalm.phar/src/Psalm/Internal/Codebase/Analyzer.php(223): Psalm\Internal\Codebase\Analyzer->doAnalysis(Object(Psalm\Internal\Analyzer\ProjectAnalyzer), 1)
#15 phar:///var/www/html/vendor/psalm/phar/psalm.phar/src/Psalm/Internal/Analyzer/ProjectAnalyzer.php(447): Psalm\Internal\Codebase\Analyzer->analyzeFiles(Object(Psalm\Internal\Analyzer\ProjectAnalyzer), 1, false, true)
#16 phar:///var/www/html/vendor/psalm/phar/psalm.phar/src/psalm.php(473): Psalm\Internal\Analyzer\ProjectAnalyzer->check('/var/www/html/', true)
#17 phar:///var/www/html/vendor/psalm/phar/psalm.phar/src/psalm.php(572): Psalm\{closure}(Array)
#18 phar:///var/www/html/vendor/psalm/phar/psalm.phar/psalm(5): require_once('phar:///var/www...')
#19 /var/www/html/vendor/psalm/phar/psalm.phar(14): require('phar:///var/www...')
#20 {main}
(Psalm 4.x-dev@ crashed due to an uncaught Throwable)
```

#### Same issues
* https://github.com/vimeo/psalm/issues/5363 (closed)

**Comment by orklah** [comment]
I'll fix that this afternoon.

For reference: https://psalm.dev/r/aa213dd8dd

**Comment by BafS** [comment]
I still have the issue with `psalm/phar` v4.7.3

```
Uncaught TypeError: Argument 2 passed to Psalm\Type::getInt() must be of the type int or null, float given, called in phar:///Users/bafs/Dev/ProtonTech/containers/webserver/repos/api/vendor/psalm/phar/psalm.phar/src/Psalm/Internal/Analyzer/Statements/Expression/BinaryOp/NonDivArithmeticOpAnalyzer.php on line 162 and defined in phar:///Users/.../vendor/psalm/phar/psalm.phar/src/Psalm/Type.php:129
```

Or is it a phar release issue ? I'm sure I have the v4.7.3 with composer

```
./bin/psalm.phar --version
Psalm 4.x-dev@
```
