### ISSUE TITLE
array_map: function name case (?) issue

### ISSUE THREAD

**Issue by weirdan** [vimeo/psalm#555]
```php
array_map('mapA', ["a"]);
function mapA(string $a): string
{
    return $a;
}
```
This fails with:
```
Fatal error: Uncaught UnexpectedValueException: Expecting mapA to have storage in /home/weirdan/src/invajo/api/q.php in /home/weirdan/.composer/vendor/vimeo/psalm/src/Psalm/Codebase/Functions.php:73
Stack trace:
#0 /home/weirdan/.composer/vendor/vimeo/psalm/src/Psalm/Checker/Statements/Expression/CallChecker.php(977): Psalm\Codebase\Functions->getStorage(Object(Psalm\Checker\StatementsChecker), 'mapA')
#1 /home/weirdan/.composer/vendor/vimeo/psalm/src/Psalm/Checker/Statements/Expression/CallChecker.php(892): Psalm\Checker\Statements\Expression\CallChecker::checkArrayFunctionClosureType(Object(Psalm\Checker\StatementsChecker), 'array_map', Object(Psalm\Type\Atomic\TString), Object(PhpParser\Node\Arg), 1, 1, Array)
#2 /home/weirdan/.composer/vendor/vimeo/psalm/src/Psalm/Checker/Statements/Expression/CallChecker.php(781): Psalm\Checker\Statements\Expression\CallChecker::checkArrayFunctionArgumentsMatch(Object(Psalm\Checker\StatementsChecker), Array, 'array_map')
#3 /home/weirdan/.composer/vendor/vimeo/psalm/src/Psalm/Checker in /home/weirdan/.composer/vendor/vimeo/psalm/src/Psalm/Codebase/Functions.php on line 73
```
If I lowercase the function (to `mapa`) it works fine.

**Comment by muglug** [comment]
Thanks, that was a little embarrassing (because there have been function name casing issues previously).
