### ISSUE TITLE
psalm --init crashes with Uncaught Exception: Appearing/Declaring classes are not defined for namespace\Class::$staticProperty

### ISSUE THREAD

**Issue by juacala** [vimeo/psalm#5679]
When I run ./vendor/bin/psalm --init I get an "Uncaught Exception: Appearing/Declaring classes are not defined for \ESP\core\mssql\MSSQL::$sqlFunctions"

Any ideas of what is going on there? 

I install psalm through composer and updated today. When I do psalm --version I get:
Psalm 4.7.1@cd53e047a58f71f646dd6bf45476076ab07b5d44

I pasted in the top of the file in question (that has the static property in question. Also see below for the full backtrace for the exception.

The top of the file in question is:
```
<?php

namespace ESP\core\mssql;

use \ESP\core\BaseSQL;
use ESP\core\ESPErr;
use \ESP\core\SQL;
use \ESP\core\mysql\MySQL;

class MSSQL extends BaseSQL
{
    /**
     * @var bool $nullsUnique Whether or not nulls are considered unique in this database.
     */
    public static $nullsUnique = true;
    /**
     * @var array $sqlFunctions These are functions that are loaded to make this db type work on the system.
     */
    public static $sqlFunctions = [
        "substring_index"
    ];

```

Full exception:
```
EEEEEEEEEEEEEEEEEEEEEEEEEEE░EEEEE░EEEEEEEEEEEEEEEEUncaught Exception: Appearing/Declaring classes are not defined for \ESP\core\mssql\MSSQL::$sqlFunctions
Stack trace in the forked worker:
#0 /ebs/esp/www/pflammer/trunk3/espaux/apis/vimeo/psalm/src/Psalm/Internal/Analyzer/Statements/Expression/Fetch/StaticPropertyFetchAnalyzer.php(261): Psalm\Internal\Analyzer\ClassLikeAnalyzer::checkPropertyVisibility('\\ESP\\core\\mssql.
..', Object(Psalm\Context), Object(Psalm\Internal\Analyzer\StatementsAnalyzer), Object(Psalm\CodeLocation), Array)
#1 /ebs/esp/www/pflammer/trunk3/espaux/apis/vimeo/psalm/src/Psalm/Internal/Analyzer/Statements/Expression/Fetch/StaticPropertyFetchAnalyzer.php(405): Psalm\Internal\Analyzer\Statements\Expression\Fetch\StaticPropertyFetchAnalyzer::analyz
e(Object(Psalm\Internal\Analyzer\StatementsAnalyzer), Object(Psalm\Node\Expr\VirtualStaticPropertyFetch), Object(Psalm\Context))
#2 /ebs/esp/www/pflammer/trunk3/espaux/apis/vimeo/psalm/src/Psalm/Internal/Analyzer/Statements/Expression/Fetch/StaticPropertyFetchAnalyzer.php(37): Psalm\Internal\Analyzer\Statements\Expression\Fetch\StaticPropertyFetchAnalyzer::analyze
VariableStaticPropertyFetch(Object(Psalm\Internal\Analyzer\StatementsAnalyzer), Object(PhpParser\Node\Expr\ArrayDimFetch), Object(PhpParser\Node\Expr\StaticPropertyFetch), Object(Psalm\Context))
#3 /ebs/esp/www/pflammer/trunk3/espaux/apis/vimeo/psalm/src/Psalm/Internal/Analyzer/Statements/ExpressionAnalyzer.php(218): Psalm\Internal\Analyzer\Statements\Expression\Fetch\StaticPropertyFetchAnalyzer::analyze(Object(Psalm\Internal\An
alyzer\StatementsAnalyzer), Object(PhpParser\Node\Expr\StaticPropertyFetch), Object(Psalm\Context))
#4 /ebs/esp/www/pflammer/trunk3/espaux/apis/vimeo/psalm/src/Psalm/Internal/Analyzer/Statements/ExpressionAnalyzer.php(45): Psalm\Internal\Analyzer\Statements\ExpressionAnalyzer::handleExpression(Object(Psalm\Internal\Analyzer\StatementsAnalyzer), Object(PhpParser\Node\Expr\StaticPropertyFetch), Object(Psalm\Context), false, NULL, false)
#5 /ebs/esp/www/pflammer/trunk3/espaux/apis/vimeo/psalm/src/Psalm/Internal/Analyzer/Statements/Expression/IssetAnalyzer.php(45): Psalm\Internal\Analyzer\Statements\ExpressionAnalyzer::analyze(Object(Psalm\Internal\Analyzer\StatementsAnalyzer), Object(PhpParser\Node\Expr\StaticPropertyFetch), Object(Psalm\Context))
#6 /ebs/esp/www/pflammer/trunk3/espaux/apis/vimeo/psalm/src/Psalm/Internal/Analyzer/Statements/Expression/IssetAnalyzer.php(31): Psalm\Internal\Analyzer\Statements\Expression\IssetAnalyzer::analyzeIssetVar(Object(Psalm\Internal\Analyzer\StatementsAnalyzer), Object(PhpParser\Node\Expr\StaticPropertyFetch), Object(Psalm\Context))
#7 /ebs/esp/www/pflammer/trunk3/espaux/apis/vimeo/psalm/src/Psalm/Internal/Analyzer/Statements/ExpressionAnalyzer.php(195): Psalm\Internal\Analyzer\Statements\Expression\IssetAnalyzer::analyze(Object(Psalm\Internal\Analyzer\StatementsAnalyzer), Object(Psalm\Node\Expr\VirtualIsset), Object(Psalm\Context))
#8 /ebs/esp/www/pflammer/trunk3/espaux/apis/vimeo/psalm/src/Psalm/Internal/Analyzer/Statements/ExpressionAnalyzer.php(45): Psalm\Internal\Analyzer\Statements\ExpressionAnalyzer::handleExpression(Object(Psalm\Internal\Analyzer\StatementsAnalyzer), Object(Psalm\Node\Expr\VirtualIsset), Object(Psalm\Context), false, NULL, false)
#9 /ebs/esp/www/pflammer/trunk3/espaux/apis/vimeo/psalm/src/Psalm/Internal/Analyzer/Statements/Block/IfConditionalAnalyzer.php(116): Psalm\Internal\Analyzer\Statements\ExpressionAnalyzer::analyze(Object(Psalm\Internal\Analyzer\StatementsAnalyzer), Object(Psalm\Node\Expr\VirtualIsset), Object(Psalm\Context))
#10 /ebs/esp/www/pflammer/trunk3/espaux/apis/vimeo/psalm/src/Psalm/Internal/Analyzer/Statements/Expression/TernaryAnalyzer.php(45): Psalm\Internal\Analyzer\Statements\Block\IfConditionalAnalyzer::analyze(Object(Psalm\Internal\Analyzer\StatementsAnalyzer), Object(Psalm\Node\Expr\VirtualIsset), Object(Psalm\Context), Object(Psalm\Codebase), Object(Psalm\Internal\Scope\IfScope), 1980)
#11 /ebs/esp/www/pflammer/trunk3/espaux/apis/vimeo/psalm/src/Psalm/Internal/Analyzer/Statements/ExpressionAnalyzer.php(267): Psalm\Internal\Analyzer\Statements\Expression\TernaryAnalyzer::analyze(Object(Psalm\Internal\Analyzer\StatementsAnalyzer), Object(Psalm\Node\Expr\VirtualTernary), Object(Psalm\Context))
#12 /ebs/esp/www/pflammer/trunk3/espaux/apis/vimeo/psalm/src/Psalm/Internal/Analyzer/Statements/ExpressionAnalyzer.php(45): Psalm\Internal\Analyzer\Statements\ExpressionAnalyzer::handleExpression(Object(Psalm\Internal\Analyzer\StatementsAnalyzer), Object(Psalm\Node\Expr\VirtualTernary), Object(Psalm\Context), false, NULL, false)
#13 /ebs/esp/www/pflammer/trunk3/espaux/apis/vimeo/psalm/src/Psalm/Internal/Analyzer/Statements/Expression/BinaryOp/CoalesceAnalyzer.php(76): Psalm\Internal\Analyzer\Statements\ExpressionAnalyzer::analyze(Object(Psalm\Internal\Analyzer\StatementsAnalyzer), Object(Psalm\Node\Expr\VirtualTernary), Object(Psalm\Context))
#14 /ebs/esp/www/pflammer/trunk3/espaux/apis/vimeo/psalm/src/Psalm/Internal/Analyzer/Statements/Expression/BinaryOpAnalyzer.php(81): Psalm\Internal\Analyzer\Statements\Expression\BinaryOp\CoalesceAnalyzer::analyze(Object(Psalm\Internal\Analyzer\StatementsAnalyzer), Object(PhpParser\Node\Expr\BinaryOp\Coalesce), Object(Psalm\Context))
#15 /ebs/esp/www/pflammer/trunk3/espaux/apis/vimeo/psalm/src/Psalm/Internal/Analyzer/Statements/ExpressionAnalyzer.php(232): Psalm\Internal\Analyzer\Statements\Expression\BinaryOpAnalyzer::analyze(Object(Psalm\Internal\Analyzer\StatementsAnalyzer), Object(PhpParser\Node\Expr\BinaryOp\Coalesce), Object(Psalm\Context), 0, false)
#16 /ebs/esp/www/pflammer/trunk3/espaux/apis/vimeo/psalm/src/Psalm/Internal/Analyzer/Statements/ExpressionAnalyzer.php(45): Psalm\Internal\Analyzer\Statements\ExpressionAnalyzer::handleExpression(Object(Psalm\Internal\Analyzer\StatementsAnalyzer), Object(PhpParser\Node\Expr\BinaryOp\Coalesce), Object(Psalm\Context), false, NULL, false)
#17 /ebs/esp/www/pflammer/trunk3/espaux/apis/vimeo/psalm/src/Psalm/Internal/Analyzer/Statements/Block/IfConditionalAnalyzer.php(116): Psalm\Internal\Analyzer\Statements\ExpressionAnalyzer::analyze(Object(Psalm\Internal\Analyzer\StatementsAnalyzer), Object(PhpParser\Node\Expr\BinaryOp\Coalesce), Object(Psalm\Context))
#18 /ebs/esp/www/pflammer/trunk3/espaux/apis/vimeo/psalm/src/Psalm/Internal/Analyzer/Statements/Block/IfElseAnalyzer.php(97): Psalm\Internal\Analyzer\Statements\Block\IfConditionalAnalyzer::analyze(Object(Psalm\Internal\Analyzer\StatementsAnalyzer), Object(PhpParser\Node\Expr\BinaryOp\Coalesce), Object(Psalm\Context), Object(Psalm\Codebase), Object(Psalm\Internal\Scope\IfScope), 1977)
#19 /ebs/esp/www/pflammer/trunk3/espaux/apis/vimeo/psalm/src/Psalm/Internal/Analyzer/StatementsAnalyzer.php(478): Psalm\Internal\Analyzer\Statements\Block\IfElseAnalyzer::analyze(Object(Psalm\Internal\Analyzer\StatementsAnalyzer), Object(PhpParser\Node\Stmt\If_), Object(Psalm\Context))
#20 /ebs/esp/www/pflammer/trunk3/espaux/apis/vimeo/psalm/src/Psalm/Internal/Analyzer/StatementsAnalyzer.php(172): Psalm\Internal\Analyzer\StatementsAnalyzer::analyzeStatement(Object(Psalm\Internal\Analyzer\StatementsAnalyzer), Object(PhpParser\Node\Stmt\If_), Object(Psalm\Context), Object(Psalm\Context))
#21 /ebs/esp/www/pflammer/trunk3/espaux/apis/vimeo/psalm/src/Psalm/Internal/Analyzer/FunctionLikeAnalyzer.php(430): Psalm\Internal\Analyzer\StatementsAnalyzer->analyze(Array, Object(Psalm\Context), Object(Psalm\Context), true)
#22 /ebs/esp/www/pflammer/trunk3/espaux/apis/vimeo/psalm/src/Psalm/Internal/Analyzer/FunctionAnalyzer.php(95): Psalm\Internal\Analyzer\FunctionLikeAnalyzer->analyze(Object(Psalm\Context), Object(Psalm\Internal\Provider\NodeDataProvider), Object(Psalm\Context))
#23 /ebs/esp/www/pflammer/trunk3/espaux/apis/vimeo/psalm/src/Psalm/Internal/Analyzer/StatementsAnalyzer.php(522): Psalm\Internal\Analyzer\FunctionAnalyzer::analyzeStatement(Object(Psalm\Internal\Analyzer\StatementsAnalyzer), Object(PhpParser\Node\Stmt\Function_), Object(Psalm\Context))
#24 /ebs/esp/www/pflammer/trunk3/espaux/apis/vimeo/psalm/src/Psalm/Internal/Analyzer/StatementsAnalyzer.php(172): Psalm\Internal\Analyzer\StatementsAnalyzer::analyzeStatement(Object(Psalm\Internal\Analyzer\StatementsAnalyzer), Object(PhpParser\Node\Stmt\Function_), Object(Psalm\Context), NULL)
#25 /ebs/esp/www/pflammer/trunk3/espaux/apis/vimeo/psalm/src/Psalm/Internal/Analyzer/FileAnalyzer.php(189): Psalm\Internal\Analyzer\StatementsAnalyzer->analyze(Array, Object(Psalm\Context), NULL, true)
#26 /ebs/esp/www/pflammer/trunk3/espaux/apis/vimeo/psalm/src/Psalm/Internal/Codebase/Analyzer.php(341): Psalm\Internal\Analyzer\FileAnalyzer->analyze(NULL)
#27 /ebs/esp/www/pflammer/trunk3/espaux/apis/vimeo/psalm/src/Psalm/Internal/Fork/Pool.php(193): Psalm\Internal\Codebase\Analyzer->Psalm\Internal\Codebase\{closure}(198, '/ebs/esp/www/pf...')
#28 /ebs/esp/www/pflammer/trunk3/espaux/apis/vimeo/psalm/src/Psalm/Internal/Codebase/Analyzer.php(465): Psalm\Internal\Fork\Pool->__construct(Array, Object(Closure), Object(Closure), Object(Closure), Object(Closure))
#29 /ebs/esp/www/pflammer/trunk3/espaux/apis/vimeo/psalm/src/Psalm/Internal/Codebase/Analyzer.php(270): Psalm\Internal\Codebase\Analyzer->doAnalysis(Object(Psalm\Internal\Analyzer\ProjectAnalyzer), 3)
#30 /ebs/esp/www/pflammer/trunk3/espaux/apis/vimeo/psalm/src/Psalm/Internal/Analyzer/ProjectAnalyzer.php(636): Psalm\Internal\Codebase\Analyzer->analyzeFiles(Object(Psalm\Internal\Analyzer\ProjectAnalyzer), 3, false, true)
#31 /ebs/esp/www/pflammer/trunk3/espaux/apis/vimeo/psalm/src/psalm.php(700): Psalm\Internal\Analyzer\ProjectAnalyzer->check('/ebs/esp/www/pf...', true)
#32 /ebs/esp/www/pflammer/trunk3/espaux/apis/vimeo/psalm/src/psalm.php(884): Psalm\{closure}(Array)
#33 /ebs/esp/www/pflammer/trunk3/espaux/apis/vimeo/psalm/psalm(2): require_once('/ebs/esp/www/pf...')
#34 {main} in /ebs/esp/www/pflammer/trunk3/espaux/apis/vimeo/psalm/src/Psalm/Internal/Fork/Pool.php:357
Stack trace:
#0 /ebs/esp/www/pflammer/trunk3/espaux/apis/vimeo/psalm/src/Psalm/Internal/Fork/Pool.php(389): Psalm\Internal\Fork\Pool->readResultsFromChildren()
#1 /ebs/esp/www/pflammer/trunk3/espaux/apis/vimeo/psalm/src/Psalm/Internal/Codebase/Analyzer.php(474): Psalm\Internal\Fork\Pool->wait()
#2 /ebs/esp/www/pflammer/trunk3/espaux/apis/vimeo/psalm/src/Psalm/Internal/Codebase/Analyzer.php(270): Psalm\Internal\Codebase\Analyzer->doAnalysis(Object(Psalm\Internal\Analyzer\ProjectAnalyzer), 3)
#3 /ebs/esp/www/pflammer/trunk3/espaux/apis/vimeo/psalm/src/Psalm/Internal/Analyzer/ProjectAnalyzer.php(636): Psalm\Internal\Codebase\Analyzer->analyzeFiles(Object(Psalm\Internal\Analyzer\ProjectAnalyzer), 3, false, true)
#4 /ebs/esp/www/pflammer/trunk3/espaux/apis/vimeo/psalm/src/psalm.php(700): Psalm\Internal\Analyzer\ProjectAnalyzer->check('/ebs/esp/www/pf...', true)
#5 /ebs/esp/www/pflammer/trunk3/espaux/apis/vimeo/psalm/src/psalm.php(884): Psalm\{closure}(Array)
#6 /ebs/esp/www/pflammer/trunk3/espaux/apis/vimeo/psalm/psalm(2): require_once('/ebs/esp/www/pf...')
#7 {main}
```

**Comment by juacala** [comment]
Pasting

```
<?php

namespace ESP\core;

/**
 * Any SQL variants should extend this class. Down the road you can add in required methods here that throw an error if they haven't been overridden. Right now it has some helper methods that functions can call in their private methods.
 *
 */
class BaseSQL
{
    /**
     * @var bool $nullsUnique Whether or not nulls are considered unique in this database.
     */
    public static $nullsUnique = null;
}

namespace ESP\core\mssql;

use \ESP\core\BaseSQL;
use ESP\core\ESPErr;
use \ESP\core\SQL;
use \ESP\core\mysql\MySQL;


class MSSQL extends BaseSQL
{
    /**
     * @var bool $nullsUnique Whether or not nulls are considered unique in this database.
     */
    public static $nullsUnique = true;
    /**
     * @var array $sqlFunctions These are functions that are loaded to make this db type work on the system.
     */
    public static $sqlFunctions = [
        "substring_index"
    ];
}
```

into psalm.dev does NOT reproduce the issue. I should have mentioned that in the initial post. At least I don't see any kind of indication there is an exception, and it appears to be parsing correctly.

**Comment by orklah** [comment]
I see you add a "\" before some of your imports but not all. Could there be an issue on that? Try adding the leading "\" everywhere maybe?

**Comment by juacala** [comment]
I grep'd through the codebase and changed any imports that didn't have a leading \ to have it. That did change things.

I now get the following error:
```
Uncaught Exception: $storage should not be null for ESP\unit\unit::appconfig
Stack trace in the forked worker:
#0 /ebs/esp/www/pflammer/trunk3/espaux/apis/vimeo/psalm/src/Psalm/Internal/Analyzer/ClassAnalyzer.php(1850): Psalm\Internal\Codebase\Methods->getStorage(Object(Psalm\Internal\MethodIdentifier))
#1 /ebs/esp/www/pflammer/trunk3/espaux/apis/vimeo/psalm/src/Psalm/Internal/Analyzer/ClassAnalyzer.php(1793): Psalm\Internal\Analyzer\ClassAnalyzer::analyzeClassMethodReturnType(Object(PhpParser\Node\Stmt\ClassMethod), Object(Psalm\Internal\Analyzer\MethodAnalyzer), Object(Psalm\Internal\Analyzer\ClassAnalyzer), Object(Psalm\Internal\Provider\NodeDataProvider), Object(Psalm\Codebase), Object(Psalm\Storage\ClassLikeStorage), 'ESP\\unit\\unit', Object(Psalm\Internal\MethodIdentifier), Object(Psalm\Internal\MethodIdentifier), true)
#2 /ebs/esp/www/pflammer/trunk3/espaux/apis/vimeo/psalm/src/Psalm/Internal/Analyzer/ClassAnalyzer.php(405): Psalm\Internal\Analyzer\ClassAnalyzer->analyzeClassMethod(Object(PhpParser\Node\Stmt\ClassMethod), Object(Psalm\Storage\ClassLikeStorage), Object(Psalm\Internal\Analyzer\ClassAnalyzer), Object(Psalm\Context), Object(Psalm\Context))
#3 /ebs/esp/www/pflammer/trunk3/espaux/apis/vimeo/psalm/src/Psalm/Internal/Analyzer/FileAnalyzer.php(213): Psalm\Internal\Analyzer\ClassAnalyzer->analyze(Object(Psalm\Context), Object(Psalm\Context))
#4 /ebs/esp/www/pflammer/trunk3/espaux/apis/vimeo/psalm/src/Psalm/Internal/Codebase/Analyzer.php(341): Psalm\Internal\Analyzer\FileAnalyzer->analyze(NULL)
#5 /ebs/esp/www/pflammer/trunk3/espaux/apis/vimeo/psalm/src/Psalm/Internal/Fork/Pool.php(193): Psalm\Internal\Codebase\Analyzer->Psalm\Internal\Codebase\{closure}(18, '/ebs/esp/www/pf...')
#6 /ebs/esp/www/pflammer/trunk3/espaux/apis/vimeo/psalm/src/Psalm/Internal/Codebase/Analyzer.php(465): Psalm\Internal\Fork\Pool->__construct(Array, Object(Closure), Object(Closure), Object(Closure), Object(Closure))
#7 /ebs/esp/www/pflammer/trunk3/espaux/apis/vimeo/psalm/src/Psalm/Internal/Codebase/Analyzer.php(270): Psalm\Internal\Codebase\Analyzer->doAnalysis(Object(Psalm\Internal\Analyzer\ProjectAnalyzer), 3)
#8 /ebs/esp/www/pflammer/trunk3/espaux/apis/vimeo/psalm/src/Psalm/Internal/Analyzer/ProjectAnalyzer.php(636): Psalm\Internal\Codebase\Analyzer->analyzeFiles(Object(Psalm\Internal\Analyzer\ProjectAnalyzer), 3, false, true)
#9 /ebs/esp/www/pflammer/trunk3/espaux/apis/vimeo/psalm/src/psalm.php(700): Psalm\Internal\Analyzer\ProjectAnalyzer->check('/ebs/esp/www/pf...', true)
#10 /ebs/esp/www/pflammer/trunk3/espaux/apis/vimeo/psalm/src/psalm.php(884): Psalm\{closure}(Array)
#11 /ebs/esp/www/pflammer/trunk3/espaux/apis/vimeo/psalm/psalm(2): require_once('/ebs/esp/www/pf...')
#12 {main} in /ebs/esp/www/pflammer/trunk3/espaux/apis/vimeo/psalm/src/Psalm/Internal/Fork/Pool.php:357
Stack trace:
#0 /ebs/esp/www/pflammer/trunk3/espaux/apis/vimeo/psalm/src/Psalm/Internal/Fork/Pool.php(389): Psalm\Internal\Fork\Pool->readResultsFromChildren()
#1 /ebs/esp/www/pflammer/trunk3/espaux/apis/vimeo/psalm/src/Psalm/Internal/Codebase/Analyzer.php(474): Psalm\Internal\Fork\Pool->wait()
#2 /ebs/esp/www/pflammer/trunk3/espaux/apis/vimeo/psalm/src/Psalm/Internal/Codebase/Analyzer.php(270): Psalm\Internal\Codebase\Analyzer->doAnalysis(Object(Psalm\Internal\Analyzer\ProjectAnalyzer), 3)
#3 /ebs/esp/www/pflammer/trunk3/espaux/apis/vimeo/psalm/src/Psalm/Internal/Analyzer/ProjectAnalyzer.php(636): Psalm\Internal\Codebase\Analyzer->analyzeFiles(Object(Psalm\Internal\Analyzer\ProjectAnalyzer), 3, false, true)
#4 /ebs/esp/www/pflammer/trunk3/espaux/apis/vimeo/psalm/src/psalm.php(700): Psalm\Internal\Analyzer\ProjectAnalyzer->check('/ebs/esp/www/pf...', true)
#5 /ebs/esp/www/pflammer/trunk3/espaux/apis/vimeo/psalm/src/psalm.php(884): Psalm\{closure}(Array)
#6 /ebs/esp/www/pflammer/trunk3/espaux/apis/vimeo/psalm/psalm(2): require_once('/ebs/esp/www/pf...')
#7 {main}
(Psalm 4.7.1@cd53e047a58f71f646dd6bf45476076ab07b5d44 crashed due to an uncaught Throwable)
```

This appears to be similar to the following issue:
[Issue 4899](https://github.com/vimeo/psalm/issues/4899)

I tried adding in some error_log statements to the psalm files responsible, and what I find is that it either hangs or gives similar errors to the first one I got or this one, but for different places in our code. That makes me think it's a concurrency issue as multiple threads are used. 

Is there a way with psalm --init to run it with just one thread?

Thanks!

**Comment by orklah** [comment]
Try something like psalm --init 8 src. the number is the level you want to run that you will be able to change later. I think I remember Psalm not needing to actually analyze if you give it the level directly
