### ISSUE TITLE
ClassAnalyzer.php: Property Failure

### ISSUE THREAD

**Issue by bdrodes** [vimeo/psalm#5728]
Psalter reporting the following exception when analyzing a class called FormSoap, apparently it doesn't see the internal field `var $objective`. 

```
Uncaught Exception: Property formsoap::$objective should exist 133 / 1783 (7%)
```

The stack trace says it is failing on ​line 432 of Internal/Analyzer/ClassAnalyzer.php::analyze

``` 
$property_storage = $codebase->properties->getStorage($property_id);
```

I can't reproduce this running on a single module. For some reason this only occurs when running psalter on the entire project. I'm not sure how to send a reproducible code snippet, so I thought I would ask if there was any way a class property could somehow disappear prior to this line in the ClassAnalyzer?

Here is the complete stack trace:

```
Uncaught Exception: Property formsoap::$objective should exist 133 / 1783 (7%)
Stack trace in the forked worker:
#0 psalm/src/Psalm/Internal/Analyzer/ClassAnalyzer.php(432): Psalm\Internal\Codebase\Properties->getStorage('formsoap::$obje...')
#1 psalm/src/Psalm/Internal/Analyzer/FileAnalyzer.php(213): Psalm\Internal\Analyzer\ClassAnalyzer->analyze(Object(Psalm\Context), Object(Psalm\Context))
#2 psalm/src/Psalm/Internal/Analyzer/Statements/Expression/IncludeAnalyzer.php(198): Psalm\Internal\Analyzer\FileAnalyzer->analyze(Object(Psalm\Context), NULL)
#3 psalm/src/Psalm/Internal/Analyzer/Statements/ExpressionAnalyzer.php(313): Psalm\Internal\Analyzer\Statements\Expression\IncludeAnalyzer::analyze(Object(Psalm\Internal\Analyzer\StatementsAnalyzer), Object(PhpParser\Node\Expr\Include_), Object(Psalm\Context), NULL)
#4 psalm/src/Psalm/Internal/Analyzer/Statements/ExpressionAnalyzer.php(45): Psalm\Internal\Analyzer\Statements\ExpressionAnalyzer::handleExpression(Object(Psalm\Internal\Analyzer\StatementsAnalyzer), Object(PhpParser\Node\Expr\Include_), Object(Psalm\Context), false, NULL, true)
#5 psalm/src/Psalm/Internal/Analyzer/StatementsAnalyzer.php(530): Psalm\Internal\Analyzer\Statements\ExpressionAnalyzer::analyze(Object(Psalm\Internal\Analyzer\StatementsAnalyzer), Object(PhpParser\Node\Expr\Include_), Object(Psalm\Context), false, NULL, true)
#6 psalm/src/Psalm/Internal/Analyzer/StatementsAnalyzer.php(172): Psalm\Internal\Analyzer\StatementsAnalyzer::analyzeStatement(Object(Psalm\Internal\Analyzer\StatementsAnalyzer), Object(PhpParser\Node\Stmt\Expression), Object(Psalm\Context), NULL)
#7 psalm/src/Psalm/Internal/Analyzer/FileAnalyzer.php(189): Psalm\Internal\Analyzer\StatementsAnalyzer->analyze(Array, Object(Psalm\Context), NULL, true)
#8 psalm/src/Psalm/Internal/Codebase/Analyzer.php(341): Psalm\Internal\Analyzer\FileAnalyzer->analyze(NULL)
#9 psalm/src/Psalm/Internal/Fork/Pool.php(193): Psalm\Internal\Codebase\Analyzer->Psalm\Internal\Codebase\{closure}(15, '/home/o...')
#10 psalm/src/Psalm/Internal/Codebase/Analyzer.php(465): Psalm\Internal\Fork\Pool->__construct(Array, Object(Closure), Object(Closure), Object(Closure), Object(Closure))
#11 psalm/src/Psalm/Internal/Codebase/Analyzer.php(270): Psalm\Internal\Codebase\Analyzer->doAnalysis(Object(Psalm\Internal\Analyzer\ProjectAnalyzer), 16)
#12 psalm/src/Psalm/Internal/Analyzer/ProjectAnalyzer.php(636): Psalm\Internal\Codebase\Analyzer->analyzeFiles(Object(Psalm\Internal\Analyzer\ProjectAnalyzer), 16, true, true)
#13 psalm/src/psalter.php(507): Psalm\Internal\Analyzer\ProjectAnalyzer->check('/home/o...')
#14 psalm/src/psalter.php(520): Psalm\{closure}(Array)
#15 psalm/src/psalm.php(150): require_once('/home/v...')
#16 psalm/src/psalm.php(884): Psalm\{closure}(Array)
#17 psalm/psalm(2): require_once('/home/v...')
#18 {main} in psalm/src/Psalm/Internal/Fork/Pool.php:365
Stack trace:
#0 psalm/src/Psalm/Internal/Fork/Pool.php(399): Psalm\Internal\Fork\Pool->readResultsFromChildren()
#1 psalm/src/Psalm/Internal/Codebase/Analyzer.php(474): Psalm\Internal\Fork\Pool->wait()
#2 psalm/src/Psalm/Internal/Codebase/Analyzer.php(270): Psalm\Internal\Codebase\Analyzer->doAnalysis(Object(Psalm\Internal\Analyzer\ProjectAnalyzer), 16)
#3 psalm/src/Psalm/Internal/Analyzer/ProjectAnalyzer.php(636): Psalm\Internal\Codebase\Analyzer->analyzeFiles(Object(Psalm\Internal\Analyzer\ProjectAnalyzer), 16, true, true)
#4 psalm/src/psalter.php(507): Psalm\Internal\Analyzer\ProjectAnalyzer->check('/home/o...')
#5 psalm/src/psalter.php(520): Psalm\{closure}(Array)
#6 psalm/src/psalm.php(150): require_once('/home/v...')
#7 psalm/src/psalm.php(884): Psalm\{closure}(Array)
#8 psalm/psalm(2): require_once('/home/v...')
#9 {main}
```

**Comment by orklah** [comment]
Can you check if you have consistent casing for the class and the property everywhere in your code?
Also, can you try --debug-by-line to check where the execution stops?

**Comment by orklah** [comment]
Closing as stale
