### ISSUE TITLE
Crash related to no-return in 4.7.1+

### ISSUE THREAD

**Issue by pilif** [vimeo/psalm#5751]
After updating from 4.7.0 to 4.7.2, and running over our (quite crusty but improving) code-base, we get the following crash:

```
Uncaught Exception: There should be types here░░░░░░░░░░░░░░   343 / 2136 (16%)
Stack trace in the forked worker:
#0 /Users/pilif/…/vendor/vimeo/psalm/src/Psalm/Type.php(464): Psalm\Internal\Type\TypeCombiner::combine(Array, NULL, false, true, 500)
#1 /Users/pilif/…/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/Statements/Expression/TernaryAnalyzer.php(267): Psalm\Type::combineUnionTypes(Object(Psalm\Type\Union), Object(Psalm\Type\Union))
#2 /Users/pilif/…/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/Statements/ExpressionAnalyzer.php(267): Psalm\Internal\Analyzer\Statements\Expression\TernaryAnalyzer::analyze(Object(Psalm\Internal\Analyzer\StatementsAnalyzer), Object(PhpParser\Node\Expr\Ternary), Object(Psalm\Context))
#3 /Users/pilif/…/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/Statements/ExpressionAnalyzer.php(40): Psalm\Internal\Analyzer\Statements\ExpressionAnalyzer::handleExpression(Object(Psalm\Internal\Analyzer\StatementsAnalyzer), Object(PhpParser\Node\Expr\Ternary), Object(Psalm\Context), false, Object(Psalm\Context), true)
#4 /Users/pilif/…/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/StatementsAnalyzer.php(530): Psalm\Internal\Analyzer\Statements\ExpressionAnalyzer::analyze(Object(Psalm\Internal\Analyzer\StatementsAnalyzer), Object(PhpParser\Node\Expr\Ternary), Object(Psalm\Context), false, Object(Psalm\Context), true)
#5 /Users/pilif/…/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/StatementsAnalyzer.php(172): Psalm\Internal\Analyzer\StatementsAnalyzer::analyzeStatement(Object(Psalm\Internal\Analyzer\StatementsAnalyzer), Object(PhpParser\Node\Stmt\Expression), Object(Psalm\Context), Object(Psalm\Context))
#6 /Users/pilif/…/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/FunctionLikeAnalyzer.php(430): Psalm\Internal\Analyzer\StatementsAnalyzer->analyze(Array, Object(Psalm\Context), Object(Psalm\Context), true)
#7 /Users/pilif/…/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/ClassAnalyzer.php(1776): Psalm\Internal\Analyzer\FunctionLikeAnalyzer->analyze(Object(Psalm\Context), Object(Psalm\Internal\Provider\NodeDataProvider), Object(Psalm\Context))
#8 /Users/pilif/…/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/ClassAnalyzer.php(401): Psalm\Internal\Analyzer\ClassAnalyzer->analyzeClassMethod(Object(PhpParser\Node\Stmt\ClassMethod), Object(Psalm\Storage\ClassLikeStorage), Object(Psalm\Internal\Analyzer\ClassAnalyzer), Object(Psalm\Context), Object(Psalm\Context))
#9 /Users/pilif/…/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/FileAnalyzer.php(213): Psalm\Internal\Analyzer\ClassAnalyzer->analyze(Object(Psalm\Context), Object(Psalm\Context))
#10 /Users/pilif/…/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Analyzer.php(341): Psalm\Internal\Analyzer\FileAnalyzer->analyze(NULL)
#11 /Users/pilif/…/vendor/vimeo/psalm/src/Psalm/Internal/Fork/Pool.php(193): Psalm\Internal\Codebase\Analyzer->Psalm\Internal\Codebase\{closure}(12, '/Users/pilif/Si...')
#12 /Users/pilif/…/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Analyzer.php(407): Psalm\Internal\Fork\Pool->__construct(Array, Object(Closure), Object(Closure), Object(Closure), Object(Closure))
#13 /Users/pilif/…/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Analyzer.php(270): Psalm\Internal\Codebase\Analyzer->doAnalysis(Object(Psalm\Internal\Analyzer\ProjectAnalyzer), 16)
#14 /Users/pilif/…/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/ProjectAnalyzer.php(636): Psalm\Internal\Codebase\Analyzer->analyzeFiles(Object(Psalm\Internal\Analyzer\ProjectAnalyzer), 16, false, true)
#15 /Users/pilif/…/vendor/vimeo/psalm/src/psalm.php(700): Psalm\Internal\Analyzer\ProjectAnalyzer->check('/Users/pilif/Si...', true)
#16 /Users/pilif/…/vendor/vimeo/psalm/src/psalm.php(884): Psalm\{closure}(Array)
#17 /Users/pilif/…/vendor/vimeo/psalm/psalm(2): require_once('/Users/pilif/Si...')
#18 {main} in /Users/pilif/…/vendor/vimeo/psalm/src/Psalm/Internal/Fork/Pool.php:365
Stack trace:
#0 /Users/pilif/…/vendor/vimeo/psalm/src/Psalm/Internal/Fork/Pool.php(399): Psalm\Internal\Fork\Pool->readResultsFromChildren()
#1 /Users/pilif/…/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Analyzer.php(474): Psalm\Internal\Fork\Pool->wait()
#2 /Users/pilif/…/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Analyzer.php(270): Psalm\Internal\Codebase\Analyzer->doAnalysis(Object(Psalm\Internal\Analyzer\ProjectAnalyzer), 16)
#3 /Users/pilif/…/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/ProjectAnalyzer.php(636): Psalm\Internal\Codebase\Analyzer->analyzeFiles(Object(Psalm\Internal\Analyzer\ProjectAnalyzer), 16, false, true)
#4 /Users/pilif/…/vendor/vimeo/psalm/src/psalm.php(700): Psalm\Internal\Analyzer\ProjectAnalyzer->check('/Users/pilif/Si...', true)
#5 /Users/pilif/…/vendor/vimeo/psalm/src/psalm.php(884): Psalm\{closure}(Array)
#6 /Users/pilif/…/vendor/vimeo/psalm/psalm(2): require_once('/Users/pilif/…')
#7 {main}
(Psalm 4.7.2@83a0325c0a95c0ab531d6b90c877068b464377b5 crashed due to an uncaught Throwable)
```

I'm posting this now before I have additional info, but I'm going to update this issue with further diagnositics and maybe, if I'm lucky, a reduced test-case.

**Comment by pilif** [comment]
also happens on 4.7.1, possibly related to some `@return no-return`. trying to produce a reduced test-case.

**Comment by pilif** [comment]
reduced test case:

https://psalm.dev/r/c9180e1833

**Comment by weirdan** [comment]
Simplified a bit: https://psalm.dev/r/77a0a4ce53

**Comment by pilif** [comment]
it even happens without the `rand()`

https://psalm.dev/r/0e5070841d
