### ISSUE TITLE
"Could not located any PSR-0 or PSR-4-compatible paths..." when running ./vendor/bin/psalm.phar --init

### ISSUE THREAD

**Issue by nth347** [vimeo/psalm#5754]
I have the following exception when running ./vendor/bin/psalm.phar --init
```
nth347@ubuntu:~/PhpstormProjects/psalm$ ./vendor/bin/psalm.phar --init
Calculating best config level based on project files
Uncaught Psalm\Exception\ConfigCreationException: Could not located any PSR-0 or PSR-4-compatible paths in /home/nth347/PhpstormProjects/psalm//composer.json in phar:///home/nth347/PhpstormProjects/psalm/vendor/psalm/phar/psalm.phar/src/Psalm/Config/Creator.php:137
Stack trace:
#0 phar:///home/nth347/PhpstormProjects/psalm/vendor/psalm/phar/psalm.phar/src/Psalm/Config/Creator.php(50): Psalm\Config\Creator::getPaths()
#1 phar:///home/nth347/PhpstormProjects/psalm/vendor/psalm/phar/psalm.phar/src/Psalm/Config/Creator.php(62): Psalm\Config\Creator::getContents()
#2 phar:///home/nth347/PhpstormProjects/psalm/vendor/psalm/phar/psalm.phar/src/psalm.php(257): Psalm\Config\Creator::createBareConfig()
#3 phar:///home/nth347/PhpstormProjects/psalm/vendor/psalm/phar/psalm.phar/src/psalm.php(571): Psalm\{closure}()
#4 phar:///home/nth347/PhpstormProjects/psalm/vendor/psalm/phar/psalm.phar/psalm(5): require_once('phar:///home/nt...')
#5 /home/nth347/PhpstormProjects/psalm/vendor/psalm/phar/psalm.phar(14): require('phar:///home/nt...')
#6 {main}
(Psalm 4.x-dev@ crashed due to an uncaught Throwable)

```
Please help

**Comment by weirdan** [comment]
Mind sharing your `composer.json`? Psalm expects either `autoload.psr-4` or `autoload.psr-0` entries to be there, otherwise you need to create `psalm.xml` manually (i.e. you can't use `--init`) and use a custom autoloader.

**Comment by nth347** [comment]
Hi @weirdan, I added PSR-0 autoload section into composer.json, the problem has vanished, thanks!
