### ISSUE TITLE
Unable to create baseline in psalm 4.8.0

### ISSUE THREAD

**Issue by NoodlesNZ** [vimeo/psalm#5960]
I upgraded a project to psalm 4.8.0 this morning and tried to create a baseline (using `./vendor/bin/psalm --set-baseline=site-baseline.xml`) and it give me this:

```
Writing error baseline to file...
Uncaught Psalm\Exception\ConfigException: site-baseline.xml does not exist or is not readable in /Users/noodles/Developer/web/site/vendor/vimeo/psalm/src/Psalm/ErrorBaseline.php:78
Stack trace:
#0 /Users/noodles/Developer/web/site/vendor/vimeo/psalm/src/Psalm/Internal/Cli/Psalm.php(623): Psalm\ErrorBaseline::read(Object(Psalm\Internal\Provider\FileProvider), 'site-baseline.xm...')
#1 /Users/noodles/Developer/web/site/vendor/vimeo/psalm/src/Psalm/Internal/Cli/Psalm.php(1002): Psalm\Internal\Cli\Psalm::generateBaseline(Array, Object(Psalm\Config), '/Users/noodles/...', NULL)
#2 /Users/noodles/Developer/web/site/vendor/vimeo/psalm/src/Psalm/Internal/Cli/Psalm.php(386): Psalm\Internal\Cli\Psalm::initBaseline(Array, Object(Psalm\Config), '/Users/noodles/...', NULL)
#3 /Users/noodles/Developer/web/site/vendor/vimeo/psalm/psalm(4): Psalm\Internal\Cli\Psalm::run(Array)
#4 {main}
(Psalm 4.8.0@0a57c865499049527b3e1c47f14abea761d94b83 crashed due to an uncaught Throwable)
```

Downgrading to psalm 4.7.2 and re-running the command seemed to work.

**Comment by weirdan** [comment]
Confirmed locally on master

**Comment by weirdan** [comment]
As a workaround, you can generate it using an older version and then re-generate it with 4.8

**Comment by NoodlesNZ** [comment]
Thanks @muglug and @weirdan for your quick responses and resolution :)

**Comment by muglug** [comment]
@weirdan any reason why you reopened this?

**Comment by weirdan** [comment]
@muglug yep, I think the fix provided in the linked PR is better.
