### ISSUE TITLE
`@var [] something` crashes psalm

### ISSUE THREAD

**Issue by weirdan** [vimeo/psalm#617]
```php
<?php
class A {
    /**
     * @var [] some desc
     */
    private $q = [];
}
```
Checking this results in
```
PHP Fatal error:  Uncaught InvalidArgumentException: Unrecognised parse tree type in /home/weirdan/.composer/vendor/vimeo/psalm/src/Psalm/Type.php:260
Stack trace:
#0 /home/weirdan/.composer/vendor/vimeo/psalm/src/Psalm/Type.php(136): Psalm\Type::getTypeFromTree(Object(Psalm\Type\ParseTree\Root), false)
#1 [internal function]: Psalm\Type::Psalm\{closure}(Object(Psalm\Type\ParseTree\Root))
#2 /home/weirdan/.composer/vendor/vimeo/psalm/src/Psalm/Type.php(140): array_map(Object(Closure), Array)
#3 /home/weirdan/.composer/vendor/vimeo/psalm/src/Psalm/Type.php(64): Psalm\Type::getTypeFromTree(Object(Psalm\Type\ParseTree\GenericTree), false)
#4 /home/weirdan/.composer/vendor/vimeo/psalm/src/Psalm/Checker/CommentChecker.php(93): Psalm\Type::parseString('[]')
#5 /home/weirdan/.composer/vendor/vimeo/psalm/src/Psalm/Visitor/DependencyFinderVisitor.php(1280): Psalm\Checker\CommentChecker::getTypeFromComment('/**\n     * @var...', Object(Psalm\Scanner\FileScanner), Object(Psalm\Aliases), Array, 4)
#6 /home/weirdan/.composer/vendor/vimeo/p in /home/weirdan/.composer/vendor/vimeo/psalm/src/Psalm/Type.php on line 260
```
I've never seen people using '[]' to denote arbitrary array in docblocks (in `@var`, `@param` and `@return` specifically), but it seems to have some popularity, as I found this to be used in two unrelated libraries.

Bisect points to c8fe9e89, before that psalm didn't crash on this input.

**Comment by muglug** [comment]
Yeah, broken ultimately because I removed [this catch](https://github.com/vimeo/psalm/commit/3f90bceabffee5c610010b930d3cbe7585f95a3f#diff-810ca6a7d560572fbea4e190abd34630L71) to help debugging when working on a feature.
