### ISSUE TITLE
Running after requiring with no scripts results in fatal error

### ISSUE THREAD

**Issue by kubawerlos** [vimeo/psalm#622]
Running:
```bash
composer require --dev vimeo/psalm --no-scripts
./vendor/bin/psalm --init
```
(`--no-scripts` in `require` might look weird, but the same applies to `install`)
results in:
```bash
PHP Fatal error:  Uncaught OutOfBoundsException: Required package "vimeo/psalm" is not installed: cannot detect its version in /foo/vendor/muglug/package-versions-56/src/PackageVersions/Versions.php:69
Stack trace:
#0 /foo/vendor/vimeo/psalm/src/command_functions.php(78): Muglug\PackageVersions\Versions::getVersion('vimeo/psalm')
#1 /foo/vendor/vimeo/psalm/src/psalm.php(139): requireAutoloaders('/foo...', false, 'vendor')
#2 /foo/vendor/vimeo/psalm/psalm(2): require_once('/foo...')
#3 {main}
  thrown in /foo/vendor/muglug/package-versions-56/src/PackageVersions/Versions.php on line 69

Fatal error: Uncaught OutOfBoundsException: Required package "vimeo/psalm" is not installed: cannot detect its version in /foo/vendor/muglug/package-versions-56/src/PackageVersions/Versions.php:69
Stack trace:
#0 /foo/vendor/vimeo/psalm/src/command_functions.php(78): Muglug\PackageVersions\Versions::getVersion('vimeo/psalm')
#1 /foo/vendor/vimeo/psalm/src/psalm.php(139): requireAutoloaders('/foo...', false, 'vendor')
#2 /foo/vendor/vimeo/psalm/psalm(2): require_once('/foo...')
#3 {main}
  thrown in /foo/vendor/muglug/package-versions-56/src/PackageVersions/Versions.php on line 69
```

Shouldn't the exception be handled?

**Comment by weirdan** [comment]
Actually FallbackVersions should kick in, it exists there primarily to support this use case.

**Comment by weirdan** [comment]
@muglug I think `Versions.php` should look similar to this: https://github.com/Ocramius/PackageVersions/blob/633b8dbdc28569ad6ed0f59ec5802d47ece96114/src/PackageVersions/Versions.php
