### ISSUE TITLE
Psalm tries to remove a non-empty directory after a config change, causes one-time crash

### ISSUE THREAD

**Issue by fluffycondor** [vimeo/psalm#6224]
Step to reproduce (possible only sometimes):
1. Manually remove and then add again some plugin in the <plugins> sections in psalm.xml
2. Try to run vendor/bin/psalm

```
Uncaught RuntimeException: PHP Error: rmdir(/home/user/.cache/psalm/2166e28d365c20e11b5e7545cab6785113fefaf4/class_cache): Directory not empty in /home/user/project_dir/vendor/vimeo/psalm/src/Psalm/Config.php:2145 in /home/user/project_dir/vendor/vimeo/psalm/src/Psalm/Internal/ErrorHandler.php:66
Stack trace:
#0 [internal function]: Psalm\Internal\ErrorHandler::Psalm\Internal\{closure}()
#1 /home/user/project_dir/vendor/vimeo/psalm/src/Psalm/Config.php(2145): rmdir()
#2 /home/user/project_dir/vendor/vimeo/psalm/src/Psalm/Config.php(2137): Psalm\Config::removeCacheDirectory()
#3 /home/user/project_dir/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/ProjectAnalyzer.php(332): Psalm\Config::removeCacheDirectory()
#4 /home/user/project_dir/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/ProjectAnalyzer.php(281): Psalm\Internal\Analyzer\ProjectAnalyzer->clearCacheDirectoryIfConfigOrComposerLockfileChanged()
#5 /home/user/project_dir/vendor/vimeo/psalm/src/Psalm/Internal/Cli/Psalm.php(323): Psalm\Internal\Analyzer\ProjectAnalyzer->__construct()
#6 /home/user/project_dir/vendor/vimeo/psalm/psalm(4): Psalm\Internal\Cli\Psalm::run()
#7 {main}
(Psalm 4.8.1@f73f2299dbc59a3e6c4d66cff4605176e728ee69 crashed due to an uncaught Throwable)
```

And it works fine on the next run.

**Comment by fluffycondor** [comment]
> Can you tell us what's left in the directory?
There are 1381 files with hash-like names.

**Comment by fluffycondor** [comment]
Maybe `scandir()` can sometimes silently return an empty array instead of actual results?
https://stackoverflow.com/questions/26679474/php-scandir-returns-an-empty-array-on-network-folder

**Comment by weirdan** [comment]
I've seen this when I had multiple instances of Psalm running (e.g. one run by the editor, on save, and another one from cli).

**Comment by fluffycondor** [comment]
> I've seen this when I had multiple instances of Psalm running (e.g. one run by the editor, on save, and another one from cli).

Yes, it might be the reason. I have Psalm inspection enabled in my PHPStorm.
