### ISSUE TITLE
PHP Fatal error:  Uncaught TypeError: Argument 3 passed to Psalm\Checker\TypeChecker::isContainedBy() must be an instance of Psalm\Type\Union, null given,

### ISSUE THREAD

**Issue by olleharstedt** [vimeo/psalm#623]
Trying to run Psalm on the LimeSurvey project, I received these errors:

```
PHP Notice:  Undefined offset: 2 in /limesurvey/third_party/vimeo/psalm/src/Psalm/Checker/TypeChecker.php on line 369

Notice: Undefined offset: 2 in /limesurvey/third_party/vimeo/psalm/src/Psalm/Checker/TypeChecker.php on line 369
PHP Fatal error:  Uncaught TypeError: Argument 3 passed to Psalm\Checker\TypeChecker::isContainedBy() must be an instance of Psalm\Type\Union, null given, called in /limesurvey/third_party/vimeo/psalm/src/Psalm/Checker/TypeChecker.php on line 380 and defined in /limesurvey/third_party/vimeo/psalm/src/Psalm/Checker/TypeChecker.php:43
Stack trace:
#0 /limesurvey/third_party/vimeo/psalm/src/Psalm/Checker/TypeChecker.php(380): Psalm\Checker\TypeChecker::isContainedBy(Object(Psalm\Codebase), Object(Psalm\Type\Union), NULL, false, false, true, NULL, NULL)
#1 /limesurvey/third_party/vimeo/psalm/src/Psalm/Checker/TypeChecker.php(86): Psalm\Checker\TypeChecker::isAtomicContainedBy(Object(Psalm\Codebase), Object(Psalm\Type\Atomic\TArray), Object(Psalm\Type\Atomic\TArray), true, NULL, NULL, false)
#2 /limesurvey/third_party/vimeo/psalm/src/Psalm/Checker/FunctionLikeChecker.php(971): Psalm\Checker\TypeChecker::isContainedBy(Object(Psalm\Codebase), Object(Psalm\Type in /limesurvey/third_party/vimeo/psalm/src/Psalm/Checker/TypeChecker.php on line 43

Fatal error: Uncaught TypeError: Argument 3 passed to Psalm\Checker\TypeChecker::isContainedBy() must be an instance of Psalm\Type\Union, null given, called in /limesurvey/third_party/vimeo/psalm/src/Psalm/Checker/TypeChecker.php on line 380 and defined in /limesurvey/third_party/vimeo/psalm/src/Psalm/Checker/TypeChecker.php:43
Stack trace:
#0 /limesurvey/third_party/vimeo/psalm/src/Psalm/Checker/TypeChecker.php(380): Psalm\Checker\TypeChecker::isContainedBy(Object(Psalm\Codebase), Object(Psalm\Type\Union), NULL, false, false, true, NULL, NULL)
#1 /limesurvey/third_party/vimeo/psalm/src/Psalm/Checker/TypeChecker.php(86): Psalm\Checker\TypeChecker::isAtomicContainedBy(Object(Psalm\Codebase), Object(Psalm\Type\Atomic\TArray), Object(Psalm\Type\Atomic\TArray), true, NULL, NULL, false)
#2 /limesurvey/third_party/vimeo/psalm/src/Psalm/Checker/FunctionLikeChecker.php(971): Psalm\Checker\TypeChecker::isContainedBy(Object(Psalm\Codebase), Object(Psalm\Type in /limesurvey/third_party/vimeo/psalm/src/Psalm/Checker/TypeChecker.php on line 43
```

Any idea for a next step?

**Comment by muglug** [comment]
> Any idea for a next step?

yes, the best option is to get the latest Psalm `dev-master` where I've added a `--debug-by-line` option, allowing you to identify the particular line Psalm fails on.

**Comment by olleharstedt** [comment]
OK. Can I get it via composer?

**Comment by weirdan** [comment]
`composer require vimeo/psalm:dev-master`

**Comment by muglug** [comment]
Also, sorry you found this bug!

**Comment by olleharstedt** [comment]
Sorry, I get this error message from composer:

```
$ composer require --dev vimeo/psalm:dev-master
You are running composer with xdebug enabled. This has a major impact on runtime performance. See https://getcomposer.org/xdebug
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Can only install one of: muglug/package-versions-56[1.2.4, 1.2.3].
    - Can only install one of: muglug/package-versions-56[1.2.4, 1.2.3].
    - Can only install one of: muglug/package-versions-56[1.2.4, 1.2.3].
    - vimeo/psalm dev-master requires muglug/package-versions-56 1.2.4 -> satisfiable by muglug/package-versions-56[1.2.4].
    - Installation request for vimeo/psalm dev-master -> satisfiable by vimeo/psalm[dev-master].
    - Installation request for muglug/package-versions-56 (locked at 1.2.3) -> satisfiable by muglug/package-versions-56[1.2.3].


Installation failed, reverting ./composer.json to its original content.
```

**Comment by weirdan** [comment]
Then it would be `composer require --dev --update-with-all-dependencies vimeo/psalm:dev-master`

**Comment by olleharstedt** [comment]
Error message after update to dev:

```
$ ./third_party/bin/psalm 
Scanning files...
PHP Fatal error:  Uncaught Psalm\Exception\TypeParseTreeException: Cannot parse generic type in /var/www/lime25/limesurvey/third_party/vimeo/psalm/src/Psalm/Type/ParseTree.php:104
Stack trace:
#0 /var/www/lime25/limesurvey/third_party/vimeo/psalm/src/Psalm/Type.php(61): Psalm\Type\ParseTree::createFromTokens(Array)
#1 /var/www/lime25/limesurvey/third_party/vimeo/psalm/src/Psalm/Codebase/CallMap.php(75): Psalm\Type::parseString('callable():void')
#2 /var/www/lime25/limesurvey/third_party/vimeo/psalm/src/Psalm/Visitor/DependencyFinderVisitor.php(332): Psalm\Codebase\CallMap::getParamsFromCallMap('register_shutdo...')
#3 /var/www/lime25/limesurvey/third_party/nikic/php-parser/lib/PhpParser/NodeTraverser.php(159): Psalm\Visitor\DependencyFinderVisitor->enterNode(Object(PhpParser\Node\Expr\FuncCall))
#4 /var/www/lime25/limesurvey/third_party/nikic/php-parser/lib/PhpParser/NodeTraverser.php(101): PhpParser\NodeTraverser->traverseArray(Array)
#5 /var/www/lime25/limesurvey/third_party/nikic/php-parser/lib/PhpParser/NodeTraverser.php(1 in /var/www/lime25/limesurvey/third_party/vimeo/psalm/src/Psalm/Type/ParseTree.php on line 104

Fatal error: Uncaught Psalm\Exception\TypeParseTreeException: Cannot parse generic type in /var/www/lime25/limesurvey/third_party/vimeo/psalm/src/Psalm/Type/ParseTree.php:104
Stack trace:
#0 /var/www/lime25/limesurvey/third_party/vimeo/psalm/src/Psalm/Type.php(61): Psalm\Type\ParseTree::createFromTokens(Array)
#1 /var/www/lime25/limesurvey/third_party/vimeo/psalm/src/Psalm/Codebase/CallMap.php(75): Psalm\Type::parseString('callable():void')
#2 /var/www/lime25/limesurvey/third_party/vimeo/psalm/src/Psalm/Visitor/DependencyFinderVisitor.php(332): Psalm\Codebase\CallMap::getParamsFromCallMap('register_shutdo...')
#3 /var/www/lime25/limesurvey/third_party/nikic/php-parser/lib/PhpParser/NodeTraverser.php(159): Psalm\Visitor\DependencyFinderVisitor->enterNode(Object(PhpParser\Node\Expr\FuncCall))
#4 /var/www/lime25/limesurvey/third_party/nikic/php-parser/lib/PhpParser/NodeTraverser.php(101): PhpParser\NodeTraverser->traverseArray(Array)
#5 /var/www/lime25/limesurvey/third_party/nikic/php-parser/lib/PhpParser/NodeTraverser.php(1 in /var/www/lime25/limesurvey/third_party/vimeo/psalm/src/Psalm/Type/ParseTree.php on line 104
```

**Comment by weirdan** [comment]
Now that's totally different problem, related to fresh from-the-oven callable syntax additions.
/ping @muglug

**Comment by olleharstedt** [comment]
Is there any specific construct in the code-base that triggers this error?

**Comment by weirdan** [comment]
The reference to `register_shutdown_function()` in this case. However it's quite possible that other built-in functions are currently affected. Psalm apparently not yet fully compatible with the function map imported from Phan.

If your `vendor/vimeo/psalm` (assuming standard composer layout) contains a git checkout, you may try to go back before the commit that imported that map (`git checkout 3ef70738623af08ef2624ac522e9ddf3c83e220e^` should do the trick, caret is important here).

**Comment by muglug** [comment]
Again, running with `--debug-by-line` will tell you where Psalm is failing

**Comment by olleharstedt** [comment]
@muglug Thank you!

**Comment by muglug** [comment]
@olleharstedt @weirdan yes, sorry those were broken by changes made last night. Latest `dev-master` should protect against those issues.

**Comment by olleharstedt** [comment]
Got another error:

```
PHP Fatal error:  Uncaught InvalidArgumentException: Cannot handle static when $static_class is empty in /var/www/lime25/limesurvey/third_party/vimeo/psalm/src/Psalm/Checker/Statements/ExpressionChecker.php:761
Stack trace:
#0 /var/www/lime25/limesurvey/third_party/vimeo/psalm/src/Psalm/Checker/Statements/ExpressionChecker.php(728): Psalm\Checker\Statements\ExpressionChecker::fleshOutAtomicType(Object(Psalm\Checker\ProjectChecker), Object(Psalm\Type\Atomic\TNamedObject), NULL, NULL)
#1 /var/www/lime25/limesurvey/third_party/vimeo/psalm/src/Psalm/Checker/Statements/Expression/AssignmentChecker.php(97): Psalm\Checker\Statements\ExpressionChecker::fleshOutType(Object(Psalm\Checker\ProjectChecker), Object(Psalm\Type\Union), NULL, NULL)
#2 /var/www/lime25/limesurvey/third_party/vimeo/psalm/src/Psalm/Checker/Statements/ExpressionChecker.php(87): Psalm\Checker\Statements\Expression\AssignmentChecker::analyze(Object(Psalm\Checker\StatementsChecker), Object(PhpParser\Node\Expr\Variable), Object(PhpParser\Node\Expr\StaticCall), NULL, Ob in /var/www/lime25/limesurvey/third_party/vimeo/psalm/src/Psalm/Checker/Statements/ExpressionChecker.php on line 761

Fatal error: Uncaught InvalidArgumentException: Cannot handle static when $static_class is empty in /var/www/lime25/limesurvey/third_party/vimeo/psalm/src/Psalm/Checker/Statements/ExpressionChecker.php:761
Stack trace:
#0 /var/www/lime25/limesurvey/third_party/vimeo/psalm/src/Psalm/Checker/Statements/ExpressionChecker.php(728): Psalm\Checker\Statements\ExpressionChecker::fleshOutAtomicType(Object(Psalm\Checker\ProjectChecker), Object(Psalm\Type\Atomic\TNamedObject), NULL, NULL)
#1 /var/www/lime25/limesurvey/third_party/vimeo/psalm/src/Psalm/Checker/Statements/Expression/AssignmentChecker.php(97): Psalm\Checker\Statements\ExpressionChecker::fleshOutType(Object(Psalm\Checker\ProjectChecker), Object(Psalm\Type\Union), NULL, NULL)
#2 /var/www/lime25/limesurvey/third_party/vimeo/psalm/src/Psalm/Checker/Statements/ExpressionChecker.php(87): Psalm\Checker\Statements\Expression\AssignmentChecker::analyze(Object(Psalm\Checker\StatementsChecker), Object(PhpParser\Node\Expr\Variable), Object(PhpParser\Node\Expr\StaticCall), NULL, Ob in /var/www/lime25/limesurvey/third_party/vimeo/psalm/src/Psalm/Checker/Statements/ExpressionChecker.php on line 761
```

**Comment by muglug** [comment]
@olleharstedt could you run with `--debug-by-line` and then paste the code that causes this message?

**Comment by muglug** [comment]
Also @olleharstedt latest Psalm contains a fix for that particular issue - instead of an exception, it'll emit an `InvalidDocblock` issue.

**Comment by olleharstedt** [comment]
Thank you very much for your help so far!

After adding my bootstrap file to include Yii files etc, I now get this error:

```
<h1>Internal Server Error</h1>
<h2>Call to a member function collectPredefinedConstants() on array</h2>
<p>
    An internal error occurred while the Web server was processing your request.
    Please contact the webmaster to report this problem.
```

Not sure why it would return a HTML page at this point...?

**Comment by muglug** [comment]
Did you figure out what was causing the original exception?

**Comment by olleharstedt** [comment]
Sorry, didn't have time yet to look at it. Will have to write an autoloader or a full bootstrap first.

**Comment by olleharstedt** [comment]
Disabling the Yii error handler, I get this stack trace:
```
string(574) "#0 /var/www/lime25/limesurvey/third_party/vimeo/psalm/src/Psalm/Config.php(324): Psalm\Config::loadFromXML('/var/www/lime25...', '<?xml version="...')
#1 /var/www/lime25/limesurvey/third_party/vimeo/psalm/src/Psalm/Config.php(286): Psalm\Config::loadFromXMLFile('/var/www/lime25...', '/var/www/lime25...')
#2 /var/www/lime25/limesurvey/third_party/vimeo/psalm/src/psalm.php(279): Psalm\Config::getConfigForPath('/var/www/lime25...', '/var/www/lime25...', 'console')
#3 /var/www/lime25/limesurvey/third_party/vimeo/psalm/psalm(2): require_once('/var/www/lime25...')
#4 {main}"
```

**Comment by olleharstedt** [comment]
This line: https://github.com/vimeo/psalm/blob/master/src/Psalm/Config.php#L518

turns `$config` from object to array when running our Yii setup.

**Comment by muglug** [comment]
Hahaha! Ok, you can create a PR, or I can create one in an hour or so. Up to you.

**Comment by olleharstedt** [comment]
@muglug OK, well, if you have time, feel free to do it. :)

I saw some other problems with some of our files, but I will create separate reports for that when they come up again.

**Comment by muglug** [comment]
That's fixed in latest master
