### ISSUE TITLE
Support Windows

### ISSUE THREAD

**Issue by Fleshgrinder** [vimeo/psalm#63]
Splitting this from #60 to keep issues separate. You wrote last:

> That directory should be created here: https://github.com/vimeo/psalm/blob/dde39ed841598b06d8fb7a752c1393590a9b4568/src/Psalm/Checker/FileChecker.php#L563
but maybe it's failing due to nesting?

I added a `var_dump` directly in front of the `mkdir` and it is never printed to screen. My setup of psalm is endlessly simple, I just executed `composer require --dev vimeo/psalm` and executed `./vendor/bin/psalm` in my project. Obviously that means that I used version `0.3.12`. I wanted to use the current `dev-master` but that seems to be broken right now and always ends in:

```
Fatal error: Uncaught UnexpectedValueException: eesh in X:\some-project\vendor\vimeo\psalm\src\Psalm\Config.php:454
Stack trace:
#0 X:\some-project\vendor\vimeo\psalm\src\Psalm\Checker\ProjectChecker.php(334): Psalm\Config->isInProjectDirs('X:\\...')
#1 X:\some-project\vendor\vimeo\psalm\src\Psalm\Checker\ProjectChecker.php(219): Psalm\Checker\ProjectChecker->checkDirWithConfig('X:\\...', Object(Psalm\Config))
#2 X:\some-project\vendor\vimeo\psalm\bin\psalm(156): Psalm\Checker\ProjectChecker->check(false)
#3 {main}
  thrown in X:\some-project\vendor\vimeo\psalm\src\Psalm\Config.php on line 454
```

**Comment by muglug** [comment]
OK - it'll take me some time to get PHP set up on my windows machine, but I'll get on this.

**Comment by muglug** [comment]
I've removed that anti-Windows exception in 98454f864499f2a45cc7d7579558ba1a312de706.

**Comment by Fleshgrinder** [comment]
I can debug anything and everything for you if you point me in the right direction. 😉 I created a breakpoint directly at the beginning of the `Psalm\Checker\FileChecker::getStatementsForFile()` method but it is simply never called at all.

```
php -dzend_extension=php_xdebug.dll vendor/vimeo/psalm/bin/psalm

Warning: file_put_contents(build/psalm/cache/references): failed to open stream: No such file or directory in X:\some-project\vendor\vimeo\psalm\src\Psalm\Checker\FileChecker.php on line 642

Call Stack:
    0.0006     386456   1. {main}() X:\some-project\vendor\vimeo\psalm\bin\psalm:0
    0.0072     398368   2. Psalm\Checker\ProjectChecker->check() X:\some-project\vendor\vimeo\psalm\bin\psalm:156
    0.0155     633672   3. Psalm\IssueBuffer::finish() X:\some-project\vendor\vimeo\psalm\src\Psalm\Checker\ProjectChecker.php:251
    0.0155     633672   4. Psalm\Checker\FileChecker::updateReferenceCache() X:\some-project\vendor\vimeo\psalm\src\Psalm\IssueBuffer.php:201
    0.0155     633984   5. file_put_contents() X:\some-project\vendor\vimeo\psalm\src\Psalm\Checker\FileChecker.php:642

Checks took 0.010139226913452 and used 1.056MB

Warning: touch(): Unable to create file build/psalm/cache/good_run because No such file or directory in X:\some-project\vendor\vimeo\psalm\src\Psalm\Checker\FileChecker.php on line 828

Call Stack:
    0.0006     386456   1. {main}() X:\some-project\vendor\vimeo\psalm\bin\psalm:0
    0.0072     398368   2. Psalm\Checker\ProjectChecker->check() X:\some-project\vendor\vimeo\psalm\bin\psalm:156
    0.0155     633672   3. Psalm\IssueBuffer::finish() X:\some-project\vendor\vimeo\psalm\src\Psalm\Checker\ProjectChecker.php:251
    0.0174     633704   4. Psalm\Checker\FileChecker::goodRun() X:\some-project\vendor\vimeo\psalm\src\Psalm\IssueBuffer.php:218
    0.0174     633760   5. touch() X:\some-project\vendor\vimeo\psalm\src\Psalm\Checker\FileChecker.php:828
```

**Comment by muglug** [comment]
I've just updated Psalm to be a little more helpful – now the cache path is resolved when scanning the config.

I've added a caveat to the wiki – if you specify a cache directory, its parent must already exist.

**Comment by Fleshgrinder** [comment]
Replacing `/` with `DIRECTORY_SEPARATOR` is unnecessary in Windows. Windows has support for them since a very, very, very long time. There are only very programs which have problems with them and non of those are part of Windows.

I will investigate why psalm does not scan any files but this is definitely not a solution for anything.

**Comment by muglug** [comment]
Psalm does string comparison on file names to determine whether a file is in a given directory, and the slashes were throwing Psalm off. On my Windows machine this prevented Psalm from scanning itself (as you noted, no files would be scanned).

**Comment by muglug** [comment]
I just pushed 686891f30f6719fcfbb0d8a41707d66db8bd6fe9 which prevents an infinite loop if a config file isn't present in the expected location.

Running Psalm on Windows on https://github.com/Fleshgrinder/php-assertion gives the following output:

```
C:\git\php-assertion>php vendor\vimeo\psalm\bin\psalm -m
INFO: MissingClosureReturnType - src\Variable.php:26 - Closure does not have a return type
INFO: MissingClosureReturnType - src\Variable.php:39 - Closure does not have a return type
INFO: MissingClosureReturnType - src\Variable.php:99 - Closure does not have a return type
INFO: MissingClosureReturnType - src\Variable.php:163 - Closure does not have a return type
INFO: MissingClosureReturnType - src\Variable.php:233 - Closure does not have a return type
INFO: MissingClosureReturnType - src\Variable.php:282 - Closure does not have a return type
INFO: MissingClosureReturnType - src\Variable.php:412 - Closure does not have a return type
ERROR: TypeDoesNotContainType - src\Variable.php:462 - Cannot resolve types for $var - numeric does not contain string
                        if (is_string($var) && self::gmpCreate($var) instanceof GMP) {

ERROR: UndefinedClass - src\Variable.php:462 - Class or interface GMP does not exist
                        if (is_string($var) && self::gmpCreate($var) instanceof GMP) {

ERROR: TypeDoesNotContainType - src\Variable.php:484 - Cannot resolve types for $var - numeric does not contain string
                        if (is_string($var) && ($gmp = self::gmpCreate($var)) instanceof GMP) {

ERROR: UndefinedClass - src\Variable.php:484 - Class or interface GMP does not exist
                        if (is_string($var) && ($gmp = self::gmpCreate($var)) instanceof GMP) {

ERROR: TypeDoesNotContainType - src\Variable.php:506 - Cannot resolve types for $var - numeric does not contain string
                        if (is_string($var) && ($gmp = self::gmpCreate($var)) instanceof GMP) {

ERROR: UndefinedClass - src\Variable.php:506 - Class or interface GMP does not exist
                        if (is_string($var) && ($gmp = self::gmpCreate($var)) instanceof GMP) {

ERROR: TypeDoesNotContainType - src\Variable.php:532 - Cannot resolve types for $var - numeric does not contain string
                                return is_string($var) && bccomp($var, $var, $scale) === 0;

INFO: MissingClosureReturnType - src\Variable.php:734 - Closure does not have a return type
Checks took 0.31379008293152 and used 16.167MB
```

FWIW the `numeric does not contain string` is a bug I've ticketed here: https://github.com/vimeo/psalm/issues/70

**Comment by Fleshgrinder** [comment]
This obviously changes the game since Windows converts any `/` transparently to `\` and if you use those somewhere you'll need to normalize. 👍 

Works now nicely! 😏

This issue is definitely closed. I'm sure I'll have plenty of other stuff to complain about but not it's time to test some code. 😉
