### ISSUE TITLE
Fresh install in project fails

### ISSUE THREAD

**Issue by uonick** [vimeo/psalm#630]
### Steps:
* `composer require --dev vimeo/psalm`
* `./vendor/bin/psalm --init app/` (laravel 5.6.x project)
* `./vendor/bin/psalm`

### Result
```
vagrant@laravel-vm:/vagrant/www/fitster$ ./vendor/bin/psalm
Scanning files...
PHP Fatal error:  Uncaught UnexpectedValueException: Was expecting an atomic type, got Psalm\Type\Union in /vagrant/www/fitster/vendor/vimeo/psalm/src/Psalm/Type.php:171
Stack trace:
#0 [internal function]: Psalm\Type::Psalm\{closure}(Object(Psalm\Type\ParseTree\UnionTree))
#1 /vagrant/www/fitster/vendor/vimeo/psalm/src/Psalm/Type.php(178): array_map(Object(Closure), Array)
#2 /vagrant/www/fitster/vendor/vimeo/psalm/src/Psalm/Type.php(64): Psalm\Type::getTypeFromTree(Object(Psalm\Type\ParseTree\UnionTree), false)
#3 /vagrant/www/fitster/vendor/vimeo/psalm/src/Psalm/Visitor/DependencyFinderVisitor.php(1164): Psalm\Type::parseString('PDO||Closure|nu...')
#4 /vagrant/www/fitster/vendor/vimeo/psalm/src/Psalm/Visitor/DependencyFinderVisitor.php(1023): Psalm\Visitor\DependencyFinderVisitor->improveParamsFromDocblock(Object(Psalm\Storage\MethodStorage), Array, Object(PhpParser\Node\Stmt\ClassMethod))
#5 /vagrant/www/fitster/vendor/vimeo/psalm/src/Psalm/Visitor/DependencyFinderVisitor.php(324): Psalm\Visitor\DependencyFinderVisitor->r in /vagrant/www/fitster/vendor/vimeo/psalm/src/Psalm/Type.php on line 171

```
<img width="1208" alt="screen shot 2018-03-28 at 21 24 47" src="https://user-images.githubusercontent.com/365029/38042686-78735fd8-32ce-11e8-99d6-de18f7950600.png">

**Comment by weirdan** [comment]
Caused by broken `@return` (?) type annotation: `PDO||Closure|numeric`
Reproducible with psalm 1.0.5, not reproducible with current master.
@uonick you can temporarily update to `dev-master` (`composer require --dev vimeo/psalm:dev-master`) where this crash is already fixed (though you probably want to fix that broken docblock as well)

**Comment by weirdan** [comment]
@muglug here's the test code, you may want to add it to the test suite:
```php
<?php

/**
 * @return PDO||Closure|numeric
 */
function f()
{

}
```

**Comment by uonick** [comment]
@weirdan Thanks, it worked!

**Comment by muglug** [comment]
Thanks @weirdan!
