### ISSUE TITLE
Could not get class storage for `zend\log\logger`

### ISSUE THREAD

**Issue by williamfalconeruk** [vimeo/psalm#6361]
Hi,

i'm currently running psalm against part of our mono repo using a github action. We are seeing the following error: 

```log
░░░░░░░░░░░░░░Uncaught InvalidArgumentException: Could not get class storage for zend\log\logger in /home/runner/.composer/vendor/vimeo/psalm/src/Psalm/Internal/Provider/ClassLikeStorageProvider.php:43
```

Details of the action job here:
https://github.com/ministryofjustice/opg-lpa/pull/605/checks?check_run_id=3412287948#step:6:13

We've also run this locally and are getting the same issue. though there are more details here:
``` log

░░░░E░EE░E░E░░░░░░E░Uncaught Exception: Could not get class storage for zend\log\logger
Stack trace in the forked worker:
#0 ~/source/opg-lpa/service-pdf/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/ClassAnalyzer.php(749): Psalm\Internal\Provider\ClassLikeStorageProvider->get('Zend\\Log\\Logger')
#1 ~/source/opg-lpa/service-pdf/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/ClassAnalyzer.php(395): Psalm\Internal\Analyzer\ClassAnalyzer::addContextProperties(Object(Psalm\Internal\Analyzer\ClassAnalyzer), Object(Psalm\Storage\ClassLikeStorage), Object(Psalm\Context), 'Opg\\Lpa\\Pdf\\Log...', 'Opg\\Lpa\\Logger\\...', Array)
#2 ~/source/opg-lpa/service-pdf/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/FileAnalyzer.php(214): Psalm\Internal\Analyzer\ClassAnalyzer->analyze(Object(Psalm\Context), Object(Psalm\Context))
#3 ~/source/opg-lpa/service-pdf/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Analyzer.php(348): Psalm\Internal\Analyzer\FileAnalyzer->analyze(NULL)
#4 ~/source/opg-lpa/service-pdf/vendor/vimeo/psalm/src/Psalm/Internal/Fork/Pool.php(194): Psalm\Internal\Codebase\Analyzer->Psalm\Internal\Codebase\{closure}(3, '/Users/williamf...')
#5 ~/source/opg-lpa/service-pdf/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Analyzer.php(414): Psalm\Internal\Fork\Pool->__construct(Array, Object(Closure), Object(Closure), Object(Closure), Object(Closure))
#6 ~/source/opg-lpa/service-pdf/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Analyzer.php(277): Psalm\Internal\Codebase\Analyzer->doAnalysis(Object(Psalm\Internal\Analyzer\ProjectAnalyzer), 7)
#7 ~/source/opg-lpa/service-pdf/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/ProjectAnalyzer.php(640): Psalm\Internal\Codebase\Analyzer->analyzeFiles(Object(Psalm\Internal\Analyzer\ProjectAnalyzer), 7, false, true)
#8 ~/source/opg-lpa/service-pdf/vendor/vimeo/psalm/src/Psalm/Internal/Cli/Psalm.php(359): Psalm\Internal\Analyzer\ProjectAnalyzer->check('/Users/williamf...', true)
#9 ~/source/opg-lpa/service-pdf/vendor/vimeo/psalm/psalm(4): Psalm\Internal\Cli\Psalm::run(Array)
#10 {main} in ~/source/opg-lpa/service-pdf/vendor/vimeo/psalm/src/Psalm/Internal/Fork/Pool.php:366
Stack trace:
#0 ~/source/opg-lpa/service-pdf/vendor/vimeo/psalm/src/Psalm/Internal/Fork/Pool.php(400): Psalm\Internal\Fork\Pool->readResultsFromChildren()
#1 ~/source/opg-lpa/service-pdf/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Analyzer.php(488): Psalm\Internal\Fork\Pool->wait()
#2 ~/source/opg-lpa/service-pdf/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Analyzer.php(277): Psalm\Internal\Codebase\Analyzer->doAnalysis(Object(Psalm\Internal\Analyzer\ProjectAnalyzer), 7)
#3 ~/source/opg-lpa/service-pdf/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/ProjectAnalyzer.php(640): Psalm\Internal\Codebase\Analyzer->analyzeFiles(Object(Psalm\Internal\Analyzer\ProjectAnalyzer), 7, false, true)
#4 ~/source/opg-lpa/service-pdf/vendor/vimeo/psalm/src/Psalm/Internal/Cli/Psalm.php(359): Psalm\Internal\Analyzer\ProjectAnalyzer->check('/Users/williamf...', true)
#5 ~/source/opg-lpa/service-pdf/vendor/vimeo/psalm/psalm(4): Psalm\Internal\Cli\Psalm::run(Array)
#6 {main}
(Psalm 4.9.3@4c262932602b9bbab5020863d1eb22d49de0dbf4 crashed due to an uncaught Throwable)

```
Any advice would be appreciated!

**Comment by williamfalconeruk** [comment]
heres  the tail of the `--debug-by-line`:
```
~/source/opg-lpa/service-pdf/src/Opg/Lpa/Pdf/AbstractIndividualPdf.php:363
Getting ~/source/opg-lpa/service-pdf/src/Opg/Lpa/Pdf/Logger/Logger.php
Analyzing ~/source/opg-lpa/service-pdf/src/Opg/Lpa/Pdf/Logger/Logger.php
~/source/opg-lpa/service-pdf/src/Opg/Lpa/Pdf/AbstractIndividualPdf.php:366
~/source/opg-lpa/service-pdf/src/Opg/Lpa/Pdf/AbstractIndividualPdf.php:368
Uncaught Exception: Could not get class storage for zend\log\logger
Stack trace in the forked worker:
...
```

**Comment by williamfalconeruk** [comment]
result of psalm.dev output:
```
Psalm output (using commit 9222b24): 

ERROR: UndefinedClass - 14:22 - Class, interface or enum named Zend\Log\Logger does not exist
```

**Comment by williamfalconeruk** [comment]
see https://psalm.dev/r/3d41137241

**Comment by weirdan** [comment]
I don't see zend logger referenced in composer.json. Where it comes from?

**Comment by williamfalconeruk** [comment]
> I don't see zend logger referenced in composer.json. Where it comes from?

it comes originally from this package: https://docs.zendframework.com/zend-log/ by the looks of it. we tried to add that using
``` bash
composer require zendframework/zend-log
```
and appears to still fail.

**Comment by williamfalconeruk** [comment]
Good news on this - we've migrated this file to use `Laminas\Log\Logger` instead and seems to have solved the issue. Happy to close this for now.
