### ISSUE TITLE
Crash due to uncaught Throwable

### ISSUE THREAD

**Issue by tvdijen** [vimeo/psalm#6373]
Psalm appears to be choking on a file in one of my projects.. Using `--debug` I was able to pinpoint the file and get some more details:

```
Analyzing /apps/development/simplesamlphp/modules/saml/lib/Auth/Process/SQLPersistentNameID.php
Uncaught Psalm\Exception\TypeParseTreeException: Unrecognized type non-empty-mixed in /apps/development/simplesamlphp/vendor/vimeo/psalm/src/Psalm/Type/Atomic.php:289
Stack trace:
#0 /apps/development/simplesamlphp/vendor/vimeo/psalm/src/Psalm/Internal/Type/TypeParser.php(87): Psalm\Type\Atomic::create()
#1 /apps/development/simplesamlphp/vendor/vimeo/psalm/src/Psalm/Type.php(75): Psalm\Internal\Type\TypeParser::parseTokens()
#2 /apps/development/simplesamlphp/vendor/vimeo/psalm/src/Psalm/Internal/Type/NegatedAssertionReconciler.php(158): Psalm\Type::parseString()
#3 /apps/development/simplesamlphp/vendor/vimeo/psalm/src/Psalm/Internal/Type/AssertionReconciler.php(115): Psalm\Internal\Type\NegatedAssertionReconciler::reconcile()
#4 /apps/development/simplesamlphp/vendor/vimeo/psalm/src/Psalm/Type/Reconciler.php(197): Psalm\Internal\Type\AssertionReconciler::reconcile()
#5 /apps/development/simplesamlphp/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/Statements/Expression/BinaryOp/AndAnalyzer.php(142): Psalm\Type\Reconciler::reconcileKeyedTypes()
#6 /apps/development/simplesamlphp/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/Statements/Expression/BinaryOpAnalyzer.php(44): Psalm\Internal\Analyzer\Statements\Expression\BinaryOp\AndAnalyzer::analyze()
#7 /apps/development/simplesamlphp/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/Statements/ExpressionAnalyzer.php(229): Psalm\Internal\Analyzer\Statements\Expression\BinaryOpAnalyzer::analyze()
#8 /apps/development/simplesamlphp/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/Statements/ExpressionAnalyzer.php(41): Psalm\Internal\Analyzer\Statements\ExpressionAnalyzer::handleExpression()
#9 /apps/development/simplesamlphp/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/Statements/Block/IfConditionalAnalyzer.php(166): Psalm\Internal\Analyzer\Statements\ExpressionAnalyzer::analyze()
#10 /apps/development/simplesamlphp/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/Statements/Block/IfElseAnalyzer.php(98): Psalm\Internal\Analyzer\Statements\Block\IfConditionalAnalyzer::analyze()
#11 /apps/development/simplesamlphp/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/StatementsAnalyzer.php(491): Psalm\Internal\Analyzer\Statements\Block\IfElseAnalyzer::analyze()
#12 /apps/development/simplesamlphp/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/StatementsAnalyzer.php(185): Psalm\Internal\Analyzer\StatementsAnalyzer::analyzeStatement()
#13 /apps/development/simplesamlphp/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/FunctionLikeAnalyzer.php(433): Psalm\Internal\Analyzer\StatementsAnalyzer->analyze()
#14 /apps/development/simplesamlphp/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/ClassAnalyzer.php(1782): Psalm\Internal\Analyzer\FunctionLikeAnalyzer->analyze()
#15 /apps/development/simplesamlphp/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/ClassAnalyzer.php(404): Psalm\Internal\Analyzer\ClassAnalyzer->analyzeClassMethod()
#16 /apps/development/simplesamlphp/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/FileAnalyzer.php(214): Psalm\Internal\Analyzer\ClassAnalyzer->analyze()
#17 /apps/development/simplesamlphp/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Analyzer.php(348): Psalm\Internal\Analyzer\FileAnalyzer->analyze()
#18 /apps/development/simplesamlphp/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Analyzer.php(609): Psalm\Internal\Codebase\Analyzer->Psalm\Internal\Codebase\{closure}()
#19 /apps/development/simplesamlphp/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Analyzer.php(277): Psalm\Internal\Codebase\Analyzer->doAnalysis()
#20 /apps/development/simplesamlphp/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/ProjectAnalyzer.php(640): Psalm\Internal\Codebase\Analyzer->analyzeFiles()
#21 /apps/development/simplesamlphp/vendor/vimeo/psalm/src/Psalm/Internal/Cli/Psalm.php(359): Psalm\Internal\Analyzer\ProjectAnalyzer->check()
#22 /apps/development/simplesamlphp/vendor/vimeo/psalm/psalm(4): Psalm\Internal\Cli\Psalm::run()
#23 {main}
(Psalm 4.9.3@4c262932602b9bbab5020863d1eb22d49de0dbf4 crashed due to an uncaught Throwable)
```

The file it's choking on is this one:  https://github.com/simplesamlphp/simplesamlphp/blob/master/modules/saml/lib/Auth/Process/SQLPersistentNameID.php

**Comment by orklah** [comment]
This has been fixed here https://github.com/vimeo/psalm/commit/285fa13d3a90053a9243d176365d08f6ad5f5a4f but not yet released

**Comment by tvdijen** [comment]
Oh, great! And sorry for opening this issue.. I couldn't find anything in the open issues over the last few weeks!

**Comment by orklah** [comment]
no problem, I intended to close the issue when the next release came but it doesn't matter :p
