### ISSUE TITLE
Fatal error: Uncaught InvalidArgumentException: Union::$types cannot be empty after get value for $length in src/Psalm/Checker/TypeChecker.php:476

### ISSUE THREAD

**Issue by paragonie-scott** [vimeo/psalm#64]
Steps to reproduce (PHP 7.1):

```bash
git clone https://github.com/paragonie/sodium_compat.git
cd sodium_compat
composer require --dev "vimeo/psalm:dev-master"
vendor/bin/psalm
```

Stack trace:

```
scott@airship-dev:/mnt/share/sodium_compat$ vendor/bin/psalm
PHP Fatal error:  Uncaught InvalidArgumentException: Union::$types cannot be empty after get value for $length in /mnt/share/sodium_compat/vendor/vimeo/psalm/src/Psalm/Checker/TypeChecker.php:476
Stack trace:
#0 /mnt/share/sodium_compat/vendor/vimeo/psalm/src/Psalm/Checker/Statements/Block/IfChecker.php(106): Psalm\Checker\TypeChecker::reconcileKeyedTypes(Array, Array, Array, Object(Psalm\Checker\FileChecker), Object(Psalm\CodeLocation), Array)
#1 /mnt/share/sodium_compat/vendor/vimeo/psalm/src/Psalm/Checker/StatementsChecker.php(115): Psalm\Checker\Statements\Block\IfChecker::analyze(Object(Psalm\Checker\StatementsChecker), Object(PhpParser\Node\Stmt\If_), Object(Psalm\Context), NULL)
#2 /mnt/share/sodium_compat/vendor/vimeo/psalm/src/Psalm/Checker/Statements/Block/IfChecker.php(268): Psalm\Checker\StatementsChecker->analyze(Array, Object(Psalm\Context), NULL)
#3 /mnt/share/sodium_compat/vendor/vimeo/psalm/src/Psalm/Checker/Statements/Block/IfChecker.php(156): Psalm\Checker\Statements\Block\IfChecker::analyzeIfBlock(Object(Ps in /mnt/share/sodium_compat/vendor/vimeo/psalm/src/Psalm/Checker/TypeChecker.php on line 476

Fatal error: Uncaught InvalidArgumentException: Union::$types cannot be empty after get value for $length in /mnt/share/sodium_compat/vendor/vimeo/psalm/src/Psalm/Checker/TypeChecker.php:476
Stack trace:
#0 /mnt/share/sodium_compat/vendor/vimeo/psalm/src/Psalm/Checker/Statements/Block/IfChecker.php(106): Psalm\Checker\TypeChecker::reconcileKeyedTypes(Array, Array, Array, Object(Psalm\Checker\FileChecker), Object(Psalm\CodeLocation), Array)
#1 /mnt/share/sodium_compat/vendor/vimeo/psalm/src/Psalm/Checker/StatementsChecker.php(115): Psalm\Checker\Statements\Block\IfChecker::analyze(Object(Psalm\Checker\StatementsChecker), Object(PhpParser\Node\Stmt\If_), Object(Psalm\Context), NULL)
#2 /mnt/share/sodium_compat/vendor/vimeo/psalm/src/Psalm/Checker/Statements/Block/IfChecker.php(268): Psalm\Checker\StatementsChecker->analyze(Array, Object(Psalm\Context), NULL)
#3 /mnt/share/sodium_compat/vendor/vimeo/psalm/src/Psalm/Checker/Statements/Block/IfChecker.php(156): Psalm\Checker\Statements\Block\IfChecker::analyzeIfBlock(Object(Ps in /mnt/share/sodium_compat/vendor/vimeo/psalm/src/Psalm/Checker/TypeChecker.php on line 476
```

**Comment by muglug** [comment]
Right yes, it crashes on
```php
<?php
/**
 * @param int $length
 */
function foo($length) {
  if (!is_int($length)) {
    if (is_numeric($length)) {
    }
  }
}
```
Inside the second `if`, `$length` should be typed to `mixed`. Will fix momentarily.

**Comment by paragonie-scott** [comment]
Excellent response!  👍
