### ISSUE TITLE
Unable to get past uncaught InvalidArgumentException

### ISSUE THREAD

**Issue by yacine-truefacet** [vimeo/psalm#647]
Hello there,

I've set up PSALM to analyze an application powered by  Magento 1.8. Initial set up was smooth but I can't seem to get past the `Analyzing files...` portion. The script keeps dying from uncaught  `InvalidArgumentException` messages, which is somewhat unpredictably caused by different classes. Sometimes it will be from one class, sometimes another. I've also been unsuccessful in my attempts to suppress this.

Here is the error:
```text
PHP Notice:  Undefined offset: 1 in /private/var/www/truefacets/vendor/vimeo/psalm/src/Psalm/Codebase/Methods.php on line 451

Notice: Undefined offset: 1 in /private/var/www/truefacets/vendor/vimeo/psalm/src/Psalm/Codebase/Methods.php on line 451
PHP Fatal error:  Uncaught InvalidArgumentException: Could not get class storage for  in /private/var/www/truefacets/vendor/vimeo/psalm/src/Psalm/Provider/ClassLikeStorageProvider.php:35
Stack trace:
#0 /private/var/www/truefacets/vendor/vimeo/psalm/src/Psalm/Codebase/Methods.php(453): Psalm\Provider\ClassLikeStorageProvider->get('')
#1 /private/var/www/truefacets/vendor/vimeo/psalm/src/Psalm/Checker/FunctionLikeChecker.php(166): Psalm\Codebase\Methods->getStorage('')
#2 /private/var/www/truefacets/vendor/vimeo/psalm/src/Psalm/Checker/ClassChecker.php(810): Psalm\Checker\FunctionLikeChecker->analyze(Object(Psalm\Context), Object(Psalm\Context))
#3 /private/var/www/truefacets/vendor/vimeo/psalm/src/Psalm/Checker/ClassChecker.php(392): Psalm\Checker\ClassChecker->analyzeClassMethod(Object(PhpParser\Node\Stmt\ClassMethod), Object(Psalm\Storage\ClassLikeStorage), Object(Psalm\Checker\ClassChecker), Object(Psalm\Context), Object(Psalm\Context))
#4 /private/var/www/truefacets/vendor/vimeo/psalm/src/Psalm/Checker/FileChecker.php(127) in /private/var/www/truefacets/vendor/vimeo/psalm/src/Psalm/Provider/ClassLikeStorageProvider.php on line 35

Fatal error: Uncaught InvalidArgumentException: Could not get class storage for  in /private/var/www/truefacets/vendor/vimeo/psalm/src/Psalm/Provider/ClassLikeStorageProvider.php:35
Stack trace:
#0 /private/var/www/truefacets/vendor/vimeo/psalm/src/Psalm/Codebase/Methods.php(453): Psalm\Provider\ClassLikeStorageProvider->get('')
#1 /private/var/www/truefacets/vendor/vimeo/psalm/src/Psalm/Checker/FunctionLikeChecker.php(166): Psalm\Codebase\Methods->getStorage('')
#2 /private/var/www/truefacets/vendor/vimeo/psalm/src/Psalm/Checker/ClassChecker.php(810): Psalm\Checker\FunctionLikeChecker->analyze(Object(Psalm\Context), Object(Psalm\Context))
#3 /private/var/www/truefacets/vendor/vimeo/psalm/src/Psalm/Checker/ClassChecker.php(392): Psalm\Checker\ClassChecker->analyzeClassMethod(Object(PhpParser\Node\Stmt\ClassMethod), Object(Psalm\Storage\ClassLikeStorage), Object(Psalm\Checker\ClassChecker), Object(Psalm\Context), Object(Psalm\Context))
#4 /private/var/www/truefacets/vendor/vimeo/psalm/src/Psalm/Checker/FileChecker.php(127) in /private/var/www/truefacets/vendor/vimeo/psalm/src/Psalm/Provider/ClassLikeStorageProvider.php on line 35
```

It would appear that some methods (with no discernible pattern as far as I can tell) are not "found" by the `Methods->getDeclaringMethodId()` method when called upon by the `FunctionLikeChecker->analyze()` method. This causes the call to `->getStorage()` to throw the above exception since it is passed a `null` value.

This is the simplest method in our codebase which causes the above exception to be thrown:
```php
    /**
     * Retrieve Order Identifier
     * @psalm-suppress InvalidArgumentException
     * @param object $order
     * @return bool
     */
    public function canPaymentSent($order):bool
    {
        return ($order->getStatus() == 'complete');
    }
```

I'm at a loss as to what the best course of action is at this point. I apologize if this is documented somewhere but I was unable to find anything, nor was I able to find this particular issue reported on here even though there are issues with similar error messages. I would really appreciate some direction.

Thanks in advance!

**Comment by muglug** [comment]
Hey! So for debugging, I recommend adding the `--debug-by-line --no-cache` options, which will give you a very precise callsites for where this exception is raised, and prevent any sort of caching that could lead to different results from one run to the next. Does doing that provide greater insight?

Oh, and `@psalm-suppress InvalidArgumentException` won't stop Psalm throwing an exception – `@psalm-suppress is only about stopping Psalm emitting issues (e.g. `InvalidArgument`).

**Comment by muglug** [comment]
Also, if you're located somewhat near the Vimeo offices in Chelsea, I can come and figure out what's up later today, or before 10am tomorrow. I rarely see exceptions nowadays, and it'd be great to figure out the code in person.

**Comment by yacine-truefacet** [comment]
We are! Just south of Times Square on 39th and 7th. I need to check with my boss to see if he's OK with you visiting!

Thanks for the quick response! I had to step out of the office for a few hours but I'm back and I ran Psalm with the flags you suggested. This was the relevant output:

```
Getting /private/var/www/truefacets/app/code/core/Mage/Catalog/Block/Product/New.php
Analyzing /private/var/www/truefacets/app/code/core/Mage/Catalog/Block/Product/New.php
Parsing /private/var/www/truefacets/app/code/core/Mage/Catalog/Block/Product/New.php
/private/var/www/truefacets/app/code/core/Mage/Catalog/Block/Product/New.php:53
/private/var/www/truefacets/app/code/core/Mage/Catalog/Block/Product/New.php:55
/private/var/www/truefacets/app/code/core/Mage/Catalog/Block/Product/New.php:61
/private/var/www/truefacets/app/code/core/Mage/Catalog/Block/Product/New.php:62
/private/var/www/truefacets/app/code/core/Mage/Catalog/Block/Product/New.php:72
PHP Fatal error:  Uncaught UnexpectedValueException: $storage should not be null for Mage_Catalog_Block_Product_New::getcachekeyinfo in /private/var/www/truefacets/vendor/vimeo/psalm/src/Psalm/Codebase/Methods.php:463
Stack trace:
#0 /private/var/www/truefacets/vendor/vimeo/psalm/src/Psalm/Checker/ClassChecker.php(819): Psalm\Codebase\Methods->getStorage('Mage_Catalog_Bl...')
#1 /private/var/www/truefacets/vendor/vimeo/psalm/src/Psalm/Checker/ClassChecker.php(392): Psalm\Checker\ClassChecker->analyzeClassMethod(Object(PhpParser\Node\Stmt\ClassMethod), Object(Psalm\Storage\ClassLikeStorage), Object(Psalm\Checker\ClassChecker), Object(Psalm\Context), Object(Psalm\Context))
#2 /private/var/www/truefacets/vendor/vimeo/psalm/src/Psalm/Checker/FileChecker.php(127): Psalm\Checker\ClassChecker->analyze(Object(Psalm\Context), Object(Psalm\Context))
#3 /private/var/www/truefacets/vendor/vimeo/psalm/src/Psalm/Codebase/Analyzer.php(138): Psalm\Checker\FileChecker->analyze(NULL)
#4 /private/var/www/truefacets/vendor/vimeo/psalm/src/Psalm/C in /private/var/www/truefacets/vendor/vimeo/psalm/src/Psalm/Codebase/Methods.php on line 463

Fatal error: Uncaught UnexpectedValueException: $storage should not be null for Mage_Catalog_Block_Product_New::getcachekeyinfo in /private/var/www/truefacets/vendor/vimeo/psalm/src/Psalm/Codebase/Methods.php:463
Stack trace:
#0 /private/var/www/truefacets/vendor/vimeo/psalm/src/Psalm/Checker/ClassChecker.php(819): Psalm\Codebase\Methods->getStorage('Mage_Catalog_Bl...')
#1 /private/var/www/truefacets/vendor/vimeo/psalm/src/Psalm/Checker/ClassChecker.php(392): Psalm\Checker\ClassChecker->analyzeClassMethod(Object(PhpParser\Node\Stmt\ClassMethod), Object(Psalm\Storage\ClassLikeStorage), Object(Psalm\Checker\ClassChecker), Object(Psalm\Context), Object(Psalm\Context))
#2 /private/var/www/truefacets/vendor/vimeo/psalm/src/Psalm/Checker/FileChecker.php(127): Psalm\Checker\ClassChecker->analyze(Object(Psalm\Context), Object(Psalm\Context))
#3 /private/var/www/truefacets/vendor/vimeo/psalm/src/Psalm/Codebase/Analyzer.php(138): Psalm\Checker\FileChecker->analyze(NULL)
#4 /private/var/www/truefacets/vendor/vimeo/psalm/src/Psalm/C in /private/var/www/truefacets/vendor/vimeo/psalm/src/Psalm/Codebase/Methods.php on line 463
```

The following link is from a different repo but it's the same file: https://github.com/gemgento/magento/blob/master/public/app/code/core/Mage/Catalog/Block/Product/New.php

**Comment by yacine-truefacet** [comment]
Got the OK from my boss for you to stop by 👍 any time today up till about 8 pm or tomorrow at 9 am would work! Let me know if those hours are not convenient.

However, I'm actually not sure what the best way to relay our contact information is 😬

**Comment by yacine-truefacet** [comment]
One more thing which may be relevant: I am running PHP `7.0.27`.

**Comment by muglug** [comment]
Ah, I'm pretty sure it's because there are duplicate classes with the same name – at least, that's where I saw a similar bug

```
PHP Fatal error:  Uncaught UnexpectedValueException: $storage should not be null for Zend_Date::mktime
```

Because that library has two different `Zend_Date` classes

**Comment by yacine-truefacet** [comment]
Right, that makes a lot of sense. It's just how Magento [was put together](http://devdocs.magento.com/guides/m1x/magefordev/mage-for-dev-1.html#2).

**Comment by muglug** [comment]
I've added https://github.com/vimeo/psalm/issues/648 to deal with duplicate classes - do you have more than one definition of `Mage_Catalog_Block_Product_New` in your codebase?

On second thoughts I won't stop by, but I'll continue to debug remotely

**Comment by yacine-truefacet** [comment]
Yes, we do. The paths are:
- `app/code/core/Mage/Catalog/Block/Product/New.php`
- `app/code/local/Mage/Catalog/Block/Product/New.php`

I fear that this may be quite tricky to deal with just because of the way the project was architected. But please let me know if you make any progress and if I can help in any way!

**Comment by yacine-truefacet** [comment]
That has been my only recourse so far 😄 

In the meantime, I'm running Psalm on our API codebase which is powered by Laravel. That one ran without problems so I'm looking into the results now. I'll get back to the Magento application later on.

Thanks again for all your help! I really appreciate your efforts and responsiveness.

**Comment by muglug** [comment]
This should not be allowed to happen given https://github.com/vimeo/psalm/issues/648 - closing unless you find other problems

**Comment by yacine-truefacet** [comment]
Hi @muglug,

I fetched and merged the latest master commit and ran it against our Magento application. 

Unfortunately, I still get an exception on one of our [Magento extensions](https://www.j2t-design.net/j2t-points-rewards.html):
```
Parsing /private/var/www/truefacets/lib/Varien/Object.php
Getting /private/var/www/truefacets/app/code/community/Rewardpoints/Model/Quote.php
Analyzing /private/var/www/truefacets/app/code/community/Rewardpoints/Model/Quote.php
Parsing /private/var/www/truefacets/app/code/community/Rewardpoints/Model/Quote.php
PHP Fatal error:  Uncaught InvalidArgumentException: Could not get class storage for Rewardpoints_Model_Quote in /private/var/www/truefacets/vendor/vimeo/psalm/src/Psalm/Provider/ClassLikeStorageProvider.php:35
Stack trace:
#0 /private/var/www/truefacets/vendor/vimeo/psalm/src/Psalm/Checker/ClassLikeChecker.php(106): Psalm\Provider\ClassLikeStorageProvider->get('Rewardpoints_Mo...')
#1 /private/var/www/truefacets/vendor/vimeo/psalm/src/Psalm/Checker/ClassChecker.php(39): Psalm\Checker\ClassLikeChecker->__construct(Object(PhpParser\Node\Stmt\Class_), Object(Psalm\Checker\FileChecker), 'Rewardpoints_Mo...')
#2 /private/var/www/truefacets/vendor/vimeo/psalm/src/Psalm/Checker/FileChecker.php(186): Psalm\Checker\ClassChecker->__construct(Object(PhpParser\Node\Stmt\Class_), Object(Psalm\Checker\FileChecker), 'Rewardpoints_Mo...')
#3 /private/var/www/truefacets/vendor/vimeo/psalm/src/Psalm/Checker/FileChecker.php(146): Psalm\Checker\FileChecker->populateClassLikeCheckers(Object(PhpParser\Node\Stmt\Class_))
#4 /private/var/www/truefac in /private/var/www/truefacets/vendor/vimeo/psalm/src/Psalm/Provider/ClassLikeStorageProvider.php on line 35

Fatal error: Uncaught InvalidArgumentException: Could not get class storage for Rewardpoints_Model_Quote in /private/var/www/truefacets/vendor/vimeo/psalm/src/Psalm/Provider/ClassLikeStorageProvider.php:35
Stack trace:
#0 /private/var/www/truefacets/vendor/vimeo/psalm/src/Psalm/Checker/ClassLikeChecker.php(106): Psalm\Provider\ClassLikeStorageProvider->get('Rewardpoints_Mo...')
#1 /private/var/www/truefacets/vendor/vimeo/psalm/src/Psalm/Checker/ClassChecker.php(39): Psalm\Checker\ClassLikeChecker->__construct(Object(PhpParser\Node\Stmt\Class_), Object(Psalm\Checker\FileChecker), 'Rewardpoints_Mo...')
#2 /private/var/www/truefacets/vendor/vimeo/psalm/src/Psalm/Checker/FileChecker.php(186): Psalm\Checker\ClassChecker->__construct(Object(PhpParser\Node\Stmt\Class_), Object(Psalm\Checker\FileChecker), 'Rewardpoints_Mo...')
#3 /private/var/www/truefacets/vendor/vimeo/psalm/src/Psalm/Checker/FileChecker.php(146): Psalm\Checker\FileChecker->populateClassLikeCheckers(Object(PhpParser\Node\Stmt\Class_))
#4 /private/var/www/truefac in /private/var/www/truefacets/vendor/vimeo/psalm/src/Psalm/Provider/ClassLikeStorageProvider.php on line 35
```
I should note that while there are other `Quote.php` files in the application, it is the only version of this particular class, `Rewardpoints_Model_Quote`.

I will just do the ignore files thing for now and see how far that takes me but I thought you might want to be aware.
