### ISSUE TITLE
Crash on 4.10

### ISSUE THREAD

**Issue by blackwolf12333** [vimeo/psalm#6513]
```
Xdebug: [Log Files] File '/var/files/xdebug/remotelog.log' could not be opened.
Scanning files...
Uncaught Error: Call to undefined method PhpParser\Node\Stmt\Property::isReadonly() in /opt/psalm/vendor/vimeo/psalm/src/Psalm/Internal/PhpVisitor/Reflector/ClassLikeNodeScanner.php:1418
Stack trace:
#0 /opt/psalm/vendor/vimeo/psalm/src/Psalm/Internal/PhpVisitor/Reflector/ClassLikeNodeScanner.php(680): Psalm\Internal\PhpVisitor\Reflector\ClassLikeNodeScanner->visitPropertyDeclaration(Object(PhpParser\Node\Stmt
\Property), Object(Psalm\Config), Object(Psalm\Storage\ClassLikeStorage), 'ComposerAutoloa...')
#1 /opt/psalm/vendor/vimeo/psalm/src/Psalm/Internal/PhpVisitor/ReflectorVisitor.php(183): Psalm\Internal\PhpVisitor\Reflector\ClassLikeNodeScanner->start(Object(PhpParser\Node\Stmt\Class_))
#2 /project/app/include/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(200): Psalm\Internal\PhpVisitor\ReflectorVisitor->enterNode(Object(PhpParser\Node\Stmt\Class_))
#3 /project/app/include/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(91): PhpParser\NodeTraverser->traverseArray(Array)
#4 /opt/psalm/vendor/vimeo/psalm/src/Psalm/Internal/Scanner/FileScanner.php(86): PhpParser\NodeTraverser->traverse(Array)
#5 /opt/psalm/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Scanner.php(578): Psalm\Internal\Scanner\FileScanner->scan(Object(Psalm\Codebase), Object(Psalm\Storage\FileStorage), false, Object(Psalm\Progress\Defau
ltProgress))
#6 /opt/psalm/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Scanner.php(329): Psalm\Internal\Codebase\Scanner->scanFile('/opt/psalm/vend...', Array, true)
#7 /opt/psalm/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Scanner.php(448): Psalm\Internal\Codebase\Scanner->Psalm\Internal\Codebase\{closure}(1, '/opt/psalm/vend...')
#8 /opt/psalm/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Scanner.php(293): Psalm\Internal\Codebase\Scanner->scanFilePaths(1)
#9 /opt/psalm/vendor/vimeo/psalm/src/Psalm/Config.php(2089): Psalm\Internal\Codebase\Scanner->scanFiles(Object(Psalm\Internal\Codebase\ClassLikes))
#10 /opt/psalm/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/ProjectAnalyzer.php(405): Psalm\Config->visitComposerAutoloadFiles(Object(Psalm\Internal\Analyzer\ProjectAnalyzer), Object(Psalm\Progress\DefaultProgre
ss))
#11 /opt/psalm/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/ProjectAnalyzer.php(586): Psalm\Internal\Analyzer\ProjectAnalyzer->visitAutoloadFiles()
#12 /opt/psalm/vendor/vimeo/psalm/src/Psalm/Internal/Cli/Psalm.php(359): Psalm\Internal\Analyzer\ProjectAnalyzer->check('/project/', true)
#13 /opt/psalm/vendor/vimeo/psalm/psalm(4): Psalm\Internal\Cli\Psalm::run(Array)
#14 {main}
(Psalm dev-master@d32b1be5a33a8ecc6b92a7bb6e4cc997db8c6040 crashed due to an uncaught Throwable)
```

We use the following docker image to to scan our codebase (which I'm afraid I can't share)

```
FROM hyperized/scratch:latest as trigger
# Used to trigger Docker hubs auto build, which it wont do on the official images

FROM php:7.4-cli-alpine as builder

COPY --from=hyperized/prestissimo:latest /usr/bin/composer /usr/bin/composer

WORKDIR /opt/psalm

RUN composer require vimeo/psalm:4.10.0

FROM php:7.4-cli-alpine

LABEL maintainer="Gerben Geijteman <gerben@hyperized.net>"
LABEL description="A PHP7.4 CLI based vimeo/psalm image"

COPY --from=builder /opt/psalm /opt/psalm

RUN apk add --update --no-cache autoconf g++ imagemagick imagemagick-dev libtool make pcre-dev \
    && pecl install imagick \
    && docker-php-ext-enable imagick

RUN apk add --update libzip-dev zlib-dev && docker-php-ext-install exif zip pdo_mysql opcache pcntl

RUN apk add --update libmemcached-dev && pecl install memcached && docker-php-ext-enable memcached

RUN apk del autoconf g++ libtool make pcre-dev 

RUN apk add --update --no-cache icu-libs icu-dev \
    && docker-php-ext-configure intl --enable-intl \
	&& docker-php-ext-install intl


ENTRYPOINT ["/opt/psalm/vendor/bin/psalm"]
CMD ["-h"]
```

And to execute on our codebase we use

`docker run --rm -t -v "/${PWD}":/project -w "//project" our_image_name --config=psalm.xml`

With the following config file:

```
<?xml version="1.0"?>
<psalm errorLevel="2"
       autoloader="app/bootstrap.php"
       allowCoercionFromStringToClassConst="true"
       ignoreInternalFunctionFalseReturn="true" errorBaseline="psalm-baseline.xml">

	<issueHandlers>	
		<MixedArgument>
			<errorLevel type="suppress">
				<directory name="app/" />
			</errorLevel>
		</MixedArgument>
		<MixedMethodCall>
			<errorLevel type="suppress">
				<directory name="app/" />
			</errorLevel>
		</MixedMethodCall>
		<MixedAssignment>
			<errorLevel type="suppress">
				<directory name="app/" />
			</errorLevel>
		</MixedAssignment>
		<MixedArrayAccess>
			<errorLevel type="suppress">
				<directory name="app/" />
			</errorLevel>
		</MixedArrayAccess>
    </issueHandlers>
    <projectFiles>
        <directory name="app/"/>
        <ignoreFiles>
            <directory name="app/bin/"/>
        </ignoreFiles>
    </projectFiles>
</psalm>
```

Let me know if you need more information!

**Comment by blackwolf12333** [comment]
This is the output of the `composer require vimeo/psalm:4.10.0` command in the Dockerfile.

```  - Installing nikic/php-parser (v4.13.0): Downloading (100%)```

**Comment by orklah** [comment]
That seems coherent, but php-parser in version 4.13.0 contains the method:
https://github.com/nikic/PHP-Parser/blob/v4.13.0/lib/PhpParser/Node/Stmt/Property.php#L84

Could you navigate through your vendor dir to retrieve this file? It should be in vendor/nikic/php-parser/lib/PhpParser/Node/Stmt/Property.php

**Comment by blackwolf12333** [comment]
Looks like the method is there in the installed php-parser as well.

```<?php declare(strict_types=1);

namespace PhpParser\Node\Stmt;

use PhpParser\Node;
use PhpParser\Node\ComplexType;
use PhpParser\Node\Identifier;
use PhpParser\Node\Name;

class Property extends Node\Stmt
{
    /** @var int Modifiers */
    public $flags;
    /** @var PropertyProperty[] Properties */
    public $props;
    /** @var null|Identifier|Name|ComplexType Type declaration */
    public $type;
    /** @var Node\AttributeGroup[] PHP attribute groups */
    public $attrGroups;

    /**
     * Constructs a class property list node.
     *
     * @param int                                     $flags      Modifiers
     * @param PropertyProperty[]                      $props      Properties
     * @param array                                   $attributes Additional attributes
     * @param null|string|Identifier|Name|ComplexType $type       Type declaration
     * @param Node\AttributeGroup[]                   $attrGroups PHP attribute groups
     */
    public function __construct(int $flags, array $props, array $attributes = [], $type = null, array $attrGroups = []) {
        $this->attributes = $attributes;
        $this->flags = $flags;
        $this->props = $props;
        $this->type = \is_string($type) ? new Identifier($type) : $type;
        $this->attrGroups = $attrGroups;
    }

    public function getSubNodeNames() : array {
        return ['attrGroups', 'flags', 'type', 'props'];
    }

    /**
     * Whether the property is explicitly or implicitly public.
     *
     * @return bool
     */
    public function isPublic() : bool {
        return ($this->flags & Class_::MODIFIER_PUBLIC) !== 0
            || ($this->flags & Class_::VISIBILITY_MODIFIER_MASK) === 0;
    }

    /**
     * Whether the property is protected.
     *
     * @return bool
     */
    public function isProtected() : bool {
        return (bool) ($this->flags & Class_::MODIFIER_PROTECTED);
    }

    /**
     * Whether the property is private.
     *
     * @return bool
     */
    public function isPrivate() : bool {
        return (bool) ($this->flags & Class_::MODIFIER_PRIVATE);
    }

    /**
     * Whether the property is static.
     *
     * @return bool
     */
    public function isStatic() : bool {
        return (bool) ($this->flags & Class_::MODIFIER_STATIC);
    }

    /**
     * Whether the property is readonly.
     *
     * @return bool
     */
    public function isReadonly() : bool {
        return (bool) ($this->flags & Class_::MODIFIER_READONLY);
    }

    public function getType() : string {
        return 'Stmt_Property';
    }
}
```

**Comment by orklah** [comment]
I'm pretty confused...
Can you try to limit php-parser to 4.12 in your composer.json?

**Comment by blackwolf12333** [comment]
Ah, I think I have some idea why this might be happening. We also have php-parser installed in the project itself (not really sure yet why, I'll investigate...) which might conflict with the version installed in the docker image that we make for psalm.

**Comment by blackwolf12333** [comment]
Yep, that's the issue. I've updated php-parser to 4.13 in our project as well and psalm is now running correctly on version 4.10.

**Comment by orklah** [comment]
I'm not sure how composer manage to push the wrong version of the lib through the autoloader, but at least the issue is resolved :)
