### ISSUE TITLE
Crash due to an uncaught Throwable: Required parameter ... follows optional

### ISSUE THREAD

**Issue by michabbb** [vimeo/psalm#6651]
hi,

the following error is reproducible:

```
Uncaught Exception: PHP Error: Required parameter $REQUEST follows optional parameter $ebene in /app/webtool/include/handler.php:1655
Stack trace in the forked worker:
#0 /app/vendor/composer/ClassLoader.php(480): Psalm\Internal\ErrorHandler::Psalm\Internal\{closure}(8192, 'Required parame...', '/app/...', 1655)
#1 /app/vendor/composer/ClassLoader.php(480): include()
#2 /app/vendor/composer/ClassLoader.php(346): Composer\Autoload\includeFile('/app/...')
#3 /app/webtool/include/getter.php(15): Composer\Autoload\ClassLoader->loadClass('handler')
#4 /app/vendor/composer/ClassLoader.php(480): include('/app/...')
#5 /app/vendor/composer/ClassLoader.php(346): Composer\Autoload\includeFile('/app/...')
#6 [internal function]: Composer\Autoload\ClassLoader->loadClass('getter')
#7 /app/vendor/vimeo/psalm/src/Psalm/Internal/Type/TemplateStandinTypeReplacer.php(490): is_a('getter', 'null', true)
#8 /app/vendor/vimeo/psalm/src/Psalm/Internal/Type/TemplateStandinTypeReplacer.php(291): Psalm\Internal\Type\TemplateStandinTypeReplacer::findMatchingAtomicTypesForTemplate(Object(Psalm\Type\Atomic\TNull), 'null', Object(Psalm\Codebase), NULL, Object(Psalm\Type\Union))
#9 /app/vendor/vimeo/psalm/src/Psalm/Internal/Type/TemplateStandinTypeReplacer.php(72): Psalm\Internal\Type\TemplateStandinTypeReplacer::handleAtomicStandin(Object(Psalm\Type\Atomic\TNull), 'null', Object(Psalm\Internal\Type\TemplateResult), Object(Psalm\Codebase), NULL, Object(Psalm\Type\Union), NULL, NULL, NULL, true, false, NULL, 1, false, false)
#10 /app/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/ClassAnalyzer.php(737): Psalm\Internal\Type\TemplateStandinTypeReplacer::replace(Object(Psalm\Type\Union), Object(Psalm\Internal\Type\TemplateResult), Object(Psalm\Codebase), NULL, Object(Psalm\Type\Union))
#11 /app/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/ClassAnalyzer.php(395): Psalm\Internal\Analyzer\ClassAnalyzer::addContextProperties(Object(Psalm\Internal\Analyzer\ClassAnalyzer), Object(Psalm\Storage\ClassLikeStorage), Object(Psalm\Context), 'Mode_ebay_shopp...', 'Mode_ebay', Array)
#12 /app/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/FileAnalyzer.php(214): Psalm\Internal\Analyzer\ClassAnalyzer->analyze(Object(Psalm\Context), Object(Psalm\Context))
#13 /app/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Analyzer.php(348): Psalm\Internal\Analyzer\FileAnalyzer->analyze(NULL)
#14 /app/vendor/vimeo/psalm/src/Psalm/Internal/Fork/Pool.php(194): Psalm\Internal\Codebase\Analyzer->Psalm\Internal\Codebase\{closure}(5, '/app/...')
#15 /app/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Analyzer.php(414): Psalm\Internal\Fork\Pool->__construct(Array, Object(Closure), Object(Closure), Object(Closure), Object(Closure))
#16 /app/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Analyzer.php(277): Psalm\Internal\Codebase\Analyzer->doAnalysis(Object(Psalm\Internal\Analyzer\ProjectAnalyzer), 8)
#17 /app/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/ProjectAnalyzer.php(640): Psalm\Internal\Codebase\Analyzer->analyzeFiles(Object(Psalm\Internal\Analyzer\ProjectAnalyzer), 8, false, true)
#18 /app/vendor/vimeo/psalm/src/Psalm/Internal/Cli/Psalm.php(359): Psalm\Internal\Analyzer\ProjectAnalyzer->check('/app/...', true)
#19 /app/vendor/vimeo/psalm/psalm(4): Psalm\Internal\Cli\Psalm::run(Array)
#20 {main} in /app/vendor/vimeo/psalm/src/Psalm/Internal/Fork/Pool.php:366
Stack trace:
#0 /app/vendor/vimeo/psalm/src/Psalm/Internal/Fork/Pool.php(400): Psalm\Internal\Fork\Pool->readResultsFromChildren()
#1 /app/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Analyzer.php(488): Psalm\Internal\Fork\Pool->wait()
#2 /app/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Analyzer.php(277): Psalm\Internal\Codebase\Analyzer->doAnalysis(Object(Psalm\Internal\Analyzer\ProjectAnalyzer), 8)
#3 /app/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/ProjectAnalyzer.php(640): Psalm\Internal\Codebase\Analyzer->analyzeFiles(Object(Psalm\Internal\Analyzer\ProjectAnalyzer), 8, false, true)
#4 /app/vendor/vimeo/psalm/src/Psalm/Internal/Cli/Psalm.php(359): Psalm\Internal\Analyzer\ProjectAnalyzer->check('/home/xxxx...', true)
#5 /app/vendor/vimeo/psalm/psalm(4): Psalm\Internal\Cli\Psalm::run(Array)
#6 {main}
(Psalm 4.10.0@916b098b008f6de4543892b1e0651c1c3b92cbfa crashed due to an uncaught Throwable)
```

the responsible code:

```php
protected function build_dropdown ($type,$list,$ebene=1,$REQUEST): void {
```

if u put `$REQUEST` as the first parameter, psalm is **NOT** throwing this error.

```
PHP version: 8.0.8
PSALM version: 4.10
```

**Comment by michabbb** [comment]
@weirdan 🙈 okay.. i get it.... code is written in php7 but i use php8 for scanning because it´s faster... and that code is producing an error with php8 because required parameters no longer are allowed after optional... get it... 🤦‍♂️ sorry for the noise..... 😖
