### ISSUE TITLE
Keep getting fatal error.

### ISSUE THREAD

**Issue by ularanigu** [vimeo/psalm#682]
I am using psalm with no complex configuration and i am getting this error.

```sh
$ ./vendor/bin/psalm
Scanning files...
PHP Fatal error:  Uncaught PhpParser\Error: Syntax error, unexpected T_STRING, expecting T_FUNCTION or T_CONST on line 76 in /home/travis/build/ularanigu/cherrystone/vendor/nikic/php-parser/lib/PhpParser/ParserAbstract.php:293
Stack trace:
#0 /home/travis/build/ularanigu/cherrystone/vendor/nikic/php-parser/lib/PhpParser/Parser/Multiple.php(50): PhpParser\ParserAbstract->parse('<?php\ndeclare(s...', Object(PhpParser\ErrorHandler\Collecting))
#1 /home/travis/build/ularanigu/cherrystone/vendor/nikic/php-parser/lib/PhpParser/Parser/Multiple.php(31): PhpParser\Parser\Multiple->tryParse(Object(PhpParser\Parser\Php7), Object(PhpParser\ErrorHandler\Collecting), '<?php\ndeclare(s...')
#2 /home/travis/build/ularanigu/cherrystone/vendor/vimeo/psalm/src/Psalm/Provider/StatementsProvider.php(114): PhpParser\Parser\Multiple->parse('<?php\ndeclare(s...', Object(PhpParser\ErrorHandler\Collecting))
#3 /home/travis/build/ularanigu/cherrystone/vendor/vimeo/psalm/src/Psalm/Provider/StatementsProvider.php(73): Psalm\Provider\StatementsProvider::pa in /home/travis/build/ularanigu/cherrystone/vendor/nikic/php-parser/lib/PhpParser/ParserAbstract.php on line 293
Fatal error: Uncaught PhpParser\Error: Syntax error, unexpected T_STRING, expecting T_FUNCTION or T_CONST on line 76 in /home/travis/build/ularanigu/cherrystone/vendor/nikic/php-parser/lib/PhpParser/ParserAbstract.php:293
Stack trace:
#0 /home/travis/build/ularanigu/cherrystone/vendor/nikic/php-parser/lib/PhpParser/Parser/Multiple.php(50): PhpParser\ParserAbstract->parse('<?php\ndeclare(s...', Object(PhpParser\ErrorHandler\Collecting))
#1 /home/travis/build/ularanigu/cherrystone/vendor/nikic/php-parser/lib/PhpParser/Parser/Multiple.php(31): PhpParser\Parser\Multiple->tryParse(Object(PhpParser\Parser\Php7), Object(PhpParser\ErrorHandler\Collecting), '<?php\ndeclare(s...')
#2 /home/travis/build/ularanigu/cherrystone/vendor/vimeo/psalm/src/Psalm/Provider/StatementsProvider.php(114): PhpParser\Parser\Multiple->parse('<?php\ndeclare(s...', Object(PhpParser\ErrorHandler\Collecting))
#3 /home/travis/build/ularanigu/cherrystone/vendor/vimeo/psalm/src/Psalm/Provider/StatementsProvider.php(73): Psalm\Provider\StatementsProvider::pa in /home/travis/build/ularanigu/cherrystone/vendor/nikic/php-parser/lib/PhpParser/ParserAbstract.php on line 293
```

Any reason what is wrong here.

**Comment by ularanigu** [comment]
Original log can be found here - https://travis-ci.org/ularanigu/cherrystone/jobs/367931172

**Comment by muglug** [comment]
The error's here: https://github.com/ularanigu/cherrystone/blob/55bb6374184cefd9ae8495bf436b7c7c2b6b16de/src/Service/BrowserBasedService.php#L76

You're missing a `function` keyword.

Psalm isn't designed to check files that don't compile (you can check this with `php -l [path-to-file]`).

**Comment by ularanigu** [comment]
Thanks I feel stupid.

**Comment by muglug** [comment]
Please don’t! These sorts of errors are really common when you're coming from a language that doesn't have so many keywords.
