### ISSUE TITLE
Cannot process colon without parent seems to be back 

### ISSUE THREAD

**Issue by reypm** [vimeo/psalm#7295]
I ran a `composer update` today on my project and apparently Psalm is broken since it fails with the following error:
```bash
>>  ../framework
Target PHP version: 8.1 (inferred from composer.json)
Scanning files...
Analyzing files...

Uncaught Exception: Psalm\Exception\TypeParseTreeException Cannot process colon without parent
Emitted in /var/www/framework/vendor/vimeo/psalm/src/Psalm/Internal/Type/ParseTreeCreator.php:490
Stack trace in the forked worker:
#0 /var/www/framework/vendor/vimeo/psalm/src/Psalm/Internal/Type/ParseTreeCreator.php(123): Psalm\Internal\Type\ParseTreeCreator->handleColon()
#1 /var/www/framework/vendor/vimeo/psalm/src/Psalm/Internal/Type/TypeParser.php(135): Psalm\Internal\Type\ParseTreeCreator->create()
#2 /var/www/framework/vendor/vimeo/psalm/src/Psalm/Type.php(82): Psalm\Internal\Type\TypeParser::parseTokens(Array, NULL, Array)
#3 /var/www/framework/vendor/vimeo/psalm/src/Psalm/Internal/Type/SimpleAssertionReconciler.php(1565): Psalm\Type::parseString('T:fn-rector\\net...')
#4 /var/www/framework/vendor/vimeo/psalm/src/Psalm/Internal/Type/SimpleAssertionReconciler.php(115): Psalm\Internal\Type\SimpleAssertionReconciler::reconcileInArray(Object(Psalm\Codebase), Object(Psalm\Type\Union), 'T:fn-rector\\net...', '$object', false, Object(Psalm\CodeLocation), Array, 0)
#5 /var/www/framework/vendor/vimeo/psalm/src/Psalm/Internal/Type/AssertionReconciler.php(150): Psalm\Internal\Type\SimpleAssertionReconciler::reconcile('in-array-T:fn-r...', Object(Psalm\Codebase), Object(Psalm\Type\Union), '$object', false, Object(Psalm\CodeLocation), Array, 0, false, false, true)
#6 /var/www/framework/vendor/vimeo/psalm/src/Psalm/Type/Reconciler.php(217): Psalm\Internal\Type\AssertionReconciler::reconcile('in-array-T:fn-r...', Object(Psalm\Type\Union), '$object', Object(Psalm\Internal\Analyzer\StatementsAnalyzer), true, Array, Object(Psalm\CodeLocation), Array, 0, false)
#7 /var/www/framework/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/Statements/Block/IfElseAnalyzer.php(289): Psalm\Type\Reconciler::reconcileKeyedTypes(Array, Array, Array, Array, Array, Object(Psalm\Internal\Analyzer\StatementsAnalyzer), Array, true, Object(Psalm\CodeLocation))
#8 /var/www/framework/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/StatementsAnalyzer.php(515): Psalm\Internal\Analyzer\Statements\Block\IfElseAnalyzer::analyze(Object(Psalm\Internal\Analyzer\StatementsAnalyzer), Object(PhpParser\Node\Stmt\If_), Object(Psalm\Context))
#9 /var/www/framework/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/StatementsAnalyzer.php(206): Psalm\Internal\Analyzer\StatementsAnalyzer::analyzeStatement(Object(Psalm\Internal\Analyzer\StatementsAnalyzer), Object(PhpParser\Node\Stmt\If_), Object(Psalm\Context), NULL)
#10 /var/www/framework/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/Statements/Block/LoopAnalyzer.php(387): Psalm\Internal\Analyzer\StatementsAnalyzer->analyze(Array, Object(Psalm\Context))
#11 /var/www/framework/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/Statements/Block/ForeachAnalyzer.php(340): Psalm\Internal\Analyzer\Statements\Block\LoopAnalyzer::analyze(Object(Psalm\Internal\Analyzer\StatementsAnalyzer), Array, Array, Array, Object(Psalm\Internal\Scope\LoopScope), Object(Psalm\Context), false, false)
#12 /var/www/framework/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/StatementsAnalyzer.php(527): Psalm\Internal\Analyzer\Statements\Block\ForeachAnalyzer::analyze(Object(Psalm\Internal\Analyzer\StatementsAnalyzer), Object(PhpParser\Node\Stmt\Foreach_), Object(Psalm\Context))
#13 /var/www/framework/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/StatementsAnalyzer.php(206): Psalm\Internal\Analyzer\StatementsAnalyzer::analyzeStatement(Object(Psalm\Internal\Analyzer\StatementsAnalyzer), Object(PhpParser\Node\Stmt\Foreach_), Object(Psalm\Context), Object(Psalm\Context))
#14 /var/www/framework/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/FunctionLikeAnalyzer.php(463): Psalm\Internal\Analyzer\StatementsAnalyzer->analyze(Array, Object(Psalm\Context), Object(Psalm\Context), true)
#15 /var/www/framework/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/ClassAnalyzer.php(1788): Psalm\Internal\Analyzer\FunctionLikeAnalyzer->analyze(Object(Psalm\Context), Object(Psalm\Internal\Provider\NodeDataProvider), Object(Psalm\Context))
#16 /var/www/framework/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/ClassAnalyzer.php(425): Psalm\Internal\Analyzer\ClassAnalyzer->analyzeClassMethod(Object(PhpParser\Node\Stmt\ClassMethod), Object(Psalm\Storage\ClassLikeStorage), Object(Psalm\Internal\Analyzer\ClassAnalyzer), Object(Psalm\Context), Object(Psalm\Context))
#17 /var/www/framework/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/FileAnalyzer.php(229): Psalm\Internal\Analyzer\ClassAnalyzer->analyze(Object(Psalm\Context), Object(Psalm\Context))
#18 /var/www/framework/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Analyzer.php(362): Psalm\Internal\Analyzer\FileAnalyzer->analyze()
#19 /var/www/framework/vendor/vimeo/psalm/src/Psalm/Internal/Fork/Pool.php(211): Psalm\Internal\Codebase\Analyzer->Psalm\Internal\Codebase\{closure}(1874, '/var/www/framew...')
#20 /var/www/framework/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Analyzer.php(428): Psalm\Internal\Fork\Pool->__construct(Object(Psalm\Config), Array, Object(Closure), Object(Closure), Object(Closure), Object(Closure))
#21 /var/www/framework/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Analyzer.php(291): Psalm\Internal\Codebase\Analyzer->doAnalysis(Object(Psalm\Internal\Analyzer\ProjectAnalyzer), 3)
#22 /var/www/framework/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/ProjectAnalyzer.php(1203): Psalm\Internal\Codebase\Analyzer->analyzeFiles(Object(Psalm\Internal\Analyzer\ProjectAnalyzer), 3, false, false)
#23 /var/www/framework/vendor/vimeo/psalm/src/Psalm/Internal/Cli/Psalm.php(375): Psalm\Internal\Analyzer\ProjectAnalyzer->checkPaths(Array)
#24 /var/www/framework/vendor/vimeo/psalm/psalm(7): Psalm\Internal\Cli\Psalm::run(Array)
#25 /var/www/framework/vendor/bin/psalm(97): include('/var/www/framew...')
#26 {main} in /var/www/framework/vendor/vimeo/psalm/src/Psalm/Internal/Fork/Pool.php:402
Stack trace:
#0 /var/www/framework/vendor/vimeo/psalm/src/Psalm/Internal/Fork/Pool.php(436): Psalm\Internal\Fork\Pool->readResultsFromChildren()
#1 /var/www/framework/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Analyzer.php(503): Psalm\Internal\Fork\Pool->wait()
#2 /var/www/framework/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Analyzer.php(291): Psalm\Internal\Codebase\Analyzer->doAnalysis(Object(Psalm\Internal\Analyzer\ProjectAnalyzer), 3)
#3 /var/www/framework/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/ProjectAnalyzer.php(1203): Psalm\Internal\Codebase\Analyzer->analyzeFiles(Object(Psalm\Internal\Analyzer\ProjectAnalyzer), 3, false, false)
#4 /var/www/framework/vendor/vimeo/psalm/src/Psalm/Internal/Cli/Psalm.php(375): Psalm\Internal\Analyzer\ProjectAnalyzer->checkPaths(Array)
#5 /var/www/framework/vendor/vimeo/psalm/psalm(7): Psalm\Internal\Cli\Psalm::run(Array)
#6 /var/www/framework/vendor/bin/psalm(97): include('/var/www/framew...')
#7 {main}
(Psalm 4.17.0@6f4707aa41c9174353a6434bba3fc8840f981d9c crashed due to an uncaught Throwable)
Script find ../* -prune -type d | while IFS= read -r DIR; do echo '>> ' ${DIR}; ./vendor/bin/psalm ${DIR}; done handling the psalm event returned with error code 1
Script @psalm was called via tools
```
This is the `psalm.xml` config file:
```xml
<?xml version="1.0"?>
<psalm xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" errorLevel="7" totallyTyped="true"
       strictBinaryOperands="true" useDocblockPropertyTypes="true"
       xmlns="https://getpsalm.org/schema/config"
       xsi:schemaLocation="https://getpsalm.org/schema/config vendor/vimeo/psalm/config.xsd">
    <projectFiles>
        <directory name=".."/>
        <ignoreFiles>
            <directory name="*vendor"/>
            <directory name="*var"/>
            <directory name="*features/"/>
            <file name="phpinsights.php"/>
            <file name="rector.php"/>
        </ignoreFiles>
    </projectFiles>

    <plugins>
        <pluginClass class="Psalm\SymfonyPsalmPlugin\Plugin">
            <containerXml>var/cache/dev/App_KernelDevDebugContainer.xml</containerXml>
        </pluginClass>
        <pluginClass class="Weirdan\DoctrinePsalmPlugin\Plugin"/>
    </plugins>

    <issueHandlers>
        <MethodSignatureMismatch errorLevel="suppress"/>
        <UndefinedDocblockClass errorLevel="suppress"/>
        <MissingFile errorLevel="suppress"/>
        <UndefinedClass errorLevel="suppress"/>
        <PluginIssue name="RepositoryStringShortcut" errorLevel="suppress" />
    </issueHandlers>
</psalm>
```
This is the log for the `composer update`:
```bash
# composer update
Loading composer repositories with package information
Restricting packages listed in "symfony/symfony" to "5.4.*"
Updating dependencies
Lock file operations: 0 installs, 19 updates, 0 removals
  - Upgrading composer/composer (2.2.2 => 2.2.3)
  - Upgrading composer/semver (3.2.6 => 3.2.7)
  - Upgrading composer/xdebug-handler (2.0.3 => 2.0.4)
  - Upgrading doctrine/mongodb-odm-bundle (4.4.1 => 4.4.2)
  - Upgrading mongodb/mongodb (dev-master e346802 => dev-master c41a46f)
  - Upgrading phpdocumentor/type-resolver (1.5.1 => 1.6.0)
  - Upgrading phpstan/phpstan (dev-master f61e569 => dev-master c3e7a58)
  - Upgrading phpstan/phpstan-php-parser (1.0.0 => 1.1.0)
  - Upgrading psalm/plugin-symfony (v3.1.0 => v3.1.2)
  - Upgrading rector/rector (0.12.9 => 0.12.10)
  - Upgrading sensio/framework-extra-bundle (v6.2.4 => v6.2.5)
  - Upgrading symfony/security-bundle (v5.4.1 => v5.4.2)
  - Upgrading symplify/autowire-array-parameter (10.0.6 => 10.0.8)
  - Upgrading symplify/composer-json-manipulator (10.0.6 => 10.0.8)
  - Upgrading symplify/easy-testing (10.0.6 => 10.0.8)
  - Upgrading symplify/package-builder (10.0.6 => 10.0.8)
  - Upgrading symplify/smart-file-system (10.0.6 => 10.0.8)
  - Upgrading symplify/symplify-kernel (10.0.6 => 10.0.8)
  - Upgrading vimeo/psalm (4.16.1 => 4.17.0)
Writing lock file
Installing dependencies from lock file (including require-dev)
Package operations: 0 installs, 19 updates, 0 removals
  - Downloading composer/xdebug-handler (2.0.4)
  - Downloading composer/semver (3.2.7)
  - Downloading phpdocumentor/type-resolver (1.6.0)
  - Downloading phpstan/phpstan (dev-master c3e7a58)
  - Upgrading mongodb/mongodb (dev-master e346802 => dev-master c41a46f): Extracting archive
  - Upgrading doctrine/mongodb-odm-bundle (4.4.1 => 4.4.2): Extracting archive
  - Upgrading composer/xdebug-handler (2.0.3 => 2.0.4): Extracting archive
  - Upgrading composer/semver (3.2.6 => 3.2.7): Extracting archive
  - Upgrading composer/composer (2.2.2 => 2.2.3): Extracting archive
  - Upgrading phpdocumentor/type-resolver (1.5.1 => 1.6.0): Extracting archive
  - Upgrading phpstan/phpstan (dev-master f61e569 => dev-master c3e7a58): Extracting archive
  - Upgrading phpstan/phpstan-php-parser (1.0.0 => 1.1.0): Extracting archive
  - Upgrading vimeo/psalm (4.16.1 => 4.17.0): Extracting archive
  - Upgrading psalm/plugin-symfony (v3.1.0 => v3.1.2): Extracting archive
  - Upgrading rector/rector (0.12.9 => 0.12.10): Extracting archive
  - Upgrading sensio/framework-extra-bundle (v6.2.4 => v6.2.5): Extracting archive
  - Upgrading symfony/security-bundle (v5.4.1 => v5.4.2): Extracting archive
  - Upgrading symplify/smart-file-system (10.0.6 => 10.0.8): Extracting archive
  - Upgrading symplify/symplify-kernel (10.0.6 => 10.0.8): Extracting archive
  - Upgrading symplify/easy-testing (10.0.6 => 10.0.8): Extracting archive
  - Upgrading symplify/package-builder (10.0.6 => 10.0.8): Extracting archive
  - Upgrading symplify/composer-json-manipulator (10.0.6 => 10.0.8): Extracting archive
  - Upgrading symplify/autowire-array-parameter (10.0.6 => 10.0.8): Extracting archive
Package webmozart/path-util is abandoned, you should avoid using it. Use symfony/filesystem instead.
Generating optimized autoload files
composer/package-versions-deprecated: Generating version class...
composer/package-versions-deprecated: ...done generating version class
118 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
phpstan/extension-installer: Extensions installed
> phpstan/phpstan-deprecation-rules: installed
> phpstan/phpstan-doctrine: installed
> phpstan/phpstan-php-parser: installed
> phpstan/phpstan-strict-rules: installed
> phpstan/phpstan-symfony: installed

What about running composer thanks now?
This will spread some 💖  by sending a ★  to 6 GitHub repositories of your fellow package maintainers.
You can also run composer fund to discover how you can sponsor their work with some 💵


Run composer recipes at any time to see the status of your Symfony recipes.

Executing script cache:clear [OK]
Executing script assets:install public [OK]
```

Related to:
 - https://github.com/vimeo/psalm/issues/6309
 - https://github.com/vimeo/psalm/issues/795

**Comment by weirdan** [comment]
We will need the code that triggers the issue. You may try to identify it with the `--debug-by-line` switch.

**Comment by reypm** [comment]
@weirdan that's my issue the file and/or code isn't displayed as part of the stacktrace so I don't know where the issue is being generated on my end, is there a flag that I can pass to `psalm` so I can get this?

**Comment by weirdan** [comment]
> You may try to identify it with the `--debug-by-line` switch.

**Comment by orklah** [comment]
Note: I suspect this may come from the PR that now assert array shapes. If we were to generate an assertion base on a Keyed array which would contain an empty string as an offset, I believe we wouldn't quote the offset, resulting in a syntax like `array{: string}` who could trigger that kind of error

**Comment by reypm** [comment]
here is the result for running the command with `--debug-by-line`:

```bash
/var/www/framework/vendor/rector/rector/vendor/rector/rector-nette/src/NodeAnalyzer/MethodCallManipulator.php:131
/var/www/framework/vendor/rector/rector/vendor/rector/rector-nette/src/NodeAnalyzer/MethodCallManipulator.php:133
/var/www/framework/vendor/rector/rector/vendor/rector/rector-nette/src/NodeAnalyzer/MethodCallManipulator.php:130
Uncaught Exception: Psalm\Exception\TypeParseTreeException Cannot process colon without parent
Emitted in /var/www/framework/vendor/vimeo/psalm/src/Psalm/Internal/Type/ParseTreeCreator.php:490
Stack trace in the forked worker:
#0 /var/www/framework/vendor/vimeo/psalm/src/Psalm/Internal/Type/ParseTreeCreator.php(123): Psalm\Internal\Type\ParseTreeCreator->handleColon()
#1 /var/www/framework/vendor/vimeo/psalm/src/Psalm/Internal/Type/TypeParser.php(135): Psalm\Internal\Type\ParseTreeCreator->create()
#2 /var/www/framework/vendor/vimeo/psalm/src/Psalm/Type.php(82): Psalm\Internal\Type\TypeParser::parseTokens(Array, NULL, Array)
#3 /var/www/framework/vendor/vimeo/psalm/src/Psalm/Internal/Type/SimpleAssertionReconciler.php(1565): Psalm\Type::parseString('T:fn-rector\\net...')
#4 /var/www/framework/vendor/vimeo/psalm/src/Psalm/Internal/Type/SimpleAssertionReconciler.php(115): Psalm\Internal\Type\SimpleAssertionReconciler::reconcileInArray(Object(Psalm\Codebase), Object(Psalm\Type\Union), 'T:fn-rector\\net...', '$object', false, Object(Psalm\CodeLocation), Array, 0)
#5 /var/www/framework/vendor/vimeo/psalm/src/Psalm/Internal/Type/AssertionReconciler.php(150): Psalm\Internal\Type\SimpleAssertionReconciler::reconcile('in-array-T:fn-r...', Object(Psalm\Codebase), Object(Psalm\Type\Union), '$object', false, Object(Psalm\CodeLocation), Array, 0, false, false, true)
#6 /var/www/framework/vendor/vimeo/psalm/src/Psalm/Type/Reconciler.php(217): Psalm\Internal\Type\AssertionReconciler::reconcile('in-array-T:fn-r...', Object(Psalm\Type\Union), '$object', Object(Psalm\Internal\Analyzer\StatementsAnalyzer), true, Array, Object(Psalm\CodeLocation), Array, 0, false)
#7 /var/www/framework/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/Statements/Block/IfElseAnalyzer.php(289): Psalm\Type\Reconciler::reconcileKeyedTypes(Array, Array, Array, Array, Array, Object(Psalm\Internal\Analyzer\StatementsAnalyzer), Array, true, Object(Psalm\CodeLocation))
#8 /var/www/framework/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/StatementsAnalyzer.php(515): Psalm\Internal\Analyzer\Statements\Block\IfElseAnalyzer::analyze(Object(Psalm\Internal\Analyzer\StatementsAnalyzer), Object(PhpParser\Node\Stmt\If_), Object(Psalm\Context))
#9 /var/www/framework/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/StatementsAnalyzer.php(206): Psalm\Internal\Analyzer\StatementsAnalyzer::analyzeStatement(Object(Psalm\Internal\Analyzer\StatementsAnalyzer), Object(PhpParser\Node\Stmt\If_), Object(Psalm\Context), NULL)
#10 /var/www/framework/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/Statements/Block/LoopAnalyzer.php(387): Psalm\Internal\Analyzer\StatementsAnalyzer->analyze(Array, Object(Psalm\Context))
#11 /var/www/framework/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/Statements/Block/ForeachAnalyzer.php(340): Psalm\Internal\Analyzer\Statements\Block\LoopAnalyzer::analyze(Object(Psalm\Internal\Analyzer\StatementsAnalyzer), Array, Array, Array, Object(Psalm\Internal\Scope\LoopScope), Object(Psalm\Context), false, false)
#12 /var/www/framework/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/StatementsAnalyzer.php(527): Psalm\Internal\Analyzer\Statements\Block\ForeachAnalyzer::analyze(Object(Psalm\Internal\Analyzer\StatementsAnalyzer), Object(PhpParser\Node\Stmt\Foreach_), Object(Psalm\Context))
#13 /var/www/framework/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/StatementsAnalyzer.php(206): Psalm\Internal\Analyzer\StatementsAnalyzer::analyzeStatement(Object(Psalm\Internal\Analyzer\StatementsAnalyzer), Object(PhpParser\Node\Stmt\Foreach_), Object(Psalm\Context), Object(Psalm\Context))
#14 /var/www/framework/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/FunctionLikeAnalyzer.php(463): Psalm\Internal\Analyzer\StatementsAnalyzer->analyze(Array, Object(Psalm\Context), Object(Psalm\Context), true)
#15 /var/www/framework/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/ClassAnalyzer.php(1788): Psalm\Internal\Analyzer\FunctionLikeAnalyzer->analyze(Object(Psalm\Context), Object(Psalm\Internal\Provider\NodeDataProvider), Object(Psalm\Context))
#16 /var/www/framework/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/ClassAnalyzer.php(425): Psalm\Internal\Analyzer\ClassAnalyzer->analyzeClassMethod(Object(PhpParser\Node\Stmt\ClassMethod), Object(Psalm\Storage\ClassLikeStorage), Object(Psalm\Internal\Analyzer\ClassAnalyzer), Object(Psalm\Context), Object(Psalm\Context))
#17 /var/www/framework/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/FileAnalyzer.php(229): Psalm\Internal\Analyzer\ClassAnalyzer->analyze(Object(Psalm\Context), Object(Psalm\Context))
#18 /var/www/framework/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Analyzer.php(362): Psalm\Internal\Analyzer\FileAnalyzer->analyze()
#19 /var/www/framework/vendor/vimeo/psalm/src/Psalm/Internal/Fork/Pool.php(211): Psalm\Internal\Codebase\Analyzer->Psalm\Internal\Codebase\{closure}(722, '/var/www/framew...')
#20 /var/www/framework/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Analyzer.php(428): Psalm\Internal\Fork\Pool->__construct(Object(Psalm\Config), Array, Object(Closure), Object(Closure), Object(Closure), Object(Closure))
#21 /var/www/framework/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Analyzer.php(291): Psalm\Internal\Codebase\Analyzer->doAnalysis(Object(Psalm\Internal\Analyzer\ProjectAnalyzer), 3)
#22 /var/www/framework/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/ProjectAnalyzer.php(1203): Psalm\Internal\Codebase\Analyzer->analyzeFiles(Object(Psalm\Internal\Analyzer\ProjectAnalyzer), 3, false, false)
#23 /var/www/framework/vendor/vimeo/psalm/src/Psalm/Internal/Cli/Psalm.php(375): Psalm\Internal\Analyzer\ProjectAnalyzer->checkPaths(Array)
#24 /var/www/framework/vendor/vimeo/psalm/psalm(7): Psalm\Internal\Cli\Psalm::run(Array)
#25 /var/www/framework/vendor/bin/psalm(97): include('/var/www/framew...')
#26 {main} in /var/www/framework/vendor/vimeo/psalm/src/Psalm/Internal/Fork/Pool.php:402
Stack trace:
#0 /var/www/framework/vendor/vimeo/psalm/src/Psalm/Internal/Fork/Pool.php(436): Psalm\Internal\Fork\Pool->readResultsFromChildren()
#1 /var/www/framework/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Analyzer.php(503): Psalm\Internal\Fork\Pool->wait()
#2 /var/www/framework/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Analyzer.php(291): Psalm\Internal\Codebase\Analyzer->doAnalysis(Object(Psalm\Internal\Analyzer\ProjectAnalyzer), 3)
#3 /var/www/framework/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/ProjectAnalyzer.php(1203): Psalm\Internal\Codebase\Analyzer->analyzeFiles(Object(Psalm\Internal\Analyzer\ProjectAnalyzer), 3, false, false)
#4 /var/www/framework/vendor/vimeo/psalm/src/Psalm/Internal/Cli/Psalm.php(375): Psalm\Internal\Analyzer\ProjectAnalyzer->checkPaths(Array)
#5 /var/www/framework/vendor/vimeo/psalm/psalm(7): Psalm\Internal\Cli\Psalm::run(Array)
#6 /var/www/framework/vendor/bin/psalm(97): include('/var/www/framew...')
#7 {main}
(Psalm 4.17.0@6f4707aa41c9174353a6434bba3fc8840f981d9c crashed due to an uncaught Throwable)
```

**Comment by orklah** [comment]
reproducer: https://psalm.dev/r/07224a2421

**Comment by orklah** [comment]
It can be fixed by adding ` && !$value_type->hasTemplate()` in AssertionFinder line 3559. It will prevent generating assertions like this one that look like `in-array-T:fn-a::uniquateobjects as mixed` that can't be parsed later.

I'll make the PR once I manage to clear my repo of what I'm currently working on
