### ISSUE TITLE
InvalidArgumentException: You must pass at least one type to combineTypes

### ISSUE THREAD

**Issue by sserbin** [vimeo/psalm#736]
Minimal reproducible test case:
```php
<?php
use Doctrine\ORM\EntityRepository;

class Foo
{
    /** @var EntityRepository */
    private $repo;

    private const TYPES = [
        'type1' => 'class1',
        'type2' => 'class2',
    ];

    public function bar(array $data): void
    {
        if (!isset(self::TYPES[$data['type']])) {
            throw new \InvalidArgumentException('Unknown type');
        }

        $class = self::TYPES[$data['type']];

        $ret = $this->repo->find($data['id']);

        if (!$ret || !$ret instanceof $class) {
            throw new \InvalidArgumentException;
        }
    }
}

```

```
Fatal error: Uncaught InvalidArgumentException: You must pass at least one type to combineTypes in /home/serg/.composer/vendor/vimeo/psalm/src/Psalm/Type.php:850
Stack trace:
#0 /home/serg/.composer/vendor/vimeo/psalm/src/Psalm/Type.php(783): Psalm\Type::combineTypes(Array)
#1 /home/serg/.composer/vendor/vimeo/psalm/src/Psalm/Checker/Statements/Expression/BinaryOpChecker.php(225): Psalm\Type::combineUnionTypes(Object(Psalm\Type\Union), Object(Psalm\Type\Union))
#2 /home/serg/.composer/vendor/vimeo/psalm/src/Psalm/Checker/Statements/ExpressionChecker.php(188): Psalm\Checker\Statements\Expression\BinaryOpChecker::analyze(Object(Psalm\Checker\StatementsChecker), Object(PhpParser\Node\Expr\BinaryOp\BooleanOr), Object(Psalm\Context))
#3 /home/serg/.composer/vendor/vimeo/psalm/src/Psalm/Checker/Statements/Block/IfChecker.php(75): Psalm\Checker\Statements\ExpressionChecker::analyze(Object(Psalm\Checker\StatementsChecker), Object(PhpParser\Node\Expr\BinaryOp\BooleanOr), Object(Psalm\Context))
#4 /home/serg/.composer/vendor/vimeo/ in /home/serg/.composer/vendor/vimeo/psalm/src/Psalm/Type.php on line 850
```

Aforementioned code was working properly with psalm master from yesterday/day before yesterday version.

**Comment by muglug** [comment]
Thanks, sorry for the inconvenience!
