### ISSUE TITLE
Regression in #7321

### ISSUE THREAD

**Issue by tm1000** [vimeo/psalm#7378]
The code added was `$node->isFirstClassCallable()`

However `$node` is typed as `PhpParser\Node\Expr\FuncCall`. Looking at `PhpParser\Node\Expr\FuncCall` you can see there is no method like that: https://github.com/nikic/PHP-Parser/blob/master/lib/PhpParser/Node/Expr/FuncCall.php

This causes a fatal error: 
```
Uncaught Error: Call to undefined method PhpParser\Node\Expr\FuncCall::isFirstClassCallable()
```

**Comment by tm1000** [comment]
So Im unsure why this is happening but its the result of me using composers 'path' repository to link psalm into my project instead of having to use github (for psalm development).

I see the class extended but the call fails in the same place:

```
Uncaught Error: Call to undefined method PhpParser\Node\Expr\FuncCall::isFirstClassCallable() in /Users/andrewnagy/psalm/src/Psalm/Internal/PhpVisitor/Reflector/ExpressionScanner.php:128
Stack trace:
#0 /Users/andrewnagy/psalm/src/Psalm/Internal/PhpVisitor/Reflector/ExpressionScanner.php(84): Psalm\Internal\PhpVisitor\Reflector\ExpressionScanner::registerClassMapFunctionCall(Object(Psalm\Codebase), Object(Psalm\Storage\FileStorage), Object(Psalm\Internal\Scanner\FileScanner), Object(Psalm\Aliases), 'spl_autoload_re...', Object(PhpParser\Node\Expr\FuncCall), Object(Psalm\Storage\MethodStorage), NULL)
#1 /Users/andrewnagy/psalm/src/Psalm/Internal/PhpVisitor/ReflectorVisitor.php(346): Psalm\Internal\PhpVisitor\Reflector\ExpressionScanner::scan(Object(Psalm\Codebase), Object(Psalm\Internal\Scanner\FileScanner), Object(Psalm\Storage\FileStorage), Object(Psalm\Aliases), Object(PhpParser\Node\Expr\FuncCall), Object(Psalm\Storage\MethodStorage), NULL)
#2 /Users/andrewnagy/psalm/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(123): Psalm\Internal\PhpVisitor\ReflectorVisitor->enterNode(Object(PhpParser\Node\Expr\FuncCall))
#3 /Users/andrewnagy/psalm/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(223): PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Stmt\Expression))
#4 /Users/andrewnagy/psalm/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(114): PhpParser\NodeTraverser->traverseArray(Array)
#5 /Users/andrewnagy/psalm/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(223): PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Stmt\ClassMethod))
#6 /Users/andrewnagy/psalm/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(114): PhpParser\NodeTraverser->traverseArray(Array)
#7 /Users/andrewnagy/psalm/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(223): PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Stmt\Class_))
#8 /Users/andrewnagy/psalm/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(91): PhpParser\NodeTraverser->traverseArray(Array)
#9 /Users/andrewnagy/psalm/src/Psalm/Internal/Scanner/FileScanner.php(88): PhpParser\NodeTraverser->traverse(Array)
#10 /Users/andrewnagy/psalm/src/Psalm/Internal/Codebase/Scanner.php(589): Psalm\Internal\Scanner\FileScanner->scan(Object(Psalm\Codebase), Object(Psalm\Storage\FileStorage), false, Object(Psalm\Progress\VoidProgress))
#11 /Users/andrewnagy/psalm/src/Psalm/Internal/Codebase/Scanner.php(339): Psalm\Internal\Codebase\Scanner->scanFile('/Users/andrewna...', Array, true)
#12 /Users/andrewnagy/psalm/src/Psalm/Internal/Codebase/Scanner.php(459): Psalm\Internal\Codebase\Scanner->Psalm\Internal\Codebase\{closure}(1, '/Users/andrewna...')
#13 /Users/andrewnagy/psalm/src/Psalm/Internal/Codebase/Scanner.php(303): Psalm\Internal\Codebase\Scanner->scanFilePaths(1)
#14 /Users/andrewnagy/psalm/src/Psalm/Config.php(2138): Psalm\Internal\Codebase\Scanner->scanFiles(Object(Psalm\Internal\Codebase\ClassLikes))
#15 /Users/andrewnagy/psalm/src/Psalm/Internal/Analyzer/ProjectAnalyzer.php(426): Psalm\Config->visitComposerAutoloadFiles(Object(Psalm\Internal\Analyzer\ProjectAnalyzer), Object(Psalm\Progress\VoidProgress))
#16 /Users/andrewnagy/psalm/src/Psalm/Internal/Analyzer/ProjectAnalyzer.php(437): Psalm\Internal\Analyzer\ProjectAnalyzer->visitAutoloadFiles()
#17 /Users/andrewnagy/psalm/src/Psalm/Internal/Cli/LanguageServer.php(321): Psalm\Internal\Analyzer\ProjectAnalyzer->server(NULL, false)
#18 /Users/andrewnagy/psalm/psalm-language-server(7): Psalm\Internal\Cli\LanguageServer::run(Array)
#19 {main}
```

**Comment by tm1000** [comment]
Figured it out.

When using `path` in repositories then that library will reference its own composer libraries to run instead of the projects. Which makes sense. Thus I was very much outdated.
