### ISSUE TITLE
Crash when using psalm with rector

### ISSUE THREAD

**Issue by leighman** [vimeo/psalm#7458]
This issue occurs when updating from rector `0.11.52` to `0.12.12` but the config has
```
        <ignoreFiles>
          <directory name="vendor/rector" />
        </ignoreFiles>
```
so I wouldn't expect the situation.

When I run psalm I get the following error:
```
> Composer\Config::disableProcessTimeout
> psalm --config=psalm-ci.xml --no-cache
Scanning files...
Uncaught RuntimeException: PHP Error: Class 'RectorPrefix20220107\Attribute' not found in /var/www/html/vendor/rector/rector/vendor/symfony/polyfill-php80/Resources/stubs/Attribute.php:23 in /var/www/html/vendor/vimeo/psalm/src/Psalm/Internal/ErrorHandler.php:66
Stack trace:
#0 [internal function]: Psalm\Internal\ErrorHandler::Psalm\Internal\{closure}()
#1 /var/www/html/vendor/rector/rector/vendor/symfony/polyfill-php80/Resources/stubs/Attribute.php(23): class_alias()
#2 /var/www/html/vendor/composer/ClassLoader.php(476): include('/var/www/html/v...')
#3 /var/www/html/vendor/composer/ClassLoader.php(344): Composer\Autoload\includeFile()
#4 [internal function]: Composer\Autoload\ClassLoader->loadClass()
#5 [internal function]: spl_autoload_call()
#6 /var/www/html/vendor/vimeo/psalm/src/Psalm/Internal/PhpVisitor/Reflector/ExpressionResolver.php(385): class_exists()
#7 /var/www/html/vendor/vimeo/psalm/src/Psalm/Internal/PhpVisitor/Reflector/ExpressionResolver.php(344): Psalm\Internal\PhpVisitor\Reflector\ExpressionResolver::functionEvaluatesToTrue()
#8 /var/www/html/vendor/vimeo/psalm/src/Psalm/Internal/PhpVisitor/Reflector/ExpressionResolver.php(288): Psalm\Internal\PhpVisitor\Reflector\ExpressionResolver::enterConditional()
#9 /var/www/html/vendor/vimeo/psalm/src/Psalm/Internal/PhpVisitor/Reflector/ExpressionResolver.php(294): Psalm\Internal\PhpVisitor\Reflector\ExpressionResolver::enterConditional()
#10 /var/www/html/vendor/vimeo/psalm/src/Psalm/Internal/PhpVisitor/Reflector/ExpressionResolver.php(294): Psalm\Internal\PhpVisitor\Reflector\ExpressionResolver::enterConditional()
#11 /var/www/html/vendor/vimeo/psalm/src/Psalm/Internal/PhpVisitor/ReflectorVisitor.php(297): Psalm\Internal\PhpVisitor\Reflector\ExpressionResolver::enterConditional()
#12 /var/www/html/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(200): Psalm\Internal\PhpVisitor\ReflectorVisitor->enterNode()
#13 /var/www/html/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(91): PhpParser\NodeTraverser->traverseArray()
#14 /var/www/html/vendor/vimeo/psalm/src/Psalm/Internal/Scanner/FileScanner.php(86): PhpParser\NodeTraverser->traverse()
#15 /var/www/html/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Scanner.php(579): Psalm\Internal\Scanner\FileScanner->scan()
#16 /var/www/html/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Scanner.php(330): Psalm\Internal\Codebase\Scanner->scanFile()
#17 /var/www/html/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Scanner.php(449): Psalm\Internal\Codebase\Scanner->Psalm\Internal\Codebase\{closure}()
#18 /var/www/html/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Scanner.php(294): Psalm\Internal\Codebase\Scanner->scanFilePaths()
#19 /var/www/html/vendor/vimeo/psalm/src/Psalm/Codebase.php(473): Psalm\Internal\Codebase\Scanner->scanFiles()
#20 /var/www/html/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/ProjectAnalyzer.php(594): Psalm\Codebase->scanFiles()
#21 /var/www/html/vendor/vimeo/psalm/src/Psalm/Internal/Cli/Psalm.php(360): Psalm\Internal\Analyzer\ProjectAnalyzer->check()
#22 /var/www/html/vendor/vimeo/psalm/psalm(4): Psalm\Internal\Cli\Psalm::run()
#23 {main}
(Psalm 4.13.1@5cf660f63b548ccd4a56f62d916ee4d6028e01a3 crashed due to an uncaught Throwable)
Script psalm --config=psalm-ci.xml --no-cache handling the psalm event returned with error code 1
```

Any suggestions to investigate?

**Comment by orklah** [comment]
Please update to a more recent Psalm version, we recently fixed issues linked to newer versions of Composer that could explain this

**Comment by leighman** [comment]
Just tried `4.18.1` and it's still an issue unfortunately

**Comment by orklah** [comment]
Ok, with that out of the way, I'll need a few infos:
- can you run psalm with --debug-by-line and post the result?
- can you post the updated trace. Line numbers must have changed a little
- can you give us the version number of rector you us?
- can you give us the version of symfony/polyfill-80 that should be in your composer.lock ?

Thanks!

**Comment by leighman** [comment]
psalm 4.18.1
rector 0.12.15

Updated trace:
```
Uncaught RuntimeException: PHP Error: Class 'RectorPrefix20220126\Attribute' not found in /var/www/html/vendor/rector/rector/vendor/symfony/polyfill-php80/Resources/stubs/Attribute.php:23 in /var/www/html/vendor/vimeo/psalm/src/Psalm/Internal/ErrorHandler.php:66
Stack trace:
#0 [internal function]: Psalm\Internal\ErrorHandler::Psalm\Internal\{closure}()
#1 /var/www/html/vendor/rector/rector/vendor/symfony/polyfill-php80/Resources/stubs/Attribute.php(23): class_alias()
#2 /var/www/html/vendor/composer/ClassLoader.php(476): include('/var/www/html/v...')
#3 /var/www/html/vendor/composer/ClassLoader.php(344): Composer\Autoload\includeFile()
#4 [internal function]: Composer\Autoload\ClassLoader->loadClass()
#5 [internal function]: spl_autoload_call()
#6 /var/www/html/vendor/vimeo/psalm/src/Psalm/Internal/PhpVisitor/Reflector/ExpressionResolver.php(403): class_exists()
#7 /var/www/html/vendor/vimeo/psalm/src/Psalm/Internal/PhpVisitor/Reflector/ExpressionResolver.php(362): Psalm\Internal\PhpVisitor\Reflector\ExpressionResolver::functionEvaluatesToTrue()
#8 /var/www/html/vendor/vimeo/psalm/src/Psalm/Internal/PhpVisitor/Reflector/ExpressionResolver.php(306): Psalm\Internal\PhpVisitor\Reflector\ExpressionResolver::enterConditional()
#9 /var/www/html/vendor/vimeo/psalm/src/Psalm/Internal/PhpVisitor/Reflector/ExpressionResolver.php(312): Psalm\Internal\PhpVisitor\Reflector\ExpressionResolver::enterConditional()
#10 /var/www/html/vendor/vimeo/psalm/src/Psalm/Internal/PhpVisitor/Reflector/ExpressionResolver.php(312): Psalm\Internal\PhpVisitor\Reflector\ExpressionResolver::enterConditional()
#11 /var/www/html/vendor/vimeo/psalm/src/Psalm/Internal/PhpVisitor/ReflectorVisitor.php(309): Psalm\Internal\PhpVisitor\Reflector\ExpressionResolver::enterConditional()
#12 /var/www/html/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(200): Psalm\Internal\PhpVisitor\ReflectorVisitor->enterNode()
#13 /var/www/html/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(91): PhpParser\NodeTraverser->traverseArray()
#14 /var/www/html/vendor/vimeo/psalm/src/Psalm/Internal/Scanner/FileScanner.php(88): PhpParser\NodeTraverser->traverse()
#15 /var/www/html/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Scanner.php(589): Psalm\Internal\Scanner\FileScanner->scan()
#16 /var/www/html/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Scanner.php(339): Psalm\Internal\Codebase\Scanner->scanFile()
#17 /var/www/html/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Scanner.php(459): Psalm\Internal\Codebase\Scanner->Psalm\Internal\Codebase\{closure}()
#18 /var/www/html/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Scanner.php(303): Psalm\Internal\Codebase\Scanner->scanFilePaths()
#19 /var/www/html/vendor/vimeo/psalm/src/Psalm/Codebase.php(518): Psalm\Internal\Codebase\Scanner->scanFiles()
#20 /var/www/html/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/ProjectAnalyzer.php(639): Psalm\Codebase->scanFiles()
#21 /var/www/html/vendor/vimeo/psalm/src/Psalm/Internal/Cli/Psalm.php(373): Psalm\Internal\Analyzer\ProjectAnalyzer->check()
#22 /var/www/html/vendor/vimeo/psalm/psalm(7): Psalm\Internal\Cli\Psalm::run()
#23 {main}
```

**Comment by leighman** [comment]
debug-by-line (redacted some packages that are not psalm, phpstan, rector, php-parser, let me know if you think that's a problem):
```
Using composer to locate file for PhpParser\Node\Stmt\Return_
Parsing /var/www/html/vendor/vimeo/psalm/src/Psalm/Plugin/PluginEntryPointInterface.php
Scanning /var/www/html/vendor/vimeo/psalm/src/Psalm/Plugin/PluginEntryPointInterface.php
Parsing /var/www/html/vendor/vimeo/psalm/src/Psalm/Plugin/EventHandler/AfterMethodCallAnalysisInterface.php
Scanning /var/www/html/vendor/vimeo/psalm/src/Psalm/Plugin/EventHandler/AfterMethodCallAnalysisInterface.php
Parsing /var/www/html/vendor/vimeo/psalm/src/Psalm/Plugin/RegistrationInterface.php
Scanning /var/www/html/vendor/vimeo/psalm/src/Psalm/Plugin/RegistrationInterface.php
Parsing /var/www/html/vendor/vimeo/psalm/src/Psalm/Plugin/EventHandler/Event/AfterMethodCallAnalysisEvent.php
Scanning /var/www/html/vendor/vimeo/psalm/src/Psalm/Plugin/EventHandler/Event/AfterMethodCallAnalysisEvent.php
Parsing /var/www/html/vendor/nikic/php-parser/lib/PhpParser/Node/Expr/MethodCall.php
Scanning /var/www/html/vendor/nikic/php-parser/lib/PhpParser/Node/Expr/MethodCall.php
Parsing /var/www/html/vendor/vimeo/psalm/src/Psalm/Type/Atomic/TNamedObject.php
Scanning /var/www/html/vendor/vimeo/psalm/src/Psalm/Type/Atomic/TNamedObject.php
Parsing /var/www/html/vendor/vimeo/psalm/src/Psalm/IssueBuffer.php
Scanning /var/www/html/vendor/vimeo/psalm/src/Psalm/IssueBuffer.php
Parsing /var/www/html/vendor/vimeo/psalm/src/Psalm/CodeLocation.php
Scanning /var/www/html/vendor/vimeo/psalm/src/Psalm/CodeLocation.php
Parsing /var/www/html/vendor/vimeo/psalm/src/Psalm/Issue/PluginIssue.php
Deep scanning /var/www/html/vendor/vimeo/psalm/src/Psalm/Issue/PluginIssue.php
...
Parsing /var/www/html/vendor/rector/rector/packages/Testing/PHPUnit/AbstractRectorTestCase.php
Deep scanning /var/www/html/vendor/rector/rector/packages/Testing/PHPUnit/AbstractRectorTestCase.php
Parsing /var/www/html/vendor/rector/rector/vendor/symplify/smart-file-system/src/SmartFileInfo.php
Scanning /var/www/html/vendor/rector/rector/vendor/symplify/smart-file-system/src/SmartFileInfo.php
...
Parsing /var/www/html/vendor/rector/rector/src/Rector/AbstractRector.php
Deep scanning /var/www/html/vendor/rector/rector/src/Rector/AbstractRector.php
Parsing /var/www/html/vendor/rector/rector/src/Contract/Rector/ConfigurableRectorInterface.php
Scanning /var/www/html/vendor/rector/rector/src/Contract/Rector/ConfigurableRectorInterface.php
Parsing phar:///var/www/html/vendor/phpstan/phpstan/phpstan.phar/src/Reflection/ReflectionProvider.php
Scanning phar:///var/www/html/vendor/phpstan/phpstan/phpstan.phar/src/Reflection/ReflectionProvider.php
Parsing /var/www/html/vendor/rector/rector/vendor/symplify/rule-doc-generator-contracts/src/ValueObject/RuleDefinition.php
Scanning /var/www/html/vendor/rector/rector/vendor/symplify/rule-doc-generator-contracts/src/ValueObject/RuleDefinition.php
Parsing /var/www/html/vendor/rector/rector/vendor/symplify/rule-doc-generator-contracts/src/ValueObject/CodeSample/CodeSample.php
Scanning /var/www/html/vendor/rector/rector/vendor/symplify/rule-doc-generator-contracts/src/ValueObject/CodeSample/CodeSample.php
Parsing /var/www/html/vendor/nikic/php-parser/lib/PhpParser/Node/Expr/StaticCall.php
Scanning /var/www/html/vendor/nikic/php-parser/lib/PhpParser/Node/Expr/StaticCall.php
Parsing /var/www/html/vendor/nikic/php-parser/lib/PhpParser/Node.php
Scanning /var/www/html/vendor/nikic/php-parser/lib/PhpParser/Node.php
Parsing /var/www/html/vendor/nikic/php-parser/lib/PhpParser/Node/Expr/New_.php
Scanning /var/www/html/vendor/nikic/php-parser/lib/PhpParser/Node/Expr/New_.php
Parsing /var/www/html/vendor/rector/rector/src/Configuration/Option.php
Scanning /var/www/html/vendor/rector/rector/src/Configuration/Option.php
Parsing /var/www/html/vendor/rector/rector/packages/Set/ValueObject/SetList.php
Scanning /var/www/html/vendor/rector/rector/packages/Set/ValueObject/SetList.php
Parsing /var/www/html/vendor/rector/rector/rules/Php73/Rector/FuncCall/JsonThrowOnErrorRector.php
Scanning /var/www/html/vendor/rector/rector/rules/Php73/Rector/FuncCall/JsonThrowOnErrorRector.php
Parsing /var/www/html/vendor/rector/rector/rules/Php74/Rector/Closure/ClosureToArrowFunctionRector.php
Scanning /var/www/html/vendor/rector/rector/rules/Php74/Rector/Closure/ClosureToArrowFunctionRector.php
Parsing /var/www/html/vendor/rector/rector/vendor/rector/rector-phpunit/src/Set/PHPUnitSetList.php
Scanning /var/www/html/vendor/rector/rector/vendor/rector/rector-phpunit/src/Set/PHPUnitSetList.php
...
Parsing /var/www/html/vendor/nikic/php-parser/lib/PhpParser/Node/Stmt/ClassMethod.php
Scanning /var/www/html/vendor/nikic/php-parser/lib/PhpParser/Node/Stmt/ClassMethod.php
Parsing /var/www/html/vendor/rector/rector/packages/NodeTypeResolver/Node/AttributeKey.php
Scanning /var/www/html/vendor/rector/rector/packages/NodeTypeResolver/Node/AttributeKey.php
Parsing /var/www/html/vendor/nikic/php-parser/lib/PhpParser/Node/Stmt/While_.php
Scanning /var/www/html/vendor/nikic/php-parser/lib/PhpParser/Node/Stmt/While_.php
Parsing /var/www/html/vendor/nikic/php-parser/lib/PhpParser/Node/Stmt.php
Scanning /var/www/html/vendor/nikic/php-parser/lib/PhpParser/Node/Stmt.php
Parsing /var/www/html/vendor/nikic/php-parser/lib/PhpParser/Node/Stmt/For_.php
Scanning /var/www/html/vendor/nikic/php-parser/lib/PhpParser/Node/Stmt/For_.php
Parsing /var/www/html/vendor/nikic/php-parser/lib/PhpParser/Node/Stmt/Foreach_.php
Scanning /var/www/html/vendor/nikic/php-parser/lib/PhpParser/Node/Stmt/Foreach_.php
Parsing /var/www/html/vendor/nikic/php-parser/lib/PhpParser/Node/Stmt/If_.php
Scanning /var/www/html/vendor/nikic/php-parser/lib/PhpParser/Node/Stmt/If_.php
Parsing /var/www/html/vendor/nikic/php-parser/lib/PhpParser/Node/Expr/FuncCall.php
Scanning /var/www/html/vendor/nikic/php-parser/lib/PhpParser/Node/Expr/FuncCall.php
Parsing /var/www/html/vendor/nikic/php-parser/lib/PhpParser/Node/Stmt/Expression.php
Scanning /var/www/html/vendor/nikic/php-parser/lib/PhpParser/Node/Stmt/Expression.php
Parsing /var/www/html/vendor/nikic/php-parser/lib/PhpParser/Node/Stmt/Return_.php
Scanning /var/www/html/vendor/nikic/php-parser/lib/PhpParser/Node/Stmt/Return_.php
Parsing /var/www/html/vendor/rector/rector/preload.php
Deep scanning /var/www/html/vendor/rector/rector/preload.php
Parsing /var/www/html/vendor/rector/rector/vendor/scoper-autoload.php
Deep scanning /var/www/html/vendor/rector/rector/vendor/scoper-autoload.php
Uncaught RuntimeException: PHP Error: Class 'RectorPrefix20220126\Attribute' not found in /var/www/html/vendor/rector/rector/vendor/symfony/polyfill-php80/Resources/stubs/Attribute.php:23 in /var/www/html/vendor/vimeo/psalm/src/Psalm/Internal/ErrorHandler.php:66
Stack trace:
#0 [internal function]: Psalm\Internal\ErrorHandler::Psalm\Internal\{closure}()
#1 /var/www/html/vendor/rector/rector/vendor/symfony/polyfill-php80/Resources/stubs/Attribute.php(23): class_alias()
#2 /var/www/html/vendor/composer/ClassLoader.php(476): include('/var/www/html/v...')
#3 /var/www/html/vendor/composer/ClassLoader.php(344): Composer\Autoload\includeFile()
#4 [internal function]: Composer\Autoload\ClassLoader->loadClass()
#5 [internal function]: spl_autoload_call()
#6 /var/www/html/vendor/vimeo/psalm/src/Psalm/Internal/PhpVisitor/Reflector/ExpressionResolver.php(403): class_exists()
#7 /var/www/html/vendor/vimeo/psalm/src/Psalm/Internal/PhpVisitor/Reflector/ExpressionResolver.php(362): Psalm\Internal\PhpVisitor\Reflector\ExpressionResolver::functionEvaluatesToTrue()
#8 /var/www/html/vendor/vimeo/psalm/src/Psalm/Internal/PhpVisitor/Reflector/ExpressionResolver.php(306): Psalm\Internal\PhpVisitor\Reflector\ExpressionResolver::enterConditional()
#9 /var/www/html/vendor/vimeo/psalm/src/Psalm/Internal/PhpVisitor/Reflector/ExpressionResolver.php(312): Psalm\Internal\PhpVisitor\Reflector\ExpressionResolver::enterConditional()
#10 /var/www/html/vendor/vimeo/psalm/src/Psalm/Internal/PhpVisitor/Reflector/ExpressionResolver.php(312): Psalm\Internal\PhpVisitor\Reflector\ExpressionResolver::enterConditional()
#11 /var/www/html/vendor/vimeo/psalm/src/Psalm/Internal/PhpVisitor/ReflectorVisitor.php(309): Psalm\Internal\PhpVisitor\Reflector\ExpressionResolver::enterConditional()
#12 /var/www/html/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(200): Psalm\Internal\PhpVisitor\ReflectorVisitor->enterNode()
#13 /var/www/html/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(91): PhpParser\NodeTraverser->traverseArray()
#14 /var/www/html/vendor/vimeo/psalm/src/Psalm/Internal/Scanner/FileScanner.php(88): PhpParser\NodeTraverser->traverse()
#15 /var/www/html/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Scanner.php(589): Psalm\Internal\Scanner\FileScanner->scan()
#16 /var/www/html/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Scanner.php(339): Psalm\Internal\Codebase\Scanner->scanFile()
#17 /var/www/html/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Scanner.php(459): Psalm\Internal\Codebase\Scanner->Psalm\Internal\Codebase\{closure}()
#18 /var/www/html/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Scanner.php(303): Psalm\Internal\Codebase\Scanner->scanFilePaths()
#19 /var/www/html/vendor/vimeo/psalm/src/Psalm/Codebase.php(518): Psalm\Internal\Codebase\Scanner->scanFiles()
#20 /var/www/html/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/ProjectAnalyzer.php(639): Psalm\Codebase->scanFiles()
#21 /var/www/html/vendor/vimeo/psalm/src/Psalm/Internal/Cli/Psalm.php(373): Psalm\Internal\Analyzer\ProjectAnalyzer->check()
#22 /var/www/html/vendor/vimeo/psalm/psalm(7): Psalm\Internal\Cli\Psalm::run()
#23 {main}
(Psalm 4.18.1@dda05fa913f4dc6eb3386f2f7ce5a45d37a71bcb crashed due to an uncaught Throwable)
```

**Comment by orklah** [comment]
Hi @TomasVotruba!

Could you take a look at this please? I'd expect the Attribute class to have a namespace declaration here. When we actually make a call to class_exists on `RectorPrefix20220126\\Attribute`, Composer is unable to retrieve a corresponding class

**Comment by TomasVotruba** [comment]
Hi @orklah ,

it seems the scoper is prefixing too much of code in Rector.

What happens when you remove this line?
https://github.com/rectorphp/rector/blob/c88e1fc6018e7cf2e23cc638f136a1c730c36719/vendor/symfony/polyfill-php80/Resources/stubs/Attribute.php#L23

**Comment by leighman** [comment]
Removing that gives
```
PHP Fatal error:  Declaration of RectorPrefix20220126\Symfony\Component\Console\Completion\CompletionInput::__toString() must be compatible with RectorPrefix20220126\Symfony\Component\Console\Input\ArgvInput::__toString(): string in /var/www/html/vendor/rector/rector/vendor/symfony/console/Completion/CompletionInput.php on line 198
```

Adding a `: string` return type in `CompletionInput.php` then seems to allow psalm to complete successfully

**Comment by TomasVotruba** [comment]
cc @samsonasik Could you check this one? We need to extend `scoper.php` to remove class_alias from this line https://github.com/rectorphp/rector/blob/c88e1fc6018e7cf2e23cc638f136a1c730c36719/vendor/symfony/polyfill-php80/Resources/stubs/Attribute.php#L23

+ check the return type removal in https://github.com/vimeo/psalm/issues/7458#issuecomment-1025689642

**Comment by samsonasik** [comment]
I will try.

**Comment by samsonasik** [comment]
@leighman it should be fixed in latest `"rector/rector": "dev-main"`, ref  https://github.com/rectorphp/rector/commit/3ebcd0c7baab406140e4f797d18646d722746df2#diff-be08106ae719ccbdbdb5bc47abffc854c9050d8a40c87b2e0187ae014bf1702d 

please give it a try.

```bash
composer config minimum-stability dev
composer config prefer-stable true
composer update rector/rector:dev-main
```
