### ISSUE TITLE
Psalm 4.20.0 crashes on "@throws ExceptionClassThatDoesNotExist"

### ISSUE THREAD

**Issue by sebastianbergmann** [vimeo/psalm#7605]
The crash can be seen [here](https://github.com/sebastianbergmann/phpunit/runs/5110170458?check_suite_focus=true):

```
Uncaught InvalidArgumentException: Could not get class storage for sebastianbergmann\objectreflector\invalidargumentexception in phar:///home/runner/work/phpunit/phpunit/tools/psalm/src/Psalm/Internal/Provider/ClassLikeStorageProvider.php:40
Stack trace:
#0 phar:///home/runner/work/phpunit/phpunit/tools/psalm/src/Psalm/Internal/Codebase/ClassLikes.php(426): Psalm\Internal\Provider\ClassLikeStorageProvider->get()
#1 phar:///home/runner/work/phpunit/phpunit/tools/psalm/src/Psalm/Codebase.php(532): Psalm\Internal\Codebase\ClassLikes->classExtends()
#2 phar:///home/runner/work/phpunit/phpunit/tools/psalm/src/Psalm/Internal/Analyzer/FunctionLikeAnalyzer.php(377): Psalm\Codebase->classExtendsOrImplements()
#3 phar:///home/runner/work/phpunit/phpunit/tools/psalm/src/Psalm/Internal/Analyzer/ClassAnalyzer.php(824): Psalm\Internal\Analyzer\FunctionLikeAnalyzer->analyze()
#4 phar:///home/runner/work/phpunit/phpunit/tools/psalm/src/Psalm/Internal/Analyzer/ClassAnalyzer.php(245): Psalm\Internal\Analyzer\ClassAnalyzer->analyzeClassMethod()
#5 phar:///home/runner/work/phpunit/phpunit/tools/psalm/src/Psalm/Internal/Analyzer/FileAnalyzer.php(184): Psalm\Internal\Analyzer\ClassAnalyzer->analyze()
#6 phar:///home/runner/work/phpunit/phpunit/tools/psalm/src/Psalm/Internal/Codebase/Analyzer.php(286): Psalm\Internal\Analyzer\FileAnalyzer->analyze()
#7 phar:///home/runner/work/phpunit/phpunit/tools/psalm/src/Psalm/Internal/Codebase/Analyzer.php(436): Psalm\Internal\Codebase\Analyzer->Psalm\Internal\Codebase\{closure}()
#8 phar:///home/runner/work/phpunit/phpunit/tools/psalm/src/Psalm/Internal/Codebase/Analyzer.php(241): Psalm\Internal\Codebase\Analyzer->doAnalysis()
#9 phar:///home/runner/work/phpunit/phpunit/tools/psalm/src/Psalm/Internal/Analyzer/ProjectAnalyzer.php(482): Psalm\Internal\Codebase\Analyzer->analyzeFiles()
#10 phar:///home/runner/work/phpunit/phpunit/tools/psalm/src/Psalm/Internal/Cli/Psalm.php(275): Psalm\Internal\Analyzer\ProjectAnalyzer->check()
#11 phar:///home/runner/work/phpunit/phpunit/tools/psalm/psalm(7): Psalm\Internal\Cli\Psalm::run()
#12 /home/runner/work/phpunit/phpunit/tools/psalm(14): require('...')
#13 {main}
(Psalm 4.x-dev@ crashed due to an uncaught Throwable)
```

After this [change](https://github.com/sebastianbergmann/phpunit/commit/af00e008c279b0ac75d8a05b9676a929562d17d0), Psalm 4.20.0 no longer crashes when analysing PHPUnit's codebase.

**Comment by weirdan** [comment]
https://psalm.dev/r/d2e5e37236 - doesn't seem to crash anymore.
