### ISSUE TITLE
Scanning breaks due to unused vendor file using non existent class (during `visitAutoloadFiles`)

### ISSUE THREAD

**Issue by nocive** [vimeo/psalm#7680]
The scanning breaks during `visitAutoloadFiles` invokation.
The causer is a vendor file which is not used by the project. Couldn't find a way to explicitly exclude this file using `ignoredFiles`.

Here's the stack trace:
```
> HOME=/tmp psalm --threads=1 --no-cache
Target PHP version: 8.0 (inferred from composer.json)
Scanning files...
Uncaught Error: Class "Doctrine\Common\Cache\CacheProvider" not found in /src/vendor/symfony/cache/DoctrineProvider.php:23
Stack trace:
#0 phar:///usr/local/bin/psalm/.box/vendor/composer/ClassLoader.php(444): include()
#1 phar:///usr/local/bin/psalm/.box/vendor/composer/ClassLoader.php(322): Composer\Autoload\includeFile('/src/applicatio...')
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass('Symfony\\Compone...')
#3 phar:///usr/local/bin/psalm/src/Psalm/Internal/PhpVisitor/Reflector/ExpressionResolver.php(230): class_exists('Symfony\\Compone...')
#4 phar:///usr/local/bin/psalm/src/Psalm/Internal/PhpVisitor/Reflector/ExpressionResolver.php(209): Psalm\Internal\PhpVisitor\Reflector\ExpressionResolver::functionEvaluatesToTrue(Object(Psalm\Codebase), '/src/applicatio...', Object(_HumbugBox4731e20c145c\PhpParser\Node\Expr\FuncCall))
#5 phar:///usr/local/bin/psalm/src/Psalm/Internal/PhpVisitor/Reflector/ExpressionResolver.php(177): Psalm\Internal\PhpVisitor\Reflector\ExpressionResolver::enterConditional(Object(Psalm\Codebase), '/src/applicatio...', Object(_HumbugBox4731e20c145c\PhpParser\Node\Expr\FuncCall))
#6 phar:///usr/local/bin/psalm/src/Psalm/Internal/PhpVisitor/Reflector/ExpressionResolver.php(181): Psalm\Internal\PhpVisitor\Reflector\ExpressionResolver::enterConditional(Object(Psalm\Codebase), '/src/applicatio...', Object(_HumbugBox4731e20c145c\PhpParser\Node\Expr\BooleanNot))
#7 phar:///usr/local/bin/psalm/src/Psalm/Internal/PhpVisitor/ReflectorVisitor.php(226): Psalm\Internal\PhpVisitor\Reflector\ExpressionResolver::enterConditional(Object(Psalm\Codebase), '/src/applicatio...', Object(_HumbugBox4731e20c145c\PhpParser\Node\Expr\BinaryOp\BooleanAnd))
#8 phar:///usr/local/bin/psalm/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(176): Psalm\Internal\PhpVisitor\ReflectorVisitor->enterNode(Object(_HumbugBox4731e20c145c\PhpParser\Node\Stmt\If_))
#9 phar:///usr/local/bin/psalm/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(105): _HumbugBox4731e20c145c\PhpParser\NodeTraverser->traverseArray(Array)
#10 phar:///usr/local/bin/psalm/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(196): _HumbugBox4731e20c145c\PhpParser\NodeTraverser->traverseNode(Object(_HumbugBox4731e20c145c\PhpParser\Node\Stmt\If_))
#11 phar:///usr/local/bin/psalm/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(105): _HumbugBox4731e20c145c\PhpParser\NodeTraverser->traverseArray(Array)
#12 phar:///usr/local/bin/psalm/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(196): _HumbugBox4731e20c145c\PhpParser\NodeTraverser->traverseNode(Object(_HumbugBox4731e20c145c\PhpParser\Node\Stmt\Namespace_))
#13 phar:///usr/local/bin/psalm/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(85): _HumbugBox4731e20c145c\PhpParser\NodeTraverser->traverseArray(Array)
#14 phar:///usr/local/bin/psalm/src/Psalm/Internal/Scanner/FileScanner.php(60): _HumbugBox4731e20c145c\PhpParser\NodeTraverser->traverse(Array)
#15 phar:///usr/local/bin/psalm/src/Psalm/Internal/Codebase/Scanner.php(424): Psalm\Internal\Scanner\FileScanner->scan(Object(Psalm\Codebase), Object(Psalm\Storage\FileStorage), false, Object(Psalm\Progress\DefaultProgress))
#16 phar:///usr/local/bin/psalm/src/Psalm/Internal/Codebase/Scanner.php(264): Psalm\Internal\Codebase\Scanner->scanFile('/src/applicatio...', Array, true)
#17 phar:///usr/local/bin/psalm/src/Psalm/Internal/Codebase/Scanner.php(336): Psalm\Internal\Codebase\Scanner->Psalm\Internal\Codebase\{closure}(29, '/src/applicatio...')
#18 phar:///usr/local/bin/psalm/src/Psalm/Internal/Codebase/Scanner.php(243): Psalm\Internal\Codebase\Scanner->scanFilePaths(1)
#19 phar:///usr/local/bin/psalm/src/Psalm/Config.php(1590): Psalm\Internal\Codebase\Scanner->scanFiles(Object(Psalm\Internal\Codebase\ClassLikes))
#20 phar:///usr/local/bin/psalm/src/Psalm/Internal/Analyzer/ProjectAnalyzer.php(309): Psalm\Config->visitComposerAutoloadFiles(Object(Psalm\Internal\Analyzer\ProjectAnalyzer), Object(Psalm\Progress\DefaultProgress))
#21 phar:///usr/local/bin/psalm/src/Psalm/Internal/Analyzer/ProjectAnalyzer.php(448): Psalm\Internal\Analyzer\ProjectAnalyzer->visitAutoloadFiles()
#22 phar:///usr/local/bin/psalm/src/Psalm/Internal/Cli/Psalm.php(275): Psalm\Internal\Analyzer\ProjectAnalyzer->check('/src/applicatio...', true)
#23 phar:///usr/local/bin/psalm/psalm(7): Psalm\Internal\Cli\Psalm::run(Array)
#24 /usr/local/bin/psalm(14): require('phar:///usr/loc...')
#25 {main}
(Psalm 4.x-dev@ crashed due to an uncaught Throwable)
```

psalm.xml
```
<?xml version="1.0"?>
<psalm
    errorLevel="7"
    resolveFromConfigFile="true"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns="https://getpsalm.org/schema/config"
    xsi:schemaLocation="https://getpsalm.org/schema/config vendor/vimeo/psalm/config.xsd"
>
    <projectFiles>
        <directory name="src" />
        <ignoreFiles>
            <directory name="vendor" />
        </ignoreFiles>
    </projectFiles>
</psalm>
```

The culprit file `/src/vendor/symfony/cache/DoctrineProvider.php` is a legacy doctrine provider from `symfony/cache` which does in fact rely on a non existent class, however this file is not actually used by the project's code.
Attempting to explicitly ignore the vendor file also makes no difference.

Psalm version is the latest at the time of writing: `4.20.0`.
Using the non phar version of psalm results in the same error.

**Comment by nocive** [comment]
After further investigation I realized that the issue stems from a library update and also occurs in php 8.0.
Closing as invalid.

Would still be nice to be able to exclude specific files which currently doesn't seem to be possible.

**Comment by Jean85** [comment]
@nocive I'm having the same issue, how did you solve it?

**Comment by nocive** [comment]
@Jean85 i ended up making doctrine/common a dev dependency in a project that doesn’t use nor need doctrine :(

**Comment by Jean85** [comment]
Roger. My solution is https://github.com/symfony/symfony/pull/45703 instead, but I had to copy the commit into a [split fork](https://github.com/jean85/cache/tree/hide-deprecated-doctrine-provider) to be able to install it alongside the other normal Symfony packages. Feel free to use it.

**Comment by nicolas-grekas** [comment]
This should be reopened to me. Things like https://github.com/symfony/symfony/pull/45703 are not legit.

**Comment by orklah** [comment]
Could someone create a small snippet just to show the issue? I'm unfamiliar with the code.

From what I understand, there is a class declared somewhere in a dependency that extends another class that is missing.

If so, this is the sort of thing Psalm have to report, it could mean the autoloader is broken, it could be a missing dependency or even a bug in Psalm own resolving module. Hard to just sweep that under the rug :(

But maybe I'm missing context?

**Comment by nocive** [comment]
@orklah it could be good enough to have the ability to ignore a specific file for scanning purposes. Currently there's basically no way to work around something like this even if the offending file is not used in the project.

Additionally and maybe to help provide more context, the problem at hands here is that the `symfony/cache` component references a class from `doctrine/common`, but a project won't use doctrine just because it uses the cache component (unless it actually needs the doctrine adapter).

**Comment by Jean85** [comment]
> If so, this is the sort of thing Psalm have to report, it could mean the autoloader is broken, it could be a missing dependency or even a bug in Psalm own resolving module. Hard to just sweep that under the rug :(

@orklah I would put the issue in the baseline, if that was the case... but the issue here is that the whole tool crashes!
