### ISSUE TITLE
JsonException Psalm\Internal\Clause

### ISSUE THREAD

**Issue by ohader** [vimeo/psalm#7771]
> Uncaught JsonException: Malformed UTF-8 characters, possibly incorrectly encoded in src/Psalm/Internal/Clause.php:124
https://github.com/vimeo/psalm/blob/0a81f8cd6cfb4d6db37b9d29c0e7b51d5af0f498/src/Psalm/Internal/Clause.php#L124

using `vimeo/psalm dev-master` (a0739b1), probably related to 0a81f8cd6cfb4d6db37b9d29c0e7b51d5af0f498

#### The payload of `$possibility_strings` at that time is

```
array(1) {
  ["$signature"]=>
  array(1) {
    [0]=>
    string(18) "!~string(��ࡱ�)"
  }
}
```

and the parsed file at that time was (similar to) https://github.com/PHPOffice/PHPExcel/blob/1.8.0/Classes/PHPExcel/Shared/OLE.php

#### Stack Trace

```
Stack trace:
#0 src/Psalm/Internal/Clause.php(124): json_encode(Array, 4194304)
#1 src/Psalm/Internal/Algebra/FormulaGenerator.php(436): Psalm\Internal\Clause->__construct(Array, 4922980, 4922980, false, true, true, Array)
#2 src/Psalm/Internal/Analyzer/Statements/Block/IfElseAnalyzer.php(135): Psalm\Internal\Algebra\FormulaGenerator::getFormula(4922980, 4922980, Object(PhpParser\Node\Expr\BinaryOp\NotEqual), 'PHPExcel_Shared...', Object(Psalm\Internal\Analyzer\StatementsAnalyzer), Object(Psalm\Codebase))
#3 src/Psalm/Internal/Analyzer/StatementsAnalyzer.php(534): Psalm\Internal\Analyzer\Statements\Block\IfElseAnalyzer::analyze(Object(Psalm\Internal\Analyzer\StatementsAnalyzer), Object(PhpParser\Node\Stmt\If_), Object(Psalm\Context))
#4 src/Psalm/Internal/Analyzer/StatementsAnalyzer.php(212): Psalm\Internal\Analyzer\StatementsAnalyzer::analyzeStatement(Object(Psalm\Internal\Analyzer\StatementsAnalyzer), Object(PhpParser\Node\Stmt\If_), Object(Psalm\Context), Object(Psalm\Context))
#5 src/Psalm/Internal/Analyzer/FunctionLikeAnalyzer.php(478): Psalm\Internal\Analyzer\StatementsAnalyzer->analyze(Array, Object(Psalm\Context), Object(Psalm\Context), true)
#6 src/Psalm/Internal/Analyzer/ClassAnalyzer.php(1780): Psalm\Internal\Analyzer\FunctionLikeAnalyzer->analyze(Object(Psalm\Context), Object(Psalm\Internal\Provider\NodeDataProvider), Object(Psalm\Context))
#7 src/Psalm/Internal/Analyzer/ClassAnalyzer.php(421): Psalm\Internal\Analyzer\ClassAnalyzer->analyzeClassMethod(Object(PhpParser\Node\Stmt\ClassMethod), Object(Psalm\Storage\ClassLikeStorage), Object(Psalm\Internal\Analyzer\ClassAnalyzer), Object(Psalm\Context), Object(Psalm\Context))
#8 src/Psalm/Internal/Analyzer/FileAnalyzer.php(229): Psalm\Internal\Analyzer\ClassAnalyzer->analyze(Object(Psalm\Context), Object(Psalm\Context))
#9 src/Psalm/Internal/Codebase/Analyzer.php(360): Psalm\Internal\Analyzer\FileAnalyzer->analyze()
#10 src/Psalm/Internal/Codebase/Analyzer.php(617): Psalm\Internal\Codebase\Analyzer->Psalm\Internal\Codebase\{closure}(1121, '/Volumes/kranke...')
#11 src/Psalm/Internal/Codebase/Analyzer.php(289): Psalm\Internal\Codebase\Analyzer->doAnalysis(Object(Psalm\Internal\Analyzer\ProjectAnalyzer), 1)
#12 src/Psalm/Internal/Analyzer/ProjectAnalyzer.php(689): Psalm\Internal\Codebase\Analyzer->analyzeFiles(Object(Psalm\Internal\Analyzer\ProjectAnalyzer), 1, false, true)
#13 src/Psalm/Internal/Cli/Psalm.php(376): Psalm\Internal\Analyzer\ProjectAnalyzer->check('/Volumes/kranke...', false)
#14 psalm(8): Psalm\Internal\Cli\Psalm::run(Array)
```

**Comment by ohader** [comment]
I've been able to isolate the problem:
https://psalm.dev/r/01a52d62ce

**Comment by ohader** [comment]
Another test, which does not output any exception on psalm.dev, but still fails:
https://psalm.dev/r/7120281c23

**Comment by orklah** [comment]
I'm not sure what to do here. Those chars are not allowed in a json but we use that for creating a hash. 

Is there a weird string compliant way to flatten an array for hashing? If the method is performant, it could be a plus, we probably create a lot of hashes on a single execution

**Comment by ohader** [comment]
In case the scalar value of that `if` statement should be kept, e.g. for static matching particular values, the only way to preserve non-UTF8 literals in a UTF8-scope, is to encode/serialize them again (not to be mixed with `utf8_encode` or similar, which just would guess the actual "charset").

Thus for the scenario in `Clause.php` (I did not check other places, where this is assigned or compared), it might be

```php
$this->hash = md5(serialize($possibility_strings));
```

* `serialize` to keep the structure (`array` items here)
* `md5` as hash/signature of the input literals is basically just the only aspect that's interesting
