### ISSUE TITLE
Crash on Symfony with first class callable

### ISSUE THREAD

**Issue by orklah** [vimeo/psalm#7839]
see https://github.com/symfony/symfony/pull/45927

```
Uncaught TypeError: Psalm\Internal\Analyzer\Statements\Expression\Call\ArgumentsAnalyzer::evaluateArbitraryParam(): Argument #2 ($arg) must be of type _HumbugBox22f8e3c05b97\PhpParser\Node\Arg, _HumbugBox22f8e3c05b97\PhpParser\Node\VariadicPlaceholder given, called in phar:///home/runner/work/symfony/symfony/vendor/psalm/phar/psalm.phar/src/Psalm/Internal/Analyzer/Statements/Expression/Call/ArgumentsAnalyzer.php on line 99 and defined in phar:///home/runner/work/symfony/symfony/vendor/psalm/phar/psalm.phar/src/Psalm/Internal/Analyzer/Statements/Expression/Call/ArgumentsAnalyzer.php:615
Stack trace:
#0 phar:///home/runner/work/symfony/symfony/vendor/psalm/phar/psalm.phar/src/Psalm/Internal/Analyzer/Statements/Expression/Call/ArgumentsAnalyzer.php(99): Psalm\Internal\Analyzer\Statements\Expression\Call\ArgumentsAnalyzer::evaluateArbitraryParam()
#1 phar:///home/runner/work/symfony/symfony/vendor/psalm/phar/psalm.phar/src/Psalm/Internal/Analyzer/Statements/Expression/Call/Method/AtomicMethodCallAnalyzer.php(305): Psalm\Internal\Analyzer\Statements\Expression\Call\ArgumentsAnalyzer::analyze()
#2 phar:///home/runner/work/symfony/symfony/vendor/psalm/phar/psalm.phar/src/Psalm/Internal/Analyzer/Statements/Expression/Call/Method/AtomicMethodCallAnalyzer.php(86): Psalm\Internal\Analyzer\Statements\Expression\Call\Method\AtomicMethodCallAnalyzer::handleInvalidClass()
#3 phar:///home/runner/work/symfony/symfony/vendor/psalm/phar/psalm.phar/src/Psalm/Internal/Analyzer/Statements/Expression/Call/MethodCallAnalyzer.php(104): Psalm\Internal\Analyzer\Statements\Expression\Call\Method\AtomicMethodCallAnalyzer::analyze()
#4 phar:///home/runner/work/symfony/symfony/vendor/psalm/phar/psalm.phar/src/Psalm/Internal/Analyzer/Statements/ExpressionAnalyzer.php(120): Psalm\Internal\Analyzer\Statements\Expression\Call\MethodCallAnalyzer::analyze()
#5 phar:///home/runner/work/symfony/symfony/vendor/psalm/phar/psalm.phar/src/Psalm/Internal/Analyzer/Statements/ExpressionAnalyzer.php(73): Psalm\Internal\Analyzer\Statements\ExpressionAnalyzer::handleExpression()
#6 phar:///home/runner/work/symfony/symfony/vendor/psalm/phar/psalm.phar/src/Psalm/Internal/Analyzer/Statements/Expression/AssignmentAnalyzer.php(171): Psalm\Internal\Analyzer\Statements\ExpressionAnalyzer::analyze()
#7 phar:///home/runner/work/symfony/symfony/vendor/psalm/phar/psalm.phar/src/Psalm/Internal/Analyzer/Statements/ExpressionAnalyzer.php(107): Psalm\Internal\Analyzer\Statements\Expression\AssignmentAnalyzer::analyze()
#8 phar:///home/runner/work/symfony/symfony/vendor/psalm/phar/psalm.phar/src/Psalm/Internal/Analyzer/Statements/ExpressionAnalyzer.php(73): Psalm\Internal\Analyzer\Statements\ExpressionAnalyzer::handleExpression()
#9 phar:///home/runner/work/symfony/symfony/vendor/psalm/phar/psalm.phar/src/Psalm/Internal/Analyzer/Statements/ReturnAnalyzer.php(94): Psalm\Internal\Analyzer\Statements\ExpressionAnalyzer::analyze()
#10 phar:///home/runner/work/symfony/symfony/vendor/psalm/phar/psalm.phar/src/Psalm/Internal/Analyzer/StatementsAnalyzer.php(380): Psalm\Internal\Analyzer\Statements\ReturnAnalyzer::analyze()
#11 phar:///home/runner/work/symfony/symfony/vendor/psalm/phar/psalm.phar/src/Psalm/Internal/Analyzer/StatementsAnalyzer.php(185): Psalm\Internal\Analyzer\StatementsAnalyzer::analyzeStatement()
#12 phar:///home/runner/work/symfony/symfony/vendor/psalm/phar/psalm.phar/src/Psalm/Internal/Analyzer/FunctionLikeAnalyzer.php(301): Psalm\Internal\Analyzer\StatementsAnalyzer->analyze()
#13 phar:///home/runner/work/symfony/symfony/vendor/psalm/phar/psalm.phar/src/Psalm/Internal/Analyzer/ClassAnalyzer.php(814): Psalm\Internal\Analyzer\FunctionLikeAnalyzer->analyze()
#14 phar:///home/runner/work/symfony/symfony/vendor/psalm/phar/psalm.phar/src/Psalm/Internal/Analyzer/ClassAnalyzer.php(240): Psalm\Internal\Analyzer\ClassAnalyzer->analyzeClassMethod()
#15 phar:///home/runner/work/symfony/symfony/vendor/psalm/phar/psalm.phar/src/Psalm/Internal/Analyzer/FileAnalyzer.php(184): Psalm\Internal\Analyzer\ClassAnalyzer->analyze()
#16 phar:///home/runner/work/symfony/symfony/vendor/psalm/phar/psalm.phar/src/Psalm/Internal/Codebase/Analyzer.php(284): Psalm\Internal\Analyzer\FileAnalyzer->analyze()
#17 phar:///home/runner/work/symfony/symfony/vendor/psalm/phar/psalm.phar/src/Psalm/Internal/Codebase/Analyzer.php(434): Psalm\Internal\Codebase\Analyzer->Psalm\Internal\Codebase\{closure}()
#18 phar:///home/runner/work/symfony/symfony/vendor/psalm/phar/psalm.phar/src/Psalm/Internal/Codebase/Analyzer.php(239): Psalm\Internal\Codebase\Analyzer->doAnalysis()
#19 phar:///home/runner/work/symfony/symfony/vendor/psalm/phar/psalm.phar/src/Psalm/Internal/Analyzer/ProjectAnalyzer.php(484): Psalm\Internal\Codebase\Analyzer->analyzeFiles()
#20 phar:///home/runner/work/symfony/symfony/vendor/psalm/phar/psalm.phar/src/Psalm/Internal/Cli/Psalm.php(277): Psalm\Internal\Analyzer\ProjectAnalyzer->check()
#21 phar:///home/runner/work/symfony/symfony/vendor/psalm/phar/psalm.phar/psalm(7): Psalm\Internal\Cli\Psalm::run()
#22 /home/runner/work/symfony/symfony/vendor/psalm/phar/psalm.phar(14): require('...')
#23 /home/runner/work/symfony/symfony/vendor/bin/psalm.phar(117): include('...')
```

**Comment by weirdan** [comment]
The crash is likely fixed in #8814, would you mind retesting this on the latest master?
