### ISSUE TITLE
Crash during closure return type check in an ignored file

### ISSUE THREAD

**Issue by weirdan** [vimeo/psalm#797]
https://github.com/weirdan/psalm-closure-in-an-ignored-file-bug

Checking this I get:
```
Analyzing files...
Getting /home/weirdan/src/t/src/a.php
Analyzing /home/weirdan/src/t/src/a.php
/home/weirdan/src/t/src/a.php:2
  checking src/b.php
/home/weirdan/src/t/src/b.php:2
/home/weirdan/src/t/src/b.php:2
PHP Fatal error:  Uncaught UnexpectedValueException: Expecting /home/weirdan/src/t/src/b.php:2:13:-:closure to have storage in /home/weirdan/src/t/src/a.php in /home/weirdan/src/psalm/src/Psalm/Codebase/Functions.php:74
Stack trace:
#0 /home/weirdan/src/psalm/src/Psalm/Checker/FunctionLikeChecker.php(838): Psalm\Codebase\Functions->getStorage(Object(Psalm\Checker\StatementsChecker), '/home/weirdan/s...')
#1 /home/weirdan/src/psalm/src/Psalm/Checker/Statements/ReturnChecker.php(107): Psalm\Checker\FunctionLikeChecker->getFunctionLikeStorage(Object(Psalm\Checker\StatementsChecker))
#2 /home/weirdan/src/psalm/src/Psalm/Checker/StatementsChecker.php(285): Psalm\Checker\Statements\ReturnChecker::analyze(Object(Psalm\Checker\StatementsChecker), Object(Psalm\Checker\ProjectChecker), Object(PhpParser\Node\Stmt\Return_), Object(Psalm\Context))
#3 /home/weirdan/src/psalm/src/Psalm/Checker/FunctionLikeChecker.php(454): Psalm\Checker\StatementsChecker->analyze(Array, Object(Psalm\Context), NULL, Object(Psalm\Context), true)
#4 /home/weird in /home/weirdan/src/psalm/src/Psalm/Codebase/Functions.php on line 74
```
with psalm dev-master@ 7c2ec06de890556ad2487ec91faf3f5ebb218074

**Comment by weirdan** [comment]
In practice, though, I've encountered this when I tried to ignore `vendor` folder.

**Comment by muglug** [comment]
The fix didn't have anything to do with ignored files, so you'll have to check that it actually fixes your bug (with `vendor` dir ignoring)

**Comment by weirdan** [comment]
The fix worked, thanks.
