### ISSUE TITLE
2.0.3 Throws error when parsing

### ISSUE THREAD

**Issue by ErikBooij** [vimeo/psalm#804]
I've just updated from Psalm 2.0.1 to 2.0.3

```bash
▶ composer analyze           
> psalm
Scanning files...
Analyzing files...
PHP Fatal error:  Uncaught Psalm\Exception\TypeParseTreeException: Cannot process colon without parent in /Users/erikbooij/Projects/PHP/project-name/vendor/vimeo/psalm/src/Psalm/Type/ParseTree.php:231
Stack trace:
#0 /Users/erikbooij/Projects/PHP/project-name/vendor/vimeo/psalm/src/Psalm/Type.php(111): Psalm\Type\ParseTree::createFromTokens(Array)
#1 /Users/erikbooij/Projects/PHP/project-name/vendor/vimeo/psalm/src/Psalm/Type.php(83): Psalm\Type::parseTokens(Array, false, Array)
#2 /Users/erikbooij/Projects/PHP/project-name/vendor/vimeo/psalm/src/Psalm/Checker/ClassChecker.php(551): Psalm\Type::parseString('_Users_erikbooi...')
#3 /Users/erikbooij/Projects/PHP/project-name/vendor/vimeo/psalm/src/Psalm/Checker/StatementsChecker.php(522): Psalm\Checker\ClassChecker->analyze(Object(Psalm\Context), NULL)
#4 /Users/erikbooij/Projects/PHP/project-name/vendor/vimeo/psalm/src/Psalm/Checker/Statements/Expression/Call/NewChecker.php(98): Psalm\Checker\StatementsChecker->analyze(Array, Object(Psalm\Context))
#5 /Users/erikbooij/Projects/PHP/cr in /Users/erikbooij/Projects/PHP/project-name/vendor/vimeo/psalm/src/Psalm/Type/ParseTree.php on line 231

Fatal error: Uncaught Psalm\Exception\TypeParseTreeException: Cannot process colon without parent in /Users/erikbooij/Projects/PHP/project-name/vendor/vimeo/psalm/src/Psalm/Type/ParseTree.php:231
Stack trace:
#0 /Users/erikbooij/Projects/PHP/project-name/vendor/vimeo/psalm/src/Psalm/Type.php(111): Psalm\Type\ParseTree::createFromTokens(Array)
#1 /Users/erikbooij/Projects/PHP/project-name/vendor/vimeo/psalm/src/Psalm/Type.php(83): Psalm\Type::parseTokens(Array, false, Array)
#2 /Users/erikbooij/Projects/PHP/project-name/vendor/vimeo/psalm/src/Psalm/Checker/ClassChecker.php(551): Psalm\Type::parseString('_Users_erikbooi...')
#3 /Users/erikbooij/Projects/PHP/project-name/vendor/vimeo/psalm/src/Psalm/Checker/StatementsChecker.php(522): Psalm\Checker\ClassChecker->analyze(Object(Psalm\Context), NULL)
#4 /Users/erikbooij/Projects/PHP/project-name/vendor/vimeo/psalm/src/Psalm/Checker/Statements/Expression/Call/NewChecker.php(98): Psalm\Checker\StatementsChecker->analyze(Array, Object(Psalm\Context))
#5 /Users/erikbooij/Projects/PHP/cr in /Users/erikbooij/Projects/PHP/project-name/vendor/vimeo/psalm/src/Psalm/Type/ParseTree.php on line 231
Script psalm handling the analyze event returned with error code 255
```

I've cleared the cache, but that didn't help. I'd would gladly offer more context, but I'm not sure how/what. I could `var_dump` some variables in that file during a run, if that helps.

**Comment by muglug** [comment]
Run with `--debug-by-line` to find out where it crashes

**Comment by muglug** [comment]
It's very likely to be https://github.com/vimeo/psalm/issues/797, though

**Comment by muglug** [comment]
Do you see the same bug on `dev-master`?

**Comment by ErikBooij** [comment]
No, I do not. That works fine! :) (although it does report three errors in the `vendor` folder.

**Comment by muglug** [comment]
Yeah, that was added in https://github.com/vimeo/psalm/releases/tag/2.0.2 (but not really telegraphed appropriately)

**Comment by muglug** [comment]
You can remove them by ignoring the vendor dir with `ignoreFiles`: https://github.com/vimeo/psalm/blob/master/docs/configuration.md#project-settings

**Comment by ErikBooij** [comment]
Cool, thanks a lot! Again.
