### ISSUE TITLE
Crashes during scan on spipu/html2pdf

### ISSUE THREAD

**Issue by weirdan** [vimeo/psalm#808]
```console
$ psalm --version
Psalm dev-master@26fa003fe2c16409a87b127a1eedcaf149437988
$ psalm --debug-by-line
Scanning files...
Using reflection to get metadata for Exception
Using reflection to get metadata for Serializable
Using reflection to get metadata for Countable
Using reflection to locate file for callback
Using reflection to get metadata for SeekableIterator
Using composer to locate file for Spipu\Html2Pdf\Html2Pdf
Scanning /home/weirdan/src/t/vendor/spipu/html2pdf/src/Html2Pdf.php
PHP Fatal error:  Uncaught InvalidArgumentException: Unrecognised parse tree type Psalm\Type\ParseTree\Root in /home/weirdan/.composer/vendor/vimeo/psalm/src/Psalm/Type.php:393
Stack trace:
#0 /home/weirdan/.composer/vendor/vimeo/psalm/src/Psalm/Type.php(246): Psalm\Type::getTypeFromTree(Object(Psalm\Type\ParseTree\Root), false, Array)
#1 [internal function]: Psalm\Type::Psalm\{closure}(Object(Psalm\Type\ParseTree\Root))
#2 /home/weirdan/.composer/vendor/vimeo/psalm/src/Psalm/Type.php(256): array_map(Object(Closure), Array)
#3 /home/weirdan/.composer/vendor/vimeo/psalm/src/Psalm/Type.php(112): Psalm\Type::getTypeFromTree(Object(Psalm\Type\ParseTree\IntersectionTree), false, Array)
#4 /home/weirdan/.composer/vendor/vimeo/psalm/src/Psalm/Visitor/DependencyFinderVisitor.php(1397): Psalm\Type::parseTokens(Array, false, Array)
#5 /home/weirdan/.composer/vendor/vimeo/psalm/src/Psalm/Visitor/DependencyFinderVisitor.php(1245): Psalm\Visitor\DependencyFinderVisitor->improveParamsFromDocblock(Object(Psalm\Storage\MethodStorage), Array,  in /home/weirdan/.composer/vendor/vimeo/psalm/src/Psalm/Type.php on line 393

Fatal error: Uncaught InvalidArgumentException: Unrecognised parse tree type Psalm\Type\ParseTree\Root in /home/weirdan/.composer/vendor/vimeo/psalm/src/Psalm/Type.php:393
Stack trace:
#0 /home/weirdan/.composer/vendor/vimeo/psalm/src/Psalm/Type.php(246): Psalm\Type::getTypeFromTree(Object(Psalm\Type\ParseTree\Root), false, Array)
#1 [internal function]: Psalm\Type::Psalm\{closure}(Object(Psalm\Type\ParseTree\Root))
#2 /home/weirdan/.composer/vendor/vimeo/psalm/src/Psalm/Type.php(256): array_map(Object(Closure), Array)
#3 /home/weirdan/.composer/vendor/vimeo/psalm/src/Psalm/Type.php(112): Psalm\Type::getTypeFromTree(Object(Psalm\Type\ParseTree\IntersectionTree), false, Array)
#4 /home/weirdan/.composer/vendor/vimeo/psalm/src/Psalm/Visitor/DependencyFinderVisitor.php(1397): Psalm\Type::parseTokens(Array, false, Array)
#5 /home/weirdan/.composer/vendor/vimeo/psalm/src/Psalm/Visitor/DependencyFinderVisitor.php(1245): Psalm\Visitor\DependencyFinderVisitor->improveParamsFromDocblock(Object(Psalm\Storage\MethodStorage), Array,  in /home/weirdan/.composer/vendor/vimeo/psalm/src/Psalm/Type.php on line 393
```

**Comment by weirdan** [comment]
2.0.3 is not affected (but crashes on that anon function in required file, fixed in master)

**Comment by weirdan** [comment]
It appears that the culprit is the docblock like this: `/** @return &array */` where ampersand is used to denote that the method returns reference.

**Comment by muglug** [comment]
Thanks!
