### ISSUE TITLE
Psalm erroring when trying to parse guzzle client

### ISSUE THREAD

**Issue by iwiznia** [vimeo/psalm#820]
I have a fairly large project that includes the [guzzle lib version 6.3.0](https://github.com/guzzle/guzzle/tree/6.3.0) and when psalm runs I am getting:
```
Parsing /vagrant/Web-Secure/vendor/guzzlehttp/guzzle/src/Client.php
Scanning /vagrant/Web-Secure/vendor/guzzlehttp/guzzle/src/Client.php

Notice: Undefined property: PhpParser\Node\Expr\Error::$name in /vagrant/Web-Secure/vendor/vimeo/psalm/src/Psalm/Visitor/DependencyFinderVisitor.php on line 1158

Fatal error: Uncaught UnexpectedValueException: Not expecting param name to be non-string in /vagrant/Web-Secure/vendor/vimeo/psalm/src/Psalm/Visitor/DependencyFinderVisitor.php:1159
Stack trace:
#0 /vagrant/Web-Secure/vendor/vimeo/psalm/src/Psalm/Visitor/DependencyFinderVisitor.php(732): Psalm\Visitor\DependencyFinderVisitor->getTranslatedFunctionParam(Object(PhpParser\Node\Param))
#1 /vagrant/Web-Secure/vendor/vimeo/psalm/src/Psalm/Visitor/DependencyFinderVisitor.php(273): Psalm\Visitor\DependencyFinderVisitor->registerFunctionLike(Object(PhpParser\Node\Stmt\Function_), true)
#2 /vagrant/Web-Secure/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(181): Psalm\Visitor\DependencyFinderVisitor->enterNode(Object(PhpParser\Node\Stmt\Class_))
#3 /vagrant/Web-Secure/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(108): PhpParser\NodeTraverser->traverseArray(Array)
#4 /vagrant/Web-Secure/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(200): PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Stmt\N in /vagrant/Web-Secure/vendor/vimeo/psalm/src/Psalm/Visitor/DependencyFinderVisitor.php on line 1159
```

Trying to figure out why it's failing, I see that if I remove [this](https://github.com/guzzle/guzzle/blob/6.3.0/src/Client.php#L11-L24), the error is gone.

I am not entirely sure the if the problem is in that library or in one of my usages of it... I have another project with a slightly different version of guzzle that parses with no problems (and has the same annotations).
Any ideas? 
I am running psalm with `--debug-by-line` but that's all the information I get out of it.

**Comment by muglug** [comment]
Are you running with latest `dev-master` (or 2.0.4, for that matter)? https://github.com/vimeo/psalm/issues/789 addressed this

**Comment by muglug** [comment]
Thanks for trying Psalm, by the way!

**Comment by iwiznia** [comment]
That did it, thank you very much!! Also thanks for an awesome project! 😄
