### ISSUE TITLE
Long match-statement results in TypeParseTreeException

### ISSUE THREAD

**Issue by Lorenzschaef** [vimeo/psalm#8464]
I have a match-statement with 104 branches and Psalm throws the Exception shown below. If I remove the last 3 branches, it works fine. The error message seems completely unrelated, as there is no closure or callable anywhere in that file.

### Code
```php
    public function getAppAction(AppActionId $id): AppAction
    {
        return $this->cache[$id->value] ?? $this->cache[$id->value] = match ($id) {
            AppActionId::WORKSPACE => new AppAction(
                $id,
                'workspace',
            ),
            AppActionId::PROJECTS => new AppAction(
                $id,
                'projects',
            ),

            // match statement goes on for 100 more branches...

            AppActionId::USER_ACTIVITIES => new AppAction(
                $id,
                'activities',
                'account',
            ),
            AppActionId::BACKGROUND_JOBS => new AppAction(
                $id,
                'background_jobs',
                '',
            ),
        };
    }
```

### Error
```
Uncaught Psalm\Exception\TypeParseTreeException: Parenthesis must be preceded by “Closure”, “callable”, "pure-callable" or a valid @method name in /www/vendor/vimeo/psalm/src/Psalm/Internal/Type/ParseTreeCreator.php:775
Stack trace:
#0 /www/vendor/vimeo/psalm/src/Psalm/Internal/Type/ParseTreeCreator.php(148): Psalm\Internal\Type\ParseTreeCreator->handleValue()
#1 /www/vendor/vimeo/psalm/src/Psalm/Internal/Type/TypeParser.php(136): Psalm\Internal\Type\ParseTreeCreator->create()
#2 /www/vendor/vimeo/psalm/src/Psalm/Type.php(82): Psalm\Internal\Type\TypeParser::parseTokens()
#3 /www/vendor/vimeo/psalm/src/Psalm/Internal/Type/SimpleNegatedAssertionReconciler.php(146): Psalm\Type::parseString()
#4 /www/vendor/vimeo/psalm/src/Psalm/Internal/Type/NegatedAssertionReconciler.php(91): Psalm\Internal\Type\SimpleNegatedAssertionReconciler::reconcile()
#5 /www/vendor/vimeo/psalm/src/Psalm/Internal/Type/AssertionReconciler.php(137): Psalm\Internal\Type\NegatedAssertionReconciler::reconcile()
#6 /www/vendor/vimeo/psalm/src/Psalm/Type/Reconciler.php(217): Psalm\Internal\Type\AssertionReconciler::reconcile()
#7 /www/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/Statements/Expression/MatchAnalyzer.php(258): Psalm\Type\Reconciler::reconcileKeyedTypes()
#8 /www/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/Statements/ExpressionAnalyzer.php(477): Psalm\Internal\Analyzer\Statements\Expression\MatchAnalyzer::analyze()
#9 /www/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/Statements/ExpressionAnalyzer.php(78): Psalm\Internal\Analyzer\Statements\ExpressionAnalyzer::handleExpression()
#10 /www/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/Statements/Expression/AssignmentAnalyzer.php(240): Psalm\Internal\Analyzer\Statements\ExpressionAnalyzer::analyze()
#11 /www/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/Statements/ExpressionAnalyzer.php(167): Psalm\Internal\Analyzer\Statements\Expression\AssignmentAnalyzer::analyze()
#12 /www/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/Statements/ExpressionAnalyzer.php(78): Psalm\Internal\Analyzer\Statements\ExpressionAnalyzer::handleExpression()
#13 /www/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/Statements/Expression/TernaryAnalyzer.php(216): Psalm\Internal\Analyzer\Statements\ExpressionAnalyzer::analyze()
#14 /www/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/Statements/ExpressionAnalyzer.php(303): Psalm\Internal\Analyzer\Statements\Expression\TernaryAnalyzer::analyze()
#15 /www/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/Statements/ExpressionAnalyzer.php(78): Psalm\Internal\Analyzer\Statements\ExpressionAnalyzer::handleExpression()
#16 /www/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/Statements/Expression/BinaryOp/CoalesceAnalyzer.php(79): Psalm\Internal\Analyzer\Statements\ExpressionAnalyzer::analyze()
#17 /www/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/Statements/Expression/BinaryOpAnalyzer.php(99): Psalm\Internal\Analyzer\Statements\Expression\BinaryOp\CoalesceAnalyzer::analyze()
#18 /www/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/Statements/ExpressionAnalyzer.php(266): Psalm\Internal\Analyzer\Statements\Expression\BinaryOpAnalyzer::analyze()
#19 /www/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/Statements/ExpressionAnalyzer.php(78): Psalm\Internal\Analyzer\Statements\ExpressionAnalyzer::handleExpression()
#20 /www/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/Statements/ReturnAnalyzer.php(156): Psalm\Internal\Analyzer\Statements\ExpressionAnalyzer::analyze()
#21 /www/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/StatementsAnalyzer.php(546): Psalm\Internal\Analyzer\Statements\ReturnAnalyzer::analyze()
#22 /www/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/StatementsAnalyzer.php(207): Psalm\Internal\Analyzer\StatementsAnalyzer::analyzeStatement()
#23 /www/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/FunctionLikeAnalyzer.php(476): Psalm\Internal\Analyzer\StatementsAnalyzer->analyze()
#24 /www/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/ClassAnalyzer.php(1788): Psalm\Internal\Analyzer\FunctionLikeAnalyzer->analyze()
#25 /www/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/ClassAnalyzer.php(425): Psalm\Internal\Analyzer\ClassAnalyzer->analyzeClassMethod()
#26 /www/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/FileAnalyzer.php(229): Psalm\Internal\Analyzer\ClassAnalyzer->analyze()
#27 /www/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Analyzer.php(362): Psalm\Internal\Analyzer\FileAnalyzer->analyze()
#28 /www/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Analyzer.php(619): Psalm\Internal\Codebase\Analyzer->Psalm\Internal\Codebase\{closure}()
#29 /www/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Analyzer.php(291): Psalm\Internal\Codebase\Analyzer->doAnalysis()
#30 /www/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/ProjectAnalyzer.php(686): Psalm\Internal\Codebase\Analyzer->analyzeFiles()
#31 /www/vendor/vimeo/psalm/src/Psalm/Internal/Cli/Psalm.php(373): Psalm\Internal\Analyzer\ProjectAnalyzer->check()
#32 /www/vendor/vimeo/psalm/psalm(7): Psalm\Internal\Cli\Psalm::run()
#33 /www/vendor/bin/psalm(120): include('...')
#34 {main}
```

**Comment by Lorenzschaef** [comment]
I could get a demo working with the same issue but a different error message. However, psalm.dev does not let me share the link, as "there is too much code".

Just copy this over:

```php
<?php

// if you remove case 102 from the enum and the match-statement, the error disappears.

class Test {
    public function __construct(private int $id) {}
}

enum Id: string {
    case ID_1 = '1';
    case ID_2 = '2';
    case ID_3 = '3';
    case ID_4 = '4';
    case ID_5 = '5';
    case ID_6 = '6';
    case ID_7 = '7';
    case ID_8 = '8';
    case ID_9 = '9';
    case ID_10 = '10';
    case ID_11 = '11';
    case ID_12 = '12';
    case ID_13 = '13';
    case ID_14 = '14';
    case ID_15 = '15';
    case ID_16 = '16';
    case ID_17 = '17';
    case ID_18 = '18';
    case ID_19 = '19';
    case ID_20 = '20';
    case ID_21 = '21';
    case ID_22 = '22';
    case ID_23 = '23';
    case ID_24 = '24';
    case ID_25 = '25';
    case ID_26 = '26';
    case ID_27 = '27';
    case ID_28 = '28';
    case ID_29 = '29';
    case ID_30 = '30';
    case ID_31 = '31';
    case ID_32 = '32';
    case ID_33 = '33';
    case ID_34 = '34';
    case ID_35 = '35';
    case ID_36 = '36';
    case ID_37 = '37';
    case ID_38 = '38';
    case ID_39 = '39';
    case ID_40 = '40';
    case ID_41 = '41';
    case ID_42 = '42';
    case ID_43 = '43';
    case ID_44 = '44';
    case ID_45 = '45';
    case ID_46 = '46';
    case ID_47 = '47';
    case ID_48 = '48';
    case ID_49 = '49';
    case ID_50 = '50';
    case ID_51 = '51';
    case ID_52 = '52';
    case ID_53 = '53';
    case ID_54 = '54';
    case ID_55 = '55';
    case ID_56 = '56';
    case ID_57 = '57';
    case ID_58 = '58';
    case ID_59 = '59';
    case ID_60 = '60';
    case ID_61 = '61';
    case ID_62 = '62';
    case ID_63 = '63';
    case ID_64 = '64';
    case ID_65 = '65';
    case ID_66 = '66';
    case ID_67 = '67';
    case ID_68 = '68';
    case ID_69 = '69';
    case ID_70 = '70';
    case ID_71 = '71';
    case ID_72 = '72';
    case ID_73 = '73';
    case ID_74 = '74';
    case ID_75 = '75';
    case ID_76 = '76';
    case ID_77 = '77';
    case ID_78 = '78';
    case ID_79 = '79';
    case ID_80 = '80';
    case ID_81 = '81';
    case ID_82 = '82';
    case ID_83 = '83';
    case ID_84 = '84';
    case ID_85 = '85';
    case ID_86 = '86';
    case ID_87 = '87';
    case ID_88 = '88';
    case ID_89 = '89';
    case ID_90 = '90';
    case ID_91 = '91';
    case ID_92 = '92';
    case ID_93 = '93';
    case ID_94 = '94';
    case ID_95 = '95';
    case ID_96 = '96';
    case ID_97 = '97';
    case ID_98 = '98';
    case ID_99 = '99';
    case ID_100 = '100';
    case ID_101 = '101';
    case ID_102 = '102';
}

function test (Id $a): Test
{
	return match ($a) {
        Id::ID_1 => new Test(1),
        Id::ID_2 => new Test(2),
        Id::ID_3 => new Test(3),
        Id::ID_4 => new Test(4),
        Id::ID_5 => new Test(5),
        Id::ID_6 => new Test(6),
        Id::ID_7 => new Test(7),
        Id::ID_8 => new Test(8),
        Id::ID_9 => new Test(9),
        Id::ID_10 => new Test(10),
        Id::ID_11 => new Test(11),
        Id::ID_12 => new Test(12),
        Id::ID_13 => new Test(13),
        Id::ID_14 => new Test(14),
        Id::ID_15 => new Test(15),
        Id::ID_16 => new Test(16),
        Id::ID_17 => new Test(17),
        Id::ID_18 => new Test(18),
        Id::ID_19 => new Test(19),
        Id::ID_20 => new Test(20),
        Id::ID_21 => new Test(21),
        Id::ID_22 => new Test(22),
        Id::ID_23 => new Test(23),
        Id::ID_24 => new Test(24),
        Id::ID_25 => new Test(25),
        Id::ID_26 => new Test(26),
        Id::ID_27 => new Test(27),
        Id::ID_28 => new Test(28),
        Id::ID_29 => new Test(29),
        Id::ID_30 => new Test(30),
        Id::ID_31 => new Test(31),
        Id::ID_32 => new Test(32),
        Id::ID_33 => new Test(33),
        Id::ID_34 => new Test(34),
        Id::ID_35 => new Test(35),
        Id::ID_36 => new Test(36),
        Id::ID_37 => new Test(37),
        Id::ID_38 => new Test(38),
        Id::ID_39 => new Test(39),
        Id::ID_40 => new Test(40),
        Id::ID_41 => new Test(41),
        Id::ID_42 => new Test(42),
        Id::ID_43 => new Test(43),
        Id::ID_44 => new Test(44),
        Id::ID_45 => new Test(45),
        Id::ID_46 => new Test(46),
        Id::ID_47 => new Test(47),
        Id::ID_48 => new Test(48),
        Id::ID_49 => new Test(49),
        Id::ID_50 => new Test(50),
        Id::ID_51 => new Test(51),
        Id::ID_52 => new Test(52),
        Id::ID_53 => new Test(53),
        Id::ID_54 => new Test(54),
        Id::ID_55 => new Test(55),
        Id::ID_56 => new Test(56),
        Id::ID_57 => new Test(57),
        Id::ID_58 => new Test(58),
        Id::ID_59 => new Test(59),
        Id::ID_60 => new Test(60),
        Id::ID_61 => new Test(61),
        Id::ID_62 => new Test(62),
        Id::ID_63 => new Test(63),
        Id::ID_64 => new Test(64),
        Id::ID_65 => new Test(65),
        Id::ID_66 => new Test(66),
        Id::ID_67 => new Test(67),
        Id::ID_68 => new Test(68),
        Id::ID_69 => new Test(69),
        Id::ID_70 => new Test(70),
        Id::ID_71 => new Test(71),
        Id::ID_72 => new Test(72),
        Id::ID_73 => new Test(73),
        Id::ID_74 => new Test(74),
        Id::ID_75 => new Test(75),
        Id::ID_76 => new Test(76),
        Id::ID_77 => new Test(77),
        Id::ID_78 => new Test(78),
        Id::ID_79 => new Test(79),
        Id::ID_80 => new Test(80),
        Id::ID_81 => new Test(81),
        Id::ID_82 => new Test(82),
        Id::ID_83 => new Test(83),
        Id::ID_84 => new Test(84),
        Id::ID_85 => new Test(85),
        Id::ID_86 => new Test(86),
        Id::ID_87 => new Test(87),
        Id::ID_88 => new Test(88),
        Id::ID_89 => new Test(89),
        Id::ID_90 => new Test(90),
        Id::ID_91 => new Test(91),
        Id::ID_92 => new Test(92),
        Id::ID_93 => new Test(93),
        Id::ID_94 => new Test(94),
        Id::ID_95 => new Test(95),
        Id::ID_96 => new Test(96),
        Id::ID_97 => new Test(97),
        Id::ID_98 => new Test(98),
        Id::ID_99 => new Test(99),
        Id::ID_100 => new Test(100),
        Id::ID_101 => new Test(101),
        Id::ID_102 => new Test(102),
	};
}

```

Psalm output:
```
ERROR: [UnhandledMatchCondition](https://psalm.dev/236) - 116:16 - This match expression is not exhaustive - consider values Id|enum(Id::ID_1)|enum(Id::ID_10)|enum(Id::ID_100)|enum(Id::ID_101)|enum(Id::ID_102)|enum(Id::ID_11)|enum(Id::ID_12)|enum(Id::ID_13)|enum(Id::ID_14)|enum(Id::ID_15)|enum(Id::ID_16)|enum(Id::ID_17)|enum(Id::ID_18)|enum(Id::ID_19)|enum(Id::ID_2)|enum(Id::ID_20)|enum(Id::ID_21)|enum(Id::ID_22)|enum(Id::ID_23)|enum(Id::ID_24)|enum(Id::ID_25)|enum(Id::ID_26)|enum(Id::ID_27)|enum(Id::ID_28)|enum(Id::ID_29)|enum(Id::ID_3)|enum(Id::ID_30)|enum(Id::ID_31)|enum(Id::ID_32)|enum(Id::ID_33)|enum(Id::ID_34)|enum(Id::ID_35)|enum(Id::ID_36)|enum(Id::ID_37)|enum(Id::ID_38)|enum(Id::ID_39)|enum(Id::ID_4)|enum(Id::ID_40)|enum(Id::ID_41)|enum(Id::ID_42)|enum(Id::ID_43)|enum(Id::ID_44)|enum(Id::ID_45)|enum(Id::ID_46)|enum(Id::ID_47)|enum(Id::ID_48)|enum(Id::ID_49)|enum(Id::ID_5)|enum(Id::ID_50)|enum(Id::ID_51)|enum(Id::ID_52)|enum(Id::ID_53)|enum(Id::ID_54)|enum(Id::ID_55)|enum(Id::ID_56)|enum(Id::ID_57)|enum(Id::ID_58)|enum(Id::ID_59)|enum(Id::ID_6)|enum(Id::ID_60)|enum(Id::ID_61)|enum(Id::ID_62)|enum(Id::ID_63)|enum(Id::ID_64)|enum(Id::ID_65)|enum(Id::ID_66)|enum(Id::ID_67)|enum(Id::ID_68)|enum(Id::ID_69)|enum(Id::ID_7)|enum(Id::ID_70)|enum(Id::ID_71)|enum(Id::ID_72)|enum(Id::ID_73)|enum(Id::ID_74)|enum(Id::ID_75)|enum(Id::ID_76)|enum(Id::ID_77)|enum(Id::ID_78)|enum(Id::ID_79)|enum(Id::ID_8)|enum(Id::ID_80)|enum(Id::ID_81)|enum(Id::ID_82)|enum(Id::ID_83)|enum(Id::ID_84)|enum(Id::ID_85)|enum(Id::ID_86)|enum(Id::ID_87)|enum(Id::ID_88)|enum(Id::ID_89)|enum(Id::ID_9)|enum(Id::ID_90)|enum(Id::ID_91)|enum(Id::ID_92)|enum(Id::ID_93)|enum(Id::ID_94)|enum(Id::ID_95)|enum(Id::ID_96)|enum(Id::ID_97)|enum(Id::ID_98)|enum(Id::ID_99)
```
