### ISSUE TITLE
Uncaught InvalidArgumentException with ffi\cdata

### ISSUE THREAD

**Issue by pirast** [vimeo/psalm#8612]
Hi !

Psalm throws Uncaught InvalidArgumentException when using some functions of PHP FFI.
In my tests this was the case with FFI::new and FFI::string.

As it cannot really be reproduced on psalm.dev (https://psalm.dev/r/012cdba7d1) I have setup a minimal repo demonstrating the problem: https://github.com/pirast/psalm-uncaught-InvalidArgumentException-with-ffi-cdata

**Comment by orklah** [comment]
Hi!

Psalm doesn't seem to currently have definitions for FFI. If you have errors, it means Psalm is probably using Reflection in order to retrieve signatures directly from the extension. 

The fact that you don't reproduce on psalm.dev is because we don't have this extension installed so Psalm has no signature whatsoever.

Signatures retrieved through Reflection may be wrong or invalid, in this case, I'd suggest providing some to Psalm (we won't need Reflection then). You can do that by creating a new file like this one: https://github.com/vimeo/psalm/blob/master/stubs/extensions/gmp.phpstub (please target the master branch)

**Comment by LeSuisse** [comment]
Hi,

Is it not a bit strange that it ends up crashing instead of throwing an errors/warnings?

https://github.com/pirast/psalm-uncaught-InvalidArgumentException-with-ffi-cdata/actions/runs/3314112122/jobs/5472964336

```
Uncaught InvalidArgumentException: Could not get class storage for ffi\ctype in /home/runner/work/psalm-uncaught-InvalidArgumentException-with-ffi-cdata/psalm-uncaught-InvalidArgumentException-with-ffi-cdata/vendor/vimeo/psalm/src/Psalm/Internal/Provider/ClassLikeStorageProvider.php:46
Stack trace:
#0 /home/runner/work/psalm-uncaught-InvalidArgumentException-with-ffi-cdata/psalm-uncaught-InvalidArgumentException-with-ffi-cdata/vendor/vimeo/psalm/src/Psalm/Internal/Type/TypeExpander.php(607): Psalm\Internal\Provider\ClassLikeStorageProvider->get()
#1 /home/runner/work/psalm-uncaught-InvalidArgumentException-with-ffi-cdata/psalm-uncaught-InvalidArgumentException-with-ffi-cdata/vendor/vimeo/psalm/src/Psalm/Internal/Type/TypeExpander.php(178): Psalm\Internal\Type\TypeExpander::expandNamedObject()
#2 /home/runner/work/psalm-uncaught-InvalidArgumentException-with-ffi-cdata/psalm-uncaught-InvalidArgumentException-with-ffi-cdata/vendor/vimeo/psalm/src/Psalm/Internal/Type/TypeExpander.php(82): Psalm\Internal\Type\TypeExpander::expandAtomic()
#3 /home/runner/work/psalm-uncaught-InvalidArgumentException-with-ffi-cdata/psalm-uncaught-InvalidArgumentException-with-ffi-cdata/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/Statements/Expression/Call/ArgumentAnalyzer.php(284): Psalm\Internal\Type\TypeExpander::expandUnion()
#4 /home/runner/work/psalm-uncaught-InvalidArgumentException-with-ffi-cdata/psalm-uncaught-InvalidArgumentException-with-ffi-cdata/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/Statements/Expression/Call/ArgumentAnalyzer.php(195): Psalm\Internal\Analyzer\Statements\Expression\Call\ArgumentAnalyzer::checkFunctionLikeTypeMatches()
#5 /home/runner/work/psalm-uncaught-InvalidArgumentException-with-ffi-cdata/psalm-uncaught-InvalidArgumentException-with-ffi-cdata/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/Statements/Expression/Call/ArgumentsAnalyzer.php(828): Psalm\Internal\Analyzer\Statements\Expression\Call\ArgumentAnalyzer::checkArgumentMatches()
#6 /home/runner/work/psalm-uncaught-InvalidArgumentException-with-ffi-cdata/psalm-uncaught-InvalidArgumentException-with-ffi-cdata/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/Statements/Expression/CallAnalyzer.php(357): Psalm\Internal\Analyzer\Statements\Expression\Call\ArgumentsAnalyzer::checkArgumentsMatch()
#7 /home/runner/work/psalm-uncaught-InvalidArgumentException-with-ffi-cdata/psalm-uncaught-InvalidArgumentException-with-ffi-cdata/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/Statements/Expression/Call/StaticMethod/ExistingAtomicStaticCallAnalyzer.php(191): Psalm\Internal\Analyzer\Statements\Expression\CallAnalyzer::checkMethodArgs()
#8 /home/runner/work/psalm-uncaught-InvalidArgumentException-with-ffi-cdata/psalm-uncaught-InvalidArgumentException-with-ffi-cdata/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/Statements/Expression/Call/StaticMethod/AtomicStaticCallAnalyzer.php(877): Psalm\Internal\Analyzer\Statements\Expression\Call\StaticMethod\ExistingAtomicStaticCallAnalyzer::analyze()
#9 /home/runner/work/psalm-uncaught-InvalidArgumentException-with-ffi-cdata/psalm-uncaught-InvalidArgumentException-with-ffi-cdata/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/Statements/Expression/Call/StaticMethod/AtomicStaticCallAnalyzer.php(202): Psalm\Internal\Analyzer\Statements\Expression\Call\StaticMethod\AtomicStaticCallAnalyzer::handleNamedCall()
#10 /home/runner/work/psalm-uncaught-InvalidArgumentException-with-ffi-cdata/psalm-uncaught-InvalidArgumentException-with-ffi-cdata/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/Statements/Expression/Call/StaticCallAnalyzer.php(215): Psalm\Internal\Analyzer\Statements\Expression\Call\StaticMethod\AtomicStaticCallAnalyzer::analyze()
#11 /home/runner/work/psalm-uncaught-InvalidArgumentException-with-ffi-cdata/psalm-uncaught-InvalidArgumentException-with-ffi-cdata/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/Statements/ExpressionAnalyzer.php(190): Psalm\Internal\Analyzer\Statements\Expression\Call\StaticCallAnalyzer::analyze()
#12 /home/runner/work/psalm-uncaught-InvalidArgumentException-with-ffi-cdata/psalm-uncaught-InvalidArgumentException-with-ffi-cdata/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/Statements/ExpressionAnalyzer.php(78): Psalm\Internal\Analyzer\Statements\ExpressionAnalyzer::handleExpression()
#13 /home/runner/work/psalm-uncaught-InvalidArgumentException-with-ffi-cdata/psalm-uncaught-InvalidArgumentException-with-ffi-cdata/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/Statements/Expression/AssignmentAnalyzer.php(240): Psalm\Internal\Analyzer\Statements\ExpressionAnalyzer::analyze()
#14 /home/runner/work/psalm-uncaught-InvalidArgumentException-with-ffi-cdata/psalm-uncaught-InvalidArgumentException-with-ffi-cdata/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/Statements/ExpressionAnalyzer.php(167): Psalm\Internal\Analyzer\Statements\Expression\AssignmentAnalyzer::analyze()
#15 /home/runner/work/psalm-uncaught-InvalidArgumentException-with-ffi-cdata/psalm-uncaught-InvalidArgumentException-with-ffi-cdata/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/Statements/ExpressionAnalyzer.php(78): Psalm\Internal\Analyzer\Statements\ExpressionAnalyzer::handleExpression()
#16 /home/runner/work/psalm-uncaught-InvalidArgumentException-with-ffi-cdata/psalm-uncaught-InvalidArgumentException-with-ffi-cdata/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/StatementsAnalyzer.php(572): Psalm\Internal\Analyzer\Statements\ExpressionAnalyzer::analyze()
#17 /home/runner/work/psalm-uncaught-InvalidArgumentException-with-ffi-cdata/psalm-uncaught-InvalidArgumentException-with-ffi-cdata/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/StatementsAnalyzer.php(207): Psalm\Internal\Analyzer\StatementsAnalyzer::analyzeStatement()
#18 /home/runner/work/psalm-uncaught-InvalidArgumentException-with-ffi-cdata/psalm-uncaught-InvalidArgumentException-with-ffi-cdata/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/FileAnalyzer.php(205): Psalm\Internal\Analyzer\StatementsAnalyzer->analyze()
#19 /home/runner/work/psalm-uncaught-InvalidArgumentException-with-ffi-cdata/psalm-uncaught-InvalidArgumentException-with-ffi-cdata/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Analyzer.php(362): Psalm\Internal\Analyzer\FileAnalyzer->analyze()
#20 /home/runner/work/psalm-uncaught-InvalidArgumentException-with-ffi-cdata/psalm-uncaught-InvalidArgumentException-with-ffi-cdata/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Analyzer.php(619): Psalm\Internal\Codebase\Analyzer->Psalm\Internal\Codebase\{closure}()
#21 /home/runner/work/psalm-uncaught-InvalidArgumentException-with-ffi-cdata/psalm-uncaught-InvalidArgumentException-with-ffi-cdata/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Analyzer.php(291): Psalm\Internal\Codebase\Analyzer->doAnalysis()
#22 /home/runner/work/psalm-uncaught-InvalidArgumentException-with-ffi-cdata/psalm-uncaught-InvalidArgumentException-with-ffi-cdata/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/ProjectAnalyzer.php(691): Psalm\Internal\Codebase\Analyzer->analyzeFiles()
#23 /home/runner/work/psalm-uncaught-InvalidArgumentException-with-ffi-cdata/psalm-uncaught-InvalidArgumentException-with-ffi-cdata/vendor/vimeo/psalm/src/Psalm/Internal/Cli/Psalm.php(373): Psalm\Internal\Analyzer\ProjectAnalyzer->check()
#24 /home/runner/work/psalm-uncaught-InvalidArgumentException-with-ffi-cdata/psalm-uncaught-InvalidArgumentException-with-ffi-cdata/vendor/vimeo/psalm/psalm(7): Psalm\Internal\Cli\Psalm::run()
#25 /home/runner/work/psalm-uncaught-InvalidArgumentException-with-ffi-cdata/psalm-uncaught-InvalidArgumentException-with-ffi-cdata/vendor/bin/psalm(120): include('...')
#26 {main}
(Psalm 4.29.0@7ec5ffbd5f68ae03782d7fd33fff0c45a69f95b3 crashed due to an uncaught Throwable)
```

Should not we wrap those lines with a `if ($codebase->classlike_storage_provider->has($value)) { /* ... */ }` in order to avoid this?

https://github.com/vimeo/psalm/blob/b739b67080781e880529c18f263d8c19e2f22597/src/Psalm/Internal/Type/TypeExpander.php#L606-L632

Nonetheless we likely need the stub anyway.

**Comment by orklah** [comment]
Possibly for the has, though I'm not sure Psalm would manage to get back on its feet after trying to resolve templates with unknown classes. Maybe just to add a better error...

**Comment by orklah** [comment]
This was fixed
