### ISSUE TITLE
"Could not get class storage for SodiumException" (for polyfill library, sodium_compat)

### ISSUE THREAD

**Issue by paragonie-scott** [vimeo/psalm#862]
https://travis-ci.org/paragonie/sodium_compat/jobs/400094927

```
PHP Fatal error:  Uncaught InvalidArgumentException: Could not get class storage for SodiumException in /home/travis/build/paragonie/sodium_compat/vendor/vimeo/psalm/src/Psalm/Provider/ClassLikeStorageProvider.php:35
Stack trace:
#0 /home/travis/build/paragonie/sodium_compat/vendor/vimeo/psalm/src/Psalm/Checker/ClassLikeChecker.php(251): Psalm\Provider\ClassLikeStorageProvider->get('SodiumException')
#1 /home/travis/build/paragonie/sodium_compat/vendor/vimeo/psalm/src/Psalm/Checker/Statements/Expression/Call/NewChecker.php(61): Psalm\Checker\ClassLikeChecker::checkFullyQualifiedClassLikeName(Object(Psalm\Checker\StatementsChecker), 'SodiumException', Object(Psalm\CodeLocation), Array, false)
#2 /home/travis/build/paragonie/sodium_compat/vendor/vimeo/psalm/src/Psalm/Checker/Statements/ExpressionChecker.php(259): Psalm\Checker\Statements\Expression\Call\NewChecker::analyze(Object(Psalm\Checker\StatementsChecker), Object(PhpParser\Node\Expr\New_), Object(Psalm\Context))
#3 /home/travis/build/paragonie/sodium_compat/vendor/vimeo/p in /home/travis/build/paragonie/sodium_compat/vendor/vimeo/psalm/src/Psalm/Provider/ClassLikeStorageProvider.php on line 35
```

**Comment by muglug** [comment]
Ok, I'm checking with latest master to see if that fixes things

**Comment by muglug** [comment]
Fixed in https://github.com/vimeo/psalm/commit/5cb23b7f473d6ab1d42aacf985ef166ba2ea667e. I'll push out a new release of both branches later today.

**Comment by pretzlaw** [comment]
Hello there,

would you mind fixing that in version ^1.1 too?
I am experiencing the same issue there.

We still rely on 1.1 because it supports PHP 5.6 and (unfortunately) some customers have that.

Cheers!
