### ISSUE TITLE
InvalidArgumentException Could not get class storage for curlhandle

### ISSUE THREAD

**Issue by Crell** [vimeo/psalm#8640]
Using Psalm for the first time myself, although on a codebase (Laravel-based) that has been used with Psalm before.  Default settings, level 7 (guessed by Psalm).

I'm getting the following exception thrown:

```
Uncaught Exception: InvalidArgumentException Could not get class storage for curlhandle
Emitted in /var/www/html/vendor/vimeo/psalm/src/Psalm/Internal/Provider/ClassLikeStorageProvider.php:46
Stack trace in the forked worker:
#0 /var/www/html/vendor/vimeo/psalm/src/Psalm/Internal/Type/TypeExpander.php(607): Psalm\Internal\Provider\ClassLikeStorageProvider->get()
#1 /var/www/html/vendor/vimeo/psalm/src/Psalm/Internal/Type/TypeExpander.php(178): Psalm\Internal\Type\TypeExpander::expandNamedObject()
#2 /var/www/html/vendor/vimeo/psalm/src/Psalm/Internal/Type/TypeExpander.php(82): Psalm\Internal\Type\TypeExpander::expandAtomic()
...
```

This happens even when skipping the cache (as suggested in [#3671](https://github.com/vimeo/psalm/issues/3671)), and even when specifying only one thread.  I have confirmed that curl is installed (according to `php -m`).  Running on PHP 8.1.

Any idea what the issue could be?

**Comment by Crell** [comment]
No, I cannot reproduce it on psalm.dev, bot. 😄

**Comment by weirdan** [comment]
Do you have `CurlHandle` available in your docker container (judging by the paths in stacktrace)? What does `php --rc CurlHandle` output when run from inside the container?

**Comment by weirdan** [comment]
Also, what does Psalm says about the PHP version it targets for analysis? Look for a string like `Target PHP version: 8.0 (inferred from composer.json)` in Psalm output. If it specifies anything lower than 8.0 (the version in which `CurlHandle` was introduced) then that would likely be the culprit.

**Comment by Crell** [comment]
Psalm reports it's using PHP 8.1, which is what I have specified in composer.json.  

`php --rc CurlHandle` finds one internal class, which seems to have no properties or methods.  (I think that's weirdly correct for this case, but not certain of that.)

**Comment by weirdan** [comment]
To cover all the bases, do you use laravel plugin? This can be checked by running `psalm-plugin` in the directory where you usually run Psalm.

**Comment by Crell** [comment]
I do not.  Should I in this case?

**Comment by Crell** [comment]
Update: I tried installing the laravel plugin, and that seems to have resolved the curl issue.  I... do not comprehend how, but that error has gone away.  Now I'm just getting a file-not-found issue from Laravel itself that I cannot explain, but is not a psalm-specific issue.  Though curiously, PHPStan doesn't seem to complain about it.  I have no explanation.

**Comment by weirdan** [comment]
> I do not. Should I in this case?

I would advise doing so. Laravel employs a lot of funny dynamic tricks (e.g. facades) that are a pain to work with without that plugin.
