### ISSUE TITLE
 Could not get class storage when using intersection types with Psalm v5

### ISSUE THREAD

**Issue by greg0ire** [vimeo/psalm#8772]
I get the following issue with v5.0.0-rc1 and with the master branch as well.

```
Target PHP version: 8.1 (set by config file) Extensions enabled:  (unsupported extensions: ctype)
Scanning files...
Uncaught InvalidArgumentException: Could not get class storage for doctrine\common\collections\selectable in /home/greg/dev/doctrine-orm/major/vendor/vimeo/psalm/src/Psalm/Internal/Provider/ClassLikeStorageProvider.php:48
Stack trace:
#0 /home/greg/dev/doctrine-orm/major/vendor/vimeo/psalm/src/Psalm/Type.php(917): Psalm\Internal\Provider\ClassLikeStorageProvider->get()
#1 /home/greg/dev/doctrine-orm/major/vendor/vimeo/psalm/src/Psalm/Type.php(848): Psalm\Type::mayHaveIntersection()
#2 /home/greg/dev/doctrine-orm/major/vendor/vimeo/psalm/src/Psalm/Type.php(704): Psalm\Type::intersectAtomicTypes()
#3 /home/greg/dev/doctrine-orm/major/vendor/vimeo/psalm/src/Psalm/Internal/PhpVisitor/Reflector/TypeHintResolver.php(113): Psalm\Type::intersectUnionTypes()
#4 /home/greg/dev/doctrine-orm/major/vendor/vimeo/psalm/src/Psalm/Internal/PhpVisitor/Reflector/FunctionLikeNodeScanner.php(441): Psalm\Internal\PhpVisitor\Reflector\TypeHintResolver::resolve()
#5 /home/greg/dev/doctrine-orm/major/vendor/vimeo/psalm/src/Psalm/Internal/PhpVisitor/ReflectorVisitor.php(236): Psalm\Internal\PhpVisitor\Reflector\FunctionLikeNodeScanner->start()
#6 /home/greg/dev/doctrine-orm/major/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(200): Psalm\Internal\PhpVisitor\ReflectorVisitor->enterNode()
#7 /home/greg/dev/doctrine-orm/major/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(114): PhpParser\NodeTraverser->traverseArray()
#8 /home/greg/dev/doctrine-orm/major/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(223): PhpParser\NodeTraverser->traverseNode()
#9 /home/greg/dev/doctrine-orm/major/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(114): PhpParser\NodeTraverser->traverseArray()
#10 /home/greg/dev/doctrine-orm/major/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(223): PhpParser\NodeTraverser->traverseNode()
#11 /home/greg/dev/doctrine-orm/major/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(91): PhpParser\NodeTraverser->traverseArray()
#12 /home/greg/dev/doctrine-orm/major/vendor/vimeo/psalm/src/Psalm/Internal/Scanner/FileScanner.php(88): PhpParser\NodeTraverser->traverse()
#13 /home/greg/dev/doctrine-orm/major/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Scanner.php(582): Psalm\Internal\Scanner\FileScanner->scan()
#14 /home/greg/dev/doctrine-orm/major/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Scanner.php(810): Psalm\Internal\Codebase\Scanner->scanFile()
#15 /home/greg/dev/doctrine-orm/major/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Scanner.php(452): Psalm\Internal\Codebase\Scanner->scanAPath()
#16 /home/greg/dev/doctrine-orm/major/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Scanner.php(305): Psalm\Internal\Codebase\Scanner->scanFilePaths()
#17 /home/greg/dev/doctrine-orm/major/vendor/vimeo/psalm/src/Psalm/Codebase.php(503): Psalm\Internal\Codebase\Scanner->scanFiles()
#18 /home/greg/dev/doctrine-orm/major/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/ProjectAnalyzer.php(662): Psalm\Codebase->scanFiles()
#19 /home/greg/dev/doctrine-orm/major/vendor/vimeo/psalm/src/Psalm/Internal/Cli/Psalm.php(375): Psalm\Internal\Analyzer\ProjectAnalyzer->check()
#20 /home/greg/dev/doctrine-orm/major/vendor/vimeo/psalm/psalm(9): Psalm\Internal\Cli\Psalm::run()
#21 /home/greg/dev/doctrine-orm/major/vendor/bin/psalm(120): include('...')
#22 {main}
(Psalm 5.0.0-rc1@8f39de9001c995eb203cee3399307570f322076a crashed due to an uncaught Throwable)
```

- failing job: https://github.com/doctrine/orm/actions/runs/3554041371/jobs/5969902463
- pull request: https://github.com/doctrine/orm/pull/10255

## Reproducer script

```shell
git clone git@github.com:greg0ire/doctrine-orm.git
cd doctrine-orm
composer update
vendor/bin/psalm
```

**Comment by othercorey** [comment]
We are experiencing the same issue with cakephp:

```
Uncaught InvalidArgumentException: Could not get class storage for cake\cache\cacheengineinterface in phar:///home/runner/work/cakephp/cakephp/vendor/psalm/phar/psalm.phar/src/Psalm/Internal/Provider/ClassLikeStorageProvider.php:42
Stack trace:
#0 phar:///home/runner/work/cakephp/cakephp/vendor/psalm/phar/psalm.phar/src/Psalm/Type.php(660): Psalm\Internal\Provider\ClassLikeStorageProvider->get()
#1 phar:///home/runner/work/cakephp/cakephp/vendor/psalm/phar/psalm.phar/src/Psalm/Type.php(617): Psalm\Type::mayHaveIntersection()
#2 phar:///home/runner/work/cakephp/cakephp/vendor/psalm/phar/psalm.phar/src/Psalm/Type.php(524): Psalm\Type::intersectAtomicTypes()
#3 phar:///home/runner/work/cakephp/cakephp/vendor/psalm/phar/psalm.phar/src/Psalm/Internal/PhpVisitor/Reflector/TypeHintResolver.php(62): Psalm\Type::intersectUnionTypes()
#4 phar:///home/runner/work/cakephp/cakephp/vendor/psalm/phar/psalm.phar/src/Psalm/Internal/PhpVisitor/Reflector/FunctionLikeNodeScanner.php(274): Psalm\Internal\PhpVisitor\Reflector\TypeHintResolver::resolve()
#5 phar:///home/runner/work/cakephp/cakephp/vendor/psalm/phar/psalm.phar/src/Psalm/Internal/PhpVisitor/ReflectorVisitor.php(178): Psalm\Internal\PhpVisitor\Reflector\FunctionLikeNodeScanner->start()
#6 phar:///home/runner/work/cakephp/cakephp/vendor/psalm/phar/psalm.phar/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(176): Psalm\Internal\PhpVisitor\ReflectorVisitor->enterNode()
#7 phar:///home/runner/work/cakephp/cakephp/vendor/psalm/phar/psalm.phar/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(105): _HumbugBox438c463ab5e0\PhpParser\NodeTraverser->traverseArray()
#8 phar:///home/runner/work/cakephp/cakephp/vendor/psalm/phar/psalm.phar/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(196): _HumbugBox438c463ab5e0\PhpParser\NodeTraverser->traverseNode()
#9 phar:///home/runner/work/cakephp/cakephp/vendor/psalm/phar/psalm.phar/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(105): _HumbugBox438c463ab5e0\PhpParser\NodeTraverser->traverseArray()
#10 phar:///home/runner/work/cakephp/cakephp/vendor/psalm/phar/psalm.phar/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(196): _HumbugBox438c463ab5e0\PhpParser\NodeTraverser->traverseNode()
#[11](https://github.com/cakephp/cakephp/actions/runs/3555703960/jobs/5972547009#step:9:12) phar:///home/runner/work/cakephp/cakephp/vendor/psalm/phar/psalm.phar/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(85): _HumbugBox438c463ab5e0\PhpParser\NodeTraverser->traverseArray()
#[12](https://github.com/cakephp/cakephp/actions/runs/3555703960/jobs/5972547009#step:9:13) phar:///home/runner/work/cakephp/cakephp/vendor/psalm/phar/psalm.phar/src/Psalm/Internal/Scanner/FileScanner.php(60): _HumbugBox438c463ab5e0\PhpParser\NodeTraverser->traverse()
#[13](https://github.com/cakephp/cakephp/actions/runs/3555703960/jobs/5972547009#step:9:14) phar:///home/runner/work/cakephp/cakephp/vendor/psalm/phar/psalm.phar/src/Psalm/Internal/Codebase/Scanner.php(423): Psalm\Internal\Scanner\FileScanner->scan()
#[14](https://github.com/cakephp/cakephp/actions/runs/3555703960/jobs/5972547009#step:9:15) phar:///home/runner/work/cakephp/cakephp/vendor/psalm/phar/psalm.phar/src/Psalm/Internal/Codebase/Scanner.php(573): Psalm\Internal\Codebase\Scanner->scanFile()
#[15](https://github.com/cakephp/cakephp/actions/runs/3555703960/jobs/5972547009#step:9:16) phar:///home/runner/work/cakephp/cakephp/vendor/psalm/phar/psalm.phar/src/Psalm/Internal/Codebase/Scanner.php(335): Psalm\Internal\Codebase\Scanner->scanAPath()
#[16](https://github.com/cakephp/cakephp/actions/runs/3555703960/jobs/5972547009#step:9:17) phar:///home/runner/work/cakephp/cakephp/vendor/psalm/phar/psalm.phar/src/Psalm/Internal/Codebase/Scanner.php(245): Psalm\Internal\Codebase\Scanner->scanFilePaths()
#[17](https://github.com/cakephp/cakephp/actions/runs/3555703960/jobs/5972547009#step:9:18) phar:///home/runner/work/cakephp/cakephp/vendor/psalm/phar/psalm.phar/src/Psalm/Config.php(1716): Psalm\Internal\Codebase\Scanner->scanFiles()
```

**Comment by orklah** [comment]
It may be the same issue as https://github.com/vimeo/psalm/issues/7520

Could you try flipping the intersection please?

**Comment by greg0ire** [comment]
Flipping the intersection results in a flipped message:

```
Target PHP version: 8.1 (set by config file) Extensions enabled:  (unsupported extensions: ctype)
Scanning files...
Uncaught InvalidArgumentException: Could not get class storage for doctrine\common\collections\readablecollection in /home/greg/dev/doctrine-orm/major/vendor/vimeo/psalm/src/Psalm/Internal/Provider/ClassLikeStorageProvider.php:48
Stack trace:
#0 /home/greg/dev/doctrine-orm/major/vendor/vimeo/psalm/src/Psalm/Type.php(917): Psalm\Internal\Provider\ClassLikeStorageProvider->get()
#1 /home/greg/dev/doctrine-orm/major/vendor/vimeo/psalm/src/Psalm/Type.php(848): Psalm\Type::mayHaveIntersection()
#2 /home/greg/dev/doctrine-orm/major/vendor/vimeo/psalm/src/Psalm/Type.php(704): Psalm\Type::intersectAtomicTypes()
#3 /home/greg/dev/doctrine-orm/major/vendor/vimeo/psalm/src/Psalm/Internal/PhpVisitor/Reflector/TypeHintResolver.php(113): Psalm\Type::intersectUnionTypes()
#4 /home/greg/dev/doctrine-orm/major/vendor/vimeo/psalm/src/Psalm/Internal/PhpVisitor/Reflector/FunctionLikeNodeScanner.php(441): Psalm\Internal\PhpVisitor\Reflector\TypeHintResolver::resolve()
#5 /home/greg/dev/doctrine-orm/major/vendor/vimeo/psalm/src/Psalm/Internal/PhpVisitor/ReflectorVisitor.php(236): Psalm\Internal\PhpVisitor\Reflector\FunctionLikeNodeScanner->start()
#6 /home/greg/dev/doctrine-orm/major/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(200): Psalm\Internal\PhpVisitor\ReflectorVisitor->enterNode()
#7 /home/greg/dev/doctrine-orm/major/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(114): PhpParser\NodeTraverser->traverseArray()
#8 /home/greg/dev/doctrine-orm/major/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(223): PhpParser\NodeTraverser->traverseNode()
#9 /home/greg/dev/doctrine-orm/major/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(114): PhpParser\NodeTraverser->traverseArray()
#10 /home/greg/dev/doctrine-orm/major/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(223): PhpParser\NodeTraverser->traverseNode()
#11 /home/greg/dev/doctrine-orm/major/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(91): PhpParser\NodeTraverser->traverseArray()
#12 /home/greg/dev/doctrine-orm/major/vendor/vimeo/psalm/src/Psalm/Internal/Scanner/FileScanner.php(88): PhpParser\NodeTraverser->traverse()
#13 /home/greg/dev/doctrine-orm/major/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Scanner.php(582): Psalm\Internal\Scanner\FileScanner->scan()
#14 /home/greg/dev/doctrine-orm/major/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Scanner.php(810): Psalm\Internal\Codebase\Scanner->scanFile()
#15 /home/greg/dev/doctrine-orm/major/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Scanner.php(452): Psalm\Internal\Codebase\Scanner->scanAPath()
#16 /home/greg/dev/doctrine-orm/major/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Scanner.php(305): Psalm\Internal\Codebase\Scanner->scanFilePaths()
#17 /home/greg/dev/doctrine-orm/major/vendor/vimeo/psalm/src/Psalm/Codebase.php(503): Psalm\Internal\Codebase\Scanner->scanFiles()
#18 /home/greg/dev/doctrine-orm/major/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/ProjectAnalyzer.php(662): Psalm\Codebase->scanFiles()
#19 /home/greg/dev/doctrine-orm/major/vendor/vimeo/psalm/src/Psalm/Internal/Cli/Psalm.php(375): Psalm\Internal\Analyzer\ProjectAnalyzer->check()
#20 /home/greg/dev/doctrine-orm/major/vendor/vimeo/psalm/psalm(9): Psalm\Internal\Cli\Psalm::run()
#21 /home/greg/dev/doctrine-orm/major/vendor/bin/psalm(120): include('...')
#22 {main}
(Psalm dev-master@074136c8ef279314901fa44ba140e368935b3c1d crashed due to an uncaught Throwable)
```

**Comment by greg0ire** [comment]
Intersection types are not supported in v4, so it's not like the issue is new. But yeah, congrats to the team on the v5 stable release!

**Comment by ADmad** [comment]
> Intersection types are not supported in v4, so it's not like the issue is new.

Intersection types were working with 5.0.0-beta and it a regression cased in 5.0.0-rc1.

**Comment by greg0ire** [comment]
I think that's OK: if you're ready to risk your software on a beta version, then surely you're ready to deal with a regression. Now that 5.0.0 is released, I'd expect no regressions to happen, so you just have to wait and let users that don't use intersections type enjoy Psalm v5.

**Comment by othercorey** [comment]
@greg0ire We're simply reporting a break in a feature that we thought was working.

**Comment by greg0ire** [comment]
So? It's great that you are reporting it, what's your point?

**Comment by othercorey** [comment]
@greg0ire What is yours? You seem to be gate keeping reporting issues.

**Comment by orklah** [comment]
Hey guys, please chill

a PR has been submitted to fix this soon. The release was made independently from any issue lingering (and frankly, it was time, it should have been made months ago)

Sorry for the inconvenience, there are a lot of things we're trying to sort out and things don't always go as planned

**Comment by othercorey** [comment]
@orklah Issues with releases happen with every project, not a problem.

**Comment by greg0ire** [comment]
Reporting issues is 100% fine, I don't know what gave you the impression I had an issue with that.


> but doing a stable release without fixing a major issue as this one doesn't make sense to me

This kind of criticism is what I'm taking an issue with.
