### ISSUE TITLE
Uncaught UnexpectedValueException: Storage for Phar::running is not user-defined

### ISSUE THREAD

**Issue by weirdan** [vimeo/psalm#884]
That's fresh, I'm getting this running psalm@dev-master against my local psalm branch I'm working on, but also when running clean master on master itself.
```console
$ ./psalm --version
Psalm 2.9999999.9999999.9999999-dev@42e109064768f3b52fbbea325b9a67a26844ce61
$ ./psalm
Scanning files...
Analyzing files...
PHP Fatal error:  Uncaught UnexpectedValueException: Storage for Phar::running is not user-defined in /home/weirdan/src/psalm/src/Psalm/Codebase/Methods.php:449
Stack trace:
#0 /home/weirdan/src/psalm/src/Psalm/Checker/Statements/Expression/Call/StaticCallChecker.php(433): Psalm\Codebase\Methods->getUserMethodStorage('Phar::running')
#1 /home/weirdan/src/psalm/src/Psalm/Checker/Statements/ExpressionChecker.php(108): Psalm\Checker\Statements\Expression\Call\StaticCallChecker::analyze(Object(Psalm\Checker\StatementsChecker), Object(PhpParser\Node\Expr\StaticCall), Object(Psalm\Context))
#2 /home/weirdan/src/psalm/src/Psalm/Checker/Statements/Expression/BinaryOpChecker.php(444): Psalm\Checker\Statements\ExpressionChecker::analyze(Object(Psalm\Checker\StatementsChecker), Object(PhpParser\Node\Expr\StaticCall), Object(Psalm\Context))
#3 /home/weirdan/src/psalm/src/Psalm/Checker/Statements/ExpressionChecker.php(200): Psalm\Checker\Statements\Expression\BinaryOpChecker::analyze(Object(Psalm\Checker\StatementsChecker), Object(PhpParse in /home/weirdan/src/psalm/src/Psalm/Codebase/Methods.php on line 449

Fatal error: Uncaught UnexpectedValueException: Storage for Phar::running is not user-defined in /home/weirdan/src/psalm/src/Psalm/Codebase/Methods.php:449
Stack trace:
#0 /home/weirdan/src/psalm/src/Psalm/Checker/Statements/Expression/Call/StaticCallChecker.php(433): Psalm\Codebase\Methods->getUserMethodStorage('Phar::running')
#1 /home/weirdan/src/psalm/src/Psalm/Checker/Statements/ExpressionChecker.php(108): Psalm\Checker\Statements\Expression\Call\StaticCallChecker::analyze(Object(Psalm\Checker\StatementsChecker), Object(PhpParser\Node\Expr\StaticCall), Object(Psalm\Context))
#2 /home/weirdan/src/psalm/src/Psalm/Checker/Statements/Expression/BinaryOpChecker.php(444): Psalm\Checker\Statements\ExpressionChecker::analyze(Object(Psalm\Checker\StatementsChecker), Object(PhpParser\Node\Expr\StaticCall), Object(Psalm\Context))
#3 /home/weirdan/src/psalm/src/Psalm/Checker/Statements/ExpressionChecker.php(200): Psalm\Checker\Statements\Expression\BinaryOpChecker::analyze(Object(Psalm\Checker\StatementsChecker), Object(PhpParse in /home/weirdan/src/psalm/src/Psalm/Codebase/Methods.php on line 449
```

**Comment by muglug** [comment]
Sorry, didn't consider this possibility
