### ISSUE TITLE
self::class is not resolved

### ISSUE THREAD

**Issue by weirdan** [vimeo/psalm#887]
https://getpsalm.org/r/cb74e45ddd
https://3v4l.org/MXMHV
```php
<?php  
  class C {
     /** @param object $obj */
     public function work($obj): string {
       if (get_class($obj) === self::class) {
         return $obj->baz();
       }
       return '';
     }
     public function baz(): string {
       return "baz";
     }
  }
  $q = new C;
  echo $q->work($q);
```
```
Psalm runner output: 

Internal Psalm error on line 35 - Could not get class storage for self
```
Real-world example: https://github.com/sebastianbergmann/phpunit/blob/093ca5508174cd8ab8efe44fd1dde447adfdec8f/src/Framework/Constraint/LogicalNot.php#L141

This causes psalm fail with the following exception, when trying to analyze PHPUnit:
```
PHP Fatal error:  Uncaught InvalidArgumentException: Could not get class storage for self in /home/weirdan/.composer/vendor/vimeo/psalm/src/Psalm/Provider/ClassLikeStorageProvider.php:35
Stack trace:
#0 /home/weirdan/.composer/vendor/vimeo/psalm/src/Psalm/Codebase/Methods.php(64): Psalm\Provider\ClassLikeStorageProvider->get('self')
#1 /home/weirdan/.composer/vendor/vimeo/psalm/src/Psalm/Codebase.php(575): Psalm\Codebase\Methods->methodExists('self::__call', NULL)
#2 /home/weirdan/.composer/vendor/vimeo/psalm/src/Psalm/Checker/Statements/Expression/Call/MethodCallChecker.php(297): Psalm\Codebase->methodExists('self::__call')
#3 /home/weirdan/.composer/vendor/vimeo/psalm/src/Psalm/Checker/Statements/ExpressionChecker.php(104): Psalm\Checker\Statements\Expression\Call\MethodCallChecker::analyze(Object(Psalm\Checker\StatementsChecker), Object(PhpParser\Node\Expr\MethodCall), Object(Psalm\Context))
#4 /home/weirdan/.composer/vendor/vimeo/psalm/src/Psalm/Checker/Statements/Expression/BinaryOpChecker.php(279): Psalm\Checker\Statemen in /home/weirdan/.composer/vendor/vimeo/psalm/src/Psalm/Provider/ClassLikeStorageProvider.php on line 35

Fatal error: Uncaught InvalidArgumentException: Could not get class storage for self in /home/weirdan/.composer/vendor/vimeo/psalm/src/Psalm/Provider/ClassLikeStorageProvider.php:35
Stack trace:
#0 /home/weirdan/.composer/vendor/vimeo/psalm/src/Psalm/Codebase/Methods.php(64): Psalm\Provider\ClassLikeStorageProvider->get('self')
#1 /home/weirdan/.composer/vendor/vimeo/psalm/src/Psalm/Codebase.php(575): Psalm\Codebase\Methods->methodExists('self::__call', NULL)
#2 /home/weirdan/.composer/vendor/vimeo/psalm/src/Psalm/Checker/Statements/Expression/Call/MethodCallChecker.php(297): Psalm\Codebase->methodExists('self::__call')
#3 /home/weirdan/.composer/vendor/vimeo/psalm/src/Psalm/Checker/Statements/ExpressionChecker.php(104): Psalm\Checker\Statements\Expression\Call\MethodCallChecker::analyze(Object(Psalm\Checker\StatementsChecker), Object(PhpParser\Node\Expr\MethodCall), Object(Psalm\Context))
#4 /home/weirdan/.composer/vendor/vimeo/psalm/src/Psalm/Checker/Statements/Expression/BinaryOpChecker.php(279): Psalm\Checker\Statemen in /home/weirdan/.composer/vendor/vimeo/psalm/src/Psalm/Provider/ClassLikeStorageProvider.php on line 35
```

**Comment by muglug** [comment]
Thanks!
