### ISSUE TITLE
Creation of dynamic property Psalm\Internal\LanguageServer\LanguageServer::$mapper is deprecated in PHP 8.2

### ISSUE THREAD

**Issue by elplaza** [vimeo/psalm#8873]
Running psalm command I have this error:
```sh
Uncaught RuntimeException: PHP Error: Creation of dynamic property Psalm\Internal\LanguageServer\LanguageServer::$mapper is deprecated in /<project-path>/vendor/felixfbecker/advanced-json-rpc/lib/Dispatcher.php:53 for command with CLI args "/<project-path>/vendor/bin/psalm --use-extended-diagnostic-codes --language-server -c /<project-path>/psalm.xml -r /<project-path>/bin --find-dead-code" in /<project-path>/vendor/vimeo/psalm/src/Psalm/Internal/ErrorHandler.php:77
Stack trace:
#0 /<project-path>/vendor/felixfbecker/advanced-json-rpc/lib/Dispatcher.php(53): Psalm\Internal\ErrorHandler::Psalm\Internal\{closure}()
#1 /<project-path>/vendor/vimeo/psalm/src/Psalm/Internal/LanguageServer/LanguageServer.php(116): AdvancedJsonRpc\Dispatcher->__construct()
#2 /<project-path>/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/ProjectAnalyzer.php(567): Psalm\Internal\LanguageServer\LanguageServer->__construct()
#3 /<project-path>/vendor/vimeo/psalm/src/Psalm/Internal/Cli/LanguageServer.php(325): Psalm\Internal\Analyzer\ProjectAnalyzer->server()
#4 /<project-path>/vendor/vimeo/psalm/src/Psalm/Internal/Cli/Psalm.php(941): Psalm\Internal\Cli\LanguageServer::run()
#5 /<project-path>/vendor/vimeo/psalm/src/Psalm/Internal/Cli/Psalm.php(182): Psalm\Internal\Cli\Psalm::forwardCliCall()
#6 /<project-path>/vendor/vimeo/psalm/psalm(9): Psalm\Internal\Cli\Psalm::run()
#7 /<project-path>/vendor/bin/psalm(120): include('...')
#8 {main}
(Psalm 5.1.0@4defa177c89397c5e14737a80fe4896584130674 crashed due to an uncaught Throwable)
```

Environment:
PHP 8.2
Psalm 5.1

**Comment by elplaza** [comment]
> Hey @elplaza, can you reproduce the issue on https://psalm.dev ?

Mmmm . . . I think no, I can't find a way to select the php version.

**Comment by weirdan** [comment]
@elplaza I'm not sure why you closed this
