### ISSUE TITLE
Psalm not working on big project?

### ISSUE THREAD

**Issue by arjenrommens** [vimeo/psalm#898]
Hi there!

I'm trying to get Psalm work on a big project, but keep on getting errors in the php-parser lib, such as:

```
Fatal error: Uncaught PhpParser\Error: Syntax error, unexpected T_ENDIF, expecting '}' on line 44 in /mnt/hgfs/www_host/IPS_TP/vendor/nikic/php-parser/lib/PhpParser/ParserAbstract.php:313
Stack trace:
#0 /mnt/hgfs/www_host/IPS_TP/vendor/nikic/php-parser/lib/PhpParser/ParserAbstract.php(156): PhpParser\ParserAbstract->doParse()
#1 /mnt/hgfs/www_host/IPS_TP/vendor/nikic/php-parser/lib/PhpParser/Parser/Multiple.php(51): PhpParser\ParserAbstract->parse('<?php     \r\n   ...', Object(PhpParser\ErrorHandler\Collecting))
#2 /mnt/hgfs/www_host/IPS_TP/vendor/nikic/php-parser/lib/PhpParser/Parser/Multiple.php(32): PhpParser\Parser\Multiple->tryParse(Object(PhpParser\Parser\Php7), Object(PhpParser\ErrorHandler\Collecting), '<?php     \r\n   ...')
#3 /mnt/hgfs/www_host/IPS_TP/vendor/vimeo/psalm/src/Psalm/Provider/StatementsProvider.php(108): PhpParser\Parser\Multiple->parse('<?php     \r\n   ...', Object(PhpParser\ErrorHandler\Collecting))
#4 /mnt/hgfs/www_host/IPS_TP/vendor/vimeo/psalm/src/Psalm/Provider/StatementsProvider.php(73):  in /mnt/hgfs/www_host/IPS_TP/vendor/nikic/php-parser/lib/PhpParser/ParserAbstract.php on line 313
```

or

```
Fatal error: Uncaught PhpParser\Error: Syntax error, unexpected T_ENDIF, expecting '}' on line 44 in /mnt/hgfs/www_host/IPS_TP/vendor/nikic/php-parser/lib/PhpParser/ParserAbstract.php:313
Stack trace:
#0 /mnt/hgfs/www_host/IPS_TP/vendor/nikic/php-parser/lib/PhpParser/ParserAbstract.php(156): PhpParser\ParserAbstract->doParse()
#1 /mnt/hgfs/www_host/IPS_TP/vendor/nikic/php-parser/lib/PhpParser/Parser/Multiple.php(51): PhpParser\ParserAbstract->parse('<?php     \r\n   ...', Object(PhpParser\ErrorHandler\Collecting))
#2 /mnt/hgfs/www_host/IPS_TP/vendor/nikic/php-parser/lib/PhpParser/Parser/Multiple.php(32): PhpParser\Parser\Multiple->tryParse(Object(PhpParser\Parser\Php7), Object(PhpParser\ErrorHandler\Collecting), '<?php     \r\n   ...')
#3 /mnt/hgfs/www_host/IPS_TP/vendor/vimeo/psalm/src/Psalm/Provider/StatementsProvider.php(108): PhpParser\Parser\Multiple->parse('<?php     \r\n   ...', Object(PhpParser\ErrorHandler\Collecting))
#4 /mnt/hgfs/www_host/IPS_TP/vendor/vimeo/psalm/src/Psalm/Provider/StatementsProvider.php(73):  in /mnt/hgfs/www_host/IPS_TP/vendor/nikic/php-parser/lib/PhpParser/ParserAbstract.php on line 313
```

Anyone a suggestion / similar problem?

**Comment by muglug** [comment]
You can run with `--debug` to find out which file it's failing on.

**Comment by arjenrommens** [comment]
Thanks muglug. I now can see the issue is in a view. Any suggestion what to do next?

Parsing views/agreements/list_results.php

```
Fatal error: Uncaught PhpParser\Error: Syntax error, unexpected T_ENDIF, expecting '}' on line 44 in /mnt/hgfs/www_host/IPS_TP/vendor/nikic/php-parser/lib/PhpParser/ParserAbstract.php:313
Stack trace:
#0 /mnt/hgfs/www_host/IPS_TP/vendor/nikic/php-parser/lib/PhpParser/ParserAbstract.php(156): PhpParser\ParserAbstract->doParse()
#1 /mnt/hgfs/www_host/IPS_TP/vendor/nikic/php-parser/lib/PhpParser/Parser/Multiple.php(51): PhpParser\ParserAbstract->parse('<?php     \r\n   ...', Object(PhpParser\ErrorHandler\Collecting))
#2 /mnt/hgfs/www_host/IPS_TP/vendor/nikic/php-parser/lib/PhpParser/Parser/Multiple.php(32): PhpParser\Parser\Multiple->tryParse(Object(PhpParser\Parser\Php7), Object(PhpParser\ErrorHandler\Collecting), '<?php     \r\n   ...')
#3 /mnt/hgfs/www_host/IPS_TP/vendor/vimeo/psalm/src/Psalm/Provider/StatementsProvider.php(108): PhpParser\Parser\Multiple->parse('<?php     \r\n   ...', Object(PhpParser\ErrorHandler\Collecting))
#4 /mnt/hgfs/www_host/IPS_TP/vendor/vimeo/psalm/src/Psalm/Provider/StatementsProvider.php(73):  in /mnt/hgfs/www_host/IPS_TP/vendor/nikic/php-parser/lib/PhpParser/ParserAbstract.php on line 313

```

**Comment by muglug** [comment]
Run `php -l views/agreements/list_results.php` to identify the syntax error in that file - and if you could include it here for posterity, that’d he great!

**Comment by arjenrommens** [comment]
`php -l application/views/agreements/list_results.php
PHP Parse error:  syntax error, unexpected 'endif' (T_ENDIF) in application/views/agreements/list_results.php on line 109
Errors parsing application/views/agreements/list_results.php
`
Which is strange, because my application & code works perfect.

My view contains a mix of control structures:
```
if(...):
...;
endif;

and

if(...) {
...;
}
```
