### ISSUE TITLE
Regenerating baseline with --no-cache fails

### ISSUE THREAD

**Issue by mixdf** [vimeo/psalm#9057]
I tried regenerating psalm baseline using `php -d memory_limit=-1 vendor/bin/psalm --config=psalm.xml --set-baseline=psalm-baseline.xml --no-cache` and it fails.

To make the command work successfully I need to either remove 1 class from the project (removing any of the existing test classes work) or to remove the `--no-cache` option. Is there a limit for the number of files?

Console output:
```bash
> @php -d memory_limit=-1 tools/psalm/vendor/bin/psalm --config=psalm.xml --find-unused-psalm-suppress --output-format=phpstorm '--set-baseline=psalm-baseline.xml' '--long-progress' '--no-cache'
Target PHP version: 8.1 (inferred from composer.json) Extensions enabled: dom, pdo, redis (unsupported extensions: bcmath, curl, filter, gd, hash, iconv, intl, json, mbstring, openssl, pcntl, pdo_mysql, tokenizer, zip)
Scanning files...
Uncaught Exception: InvalidArgumentException Could not get class storage for illuminate\database\eloquent\model
Emitted in /var/www/tools/psalm/vendor/vimeo/psalm/src/Psalm/Internal/Provider/ClassLikeStorageProvider.php:45
Stack trace in the forked worker:
#0 /var/www/tools/psalm/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/ClassLikes.php(611): Psalm\Internal\Provider\ClassLikeStorageProvider->get('Illuminate\\Data...')
#1 /var/www/tools/psalm/vendor/vimeo/psalm/src/Psalm/Codebase.php(692): Psalm\Internal\Codebase\ClassLikes->classExtends('Illuminate\\Data...', 'App\\Modules\\Pay...')
#2 /var/www/tools/psalm/vendor/vimeo/psalm/src/Psalm/Internal/Type/Comparator/AtomicTypeComparator.php(711): Psalm\Codebase->classExtendsOrImplements('Illuminate\\Data...', 'App\\Modules\\Pay...')
#3 /var/www/tools/psalm/vendor/vimeo/psalm/src/Psalm/Type.php(857): Psalm\Internal\Type\Comparator\AtomicTypeComparator::isContainedBy(Object(Psalm\Codebase), Object(Psalm\Type\Atomic\TNamedObject), Object(Psalm\Type\Atomic\TNamedObject))
#4 /var/www/tools/psalm/vendor/vimeo/psalm/src/Psalm/Type.php(738): Psalm\Type::intersectAtomicTypes(Object(Psalm\Type\Atomic\TNamedObject), Object(Psalm\Type\Atomic\TNamedObject), Object(Psalm\Codebase), false)
#5 /var/www/tools/psalm/vendor/vimeo/psalm/src/Psalm/Internal/PhpVisitor/Reflector/TypeHintResolver.php(113): Psalm\Type::intersectUnionTypes(Object(Psalm\Type\Union), Object(Psalm\Type\Union), Object(Psalm\Codebase))
#6 /var/www/tools/psalm/vendor/vimeo/psalm/src/Psalm/Internal/PhpVisitor/Reflector/FunctionLikeNodeScanner.php(811): Psalm\Internal\PhpVisitor\Reflector\TypeHintResolver::resolve(Object(PhpParser\Node\IntersectionType), Object(Psalm\CodeLocation), Object(Psalm\Codebase), Object(Psalm\Storage\FileStorage), Object(Psalm\Storage\ClassLikeStorage), Object(Psalm\Aliases), 80100)
#7 /var/www/tools/psalm/vendor/vimeo/psalm/src/Psalm/Internal/PhpVisitor/Reflector/FunctionLikeNodeScanner.php(189): Psalm\Internal\PhpVisitor\Reflector\FunctionLikeNodeScanner->getTranslatedFunctionParam(Object(PhpParser\Node\Param), Object(PhpParser\Node\Stmt\ClassMethod), false, 'Tests\\Unit\\Serv...')
#8 /var/www/tools/psalm/vendor/vimeo/psalm/src/Psalm/Internal/PhpVisitor/ReflectorVisitor.php(208): Psalm\Internal\PhpVisitor\Reflector\FunctionLikeNodeScanner->start(Object(PhpParser\Node\Stmt\ClassMethod))
#9 /var/www/tools/psalm/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(200): Psalm\Internal\PhpVisitor\ReflectorVisitor->enterNode(Object(PhpParser\Node\Stmt\ClassMethod))
#10 /var/www/tools/psalm/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(114): PhpParser\NodeTraverser->traverseArray(Array)
#11 /var/www/tools/psalm/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(223): PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Stmt\Class_))
#12 /var/www/tools/psalm/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(114): PhpParser\NodeTraverser->traverseArray(Array)
#13 /var/www/tools/psalm/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(223): PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Stmt\Namespace_))
#14 /var/www/tools/psalm/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(91): PhpParser\NodeTraverser->traverseArray(Array)
#15 /var/www/tools/psalm/vendor/vimeo/psalm/src/Psalm/Internal/Scanner/FileScanner.php(79): PhpParser\NodeTraverser->traverse(Array)
#16 /var/www/tools/psalm/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Scanner.php(553): Psalm\Internal\Scanner\FileScanner->scan(Object(Psalm\Codebase), Object(Psalm\Storage\FileStorage), false, Object(Psalm\Progress\LongProgress))
#17 /var/www/tools/psalm/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Scanner.php(781): Psalm\Internal\Codebase\Scanner->scanFile('/var/www/tests/...', Array, true)
#18 /var/www/tools/psalm/vendor/vimeo/psalm/src/Psalm/Internal/Fork/Pool.php(209): Psalm\Internal\Codebase\Scanner->scanAPath(1288, '/var/www/tests/...')
#19 /var/www/tools/psalm/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Scanner.php(331): Psalm\Internal\Fork\Pool->__construct(Object(Psalm\Config), Array, Object(Closure), Object(Closure), Object(Closure))
#20 /var/www/tools/psalm/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Scanner.php(280): Psalm\Internal\Codebase\Scanner->scanFilePaths(3.0)
#21 /var/www/tools/psalm/vendor/vimeo/psalm/src/Psalm/Codebase.php(496): Psalm\Internal\Codebase\Scanner->scanFiles(Object(Psalm\Internal\Codebase\ClassLikes), 3)
#22 /var/www/tools/psalm/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/ProjectAnalyzer.php(605): Psalm\Codebase->scanFiles(3)
#23 /var/www/tools/psalm/vendor/vimeo/psalm/src/Psalm/Internal/Cli/Psalm.php(380): Psalm\Internal\Analyzer\ProjectAnalyzer->check('/var/www/', false)
#24 /var/www/tools/psalm/vendor/vimeo/psalm/psalm(9): Psalm\Internal\Cli\Psalm::run(Array)
#25 /var/www/tools/psalm/vendor/bin/psalm(117): include('/var/www/tools/...')
#26 {main} in /var/www/tools/psalm/vendor/vimeo/psalm/src/Psalm/Internal/Fork/Pool.php:397
Stack trace:
#0 /var/www/tools/psalm/vendor/vimeo/psalm/src/Psalm/Internal/Fork/Pool.php(431): Psalm\Internal\Fork\Pool->readResultsFromChildren()
#1 /var/www/tools/psalm/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Scanner.php(383): Psalm\Internal\Fork\Pool->wait()
#2 /var/www/tools/psalm/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Scanner.php(280): Psalm\Internal\Codebase\Scanner->scanFilePaths(3.0)
#3 /var/www/tools/psalm/vendor/vimeo/psalm/src/Psalm/Codebase.php(496): Psalm\Internal\Codebase\Scanner->scanFiles(Object(Psalm\Internal\Codebase\ClassLikes), 3)
#4 /var/www/tools/psalm/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/ProjectAnalyzer.php(605): Psalm\Codebase->scanFiles(3)
#5 /var/www/tools/psalm/vendor/vimeo/psalm/src/Psalm/Internal/Cli/Psalm.php(380): Psalm\Internal\Analyzer\ProjectAnalyzer->check('/var/www/', false)
#6 /var/www/tools/psalm/vendor/vimeo/psalm/psalm(9): Psalm\Internal\Cli\Psalm::run(Array)
#7 /var/www/tools/psalm/vendor/bin/psalm(117): include('/var/www/tools/...')
#8 {main}
(Psalm 5.4.0@62db5d4f6a7ae0a20f7cc5a4952d730272fc0863 crashed due to an uncaught Throwable)
```

Running the command with `--debug-by-line` doesn't show any useful info since it crashes semi-randomly.

I have psalm installed in a separate directory (`tools/psalm`) and here's the content of the `composer.json` file:
```json
{
    "require-dev": {
        "leighman/psalm-plugin-todo-by": "dev-master",
        "psalm/plugin-mockery": "^1.1",
        "psalm/plugin-phpunit": "^0.18",
        "vimeo/psalm": "^5.4"
    },
    "config": {
        "allow-plugins": {
            "psalm/psalm-plugin": true
        }
    }
}
```

**Comment by mixdf** [comment]
I removed a class, regenerated the baseline, continued development, and now everything seems to be working. I think it's safe to assume that it was a local issue, so I'm going to close this.

**Comment by lptn** [comment]
Hello guys!

I have the same issue. Together with @mixdf , we worked at the same private project and we still experience issues like this. Not always, but sometimes. With ` --threads=1` it doesn't fail and create cache, for on next run there is a chance that this cache will be used and thus the next run is usually green. The project is pretty big, I already reduced scope of the issue, but the scope is still big. I'll continue reducing the scope, but as @mixdf said, `--debug-by-line` "points" to different classes. 

Do you have any recommendations for debugging this issue? The thing is the project is under NDA, I can't share a lot of information here, but ready to go deeper to psalm src to solve the issue, just need to get a direction for the research.
