### ISSUE TITLE
Depreciated/undocumented PostgreSQL function aliases crash Psalm.

### ISSUE THREAD

**Issue by ReimuHakurei** [vimeo/psalm#9140]
Psalm crashes with this message:

```
Uncaught InvalidArgumentException: Could not get class storage for pgsql\result
```

...when encountering (at the very least) pg_numfields from this list of depreciated, undocumented function aliases: https://php.watch/versions/8.0/pgsql-aliases-deprecated

I can only assume from my cursory searching of the code for references to this function that it's probably because they're not defined here like the normal version of these functions are: https://github.com/vimeo/psalm/blob/466ff68daea0a45680177e0dba214d3e296dcd2c/dictionaries/CallMap_81_delta.php

**Comment by ReimuHakurei** [comment]
No, it does not seem to crash or error on psalm.dev, but I did test it on 5d6dff9069d01eb8b58ffa56fde54be7e38e5b89 on my local system and it does crash there.

The codebase in question is very ancient and is over 1100+ files, and takes Psalm over 30 minutes to fully scan on my test system, so it would not surprise me in the least if it's an interaction with something else contributing to the crash.

**Comment by ohader** [comment]
Can you try to isolate the problem? For instance running `psalm` with the `--debug` option, identify the file/class that probably causes this behavior and create a reduced and simplified version on psalm.dev?

**Comment by ReimuHakurei** [comment]
I honestly forgot I filed this issue -- looking back at it now, I have been able to make a reproducible version.

It is possible this might be more broad, but at least the following is sufficient to reproduce this issue:

Requirements: Be running PHP 8.1. Psalm must target a PHP version of 8.0 or under. Run Psalm against the following 2 lines of code:

```php
<?php
        $num_fields = pg_numfields($res);
```

I have not tested further, but I suspect all the other depreciated aliases in the page I linked in the initial issue comment likely will behave similarly.

Crash log:
```
$ ./vendor/vimeo/psalm/psalm --no-cache test.php
Target PHP version: 8.0 (inferred from composer.json).
Scanning files...
Analyzing files...

Uncaught InvalidArgumentException: Could not get class storage for pgsql\result in /storage/test2/vendor/vimeo/psalm/src/Psalm/Internal/Provider/ClassLikeStorageProvider.php:45
Stack trace:
#0 /storage/test2/vendor/vimeo/psalm/src/Psalm/Internal/Type/TypeExpander.php(629): Psalm\Internal\Provider\ClassLikeStorageProvider->get()
#1 /storage/test2/vendor/vimeo/psalm/src/Psalm/Internal/Type/TypeExpander.php(175): Psalm\Internal\Type\TypeExpander::expandNamedObject()
#2 /storage/test2/vendor/vimeo/psalm/src/Psalm/Internal/Type/TypeExpander.php(77): Psalm\Internal\Type\TypeExpander::expandAtomic()
#3 /storage/test2/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/Statements/Expression/Call/ArgumentAnalyzer.php(285): Psalm\Internal\Type\TypeExpander::expandUnion()
#4 /storage/test2/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/Statements/Expression/Call/ArgumentAnalyzer.php(196): Psalm\Internal\Analyzer\Statements\Expression\Call\ArgumentAnalyzer::checkFunctionLikeTypeMatches()
#5 /storage/test2/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/Statements/Expression/Call/ArgumentsAnalyzer.php(850): Psalm\Internal\Analyzer\Statements\Expression\Call\ArgumentAnalyzer::checkArgumentMatches()
#6 /storage/test2/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/Statements/Expression/Call/FunctionCallAnalyzer.php(219): Psalm\Internal\Analyzer\Statements\Expression\Call\ArgumentsAnalyzer::checkArgumentsMatch()
#7 /storage/test2/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/Statements/ExpressionAnalyzer.php(287): Psalm\Internal\Analyzer\Statements\Expression\Call\FunctionCallAnalyzer::analyze()
#8 /storage/test2/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/Statements/ExpressionAnalyzer.php(91): Psalm\Internal\Analyzer\Statements\ExpressionAnalyzer::handleExpression()
#9 /storage/test2/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/Statements/Expression/AssignmentAnalyzer.php(243): Psalm\Internal\Analyzer\Statements\ExpressionAnalyzer::analyze()
#10 /storage/test2/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/Statements/ExpressionAnalyzer.php(535): Psalm\Internal\Analyzer\Statements\Expression\AssignmentAnalyzer::analyze()
#11 /storage/test2/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/Statements/ExpressionAnalyzer.php(169): Psalm\Internal\Analyzer\Statements\ExpressionAnalyzer::analyzeAssignment()
#12 /storage/test2/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/Statements/ExpressionAnalyzer.php(91): Psalm\Internal\Analyzer\Statements\ExpressionAnalyzer::handleExpression()
#13 /storage/test2/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/StatementsAnalyzer.php(566): Psalm\Internal\Analyzer\Statements\ExpressionAnalyzer::analyze()
#14 /storage/test2/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/StatementsAnalyzer.php(194): Psalm\Internal\Analyzer\StatementsAnalyzer::analyzeStatement()
#15 /storage/test2/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/FileAnalyzer.php(178): Psalm\Internal\Analyzer\StatementsAnalyzer->analyze()
#16 /storage/test2/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Analyzer.php(1591): Psalm\Internal\Analyzer\FileAnalyzer->analyze()
#17 /storage/test2/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Analyzer.php(522): Psalm\Internal\Codebase\Analyzer->analysisWorker()
#18 /storage/test2/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Analyzer.php(272): Psalm\Internal\Codebase\Analyzer->doAnalysis()
#19 /storage/test2/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/ProjectAnalyzer.php(1086): Psalm\Internal\Codebase\Analyzer->analyzeFiles()
#20 /storage/test2/vendor/vimeo/psalm/src/Psalm/Internal/Cli/Psalm.php(381): Psalm\Internal\Analyzer\ProjectAnalyzer->checkPaths()
#21 /storage/test2/vendor/vimeo/psalm/psalm(9): Psalm\Internal\Cli\Psalm::run()
#22 {main}
(Psalm 5.15.0@5c774aca4746caf3d239d9c8cadb9f882ca29352 crashed due to an uncaught Throwable)
```
