### ISSUE TITLE
Could not get class storage for self

### ISSUE THREAD

**Issue by endelwar** [vimeo/psalm#920]
I'm running psalm 2.0.9 on https://github.com/pepeverde/doctrine1 and processing [line 104 of Doctrine_Manager class](https://github.com/pepeverde/doctrine1/blob/enhance-tests/lib/Doctrine/Manager.php#L104) I get the following exception:

```
Scanning files...
Analyzing files...
PHP Fatal error:  Uncaught InvalidArgumentException: Could not get class storage for self in /Users/manuel/projects/pepeverde/doctrine1/vendor/vimeo/psalm/src/Psalm/Provider/ClassLikeStorageProvider.php:35
Stack trace:
#0 /Users/manuel/projects/pepeverde/doctrine1/vendor/vimeo/psalm/src/Psalm/Codebase/Methods.php(64): Psalm\Provider\ClassLikeStorageProvider->get('self')
#1 /Users/manuel/projects/pepeverde/doctrine1/vendor/vimeo/psalm/src/Psalm/Codebase.php(575): Psalm\Codebase\Methods->methodExists('self::__call', NULL)
#2 /Users/manuel/projects/pepeverde/doctrine1/vendor/vimeo/psalm/src/Psalm/Checker/Statements/Expression/Call/MethodCallChecker.php(304): Psalm\Codebase->methodExists('self::__call')
#3 /Users/manuel/projects/pepeverde/doctrine1/vendor/vimeo/psalm/src/Psalm/Checker/Statements/ExpressionChecker.php(104): Psalm\Checker\Statements\Expression\Call\MethodCallChecker::analyze(Object(Psalm\Checker\StatementsChecker), Object(PhpParser\Node\Expr\MethodCall), Object(Psalm\Context))
#4 /Users/manuel/projects/pepeverde/doc in /Users/manuel/projects/pepeverde/doctrine1/vendor/vimeo/psalm/src/Psalm/Provider/ClassLikeStorageProvider.php on line 35

Fatal error: Uncaught InvalidArgumentException: Could not get class storage for self in /Users/manuel/projects/pepeverde/doctrine1/vendor/vimeo/psalm/src/Psalm/Provider/ClassLikeStorageProvider.php:35
Stack trace:
#0 /Users/manuel/projects/pepeverde/doctrine1/vendor/vimeo/psalm/src/Psalm/Codebase/Methods.php(64): Psalm\Provider\ClassLikeStorageProvider->get('self')
#1 /Users/manuel/projects/pepeverde/doctrine1/vendor/vimeo/psalm/src/Psalm/Codebase.php(575): Psalm\Codebase\Methods->methodExists('self::__call', NULL)
#2 /Users/manuel/projects/pepeverde/doctrine1/vendor/vimeo/psalm/src/Psalm/Checker/Statements/Expression/Call/MethodCallChecker.php(304): Psalm\Codebase->methodExists('self::__call')
#3 /Users/manuel/projects/pepeverde/doctrine1/vendor/vimeo/psalm/src/Psalm/Checker/Statements/ExpressionChecker.php(104): Psalm\Checker\Statements\Expression\Call\MethodCallChecker::analyze(Object(Psalm\Checker\StatementsChecker), Object(PhpParser\Node\Expr\MethodCall), Object(Psalm\Context))
#4 /Users/manuel/projects/pepeverde/doc in /Users/manuel/projects/pepeverde/doctrine1/vendor/vimeo/psalm/src/Psalm/Provider/ClassLikeStorageProvider.php on line 35
```

Changing line 104 from `/** @var self */` to `/** @var Doctrine_Manager */` fixes the problem and I get the expected output

**Comment by muglug** [comment]
Reproduced with

```php
class A {
  /** @var self|null */
  private static $instance;
  
  public function foo() : void {
    if (self::$instance) {
      self::$instance->bar();
    }
  }
  
  public function bar() : void {}
}
```

**Comment by muglug** [comment]
Thanks, sorry for the long wait to fix

**Comment by endelwar** [comment]
Thanks!
