### ISSUE TITLE
Uncaught Exception: UnexpectedValueException $storage should not be null for XXX

### ISSUE THREAD

**Issue by lens0021** [vimeo/psalm#9357]
I have a private project and have set up psalm.xml file.
I am sorry the project is private so I can't upload the full source code of the project.

## ❌ Case 1

Executing `psalm` throws an uncaught exception. 
```console
% psalm               
Warning: "findUnusedBaselineEntry" will be defaulted to "true" in Psalm 6. You should explicitly enable or disable this setting.
Warning: "findUnusedCode" will be defaulted to "true" in Psalm 6. You should explicitly enable or disable this setting.

Install the opcache extension to make use of JIT on PHP 8.0+ for a 20%+ performance boost!

Target PHP version: 5.4 (inferred from composer.json) (unsupported extensions: mcrypt, grpc).
Scanning files...
Analyzing files...

░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░   60 / 1074 (5%)
░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░  120 / 1074 (11%)
░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░  180 / 1074 (16%)
░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░  240 / 1074 (22%)
░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░  300 / 1074 (27%)
░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░  360 / 1074 (33%)
░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░  420 / 1074 (39%)
░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░  480 / 1074 (44%)
░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░  540 / 1074 (50%)
░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░Uncaught Exception: UnexpectedValueException $storage should not be null for AuthComponent::initialize
Emitted in /Users/Leslie/.asdf/installs/php/8.1.15/.composer/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Methods.php:1117
Stack trace in the forked worker:
#0 /Users/Leslie/.asdf/installs/php/8.1.15/.composer/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/ClassAnalyzer.php(1873): Psalm\Internal\Codebase\Methods->getStorage(Object(Psalm\Internal\MethodIdentifier))
#1 /Users/Leslie/.asdf/installs/php/8.1.15/.composer/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/ClassAnalyzer.php(1816): Psalm\Internal\Analyzer\ClassAnalyzer::analyzeClassMethodReturnType(Object(PhpParser\Node\Stmt\ClassMethod), Object(Psalm\Internal\Analyzer\MethodAnalyzer), Object(Psalm\Internal\Analyzer\ClassAnalyzer), Object(Psalm\Internal\Provider\NodeDataProvider), Object(Psalm\Codebase), Object(Psalm\Storage\ClassLikeStorage), 'AuthComponent', Object(Psalm\Internal\MethodIdentifier), Object(Psalm\Internal\MethodIdentifier), false)
#2 /Users/Leslie/.asdf/installs/php/8.1.15/.composer/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/ClassAnalyzer.php(426): Psalm\Internal\Analyzer\ClassAnalyzer->analyzeClassMethod(Object(PhpParser\Node\Stmt\ClassMethod), Object(Psalm\Storage\ClassLikeStorage), Object(Psalm\Internal\Analyzer\ClassAnalyzer), Object(Psalm\Context), Object(Psalm\Context))
#3 /Users/Leslie/.asdf/installs/php/8.1.15/.composer/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/FileAnalyzer.php(203): Psalm\Internal\Analyzer\ClassAnalyzer->analyze(Object(Psalm\Context), Object(Psalm\Context))
#4 /Users/Leslie/.asdf/installs/php/8.1.15/.composer/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Analyzer.php(1581): Psalm\Internal\Analyzer\FileAnalyzer->analyze()
#5 /Users/Leslie/.asdf/installs/php/8.1.15/.composer/vendor/vimeo/psalm/src/Psalm/Internal/Fork/Pool.php(209): Psalm\Internal\Codebase\Analyzer->analysisWorker(82, '/usr/local/git/...')
#6 /Users/Leslie/.asdf/installs/php/8.1.15/.composer/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Analyzer.php(373): Psalm\Internal\Fork\Pool->__construct(Object(Psalm\Config), Array, Object(Closure), Object(Closure), Object(Closure), Object(Closure))
#7 /Users/Leslie/.asdf/installs/php/8.1.15/.composer/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Analyzer.php(272): Psalm\Internal\Codebase\Analyzer->doAnalysis(Object(Psalm\Internal\Analyzer\ProjectAnalyzer), 9)
#8 /Users/Leslie/.asdf/installs/php/8.1.15/.composer/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/ProjectAnalyzer.php(669): Psalm\Internal\Codebase\Analyzer->analyzeFiles(Object(Psalm\Internal\Analyzer\ProjectAnalyzer), 9, false, true)
#9 /Users/Leslie/.asdf/installs/php/8.1.15/.composer/vendor/vimeo/psalm/src/Psalm/Internal/Cli/Psalm.php(372): Psalm\Internal\Analyzer\ProjectAnalyzer->check('/usr/local/git/...', true)
#10 /Users/Leslie/.asdf/installs/php/8.1.15/.composer/vendor/vimeo/psalm/psalm(9): Psalm\Internal\Cli\Psalm::run(Array)
#11 /Users/Leslie/.asdf/installs/php/8.1.15/.composer/vendor/bin/psalm(120): include('/Users/Leslie/....')
#12 {main} in /Users/Leslie/.asdf/installs/php/8.1.15/.composer/vendor/vimeo/psalm/src/Psalm/Internal/Fork/Pool.php:397
Stack trace:
#0 /Users/Leslie/.asdf/installs/php/8.1.15/.composer/vendor/vimeo/psalm/src/Psalm/Internal/Fork/Pool.php(431): Psalm\Internal\Fork\Pool->readResultsFromChildren()
#1 /Users/Leslie/.asdf/installs/php/8.1.15/.composer/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Analyzer.php(406): Psalm\Internal\Fork\Pool->wait()
#2 /Users/Leslie/.asdf/installs/php/8.1.15/.composer/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Analyzer.php(272): Psalm\Internal\Codebase\Analyzer->doAnalysis(Object(Psalm\Internal\Analyzer\ProjectAnalyzer), 9)
#3 /Users/Leslie/.asdf/installs/php/8.1.15/.composer/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/ProjectAnalyzer.php(669): Psalm\Internal\Codebase\Analyzer->analyzeFiles(Object(Psalm\Internal\Analyzer\ProjectAnalyzer), 9, false, true)
#4 /Users/Leslie/.asdf/installs/php/8.1.15/.composer/vendor/vimeo/psalm/src/Psalm/Internal/Cli/Psalm.php(372): Psalm\Internal\Analyzer\ProjectAnalyzer->check('/usr/local/git/...', true)
#5 /Users/Leslie/.asdf/installs/php/8.1.15/.composer/vendor/vimeo/psalm/psalm(9): Psalm\Internal\Cli\Psalm::run(Array)
#6 /Users/Leslie/.asdf/installs/php/8.1.15/.composer/vendor/bin/psalm(120): include('/Users/Leslie/....')
#7 {main}
(Psalm 5.7.3@471a8c6a1d4f0dcf91fdb34a3109adb204012fb3 crashed due to an uncaught Throwable)
```

## ✅ Case 2

`psalm --debug` success.

```console
% psalm --debug
Warning: "findUnusedBaselineEntry" will be defaulted to "true" in Psalm 6. You should explicitly enable or disable this setting.
Warning: "findUnusedCode" will be defaulted to "true" in Psalm 6. You should explicitly enable or disable this setting.

Install the opcache extension to make use of JIT on PHP 8.0+ for a 20%+ performance boost!

Composer lockfile change detected, clearing cache directory /Users/Leslie/.cache/psalm/d52cb386c7f7e4ba1df9d21d2cb5f137904ab755
Process plugin adjustments...
Target PHP version: 5.4 (inferred from composer.json) (unsupported extensions: mcrypt, grpc).
Scanning files...
Registering autoloaded files
   /usr/local/git/my-private-project/vendor/autoload.php
   /usr/local/git/my-private-project/vendor/composer/autoload_real.php
   /usr/local/git/my-private-project/vendor/composer/platform_check.php
   /usr/local/git/my-private-project/vendor/composer/ClassLoader.php
   /usr/local/git/my-private-project/vendor/composer/autoload_static.php
...
Getting /usr/local/git/my-private-project/lib/Cake/View/XmlView.php
Analyzing /usr/local/git/my-private-project/lib/Cake/View/XmlView.php
Checking class references
...
ERROR: RedundantCondition - lib/Cake/View/Helper/JsHelper.php:133:34 - Type array<array-key, mixed> for $lastParam is always array<array-key, mixed> (see https://psalm.dev/122)
                                } elseif ($hasBufferParam && is_array($lastParam)) {


------------------------------
22 errors found
------------------------------
3675 other issues found.
You can display them with --show-info=true
------------------------------
Psalm can automatically fix 537 of these issues.
Run Psalm again with 
--alter --issues=UnusedVariable,MissingClosureReturnType,InvalidFalsableReturnType,InvalidReturnType,InvalidNullableReturnType,UnnecessaryVarAnnotation,MismatchingDocblockParamType,MissingParamType --dry-run
to see what it can fix.
------------------------------

Checks took 20.82 seconds and used 285.871MB of memory
Psalm was able to infer types for 75.8535% of the codebase
```

## ✅ Case 3

Adding `<ignoreFiles><file name="lib/Cake/Controller/Component/AuthComponent.php" /></ignoreFiles>` to psalm.xml works.

```console
% psalm
...
------------------------------
465 errors found
------------------------------
3694 other issues found.
You can display them with --show-info=true
------------------------------
Psalm can automatically fix 580 of these issues.
Run Psalm again with 
--alter --issues=InvalidReturnType,UnusedVariable,InvalidNullableReturnType,InvalidFalsableReturnType,MismatchingDocblockParamType,UnnecessaryVarAnnotation,MissingClosureReturnType,MissingParamType --dry-run
to see what it can fix.
------------------------------

Checks took 6.06 seconds and used 565.297MB of memory
Psalm was able to infer types for 76.1574% of the codebase
```

## ✅ Case 4

`psalm lib/Cake/Controller/Component/AuthComponent.php` does not error.

```console
% psalm lib/Cake/Controller/Component/AuthComponent.php
Warning: "findUnusedBaselineEntry" will be defaulted to "true" in Psalm 6. You should explicitly enable or disable this setting.
Warning: "findUnusedCode" will be defaulted to "true" in Psalm 6. You should explicitly enable or disable this setting.

Install the opcache extension to make use of JIT on PHP 8.0+ for a 20%+ performance boost!

Target PHP version: 5.4 (inferred from composer.json) (unsupported extensions: mcrypt, grpc).
Scanning files...
Analyzing files...

░

To whom it may concern: Psalm cannot detect unused classes, methods and properties
when analyzing individual files and folders. Run on the full project to enable
complete unused code detection.

ERROR: UndefinedClass - lib/Cake/Controller/Component/AuthComponent.php:21:1 - Class, interface or enum named App does not exist (see https://psalm.dev/019)
/**
 * Authentication component
 *
 * Manages user logins and permissions.
 *
 * CakePHP(tm) : Rapid Development Framework (http://cakephp.org)
 * Copyright (c) Cake Software Foundation, Inc. (http://cakefoundation.org)
 *
 * Licensed under The MIT License
 * For full copyright and license information, please see the LICENSE.txt
 * Redistributions of files must retain the above copyright notice.
 *
 * @copyright     Copyright (c) Cake Software Foundation, Inc. (http://cakefoundation.org)
 * @link          http://cakephp.org CakePHP(tm) Project
 * @package       Cake.Controller.Component
 * @since         CakePHP(tm) v 0.10.0.1076
 * @license       http://www.opensource.org/licenses/mit-license.php MIT License
 */

App::uses('Component', 'Controller');


ERROR: UndefinedClass - lib/Cake/Controller/Component/AuthComponent.php:38:29 - Class, interface or enum named Component does not exist (see https://psalm.dev/019)
class AuthComponent extends Component {


------------------------------
2 errors found
------------------------------

Checks took 0.50 seconds and used 76.476MB of memory
Psalm was unable to infer types in the codebase
```

## Expected behaivior

I want that the case 1, just executing `psalm` success.

## Versions
```console
% php --version
PHP 8.1.15 (cli) (built: Feb  9 2023 18:15:32) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.1.15, Copyright (c) Zend Technologies
% psalm --version
Psalm 5.7.3@471a8c6a1d4f0dcf91fdb34a3109adb204012fb3
% php -i | grep memory_limit
memory_limit => -1 => -1
% uname -a
Darwin LESLIE-EX-MAC 22.2.0 Darwin Kernel Version 22.2.0: Fri Nov 11 02:03:51 PST 2022; root:xnu-8792.61.2~4/RELEASE_ARM64_T6000 arm64
% sw_vers
ProductName:		macOS
ProductVersion:		13.1
BuildVersion:		22C65
```

And I've installed PHP by [asdf php plugin](https://github.com/asdf-community/asdf-php).

**Comment by lens0021** [comment]
It was there were classes in the same name. One was in our code and one was as a vendor. I've added the vendor to `<ignoreFiles>`.
