### ISSUE TITLE
Uncaught RuntimeException: PHP Error: Undefined property: Psalm\Config::$config_warnings

### ISSUE THREAD

**Issue by dwasil** [vimeo/psalm#9423]
I've tried to use psalm.phar, (ver. 5.7.7) but got the error:

```$ ./tools/psalm ```

```Uncaught RuntimeException: PHP Error: Undefined property: Psalm\Config::$config_warnings in phar:///Users/******/repos/******/tools/psalm/src/Psalm/Internal/Cli/Psalm.php:410 for command with CLI args "./tools/psalm" in phar:///Users/******/repos/******/tools/psalm/src/Psalm/Internal/ErrorHandler.php:61
Stack trace:
#0 phar:///Users/******/repos/******/tools/psalm/src/Psalm/Internal/Cli/Psalm.php(410): Psalm\Internal\ErrorHandler::Psalm\Internal\{closure}(2, 'Undefined prope...', 'phar:///Users/v...', 410)
#1 phar:///Users/******/repos/******/tools/psalm/src/Psalm/Internal/Cli/Psalm.php(216): Psalm\Internal\Cli\Psalm::initProgress(Array, Object(Psalm\Config))
#2 phar:///Users/******/repos/******/tools/psalm/psalm(7): Psalm\Internal\Cli\Psalm::run(Array)
#3 /Users/******/repos/******/tools/psalm(14): require('phar:///Users/v...')
#4 {main}
(Psalm 5.7.7@e028ba46ba0d7f9a78bc3201c251e137383e145f crashed due to an uncaught Throwable)```

psalm.xml:

```<?xml version="1.0"?>
<psalm
    errorLevel="3"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns="https://getpsalm.org/schema/config"
    xsi:schemaLocation="https://getpsalm.org/schema/config vendor/vimeo/psalm/config.xsd"
    autoloader="./vendor/autoload.php"
    errorBaseline="psalm-baseline.xml"
>
</psalm>```

**Comment by dwasil** [comment]
> Hey @dwasil, can you reproduce the issue on https://psalm.dev ?

Unfortunately not. I need the access to cli for that))

**Comment by dwasil** [comment]
Why it was closed?

**Comment by weirdan** [comment]
This issue wasn't closed. What you see above your comment is a link *from a closed issue* where you mentioned this one.

**Comment by dwasil** [comment]
> This issue wasn't closed. What you see above your comment is a link _from a closed issue_ where you mentioned this one.

Thank you for the explanation :-)

**Comment by PurpleVsGreen** [comment]
[Here's the PR that created this bug.](https://github.com/vimeo/psalm/pull/9162/files#diff-20b00de237986e634ae4c11c7c5daada342880a20c8ab7bde29e91cc92b30a04)

**Comment by PurpleVsGreen** [comment]
This happens when running a version of psalm.phar in a composer-enabled project that's newer than the version of Psalm installed by composer.

The real bug is that apparently halfway through the process the composer autoloader takes precedence over the classes in the phar so that a version mismatch yields a franken-psalm that's half one version and half another.

To get around this, remove the psalm dependency from composer or change the version to match.

**Comment by jrfnl** [comment]
> This happens when running a version of psalm.phar in a composer-enabled project that's newer than the version of Psalm installed by composer.

@PurpleVsGreen Ha! Just ran into this on a project where I was trying to upgrade Psalm (and testing with the PHAR before updating in Composer). Thanks for your comment. That unblocked me.
