### ISSUE TITLE
Uncaught UnexpectedValueException: Storage for SimpleXMLElement::savexml is not user-defined

### ISSUE THREAD

**Issue by ADmad** [vimeo/psalm#963]
Getting error when trying to use the latest `.phar`.

```
$ psalm.phar -v
Psalm 2.0.10.0@366f625c83000a701ce0a69b8a05b387c7bf4bce
```
```
$ psalm.phar --init
Config file created successfully. Please re-run psalm.
```
```
$ psalm.phar
Scanning files...
Analyzing files...
PHP Fatal error:  Uncaught UnexpectedValueException: Storage for SimpleXMLElement::savexml is not user-defined in phar:///home/admad/bin/psalm.phar/src/Psalm/Codebase/Methods.php:336
Stack trace:
#0 phar:///home/admad/bin/psalm.phar/src/Psalm/Checker/Statements/Expression/Call/MethodCallChecker.php(369): _HumbugBox5b7319125e8ef\Psalm\Codebase\Methods->getUserMethodStorage('SimpleXMLElemen...')
#1 phar:///home/admad/bin/psalm.phar/src/Psalm/Checker/Statements/ExpressionChecker.php(81): _HumbugBox5b7319125e8ef\Psalm\Checker\Statements\Expression\Call\MethodCallChecker::analyze(Object(_HumbugBox5b7319125e8ef\Psalm\Checker\StatementsChecker), Object(_HumbugBox5b7319125e8ef\PhpParser\Node\Expr\MethodCall), Object(_HumbugBox5b7319125e8ef\Psalm\Context))
#2 phar:///home/admad/bin/psalm.phar/src/Psalm/Checker/Statements/Expression/CallChecker.php(314): _HumbugBox5b7319125e8ef\Psalm\Checker\Statements\ExpressionChecker::analyze(Object(_HumbugBox5b7319125e8ef\Psalm\Checker\StatementsChecker), Object(_HumbugBox5b7319125e8ef\PhpParser\Nod in phar:///home/admad/bin/psalm.phar/src/Psalm/Codebase/Methods.php on line 336

Fatal error: Uncaught UnexpectedValueException: Storage for SimpleXMLElement::savexml is not user-defined in phar:///home/admad/bin/psalm.phar/src/Psalm/Codebase/Methods.php:336
Stack trace:
#0 phar:///home/admad/bin/psalm.phar/src/Psalm/Checker/Statements/Expression/Call/MethodCallChecker.php(369): _HumbugBox5b7319125e8ef\Psalm\Codebase\Methods->getUserMethodStorage('SimpleXMLElemen...')
#1 phar:///home/admad/bin/psalm.phar/src/Psalm/Checker/Statements/ExpressionChecker.php(81): _HumbugBox5b7319125e8ef\Psalm\Checker\Statements\Expression\Call\MethodCallChecker::analyze(Object(_HumbugBox5b7319125e8ef\Psalm\Checker\StatementsChecker), Object(_HumbugBox5b7319125e8ef\PhpParser\Node\Expr\MethodCall), Object(_HumbugBox5b7319125e8ef\Psalm\Context))
#2 phar:///home/admad/bin/psalm.phar/src/Psalm/Checker/Statements/Expression/CallChecker.php(314): _HumbugBox5b7319125e8ef\Psalm\Checker\Statements\ExpressionChecker::analyze(Object(_HumbugBox5b7319125e8ef\Psalm\Checker\StatementsChecker), Object(_HumbugBox5b7319125e8ef\PhpParser\Nod in phar:///home/admad/bin/psalm.phar/src/Psalm/Codebase/Methods.php on line 336
```

**Comment by muglug** [comment]
Could you provide more info - where exactly does it fail?

You can use `--debug` and `--debug-by-line` to narrow down the culprit

**Comment by ADmad** [comment]
I ran `psalm.phar --debug` and the line right before the error is

```
Analyzing /srv/sites/cake-apps/cakephp/src/Command/HelpCommand.php
```

I am trying it on `4.x` branch of [cakephp/cakephp](https://github.com/cakephp/cakephp/tree/4.x) on PHP 7.1.

**Comment by weirdan** [comment]
Must be failing on this line then:

https://github.com/cakephp/cakephp/blob/4.x/src/Command/HelpCommand.php#L145

**Comment by ADmad** [comment]
Probably, but I would expect psalm to run without throwing fatal errors :slightly_smiling_face:.

**Comment by muglug** [comment]
I encountered a different fatal error running latest master against 4.x (fixed in https://github.com/vimeo/psalm/commit/3e69a333c9683596ad4a4325e0039374516295a0)

This issue was fixed in https://github.com/vimeo/psalm/commit/06917638031ade75292ac0fc2db6f006f9bdd320

**Comment by muglug** [comment]
`SimpleXMLElement::saveXML` is an alias of `SimpleXMLElement::asXML`, and presumably there's something funny happening around that. But the callmap entry seems to have remedied that particular bug.
