### ISSUE TITLE
Psalm crashed if there are multiple classes with the same name and different methods

### ISSUE THREAD

**Issue by max-matiukhin** [vimeo/psalm#971]
Hi
There are 2 files in the src/ directory:
a.php
```php
<?php
class A {
    function aa() {}
    function bb() { $this->aa(); }
}
```

b.php
```php
<?php
class A {
    function dd() {}
    function zz() { $this->dd(); }
}
```

When I run psalm on these files, it crashed:
```
$ ./vendor/bin/psalm --debug ./src/
Checking /projects/php/psalm/src
Scanning files...
Parsing /projects/php/psalm/src/b.php
Deep scanning /projects/php/psalm/src/b.php
ClassLikeStorage is populating
Have populated A
ClassLikeStorage is populated
FileStorage is populating
FileStorage is populated
Registering stub files
Scanning /projects/php/psalm/vendor/vimeo/psalm/src/Psalm/Stubs/CoreGenericFunctions.php
Scanning /projects/php/psalm/vendor/vimeo/psalm/src/Psalm/Stubs/CoreGenericClasses.php
Using reflection to get metadata for Exception
Using reflection to get metadata for Serializable
Using reflection to get metadata for Countable
Using reflection to locate file for callback
Using reflection to get metadata for SeekableIterator
Using reflection to get metadata for DOMNode
Using reflection to get metadata for Throwable
ClassLikeStorage is populating
Have populated Traversable
Have populated IteratorAggregate
Have populated Iterator
Have populated Generator
Have populated ArrayAccess
Have populated Serializable
Have populated Countable
Have populated ArrayObject
Have populated SeekableIterator
Have populated ArrayIterator
Have populated DOMNode
Have populated DOMElement
Have populated DOMNodeList
ClassLikeStorage is populated
FileStorage is populating
FileStorage is populated
Finished registering stub files
Analyzing files...
Getting /projects/php/psalm/src/a.php
Analyzing /projects/php/psalm/src/a.php
Parsing /projects/php/psalm/src/a.php
Getting /projects/php/psalm/src/b.php
Analyzing /projects/php/psalm/src/b.php
PHP Fatal error:  Uncaught UnexpectedValueException: $storage should not be null for A::dd in /projects/php/psalm/vendor/vimeo/psalm/src/Psalm/Codebase/Methods.php:469
Stack trace:
#0 /projects/php/psalm/vendor/vimeo/psalm/src/Psalm/Checker/FunctionLikeChecker.php(156): Psalm\Codebase\Methods->getStorage('A::dd')
#1 /projects/php/psalm/vendor/vimeo/psalm/src/Psalm/Checker/ClassChecker.php(882): Psalm\Checker\FunctionLikeChecker->analyze(Object(Psalm\Context), Object(Psalm\Context))
#2 /projects/php/psalm/vendor/vimeo/psalm/src/Psalm/Checker/ClassChecker.php(404): Psalm\Checker\ClassChecker->analyzeClassMethod(Object(PhpParser\Node\Stmt\ClassMethod), Object(Psalm\Storage\ClassLikeStorage), Object(Psalm\Checker\ClassChecker), Object(Psalm\Context), Object(Psalm\Context))
#3 /projects/php/psalm/vendor/vimeo/psalm/src/Psalm/Checker/FileChecker.php(142): Psalm\Checker\ClassChecker->analyze(Object(Psalm\Context), Object(Psalm\Context))
#4 /projects/php/psalm/vendor/vimeo/psalm/src/Psalm/Codebase/Analyzer.php(149): Psalm\Checker\File in /projects/php/psalm/vendor/vimeo/psalm/src/Psalm/Codebase/Methods.php on line 469

Fatal error: Uncaught UnexpectedValueException: $storage should not be null for A::dd in /projects/php/psalm/vendor/vimeo/psalm/src/Psalm/Codebase/Methods.php:469
Stack trace:
#0 /projects/php/psalm/vendor/vimeo/psalm/src/Psalm/Checker/FunctionLikeChecker.php(156): Psalm\Codebase\Methods->getStorage('A::dd')
#1 /projects/php/psalm/vendor/vimeo/psalm/src/Psalm/Checker/ClassChecker.php(882): Psalm\Checker\FunctionLikeChecker->analyze(Object(Psalm\Context), Object(Psalm\Context))
#2 /projects/php/psalm/vendor/vimeo/psalm/src/Psalm/Checker/ClassChecker.php(404): Psalm\Checker\ClassChecker->analyzeClassMethod(Object(PhpParser\Node\Stmt\ClassMethod), Object(Psalm\Storage\ClassLikeStorage), Object(Psalm\Checker\ClassChecker), Object(Psalm\Context), Object(Psalm\Context))
#3 /projects/php/psalm/vendor/vimeo/psalm/src/Psalm/Checker/FileChecker.php(142): Psalm\Checker\ClassChecker->analyze(Object(Psalm\Context), Object(Psalm\Context))
#4 /projects/php/psalm/vendor/vimeo/psalm/src/Psalm/Codebase/Analyzer.php(149): Psalm\Checker\File in /projects/php/psalm/vendor/vimeo/psalm/src/Psalm/Codebase/Methods.php on line 469
```

I undersatand that it is difficult to analyse such codebase, but it would be great not crash, just warn about it :)

**Comment by muglug** [comment]
Thanks! Psalm isn't really designed to handle duplicate classes, but I've made it cope a little better
