### ISSUE TITLE
inaccurate phpdoc can crash psalm

### ISSUE THREAD

**Issue by max-matiukhin** [vimeo/psalm#974]
Hi,
here is my code: https://getpsalm.org/r/8e17ee6244
It results with uncaught exception

```
$ ./vendor/bin/psalm --debug src/
Checking /projects/php/psalm_tst/src
Scanning files...
Parsing /projects/php/psalm_tst/src/a.php
Deep scanning /projects/php/psalm_tst/src/a.php
PHP Fatal error:  Uncaught InvalidArgumentException: Unrecognised parse tree type Psalm\Type\ParseTree\MethodTree in /projects/php/psalm_tst/vendor/vimeo/psalm/src/Psalm/Type.php:410
Stack trace:
#0 /projects/php/psalm_tst/vendor/vimeo/psalm/src/Psalm/Type.php(119): Psalm\Type::getTypeFromTree(Object(Psalm\Type\ParseTree\MethodTree), false, Array)
#1 /projects/php/psalm_tst/vendor/vimeo/psalm/src/Psalm/Visitor/DependencyFinderVisitor.php(1294): Psalm\Type::parseTokens(Array, false, Array)
#2 /projects/php/psalm_tst/vendor/vimeo/psalm/src/Psalm/Visitor/DependencyFinderVisitor.php(235): Psalm\Visitor\DependencyFinderVisitor->registerFunctionLike(Object(PhpParser\Node\Stmt\ClassMethod))
#3 /projects/php/psalm_tst/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(181): Psalm\Visitor\DependencyFinderVisitor->enterNode(Object(PhpParser\Node\Stmt\ClassMethod))
#4 /projects/php/psalm_tst/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(108): PhpParser\NodeTraverser->traverseArray(Array)
#5 /projects/php/psalm_tst/vendor/n in /projects/php/psalm_tst/vendor/vimeo/psalm/src/Psalm/Type.php on line 410

Fatal error: Uncaught InvalidArgumentException: Unrecognised parse tree type Psalm\Type\ParseTree\MethodTree in /projects/php/psalm_tst/vendor/vimeo/psalm/src/Psalm/Type.php:410
Stack trace:
#0 /projects/php/psalm_tst/vendor/vimeo/psalm/src/Psalm/Type.php(119): Psalm\Type::getTypeFromTree(Object(Psalm\Type\ParseTree\MethodTree), false, Array)
#1 /projects/php/psalm_tst/vendor/vimeo/psalm/src/Psalm/Visitor/DependencyFinderVisitor.php(1294): Psalm\Type::parseTokens(Array, false, Array)
#2 /projects/php/psalm_tst/vendor/vimeo/psalm/src/Psalm/Visitor/DependencyFinderVisitor.php(235): Psalm\Visitor\DependencyFinderVisitor->registerFunctionLike(Object(PhpParser\Node\Stmt\ClassMethod))
#3 /projects/php/psalm_tst/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(181): Psalm\Visitor\DependencyFinderVisitor->enterNode(Object(PhpParser\Node\Stmt\ClassMethod))
#4 /projects/php/psalm_tst/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(108): PhpParser\NodeTraverser->traverseArray(Array)
#5 /projects/php/psalm_tst/vendor/n in /projects/php/psalm_tst/vendor/vimeo/psalm/src/Psalm/Type.php on line 410
```

**Comment by weirdan** [comment]
Seen similar issue with missing import for Closure:
```php
<?php
namespace NS1;
/** @var Closure():int */
```
https://getpsalm.org/r/d2c05d167a

**Comment by muglug** [comment]
Thanks!
