### ISSUE TITLE
Bad cache directory when HOME is not set

### ISSUE THREAD

**Issue by AndreyMZ** [vimeo/psalm#9800]
### Problem description

The documentation <https://psalm.dev/docs/running_psalm/configuration/#cachedirectory> says:
> Defaults to `$XDG_CACHE_HOME/psalm`. If `$XDG_CACHE_HOME` is either not set or empty, a default equal to `$HOME/.cache/psalm` is used **or `sys_get_temp_dir() . '/psalm'` when not defined**.

This is wrong. Actually the cache directory never equals to `sys_get_temp_dir() . '/psalm'`. If `$HOME` is not set or empty, then the directory equals to `//.cache/psalm`, and Psalm most probably crashes with a permission denied exception like this:
```
Uncaught RuntimeException: PHP Error: mkdir(): Permission denied in /opt/psalm/vendor/vimeo/psalm/src/Psalm/Config.php:2324 for command with CLI args "/opt/psalm/vendor/bin/psalm --taint-analysis --long-progress --config=/psalm.xml" in /opt/psalm/vendor/vimeo/psalm/src/Psalm/Internal/ErrorHandler.php:75
Stack trace:
#0 [internal function]: Psalm\Internal\ErrorHandler::Psalm\Internal\{closure}(2, 'mkdir(): Permis...', '/opt/psalm/vend...', 2324, Array)
#1 /opt/psalm/vendor/vimeo/psalm/src/Psalm/Config.php(2324): mkdir('//.cache/psalm/...', 511, true)
#2 /opt/psalm/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/ProjectAnalyzer.php(280): Psalm\Config->getCacheDirectory()
#3 /opt/psalm/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/ProjectAnalyzer.php(237): Psalm\Internal\Analyzer\ProjectAnalyzer->clearCacheDirectoryIfConfigOrComposerLockfileChanged()
#4 /opt/psalm/vendor/vimeo/psalm/src/Psalm/Internal/Cli/Psalm.php(336): Psalm\Internal\Analyzer\ProjectAnalyzer->__construct(Object(Psalm\Config), Object(Psalm\Internal\Provider\Providers), Object(Psalm\Report\ReportOptions), Array, 7, Object(Psalm\Progress\LongProgress))
#5 /opt/psalm/vendor/vimeo/psalm/psalm(8): Psalm\Internal\Cli\Psalm::run(Array)
#6 /opt/psalm/vendor/bin/psalm(115): include('/opt/psalm/vend...')
#7 {main}
(Psalm 5.11.0@c9b192ab8400fdaf04b2b13d110575adc879aa90 crashed due to an uncaught Throwable)
```

### Additional information

The same result is when `$HOME` is set to `/`. E.g. this is the case when one runs a container with the `--user` argument:
~~~
$ docker run --user 1000:1000 debian env
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
HOSTNAME=1eba5624d322
TERM=xterm
HOME=/
~~~

Workaround:
~~~
docker run --user 1000:1000 --env "HOME=/home/mGfUcvD6kfBy" --mount "type=tmpfs,destination=/home/mGfUcvD6kfBy" debian env
~~~

### Root cause

https://github.com/vimeo/psalm/blob/0221ff1836e5a682626692530a82608188916165/src/Psalm/Config.php#L1176-L1182

The "else" clause is a dead code, because `Xdg.getHomeCacheDir` never returns a falsy value, see 
- [`‎Xdg.getHomeCacheDir`](https://github.com/dnoegel/php-xdg-base-dir/blob/12f5b94710c8f5b504432d57ce353075fc434339/src/Xdg.php#L78-L84)
- [`Xdg.getHomeDir`](https://github.com/dnoegel/php-xdg-base-dir/blob/12f5b94710c8f5b504432d57ce353075fc434339/src/Xdg.php#L20-L23)

### Possible solution

Do not use [dnoegel/php-xdg-base-dir](https://github.com/dnoegel/php-xdg-base-dir), because it is buggy.

~~~php
function join_path(string ...$segments): string {
    return join(DIRECTORY_SEPARATOR, $segments);
}

function getHomeDir(): string|false {
    if ('PHP_OS_FAMILY' === 'Windows') {
        $drive = getenv('HOMEDRIVE');
        $path  = getenv('HOMEPATH');
        return ($drive && $path ? join_path($drive, $path) : false);
    } else {
        return getenv('HOME') ?: false;
    }
}

function getTemporaryDir(string $prefix = ''): string {
    $path = tempnam(sys_get_temp_dir(), $prefix);
    if (unlink($path) === false || mkdir($path, 0700) === false) {
        throw new Exception("Cannot create a temporary directory: $path");
    }
    return $path;
}

function getCacheHomeDir(): string {
    if ($cache_home = getenv('XDG_CACHE_HOME')) {
        return $cache_home;
    } elseif (($home = getHomeDir()) !== false && $home !== '/') {
        return join_path($home, '.cache');
    } else {
        return getTemporaryDir();
    }
}

if (isset($config_xml['cacheDirectory'])) {
    $config->cache_directory = (string)$config_xml['cacheDirectory'];
} else {
    $config->cache_directory = join_path(getCacheHomeDir(), 'psalm');
} 
~~~

**Comment by orklah** [comment]
Seems you have this figured it out. Mind making a PR to fix that?
