### ISSUE TITLE
Exception thrown on init `psalm --init ` [PHP 8.2, Psalm 5.8.0]

### ISSUE THREAD

**Issue by sa-tasche** [vimeo/psalm#9863]
Exception thrown on init `psalm --init .` (without composer).

```
Target PHP version: 8.2 (inferred from current PHP version).
Scanning files...
Uncaught RuntimeException: Failed to infer case value for Removed in phar://D:/Development/PHP/__Dev/psalm.phar/src/Psalm/Internal/PhpVisitor/Reflector/ClassLikeNodeScanner.php:793
Stack trace:
#0 phar://D:/Development/PHP/__Dev/psalm.phar/src/Psalm/Internal/PhpVisitor/Reflector/ClassLikeNodeScanner.php(435): Psalm\Internal\PhpVisitor\Reflector\ClassLikeNodeScanner->visitEnumDeclaration(Object(_HumbugBoxcec0369c4b7c\PhpParser\Node\Stmt\EnumCase), Object(Psalm\Storage\ClassLikeStorage), 'mitgedanken\\Uti...')
#1 phar://D:/Development/PHP/__Dev/psalm.phar/src/Psalm/Internal/PhpVisitor/ReflectorVisitor.php(118): Psalm\Internal\PhpVisitor\Reflector\ClassLikeNodeScanner->start(Object(_HumbugBoxcec0369c4b7c\PhpParser\Node\Stmt\Enum_))
#2 phar://D:/Development/PHP/__Dev/psalm.phar/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(176): Psalm\Internal\PhpVisitor\ReflectorVisitor->enterNode(Object(_HumbugBoxcec0369c4b7c\PhpParser\Node\Stmt\Enum_))
#3 phar://D:/Development/PHP/__Dev/psalm.phar/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(105): _HumbugBoxcec0369c4b7c\PhpParser\NodeTraverser->traverseArray(Array)
#4 phar://D:/Development/PHP/__Dev/psalm.phar/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(196): _HumbugBoxcec0369c4b7c\PhpParser\NodeTraverser->traverseNode(Object(_HumbugBoxcec0369c4b7c\PhpParser\Node\Stmt\Namespace_))
#5 phar://D:/Development/PHP/__Dev/psalm.phar/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(85): _HumbugBoxcec0369c4b7c\PhpParser\NodeTraverser->traverseArray(Array)
#6 phar://D:/Development/PHP/__Dev/psalm.phar/src/Psalm/Internal/Scanner/FileScanner.php(51): _HumbugBoxcec0369c4b7c\PhpParser\NodeTraverser->traverse(Array)
#7 phar://D:/Development/PHP/__Dev/psalm.phar/src/Psalm/Internal/Codebase/Scanner.php(398): Psalm\Internal\Scanner\FileScanner->scan(Object(Psalm\Codebase), Object(Psalm\Storage\FileStorage), false, Object(anner->scanFiles(Object(Psalm\Internal\Codebase\ClassLikes), 1)
#12 phar://D:/Development/PHP/__Dev/psalm.phar/src/Psalm/Internal/Analyzer/ProjectAnalyzer.php(751): Psalm\Codebase->scanFiles(1)
#13 phar://D:/Development/PHP/__Dev/psalm.phar/src/Psalm/Internal/Cli/Psalm.php(277): Psalm\Internal\Analyzer\ProjectAnalyzer->checkPaths(Array)
#14 phar://D:/Development/PHP/__Dev/psalm.phar/psalm(7): Psalm\Internal\Cli\Psalm::run(Array)
#15 D:\Development\PHP\__Dev\psalm.phar(14): require('phar://D:/Devel...')
#16 {main}
(Psalm 5.8.0@9cf4f60a333f779ad3bc704a555920e81d4fdcda crashed due to an uncaught Throwable)
```

**Comment by weirdan** [comment]
This is likely a duplicate of #8978
