### ISSUE TITLE
psalter throws errors

### ISSUE THREAD

**Issue by ADmad** [vimeo/psalm#995]
Tried using `psalter` 
```
vendor/bin/psalter --php-version=7.1 --debug --dry-run --issues=MissingReturnType,MissingClosureReturnType,InvalidReturnType,InvalidNullableReturnType,InvalidFalsableReturnType,MismatchingDocblockParamType,MismatchingDocblockReturnType,LessSpecificReturnType,PossiblyUndefinedVariable
```

on `4.x` branch of [cakephp/cakephp](https://github.com/cakephp/cakephp/tree/4.x), ended up with following error.

```
......
Analyzing /mypath/cakephp/src/I18n/TranslatorRegistry.php
PHP Fatal error:  Uncaught UnexpectedValueException: Param type must not be null in /mypath/cakephp/vendor/vimeo/psalm/src/Psalm/Type/Atomic/CallableTrait.php:76
Stack trace:
#0 [internal function]: Psalm\Type\Atomic\Fn->Psalm\Type\Atomic\{closure}(Object(Psalm\Storage\FunctionLikeParameter))
#1 /mypath/cakephp/vendor/vimeo/psalm/src/Psalm/Type/Atomic/CallableTrait.php(88): array_map(Object(Closure), Array)
#2 /mypath/cakephp/vendor/vimeo/psalm/src/Psalm/Type/Atomic/TNamedObject.php(120): Psalm\Type\Atomic\Fn->toNamespacedString('Cake\\I18n', Array, 'Cake\\I18n\\Trans...', false)
#3 /mypath/cakephp/vendor/vimeo/psalm/src/Psalm/Type/Union.php(344): Psalm\Type\Atomic\TNamedObject->toPhpString('Cake\\I18n', Array, 'Cake\\I18n\\Trans...', 7, 1)
#4 /mypath/cakephp/vendor/vimeo/psalm/src/Psalm/Checker/FunctionLike/ReturnTypeChecker.php(676): Psalm\Type\Union->toPhpString('Cake\\I18n', Array, 'Cake\\I18n\\Trans...', 7, 1)
#5 /mypath/cakephp/vendor/vimeo/psa in /mypath/cakephp/vendor/vimeo/psalm/src/Psalm/Type/Atomic/CallableTrait.php on line 76

Fatal error: Uncaught UnexpectedValueException: Param type must not be null in /mypath/cakephp/vendor/vimeo/psalm/src/Psalm/Type/Atomic/CallableTrait.php:76
Stack trace:
#0 [internal function]: Psalm\Type\Atomic\Fn->Psalm\Type\Atomic\{closure}(Object(Psalm\Storage\FunctionLikeParameter))
#1 /mypath/cakephp/vendor/vimeo/psalm/src/Psalm/Type/Atomic/CallableTrait.php(88): array_map(Object(Closure), Array)
#2 /mypath/cakephp/vendor/vimeo/psalm/src/Psalm/Type/Atomic/TNamedObject.php(120): Psalm\Type\Atomic\Fn->toNamespacedString('Cake\\I18n', Array, 'Cake\\I18n\\Trans...', false)
#3 /mypath/cakephp/vendor/vimeo/psalm/src/Psalm/Type/Union.php(344): Psalm\Type\Atomic\TNamedObject->toPhpString('Cake\\I18n', Array, 'Cake\\I18n\\Trans...', 7, 1)
#4 /mypath/cakephp/vendor/vimeo/psalm/src/Psalm/Checker/FunctionLike/ReturnTypeChecker.php(676): Psalm\Type\Union->toPhpString('Cake\\I18n', Array, 'Cake\\I18n\\Trans...', 7, 1)
#5 /mypath/cakephp/vendor/vimeo/psa in /mypath/cakephp/vendor/vimeo/psalm/src/Psalm/Type/Atomic/CallableTrait.php on line 76
```

**Comment by muglug** [comment]
Thanks!

I noticed https://github.com/vimeo/psalm/issues/996 while fixing which reflects a certain paucity of documentation in the codebase that Psalter was tested on.

**Comment by ADmad** [comment]
Thanks for the quick fix. BTW can psalter be used without installing it through composer?

**Comment by muglug** [comment]
at the moment, no

**Comment by ADmad** [comment]
No problem, I can live with that for now :)

**Comment by muglug** [comment]
And latest master has the fix for return type comment killing
