### ISSUE TITLE
The phar fails with an exception during config validation

### ISSUE THREAD

**Issue by stof** [vimeo/psalm#9951]
1. clone https://github.com/async-aws/aws at commit https://github.com/async-aws/aws/commit/ed7033600341a9b3f3113187bf64933df371b0ad (or create a project with a similar config file)
2. *Don't* install Psalm with composer in that project
3. Download the phar from https://github.com/vimeo/psalm/releases/tag/5.12.0
4. Run the phar in the project

Here is the output:

```
Uncaught RuntimeException: PHP Error: DOMDocument::schemaValidate(): Invalid Schema in phar://<redacted>/psalm.phar/src/Psalm/Config.php:652 for command with CLI args "<redacted>/psalm.phar" in phar://<redacted>/psalm.phar/src/Psalm/Internal/ErrorHandler.php:61
Stack trace:
#0 [internal function]: Psalm\Internal\ErrorHandler::Psalm\Internal\{closure}()
#1 phar://<redacted>/psalm.phar/src/Psalm/Config.php(652): DOMDocument->schemaValidate()
#2 phar://<redacted>/psalm.phar/src/Psalm/Config.php(608): Psalm\Config::validateXmlConfig()
#3 phar://<redacted>/psalm.phar/src/Psalm/Config.php(582): Psalm\Config::loadFromXML()
#4 phar://<redacted>/psalm.phar/src/Psalm/Config.php(543): Psalm\Config::loadFromXMLFile()
#5 phar://<redacted>/psalm.phar/src/Psalm/Internal/CliUtils.php(262): Psalm\Config::getConfigForPath()
#6 phar://<redacted>/psalm.phar/src/Psalm/Internal/Cli/Psalm.php(384): Psalm\Internal\CliUtils::initializeConfig()
#7 phar://<redacted>/psalm.phar/src/Psalm/Internal/Cli/Psalm.php(674): Psalm\Internal\Cli\Psalm::loadConfig()
#8 phar://<redacted>/psalm.phar/src/Psalm/Internal/Cli/Psalm.php(206): Psalm\Internal\Cli\Psalm::initConfig()
#9 phar://<redacted>/psalm.phar/psalm(7): Psalm\Internal\Cli\Psalm::run()
#10 <redacted>/psalm.phar(14): require('...')
#11 {main}
(Psalm 5.11.0@c9b192ab8400fdaf04b2b13d110575adc879aa90 crashed due to an uncaught Throwable)
```

If you install `vimeo/psalm` with composer, running the phar works fine (probably because it loads the Config class from the vendor folder and not from the phar)

**Comment by stof** [comment]
No I cannot, as it impacts only the phar.

**Comment by weirdan** [comment]
I was unable to reproduce the issue using the provided steps.

I:
1. cloned the repo
2. checked out commit ed7033600341a9b3f3113187bf64933df371b0ad
3. ran `composer install --no-dev`
4. downloaded 5.12 phar
5. ran the phar and observed no crash
